///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Травы"
o.display_page_description[1] = "Камень/Дерево"
o.display_page_description[2] = "Камни"
o.display_page_description[3] = "Спуски"
o.display_page_description[4] = "Декор"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Трава 1"
o.display_description_item[o.display_page_one,1] = "Трава 2"
o.display_description_item[o.display_page_one,2] = "Трава 3"
o.display_description_item[o.display_page_one,3] = "Земля 1"
o.display_description_item[o.display_page_one,4] = "Земля 2"
o.display_description_item[o.display_page_one,5] = "Земля 3"
o.display_description_item[o.display_page_one,6] = "Трава 4"
o.display_description_item[o.display_page_one,7] = "Трава 5"
o.display_description_item[o.display_page_one,8] = "Трава 6"
o.display_description_item[o.display_page_one,9] = "Трава 7"
o.display_description_item[o.display_page_one,10] = "Трава 8"
o.display_description_item[o.display_page_one,11] = "Трава 9"
o.display_description_item[o.display_page_one,12] = "Трава 10"
o.display_description_item[o.display_page_one,13] = "Трава 11"
o.display_description_item[o.display_page_one,14] = "Трава 12"
o.display_description_item[o.display_page_one,15] = "Трава 13"
o.display_description_item[o.display_page_one,16] = "Трава 14"
o.display_description_item[o.display_page_one,17] = "Трава 15"
o.display_description_item[o.display_page_one,18] = "Уголок Травы 1"
o.display_description_item[o.display_page_one,19] = "Уголок Травы 2"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Камень 1"
o.display_description_item[o.display_page_two,1] = "Камень 2"
o.display_description_item[o.display_page_two,2] = "Камень 3"
o.display_description_item[o.display_page_two,3] = "Камень 4"
o.display_description_item[o.display_page_two,4] = "Камень 5"
o.display_description_item[o.display_page_two,5] = "Камень 6"
o.display_description_item[o.display_page_two,6] = "Камень 7"
o.display_description_item[o.display_page_two,7] = "Камень 8"
o.display_description_item[o.display_page_two,8] = "Ветка 1"
o.display_description_item[o.display_page_two,9] = "Ветка 2"
o.display_description_item[o.display_page_two,10] = "Ветка 3"
o.display_description_item[o.display_page_two,11] = "Ветка 4"
o.display_description_item[o.display_page_two,12] = "Ветка 5"
o.display_description_item[o.display_page_two,13] = "Ветка 6"
o.display_description_item[o.display_page_two,14] = "Ствол Дерева Маленький"
o.display_description_item[o.display_page_two,15] = "Стебель Растения"
o.display_description_item[o.display_page_two,16] = "Цветок Растения"
o.display_description_item[o.display_page_two,17] = ""
o.display_description_item[o.display_page_two,18] = "Уголок Травы 3"
o.display_description_item[o.display_page_two,19] = "Уголок Травы 4"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Каменная Поверхность 1"
o.display_description_item[o.display_page_three,1] = "Каменная Поверхность 2"
o.display_description_item[o.display_page_three,2] = "Каменная Поверхность 3"
o.display_description_item[o.display_page_three,3] = "Каменная Поверхность 4"
o.display_description_item[o.display_page_three,4] = "Каменная Поверхность 5"
o.display_description_item[o.display_page_three,5] = "Каменная Поверхность 6"
o.display_description_item[o.display_page_three,6] = "Каменная Стена 1"
o.display_description_item[o.display_page_three,7] = "Каменная Стена 2"
o.display_description_item[o.display_page_three,8] = "Каменная Стена 3"
o.display_description_item[o.display_page_three,9] = "Каменная Стена 4"
o.display_description_item[o.display_page_three,10] = "Каменная Стена 5"
o.display_description_item[o.display_page_three,11] = "Каменная Стена 6"
o.display_description_item[o.display_page_three,12] = "Заросший Мост"
o.display_description_item[o.display_page_three,13] = ""
o.display_description_item[o.display_page_three,14] = ""
o.display_description_item[o.display_page_three,15] = ""
o.display_description_item[o.display_page_three,16] = ""
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Каменный Спуск 1"
o.display_description_item[o.display_page_four,1] = "Каменный Спуск 2"
o.display_description_item[o.display_page_four,2] = "Древесный Спуск 1"
o.display_description_item[o.display_page_four,3] = "Древесный Спуск 2"
o.display_description_item[o.display_page_four,4] = ""
o.display_description_item[o.display_page_four,5] = ""
o.display_description_item[o.display_page_four,6] = ""
o.display_description_item[o.display_page_four,7] = "Каменный Спуск 3"
o.display_description_item[o.display_page_four,8] = "Каменный Спуск 4"
o.display_description_item[o.display_page_four,9] = "Древесный Спуск 3"
o.display_description_item[o.display_page_four,10] = "Древесный Спуск 4"
o.display_description_item[o.display_page_four,11] = ""
o.display_description_item[o.display_page_four,12] = ""
o.display_description_item[o.display_page_four,13] = ""
o.display_description_item[o.display_page_four,14] = ""
o.display_description_item[o.display_page_four,15] = ""
o.display_description_item[o.display_page_four,16] = ""
o.display_description_item[o.display_page_four,17] = ""
o.display_description_item[o.display_page_four,18] = ""
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Поручень"
o.display_description_item[o.display_page_five,1] = "Фонарь 1"
o.display_description_item[o.display_page_five,2] = "Фонарь 2"
o.display_description_item[o.display_page_five,3] = "Цветок"
o.display_description_item[o.display_page_five,4] = "Заросций Колодец"
o.display_description_item[o.display_page_five,5] = "Саженец"
o.display_description_item[o.display_page_five,6] = "Корень Дерева"
o.display_description_item[o.display_page_five,7] = "Стебель Растения"
o.display_description_item[o.display_page_five,8] = "Часть Дракона 1"
o.display_description_item[o.display_page_five,9] = "Часть Дракона 2"
o.display_description_item[o.display_page_five,10] = "Часть Дракона 3"
o.display_description_item[o.display_page_five,11] = "Часть Дракона 4"
o.display_description_item[o.display_page_five,12] = "Растительность Задний Фон"
o.display_description_item[o.display_page_five,13] = "Кусок Растительности"
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = ""
o.display_description_item[o.display_page_six,1] = ""
o.display_description_item[o.display_page_six,2] = ""
o.display_description_item[o.display_page_six,3] = ""
o.display_description_item[o.display_page_six,4] = ""
o.display_description_item[o.display_page_six,5] = ""
o.display_description_item[o.display_page_six,6] = ""
o.display_description_item[o.display_page_six,7] = ""
o.display_description_item[o.display_page_six,8] = ""
o.display_description_item[o.display_page_six,9] = ""
o.display_description_item[o.display_page_six,10] = ""
o.display_description_item[o.display_page_six,11] = ""
o.display_description_item[o.display_page_six,12] = ""
o.display_description_item[o.display_page_six,13] = ""
o.display_description_item[o.display_page_six,14] = ""
o.display_description_item[o.display_page_six,15] = ""
o.display_description_item[o.display_page_six,16] = ""
o.display_description_item[o.display_page_six,17] = ""
o.display_description_item[o.display_page_six,18] = ""
o.display_description_item[o.display_page_six,19] = ""
