///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Земля/Глина"
o.display_page_description[1] = "Спуски 1"
o.display_page_description[2] = "Спуски 2"
o.display_page_description[3] = "Декор"
o.display_page_description[4] = "???"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Земля 1"
o.display_description_item[o.display_page_one,1] = "Земля 2"
o.display_description_item[o.display_page_one,2] = "Земля 3"
o.display_description_item[o.display_page_one,3] = "Земля 4"
o.display_description_item[o.display_page_one,4] = "Земля 5"
o.display_description_item[o.display_page_one,5] = "Земля 6"
o.display_description_item[o.display_page_one,6] = "Земля 7"
o.display_description_item[o.display_page_one,7] = "Земля 8"
o.display_description_item[o.display_page_one,8] = "Земля 9"
o.display_description_item[o.display_page_one,9] = "Длмнный Мост"
o.display_description_item[o.display_page_one,10] = "Короткий Мост"
o.display_description_item[o.display_page_one,11] = ""
o.display_description_item[o.display_page_one,12] = ""
o.display_description_item[o.display_page_one,13] = ""
o.display_description_item[o.display_page_one,14] = ""
o.display_description_item[o.display_page_one,15] = ""
o.display_description_item[o.display_page_one,16] = ""
o.display_description_item[o.display_page_one,17] = ""
o.display_description_item[o.display_page_one,18] = ""
o.display_description_item[o.display_page_one,19] = ""

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Земляная Рампа Левая"
o.display_description_item[o.display_page_two,1] = "Земляная Рампа Правая"
o.display_description_item[o.display_page_two,2] = "Каменная Рампа Левая"
o.display_description_item[o.display_page_two,3] = "Каменная Рампа Правая"
o.display_description_item[o.display_page_two,4] = "Каменный Спуск 1"
o.display_description_item[o.display_page_two,5] = "Каменный Спуск 2"
o.display_description_item[o.display_page_two,6] = ""
o.display_description_item[o.display_page_two,7] = "Узкая Петля 1"
o.display_description_item[o.display_page_two,8] = "Узкая Петля 2"
o.display_description_item[o.display_page_two,9] = "Каменная Петля 1"
o.display_description_item[o.display_page_two,10] = "Каменная Петля 2"
o.display_description_item[o.display_page_two,11] = "Каменная Круговая Петля 1"
o.display_description_item[o.display_page_two,12] = "Каменная Круговая Петля 2"
o.display_description_item[o.display_page_two,13] = "Узкая Петля 3"
o.display_description_item[o.display_page_two,14] = "Узкая Петля 4"
o.display_description_item[o.display_page_two,15] = "Каменная Петля 3"
o.display_description_item[o.display_page_two,16] = "Каменная Петля 4"
o.display_description_item[o.display_page_two,17] = "Каменная Круговая Петля 3"
o.display_description_item[o.display_page_two,18] = "Каменная Круговая Петля 3"
o.display_description_item[o.display_page_two,19] = ""

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Глиняная Насыпь 1"
o.display_description_item[o.display_page_three,1] = "Трава 1"
o.display_description_item[o.display_page_three,2] = "Глиняная Насыпь 2"
o.display_description_item[o.display_page_three,3] = "Глиняная Насыпь 3"
o.display_description_item[o.display_page_three,4] = "Глиняная Насыпь 4"
o.display_description_item[o.display_page_three,5] = "Глиняная Насыпь 5"
o.display_description_item[o.display_page_three,6] = "Каменная Арка 1"
o.display_description_item[o.display_page_three,7] = "Каменная Арка 2"
o.display_description_item[o.display_page_three,8] = "Каменная Арка 3"
o.display_description_item[o.display_page_three,9] = ""
o.display_description_item[o.display_page_three,10] = ""
o.display_description_item[o.display_page_three,11] = ""
o.display_description_item[o.display_page_three,12] = ""
o.display_description_item[o.display_page_three,13] = ""
o.display_description_item[o.display_page_three,14] = ""
o.display_description_item[o.display_page_three,15] = ""
o.display_description_item[o.display_page_three,16] = ""
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""
