//For calling in Story Mode object only, call BEFORE NPC spawn scripts
//Language Array; 0 = English; 1 = Portuguese; 2 = Polish; 3 = Spanish; 4 = German; 5 = Russian
var lang_num = 1;
//West District NPCs 1
lang_npc[lang_num,0]  = "É! Essas coisinhas tá difícil de levar nos lugar!"  //Clyde
lang_npc[lang_num,1]  = "Por isso meus dente tá tudo quebrado, heh!"         //Clyde
lang_npc[lang_num,2]  = "Com toda essa saudade de casa, senti falta dos trem!" //Bucky
lang_npc[lang_num,3]  = "Me lembra dos dia de emu wrestling!"                //Bucky
lang_npc[lang_num,4]  = "Desculpaa, #Chiasa! Eu estava com fome!"            //Marshmallow
lang_npc[lang_num,5]  = "Eu vou compartilhar com você!"                      //Marshmallow
lang_npc[lang_num,6]  = "Não entendo... a onde foi tudo mundo?"              //Candy
lang_npc[lang_num,7]  = "Bem, caso você não tinha percebido!"                //Allister
lang_npc[lang_num,8]  = "Tem um *tanque* atravessando a cidade agora mesmo!" //Allister
lang_npc[lang_num,9]  = "O que estamos esperando?! Tá na hora da AÇÃO!"      //Jett
lang_npc[lang_num,10] = "Eles *realmente* colocaram uma parede de tijolos?"  //Trip
lang_npc[lang_num,11] = "Grr..."                                             //Axl
lang_npc[lang_num,12] = "Aquele tanque destruiu a Ponte do Leste!"           //Lilac
lang_npc[lang_num,13] = "Não podemos ficar parado aqui..."                   //Lilac
lang_npc[lang_num,14] = "Queria um lanchinho antes da gente sair, mas..."    //Carol
lang_npc[lang_num,15] = "Aqueles barulhos vindo de lá... eu estou bem agora!" //Carol
lang_npc[lang_num,16] = "*barulhos nojentos de guaxinim*"                    //Trash Can
lang_npc[lang_num,17] = "Ou jovem! Me deixa comer um muffler fresco em paz!" //Trash Can
lang_npc[lang_num,18] = "O lanche dessa senhorita são estranhos! Eu comi um..." //Libbie Dark
lang_npc[lang_num,19] = "É uma nuvem pequenina apareceu acima da minha cabeça!" //Libbie Dark
lang_npc[lang_num,20] = "Quem disse que você não pode comprar um segundo lanche?" //Tiwi
lang_npc[lang_num,21] = "Quem tem vontade de comer bananas frescas?"         //Harige
lang_npc[lang_num,22] = "É bem comum em Parusa!"                             //Harige
lang_npc[lang_num,23] = "Eu tenho muitas perguntas sobre a comida desse cara!" //Astum
lang_npc[lang_num,24] = "Dedos de Peixe? Salad de Hotdog? BURRITOS AMARGOS?!" //Astum
lang_npc[lang_num,25] = "Eu me sinto perdida! Eu deveria perguntar por direções." //Leela
lang_npc[lang_num,26] = "Mas eu não quero falar com PESSOAS! Ugh!"           //Leela

//West District NPCs 2
lang_npc[lang_num,27] = "Foi um dia longo, estou quase pronto para ir."      //Harige
lang_npc[lang_num,28] = "Algum cliente de último minuto?"                    //Harige
lang_npc[lang_num,29] = "Éee... Exagerei com o sorvete..."                   //Shy
lang_npc[lang_num,30] = "Talvez alguma comida de verdade vai me fazer sentir melhor?" //Shy
lang_npc[lang_num,31] = "Não tenho certeza sobre a nova poção da Milla!"     //Carol
lang_npc[lang_num,32] = "Eu peguei uma e ela vôou para fora da janela!"      //Carol
lang_npc[lang_num,33] = "Uhew! Aqui deve ser um lugar seguro para cochilar..." //
lang_npc[lang_num,34] = "Essa cidade é cansativo de explorar!"               //
lang_npc[lang_num,35] = "Visitar a cidade foi divertido! Ainda bem que vim"  //Iris
lang_npc[lang_num,36] = "Até mesmo vi as garotas lutarem contra tanques!"    //Iris
lang_npc[lang_num,37] = "Este lugar vai fechar em breve, mas eu não me importo." //Azuli
lang_npc[lang_num,38] = "Mais uma olhada nesta vista é tudo que eu preciso!" //Azuli
lang_npc[lang_num,39] = "Essa é a última vez que eu deixo a bazuca em casa"  //Rhyme
lang_npc[lang_num,40] = "Rapaz, estou feliz que aquele tanque se foi!"       //Rhyme
lang_npc[lang_num,41] = "Cê deve tá se perguntando como eu respiro!"         //Bucky
lang_npc[lang_num,42] = "Fácil, não respira! Água é pra fracotes! Hyunk!"    //Bucky
lang_npc[lang_num,43] = "*Suspira* Eu queria outro caminho para casa..."     //Trip
lang_npc[lang_num,44] = "Está cidade não é a mesma desde a guerra."          //Trip
lang_npc[lang_num,45] = "Certeza que tu quer voltar lá, jovem?"              //Clyde
lang_npc[lang_num,46] = "O centro tá tudo quebrado com os traços do tanque!" //Clyde
lang_npc[lang_num,47] = "Por que estamos aqui? O Bouncer está no lado leste!" //Lilac
lang_npc[lang_num,48] = "Está parte da cidade está segura agora!"            //Lilac
lang_npc[lang_num,49] = "Essa lata é assustadora!"                           //Chiasa
lang_npc[lang_num,50] = "Ela tentou comer as luzes do meu scooter!"          //Chiasa
lang_npc[lang_num,51] = "Eca! Faróis não tem o mesmo gosto que tinham antes!!" //Trash Can
lang_npc[lang_num,52] = "Sinto cheiro de oportunidade para um trabalho novo próximo..." //
lang_npc[lang_num,53] = "Tem muitas denúncias de incidentes nos esgotos ultimamente..."   //
lang_npc[lang_num,54] = "Eu quero me meter em problemas no lado leste!"      //Jett
lang_npc[lang_num,55] = "Bem, *eu* vou alimentar as gaivotas eu mesmo!"      //Astum
lang_npc[lang_num,56] = "O que tem de tão ruim sobre eles?!"                 //Astum
lang_npc[lang_num,57] = "Caramba, até o lixo cheira bem aqui!"               //Marshmallow

//West District NPCs 3
lang_npc[lang_num,58] = "Alguma coisa na lixeira tentou comer o meu cabelo!" //Lilac
lang_npc[lang_num,59] = "Mmm! Tem gosto de arame farpado e óleo de motor!"   //Trash can
lang_npc[lang_num,60] = "Estou tentando limpar os grafites de Jett!"         //Marshmallow
lang_npc[lang_num,61] = "Ela desenhou nosso prefeito como um pino de boliche!" //Marshmallow
lang_npc[lang_num,62] = "Bem, está na hora de ir!"                           //Garrett
lang_npc[lang_num,63] = "O ônibus realmente está levando seu tempo!"         //Abby
lang_npc[lang_num,64] = "Será que o monstro comeu o ônibus também?!"         //Abby
lang_npc[lang_num,65] = "Não seja bobo, Abby!"                               //Alexis
lang_npc[lang_num,66] = "Espera..."                                          //Alexis
lang_npc[lang_num,67] = "Oh, querida! Eu disse para a minha filha que ela é adotada!" //Vela
lang_npc[lang_num,68] = "A sua curiosidade superou ela..."                   //Vela
lang_npc[lang_num,69] = "*Gato.exe parou de funcionar*"                      //Chiasa
lang_npc[lang_num,70] = "Alimentar as gaivotas é tão divertido!"             //Astum
lang_npc[lang_num,71] = "Estou fazendo muitas avés amigas!"                  //Astum
lang_npc[lang_num,72] = "Me desculpe se eu não estiver na minha estande no momento!" //Milla
lang_npc[lang_num,73] = "Eu estava com fome!"                                //Milla
lang_npc[lang_num,74] = "Eu desenho caminhos para órbita de terra baixa! (LEO)" //Leo
lang_npc[lang_num,75] = "Mas aqui estou exibindo um menu para porcaria!"     //Leo
lang_npc[lang_num,76] = "Joga outra embalagem de pirulito em mim, menina!"   //Cook
lang_npc[lang_num,77] = "E eu vou mostrar quem é o lixo!"                    //Cook
lang_npc[lang_num,78] = "Joga outro copo plástico em mim, rapaz!"            //Cook
lang_npc[lang_num,79] = "Ainda tá fechado?"                                  //Azuli
lang_npc[lang_num,80] = "Caminhar até o meu trabalho paralelo foi divertido noite passada!" //Cassandre
lang_npc[lang_num,81] = "Desculpa chefe, um sapo comeu o meu carro, NÃO correu bem!" //Cassandre
lang_npc[lang_num,82] = "Bananas frescas e sopa de mariscos!"                //Harige
lang_npc[lang_num,83] = "Eu especializo em pratos de acompanhamentos de Parusa!" //Harige
lang_npc[lang_num,84] = "Sabe, eu acho que nunca fui para Parusa."           //Carol
lang_npc[lang_num,85] = "Mas a comida de lá cheira bem!"                     //Carol
lang_npc[lang_num,86] = "Eu acho que gosto mais das batatas de Milla"        //Carrie
lang_npc[lang_num,87] = "Minha última poção tacou fogo numa lixeira!"        //Carrie

//West District NPCs 4
lang_npc[lang_num,88]  = "Essa lata está com sorte que ele está fora da minha jurisdição!" //Bird Guard
lang_npc[lang_num,89]  = "Ele comeu minha bicicleta inteira..."               //Bird Guard
lang_npc[lang_num,90]  = "Ehehehehehehe..."                                   //Trash Can
lang_npc[lang_num,91]  = "Psst! Ei, criança! Você quer nabos?"                //Boss
lang_npc[lang_num,92]  = "Você não é uma galinha, né?"                        //Boss
lang_npc[lang_num,93]  = "Essa foi uma notícia das grandes na TV noite passada!" //Axl
lang_npc[lang_num,94]  = "Você fez muito bem, jovem!"                         //Axl
lang_npc[lang_num,95]  = "Siopaos são tãoooo bons..."                         //Carrie
lang_npc[lang_num,96]  = "Eu perdi essa diversão toda noite passada!"         //Rhyme
lang_npc[lang_num,97]  = "Estou com inveja..."                                //Rhyme
lang_npc[lang_num,98]  = "Pode pedir um burger de queijo para mim, Milla?"    //Stumpy
lang_npc[lang_num,99]  = "Essa foi uma boa pausa pro lanche. Hora de voltar!" //Beibo
lang_npc[lang_num,100] = "Sorvete, Sorvete, eu quero sorvete!"                //Milla
lang_npc[lang_num,101] = "AAAAAAAAAAAAA#AAAAAAAAAAAAA#AAAAAAAAAAAAA"          //Milla
lang_npc[lang_num,102] = "Olha pra ela! Eu acho que ela está comendo a tigela!" //Carol
lang_npc[lang_num,103] = "Eu amo e odeio o quão bagunçada essa cidade está."    //Kusei
lang_npc[lang_num,104] = "Chato por 3 meses, excitação de mais por 3 meses..."  //Kusei
lang_npc[lang_num,105] = "Você deveria ir a Shuigang! Nunca tem um dia chato, aha" //Millie
lang_npc[lang_num,106] = "Ahaha..."                                             //Millie
lang_npc[lang_num,107] = "Não é todo dia que o seu escritório de RH é comido por um sapo." //Guage
lang_npc[lang_num,108] = "Bem vindo ao Salão de Sorvete do Zao!"                //Leo
lang_npc[lang_num,109] = "E não, estamos sem morangos por hoje, desculpe!"      //Leo
lang_npc[lang_num,110] = "Ei criança, quer ir x1 nos fliperamas?"               //Flavio
lang_npc[lang_num,111] = "Aposto que você não passa do meu recorde no Sumo F1!" //Flavio

//West District NPCs 5
lang_npc[lang_num,112] = "Por que ninguém me falou que essa lata é sentiente!"  //Flavio
lang_npc[lang_num,113] = "Aquilo comeu o meu Game Bee..."                       //Flavio
lang_npc[lang_num,114] = "Rala muleque! Essa é MINHA tralha!"                   //Trash Can
lang_npc[lang_num,115] = "Mmm! Aposto que seu cabelo deve ficar bom na fritadeira!" //Trash Can
lang_npc[lang_num,116] = "*sons malignos de guaxinim mastigando*"               //Trash Can
lang_npc[lang_num,117] = "Ugh... Acho que terei que usar a bicicleta de palhaço de novo." //Mirdin
lang_npc[lang_num,118] = "*honk honk*"                                          //Mirdin
lang_npc[lang_num,119] = "Ainda não convencida por esses estoques de nabos, hein?" //Boss
lang_npc[lang_num,120] = "Você tem que tentar isso, jovem! É lanche de graça."  //Boss
lang_npc[lang_num,121] = "Hmm, alguém fica esmagando o meu carro..."            //Garrett
lang_npc[lang_num,122] = "Oi, Milla! quero cachilo-quente num paum, por favor, hehe!" //Pummpy
lang_npc[lang_num,123] = "Pai, podemos ter segundos?! Isso foi INCRÍVEL!!!"     //Zeia
lang_npc[lang_num,124] = "Heh, o que eu faço com você, Zeia?"                   //Guage
lang_npc[lang_num,125] = "Bom dia, crianças, a escola liberou cedo?"            //Millie
lang_npc[lang_num,126] = "Ainda precisamos verificar o Templo Wuzhen..."        //Lilac
lang_npc[lang_num,127] = "Milla, quero ver a montanha!"                         //Stumpy
lang_npc[lang_num,128] = "Eu vou querer cinco de suas bananas, por favorzinho!" //Tiwi
lang_npc[lang_num,129] = "Heh, você está deixando o Reino-Tri News ocupado!"    //Axl

//West District NPCs 6
lang_npc[lang_num,130] = "Ou Candy, seria bem legal roubar isso daqui em pleno dia."//Umi
lang_npc[lang_num,131] = "Ter placas de Pare nunca é de mais!"                      //Umi
lang_npc[lang_num,132] = "Umi, você já não comete crimes o bastante?!"              //Candy
lang_npc[lang_num,133] = "Irei levar esta criatura comigo!"                         //Neera
lang_npc[lang_num,134] = "Ele é procurado em todos os três reinos!"                 //Neera
lang_npc[lang_num,135] = "*sons de guaxinim maligno triste*"                        //Trash Can
lang_npc[lang_num,136] = "Eu acho que já me perdi... Hmm."                          //Tanner
lang_npc[lang_num,137] = "Oi, Milla! quero cachilo-quente num paum, por favor, hehe!" //Pummpy
lang_npc[lang_num,138] = "Bom dia, crianças, aproveitando o fim de semana?"         //Millie
lang_npc[lang_num,139] = "Milla, Eu quero ver a praia!"                             //Milla

//West District NPCs 7
lang_npc[lang_num,140] = "Okay, certo, eu não vou roubar a placa de pare!"          //Umi
lang_npc[lang_num,141] = "Talvez nossa cabana ESTEJA ficando um pouco cheio..."     //Umi
lang_npc[lang_num,142] = "Agora sim! Vamos para casa, Umi."                         //Candy
lang_npc[lang_num,143] = "Oi, Milla! Eu quero um burgum, 'favor, hehe!"             //Pumppy
lang_npc[lang_num,144] = "Mmm! Esse sorvete é o melhor sorvete da cidade!"          //Marshmallow
lang_npc[lang_num,145] = "Eu quero segundos!"                                       //Marshmallow
lang_npc[lang_num,146] = "Oh, meu querido... Você me traz verdadeiro contentamento." //Bird Guard (Female)
lang_npc[lang_num,147] = "Qua"                                                      //Bird Guard (Male)
lang_npc[lang_num,148] = "Ooh! Eu amo bananas! Vou levar três."                     //
lang_npc[lang_num,149] = "Oh... É por isso que você não deve alimentar as gaivotas..." //Astum
lang_npc[lang_num,150] = "Eles bicaram meus joelhos por HORAS!!! AI!!!"             //Astum
lang_npc[lang_num,151] = "Não o suficiente!"                                        //Abby
lang_npc[lang_num,152] = "Did we annoy the #babysitter #enough?!"                   //Alexis

