///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Интерьер 1"
o.display_page_description[1] = "Интерьер 2"
o.display_page_description[2] = "Декор"
o.display_page_description[3] = "???"
o.display_page_description[4] = "???"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Панель Пола 1"
o.display_description_item[o.display_page_one,1] = "Панель Пола 2"
o.display_description_item[o.display_page_one,2] = "Панель Пола 3"
o.display_description_item[o.display_page_one,3] = "Панель Стены 1"
o.display_description_item[o.display_page_one,4] = "Панель Стены 2"
o.display_description_item[o.display_page_one,5] = "Панель Потолка 1"
o.display_description_item[o.display_page_one,6] = "Панель Потолка 2"
o.display_description_item[o.display_page_one,7] = "Панель Потолка 3"
o.display_description_item[o.display_page_one,8] = "Угловая Панель 1"
o.display_description_item[o.display_page_one,9] = "Угловая Панель 2"
o.display_description_item[o.display_page_one,10] = "Угловая Панель 3"
o.display_description_item[o.display_page_one,11] = "Угловая Панель 4"
o.display_description_item[o.display_page_one,12] = "Угловая Панель 5"
o.display_description_item[o.display_page_one,13] = "Панель Пола 4"
o.display_description_item[o.display_page_one,14] = "Панель Пола 5"
o.display_description_item[o.display_page_one,15] = "Панель Стены 3"
o.display_description_item[o.display_page_one,16] = "Панель Стены 4"
o.display_description_item[o.display_page_one,17] = "Панель Стены 5"
o.display_description_item[o.display_page_one,18] = "Панель Стены 6"
o.display_description_item[o.display_page_one,19] = "Панель Стены 7"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Панель Пола Альтернативная 1"
o.display_description_item[o.display_page_two,1] = "Панель Пола Альтернативная 2"
o.display_description_item[o.display_page_two,2] = "Панель Пола Альтернативная 3"
o.display_description_item[o.display_page_two,3] = "Металлический Мост"
o.display_description_item[o.display_page_two,4] = "Металлическая Труба"
o.display_description_item[o.display_page_two,5] = ""
o.display_description_item[o.display_page_two,6] = ""
o.display_description_item[o.display_page_two,7] = "Панель Стены Альтернативная 1"
o.display_description_item[o.display_page_two,8] = "Панель Стены Альтернативная 2"
o.display_description_item[o.display_page_two,9] = "Панель Стены Альтернативная 3"
o.display_description_item[o.display_page_two,10] = ""
o.display_description_item[o.display_page_two,11] = "Ржавая петля 1"
o.display_description_item[o.display_page_two,12] = "Ржавая петля 2"
o.display_description_item[o.display_page_two,13] = "Панель Потолка Альтернативная 1"
o.display_description_item[o.display_page_two,14] = "Панель Потолка Альтернативная 2"
o.display_description_item[o.display_page_two,15] = "Панель Потолка Альтернативная 3"
o.display_description_item[o.display_page_two,16] = ""
o.display_description_item[o.display_page_two,17] = ""
o.display_description_item[o.display_page_two,18] = "Ржавая петля 3"
o.display_description_item[o.display_page_two,19] = "Ржавая петля 4"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Колонна"
o.display_description_item[o.display_page_three,1] = "Коридор"
o.display_description_item[o.display_page_three,2] = "Панель Двери 1"
o.display_description_item[o.display_page_three,3] = "Панель Двери 2"
o.display_description_item[o.display_page_three,4] = "Мертвое Растение"
o.display_description_item[o.display_page_three,5] = "Зелёная Колонна"
o.display_description_item[o.display_page_three,6] = "Бронзовая Колонна"
o.display_description_item[o.display_page_three,7] = "Сломанная Транспортная Панель"
o.display_description_item[o.display_page_three,8] = "Ржавая Вентиляция"
o.display_description_item[o.display_page_three,9] = "Сломанный Монитор"
o.display_description_item[o.display_page_three,10] = "Броня Теневого Солдата 1"
o.display_description_item[o.display_page_three,11] = "Броня Теневого Солдата 2"
o.display_description_item[o.display_page_three,12] = "Броня Теневого Солдата 3"
o.display_description_item[o.display_page_three,13] = "Монитор Состояния"
o.display_description_item[o.display_page_three,14] = ""
o.display_description_item[o.display_page_three,15] = ""
o.display_description_item[o.display_page_three,16] = ""
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""
