//For calling in Story Mode object only, call BEFORE NPC spawn scripts
//Language Array; 0 = English; 1 = Portuguese; 2 = Polish; 3 = Spanish; 4 = German; 5 = Russian
var lang_num = 2;

//Temple NPCs 1
lang_npc[lang_num,0] = "Hmm, nie zaszkodzi mi kwiatowa kąpiel!"          //Lilac
lang_npc[lang_num,1] = "Pomaga bardzo w opiece nad moimi włosami!"               //Lilac
lang_npc[lang_num,2] = "Haha! Chiasa! Widziałaś tą pandę?!"          //Jett
lang_npc[lang_num,3] = "Wygląda jak ktoś kogo mama nadal dobiera mu ubrania!"               //Jett
lang_npc[lang_num,4] = "Czy ma Pan lody z bekonem? Proszę!"            //Marshmallow
lang_npc[lang_num,5] = "Witaj w świątyni Shang #Mu! To co bym powiedział, ale..."         //Leo
lang_npc[lang_num,6] = "KTOŚ zapomniał włożyć moją dyskietkę z programem oprowadzania!"            //Leo
lang_npc[lang_num,7] = "Dormitoria zamknięte do 6 rano w związku z pracami*"              //Sign
lang_npc[lang_num,8] = "*Wywołanymi eksplozjami i odłamkami -EVS*"                       //Sign
lang_npc[lang_num,9] = "Proszę znajdź #Bouncera, proszę!"                          //Savvy
lang_npc[lang_num,10] = "Nie stać nas na dwa incydenty jednej nocy!"           //Savvy
lang_npc[lang_num,11] = "Hmm...ktoś zostawia wszędzie dynie."        //Rhyme
lang_npc[lang_num,12] = "To nie jest nawet sezon na dynie! Czemu?"                    //Rhyme
lang_npc[lang_num,13] = "Więc... to tu będziemy trenować?"                  //Xavier
lang_npc[lang_num,14] = "Nigdy nie wiedziałem że taka lokacja istnieje. Tak z dala od centrum."          //Xavier
lang_npc[lang_num,15] = "Czy wiesz że to miejsce ma ponad 200 lat? Jest prawie pradawne!"            //Mei
lang_npc[lang_num,16] = "Wow, to drzewo jest tak piękne!"                             //Mei
lang_npc[lang_num,17] = "Dobry wieczór! Sprzątam przed zamknięciem na noc."              //Harige
lang_npc[lang_num,18] = "Masz jakieś ostatnie zamówienia?"                                  //Harige
lang_npc[lang_num,19] = "TAK, PROSZĘ!!!"                                            //Chiasa
lang_npc[lang_num,20] = "WIDZIAŁAM ŻE MASZ NUGETSY Z KURCZAKA!!!"                       //Chiasa
lang_npc[lang_num,21] = "Ta woda nie smakuje tak dobrze jak wygląda!"           //Astum
lang_npc[lang_num,22] = "Pachnie równie źle!"                                  //Carol
lang_npc[lang_num,23] = "Nie wiem jak ta pani bohaterka... #Eee, Hej Lilac!!!"       //Carol
lang_npc[lang_num,24] = "Co za smród!"                                              //Alexis
lang_npc[lang_num,25] = "Na pewno zrobił to jeden z chłopaków, jestem pewna!"           //Alexis
lang_npc[lang_num,26] = "O, dziecię. Czy też przyszłaś posłuchać dźwięków wody?"             //Ness
lang_npc[lang_num,27] = "Zmywają one zmartwienia, tak jak woda spływa po kamieniach."           //Ness
lang_npc[lang_num,28] = "Och! Och! To będzie wyglądać świetnie przy długiej ekspozycji!"         //Uny
lang_npc[lang_num,29] = "*klik!*"                                                  //Uny
lang_npc[lang_num,30] = "Ale po prostu muszę wiedzieć!"                               //Maria
lang_npc[lang_num,31] = "Mamy raporty o pandzie walczącej z wielką kulą!"             //Maria
lang_npc[lang_num,32] = "Muszę panią przeprosić!"                         //Beldr
lang_npc[lang_num,33] = "Ale czy ty kiedykolwiek śpisz?"                                 //Beldr

//Temple NPCs 2
lang_npc[lang_num,34] = "Wow, co za noc!"                              //Lilac
lang_npc[lang_num,35] = "Chyba tym razem dołączę do Carol w braniu długiej drzemki!"             //Lilac
lang_npc[lang_num,36] = "Oooch! Zobacz na tą małą dynię."                       //Jett
lang_npc[lang_num,37] = "Mam ochotę wepchnąć ją do wyrzutni ziemniaków Marshmallowa!"        //Jett
lang_npc[lang_num,38] = "Mmm! Czyżbym czuł dynię?"                            //Marshmallow
lang_npc[lang_num,39] = "Uwielbiam dynie!"                                      //Marshmallow
lang_npc[lang_num,40] = "Zastanów się nad wzięciem przerwy, moja droga."           //Dr. Dean
lang_npc[lang_num,41] = "Nic nie skrzywdzi cię bardziej niż brak odpoczynku."       //Dr. Dean
lang_npc[lang_num,42] = "Tu jest znacznie przyjemniej niż w hałasie miasta!"         //Wacky
lang_npc[lang_num,43] = "To jest moje ulubione miejsce na drzemkę..."                  //Wacky
lang_npc[lang_num,44] = "Hejo, witaj w moim laboratorium!"                    //Milla
lang_npc[lang_num,45] = "Ten wybuch nie był moją robotą, obiecuje!"               //Milla
lang_npc[lang_num,46] = "Mmm! Tego właśnie potrzebowałem przed pracą!"                         //Tiwi
lang_npc[lang_num,47] = "Fiu! Nareszcie tu dotarłam!"                                   //Iris
lang_npc[lang_num,48] = "Obym nie przegapiła spotkania orientacyjnego!"                   //Iris
lang_npc[lang_num,49] = "Dobry', dobry', dzień dobry dzieciaki!"                        //Jamie
lang_npc[lang_num,50] = "Czuje się znacznie lepiej po dobrze przespanej nocy!"               //Jamie
lang_npc[lang_num,51] = "'Chcesz zerknąć? Jest to darmowe!' -Dyrektor"             //Sign
lang_npc[lang_num,52] = "*na dole jest dopisek: 'Oby!'*"                 //Sign
lang_npc[lang_num,53] = "Och, super! Już prawie jest weekend!"                    //Mei
lang_npc[lang_num,54] = "Nie mogę doczekać się wyjazdu na plażę i zabawy z deską do boogie!"          //Mei
lang_npc[lang_num,55] = "Hej, widziałaś może czerwoną pandę?"                    //Beldr
lang_npc[lang_num,56] = "Słyszałem że podobno gdzieś się tu kręci..."               //Beldr
lang_npc[lang_num,57] = "Hihi! Nie mogę doczekać się lekcji."              //Carrie
lang_npc[lang_num,58] = "Będzie miło was wszystkie bliżej poznać!"          //Carrie
lang_npc[lang_num,59] = "Słuchaj, daj mi sznycla z ziemniakami..."                 //Leela
lang_npc[lang_num,60] = "Mam długi dzień przed sobą."                         //Leela
lang_npc[lang_num,61] = "Dormitoria dla uczniów są teraz otwarte!"                        //Sign
lang_npc[lang_num,62] = "Zwróć uwagę na wywieszone godziny ciszy nocnej!"                   //Sign
lang_npc[lang_num,63] = "Jakiś dzieciak wcisnął mi całą pizze do stacji dysków..."         //Leo
lang_npc[lang_num,64] = "Po czym dotykał mojego ekranu! Mam TRACKBALL!"        //Leo
lang_npc[lang_num,65] = "Hej, miło cię poznać! Jestem tutaj mechanikiem."               //Elric
lang_npc[lang_num,66] = "Naprawiam roboty aby zawsze były dostępne na trening!"                //Elric
lang_npc[lang_num,67] = "Czy chcę wydać jeszcze więcej kasy?"          //Shy
lang_npc[lang_num,68] = "Oczywiście że tak!"                                           //Shy
lang_npc[lang_num,69] = "Dzień dobry, dziewczęta!"                                      //Savvy
lang_npc[lang_num,70] = "Dziękuje, #Lilac! Czynisz dla nas cuda!"        //Savvy
lang_npc[lang_num,71] = "Dzięki, Carol! Była to dla ciebie błahostka!"             //Savvy
lang_npc[lang_num,72] = "Dzięki, Milla!"                                          //Savvy
lang_npc[lang_num,73] = "Wybuchowa robota!"                 //Savvy
lang_npc[lang_num,74] = "Witaj! Czy chciałabyś papierowe menu?"             //Harige
lang_npc[lang_num,75] = "Nie mogę doczekać się pierwszego dnia treningu!"        //Chiasa
lang_npc[lang_num,76] = "Najadłam się już nuggetsów, więc jestem gotowa na wszystko!"           //Chiasa
lang_npc[lang_num,77] = "Och! Ta dynia była tu cały dzień."                   //Astum
lang_npc[lang_num,78] = "Teraz jest moja! Zjem ją na obiad."                         //Astum
lang_npc[lang_num,79] = "Ciesze się że wreszcie znaleźliśmy właściwe miejsce!"         //Ryusei
lang_npc[lang_num,80] = "Nie wieżę że szukaliśmy cały czas w złym budynku!"            //Ryusei
lang_npc[lang_num,81] = "Nie przejmuj się mną! Nadal szukam obserwatorium!"        //Allister
lang_npc[lang_num,82] = "Ta półka wygląda jak dobre miejsce na drzemkę!"              //Carol
lang_npc[lang_num,83] = "Próbowałam łóżek ale... to będzie znacznie wygodniejsze!"           //Carol
lang_npc[lang_num,84] = "Ta woda jest bardzo ciekawa!"                              //Ness
lang_npc[lang_num,85] = "Łaskocze mnie po płetwach! Hihi!"                            //Ness
lang_npc[lang_num,86] = lang_npc[lang_num,30]                                       //Maria
lang_npc[lang_num,87] = lang_npc[lang_num,31]             //Maria

//Temple NPCs 3
lang_npc[lang_num,88] = "Chrrr...Chraaaap...!"                                        //Wacky
lang_npc[lang_num,89] = "Ooch! Powinnam zabrać to coś ze mną!"                 //Milla
lang_npc[lang_num,90] = "Glup! Prawie czas wracać do pracy! #*nom*"               //Tiwi
lang_npc[lang_num,91] = lang_npc[lang_num,49]                        //Jamie
lang_npc[lang_num,92] = lang_npc[lang_num,50]               //Jamie
lang_npc[lang_num,93] = "Klejnoty tego świata są niczym w porównaniu do gwiazd!"        //Mei
lang_npc[lang_num,94] = "Zdziczałe roboty robią się bardziej agresywne o tej godzinie. Uważaj na siebie"   //Beldr
lang_npc[lang_num,95] = "Typowe! Nikt ZNOWU nie przełączył mnie w tryb snu!"          //Leo
lang_npc[lang_num,96] = lang_npc[lang_num,65]               //Elric
lang_npc[lang_num,97] = lang_npc[lang_num,66]                //Elric
lang_npc[lang_num,98] = "Ale z was poranne ptaszki!"                           //Savvy
lang_npc[lang_num,99] = "Oto wasza misja! Przeglądniemy jej wyniki później."     //Savvy
lang_npc[lang_num,100] = "Chyba jestem na teraz bezpieczny..."                        //Pumppy
lang_npc[lang_num,101] = "Chrr...witajcie...w moim programie radiowym...chrrr!"               //Maria
lang_npc[lang_num,102] = "Chrrr...ten sam kanał... ta sama stacja... ten sam nietoperz..."           //Maria

//Temple NPCs 4
lang_npc[lang_num,103] = "Naprawdę powinniśmy się zbierać, tak jak prosiła Savvy!"           //Lilac
lang_npc[lang_num,104] = "Zawierzyła nam z inspekcją świątyni w Wuzhen!"             //Lilac
lang_npc[lang_num,105] = "Czuje się jakbym mógł przeskoczyć nad górami!"              //Wacky
lang_npc[lang_num,106] = "Co za kąpiel!"                                     //Wacky
lang_npc[lang_num,107] = "Och! Mam tak dużo problemów z moimi ziemniakami"        //Milla
lang_npc[lang_num,108] = "Chciałam wystawić stabilną miksturę, a nie wybuchową!"             //Milla
lang_npc[lang_num,109] = "*Milla, czy możesz mi dziś narysować uśmiech?*"           //Stumpy
lang_npc[lang_num,110] = "Chwila, już skończyłaś swoje lekcje na dzisiaj?"              //Mei
lang_npc[lang_num,111] = "Moje dopiero się zaczynają..."                         //Mei
lang_npc[lang_num,112] = "Kto ufa pieńkowi z liczeniem?!"              //Leo
lang_npc[lang_num,113] = "Kiedy ja jestem tutaj cały czas!!!"                                   //Leo
lang_npc[lang_num,114] = "Ten pociąg dojeżdża również w góry!"           //Savvy
lang_npc[lang_num,115] = "Jesteś potrzebna dziś w świątyni Wuzhen!"               //Savvy
lang_npc[lang_num,116] = "Hejo, Milla!"                                              //Pumppy
lang_npc[lang_num,117] = "Dzień dobry, uczniowie! Kto jest głodny?"                  //Harige
lang_npc[lang_num,118] = "Och, myślę że posmakowały by ci nasze Parusańskie przekąski!"       //Harige
lang_npc[lang_num,119] = "Nie codziennie widuje tu smoka wodnego!"           //Harige
lang_npc[lang_num,120] = "Dzień dobry, Pani Carol!"                                //Harige
lang_npc[lang_num,121] = "Słyszałem że bardzo lubisz moje burgery sushi! Doceniam to."    //Harige
lang_npc[lang_num,122] = "Dzień dobry, młoda pani!"                               //Harige
lang_npc[lang_num,123] = "Mogę zaoferować ci mój ziemniaczany specjał?"              //Harige
lang_npc[lang_num,124] = "Dzień dobry uczennico! Powinnaś tu jeść więcej..."       //Harige
lang_npc[lang_num,125] = "Trening to ciężka robota! Co powiesz na stek?"       //Harige
lang_npc[lang_num,126] = "Cóż, też jestem podekscytowany! Ale..."                     //Ryusei
lang_npc[lang_num,127] = "Oby te roboty nie miały PRAWDZIWYCH noży!!!"            //Ryusei
lang_npc[lang_num,128] = "Och Ryu, to jest tak ekscytujące!"                           //Shy
lang_npc[lang_num,129] = "Dają nam walczyć z prawdziwymi robotami!"             //Shy
lang_npc[lang_num,130] = "To było super! Chcę rozwalić więcej robotów!"             //Carol
lang_npc[lang_num,131] = "Hej, Lilac! Miałyśmy ubaw, zróbmy to kiedyś jeszcze raz."        //Carol
lang_npc[lang_num,132] = "Hej, Milla! Pokazałaś temu robotowi kto tu rządzi!"           //Carol
lang_npc[lang_num,133] = "Choć czasem mnie przerażasz..."                      //Carol
lang_npc[lang_num,134] = "Ha! Zobaczcie kogo przywiało z Głupkowa?!"                //Carol

//Temple NPCs 5
lang_npc[lang_num,135] = "Dalej, chodźmy na plażę! Jest piątek!"             //Lilac
lang_npc[lang_num,136] = "Ten pokój też jest fajny!"                                  //Milla
lang_npc[lang_num,137] = "I... wcale nie zatkałam twojej toalety!"                    //Milla
lang_npc[lang_num,138] = "*Milla, czy dostałaś zwrot za tą paczkę?*"         //Stumpy
lang_npc[lang_num,139] = "W tym tempie nigdy nie otworzymy tego śmietnika!"                //Jamie
lang_npc[lang_num,140] = "Wszystkie te zwieszone pułapki, I wybuchy?"              //Jamie
lang_npc[lang_num,141] = "Masz szczęście że wyglądasz słodko!"                      //Jamie
lang_npc[lang_num,142] = "Wystrzeliłoby to mnie w kosmos, a potem do sądu!"       //Jamie
lang_npc[lang_num,143] = "W jaki sposób dzieciaki mylą mnie z automatem sprzedającym?"       //Leo
lang_npc[lang_num,144] = "Byłbym bogaty gdybym stał w pobliżu prawdziwych automatów!"       //Leo
lang_npc[lang_num,145] = "Hmm, czy wysłałem C4 na poprawny adres?"           //Elric
lang_npc[lang_num,146] = "Ech... Dowiemy się później."                             //Elric
lang_npc[lang_num,147] = "Cóż... przyznam że nie łatwo było dotrzymać ci kroku."         //Ryusei
lang_npc[lang_num,148] = "Ale nie byłem gotowy na roboty z pistoletami!"            //Ryusei
lang_npc[lang_num,149] = "Więc, co myślisz o naszych treningach do teraz?"          //Shy
lang_npc[lang_num,150] = "Rozwalanie robotów to świetna zabawa!"                      //Shy
lang_npc[lang_num,151] = "Mmm... Tak blisko kolejnej nowinki..."                         //Maria
lang_npc[lang_num,152] = "Już szykuję się do tej drzemki na plaży."               //Carol

//Temple NPCs 6
lang_npc[lang_num,153] = "Dalej, wracajmy do zatoki!"                       //Lilac
lang_npc[lang_num,154] = "Och, Pani Panini, będziemy miały tyle zabawy!"        //Milla
lang_npc[lang_num,155] = "Ryby są fajne!"                                        //Milla
lang_npc[lang_num,156] = "*Ciesze się że mnie znalazłaś, Milla!*"                  //Stumpy
lang_npc[lang_num,157] = "*Ten rekin posłał mnie w oddal!*"                            //Stumpy
lang_npc[lang_num,158] = "No co jest! Coś jest nie tak z tym automatem?!"          //Astum
lang_npc[lang_num,159] = "Włożyłem kasę, a nic mi nie wydał!"            //Astum
lang_npc[lang_num,160] = "Hejo, Milla! Masz cukiereczka?"                              //Pumppy
lang_npc[lang_num,161] = "No co ty! Też cie kocham, Shy..."                  //Ryusei
lang_npc[lang_num,162] = "...Nie zamarzyłbym sobie o silniejszej dziewczynie niż ona."             //Ryusei
lang_npc[lang_num,163] = "Tada! Oto pierścionek który wygrałam z gumowych slotów!"    //Shy
lang_npc[lang_num,164] = "Starczyło wywalczyć go z paszczy zmutowanej żaby!"           //Shy
lang_npc[lang_num,165] = lang_npc[lang_num,151]                         //Maria
lang_npc[lang_num,166] = "Nie wiem, może się ciebie boją, heh heh..."         //Abby
lang_npc[lang_num,167] = "Wiesz co, Alexis. Dlaczego nas tu nawet wpuszczają?"      //Alexis
lang_npc[lang_num,168] = "Jesteśmy jeszcze za mali aby tu się uczyć!"         //Alexis
lang_npc[lang_num,169] = "Racja, nasza misja w zatoce!"                  //Carol
lang_npc[lang_num,170] = "Sorry, zapomniałam czegoś, haha..."                     //Carol
