///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Platformy"
o.display_page_description[1] = "Trawa"
o.display_page_description[2] = "Rampy"
o.display_page_description[3] = "Platformy"
o.display_page_description[4] = "Sceneria"
o.display_page_description[5] = "Kamień"
o.display_page_description[6] = "Śnieg"
o.display_page_description[7] = "Świątynia 1"
o.display_page_description[8] = "Świątynia 2"
o.display_page_description[9] = "Wnętrza"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Płaski Kamień 1"
o.display_description_item[o.display_page_one,1] = "Krawędź Klifu - Lewa"
o.display_description_item[o.display_page_one,2] = "Krawędź Klifu - Prawa"
o.display_description_item[o.display_page_one,3] = "Ściana z Płaskimi Kamieniami 1"
o.display_description_item[o.display_page_one,4] = "Ściana z Płaskimi Kamieniami 2"
o.display_description_item[o.display_page_one,5] = "Drewniana Belka - Lewa Krawędź"
o.display_description_item[o.display_page_one,6] = "Drewniana Belka"
o.display_description_item[o.display_page_one,7] = "Drewniana Belka - Prawa Krawędź"
o.display_description_item[o.display_page_one,8] = "Łodyga Bambusa - Duża"
o.display_description_item[o.display_page_one,9] = "Łodyga Bambusa - Mała"
o.display_description_item[o.display_page_one,10] = "Łodygi Bambusa - Wąskie"
o.display_description_item[o.display_page_one,11] = "Łodyga Bambusa - Duża Żółta"
o.display_description_item[o.display_page_one,12] = "Łodyga Bambusa - Wąska Żółta"
o.display_description_item[o.display_page_one,13] = "Łodyga Bambusa - Platforma"
o.display_description_item[o.display_page_one,14] = "Łodyga Bambusa - Żółta Platforma"
o.display_description_item[o.display_page_one,15] = "Łodyga Bambusa - Mała Platforma"
o.display_description_item[o.display_page_one,16] = "Łodyga Bambusa - Mała Żółta Platforma"
o.display_description_item[o.display_page_one,17] = "Górska Trawa"
o.display_description_item[o.display_page_one,18] = "Górska Ziemia - Szeroka"
o.display_description_item[o.display_page_one,19] = "Górska Ziemia - Mała"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Górska Ziemia - Odsłonięta Prawa Krawędź"
o.display_description_item[o.display_page_two,1] = "Górska Ziemia - Odsłonięta Lewa Ściana"
o.display_description_item[o.display_page_two,2] = "Górska Ziemia - Odsłonięta Lewa Krawędź"
o.display_description_item[o.display_page_two,3] = "Górska Ziemia - Odsłonięta Prawa Ściana"
o.display_description_item[o.display_page_two,4] = "Górska Ziemia - Odwrócona"
o.display_description_item[o.display_page_two,5] = "Górska Ziemia - Lewy Narożnik"
o.display_description_item[o.display_page_two,6] = "Górska Ziemia - Lewa Ściana"
o.display_description_item[o.display_page_two,7] = "Górska Ziemia - Prawy Kąt"
o.display_description_item[o.display_page_two,8] = "Górska Ziemia - Prawy Narożnik"
o.display_description_item[o.display_page_two,9] = "Górska Ziemia - Prawa Ściana"
o.display_description_item[o.display_page_two,10] = "Górska Ziemia - Lewa Krawędź"
o.display_description_item[o.display_page_two,11] = "Górska Ziemia - Odwrócona Krawędź"
o.display_description_item[o.display_page_two,12] = "Górska Ziemia - Odwrócona Krawędź"
o.display_description_item[o.display_page_two,13] = "Kamienne Kolce 1"
o.display_description_item[o.display_page_two,14] = "Kamienne Kolce 2"
o.display_description_item[o.display_page_two,15] = "Kamienne Kolce 3"
o.display_description_item[o.display_page_two,16] = "Kamienne Kolce 4"
o.display_description_item[o.display_page_two,17] = "Drabina"
o.display_description_item[o.display_page_two,18] = "Drewniany Uchwyt 1"
o.display_description_item[o.display_page_two,19] = "Drewniany Uchwyt 2"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Mała Rampa - 1"
o.display_description_item[o.display_page_three,1] = "Mała Rampa - 2"
o.display_description_item[o.display_page_three,2] = "Mała Rampa - 3"
o.display_description_item[o.display_page_three,3] = "Mała Rampa - 4"
o.display_description_item[o.display_page_three,4] = "Kamienista Pętla - Zewnętrzna 1"
o.display_description_item[o.display_page_three,5] = "Kamienista Pętla - Zewnętrzna 2"
o.display_description_item[o.display_page_three,6] = "Uchwyt 2"
o.display_description_item[o.display_page_three,7] = "Kamienista Pętla - Wewnętrzna 1"
o.display_description_item[o.display_page_three,8] = "Kamienista Pętla - Wewnętrzna 2"
o.display_description_item[o.display_page_three,9] = "Kamienista Pętla - Wewnętrzna 3"
o.display_description_item[o.display_page_three,10] = "Kamienista Pętla - Wewnętrzna 4"
o.display_description_item[o.display_page_three,11] = "Kamienista Pętla - Zewnętrzna 3"
o.display_description_item[o.display_page_three,12] = "Kamienista Pętla - Zewnętrzna 4"
o.display_description_item[o.display_page_three,13] = "Część Trawiastej Pętli 1"
o.display_description_item[o.display_page_three,14] = "Część Trawiastej Pętli 2"
o.display_description_item[o.display_page_three,15] = "Część Trawiastej Pętli 3"
o.display_description_item[o.display_page_three,16] = "Część Trawiastej Pętli 4"
o.display_description_item[o.display_page_three,17] = "Długa Trawiasta Rampa 1"
o.display_description_item[o.display_page_three,18] = "Długa Trawiasta Rampa 2"
o.display_description_item[o.display_page_three,19] = "Kamienna Wielopiętrowa Platforma"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Kamienny Stok"
o.display_description_item[o.display_page_four,1] = "Kamienne Zbocze"
o.display_description_item[o.display_page_four,2] = "Trawiasty Stok"
o.display_description_item[o.display_page_four,3] = "Trawiaste Zbocze"
o.display_description_item[o.display_page_four,4] = "Płytki Zjazd w Dół - 3"
o.display_description_item[o.display_page_four,5] = "Płaska Powierzchnia 1"
o.display_description_item[o.display_page_four,6] = "Płytki Zjazd w Dół - 4"
o.display_description_item[o.display_page_four,7] = "Latająca Platforma 1"
o.display_description_item[o.display_page_four,8] = "Latająca Platforma 2"
o.display_description_item[o.display_page_four,9] = "Latająca Platforma 3"
o.display_description_item[o.display_page_four,10] = "Latająca Platforma 4"
o.display_description_item[o.display_page_four,11] = "Latająca Platforma 5"
o.display_description_item[o.display_page_four,12] = "Odwrót Trasy Platformy"
o.display_description_item[o.display_page_four,13] = "Sceneria - Krawędź Maski Kamienia 1"
o.display_description_item[o.display_page_four,14] = "Sceneria - Krawędź Maski Kamienia 2"
o.display_description_item[o.display_page_four,15] = "Sceneria - Krawędź Maski Kamienia 3"
o.display_description_item[o.display_page_four,16] = "Sceneria - Krawędź Maski Kamienia 4"
o.display_description_item[o.display_page_four,17] = "Sceneria - Kwiecista Czerwona Lampa Shang Mu"
o.display_description_item[o.display_page_four,18] = "Sceneria - Kwiecista Pomarańczowa Lampa Shang Mu"
o.display_description_item[o.display_page_four,19] = "Sceneria - Ciemne Pole"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Sceneria - Kamień 1"
o.display_description_item[o.display_page_five,1] = "Sceneria - Kamień 2"
o.display_description_item[o.display_page_five,2] = "Sceneria - Kamień 3"
o.display_description_item[o.display_page_five,3] = "Sceneria - Kamień 4"
o.display_description_item[o.display_page_five,4] = "Sceneria - Kamień 5"
o.display_description_item[o.display_page_five,5] = "Sceneria - Kamienna Ściana 1"
o.display_description_item[o.display_page_five,6] = "Sceneria - Kamienna Ściana 2"
o.display_description_item[o.display_page_five,7] = "Sceneria - Maska Kamienia - Pionowa"
o.display_description_item[o.display_page_five,8] = "Sceneria - Maska Kamienia - Pozioma"
o.display_description_item[o.display_page_five,9] = "Sceneria - Podpora Mostu"
o.display_description_item[o.display_page_five,10] = "Sceneria - Segment Mostu"
o.display_description_item[o.display_page_five,11] = "Sceneria - Drzewo 1"
o.display_description_item[o.display_page_five,12] = "Sceneria - Trawa"
o.display_description_item[o.display_page_five,13] = "Sceneria - Kamienna Maska - Alt"
o.display_description_item[o.display_page_five,14] = "Sceneria - Kwiat Bambusa"
o.display_description_item[o.display_page_five,15] = "Sceneria - Łodyga Bambusa"
o.display_description_item[o.display_page_five,16] = "Sceneria - Drzewo 2"
o.display_description_item[o.display_page_five,17] = "Sceneria - Krzak"
o.display_description_item[o.display_page_five,18] = "Sceneria - Gałęzie Drzewa"
o.display_description_item[o.display_page_five,19] = "Łodyga Bambusa - Duża Ściana"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Kamienna Powierzchnia 1"
o.display_description_item[o.display_page_six,1] = "Kamienna Powierzchnia 2"
o.display_description_item[o.display_page_six,2] = "Kamienny Sufit 1"
o.display_description_item[o.display_page_six,3] = "Kamienny Sufit 2"
o.display_description_item[o.display_page_six,4] = "Kamień - Wnętrze 1"
o.display_description_item[o.display_page_six,5] = "Kamień - Wnętrze 2"
o.display_description_item[o.display_page_six,6] = "Kamień - Wnętrze 3"
o.display_description_item[o.display_page_six,7] = "Kamienna Ściana 1"
o.display_description_item[o.display_page_six,8] = "Kamienna Ściana 2"
o.display_description_item[o.display_page_six,9] = "Kamienna Ściana 3"
o.display_description_item[o.display_page_six,10] = "Kamienna Ściana 1"
o.display_description_item[o.display_page_six,11] = "Kamienna Ściana 2"
o.display_description_item[o.display_page_six,12] = "Kamienna Ściana 3"
o.display_description_item[o.display_page_six,13] = "Kamień - Wnętrze 3"
o.display_description_item[o.display_page_six,14] = "Kamień - Wnętrze 4"
o.display_description_item[o.display_page_six,15] = "Kamienna Ściana 4"
o.display_description_item[o.display_page_six,16] = "Kamienna Ściana 5"
o.display_description_item[o.display_page_six,17] = "Kamienny Sufit 4"
o.display_description_item[o.display_page_six,18] = "Kamienny Sufit 5"
o.display_description_item[o.display_page_six,19] = "Kamienny Sufit 6"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Śnieżna Powierzchnia 1"
o.display_description_item[o.display_page_seven,1] = "Śnieżna Powierzchnia 2"
o.display_description_item[o.display_page_seven,2] = "Śnieżna Powierzchnia 3"
o.display_description_item[o.display_page_seven,3] = "Śnieżna Powierzchnia 4"
o.display_description_item[o.display_page_seven,4] = "Śnieżna Powierzchnia 5"
o.display_description_item[o.display_page_seven,5] = "Śnieżna Powierzchnia 6"
o.display_description_item[o.display_page_seven,6] = "Śnieżna Powierzchnia 7"
o.display_description_item[o.display_page_seven,7] = "Śnieżny Sufit 1"
o.display_description_item[o.display_page_seven,8] = "Śnieżny Sufit 2"
o.display_description_item[o.display_page_seven,9] = "Śnieżny Sufit 3"
o.display_description_item[o.display_page_seven,10] = "Śnieżna Ściana 1"
o.display_description_item[o.display_page_seven,11] = "Śnieżna Ściana 2"
o.display_description_item[o.display_page_seven,12] = "Śnieżna Ściana 3"
o.display_description_item[o.display_page_seven,13] = "Ośnieżone Drzewo 1"
o.display_description_item[o.display_page_seven,14] = "Pandzi Bałwan 1"
o.display_description_item[o.display_page_seven,15] = "Pandzi Bałwan 2"
o.display_description_item[o.display_page_seven,16] = "Koci Bałwan"
o.display_description_item[o.display_page_seven,17] = "Bałwan 1"
o.display_description_item[o.display_page_seven,18] = "Bałwan 2"
o.display_description_item[o.display_page_seven,19] = "Bałwan 3"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Świątynia - Fusama 1"
o.display_description_item[o.display_page_eight,1] = "Świątynia - Fusama 2"
o.display_description_item[o.display_page_eight,2] = "Świątynia - Fusama 3"
o.display_description_item[o.display_page_eight,3] = "Świątynia - Fusama 4"
o.display_description_item[o.display_page_eight,4] = "Świątynia - Fusama 5"
o.display_description_item[o.display_page_eight,5] = "Świątynia - Fusama 6"
o.display_description_item[o.display_page_eight,6] = "Świątynia - Ściana 1"
o.display_description_item[o.display_page_eight,7] = "Świątynia - Ściana 2"
o.display_description_item[o.display_page_eight,8] = "Świątynia - Ściana 3"
o.display_description_item[o.display_page_eight,9] = "Świątynia - Ściana 4"
o.display_description_item[o.display_page_eight,10] = "Świątynia - Dach - Lewy"
o.display_description_item[o.display_page_eight,11] = "Świątynia - Dach - Środek"
o.display_description_item[o.display_page_eight,12] = "Świątynia - Dach - Prawy"
o.display_description_item[o.display_page_eight,13] = "Świątynia - Belka"
o.display_description_item[o.display_page_eight,14] = "Świątynia - Belka - Mała"
o.display_description_item[o.display_page_eight,15] = "Świątynia - Belka - Duża"
o.display_description_item[o.display_page_eight,16] = "Świątynia - Belka - Róg 1"
o.display_description_item[o.display_page_eight,17] = "Świątynia - Belka - Róg 2"
o.display_description_item[o.display_page_eight,18] = "Świątynia - Belka - Róg 3"
o.display_description_item[o.display_page_eight,19] = "Świątynia - Belka - Róg 4"

//Tile Descriptions (Page 9)
o.display_description_item[o.display_page_nine,0] = "Świątynia - Torii"
o.display_description_item[o.display_page_nine,1] = "Świątynia - Cały Dach"
o.display_description_item[o.display_page_nine,2] = "Świątynia - Stojak Latarnii"
o.display_description_item[o.display_page_nine,3] = "Świątynia - Latarnia"
o.display_description_item[o.display_page_nine,4] = "Świątynia - Znak"
o.display_description_item[o.display_page_nine,5] = "Świątynia - Dachowy Pomnik"
o.display_description_item[o.display_page_nine,6] = "Świątynia - Flaga"
o.display_description_item[o.display_page_nine,7] = "Drewniana Belka - Lewo"
o.display_description_item[o.display_page_nine,8] = "Drewniana Belka - Środek"
o.display_description_item[o.display_page_nine,9] = "Drewniana Belka - Prawo"
o.display_description_item[o.display_page_nine,10] = "Drewniana Belka - Góra"
o.display_description_item[o.display_page_nine,11] = "Drewniana Belka - Środek"
o.display_description_item[o.display_page_nine,12] = "Drewniana Belka - Dół"
o.display_description_item[o.display_page_nine,13] = "Namiot"
o.display_description_item[o.display_page_nine,14] = "Składane Krzesło"
o.display_description_item[o.display_page_nine,15] = "Pieczone Pianki na Patyku"
o.display_description_item[o.display_page_nine,16] = "Ognisko - Płomyki"
o.display_description_item[o.display_page_nine,17] = "Świątynia - Baner Powitalny"
o.display_description_item[o.display_page_nine,18] = "Unknown Tile"
o.display_description_item[o.display_page_nine,19] = "Unknown Tile"

//Tile Descriptions (Page 10)
o.display_description_item[o.display_page_ten,0] = "Biblioteczka - Duża"
o.display_description_item[o.display_page_ten,1] = "Biblioteczka - Duża"
o.display_description_item[o.display_page_ten,2] = "Szafka - Lewo"
o.display_description_item[o.display_page_ten,3] = "Szafka - Prawo"
o.display_description_item[o.display_page_ten,4] = "Lodówka"
o.display_description_item[o.display_page_ten,5] = "Stół - Mały"
o.display_description_item[o.display_page_ten,6] = "Stół - Duży"
o.display_description_item[o.display_page_ten,7] = "Lampa"
o.display_description_item[o.display_page_ten,8] = "Telewizor"
o.display_description_item[o.display_page_ten,9] = "Sofa"
o.display_description_item[o.display_page_ten,10] = "Łóżko"
o.display_description_item[o.display_page_ten,11] = "Kuchenka"
o.display_description_item[o.display_page_ten,12] = "Drewniane Krzesło"
o.display_description_item[o.display_page_ten,13] = "Szafka - Mała"
o.display_description_item[o.display_page_ten,14] = "Toster"
o.display_description_item[o.display_page_ten,15] = "Zasłony - Duże"
o.display_description_item[o.display_page_ten,16] = "Zasłony - Małe"
o.display_description_item[o.display_page_ten,17] = "Zegar Naścienny"
o.display_description_item[o.display_page_ten,18] = "Budzik"
o.display_description_item[o.display_page_ten,19] = "Unknown Tile"

//Tile Descriptions (Page 11)
o.display_description_item[o.display_page_eleven,0] = "Płaska Trawa - Lewo"
o.display_description_item[o.display_page_eleven,1] = "Płaska Trawa"
o.display_description_item[o.display_page_eleven,2] = "Płaska Trawa - Prawo"
o.display_description_item[o.display_page_eleven,3] = "Płaska Trawa - Duża"
o.display_description_item[o.display_page_eleven,4] = "Płaska Trawa - Cieńka"
o.display_description_item[o.display_page_eleven,5] = "Ziemia"
o.display_description_item[o.display_page_eleven,6] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,7] = "Ziemna Ściana - Lewo"
o.display_description_item[o.display_page_eleven,8] = "Ziemia"
o.display_description_item[o.display_page_eleven,9] = "Ziemna Ściana - Prawo"
o.display_description_item[o.display_page_eleven,10] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,11] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,12] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,13] = "Ziemny Sufit - Lewo"
o.display_description_item[o.display_page_eleven,14] = "Ziemny Sufit"
o.display_description_item[o.display_page_eleven,15] = "Ziemny Sufit - Prawo"
o.display_description_item[o.display_page_eleven,16] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,17] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,18] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,19] = "Unknown Tile"
