///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Platforms"
o.display_page_description[1] = "Grass"
o.display_page_description[2] = "Slopes"
o.display_page_description[3] = "Platforms"
o.display_page_description[4] = "Scenery"
o.display_page_description[5] = "Rocky"
o.display_page_description[6] = "Snow"
o.display_page_description[7] = "Temple 1"
o.display_page_description[8] = "Temple 2"
o.display_page_description[9] = "Indoors"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Flat Rock 1"
o.display_description_item[o.display_page_one,1] = "Flat Cliff Edge - Left"
o.display_description_item[o.display_page_one,2] = "Flat Cliff Edge - Right"
o.display_description_item[o.display_page_one,3] = "Flat Rock Wall 1"
o.display_description_item[o.display_page_one,4] = "Flat Rock Wall 2"
o.display_description_item[o.display_page_one,5] = "Wooden Beam Edge - Left"
o.display_description_item[o.display_page_one,6] = "Wooden Beam"
o.display_description_item[o.display_page_one,7] = "Wooden Beam Edge - Right"
o.display_description_item[o.display_page_one,8] = "Bamboo Stalk - Large"
o.display_description_item[o.display_page_one,9] = "Bamboo Stalk - Small"
o.display_description_item[o.display_page_one,10] = "Bamboo Stalks - Skinny"
o.display_description_item[o.display_page_one,11] = "Bamboo Stalk - Large Yellow"
o.display_description_item[o.display_page_one,12] = "Bamboo Stalk - Skinny Yellow"
o.display_description_item[o.display_page_one,13] = "Bamboo Stalk - Platform"
o.display_description_item[o.display_page_one,14] = "Bamboo Stalk - Platform Yellow"
o.display_description_item[o.display_page_one,15] = "Bamboo Stalk - Small Platform"
o.display_description_item[o.display_page_one,16] = "Bamboo Stalk - Small Platform Yellow"
o.display_description_item[o.display_page_one,17] = "Mountain Grass"
o.display_description_item[o.display_page_one,18] = "Mountain Dirt - Wide"
o.display_description_item[o.display_page_one,19] = "Mountain Dirt - Small"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Mountain Grass - Exposed Edge Right"
o.display_description_item[o.display_page_two,1] = "Mountain Grass - Exposed Wall Left"
o.display_description_item[o.display_page_two,2] = "Mountain Grass - Exposed Edge Left"
o.display_description_item[o.display_page_two,3] = "Mountain Grass - Exposed Wall Right"
o.display_description_item[o.display_page_two,4] = "Mountain Grass - Upside Down"
o.display_description_item[o.display_page_two,5] = "Mountain Grass - Corner Piece Left"
o.display_description_item[o.display_page_two,6] = "Mountain Grass - Grass Wall Left"
o.display_description_item[o.display_page_two,7] = "Mountain Grass - Grass Edge Right"
o.display_description_item[o.display_page_two,8] = "Mountain Grass - Corner Piece Right"
o.display_description_item[o.display_page_two,9] = "Mountain Grass - Grass Wall Right"
o.display_description_item[o.display_page_two,10] = "Mountain Grass - Grass Edge Left"
o.display_description_item[o.display_page_two,11] = "Mountain Grass - Grass Edge Upside-Down"
o.display_description_item[o.display_page_two,12] = "Mountain Grass - Grass Edge Upside-Down"
o.display_description_item[o.display_page_two,13] = "Rocky Spikes 1"
o.display_description_item[o.display_page_two,14] = "Rocky Spikes 2"
o.display_description_item[o.display_page_two,15] = "Rocky Spikes 3"
o.display_description_item[o.display_page_two,16] = "Rocky Spikes 4"
o.display_description_item[o.display_page_two,17] = "Ladder"
o.display_description_item[o.display_page_two,18] = "Wooden Hangbar 1"
o.display_description_item[o.display_page_two,19] = "Wooden Hangbar 2"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Small Ramp - 1"
o.display_description_item[o.display_page_three,1] = "Small Ramp - 2"
o.display_description_item[o.display_page_three,2] = "Small Ramp - 3"
o.display_description_item[o.display_page_three,3] = "Small Ramp - 4"
o.display_description_item[o.display_page_three,4] = "Rocky Donut Loop - Outside 1"
o.display_description_item[o.display_page_three,5] = "Rocky Donut Loop - Outside 2"
o.display_description_item[o.display_page_three,6] = "Hangbar 2"
o.display_description_item[o.display_page_three,7] = "Rocky Donut Loop - Inside 1"
o.display_description_item[o.display_page_three,8] = "Rocky Donut Loop - Inside 2"
o.display_description_item[o.display_page_three,9] = "Rocky Donut Loop - Inside 3"
o.display_description_item[o.display_page_three,10] = "Rocky Donut Loop - Inside 4"
o.display_description_item[o.display_page_three,11] = "Rocky Donut Loop - Outside 3"
o.display_description_item[o.display_page_three,12] = "Rocky Donut Loop - Outside 4"
o.display_description_item[o.display_page_three,13] = "Grassy Loop Piece 1"
o.display_description_item[o.display_page_three,14] = "Grassy Loop Piece 2"
o.display_description_item[o.display_page_three,15] = "Grassy Loop Piece 3"
o.display_description_item[o.display_page_three,16] = "Grassy Loop Piece 4"
o.display_description_item[o.display_page_three,17] = "Sloped Grassy Long Piece 1"
o.display_description_item[o.display_page_three,18] = "Sloped Grassy Long Piece 2"
o.display_description_item[o.display_page_three,19] = "Rocky Floor-Over-Floor Platform"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Rock Downslope"
o.display_description_item[o.display_page_four,1] = "Rock Upslope"
o.display_description_item[o.display_page_four,2] = "Grass Downslope"
o.display_description_item[o.display_page_four,3] = "Grass Upslope"
o.display_description_item[o.display_page_four,4] = "Downward Slope - Shallow 3"
o.display_description_item[o.display_page_four,5] = "Flat Surface 1"
o.display_description_item[o.display_page_four,6] = "Downward Slope - Shallow 4"
o.display_description_item[o.display_page_four,7] = "Floating Platform 1"
o.display_description_item[o.display_page_four,8] = "Floating Platform 2"
o.display_description_item[o.display_page_four,9] = "Floating Platform 3"
o.display_description_item[o.display_page_four,10] = "Floating Platform 4"
o.display_description_item[o.display_page_four,11] = "Floating Platform 5"
o.display_description_item[o.display_page_four,12] = "Platform Reverse Course"
o.display_description_item[o.display_page_four,13] = "Scenery - Rock Mask Corner Piece 1"
o.display_description_item[o.display_page_four,14] = "Scenery - Rock Mask Corner Piece 2"
o.display_description_item[o.display_page_four,15] = "Scenery - Rock Mask Corner Piece 3"
o.display_description_item[o.display_page_four,16] = "Scenery - Rock Mask Corner Piece 4"
o.display_description_item[o.display_page_four,17] = "Scenery - Shang Mu Red Lantern Plant"
o.display_description_item[o.display_page_four,18] = "Scenery - Shang Mu Orange Lantern Plant"
o.display_description_item[o.display_page_four,19] = "Scenery - Dark Tile"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Scenery - Rock 1"
o.display_description_item[o.display_page_five,1] = "Scenery - Rock 2"
o.display_description_item[o.display_page_five,2] = "Scenery - Rock 3"
o.display_description_item[o.display_page_five,3] = "Scenery - Rock 4"
o.display_description_item[o.display_page_five,4] = "Scenery - Rock 5"
o.display_description_item[o.display_page_five,5] = "Scenery - Rock Wall 1"
o.display_description_item[o.display_page_five,6] = "Scenery - Rock Wall 2"
o.display_description_item[o.display_page_five,7] = "Scenery - Rock Mask - Horizontal"
o.display_description_item[o.display_page_five,8] = "Scenery - Rock Mask - Vertical"
o.display_description_item[o.display_page_five,9] = "Scenery - Bridge Post"
o.display_description_item[o.display_page_five,10] = "Scenery - Bridge Piece"
o.display_description_item[o.display_page_five,11] = "Scenery - Tree 1"
o.display_description_item[o.display_page_five,12] = "Scenery - Grass"
o.display_description_item[o.display_page_five,13] = "Scenery - Rock Mask - Alternate"
o.display_description_item[o.display_page_five,14] = "Scenery - Bamboo Flower"
o.display_description_item[o.display_page_five,15] = "Scenery - Bamboo Stalk"
o.display_description_item[o.display_page_five,16] = "Scenery - Tree 2"
o.display_description_item[o.display_page_five,17] = "Scenery - Bush"
o.display_description_item[o.display_page_five,18] = "Scenery - Tree Branches"
o.display_description_item[o.display_page_five,19] = "Bamboo Stalk - Large Wall"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Rock Surface 1"
o.display_description_item[o.display_page_six,1] = "Rock Surface 2"
o.display_description_item[o.display_page_six,2] = "Rock Ceiling 1"
o.display_description_item[o.display_page_six,3] = "Rock Ceiling 2"
o.display_description_item[o.display_page_six,4] = "Rock Edge 1"
o.display_description_item[o.display_page_six,5] = "Rock Surface 3"
o.display_description_item[o.display_page_six,6] = "Rock Edge 2"
o.display_description_item[o.display_page_six,7] = "Rock Inside 1"
o.display_description_item[o.display_page_six,8] = "Rock Inside 2"
o.display_description_item[o.display_page_six,9] = "Rock Ceiling 3"
o.display_description_item[o.display_page_six,10] = "Rock Wall 1"
o.display_description_item[o.display_page_six,11] = "Rock Wall 2"
o.display_description_item[o.display_page_six,12] = "Rock Wall 3"
o.display_description_item[o.display_page_six,13] = "Rock Inside 3"
o.display_description_item[o.display_page_six,14] = "Rock Inside 4"
o.display_description_item[o.display_page_six,15] = "Rock Wall 4"
o.display_description_item[o.display_page_six,16] = "Rock Wall 5"
o.display_description_item[o.display_page_six,17] = "Rock Ceiling 4"
o.display_description_item[o.display_page_six,18] = "Rock Ceiling 5"
o.display_description_item[o.display_page_six,19] = "Rock Ceiling 6"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Snow Surface 1"
o.display_description_item[o.display_page_seven,1] = "Snow Surface 2"
o.display_description_item[o.display_page_seven,2] = "Snow Surface 3"
o.display_description_item[o.display_page_seven,3] = "Snow Surface 4"
o.display_description_item[o.display_page_seven,4] = "Snow Surface 5"
o.display_description_item[o.display_page_seven,5] = "Snow Surface 6"
o.display_description_item[o.display_page_seven,6] = "Snow Surface 7"
o.display_description_item[o.display_page_seven,7] = "Snow Ceiling 1"
o.display_description_item[o.display_page_seven,8] = "Snow Ceiling 2"
o.display_description_item[o.display_page_seven,9] = "Snow Ceiling 3"
o.display_description_item[o.display_page_seven,10] = "Snow Wall 1"
o.display_description_item[o.display_page_seven,11] = "Snow Wall 2"
o.display_description_item[o.display_page_seven,12] = "Snow Wall 3"
o.display_description_item[o.display_page_seven,13] = "Snowy Tree 1"
o.display_description_item[o.display_page_seven,14] = "Snow Panda 1"
o.display_description_item[o.display_page_seven,15] = "Snow Panda 2"
o.display_description_item[o.display_page_seven,16] = "Snow Cat"
o.display_description_item[o.display_page_seven,17] = "Snow Kid 1"
o.display_description_item[o.display_page_seven,18] = "Snow Kid 2"
o.display_description_item[o.display_page_seven,19] = "Snow Kid 3"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Temple - Fusama 1"
o.display_description_item[o.display_page_eight,1] = "Temple - Fusama 2"
o.display_description_item[o.display_page_eight,2] = "Temple - Fusama 3"
o.display_description_item[o.display_page_eight,3] = "Temple - Fusama 4"
o.display_description_item[o.display_page_eight,4] = "Temple - Fusama 5"
o.display_description_item[o.display_page_eight,5] = "Temple - Fusama 6"
o.display_description_item[o.display_page_eight,6] = "Temple - Wall 1"
o.display_description_item[o.display_page_eight,7] = "Temple - Wall 2"
o.display_description_item[o.display_page_eight,8] = "Temple - Wall 3"
o.display_description_item[o.display_page_eight,9] = "Temple - Wall 4"
o.display_description_item[o.display_page_eight,10] = "Temple - Roof - Left"
o.display_description_item[o.display_page_eight,11] = "Temple - Roof - Middle"
o.display_description_item[o.display_page_eight,12] = "Temple - Roof - Right"
o.display_description_item[o.display_page_eight,13] = "Temple - Beam"
o.display_description_item[o.display_page_eight,14] = "Temple - Beam - Small"
o.display_description_item[o.display_page_eight,15] = "Temple - Beam - Large"
o.display_description_item[o.display_page_eight,16] = "Temple - Beam - Corner 1"
o.display_description_item[o.display_page_eight,17] = "Temple - Beam - Corner 2"
o.display_description_item[o.display_page_eight,18] = "Temple - Beam - Corner 3"
o.display_description_item[o.display_page_eight,19] = "Temple - Beam - Corner 4"

//Tile Descriptions (Page 9)
o.display_description_item[o.display_page_nine,0] = "Temple - Torii"
o.display_description_item[o.display_page_nine,1] = "Temple - Complete Roof"
o.display_description_item[o.display_page_nine,2] = "Temple - Lantern Stand"
o.display_description_item[o.display_page_nine,3] = "Temple - Lamppost"
o.display_description_item[o.display_page_nine,4] = "Temple - Signpost"
o.display_description_item[o.display_page_nine,5] = "Temple - Rooftop Statue"
o.display_description_item[o.display_page_nine,6] = "Temple - Flag"
o.display_description_item[o.display_page_nine,7] = "Wood Beam - Left"
o.display_description_item[o.display_page_nine,8] = "Wood Beam - Middle"
o.display_description_item[o.display_page_nine,9] = "Wood Beam - Right"
o.display_description_item[o.display_page_nine,10] = "Wood Beam - Top"
o.display_description_item[o.display_page_nine,11] = "Wood Beam - Middle"
o.display_description_item[o.display_page_nine,12] = "Wood Beam - Bottom"
o.display_description_item[o.display_page_nine,13] = "Tent"
o.display_description_item[o.display_page_nine,14] = "Folding Chair"
o.display_description_item[o.display_page_nine,15] = "Roasted Marshmallow On A Stick"
o.display_description_item[o.display_page_nine,16] = "Campire - Embers"
o.display_description_item[o.display_page_nine,17] = "Temple - Welcome Banner"
o.display_description_item[o.display_page_nine,18] = "Unknown Tile"
o.display_description_item[o.display_page_nine,19] = "Unknown Tile"

//Tile Descriptions (Page 10)
o.display_description_item[o.display_page_ten,0] = "Bookshelf - Large"
o.display_description_item[o.display_page_ten,1] = "Bookshelf - Small"
o.display_description_item[o.display_page_ten,2] = "Cabinet - Left"
o.display_description_item[o.display_page_ten,3] = "Cabinet - Right"
o.display_description_item[o.display_page_ten,4] = "Refrigerator"
o.display_description_item[o.display_page_ten,5] = "Table - Small"
o.display_description_item[o.display_page_ten,6] = "Table - Large"
o.display_description_item[o.display_page_ten,7] = "Hallway Lamp"
o.display_description_item[o.display_page_ten,8] = "TV Set"
o.display_description_item[o.display_page_ten,9] = "Living Room Couch"
o.display_description_item[o.display_page_ten,10] = "Bed"
o.display_description_item[o.display_page_ten,11] = "Oven and Stovetop"
o.display_description_item[o.display_page_ten,12] = "Wooden Chair"
o.display_description_item[o.display_page_ten,13] = "Cabinet - Small"
o.display_description_item[o.display_page_ten,14] = "Toaster"
o.display_description_item[o.display_page_ten,15] = "Curtains - Large"
o.display_description_item[o.display_page_ten,16] = "Curtains - Small"
o.display_description_item[o.display_page_ten,17] = "Wall Clock"
o.display_description_item[o.display_page_ten,18] = "Alarm Clock"
o.display_description_item[o.display_page_ten,19] = "Unknown Tile"

//Tile Descriptions (Page 11)
o.display_description_item[o.display_page_eleven,0] = "Grass Flat Left"
o.display_description_item[o.display_page_eleven,1] = "Grass Flat"
o.display_description_item[o.display_page_eleven,2] = "Grass Flat Right"
o.display_description_item[o.display_page_eleven,3] = "Grass Flat Large"
o.display_description_item[o.display_page_eleven,4] = "Grass Flat Thin"
o.display_description_item[o.display_page_eleven,5] = "Dirt"
o.display_description_item[o.display_page_eleven,6] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,7] = "Dirt Wall Left"
o.display_description_item[o.display_page_eleven,8] = "Dirt"
o.display_description_item[o.display_page_eleven,9] = "Dirt Wall Right"
o.display_description_item[o.display_page_eleven,10] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,11] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,12] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,13] = "Dirt Ceiling Left"
o.display_description_item[o.display_page_eleven,14] = "Dirt Ceiling"
o.display_description_item[o.display_page_eleven,15] = "Dirt Ceiling Right"
o.display_description_item[o.display_page_eleven,16] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,17] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,18] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,19] = "Unknown Tile"
