///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Balken"
o.display_page_description[1] = "Wände"
o.display_page_description[2] = "Pisten"
o.display_page_description[3] = "Plattformen"
o.display_page_description[4] = "Landschaft 1"
o.display_page_description[5] = "Landschaft 2"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Holzblock 1"
o.display_description_item[o.display_page_one,1] = "Floor Tile"
o.display_description_item[o.display_page_one,2] = "Stützbalken 1"
o.display_description_item[o.display_page_one,3] = "Holzblock 2"
o.display_description_item[o.display_page_one,4] = "Holzblock 3"
o.display_description_item[o.display_page_one,5] = "Holzblock 4"
o.display_description_item[o.display_page_one,6] = "Holzblock 5"
o.display_description_item[o.display_page_one,7] = "Holzblock 6"
o.display_description_item[o.display_page_one,8] = "Stützbalken 2"
o.display_description_item[o.display_page_one,9] = "Holzblock 7"
o.display_description_item[o.display_page_one,10] = "Holzblock 8"
o.display_description_item[o.display_page_one,11] = "Holzblock 9"
o.display_description_item[o.display_page_one,12] = "Holzblock 10"
o.display_description_item[o.display_page_one,13] = "Stützbalken 3"
o.display_description_item[o.display_page_one,14] = "Eckteil - Links"
o.display_description_item[o.display_page_one,15] = "Holzbalken"
o.display_description_item[o.display_page_one,16] = "Eckteil - Rechts"
o.display_description_item[o.display_page_one,17] = "Holzblock 11"
o.display_description_item[o.display_page_one,18] = "Eckteil - Oben"
o.display_description_item[o.display_page_one,19] = "Eckteil - Unten"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Wand - Rechts"
o.display_description_item[o.display_page_two,1] = "Wand - Links"
o.display_description_item[o.display_page_two,2] = "Floor"
o.display_description_item[o.display_page_two,3] = "Decke"
o.display_description_item[o.display_page_two,4] = "Außere Ecke 1"
o.display_description_item[o.display_page_two,5] = "Außere Ecke 2"
o.display_description_item[o.display_page_two,6] = "Außere Ecke 3"
o.display_description_item[o.display_page_two,7] = "Außere Ecke 4"
o.display_description_item[o.display_page_two,8] = "Innere Ecke 1"
o.display_description_item[o.display_page_two,9] = "Innere Ecke 2"
o.display_description_item[o.display_page_two,10] = "Innere Ecke 3"
o.display_description_item[o.display_page_two,11] = "Innere Ecke 4"
o.display_description_item[o.display_page_two,12] = "Shading Tile 1"
o.display_description_item[o.display_page_two,13] = "Stacheln 1"
o.display_description_item[o.display_page_two,14] = "Stacheln 2"
o.display_description_item[o.display_page_two,15] = "Stacheln 3"
o.display_description_item[o.display_page_two,16] = "Stacheln 4"
o.display_description_item[o.display_page_two,17] = "Leiter"
o.display_description_item[o.display_page_two,18] = "Hangbar 1"
o.display_description_item[o.display_page_two,19] = "Hangbar 2"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Kleine Rampe - 1"
o.display_description_item[o.display_page_three,1] = "Kleine Rampe - 2"
o.display_description_item[o.display_page_three,2] = "Kleine Rampe - 3"
o.display_description_item[o.display_page_three,3] = "Kleine Rampe - 4"
o.display_description_item[o.display_page_three,4] = "Grasschleifenteil 1"
o.display_description_item[o.display_page_three,5] = "Grasschleifenteil 2"
o.display_description_item[o.display_page_three,6] = "Boden Tile"
o.display_description_item[o.display_page_three,7] = "Schleußenteil 1"
o.display_description_item[o.display_page_three,8] = "Schleußenteil 2"
o.display_description_item[o.display_page_three,9] = "Schleußenteil 3"
o.display_description_item[o.display_page_three,10] = "Schleußenteil 4"
o.display_description_item[o.display_page_three,11] = "Grasschleifenteil 3"
o.display_description_item[o.display_page_three,12] = "Grasschleifenteil 4"
o.display_description_item[o.display_page_three,13] = "Doppelseitige Schleife 1"
o.display_description_item[o.display_page_three,14] = "Doppelseitige Schleife 2"
o.display_description_item[o.display_page_three,15] = "Doppelseitige Schleife 3"
o.display_description_item[o.display_page_three,16] = "Doppelseitige Schleife 4"
o.display_description_item[o.display_page_three,17] = "Geneigtes Langes Teil 1"
o.display_description_item[o.display_page_three,18] = "Geneigtes Langes Teil 2"
o.display_description_item[o.display_page_three,19] = "Bodenüber Plattform"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Nach unten Neigung - Flach 1"
o.display_description_item[o.display_page_four,1] = "Nach unten Neigung - Flach 2"
o.display_description_item[o.display_page_four,2] = "Nach unten Neigung - Steil 1"
o.display_description_item[o.display_page_four,3] = "Nach unten Neigung - Steil 2"
o.display_description_item[o.display_page_four,4] = "Nach unten Neigung - Flach 3"
o.display_description_item[o.display_page_four,5] = "Flache Oberfläche 1"
o.display_description_item[o.display_page_four,6] = "Nach unten Neigung - Flach 4"
o.display_description_item[o.display_page_four,7] = "Schw. Plattform 1"
o.display_description_item[o.display_page_four,8] = "Schw. Plattform 2"
o.display_description_item[o.display_page_four,9] = "Schw. Plattform 3"
o.display_description_item[o.display_page_four,10] = "Schw. Plattform 4"
o.display_description_item[o.display_page_four,11] = "Schw. Plattform 5"
o.display_description_item[o.display_page_four,12] = "Umgek. Plattform"
o.display_description_item[o.display_page_four,13] = "Gras Tile"
o.display_description_item[o.display_page_four,14] = "Dreck Tile"
o.display_description_item[o.display_page_four,15] = "Unknown Tile 3"
o.display_description_item[o.display_page_four,16] = "Unknown Tile 4"
o.display_description_item[o.display_page_four,17] = "Unknown Tile 5"
o.display_description_item[o.display_page_four,18] = "Unknown Tile 6"
o.display_description_item[o.display_page_four,19] = "Unknown Tile 7"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Landschaft - Brücke 1"
o.display_description_item[o.display_page_five,1] = "Landschaft - Spalte"
o.display_description_item[o.display_page_five,2] = "Landschaft - Baum 1"
o.display_description_item[o.display_page_five,3] = "Landschaft - Gitter"
o.display_description_item[o.display_page_five,4] = "Landschaft - Hintergrund"
o.display_description_item[o.display_page_five,5] = "Landschaft - Plattform"
o.display_description_item[o.display_page_five,6] = "Landschaft - Fusuma 1"
o.display_description_item[o.display_page_five,7] = "Landschaft - Gemälde"
o.display_description_item[o.display_page_five,8] = "Landschaft - Gardinen"
o.display_description_item[o.display_page_five,9] = "Landschaft - Gardinenende"
o.display_description_item[o.display_page_five,10] = "Landschaft - Geländer1"
o.display_description_item[o.display_page_five,11] = "Landschaft - Stütze"
o.display_description_item[o.display_page_five,12] = "Landschaft - Laterne 1"
o.display_description_item[o.display_page_five,13] = "Landschaft - Fusuma 2"
o.display_description_item[o.display_page_five,14] = "Landschaft - Baum 2"
o.display_description_item[o.display_page_five,15] = "Landschaft - Baum 3"
o.display_description_item[o.display_page_five,16] = "Landschaft - Baum 3 - Deko"
o.display_description_item[o.display_page_five,17] = "Landschaft - Baum 4"
o.display_description_item[o.display_page_five,18] = "Landschaft - Flagge 1"
o.display_description_item[o.display_page_five,19] = "Landschaft - Laterne 2"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Shading Tile 16x16"
o.display_description_item[o.display_page_six,1] = "Shading Tile 32x32"
o.display_description_item[o.display_page_six,2] = "Shading Tile 64x64"
o.display_description_item[o.display_page_six,3] = "Shading Tile 96x96"
o.display_description_item[o.display_page_six,4] = "Shading Tile 16x96"
o.display_description_item[o.display_page_six,5] = "Shading Tile 96x16"
o.display_description_item[o.display_page_six,6] = "Shading Tile 128x128"
o.display_description_item[o.display_page_six,7] = "Dunkles Tile 128x128"
o.display_description_item[o.display_page_six,8] = "Landschaft - Großer Tisch"
o.display_description_item[o.display_page_six,9] = "Landschaft - Kleiner Tisch"
o.display_description_item[o.display_page_six,10] = "Unknown Tile"
o.display_description_item[o.display_page_six,11] = "Unknown Tile"
o.display_description_item[o.display_page_six,12] = "Unknown Tile"
o.display_description_item[o.display_page_six,13] = "Unknown Tile"
o.display_description_item[o.display_page_six,14] = "Unknown Tile"
o.display_description_item[o.display_page_six,15] = "Unknown Tile"
o.display_description_item[o.display_page_six,16] = "Unknown Tile"
o.display_description_item[o.display_page_six,17] = "Unknown Tile"
o.display_description_item[o.display_page_six,18] = "Unknown Tile"
o.display_description_item[o.display_page_six,19] = "Unknown Tile"
