//Language Array (Pause Menu); 0 = English; 1 = Portuguese; 2 = Polish
lang_gui[0,0] = "Character Select"
lang_gui[0,1] = "Tutorial Stage"
lang_gui[0,2] = "Costumes"
lang_gui[0,3] = "Confirm"
lang_gui[0,4] = "Cancel"
lang_gui[0,5] = "Return"
lang_gui[0,6] = "Palettes"
//Portuguese
lang_gui[1,0] = "Selecionar Personagem"
lang_gui[1,1] = "Fase Tutorial"
lang_gui[1,2] = "Trajes"
lang_gui[1,3] = "Confirmar"
lang_gui[1,4] = "Cancelar"
lang_gui[1,5] = "Voltar"
lang_gui[1,6] = "Paletas"
//Polish
lang_gui[2,0] = "Wybór Postaci"
lang_gui[2,1] = "Samouczek"
lang_gui[2,2] = "Kostiumy"
lang_gui[2,3] = "Potwierdź"
lang_gui[2,4] = "Anuluj"
lang_gui[2,5] = "Wróć"
lang_gui[2,6] = "Paleta"
