///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Plataformas"
o.display_page_description[1] = "Paredes"
o.display_page_description[2] = "Pendientes"
o.display_page_description[3] = "Decoración"
o.display_page_description[4] = "Extras"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Panel de Piso 1"
o.display_description_item[o.display_page_one,1] = "Panel de Piso 2"
o.display_description_item[o.display_page_one,2] = "Panel de Piso 3"
o.display_description_item[o.display_page_one,3] = "Pieza de Puente 1"
o.display_description_item[o.display_page_one,4] = "Pieza de Puente 2"
o.display_description_item[o.display_page_one,5] = "Pieza de Puente 3"
o.display_description_item[o.display_page_one,6] = "Pieza de Puente 4"
o.display_description_item[o.display_page_one,7] = "Panel de Pared 1"
o.display_description_item[o.display_page_one,8] = "Panel de Pared 2"
o.display_description_item[o.display_page_one,9] = "Panel de Pared 3"
o.display_description_item[o.display_page_one,10] = "Pieza de Puente 5"
o.display_description_item[o.display_page_one,11] = "Panel de Pared 4"
o.display_description_item[o.display_page_one,12] = "Pieza de Puente 6"
o.display_description_item[o.display_page_one,13] = "Panel de Techo 1"
o.display_description_item[o.display_page_one,14] = "Panel de Techo 2"
o.display_description_item[o.display_page_one,15] = "Panel de Techo 3"
o.display_description_item[o.display_page_one,16] = "Panel Interior 1"
o.display_description_item[o.display_page_one,17] = "Panel Interior 2"
o.display_description_item[o.display_page_one,18] = "Panel Interior 3"
o.display_description_item[o.display_page_one,19] = "Panel Interior 4"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Panel de Pared 4"
o.display_description_item[o.display_page_two,1] = "Panel de Pared 5"
o.display_description_item[o.display_page_two,2] = "Panel de Pared 6"
o.display_description_item[o.display_page_two,3] = "Ventilador Grande"
o.display_description_item[o.display_page_two,4] = "Panel de Pared 7"
o.display_description_item[o.display_page_two,5] = "Panel de Pared 8"
o.display_description_item[o.display_page_two,6] = "Panel de Pared 7"
o.display_description_item[o.display_page_two,7] = "Viga de Soporte 1"
o.display_description_item[o.display_page_two,8] = "Viga de Soporte 2"
o.display_description_item[o.display_page_two,9] = "Viga de Soporte 3"
o.display_description_item[o.display_page_two,10] = ""
o.display_description_item[o.display_page_two,11] = ""
o.display_description_item[o.display_page_two,12] = ""
o.display_description_item[o.display_page_two,13] = ""
o.display_description_item[o.display_page_two,14] = ""
o.display_description_item[o.display_page_two,15] = ""
o.display_description_item[o.display_page_two,16] = ""
o.display_description_item[o.display_page_two,17] = ""
o.display_description_item[o.display_page_two,18] = ""
o.display_description_item[o.display_page_two,19] = ""

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Panel de Piso en Pendiente 1"
o.display_description_item[o.display_page_three,1] = "Panel de Piso en Pendiente 2"
o.display_description_item[o.display_page_three,2] = "Puente en Pendiente 1"
o.display_description_item[o.display_page_three,3] = "Puente en Pendiente 2"
o.display_description_item[o.display_page_three,4] = "Plataforma Flotante 1"
o.display_description_item[o.display_page_three,5] = "Orbe Flotante"
o.display_description_item[o.display_page_three,6] = "Orbe Flotante Agrietado"
o.display_description_item[o.display_page_three,7] = "Panel de Bucle 1"
o.display_description_item[o.display_page_three,8] = "Panel de Bucle 2"
o.display_description_item[o.display_page_three,9] = "Bucle Expuesto 1"
o.display_description_item[o.display_page_three,10] = "Bucle Expuesto 2"
o.display_description_item[o.display_page_three,11] = ""
o.display_description_item[o.display_page_three,12] = ""
o.display_description_item[o.display_page_three,13] = "Panel de Bucle 3"
o.display_description_item[o.display_page_three,14] = "Panel de Bucle 4"
o.display_description_item[o.display_page_three,15] = "Bucle Expuesto 3"
o.display_description_item[o.display_page_three,16] = "Bucle Expuesto 4"
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Puerta de Laboratorio"
o.display_description_item[o.display_page_four,1] = "Caja de Interruptores (Cerrada)"
o.display_description_item[o.display_page_four,2] = "Caja de Interruptores (Abierta)"
o.display_description_item[o.display_page_four,3] = "Caja con Chatarra 1"
o.display_description_item[o.display_page_four,4] = "Letrero de Objetos de Protección Personal"
o.display_description_item[o.display_page_four,5] = "Caja con Chatarra 2"
o.display_description_item[o.display_page_four,6] = "Mesa de Trabajo"
o.display_description_item[o.display_page_four,7] = "Mesa Base"
o.display_description_item[o.display_page_four,8] = "Mesa de WiFi"
o.display_description_item[o.display_page_four,9] = "Dron Desactivado"
o.display_description_item[o.display_page_four,10] = "Rieles"
o.display_description_item[o.display_page_four,11] = ""
o.display_description_item[o.display_page_four,12] = ""
o.display_description_item[o.display_page_four,13] = ""
o.display_description_item[o.display_page_four,14] = ""
o.display_description_item[o.display_page_four,15] = ""
o.display_description_item[o.display_page_four,16] = ""
o.display_description_item[o.display_page_four,17] = ""
o.display_description_item[o.display_page_four,18] = ""
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = ""
o.display_description_item[o.display_page_five,1] = ""
o.display_description_item[o.display_page_five,2] = ""
o.display_description_item[o.display_page_five,3] = ""
o.display_description_item[o.display_page_five,4] = ""
o.display_description_item[o.display_page_five,5] = ""
o.display_description_item[o.display_page_five,6] = ""
o.display_description_item[o.display_page_five,7] = ""
o.display_description_item[o.display_page_five,8] = ""
o.display_description_item[o.display_page_five,9] = ""
o.display_description_item[o.display_page_five,10] = ""
o.display_description_item[o.display_page_five,11] = ""
o.display_description_item[o.display_page_five,12] = ""
o.display_description_item[o.display_page_five,13] = ""
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = ""
o.display_description_item[o.display_page_six,1] = ""
o.display_description_item[o.display_page_six,2] = ""
o.display_description_item[o.display_page_six,3] = ""
o.display_description_item[o.display_page_six,4] = ""
o.display_description_item[o.display_page_six,5] = ""
o.display_description_item[o.display_page_six,6] = ""
o.display_description_item[o.display_page_six,7] = ""
o.display_description_item[o.display_page_six,8] = ""
o.display_description_item[o.display_page_six,9] = ""
o.display_description_item[o.display_page_six,10] = ""
o.display_description_item[o.display_page_six,11] = ""
o.display_description_item[o.display_page_six,12] = ""
o.display_description_item[o.display_page_six,13] = ""
o.display_description_item[o.display_page_six,14] = ""
o.display_description_item[o.display_page_six,15] = ""
o.display_description_item[o.display_page_six,16] = ""
o.display_description_item[o.display_page_six,17] = ""
o.display_description_item[o.display_page_six,18] = ""
o.display_description_item[o.display_page_six,19] = ""

