///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Plattform"
o.display_page_description[1] = "Balken"
o.display_page_description[2] = "Pisten"
o.display_page_description[3] = "Scene 1"
o.display_page_description[4] = "Scene 2"
o.display_page_description[5] = "Scene 3"
o.display_page_description[6] = "Scene 4"
o.display_page_description[7] = "Scene 5"
o.display_page_description[8] = "Ungenutzt"
o.display_page_description[9] = "Extras 1"
o.display_page_description[10] = "Extras 2"
o.display_page_description[11] = "Alt. Ziegel"
o.display_page_description[12] = "Extras 3"
o.display_page_description[13] = "Extras 4"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Ziegelplattform 1"
o.display_description_item[o.display_page_one,1] = "Ziegelplattform 2"
o.display_description_item[o.display_page_one,2] = "Ziegelwand 1"
o.display_description_item[o.display_page_one,3] = "Ziegelwand 2"
o.display_description_item[o.display_page_one,4] = "Ziegelwand 3"
o.display_description_item[o.display_page_one,5] = "Ziegelwand 4"
o.display_description_item[o.display_page_one,6] = "Ziegelblock 1"
o.display_description_item[o.display_page_one,7] = "Ziegelblock 2"
o.display_description_item[o.display_page_one,8] = "Ziegelblock 3"
o.display_description_item[o.display_page_one,9] = "Roter Block"
o.display_description_item[o.display_page_one,10] = "Blauer Block"
o.display_description_item[o.display_page_one,11] = "Wandteiler 1"
o.display_description_item[o.display_page_one,12] = "Wandteiler 2"
o.display_description_item[o.display_page_one,13] = "Röhren 1"
o.display_description_item[o.display_page_one,14] = "Röhren 2"
o.display_description_item[o.display_page_one,15] = "Röhren 3"
o.display_description_item[o.display_page_one,16] = "Röhren 4"
o.display_description_item[o.display_page_one,17] = "Röhrenende 1"
o.display_description_item[o.display_page_one,18] = "Röhrenende 2"
o.display_description_item[o.display_page_one,19] = "Röhrenende 3"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Konstruktionsbalken - Rot 1"
o.display_description_item[o.display_page_two,1] = "Konstruktionsbalken - Rot 2"
o.display_description_item[o.display_page_two,2] = "Konstruktionsbalken - Gelb 1"
o.display_description_item[o.display_page_two,3] = "Konstruktionsbalken - Gelb 2"
o.display_description_item[o.display_page_two,4] = "Konstruktionsbalken - Rot 3"
o.display_description_item[o.display_page_two,5] = "Konstruktionsbalken - Rot 4"
o.display_description_item[o.display_page_two,6] = "Konstruktionsbalken - Gelb 3"
o.display_description_item[o.display_page_two,7] = "Stützbalken - Gelb 1"
o.display_description_item[o.display_page_two,8] = "Stützbalken - Gelb 2"
o.display_description_item[o.display_page_two,9] = "Stützbalken - Rot 1"
o.display_description_item[o.display_page_two,10] = "Stützbalken - Rot 2"
o.display_description_item[o.display_page_two,11] = "Stützbalken - Rot 3"
o.display_description_item[o.display_page_two,12] = "Stützbalken - Gelb 3"
o.display_description_item[o.display_page_two,13] = "Betonmauer - 1"
o.display_description_item[o.display_page_two,14] = "Betonmauer - 2"
o.display_description_item[o.display_page_two,15] = "Gehweg - 1"
o.display_description_item[o.display_page_two,16] = "Gehweg - 2"
o.display_description_item[o.display_page_two,17] = "Gehweg - 3"
o.display_description_item[o.display_page_two,18] = "Gehweg - 4"
o.display_description_item[o.display_page_two,19] = "Konstruktionsbalken - Gelb 3"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Viertel Rohrbalken 1"
o.display_description_item[o.display_page_three,1] = "Viertel Rohrbalken 2"
o.display_description_item[o.display_page_three,2] = "Viertel Rohrbalken 3"
o.display_description_item[o.display_page_three,3] = "Viertel Rohrbalken 4"
o.display_description_item[o.display_page_three,4] = "Viertel Rohrbalken 1 - Umgek."
o.display_description_item[o.display_page_three,5] = "Viertel Rohrbalken 2 - Umgek."
o.display_description_item[o.display_page_three,6] = "Schweb. Platform 1"
o.display_description_item[o.display_page_three,7] = "Schlaufenteil 1"
o.display_description_item[o.display_page_three,8] = "Schlaufenteil 2"
o.display_description_item[o.display_page_three,9] = "Schlaufenteil 3"
o.display_description_item[o.display_page_three,10] = "Schlaufenteil 4"
o.display_description_item[o.display_page_three,11] = "Viertel Rohrbalken 3 - Umgek."
o.display_description_item[o.display_page_three,12] = "Viertel Rohrbalken 4 - Umgek."
o.display_description_item[o.display_page_three,13] = "Straßenrampe 1"
o.display_description_item[o.display_page_three,14] = "Straßenrampe 2"
o.display_description_item[o.display_page_three,15] = "Straßenrampe 3"
o.display_description_item[o.display_page_three,16] = "Straßenrampe 4"
o.display_description_item[o.display_page_three,17] = "Straßenschlaufe L"
o.display_description_item[o.display_page_three,18] = "Straßenschlaufe R"
o.display_description_item[o.display_page_three,19] = "Schweb. Platform 2"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Glasfenster - Groß"
o.display_description_item[o.display_page_four,1] = "Glasfenster - Klein 1"
o.display_description_item[o.display_page_four,2] = "Glasfenster - Klein 2"
o.display_description_item[o.display_page_four,3] = "Klimaanlage 1"
o.display_description_item[o.display_page_four,4] = "Klimaanlage 2"
o.display_description_item[o.display_page_four,5] = "Reflektor Teleskop"
o.display_description_item[o.display_page_four,6] = "Refraktor Teleskop"
o.display_description_item[o.display_page_four,7] = "Scene - Röhre - Vertikalverbindung"
o.display_description_item[o.display_page_four,8] = "Scene - Röhre - Horizontalverbindung"
o.display_description_item[o.display_page_four,9] = "Scene - Röhre - Oben"
o.display_description_item[o.display_page_four,10] = "Scene - Röhre - Unten"
o.display_description_item[o.display_page_four,11] = "Strommastkappe"
o.display_description_item[o.display_page_four,12] = "Strommast"
o.display_description_item[o.display_page_four,13] = "Regenschirm"
o.display_description_item[o.display_page_four,14] = "Ziyo's Eiskomet Logo"
o.display_description_item[o.display_page_four,15] = "Icecreme Schweb. 1"
o.display_description_item[o.display_page_four,16] = "Icecreme Schweb. 2"
o.display_description_item[o.display_page_four,17] = "Icecreme Schweb. 3"
o.display_description_item[o.display_page_four,18] = "Icecremeschüssel "
o.display_description_item[o.display_page_four,19] = "Banana Split"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Scene - Stützbalken 1"
o.display_description_item[o.display_page_five,1] = "Scene - Schienenschutz"
o.display_description_item[o.display_page_five,2] = "Scene - Gehweg"
o.display_description_item[o.display_page_five,3] = "Scene - Straße"
o.display_description_item[o.display_page_five,4] = "Scene - Fensterrand"
o.display_description_item[o.display_page_five,5] = "Scene - Plakatwand 1"
o.display_description_item[o.display_page_five,6] = "Scene - Plakatwand 2"
o.display_description_item[o.display_page_five,7] = "Scene - Steinwand 1"
o.display_description_item[o.display_page_five,8] = "Scene - Steinwand 2"
o.display_description_item[o.display_page_five,9] = "Scene - Steinwand 3"
o.display_description_item[o.display_page_five,10] = "Scene - Gebäude 1"
o.display_description_item[o.display_page_five,11] = "Scene - Gebäude 2"
o.display_description_item[o.display_page_five,12] = "Scene - Wasserturm"
o.display_description_item[o.display_page_five,13] = "Scene - Starbuster Poster"
o.display_description_item[o.display_page_five,14] = "Scene - HavocFox Poster"
o.display_description_item[o.display_page_five,15] = "Scene - Werbung 1"
o.display_description_item[o.display_page_five,16] = "Scene - Werbung 2"
o.display_description_item[o.display_page_five,17] = "Scene - Stopschild"
o.display_description_item[o.display_page_five,18] = "Scene - Vorfahrt achten"
o.display_description_item[o.display_page_five,19] = "Scene - Ninjakreuzung"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Mülleimer"
o.display_description_item[o.display_page_six,1] = "Müllcontainer"
o.display_description_item[o.display_page_six,2] = "East Road Schild"
o.display_description_item[o.display_page_six,3] = "North Circle Schild"
o.display_description_item[o.display_page_six,4] = "South Drive Schild"
o.display_description_item[o.display_page_six,5] = "West Lane Schild"
o.display_description_item[o.display_page_six,6] = "Blankoschild"
o.display_description_item[o.display_page_six,7] = "Pfeilzeichen"
o.display_description_item[o.display_page_six,8] = "Nasser-Boden-Schild"
o.display_description_item[o.display_page_six,9] = "Traffic Lights"
o.display_description_item[o.display_page_six,10] = "Lampenposten"
o.display_description_item[o.display_page_six,11] = "Lampenmast 1"
o.display_description_item[o.display_page_six,12] = "Lampenmast 2"
o.display_description_item[o.display_page_six,13] = "Lampenmast 3"
o.display_description_item[o.display_page_six,14] = "Busch"
o.display_description_item[o.display_page_six,15] = "Spezielle Aubergine"
o.display_description_item[o.display_page_six,16] = "Wäscheleine"
o.display_description_item[o.display_page_six,17] = "Zebrastreifenschild"
o.display_description_item[o.display_page_six,18] = "Fußgängerampel"
o.display_description_item[o.display_page_six,19] = "Mülleimer"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Gelber Stützbalken - Komplett 1"
o.display_description_item[o.display_page_seven,1] = "Gelber Stützbalken - Winkel 1"
o.display_description_item[o.display_page_seven,2] = "Gelber Stützbalken - Winkel 2"
o.display_description_item[o.display_page_seven,3] = "Roter Stützbalken - Winkel 1"
o.display_description_item[o.display_page_seven,4] = "Roter Stützbalken - Winkel 2"
o.display_description_item[o.display_page_seven,5] = "Stützbalken - Rot 3"
o.display_description_item[o.display_page_seven,6] = "Gelber Stützbalken - Complete 2"
o.display_description_item[o.display_page_seven,7] = "Gelber Stützbalken - Teil 1"
o.display_description_item[o.display_page_seven,8] = "Gelber Stützbalken - Teil 2"
o.display_description_item[o.display_page_seven,9] = "Gelber Stützbalken - Teil 3"
o.display_description_item[o.display_page_seven,10] = "Gelber Stützbalken - Teil 4"
o.display_description_item[o.display_page_seven,11] = "Gelber Stützbalken - Teil 5"
o.display_description_item[o.display_page_seven,12] = "Gelber Stützbalken - Teil 6"
o.display_description_item[o.display_page_seven,13] = "Konstruktionsbalken - Seitlich"
o.display_description_item[o.display_page_seven,14] = "Verkehrskegel - Groß"
o.display_description_item[o.display_page_seven,15] = "Verkehrskegel - Klein"
o.display_description_item[o.display_page_seven,16] = "Verkehrskegel - 1"
o.display_description_item[o.display_page_seven,17] = "Verkehrskegel - 2"
o.display_description_item[o.display_page_seven,18] = "Verkehrskegel - 3"
o.display_description_item[o.display_page_seven,19] = "Verkehrskegel - 4"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Landsch. - Röhre- Oben"
o.display_description_item[o.display_page_eight,1] = "Landsch. - Röhre - Vertikal"
o.display_description_item[o.display_page_eight,2] = "Landsch. - Röhre - Unten"
o.display_description_item[o.display_page_eight,3] = "Landsch. - Röhre - Horizontal"
o.display_description_item[o.display_page_eight,4] = "Restauranttisch"
o.display_description_item[o.display_page_eight,5] = "Großes Regal"
o.display_description_item[o.display_page_eight,6] = "Horizontale Röhre"
o.display_description_item[o.display_page_eight,7] = "Konstruktionsbalken - Mittel 1"
o.display_description_item[o.display_page_eight,8] = "Konstruktionsbalken - Mittel 2"
o.display_description_item[o.display_page_eight,9] = "Konstruktionsbalken - Mittel 3"
o.display_description_item[o.display_page_eight,10] = "Konstruktionsbalken - Mittel 4"
o.display_description_item[o.display_page_eight,11] = "Landsch. - Lattenzaun"
o.display_description_item[o.display_page_eight,12] = "Stützbalken - Klein"
o.display_description_item[o.display_page_eight,13] = "Metallstacheln - 1"
o.display_description_item[o.display_page_eight,14] = "Metallstacheln - 2"
o.display_description_item[o.display_page_eight,15] = "Metallstacheln - 3"
o.display_description_item[o.display_page_eight,16] = "Metallstacheln - 4"
o.display_description_item[o.display_page_eight,17] = "Leiter 1"
o.display_description_item[o.display_page_eight,18] = "Leiter 2"
o.display_description_item[o.display_page_eight,19] = "Hangbar 1"

//Tile Descriptions (Page 9)
o.display_description_item[o.display_page_nine,0] = "Ziegelplattform - Schrott 1"
o.display_description_item[o.display_page_nine,1] = "Ziegelplattform - Schrott 2"
o.display_description_item[o.display_page_nine,2] = "Ziegelwand - Schrott 1"
o.display_description_item[o.display_page_nine,3] = "Ziegelwand - Schrott 2"
o.display_description_item[o.display_page_nine,4] = "Ziegelwand - Schrott 3"
o.display_description_item[o.display_page_nine,5] = "Ziegelplattform - Schrott 3"
o.display_description_item[o.display_page_nine,6] = "Ziegelwand - Schrott 4"
o.display_description_item[o.display_page_nine,7] = "Ziegelwand - Schrott 5"
o.display_description_item[o.display_page_nine,8] = "Bürgersteig - Schrott 1"
o.display_description_item[o.display_page_nine,9] = "Ziegelwand - Schrott 6"
o.display_description_item[o.display_page_nine,10] = "Ziegelwand - Schrott 7"
o.display_description_item[o.display_page_nine,11] = "Leere Plakatwand - Schrott 1"
o.display_description_item[o.display_page_nine,12] = "Leere Plakatwand - Schrott 2"
o.display_description_item[o.display_page_nine,13] = "Leere Plakatwand - Schrott 3"
o.display_description_item[o.display_page_nine,14] = "Röhre - Schrott 1"
o.display_description_item[o.display_page_nine,15] = "Röhre - Schrott 2"
o.display_description_item[o.display_page_nine,16] = "Röhre - Schrott 3"
o.display_description_item[o.display_page_nine,17] = "Röhre - Schrott 4"
o.display_description_item[o.display_page_nine,18] = "Unbek. Tile"
o.display_description_item[o.display_page_nine,19] = "Unbek. Tile"

//Tile Descriptions (Page 10)
o.display_description_item[o.display_page_ten,0] = "Ziegelwand - Extra 1"
o.display_description_item[o.display_page_ten,1] = "Ziegelwand - Extra 2"
o.display_description_item[o.display_page_ten,2] = "Ziegelwand - Extra 3"
o.display_description_item[o.display_page_ten,3] = "Ziegelwand - Extra 4"
o.display_description_item[o.display_page_ten,4] = "Ziegelwand - Extra 5"
o.display_description_item[o.display_page_ten,5] = "Ziegelwand - Extra 6"
o.display_description_item[o.display_page_ten,6] = "Ziegelwand - Extra 7"
o.display_description_item[o.display_page_ten,7] = "Eckteil 1"
o.display_description_item[o.display_page_ten,8] = "Eckteil 2"
o.display_description_item[o.display_page_ten,9] = "Eckteil 3"
o.display_description_item[o.display_page_ten,10] = "Eckteil 4"
o.display_description_item[o.display_page_ten,11] = "Ziegelwand - Extra 8"
o.display_description_item[o.display_page_ten,12] = "Ziegelwand - Extra 9"
o.display_description_item[o.display_page_ten,13] = "Eckteil 5"
o.display_description_item[o.display_page_ten,14] = "Eckteil 6"
o.display_description_item[o.display_page_ten,15] = "Eckteil 7"
o.display_description_item[o.display_page_ten,16] = "Ziegelplattform - Kante Links"
o.display_description_item[o.display_page_ten,17] = "Ziegelplattform - Mitte"
o.display_description_item[o.display_page_ten,18] = "Ziegelplattform - Kante Rechts"
o.display_description_item[o.display_page_ten,19] = "Ziegelwand - Extra 10"

//Tile Descriptions (Page 11)
o.display_description_item[o.display_page_eleven,0] = "Ziegelschleuße - 1"
o.display_description_item[o.display_page_eleven,1] = "Ziegelschleuße - 2"
o.display_description_item[o.display_page_eleven,2] = "Ziegelwand - Extra 3"
o.display_description_item[o.display_page_eleven,3] = "Ziegelwand - Extra 4"
o.display_description_item[o.display_page_eleven,4] = "Ziegelwand - Extra 5"
o.display_description_item[o.display_page_eleven,5] = "Ziegelwand - Extra 6"
o.display_description_item[o.display_page_eleven,6] = "Ziegelwand - Extra 7"
o.display_description_item[o.display_page_eleven,7] = "Ziegelschleuße - 3"
o.display_description_item[o.display_page_eleven,8] = "Ziegelschleuße - 4"
o.display_description_item[o.display_page_eleven,9] = "Eckteil 3"
o.display_description_item[o.display_page_eleven,10] = "Eckteil 4"
o.display_description_item[o.display_page_eleven,11] = "Ziegelwand - Extra 8"
o.display_description_item[o.display_page_eleven,12] = "Ziegelwand - Extra 9"
o.display_description_item[o.display_page_eleven,13] = "Eckteil 5"
o.display_description_item[o.display_page_eleven,14] = "Eckteil 6"
o.display_description_item[o.display_page_eleven,15] = "Eckteil 7"
o.display_description_item[o.display_page_eleven,16] = "Ziegelplattform - Kante Left"
o.display_description_item[o.display_page_eleven,17] = "Ziegelplattform - Mitte"
o.display_description_item[o.display_page_eleven,18] = "Ziegelplattform - Kante Right"
o.display_description_item[o.display_page_eleven,19] = "Ziegelwand - Extra 10"

//Tile Descriptions (Page 12)
o.display_description_item[o.display_page_twelve,0] = "Ziegelplattform 1"
o.display_description_item[o.display_page_twelve,1] = "Ziegelplattform 2"
o.display_description_item[o.display_page_twelve,2] = "Ziegelwand 1"
o.display_description_item[o.display_page_twelve,3] = "Ziegelwand 2"
o.display_description_item[o.display_page_twelve,4] = "Ziegelwand 3"
o.display_description_item[o.display_page_twelve,5] = "Ziegelwand 4"
o.display_description_item[o.display_page_twelve,6] = "Ziegelblock 1"
o.display_description_item[o.display_page_twelve,7] = "Ziegelblock 2"
o.display_description_item[o.display_page_twelve,8] = "Ziegelblock 3"
o.display_description_item[o.display_page_twelve,9] = "Roter Ziegel"
o.display_description_item[o.display_page_twelve,10] = "Blauer Ziegel"
o.display_description_item[o.display_page_twelve,11] = "Wandteiler 1"
o.display_description_item[o.display_page_twelve,12] = "Wandteiler 2"
o.display_description_item[o.display_page_twelve,13] = "Röhre Flach 1"
o.display_description_item[o.display_page_twelve,14] = "Röhre Flach 2"
o.display_description_item[o.display_page_twelve,15] = "Röhre Flach 3"
o.display_description_item[o.display_page_twelve,16] = "Röhre Flach 4"
o.display_description_item[o.display_page_twelve,17] = "Röhre Endteil 1"
o.display_description_item[o.display_page_twelve,18] = "Röhre Endteil 2"
o.display_description_item[o.display_page_twelve,19] = "Röhre Endteil 3"

//Tile Descriptions (Page 13)
o.display_description_item[o.display_page_thirteen,0] = "Dragon Road Schild"
o.display_description_item[o.display_page_thirteen,1] = "Pheasant Lane Schild"
o.display_description_item[o.display_page_thirteen,2] = "Fantail Road Schild"
o.display_description_item[o.display_page_thirteen,3] = "Panya Plaza Schild"
o.display_description_item[o.display_page_thirteen,4] = "Fuzhu Lane Schild"
o.display_description_item[o.display_page_thirteen,5] = "Qilin Lane Schild"
o.display_description_item[o.display_page_thirteen,6] = "Phoenix Road Schild"
o.display_description_item[o.display_page_thirteen,7] = "Interstate Schild 1"
o.display_description_item[o.display_page_thirteen,8] = "Interstate Schild 2"
o.display_description_item[o.display_page_thirteen,9] = "Interstate Schild Unterst. 1"
o.display_description_item[o.display_page_thirteen,10] = "Interstate Schild Unterst. 2"
o.display_description_item[o.display_page_thirteen,11] = "Interstate Schild Unterst. 3"
o.display_description_item[o.display_page_thirteen,12] = "Interstate Schild Unterst. 4"
o.display_description_item[o.display_page_thirteen,13] = "Dragon Tempel - Stützbalken"
o.display_description_item[o.display_page_thirteen,14] = "Dragon Tempel - Lampe"
o.display_description_item[o.display_page_thirteen,15] = "Dragon Tempel - Tor"
o.display_description_item[o.display_page_thirteen,16] = "Dragon Tempel - Zaun"
o.display_description_item[o.display_page_thirteen,17] = "Dragon Tempel - Zaunposten"
o.display_description_item[o.display_page_thirteen,18] = "Bambuspflanze"
o.display_description_item[o.display_page_thirteen,19] = "Fuzhu Gemälde"

//Tile Descriptions (Page 14)
o.display_description_item[o.display_page_fourteen,0] = "Drachentempel - Drachenstatue"
o.display_description_item[o.display_page_fourteen,1] = "Drachentempel - Fuzhu Statue"
o.display_description_item[o.display_page_fourteen,2] = "Alt Restaurant Schild - Panya Sushi"
o.display_description_item[o.display_page_fourteen,3] = "Drachentempel - Drachengemälde"
o.display_description_item[o.display_page_fourteen,4] = "Timmy Tuna's Sushi Bar für Kinder - Schild"
o.display_description_item[o.display_page_fourteen,5] = "Closed Schild"
o.display_description_item[o.display_page_fourteen,6] = "Open Schild"
o.display_description_item[o.display_page_fourteen,7] = ""
o.display_description_item[o.display_page_fourteen,8] = ""
o.display_description_item[o.display_page_fourteen,9] = ""
o.display_description_item[o.display_page_fourteen,10] = ""
o.display_description_item[o.display_page_fourteen,11] = ""
o.display_description_item[o.display_page_fourteen,12] = ""
o.display_description_item[o.display_page_fourteen,13] = ""
o.display_description_item[o.display_page_fourteen,14] = ""
o.display_description_item[o.display_page_fourteen,15] = ""
o.display_description_item[o.display_page_fourteen,16] = ""
o.display_description_item[o.display_page_fourteen,17] = ""
o.display_description_item[o.display_page_fourteen,18] = ""
o.display_description_item[o.display_page_fourteen,19] = ""
