///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Vegetación"
o.display_page_description[1] = "Árboles/Piedras"
o.display_page_description[2] = "Rocas"
o.display_page_description[3] = "Pendientes"
o.display_page_description[4] = "Decoración"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Hierba 1"
o.display_description_item[o.display_page_one,1] = "Hierba 2"
o.display_description_item[o.display_page_one,2] = "Hierba 3"
o.display_description_item[o.display_page_one,3] = "Tierra 1"
o.display_description_item[o.display_page_one,4] = "Tierra 1"
o.display_description_item[o.display_page_one,5] = "Tierra 1"
o.display_description_item[o.display_page_one,6] = "Hierba 4"
o.display_description_item[o.display_page_one,7] = "Hierba 5"
o.display_description_item[o.display_page_one,8] = "Hierba 6"
o.display_description_item[o.display_page_one,9] = "Hierba 7"
o.display_description_item[o.display_page_one,10] = "Hierba 8"
o.display_description_item[o.display_page_one,11] = "Hierba 9"
o.display_description_item[o.display_page_one,12] = "Hierba 10"
o.display_description_item[o.display_page_one,13] = "Hierba 11"
o.display_description_item[o.display_page_one,14] = "Hierba 12"
o.display_description_item[o.display_page_one,15] = "Hierba 13"
o.display_description_item[o.display_page_one,16] = "Hierba 14"
o.display_description_item[o.display_page_one,17] = "Hierba 15"
o.display_description_item[o.display_page_one,18] = "Esquina de Hierba 1"
o.display_description_item[o.display_page_one,19] = "Esquina de Hierba 2"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Piedra 1"
o.display_description_item[o.display_page_two,1] = "Piedra 2"
o.display_description_item[o.display_page_two,2] = "Piedra 3"
o.display_description_item[o.display_page_two,3] = "Piedra 4"
o.display_description_item[o.display_page_two,4] = "Piedra 5"
o.display_description_item[o.display_page_two,5] = "Piedra 6"
o.display_description_item[o.display_page_two,6] = "Piedra 7"
o.display_description_item[o.display_page_two,7] = "Piedra 8"
o.display_description_item[o.display_page_two,8] = "Rama de Árbol 1"
o.display_description_item[o.display_page_two,9] = "Rama de Árbol 2"
o.display_description_item[o.display_page_two,10] = "Rama de Árbol 3"
o.display_description_item[o.display_page_two,11] = "Rama de Árbol 4"
o.display_description_item[o.display_page_two,12] = "Rama de Árbol 5"
o.display_description_item[o.display_page_two,13] = "Rama de Árbol 6"
o.display_description_item[o.display_page_two,14] = "Tronco de Árbol Pequeño"
o.display_description_item[o.display_page_two,15] = "Tallo de Planta"
o.display_description_item[o.display_page_two,16] = "Flor de Planta"
o.display_description_item[o.display_page_two,17] = ""
o.display_description_item[o.display_page_two,18] = "Esquina de Hierba 3"
o.display_description_item[o.display_page_two,19] = "Esquina de Hierba 4"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Superficie Rocosa 1"
o.display_description_item[o.display_page_three,1] = "Superficie Rocosa 2"
o.display_description_item[o.display_page_three,2] = "Superficie Rocosa 3"
o.display_description_item[o.display_page_three,3] = "Superficie Rocosa 4"
o.display_description_item[o.display_page_three,4] = "Superficie Rocosa 5"
o.display_description_item[o.display_page_three,5] = "Superficie Rocosa 6"
o.display_description_item[o.display_page_three,6] = "Pared Rocosa 1"
o.display_description_item[o.display_page_three,7] = "Pared Rocosa 2"
o.display_description_item[o.display_page_three,8] = "Pared Rocosa 3"
o.display_description_item[o.display_page_three,9] = "Pared Rocosa 4"
o.display_description_item[o.display_page_three,10] = "Pared Rocosa 5"
o.display_description_item[o.display_page_three,11] = "Pared Rocosa 6"
o.display_description_item[o.display_page_three,12] = "Puente con Maleza"
o.display_description_item[o.display_page_three,13] = ""
o.display_description_item[o.display_page_three,14] = ""
o.display_description_item[o.display_page_three,15] = ""
o.display_description_item[o.display_page_three,16] = ""
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Pendiente de Piedra 1"
o.display_description_item[o.display_page_four,1] = "Pendiente de Piedra 2"
o.display_description_item[o.display_page_four,2] = "Pendiente de Árbol 1"
o.display_description_item[o.display_page_four,3] = "Pendiente de Árbol 2"
o.display_description_item[o.display_page_four,4] = ""
o.display_description_item[o.display_page_four,5] = ""
o.display_description_item[o.display_page_four,6] = ""
o.display_description_item[o.display_page_four,7] = "Pendiente de Piedra 3"
o.display_description_item[o.display_page_four,8] = "Pendiente de Piedra 4"
o.display_description_item[o.display_page_four,9] = "Pendiente de Árbol 3"
o.display_description_item[o.display_page_four,10] = "Pendiente de Árbol 4"
o.display_description_item[o.display_page_four,11] = ""
o.display_description_item[o.display_page_four,12] = ""
o.display_description_item[o.display_page_four,13] = ""
o.display_description_item[o.display_page_four,14] = ""
o.display_description_item[o.display_page_four,15] = ""
o.display_description_item[o.display_page_four,16] = ""
o.display_description_item[o.display_page_four,17] = ""
o.display_description_item[o.display_page_four,18] = ""
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Riel de Mano"
o.display_description_item[o.display_page_five,1] = "Linterna 1"
o.display_description_item[o.display_page_five,2] = "Linterna 2"
o.display_description_item[o.display_page_five,3] = "Flor"
o.display_description_item[o.display_page_five,4] = "Pozo con Maleza"
o.display_description_item[o.display_page_five,5] = "Retoño"
o.display_description_item[o.display_page_five,6] = "Raices de Árbol"
o.display_description_item[o.display_page_five,7] = "Tallo de Planta"
o.display_description_item[o.display_page_five,8] = "Segmento de Dragón 1"
o.display_description_item[o.display_page_five,9] = "Segmento de Dragón 2"
o.display_description_item[o.display_page_five,10] = "Segmento de Dragón 3"
o.display_description_item[o.display_page_five,11] = "Segmento de Dragón 4"
o.display_description_item[o.display_page_five,12] = "Vegetación en Segundo Plano"
o.display_description_item[o.display_page_five,13] = "Pieza de Vegetación"
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = ""
o.display_description_item[o.display_page_six,1] = ""
o.display_description_item[o.display_page_six,2] = ""
o.display_description_item[o.display_page_six,3] = ""
o.display_description_item[o.display_page_six,4] = ""
o.display_description_item[o.display_page_six,5] = ""
o.display_description_item[o.display_page_six,6] = ""
o.display_description_item[o.display_page_six,7] = ""
o.display_description_item[o.display_page_six,8] = ""
o.display_description_item[o.display_page_six,9] = ""
o.display_description_item[o.display_page_six,10] = ""
o.display_description_item[o.display_page_six,11] = ""
o.display_description_item[o.display_page_six,12] = ""
o.display_description_item[o.display_page_six,13] = ""
o.display_description_item[o.display_page_six,14] = ""
o.display_description_item[o.display_page_six,15] = ""
o.display_description_item[o.display_page_six,16] = ""
o.display_description_item[o.display_page_six,17] = ""
o.display_description_item[o.display_page_six,18] = ""
o.display_description_item[o.display_page_six,19] = ""
