///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Escadas"
o.display_page_description[1] = "Espinhos"
o.display_page_description[2] = "Conjunto de Vidro"
o.display_page_description[3] = "Trilhos 1"
o.display_page_description[4] = "Trilhos 2"
o.display_page_description[5] = "Decoração"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Escada 1"
o.display_description_item[o.display_page_one,1] = "Escada 2"
o.display_description_item[o.display_page_one,2] = "Escada 3"
o.display_description_item[o.display_page_one,3] = "Escada 4"
o.display_description_item[o.display_page_one,4] = "Escada 5"
o.display_description_item[o.display_page_one,5] = "Escada 6"
o.display_description_item[o.display_page_one,6] = "Barra Suspensa 1"
o.display_description_item[o.display_page_one,7] = "Barra Suspensa 2"
o.display_description_item[o.display_page_one,8] = "Barra Suspensa 3"
o.display_description_item[o.display_page_one,9] = "Barra Suspensa 4"
o.display_description_item[o.display_page_one,10] = "Barra Suspensa 5"
o.display_description_item[o.display_page_one,11] = "Corrimão 2"
o.display_description_item[o.display_page_one,12] = "Corrimão 3"
o.display_description_item[o.display_page_one,13] = "Corrimão 4"
o.display_description_item[o.display_page_one,14] = "Corrimão 5"
o.display_description_item[o.display_page_one,15] = "Corrimão 6"
o.display_description_item[o.display_page_one,16] = "Corrimão 7"
o.display_description_item[o.display_page_one,17] = "Corrimão 8"
o.display_description_item[o.display_page_one,18] = "Corrimão 9"
o.display_description_item[o.display_page_one,19] = "Corrimão 10"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Espinhos de Metal 1"
o.display_description_item[o.display_page_two,1] = "Espinhos de Metal 2"
o.display_description_item[o.display_page_two,2] = "Espinhos de Metal 3"
o.display_description_item[o.display_page_two,3] = "Espinhos de Metal 4"
o.display_description_item[o.display_page_two,4] = "Espinhos de Madeira 1"
o.display_description_item[o.display_page_two,5] = "Espinhos de Madeira 2"
o.display_description_item[o.display_page_two,6] = "Espinhos de Madeira 3"
o.display_description_item[o.display_page_two,7] = "Espinhos de Madeira 4"
o.display_description_item[o.display_page_two,8] = "Espinhos Rochosos 1"
o.display_description_item[o.display_page_two,9] = "Espinhos Rochosos 2"
o.display_description_item[o.display_page_two,10] = "Espinhos Rochosos 3"
o.display_description_item[o.display_page_two,11] = "Espinhos Rochosos 4"
o.display_description_item[o.display_page_two,12] = "Espinhos Rochosos 1"
o.display_description_item[o.display_page_two,13] = "Espinhos Rochosos 2"
o.display_description_item[o.display_page_two,14] = "Espinhos Rochosos 3"
o.display_description_item[o.display_page_two,15] = "Espinhos Rochosos 4"
o.display_description_item[o.display_page_two,16] = "Espinhos Serrilhados 1"
o.display_description_item[o.display_page_two,17] = "Espinhos Serrilhados 2"
o.display_description_item[o.display_page_two,18] = "Espinhos Serrilhados 3"
o.display_description_item[o.display_page_two,19] = "Espinhos Serrilhados 4"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Vidro Preto - Grande"
o.display_description_item[o.display_page_three,1] = "Vidro Preto - Pequeno"
o.display_description_item[o.display_page_three,2] = "Vidro Preto - Médio"
o.display_description_item[o.display_page_three,3] = "Vidro Preto - Vertical"
o.display_description_item[o.display_page_three,4] = "Vidro Preto - Fino"
o.display_description_item[o.display_page_three,5] = "Peça do Loop-De-Loop de Vidro 1"
o.display_description_item[o.display_page_three,6] = "Peça do Loop-De-Loop de Vidro 2"
o.display_description_item[o.display_page_three,7] = "Rampa Longa de Vidro 1"
o.display_description_item[o.display_page_three,8] = "Rampa Longa de Vidro 2"
o.display_description_item[o.display_page_three,9] = "Rampa Curta de Vidro 1"
o.display_description_item[o.display_page_three,10] = "Rampa Curta de Vidro 2"
o.display_description_item[o.display_page_three,11] = "Glass Loop-De-Loop Piece 3"
o.display_description_item[o.display_page_three,12] = "Glass Loop-De-Loop Piece 4"
o.display_description_item[o.display_page_three,13] = "Rampa Longa de Vidro 3"
o.display_description_item[o.display_page_three,14] = "Rampa Longa de Vidro 4"
o.display_description_item[o.display_page_three,15] = "Rampa Curta de Vidro 3"
o.display_description_item[o.display_page_three,16] = "Rampa Curta de Vidro 4"
o.display_description_item[o.display_page_three,17] = "Janela - Verde - Grande"
o.display_description_item[o.display_page_three,18] = "Janela - Verde - Pequeno"
o.display_description_item[o.display_page_three,19] = "Janela - Azul - Pequeno"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Loop de Corrimão - Esquerdo Superior"
o.display_description_item[o.display_page_four,1] = "Loop de Corrimão - Direito Superior"
o.display_description_item[o.display_page_four,2] = "Declive de Corrimão 1"
o.display_description_item[o.display_page_four,3] = "Declive de Corrimão 2"
o.display_description_item[o.display_page_four,4] = "Rampa de Corrimão Esquerda"
o.display_description_item[o.display_page_four,5] = "Corrimão Plano 1"
o.display_description_item[o.display_page_four,6] = "Rampa de Corrimão Direita"
o.display_description_item[o.display_page_four,7] = "Loop de Corrimão - Inferior Esquerdo"
o.display_description_item[o.display_page_four,8] = "Loop de Corrimão - Inferior Direito"
o.display_description_item[o.display_page_four,9] = "Loop de Corrimão - Esquerda - Vermelho"
o.display_description_item[o.display_page_four,10] = "Loop de Corrimão - Plano - Vermelho"
o.display_description_item[o.display_page_four,11] = "Loop de Corrimão - Direita - Vermelho"
o.display_description_item[o.display_page_four,12] = "Corrimão Plano - Madeira"
o.display_description_item[o.display_page_four,13] = "Rampa de Corrimão - Esquerda - Azul"
o.display_description_item[o.display_page_four,14] = "Rampa de Corrimão - Plano - Azul"
o.display_description_item[o.display_page_four,15] = "Rampa de Corrimão - Direito - Azul"
o.display_description_item[o.display_page_four,16] = "Rampa de Corrimão - Direito - Amarelo"
o.display_description_item[o.display_page_four,17] = "Rampa de Corrimão - Plano - Amarelo"
o.display_description_item[o.display_page_four,18] = "Rampa de Corrimão - Esquerda - Amarelo"
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Corrimão Plano - Vermelho 1"
o.display_description_item[o.display_page_five,1] = "Corrimão Plano - Azul 1"
o.display_description_item[o.display_page_five,2] = "Corrimão Plano -  Amarelo 1"
o.display_description_item[o.display_page_five,3] = "Corrimão Plano - Vermelho 2"
o.display_description_item[o.display_page_five,4] = "Corrimão Plano - Azul 2"
o.display_description_item[o.display_page_five,5] = "Corrimão Plano - Amarelo 2"
o.display_description_item[o.display_page_five,6] = ""
o.display_description_item[o.display_page_five,7] = "Corrimão Plano - Vermelho 3"
o.display_description_item[o.display_page_five,8] = "Corrimão Plano - Vermelho 4"
o.display_description_item[o.display_page_five,9] = "Corrimão Plano - Amarelo3"
o.display_description_item[o.display_page_five,10] = "Corrimão Plano - Amarelo 4"
o.display_description_item[o.display_page_five,11] = "Corrimão Plano - Azul 3"
o.display_description_item[o.display_page_five,12] = "Corrimão Plano - Azul 4"
o.display_description_item[o.display_page_five,13] = ""
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Decoração - Reset de Zoom da Câmera"
o.display_description_item[o.display_page_six,1] = "Decoração - Zoom da Câmera 50 Porcento"
o.display_description_item[o.display_page_six,2] = "Decoração - Zoom da Câmera 25 Porcento"
o.display_description_item[o.display_page_six,3] = "Corrimão 11"
o.display_description_item[o.display_page_six,4] = "Corrimão 12"
o.display_description_item[o.display_page_six,5] = "Placa de Rua Pista Oeste"
o.display_description_item[o.display_page_six,6] = "Placa de Rua em Branco"
o.display_description_item[o.display_page_six,7] = "Sinal de Seta"
o.display_description_item[o.display_page_six,8] = "Cesto de Reciclagem"
o.display_description_item[o.display_page_six,9] = "Semáforo"
o.display_description_item[o.display_page_six,10] = "Poste de Luz 1"
o.display_description_item[o.display_page_six,11] = "Poste de Luz 2"
o.display_description_item[o.display_page_six,12] = "Poste de Luz 3"
o.display_description_item[o.display_page_six,13] = "Poste de Luz 4"
o.display_description_item[o.display_page_six,14] = "Arbusto"
o.display_description_item[o.display_page_six,15] = "Berinjela Única"
o.display_description_item[o.display_page_six,16] = "Varal"
o.display_description_item[o.display_page_six,17] = "Passagem de Pedestres"
o.display_description_item[o.display_page_six,18] = "Sinal de Pedestre"
o.display_description_item[o.display_page_six,19] = "Lixeira"
