///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Plattformen"
o.display_page_description[1] = "Wände"
o.display_page_description[2] = "Pisten"
o.display_page_description[3] = "Landschaft"
o.display_page_description[4] = "Extras"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Bodenplatte 1"
o.display_description_item[o.display_page_one,1] = "Bodenplatte 2"
o.display_description_item[o.display_page_one,2] = "Bodenplatte 3"
o.display_description_item[o.display_page_one,3] = "Brückenstück 1"
o.display_description_item[o.display_page_one,4] = "Brückenstück 2"
o.display_description_item[o.display_page_one,5] = "Brückenstück 3"
o.display_description_item[o.display_page_one,6] = "Brückenstück 4"
o.display_description_item[o.display_page_one,7] = "Wandplatte 1"
o.display_description_item[o.display_page_one,8] = "Wandplatte 2"
o.display_description_item[o.display_page_one,9] = "Wandplatte 3"
o.display_description_item[o.display_page_one,10] = "Brückenstück 5"
o.display_description_item[o.display_page_one,11] = "Wall Panel 4"
o.display_description_item[o.display_page_one,12] = "Wandplatte 6"
o.display_description_item[o.display_page_one,13] = "Deckenplatte 1"
o.display_description_item[o.display_page_one,14] = "Deckenplatte 2"
o.display_description_item[o.display_page_one,15] = "Deckenplatte 3"
o.display_description_item[o.display_page_one,16] = "Innenplatte 1"
o.display_description_item[o.display_page_one,17] = "Innenplatte 2"
o.display_description_item[o.display_page_one,18] = "Innenplatte 3"
o.display_description_item[o.display_page_one,19] = "Innenplatte 4"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Wandplatte 4"
o.display_description_item[o.display_page_two,1] = "Wandplatte 5"
o.display_description_item[o.display_page_two,2] = "Wandplatte 6"
o.display_description_item[o.display_page_two,3] = "Gr. Ventilator"
o.display_description_item[o.display_page_two,4] = "Wandplatte 7"
o.display_description_item[o.display_page_two,5] = "Wandplatte 8"
o.display_description_item[o.display_page_two,6] = "Wandplatte 7"
o.display_description_item[o.display_page_two,7] = "Stützbalken 1"
o.display_description_item[o.display_page_two,8] = "Stützbalken 2"
o.display_description_item[o.display_page_two,9] = "Stützbalken 3"
o.display_description_item[o.display_page_two,10] = ""
o.display_description_item[o.display_page_two,11] = ""
o.display_description_item[o.display_page_two,12] = ""
o.display_description_item[o.display_page_two,13] = ""
o.display_description_item[o.display_page_two,14] = ""
o.display_description_item[o.display_page_two,15] = ""
o.display_description_item[o.display_page_two,16] = ""
o.display_description_item[o.display_page_two,17] = ""
o.display_description_item[o.display_page_two,18] = ""
o.display_description_item[o.display_page_two,19] = ""

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Bodenplatte Piste 1"
o.display_description_item[o.display_page_three,1] = "Bodenplatte Piste 2"
o.display_description_item[o.display_page_three,2] = "Brückenpiste 1"
o.display_description_item[o.display_page_three,3] = "Brückenpiste 2"
o.display_description_item[o.display_page_three,4] = "Schw. Plattform 1"
o.display_description_item[o.display_page_three,5] = "Schw. Kugel"
o.display_description_item[o.display_page_three,6] = "Schw. gesprungene Kugel"
o.display_description_item[o.display_page_three,7] = "Schleifenplatte 1"
o.display_description_item[o.display_page_three,8] = "Schleifenplatte 2"
o.display_description_item[o.display_page_three,9] = "Freie Schleife 1"
o.display_description_item[o.display_page_three,10] = "Freie Schleife 2"
o.display_description_item[o.display_page_three,11] = ""
o.display_description_item[o.display_page_three,12] = ""
o.display_description_item[o.display_page_three,13] = "Schleifenplatte  3"
o.display_description_item[o.display_page_three,14] = "Schleifenplatte  4"
o.display_description_item[o.display_page_three,15] = "Freie Schleife 3"
o.display_description_item[o.display_page_three,16] = "Freie Schleife 4"
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Labortür
o.display_description_item[o.display_page_four,1] = "Sicherungskasten (Zu)"
o.display_description_item[o.display_page_four,2] = "Sicherungskasten (Offen)"
o.display_description_item[o.display_page_four,3] = "Kiste mit Schrott 1"
o.display_description_item[o.display_page_four,4] = "Schild für Schutzausrüstung"
o.display_description_item[o.display_page_four,5] = "Kiste mit Schrott 2"
o.display_description_item[o.display_page_four,6] = "Workstation"
o.display_description_item[o.display_page_four,7] = "Base Station"
o.display_description_item[o.display_page_four,8] = "WiFi Station"
o.display_description_item[o.display_page_four,9] = "Deaktivierte Drohne"
o.display_description_item[o.display_page_four,10] = "Geländer"
o.display_description_item[o.display_page_four,11] = ""
o.display_description_item[o.display_page_four,12] = ""
o.display_description_item[o.display_page_four,13] = ""
o.display_description_item[o.display_page_four,14] = ""
o.display_description_item[o.display_page_four,15] = ""
o.display_description_item[o.display_page_four,16] = ""
o.display_description_item[o.display_page_four,17] = ""
o.display_description_item[o.display_page_four,18] = ""
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = ""
o.display_description_item[o.display_page_five,1] = ""
o.display_description_item[o.display_page_five,2] = ""
o.display_description_item[o.display_page_five,3] = ""
o.display_description_item[o.display_page_five,4] = ""
o.display_description_item[o.display_page_five,5] = ""
o.display_description_item[o.display_page_five,6] = ""
o.display_description_item[o.display_page_five,7] = ""
o.display_description_item[o.display_page_five,8] = ""
o.display_description_item[o.display_page_five,9] = ""
o.display_description_item[o.display_page_five,10] = ""
o.display_description_item[o.display_page_five,11] = ""
o.display_description_item[o.display_page_five,12] = ""
o.display_description_item[o.display_page_five,13] = ""
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = ""
o.display_description_item[o.display_page_six,1] = ""
o.display_description_item[o.display_page_six,2] = ""
o.display_description_item[o.display_page_six,3] = ""
o.display_description_item[o.display_page_six,4] = ""
o.display_description_item[o.display_page_six,5] = ""
o.display_description_item[o.display_page_six,6] = ""
o.display_description_item[o.display_page_six,7] = ""
o.display_description_item[o.display_page_six,8] = ""
o.display_description_item[o.display_page_six,9] = ""
o.display_description_item[o.display_page_six,10] = ""
o.display_description_item[o.display_page_six,11] = ""
o.display_description_item[o.display_page_six,12] = ""
o.display_description_item[o.display_page_six,13] = ""
o.display_description_item[o.display_page_six,14] = ""
o.display_description_item[o.display_page_six,15] = ""
o.display_description_item[o.display_page_six,16] = ""
o.display_description_item[o.display_page_six,17] = ""
o.display_description_item[o.display_page_six,18] = ""
o.display_description_item[o.display_page_six,19] = ""

