///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Greens"
o.display_page_description[1] = "Stone/Tree"
o.display_page_description[2] = "Rocks"
o.display_page_description[3] = "Slopes"
o.display_page_description[4] = "Scenery"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Grass 1"
o.display_description_item[o.display_page_one,1] = "Grass 2"
o.display_description_item[o.display_page_one,2] = "Grass 3"
o.display_description_item[o.display_page_one,3] = "Dirt 1"
o.display_description_item[o.display_page_one,4] = "Dirt 1"
o.display_description_item[o.display_page_one,5] = "Dirt 1"
o.display_description_item[o.display_page_one,6] = "Grass 4"
o.display_description_item[o.display_page_one,7] = "Grass 5"
o.display_description_item[o.display_page_one,8] = "Grass 6"
o.display_description_item[o.display_page_one,9] = "Grass 7"
o.display_description_item[o.display_page_one,10] = "Grass 8"
o.display_description_item[o.display_page_one,11] = "Grass 9"
o.display_description_item[o.display_page_one,12] = "Grass 10"
o.display_description_item[o.display_page_one,13] = "Grass 11"
o.display_description_item[o.display_page_one,14] = "Grass 12"
o.display_description_item[o.display_page_one,15] = "Grass 13"
o.display_description_item[o.display_page_one,16] = "Grass 14"
o.display_description_item[o.display_page_one,17] = "Grass 15"
o.display_description_item[o.display_page_one,18] = "Grass Corner 1"
o.display_description_item[o.display_page_one,19] = "Grass Corner 2"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Stone 1"
o.display_description_item[o.display_page_two,1] = "Stone 2"
o.display_description_item[o.display_page_two,2] = "Stone 3"
o.display_description_item[o.display_page_two,3] = "Stone 4"
o.display_description_item[o.display_page_two,4] = "Stone 5"
o.display_description_item[o.display_page_two,5] = "Stone 6"
o.display_description_item[o.display_page_two,6] = "Stone 7"
o.display_description_item[o.display_page_two,7] = "Stone 8"
o.display_description_item[o.display_page_two,8] = "Tree Branch 1"
o.display_description_item[o.display_page_two,9] = "Tree Branch 2"
o.display_description_item[o.display_page_two,10] = "Tree Branch 3"
o.display_description_item[o.display_page_two,11] = "Tree Branch 4"
o.display_description_item[o.display_page_two,12] = "Tree Branch 5"
o.display_description_item[o.display_page_two,13] = "Tree Branch 6"
o.display_description_item[o.display_page_two,14] = "Tree Trunk Small"
o.display_description_item[o.display_page_two,15] = "Plant Stalk"
o.display_description_item[o.display_page_two,16] = "Plant Flower"
o.display_description_item[o.display_page_two,17] = ""
o.display_description_item[o.display_page_two,18] = "Grass Corner 3"
o.display_description_item[o.display_page_two,19] = "Grass Corner 4"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Rock Surface 1"
o.display_description_item[o.display_page_three,1] = "Rock Surface 2"
o.display_description_item[o.display_page_three,2] = "Rock Surface 3"
o.display_description_item[o.display_page_three,3] = "Rock Surface 4"
o.display_description_item[o.display_page_three,4] = "Rock Surface 5"
o.display_description_item[o.display_page_three,5] = "Rock Surface 6"
o.display_description_item[o.display_page_three,6] = "Rock Wall 1"
o.display_description_item[o.display_page_three,7] = "Rock Wall 2"
o.display_description_item[o.display_page_three,8] = "Rock Wall 3"
o.display_description_item[o.display_page_three,9] = "Rock Wall 4"
o.display_description_item[o.display_page_three,10] = "Rock Wall 5"
o.display_description_item[o.display_page_three,11] = "Rock Wall 6"
o.display_description_item[o.display_page_three,12] = "Overgrown Bridge"
o.display_description_item[o.display_page_three,13] = ""
o.display_description_item[o.display_page_three,14] = ""
o.display_description_item[o.display_page_three,15] = ""
o.display_description_item[o.display_page_three,16] = ""
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Stone Slope 1"
o.display_description_item[o.display_page_four,1] = "Stone Slope 2"
o.display_description_item[o.display_page_four,2] = "Tree Slope 1"
o.display_description_item[o.display_page_four,3] = "Tree Slope 2"
o.display_description_item[o.display_page_four,4] = ""
o.display_description_item[o.display_page_four,5] = ""
o.display_description_item[o.display_page_four,6] = ""
o.display_description_item[o.display_page_four,7] = "Stone Slope 3"
o.display_description_item[o.display_page_four,8] = "Stone Slope 4"
o.display_description_item[o.display_page_four,9] = "Tree Slope 3"
o.display_description_item[o.display_page_four,10] = "Tree Slope 4"
o.display_description_item[o.display_page_four,11] = ""
o.display_description_item[o.display_page_four,12] = ""
o.display_description_item[o.display_page_four,13] = ""
o.display_description_item[o.display_page_four,14] = ""
o.display_description_item[o.display_page_four,15] = ""
o.display_description_item[o.display_page_four,16] = ""
o.display_description_item[o.display_page_four,17] = ""
o.display_description_item[o.display_page_four,18] = ""
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Hand Rails"
o.display_description_item[o.display_page_five,1] = "Lantern 1"
o.display_description_item[o.display_page_five,2] = "Lantern 2"
o.display_description_item[o.display_page_five,3] = "Flower"
o.display_description_item[o.display_page_five,4] = "Overgrown Well"
o.display_description_item[o.display_page_five,5] = "Sapling"
o.display_description_item[o.display_page_five,6] = "Tree Root"
o.display_description_item[o.display_page_five,7] = "Plant Stalk"
o.display_description_item[o.display_page_five,8] = "Dragon Segment 1"
o.display_description_item[o.display_page_five,9] = "Dragon Segment 2"
o.display_description_item[o.display_page_five,10] = "Dragon Segment 3"
o.display_description_item[o.display_page_five,11] = "Dragon Segment 4"
o.display_description_item[o.display_page_five,12] = "Vegetation BG"
o.display_description_item[o.display_page_five,13] = "Vegetation Piece"
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = ""
o.display_description_item[o.display_page_six,1] = ""
o.display_description_item[o.display_page_six,2] = ""
o.display_description_item[o.display_page_six,3] = ""
o.display_description_item[o.display_page_six,4] = ""
o.display_description_item[o.display_page_six,5] = ""
o.display_description_item[o.display_page_six,6] = ""
o.display_description_item[o.display_page_six,7] = ""
o.display_description_item[o.display_page_six,8] = ""
o.display_description_item[o.display_page_six,9] = ""
o.display_description_item[o.display_page_six,10] = ""
o.display_description_item[o.display_page_six,11] = ""
o.display_description_item[o.display_page_six,12] = ""
o.display_description_item[o.display_page_six,13] = ""
o.display_description_item[o.display_page_six,14] = ""
o.display_description_item[o.display_page_six,15] = ""
o.display_description_item[o.display_page_six,16] = ""
o.display_description_item[o.display_page_six,17] = ""
o.display_description_item[o.display_page_six,18] = ""
o.display_description_item[o.display_page_six,19] = ""
