///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Piasek"
o.display_page_description[1] = "Platformy"
o.display_page_description[2] = "Rampy"
o.display_page_description[3] = "Zewnątrz"
o.display_page_description[4] = "Sceneria 1"
o.display_page_description[5] = "Sceneria 2"
o.display_page_description[6] = "Extra 1"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Piasek - Lewa Krawędź"
o.display_description_item[o.display_page_one,1] = "Piasek - Powierzchnia"
o.display_description_item[o.display_page_one,2] = "Piasek - Prawa Krawędź"
o.display_description_item[o.display_page_one,3] = "Piasek - Lewa Dolna Krawędź"
o.display_description_item[o.display_page_one,4] = "Piasek - Odwrócona Powierzchnia"
o.display_description_item[o.display_page_one,5] = "Piasek - Prawa Dolna Krawędź"
o.display_description_item[o.display_page_one,6] = "Piasek - Lewa Ściana"
o.display_description_item[o.display_page_one,7] = "Piasek - Prawa Ściana"
o.display_description_item[o.display_page_one,8] = "Piasek - Rampa 1"
o.display_description_item[o.display_page_one,9] = "Piasek - Rampa 2"
o.display_description_item[o.display_page_one,10] = "Piasek - Rampa 3"
o.display_description_item[o.display_page_one,11] = "Piasek - Rampa 4"
o.display_description_item[o.display_page_one,12] = "Warstwa Piaskowca"
o.display_description_item[o.display_page_one,13] = "Kamienna Platforma - Lewa Krawędź"
o.display_description_item[o.display_page_one,14] = "Kamienna Platforma - Środek"
o.display_description_item[o.display_page_one,15] = "Kamienna Platforma - Prawa Krawędź"
o.display_description_item[o.display_page_one,16] = "Marmurowa Powierzchnia - Szeroka"
o.display_description_item[o.display_page_one,17] = "Marmurowa Powierzchnia - Wąska"
o.display_description_item[o.display_page_one,18] = "Marmurowa Ściana - Lewo"
o.display_description_item[o.display_page_one,19] = "Marmurowa Ściana - Prawo"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Drewniana Szyna - 1"
o.display_description_item[o.display_page_two,1] = "Drewniana Szyna - 2"
o.display_description_item[o.display_page_two,2] = "Drewniana Szyna - 3"
o.display_description_item[o.display_page_two,3] = "Drewniana Szyna - 4"
o.display_description_item[o.display_page_two,4] = "Stara Miedziana Podpora 1"
o.display_description_item[o.display_page_two,5] = "Stara Miedziana Podpora 2"
o.display_description_item[o.display_page_two,6] = "Płytka Drewniana Szyna - 1"
o.display_description_item[o.display_page_two,7] = "Płytkie Piaskowe Wzgórze - Lewo"
o.display_description_item[o.display_page_two,8] = "Drewniana Podpora 1"
o.display_description_item[o.display_page_two,9] = "Drewniana Podpora 2"
o.display_description_item[o.display_page_two,10] = "Stara Miedziana Podpora 3"
o.display_description_item[o.display_page_two,11] = "Stara Miedziana Podpora 4"
o.display_description_item[o.display_page_two,12] = "Płytka Drewniana Szyna - 2"
o.display_description_item[o.display_page_two,13] = "Płytkie Piaskowe Wzgórze - Prawo"
o.display_description_item[o.display_page_two,14] = "Kolce 1"
o.display_description_item[o.display_page_two,15] = "Kolce 2"
o.display_description_item[o.display_page_two,16] = "Kolce 3"
o.display_description_item[o.display_page_two,17] = "Kolce 4"
o.display_description_item[o.display_page_two,18] = "Drabina"
o.display_description_item[o.display_page_two,19] = "Uchwyt"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Ćwiartka Kamiennej Rampy 1"
o.display_description_item[o.display_page_three,1] = "Ćwiartka Kamiennej Rampy 2"
o.display_description_item[o.display_page_three,2] = "Ćwiartka Kamiennej Rampy 3"
o.display_description_item[o.display_page_three,3] = "Ćwiartka Kamiennej Rampy 4"
o.display_description_item[o.display_page_three,4] = "Piaskowe Wzgórze - Lewo"
o.display_description_item[o.display_page_three,5] = "Piaskowe Wzgórze - Prawo"
o.display_description_item[o.display_page_three,6] = "Drewniana Skrzynia"
o.display_description_item[o.display_page_three,7] = "Część Pętli 1"
o.display_description_item[o.display_page_three,8] = "Część Pętli 2"
o.display_description_item[o.display_page_three,9] = "Część Pętli 3"
o.display_description_item[o.display_page_three,10] = "Część Pętli 4"
o.display_description_item[o.display_page_three,11] = "Latająca Platforma - 1"
o.display_description_item[o.display_page_three,12] = "Latająca Platforma - 2"
o.display_description_item[o.display_page_three,13] = "Drewniana Pętla 1"
o.display_description_item[o.display_page_three,14] = "Drewniana Pętla 2"
o.display_description_item[o.display_page_three,15] = "Drewniana Pętla 3"
o.display_description_item[o.display_page_three,16] = "Drewniana Pętla 4"
o.display_description_item[o.display_page_three,17] = "Latająca Platforma 3"
o.display_description_item[o.display_page_three,18] = "Latająca Platforma 4"
o.display_description_item[o.display_page_three,19] = "Piętrowa Platforma"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Drewniana Belka - Lewa"
o.display_description_item[o.display_page_four,1] = "Drewniana Belka - Długa"
o.display_description_item[o.display_page_four,2] = "Drewniana Belka - Prawa"
o.display_description_item[o.display_page_four,3] = "Drewniana Belka - Krótka"
o.display_description_item[o.display_page_four,4] = "Drewniana Szyna"
o.display_description_item[o.display_page_four,5] = "Drewniany Wspornik - Lewo"
o.display_description_item[o.display_page_four,6] = "Drewniany Wspornik - Prawo"
o.display_description_item[o.display_page_four,7] = "Drewniany Wspornik - Belka"
o.display_description_item[o.display_page_four,8] = "Drewniana Barierka - Dół"
o.display_description_item[o.display_page_four,9] = "Drewniana Barierka - Góra"
o.display_description_item[o.display_page_four,10] = "Plażowy Prysznic"
o.display_description_item[o.display_page_four,11] = "Plażowa Umywalka"
o.display_description_item[o.display_page_four,12] = "Lampa Uliczna"
o.display_description_item[o.display_page_four,13] = "Przenośna Toaleta - Panowie"
o.display_description_item[o.display_page_four,14] = "Przenośna Toaleta - Panie"
o.display_description_item[o.display_page_four,15] = "Wąskie Okno"
o.display_description_item[o.display_page_four,16] = "Duży Parasol"
o.display_description_item[o.display_page_four,17] = "Mały Parasol"
o.display_description_item[o.display_page_four,18] = "Zamek z Piasku - Mały"
o.display_description_item[o.display_page_four,19] = "Zamek z Piasku - Duży"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Palma - Konar"
o.display_description_item[o.display_page_five,1] = "Palma - Lewy Górny Liść"
o.display_description_item[o.display_page_five,2] = "Palma - Lewy Liść"
o.display_description_item[o.display_page_five,3] = "Palma - Lewy Dolny Liść"
o.display_description_item[o.display_page_five,4] = "Palma - Prawy Górny Liść"
o.display_description_item[o.display_page_five,5] = "Palma - Prawy Liść"
o.display_description_item[o.display_page_five,6] = "Palma - Prawy Dolny Liść"
o.display_description_item[o.display_page_five,7] = "Ślimacza Muszla - Duża"
o.display_description_item[o.display_page_five,8] = "Muszla"
o.display_description_item[o.display_page_five,9] = "Ślimacza Muszla - Mała"
o.display_description_item[o.display_page_five,10] = "Ptasie Gniazdo z Jajkami"
o.display_description_item[o.display_page_five,11] = "Kokos"
o.display_description_item[o.display_page_five,12] = "Kiść Bananów"
o.display_description_item[o.display_page_five,13] = "Znak: Boje"
o.display_description_item[o.display_page_five,14] = "Znak: Silne Prądy"
o.display_description_item[o.display_page_five,15] = "Znak: Śliskie Kamienie"
o.display_description_item[o.display_page_five,16] = "Znak: Nagłe Spadki"
o.display_description_item[o.display_page_five,17] = "Znak: Gniazdo Żółwi"
o.display_description_item[o.display_page_five,18] = "Znak: Nie Karm Mew"
o.display_description_item[o.display_page_five,19] = "Znak: Brak Ratownika"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Mały Kamień"
o.display_description_item[o.display_page_six,1] = "Duży Kamień - 1"
o.display_description_item[o.display_page_six,2] = "Duży Kamień - 2"
o.display_description_item[o.display_page_six,3] = "Duży Kamień - 3"
o.display_description_item[o.display_page_six,4] = "Duży Kamień - 4"
o.display_description_item[o.display_page_six,5] = "Dzika Trawa"
o.display_description_item[o.display_page_six,6] = "Góra Piasku"
o.display_description_item[o.display_page_six,7] = "Stoisko z Owocami"
o.display_description_item[o.display_page_six,8] = "Stoisko z Filtrami Słonecznymi"
o.display_description_item[o.display_page_six,9] = "Stoisko z Pamiątkami"
o.display_description_item[o.display_page_six,10] = "Stoisko z Kawą"
o.display_description_item[o.display_page_six,11] = "Stoisko z Lodami"
o.display_description_item[o.display_page_six,12] = "Stoisko z Hotdogami"
o.display_description_item[o.display_page_six,13] = "Unknown Tile"
o.display_description_item[o.display_page_six,14] = "Unknown Tile"
o.display_description_item[o.display_page_six,15] = "Unknown Tile"
o.display_description_item[o.display_page_six,16] = "Unknown Tile"
o.display_description_item[o.display_page_six,17] = "Unknown Tile"
o.display_description_item[o.display_page_six,18] = "Unknown Tile"
o.display_description_item[o.display_page_six,19] = "Unknown Tile"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Sandstone Rock"
o.display_description_item[o.display_page_seven,1] = "Sand Flat - Small - 1"
o.display_description_item[o.display_page_seven,2] = "Sand Flat - Small - 2"
o.display_description_item[o.display_page_seven,3] = "Sand Flat - Small - 3"
o.display_description_item[o.display_page_seven,4] = "Sand Flat - Small - 4"
o.display_description_item[o.display_page_seven,5] = "Sand Corner Piece - 1"
o.display_description_item[o.display_page_seven,6] = "Sand Corner Piece - 2"
o.display_description_item[o.display_page_seven,7] = "Sand Corner Piece - 3"
o.display_description_item[o.display_page_seven,8] = "Sand Corner Piece - 4"
o.display_description_item[o.display_page_seven,9] = "Sandstone Rock - Small"
o.display_description_item[o.display_page_seven,10] = "Wooden Rail - Vertical - Large"
o.display_description_item[o.display_page_seven,11] = "Wooden Rail - Vertical - Small"
o.display_description_item[o.display_page_seven,12] = "Wooden Support Beam - Small"
o.display_description_item[o.display_page_seven,13] = "Wooden Support Beam - Large"
o.display_description_item[o.display_page_seven,14] = "Construction Beam - Oxidized"
o.display_description_item[o.display_page_seven,15] = "Morning Glory"
o.display_description_item[o.display_page_seven,16] = "Red Camellia Japonica"
o.display_description_item[o.display_page_seven,17] = "Unknown Tile"
o.display_description_item[o.display_page_seven,18] = "Unknown Tile"
o.display_description_item[o.display_page_seven,19] = "Unknown Tile"
