///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Sand"
o.display_page_description[1] = "Platforms"
o.display_page_description[2] = "Slopes"
o.display_page_description[3] = "Outdoors"
o.display_page_description[4] = "Scenery 1"
o.display_page_description[5] = "Scenery 2"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Sand - Surface Edge Left"
o.display_description_item[o.display_page_one,1] = "Sand - Surface Layer"
o.display_description_item[o.display_page_one,2] = "Sand - Surface Edge Right"
o.display_description_item[o.display_page_one,3] = "Sand - Surface Edge Bottom Left"
o.display_description_item[o.display_page_one,4] = "Sand - Surface Layer Inverted"
o.display_description_item[o.display_page_one,5] = "Sand - Surface Edge Bottom Right"
o.display_description_item[o.display_page_one,6] = "Sand - Wall Left"
o.display_description_item[o.display_page_one,7] = "Sand - Wall Right"
o.display_description_item[o.display_page_one,8] = "Sand - Slope 1"
o.display_description_item[o.display_page_one,9] = "Sand - Slope 2"
o.display_description_item[o.display_page_one,10] = "Sand - Slope 3"
o.display_description_item[o.display_page_one,11] = "Sand - Slope 4"
o.display_description_item[o.display_page_one,12] = "Sandstone Layer"
o.display_description_item[o.display_page_one,13] = "Rock Platform - Edge Left"
o.display_description_item[o.display_page_one,14] = "Rock Platform - Surface"
o.display_description_item[o.display_page_one,15] = "Rock Platform - Edge Right"
o.display_description_item[o.display_page_one,16] = "Marble Surface - Wide"
o.display_description_item[o.display_page_one,17] = "Marble Surface - Narrow"
o.display_description_item[o.display_page_one,18] = "Marble Wall - Left"
o.display_description_item[o.display_page_one,19] = "Marble Wall - Right"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Wooden Rail - 1"
o.display_description_item[o.display_page_two,1] = "Wooden Rail - 2"
o.display_description_item[o.display_page_two,2] = "Wooden Rail - 3"
o.display_description_item[o.display_page_two,3] = "Wooden Rail - 4"
o.display_description_item[o.display_page_two,4] = "Old Copper Support Beam 1"
o.display_description_item[o.display_page_two,5] = "Old Copper Support Beam 2"
o.display_description_item[o.display_page_two,6] = "Wooden Rail - Shallow 1"
o.display_description_item[o.display_page_two,7] = "Sand Hill - Shallow Left"
o.display_description_item[o.display_page_two,8] = "Wooden Support Beam 1"
o.display_description_item[o.display_page_two,9] = "Wooden Support Beam 2"
o.display_description_item[o.display_page_two,10] = "Old Copper Support Beam 3"
o.display_description_item[o.display_page_two,11] = "Old Copper Support Beam 3"
o.display_description_item[o.display_page_two,12] = "Wooden Rail - Shallow 2"
o.display_description_item[o.display_page_two,13] = "Sand Hill - Shallow Right"
o.display_description_item[o.display_page_two,14] = "Spikes 1"
o.display_description_item[o.display_page_two,15] = "Spikes 2"
o.display_description_item[o.display_page_two,16] = "Spikes 3"
o.display_description_item[o.display_page_two,17] = "Spikes 4"
o.display_description_item[o.display_page_two,18] = "Ladder"
o.display_description_item[o.display_page_two,19] = "Hangbar"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Quarter Pipe Rock 1"
o.display_description_item[o.display_page_three,1] = "Quarter Pipe Rock 2"
o.display_description_item[o.display_page_three,2] = "Quarter Pipe Rock 3"
o.display_description_item[o.display_page_three,3] = "Quarter Pipe Rock 4"
o.display_description_item[o.display_page_three,4] = "Sand Hill Left"
o.display_description_item[o.display_page_three,5] = "Sand Hill Right"
o.display_description_item[o.display_page_three,6] = "Wooden Crate"
o.display_description_item[o.display_page_three,7] = "Loop-De-Loop Piece 1"
o.display_description_item[o.display_page_three,8] = "Loop-De-Loop Piece 2"
o.display_description_item[o.display_page_three,9] = "Loop-De-Loop Piece 3"
o.display_description_item[o.display_page_three,10] = "Loop-De-Loop Piece 4"
o.display_description_item[o.display_page_three,11] = "Floating Platform - 1"
o.display_description_item[o.display_page_three,12] = "Floating Platform - 2"
o.display_description_item[o.display_page_three,13] = "Wooden Loop 1"
o.display_description_item[o.display_page_three,14] = "Wooden Loop 2"
o.display_description_item[o.display_page_three,15] = "Wooden Loop 3"
o.display_description_item[o.display_page_three,16] = "Wooden Loop 4"
o.display_description_item[o.display_page_three,17] = "Floating Platform 3"
o.display_description_item[o.display_page_three,18] = "Floating Platform 4"
o.display_description_item[o.display_page_three,19] = "Floor-Over-Floor Platform"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Wooden Beam - Left"
o.display_description_item[o.display_page_four,1] = "Wooden Beam - Long"
o.display_description_item[o.display_page_four,2] = "Wooden Beam - Right"
o.display_description_item[o.display_page_four,3] = "Wooden Beam - Small"
o.display_description_item[o.display_page_four,4] = "Wooden Rail"
o.display_description_item[o.display_page_four,5] = "Wooden Support - Left"
o.display_description_item[o.display_page_four,6] = "Wooden Support - Right"
o.display_description_item[o.display_page_four,7] = "Wooden Support - Beam"
o.display_description_item[o.display_page_four,8] = "Wooden Fence - Bottom Piece"
o.display_description_item[o.display_page_four,9] = "Wooden Fence - Top Piece"
o.display_description_item[o.display_page_four,10] = "Outdoor Shower"
o.display_description_item[o.display_page_four,11] = "Outdoor Faucet"
o.display_description_item[o.display_page_four,12] = "Street Lamp"
o.display_description_item[o.display_page_four,13] = "Portable Restroom - Men"
o.display_description_item[o.display_page_four,14] = "Portable Restroom - Women"
o.display_description_item[o.display_page_four,15] = "Narrow Window"
o.display_description_item[o.display_page_four,16] = "Large Umbrella"
o.display_description_item[o.display_page_four,17] = "Small Umbrella"
o.display_description_item[o.display_page_four,18] = "Sand Castle - Small"
o.display_description_item[o.display_page_four,19] = "Sand Castle - Large"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Palm Tree - Trunk"
o.display_description_item[o.display_page_five,1] = "Palm Tree - Leaf Up-Left"
o.display_description_item[o.display_page_five,2] = "Palm Tree - Leaf Left"
o.display_description_item[o.display_page_five,3] = "Palm Tree - Leaf Down-Left"
o.display_description_item[o.display_page_five,4] = "Palm Tree - Leaf Up-Right"
o.display_description_item[o.display_page_five,5] = "Palm Tree - Leaf Right"
o.display_description_item[o.display_page_five,6] = "Palm Tree - Leaf Down-Right"
o.display_description_item[o.display_page_five,7] = "Snail Shell - Large"
o.display_description_item[o.display_page_five,8] = "Seashell"
o.display_description_item[o.display_page_five,9] = "Snail Shell - Small"
o.display_description_item[o.display_page_five,10] = "Bird Eggs Nest"
o.display_description_item[o.display_page_five,11] = "Coconut"
o.display_description_item[o.display_page_five,12] = "Banana Cluster"
o.display_description_item[o.display_page_five,13] = "Warning Sign: BuoyBuoys"
o.display_description_item[o.display_page_five,14] = "Warning Sign: Strong Currents"
o.display_description_item[o.display_page_five,15] = "Warning Sign: Slippery Rocks"
o.display_description_item[o.display_page_five,16] = "Warning Sign: Sudden Drop Off"
o.display_description_item[o.display_page_five,17] = "Warning Sign: Sea Turtle Nest"
o.display_description_item[o.display_page_five,18] = "Warning Sign: Don't Feed Gulls"
o.display_description_item[o.display_page_five,19] = "Warning Sign: No Lifeguard On Duty"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Small Rock"
o.display_description_item[o.display_page_six,1] = "Large Rock - 1"
o.display_description_item[o.display_page_six,2] = "Large Rock - 2"
o.display_description_item[o.display_page_six,3] = "Large Rock - 3"
o.display_description_item[o.display_page_six,4] = "Large Rock - 4"
o.display_description_item[o.display_page_six,5] = "Wild Grass"
o.display_description_item[o.display_page_six,6] = "Sand Pile"
o.display_description_item[o.display_page_six,7] = "Fruit Stand"
o.display_description_item[o.display_page_six,8] = "Sunscreen Stand"
o.display_description_item[o.display_page_six,9] = "Gift Shop Stand"
o.display_description_item[o.display_page_six,10] = "Coffee Stand"
o.display_description_item[o.display_page_six,11] = "Ice Cream Stand"
o.display_description_item[o.display_page_six,12] = "Hot Dog Stand"
o.display_description_item[o.display_page_six,13] = "Unknown Tile"
o.display_description_item[o.display_page_six,14] = "Unknown Tile"
o.display_description_item[o.display_page_six,15] = "Unknown Tile"
o.display_description_item[o.display_page_six,16] = "Unknown Tile"
o.display_description_item[o.display_page_six,17] = "Unknown Tile"
o.display_description_item[o.display_page_six,18] = "Unknown Tile"
o.display_description_item[o.display_page_six,19] = "Unknown Tile"

