///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Zieleń"
o.display_page_description[1] = "Głazy/Drzewa"
o.display_page_description[2] = "Kamienie"
o.display_page_description[3] = "Stoki"
o.display_page_description[4] = "Sceneria"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Trawa 1"
o.display_description_item[o.display_page_one,1] = "Trawa 2"
o.display_description_item[o.display_page_one,2] = "Trawa 3"
o.display_description_item[o.display_page_one,3] = "Ziemia 1"
o.display_description_item[o.display_page_one,4] = "Ziemia 1"
o.display_description_item[o.display_page_one,5] = "Ziemia 1"
o.display_description_item[o.display_page_one,6] = "Trawa 4"
o.display_description_item[o.display_page_one,7] = "Trawa 5"
o.display_description_item[o.display_page_one,8] = "Trawa 6"
o.display_description_item[o.display_page_one,9] = "Trawa 7"
o.display_description_item[o.display_page_one,10] = "Trawa 8"
o.display_description_item[o.display_page_one,11] = "Trawa 9"
o.display_description_item[o.display_page_one,12] = "Trawa 10"
o.display_description_item[o.display_page_one,13] = "Trawa 11"
o.display_description_item[o.display_page_one,14] = "Trawa 12"
o.display_description_item[o.display_page_one,15] = "Trawa 13"
o.display_description_item[o.display_page_one,16] = "Trawa 14"
o.display_description_item[o.display_page_one,17] = "Trawa 15"
o.display_description_item[o.display_page_one,18] = "Trawa - Krawędź 1"
o.display_description_item[o.display_page_one,19] = "Trawa - Krawędź 2"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Głaz 1"
o.display_description_item[o.display_page_two,1] = "Głaz 2"
o.display_description_item[o.display_page_two,2] = "Głaz 3"
o.display_description_item[o.display_page_two,3] = "Głaz 4"
o.display_description_item[o.display_page_two,4] = "Głaz 5"
o.display_description_item[o.display_page_two,5] = "Głaz 6"
o.display_description_item[o.display_page_two,6] = "Głaz 7"
o.display_description_item[o.display_page_two,7] = "Głaz 8"
o.display_description_item[o.display_page_two,8] = "Gałąź 1"
o.display_description_item[o.display_page_two,9] = "Gałąź 2"
o.display_description_item[o.display_page_two,10] = "Gałąź 3"
o.display_description_item[o.display_page_two,11] = "Gałąź 4"
o.display_description_item[o.display_page_two,12] = "Gałąź 5"
o.display_description_item[o.display_page_two,13] = "Gałąź 6"
o.display_description_item[o.display_page_two,14] = "Mały Pień Drzewa"
o.display_description_item[o.display_page_two,15] = "Łodyga"
o.display_description_item[o.display_page_two,16] = "Kwiat"
o.display_description_item[o.display_page_two,17] = ""
o.display_description_item[o.display_page_two,18] = "Trawa - Krawędź 3"
o.display_description_item[o.display_page_two,19] = "Trawa - Krawędź 4"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Kamienna Powierzchnia 1"
o.display_description_item[o.display_page_three,1] = "Kamienna Powierzchnia 2"
o.display_description_item[o.display_page_three,2] = "Kamienna Powierzchnia 3"
o.display_description_item[o.display_page_three,3] = "Kamienna Powierzchnia 4"
o.display_description_item[o.display_page_three,4] = "Kamienna Powierzchnia 5"
o.display_description_item[o.display_page_three,5] = "Kamienna Powierzchnia 6"
o.display_description_item[o.display_page_three,6] = "Kamienna Ściana 1"
o.display_description_item[o.display_page_three,7] = "Kamienna Ściana 2"
o.display_description_item[o.display_page_three,8] = "Kamienna Ściana 3"
o.display_description_item[o.display_page_three,9] = "Kamienna Ściana 4"
o.display_description_item[o.display_page_three,10] = "Kamienna Ściana 5"
o.display_description_item[o.display_page_three,11] = "Kamienna Ściana 6"
o.display_description_item[o.display_page_three,12] = "Porośnięty Most"
o.display_description_item[o.display_page_three,13] = ""
o.display_description_item[o.display_page_three,14] = ""
o.display_description_item[o.display_page_three,15] = ""
o.display_description_item[o.display_page_three,16] = ""
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Kamienna Rampa 1"
o.display_description_item[o.display_page_four,1] = "Kamienna Rampa 2"
o.display_description_item[o.display_page_four,2] = "Drzewna Rampa 1"
o.display_description_item[o.display_page_four,3] = "Drzewna Rampa 2"
o.display_description_item[o.display_page_four,4] = ""
o.display_description_item[o.display_page_four,5] = ""
o.display_description_item[o.display_page_four,6] = ""
o.display_description_item[o.display_page_four,7] = "Kamienna Rampa 3"
o.display_description_item[o.display_page_four,8] = "Kamienna Rampa 4"
o.display_description_item[o.display_page_four,9] = "Drzewna Rampa 3"
o.display_description_item[o.display_page_four,10] = "Drzewna Rampa 4"
o.display_description_item[o.display_page_four,11] = ""
o.display_description_item[o.display_page_four,12] = ""
o.display_description_item[o.display_page_four,13] = ""
o.display_description_item[o.display_page_four,14] = ""
o.display_description_item[o.display_page_four,15] = ""
o.display_description_item[o.display_page_four,16] = ""
o.display_description_item[o.display_page_four,17] = ""
o.display_description_item[o.display_page_four,18] = ""
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Barierki"
o.display_description_item[o.display_page_five,1] = "Latarnia 1"
o.display_description_item[o.display_page_five,2] = "Latarnia 2"
o.display_description_item[o.display_page_five,3] = "Kwiat"
o.display_description_item[o.display_page_five,4] = "Zarośnięta Studnia"
o.display_description_item[o.display_page_five,5] = "Sadzonka"
o.display_description_item[o.display_page_five,6] = "Korzeń"
o.display_description_item[o.display_page_five,7] = "Łodyga"
o.display_description_item[o.display_page_five,8] = "Segment Smoka 1"
o.display_description_item[o.display_page_five,9] = "Segment Smoka 2"
o.display_description_item[o.display_page_five,10] = "Segment Smoka 3"
o.display_description_item[o.display_page_five,11] = "Segment Smoka 4"
o.display_description_item[o.display_page_five,12] = "Roślinne Tło"
o.display_description_item[o.display_page_five,13] = "Roślinność"
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = ""
o.display_description_item[o.display_page_six,1] = ""
o.display_description_item[o.display_page_six,2] = ""
o.display_description_item[o.display_page_six,3] = ""
o.display_description_item[o.display_page_six,4] = ""
o.display_description_item[o.display_page_six,5] = ""
o.display_description_item[o.display_page_six,6] = ""
o.display_description_item[o.display_page_six,7] = ""
o.display_description_item[o.display_page_six,8] = ""
o.display_description_item[o.display_page_six,9] = ""
o.display_description_item[o.display_page_six,10] = ""
o.display_description_item[o.display_page_six,11] = ""
o.display_description_item[o.display_page_six,12] = ""
o.display_description_item[o.display_page_six,13] = ""
o.display_description_item[o.display_page_six,14] = ""
o.display_description_item[o.display_page_six,15] = ""
o.display_description_item[o.display_page_six,16] = ""
o.display_description_item[o.display_page_six,17] = ""
o.display_description_item[o.display_page_six,18] = ""
o.display_description_item[o.display_page_six,19] = ""
