///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Soportes"
o.display_page_description[1] = "Paredes "
o.display_page_description[2] = "Rampas"
o.display_page_description[3] = "Plataformas"
o.display_page_description[4] = "Decoración 1"
o.display_page_description[5] = "Decoración 2"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Bloque de Madera 1"
o.display_description_item[o.display_page_one,1] = "Suelo"
o.display_description_item[o.display_page_one,2] = "Viga de Soporte"
o.display_description_item[o.display_page_one,3] = "Bloque de Madera 2"
o.display_description_item[o.display_page_one,4] = "Bloque de Madera 3"
o.display_description_item[o.display_page_one,5] = "Bloque de Madera 4"
o.display_description_item[o.display_page_one,6] = "Bloque de Madera 5"
o.display_description_item[o.display_page_one,7] = "Bloque de Madera 6"
o.display_description_item[o.display_page_one,8] = "Viga de Soporte 2"
o.display_description_item[o.display_page_one,9] = "Bloque de Madera 7"
o.display_description_item[o.display_page_one,10] = "Bloque de Madera 8"
o.display_description_item[o.display_page_one,11] = "Bloque de Madera 9"
o.display_description_item[o.display_page_one,12] = "Bloque de Madera 10"
o.display_description_item[o.display_page_one,13] = "Viga de Soporte 3"
o.display_description_item[o.display_page_one,14] = "Pieza de Esquina - Izquierda"
o.display_description_item[o.display_page_one,15] = "Viga de Madera"
o.display_description_item[o.display_page_one,16] = "Pieza de Esquina - Derecha"
o.display_description_item[o.display_page_one,17] = "Bloque de Madera 11"
o.display_description_item[o.display_page_one,18] = "Pieza de Esquina - Superior"
o.display_description_item[o.display_page_one,19] = "Pieza de Esquina - Inferior"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Pared - Derecha"
o.display_description_item[o.display_page_two,1] = "Pared - Izquierda"
o.display_description_item[o.display_page_two,2] = "Techo"
o.display_description_item[o.display_page_two,3] = "Piso"
o.display_description_item[o.display_page_two,4] = "Esquina Exterior 1"
o.display_description_item[o.display_page_two,5] = "Esquina Exterior 2"
o.display_description_item[o.display_page_two,6] = "Esquina Exterior 3"
o.display_description_item[o.display_page_two,7] = "Esquina Exterior 4"
o.display_description_item[o.display_page_two,8] = "Esquina Interior 1"
o.display_description_item[o.display_page_two,9] = "Esquina Interior 2"
o.display_description_item[o.display_page_two,10] = "Esquina Interior 3"
o.display_description_item[o.display_page_two,11] = "Esquina Interior 4"
o.display_description_item[o.display_page_two,12] = "Sombra  1"
o.display_description_item[o.display_page_two,13] = "Sombra 1"
o.display_description_item[o.display_page_two,14] = "Sombra 2"
o.display_description_item[o.display_page_two,15] = "Sombra 3"
o.display_description_item[o.display_page_two,16] = "Sombra 4"
o.display_description_item[o.display_page_two,17] = "Escalera"
o.display_description_item[o.display_page_two,18] = "Barra Suspendida 1"
o.display_description_item[o.display_page_two,19] = "Barra Suspendida 2"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Rampa Pequeña - 1"
o.display_description_item[o.display_page_three,1] = "Rampa Pequeña - 2"
o.display_description_item[o.display_page_three,2] = "Rampa Pequeña - 3"
o.display_description_item[o.display_page_three,3] = "Rampa Pequeña - 4"
o.display_description_item[o.display_page_three,4] = "Pieza de Bucle de Hierba 1"
o.display_description_item[o.display_page_three,5] = "Pieza de Bucle de Hierba 2"
o.display_description_item[o.display_page_three,6] = "Piso"
o.display_description_item[o.display_page_three,7] = "Pieza de Bucle 1"
o.display_description_item[o.display_page_three,8] = "Pieza de Bucle 2"
o.display_description_item[o.display_page_three,9] = "Pieza de Bucle 3"
o.display_description_item[o.display_page_three,10] = "Pieza de Bucle 4"
o.display_description_item[o.display_page_three,11] = "Pieza de Bucle de Hierba 3"
o.display_description_item[o.display_page_three,12] = "Pieza de Bucle de Hierba 4"
o.display_description_item[o.display_page_three,13] = "Pieza de Bucle Doble-Cara 1"
o.display_description_item[o.display_page_three,14] = "Pieza de Bucle Doble-Cara 2"
o.display_description_item[o.display_page_three,15] = "Pieza de Bucle Doble-Cara 3"
o.display_description_item[o.display_page_three,16] = "Pieza de Bucle Doble-Cara 4"
o.display_description_item[o.display_page_three,17] = "Pieza Larga en Pendiente 1"
o.display_description_item[o.display_page_three,18] = "Pieza Larga en Pendiente 2"
o.display_description_item[o.display_page_three,19] = "Plataforma Piso-Sobre-Piso"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Pendiente - Simple 1"
o.display_description_item[o.display_page_four,1] = "Pendiente - Simple 2"
o.display_description_item[o.display_page_four,2] = "Pendiente - Escarpada 1"
o.display_description_item[o.display_page_four,3] = "Pendiente - Escarpada 2"
o.display_description_item[o.display_page_four,4] = "Pendiente - Simple 3"
o.display_description_item[o.display_page_four,5] = "Superficie Plana 1"
o.display_description_item[o.display_page_four,6] = "Pendiente - Simple 4"
o.display_description_item[o.display_page_four,7] = "Plataforma Flotante 1"
o.display_description_item[o.display_page_four,8] = "Plataforma Flotante 2"
o.display_description_item[o.display_page_four,9] = "Plataforma Flotante 3"
o.display_description_item[o.display_page_four,10] = "Plataforma Flotante 4"
o.display_description_item[o.display_page_four,11] = "Plataforma Flotante 5"
o.display_description_item[o.display_page_four,12] = "Sendero Invertido de Plataforma"
o.display_description_item[o.display_page_four,13] = "Bloque de Hierba"
o.display_description_item[o.display_page_four,14] = "Bloque de Tierra"
o.display_description_item[o.display_page_four,15] = "Unknown Tile 3"
o.display_description_item[o.display_page_four,16] = "Unknown Tile 4"
o.display_description_item[o.display_page_four,17] = "Unknown Tile 5"
o.display_description_item[o.display_page_four,18] = "Unknown Tile 6"
o.display_description_item[o.display_page_four,19] = "Unknown Tile 7"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Ambiente - Puente 1"
o.display_description_item[o.display_page_five,1] = "Ambiente - Columnan"
o.display_description_item[o.display_page_five,2] = "Ambiente - Arbol 1"
o.display_description_item[o.display_page_five,3] = "Ambiente - Rejilla"
o.display_description_item[o.display_page_five,4] = "Ambiente - Fondo"
o.display_description_item[o.display_page_five,5] = "Ambiente - Plataforma"
o.display_description_item[o.display_page_five,6] = "Ambiente - Fusuma 1"
o.display_description_item[o.display_page_five,7] = "Ambiente - Mural"
o.display_description_item[o.display_page_five,8] = "Ambiente - Cortinas"
o.display_description_item[o.display_page_five,9] = "Ambiente - Pieza Final de Cortina"
o.display_description_item[o.display_page_five,10] = "Ambiente- Riel 1"
o.display_description_item[o.display_page_five,11] = "Ambiente - Soporte"
o.display_description_item[o.display_page_five,12] = "Ambiente - Linterna 1"
o.display_description_item[o.display_page_five,13] = "Ambiente - Fusuma 2"
o.display_description_item[o.display_page_five,14] = "Ambiente - Arbol 2"
o.display_description_item[o.display_page_five,15] = "Ambiente - Arbol 3"
o.display_description_item[o.display_page_five,16] = "Ambiente - Arbol 3 - Extra"
o.display_description_item[o.display_page_five,17] = "Ambiente - Arbol 4"
o.display_description_item[o.display_page_five,18] = "Ambiente - Bandera 1"
o.display_description_item[o.display_page_five,19] = "Ambiente - Linterna 2"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Sombra 16x16"
o.display_description_item[o.display_page_six,1] = "Sombra 32x32"
o.display_description_item[o.display_page_six,2] = "Sombra 64x64"
o.display_description_item[o.display_page_six,3] = "Sombra 96x96"
o.display_description_item[o.display_page_six,4] = "Sombra 16x96"
o.display_description_item[o.display_page_six,5] = "Sombra 96x16"
o.display_description_item[o.display_page_six,6] = "Sombra 128x128"
o.display_description_item[o.display_page_six,7] = "Sombra 128x128"
o.display_description_item[o.display_page_six,8] = "Ambiente  - Mesa Grande"
o.display_description_item[o.display_page_six,9] = "Ambiente - Mesa Pequeña"
o.display_description_item[o.display_page_six,10] = "Unknown Tile"
o.display_description_item[o.display_page_six,11] = "Unknown Tile"
o.display_description_item[o.display_page_six,12] = "Unknown Tile"
o.display_description_item[o.display_page_six,13] = "Unknown Tile"
o.display_description_item[o.display_page_six,14] = "Unknown Tile"
o.display_description_item[o.display_page_six,15] = "Unknown Tile"
o.display_description_item[o.display_page_six,16] = "Unknown Tile"
o.display_description_item[o.display_page_six,17] = "Unknown Tile"
o.display_description_item[o.display_page_six,18] = "Unknown Tile"
o.display_description_item[o.display_page_six,19] = "Unknown Tile"
