///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Лестницы"
o.display_page_description[1] = "Шипы"
o.display_page_description[2] = "Стёкла"
o.display_page_description[3] = "Рельсы 1"
o.display_page_description[4] = "Рельсы 2"
o.display_page_description[5] = "Декор"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Лестница 1"
o.display_description_item[o.display_page_one,1] = "Лестница 2"
o.display_description_item[o.display_page_one,2] = "Лестница 3"
o.display_description_item[o.display_page_one,3] = "Лестница 4"
o.display_description_item[o.display_page_one,4] = "Лестница 5"
o.display_description_item[o.display_page_one,5] = "Лестница 6"
o.display_description_item[o.display_page_one,6] = "Перекладина 1"
o.display_description_item[o.display_page_one,7] = "Перекладина 2"
o.display_description_item[o.display_page_one,8] = "Перекладина 3"
o.display_description_item[o.display_page_one,9] = "Перекладина 4"
o.display_description_item[o.display_page_one,10] = "Перекладина 5"
o.display_description_item[o.display_page_one,11] = "Рельсы 2"
o.display_description_item[o.display_page_one,12] = "Рельсы 3"
o.display_description_item[o.display_page_one,13] = "Рельсы 4"
o.display_description_item[o.display_page_one,14] = "Рельсы 5"
o.display_description_item[o.display_page_one,15] = "Рельсы 6"
o.display_description_item[o.display_page_one,16] = "Рельсы 7"
o.display_description_item[o.display_page_one,17] = "Рельсы 8"
o.display_description_item[o.display_page_one,18] = "Рельсы 9"
o.display_description_item[o.display_page_one,19] = "Рельсы 10"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Металлические Шипы 1"
o.display_description_item[o.display_page_two,1] = "Металлические Шипы 2"
o.display_description_item[o.display_page_two,2] = "Металлические Шипы 3"
o.display_description_item[o.display_page_two,3] = "Металлические Шипы 4"
o.display_description_item[o.display_page_two,4] = "Деревянные Шипы 1"
o.display_description_item[o.display_page_two,5] = "Деревянные Шипы 2"
o.display_description_item[o.display_page_two,6] = "Деревянные Шипы 3"
o.display_description_item[o.display_page_two,7] = "Деревянные Шипы 4"
o.display_description_item[o.display_page_two,8] = "Каменные Шипы 1"
o.display_description_item[o.display_page_two,9] = "Каменные Шипы 2"
o.display_description_item[o.display_page_two,10] = "Каменные Шипы 3"
o.display_description_item[o.display_page_two,11] = "Каменные Шипы 4"
o.display_description_item[o.display_page_two,12] = "Деревянные Шипы 1"
o.display_description_item[o.display_page_two,13] = "Деревянные Шипы 2"
o.display_description_item[o.display_page_two,14] = "Деревянные Шипы 3"
o.display_description_item[o.display_page_two,15] = "Деревянные Шипы 4"
o.display_description_item[o.display_page_two,16] = "Зазубренные Шипы 1"
o.display_description_item[o.display_page_two,17] = "Зазубренные Шипы 2"
o.display_description_item[o.display_page_two,18] = "Зазубренные Шипы 3"
o.display_description_item[o.display_page_two,19] = "Зазубренные Шипы 4"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Затемнённое Стекло - Большое"
o.display_description_item[o.display_page_three,1] = "Затемнённое Стекло - Малое"
o.display_description_item[o.display_page_three,2] = "Затемнённое Стекло - Среднее"
o.display_description_item[o.display_page_three,3] = "Затемнённое Стекло - Вертикальное"
o.display_description_item[o.display_page_three,4] = "Затемнённое Стекло - Тонкое"
o.display_description_item[o.display_page_three,5] = "Часть Стеклянной Петли 1"
o.display_description_item[o.display_page_three,6] = "Часть Стеклянной Петли 2"
o.display_description_item[o.display_page_three,7] = "Длинная Стеклянная Рампа 1"
o.display_description_item[o.display_page_three,8] = "Длинная Стеклянная Рампа 2"
o.display_description_item[o.display_page_three,9] = "Короткая Стеклянная Рампа 1"
o.display_description_item[o.display_page_three,10] = "Короткая Стеклянная Рампа 2"
o.display_description_item[o.display_page_three,11] = "Часть Стеклянной Петли 3"
o.display_description_item[o.display_page_three,12] = "Часть Стеклянной Петли 4"
o.display_description_item[o.display_page_three,13] = "Длинная Стеклянная Рампа 3"
o.display_description_item[o.display_page_three,14] = "Длинная Стеклянная Рампа 4"
o.display_description_item[o.display_page_three,15] = "Короткая Стеклянная Рампа 3"
o.display_description_item[o.display_page_three,16] = "Короткая Стеклянная Рампа 4"
o.display_description_item[o.display_page_three,17] = "Стеклянное Окно - Зелёное - Большое"
o.display_description_item[o.display_page_three,18] = "Стеклянное Окно - Зелёное - Малое"
o.display_description_item[o.display_page_three,19] = "Стеклянное Окно - Синее - Малое"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Рельсовая Петля - Левая Верхняя Часть"
o.display_description_item[o.display_page_four,1] = "Рельсовая Петля - Правая Верхняя Часть"
o.display_description_item[o.display_page_four,2] = "Рельсовый Спуск 1"
o.display_description_item[o.display_page_four,3] = "Рельсовый Спуск 2"
o.display_description_item[o.display_page_four,4] = "Левая Рельсовая Рампа"
o.display_description_item[o.display_page_four,5] = "Плосские Рельсы 1"
o.display_description_item[o.display_page_four,6] = "Правая Рельсовая Рампа"
o.display_description_item[o.display_page_four,7] = "Рельсовая Петля - Левая Нижняя Часть"
o.display_description_item[o.display_page_four,8] = "Рельсовая Петля - Правая Нижняя Часть"
o.display_description_item[o.display_page_four,9] = "Rail Ramp - Left - Red"
o.display_description_item[o.display_page_four,10] = "Рельсовая Рампа - Плосская - Красная"
o.display_description_item[o.display_page_four,11] = "Рельсовая Рампа - Правая - Красная"
o.display_description_item[o.display_page_four,12] = "Плосские Рельсы - Дерево"
o.display_description_item[o.display_page_four,13] = "Рельсовая Рампа - Левая - Синяя"
o.display_description_item[o.display_page_four,14] = "Рельсовая Рампа - Плосская - Синяя"
o.display_description_item[o.display_page_four,15] = "Рельсовая Рампа - Правая - Синяя"
o.display_description_item[o.display_page_four,16] = "Рельсовая Рампа - Правая - Жёлтая"
o.display_description_item[o.display_page_four,17] = "Рельсовая Рампа - Плосская - Жёлтая"
o.display_description_item[o.display_page_four,18] = "Рельсовая Рампа - Левая - Желтая"
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Плосские Рельсы - Красные 1"
o.display_description_item[o.display_page_five,1] = "Плосские Рельсы - Синие 1"
o.display_description_item[o.display_page_five,2] = "Плосские Рельсы - Жёлтые 1"
o.display_description_item[o.display_page_five,3] = "Плосские Рельсы - Красные 2"
o.display_description_item[o.display_page_five,4] = "Плосские Рельсы - Синие 2"
o.display_description_item[o.display_page_five,5] = "Плосские Рельсы - Жёлтые 2"
o.display_description_item[o.display_page_five,6] = ""
o.display_description_item[o.display_page_five,7] = "Плосские Рельсы - Красные 3"
o.display_description_item[o.display_page_five,8] = "Плосские Рельсы - Красные 4"
o.display_description_item[o.display_page_five,9] = "Плосские Рельсы - Жёлтые 3"
o.display_description_item[o.display_page_five,10] = "Плосские Рельсы - Жёлтые 4"
o.display_description_item[o.display_page_five,11] = "Плосские Рельсы - Синие 3"
o.display_description_item[o.display_page_five,12] = "Плосские Рельсы - Синие 4"
o.display_description_item[o.display_page_five,13] = ""
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Декор - Масштаб По Умолчанию"
o.display_description_item[o.display_page_six,1] = "Декор - Масштаб 50 Процентов"
o.display_description_item[o.display_page_six,2] = "Декор - Масштаб 25 Процентов"
o.display_description_item[o.display_page_six,3] = "Рельсы 11"
o.display_description_item[o.display_page_six,4] = "Рельсы 12"
o.display_description_item[o.display_page_six,5] = "Уличный Знак Вест Лэйн"
o.display_description_item[o.display_page_six,6] = "Пустой Уличный Знак"
o.display_description_item[o.display_page_six,7] = "Стрелка"
o.display_description_item[o.display_page_six,8] = "Мусорная Корзина"
o.display_description_item[o.display_page_six,9] = "Светофор"
o.display_description_item[o.display_page_six,10] = "Фонарь"
o.display_description_item[o.display_page_six,11] = "Фонарный Столб 1"
o.display_description_item[o.display_page_six,12] = "Фонарный Столб 2"
o.display_description_item[o.display_page_six,13] = "Фонарный Столб 3"
o.display_description_item[o.display_page_six,14] = "Куст"
o.display_description_item[o.display_page_six,15] = "Тот Самый Баклажан"
o.display_description_item[o.display_page_six,16] = "Вешалка С Одеждой"
o.display_description_item[o.display_page_six,17] = "Знак Пешеходный Переход"
o.display_description_item[o.display_page_six,18] = "Предупреждающий Сигнал"
o.display_description_item[o.display_page_six,19] = "Мусорка"
