//For calling in Story Mode object only, call BEFORE NPC spawn scripts
//Language Array; 0 = English; 1 = Portuguese; 2 = Polish; 3 = Spanish; 4 = German; 5 = Russian
var lang_num = 1;
//Mall NPCs 1
lang_npc[lang_num,0]  = "Eu acho que esse sorvete ficaria melhor com vidro quebrado!" //Jett
lang_npc[lang_num,1]  = "Crunch crunch #crunch!"                                    //Jett
lang_npc[lang_num,2]  = "BOLAS BOLAS BOLAS BOLAS BOLAS!!!"                          //Marshmallow
lang_npc[lang_num,3]  = "Certo! Nós podemos comprar por suprimentos por agora."     //Lilac
lang_npc[lang_num,4]  = "Nós não podemos esquecer da nossa viagem ás montanhas!"    //Lilac
lang_npc[lang_num,5]  = "Bem-Vindo a Tuna do Timmy!"                                //Beibo
lang_npc[lang_num,6]  = "Gostaria de uma mesa para três?"                           //Beibo
lang_npc[lang_num,7]  = "...Quando foi que esse lixo instalou um botão de pânico?"  //Beibo
lang_npc[lang_num,8]  = "Muito suspeito dos robbits aqui... quem está fazendo eles?" //Jamie
lang_npc[lang_num,9]  = "Ficaria de olho nela se eu fosse tu."                      //Jamie
lang_npc[lang_num,10]  = "Estou tão feliz que minha irmã conseguiu o trabalho de assistente!" //Libbie
lang_npc[lang_num,11]  = "Eu já ama e eu terei um momento só para mim!"             //Libbie
lang_npc[lang_num,12]  = "Gostaria que eu tirasse uma foto?"                        //Uny
lang_npc[lang_num,13]  = "Fica parado! #*click*"                                    //Uny
lang_npc[lang_num,14]  = "Bem vindo ao Shopping Shang Mu! Você deve ser novo."      //Mirdin
lang_npc[lang_num,15]  = "Bem vindo ao Shopping Shang Mu!"                          //Mirdin
lang_npc[lang_num,16]  = "(Não ache que eu não sei quem você é, idiota!)"           //Mirdin
lang_npc[lang_num,17]  = "Eu olhei e olhei em todo lugar!"                          //Chiasa
lang_npc[lang_num,18]  = "...Ninguém tem nuggitos de frango!"                       //Chiasa
lang_npc[lang_num,19]  = "PODE COMER UM BUFÊ INTEIRO?!?!?"                          //Marshmallow
lang_npc[lang_num,20]  = "CHIASA POR FAVOR VAMOS LÁAAAAA!!!"                        //Marshmallow
lang_npc[lang_num,21]  = "Mmm! Mmm! Mmm! Esses rolinhos primavera acertou em cheio!" //Tiwi
lang_npc[lang_num,22]  = "Harige consegue fazer um sanduíche de grama gostoso!"     //Tiwi
lang_npc[lang_num,23]  = "Olá! O que você vai querer hoje?"                         //Harige
lang_npc[lang_num,24]  = "Temos o especial Tigela do Zao!"                          //Harige
lang_npc[lang_num,25]  = "Eu terei lanche aqui! A comida cheira tão bem!"           //Stella
lang_npc[lang_num,26]  = "Ehehe! Esse cachorrinho tem um rosto igual o meu!"        //Milla
lang_npc[lang_num,27]  = "Espera... Por que eu não tenho um focinho desse jeito?"   //Milla
lang_npc[lang_num,28]  = "Não se importe comigo... estou olhando para essas bikes." //Ryusei
lang_npc[lang_num,29]  = "Não que Shy deixaria subir em uma..."                     //Ryusei
lang_npc[lang_num,30]  = "Você está completamente correto que eu não vou deixar, besta!" //Shy
lang_npc[lang_num,31]  = "Ooh! Eu gostaria de uma amostra de sushi!"                //Libbie Dark
lang_npc[lang_num,32]  = "Sprindog?! O que isso realmente faz?"                     //Astum
lang_npc[lang_num,33]  = "Eí! Vocês garotas mandaram bem lá fora hoje."             //Maria
lang_npc[lang_num,34]  = "Interessada em uma entrevista exclusiva?"                 //Maria
lang_npc[lang_num,35]  = "Minha segurança está te observando!"                      //Maria
lang_npc[lang_num,36]  = "Ha! Eu sabia que Zao estava com os pássaros.."            //Carol
lang_npc[lang_num,37]  = "Mas isso daqui leva o bolo!"                              //Carol
lang_npc[lang_num,38]  = "Bom dia, crianças!"                                       //Savvy
lang_npc[lang_num,39]  = "Bom dia, #Lilac! Estou tão orgulhosa de você."            //Savvy
lang_npc[lang_num,40]  = "Seu trabalho difícil está salvando vidas, jovemzinha"     //Savvy
lang_npc[lang_num,41]  = "Bom dia, Carol! Já finalizou sua papelada?"               //Savvy
lang_npc[lang_num,42]  = "Deixe-me saber se você precisa de ajuda!!!"               //Savvy
lang_npc[lang_num,43]  = "Oh, Milla! Estou tão feliz em ver você, hehe!"            //Savvy
lang_npc[lang_num,44]  = "Você é um material de fogo, garota! Isso mesmo!"          //Savvy
lang_npc[lang_num,45]  = "Você não é o primeiro Scarf que eu derrubei, filho."      //Savvy

//Mall NPCs 1
lang_npc[lang_num,46]  = "Sra. Cosmos, o que faz acordada tão cedo?"                //Jamie
lang_npc[lang_num,47]  = "Cê não ficou acordada a noite toda?"                      //Jamie
lang_npc[lang_num,48]  = "Oh! Temos um tour de investidores vindo em breve."        //Vela
lang_npc[lang_num,49]  = "Eles são um monte de problemas, mas precisamos de fundos!" //Vela
lang_npc[lang_num,50]  = "Eu posso fazer você desaparecer a qualquer momento, sabia?" //Mirdin
lang_npc[lang_num,51]  = "Esses nuggitos de frango são estranhos!"                  //Chiasa
lang_npc[lang_num,52]  = "O que eu estou fazendo nesse kiddy #joint, você pergunta?" //Spade
lang_npc[lang_num,53]  = "Você não quer saber quem eu estou espionando?!"           //Spade
lang_npc[lang_num,54]  = "Ainda não quer o meu estoque nabo, é?"                    //Boss
lang_npc[lang_num,55]  = "Ser babás de pestinhas realmente é divertido."            //Iris
lang_npc[lang_num,56]  = "Aqueles dois já explodiram uma privada..."                //Iris
lang_npc[lang_num,57]  = "Ele tem o jeito com as palavras!"                         //Bird Guard (Female)
lang_npc[lang_num,58]  = "Weh"                                                      //Bird Guard (Male)
lang_npc[lang_num,59]  = "Ha!"                                                      //Neera
lang_npc[lang_num,60]  = "Não gaste em tudo em um só lugar, Lilac!"                 //Neera
lang_npc[lang_num,61]  = "Eu sei que não vai, Carol por outro lado..."              //Neera
lang_npc[lang_num,62]  = "Não gaste tudo em um só lugar, Gata-Selvagem!"            //Neera
lang_npc[lang_num,63]  = "Eu vi você de olho naquela motorcicleta dourada..."       //Neera
lang_npc[lang_num,64]  = "Seja sábia com o seu dinheiro, Milla!"                    //Neera
lang_npc[lang_num,65]  = "Eu vi você de olho naquela motorcicleta dourada..."       //Neera
lang_npc[lang_num,66]  = "Você tem sorte que eu tenho prioridades, Spade."          //Neera
lang_npc[lang_num,67]  = "Gong está ocupado brincando de guarda de trânsito agora mesmo." //Neera
lang_npc[lang_num,68]  = "Mmm! Mhm!"                                                //Tiwi
lang_npc[lang_num,69]  = "Especial de Hoje: Pizza Fazedor de Viúvas!"               //Harige
lang_npc[lang_num,70]  = "Oh! Eu quero uma amostra!"                                //Stella
lang_npc[lang_num,71]  = "Oh, bom dia, estudante!"                                  //Libbie Dark
lang_npc[lang_num,72]  = "Eu vou finalizar sua papelada depois, eu prometo!"        //Libbie Dark
lang_npc[lang_num,73]  = "Ouvi rumores de um dragão na montanha!"                   //Maria
lang_npc[lang_num,74]  = "Tive um sentimento de que vocês três saberiam mais!"      //Maria
lang_npc[lang_num,75]  = "Desculpa! você não é a pessoa de que eu procuro..."       //Maria
lang_npc[lang_num,76]  = "Aí sim! Isso é de mais!"                                  //Carol
lang_npc[lang_num,77]  = "Oh! Eu quero uma bike igual a de Carol!"                  //Milla
lang_npc[lang_num,78]  = "...Mas eu preciso salvar para uma casa primeiro!"         //Milla
lang_npc[lang_num,79]  = "Bom dia, crianças!"                                       //Savvy
lang_npc[lang_num,80]  = "Espero que tenha um bom fim de semana, Lilac!"            //Savvy
lang_npc[lang_num,81]  = "É melhor acreditar que você mereceu!"                     //Savvy
lang_npc[lang_num,82]  = "Tenha um bom fim de semana, Carol!"                       //Savvy
lang_npc[lang_num,83]  = "Não esqueça do seu dever de casa!"                        //Savvy
lang_npc[lang_num,84]  = "Eu espero que você tenha um fim de semana incrível, Milla!" //Savvy
lang_npc[lang_num,85]  = "Deixe-me saber caso você acenda mais fogos de artíficio!" //Savvy
lang_npc[lang_num,86]  = "Shaun's está te observando agora, filho!"                 //Savvy

//Mall NPCs 3
lang_npc[lang_num,87]  = "A Pizza Fazedor de Viúvas tem um cheiro tão nojento! Eu quero!" //Jett
lang_npc[lang_num,88]  = "Mas você tem bagels, Sr. Gatinho?"                        //Marshmallow
lang_npc[lang_num,89]  = "Eu quero um bagel de bacon com molho de pepino!"          //Marshmallow
lang_npc[lang_num,90]  = "Melhor não esquecermos da nossa viajem á praia!"          //Lilac
lang_npc[lang_num,91]  = "Oh minhas gemas! Tanto progresso, tão pouco tempo!"       //Jamie
lang_npc[lang_num,92]  = "'Galinha do Oceano'?! Mas que golpe!"                     //Chiasa
lang_npc[lang_num,93]  = "Isso não é frango! Eca!"                                  //Chiasa
lang_npc[lang_num,94]  = "O que quer dizer que eu fiz absolutamente nada o dia inteiro?" //Spade
lang_npc[lang_num,95]  = "Eu não vou negar essas alegações!"                        //Spade
lang_npc[lang_num,96]  = "Não consigo impedí-los de escorregar lá pra baixo na escada-rolante..." //Iris
lang_npc[lang_num,97]  = "Bom trabalho, garotas! O Magister ficará satisfeito."     //Neera
lang_npc[lang_num,98]  = "E sem dano de propriedade- dessa vez!"                    //Neera
lang_npc[lang_num,99]  = "Você tem sorte que eu tenho prioridades, Spade."          //Neera
lang_npc[lang_num,100] = "Gong está ocupado brincando de guarda de trânsito agora mesmo." //Neera
lang_npc[lang_num,101] = "Então, pode ser que eu tenha avisado no trabalho que não iria por estar doente..." //Tiwi
lang_npc[lang_num,102] = "TALVEZ eu tenha comido muitos sanduíches!"                //Tiwi
lang_npc[lang_num,103] = "Especial de Hoje:Encanto de Umami"                        //Harige
lang_npc[lang_num,104] = "Esse shopping parece que tem de tudo, menos computadores..." //Kubo
lang_npc[lang_num,105] = "De volta para os catálogo de livros eu acho."             //Kubo
lang_npc[lang_num,106] = "Olá! Temos filmagem do tubarão voador."                   //Maria
lang_npc[lang_num,107] = "Tenho um sentimento de que vocês três saberiam mais!"     //Maria
lang_npc[lang_num,108] = "Dançar é muito divertido! Dance Dance! Yay!"              //Milla
lang_npc[lang_num,109] = "Bom dia, crianças!"                                       //Savvy
lang_npc[lang_num,110] = "Eu vi as notícias, isso foi incrível Lilac!"              //Savvy
lang_npc[lang_num,111] = "Mas por favor descance amanhã, certo?"                    //Savvy
lang_npc[lang_num,112] = "Carol, você foi uma *dinamite* nas notícias!"             //Savvy
lang_npc[lang_num,113] = "Mas por favor não esqueça do seu dever de casa!"          //Savvy
lang_npc[lang_num,114] = "Oh, Milla! Você tem tanto potêncial."                     //Savvy
lang_npc[lang_num,115] = "Fale comigo se você precisa de uma bolsa de estudos!"      //Savvy
