///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Plataformas"
o.display_page_description[1] = "Decoraciones"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Pieza de pared Delgada"
o.display_description_item[o.display_page_one,1] = "Piso de Alfombra Roja"
o.display_description_item[o.display_page_one,2] = "Pieza de Pared Grande"
o.display_description_item[o.display_page_one,3] = "Piso de Cesped 1"
o.display_description_item[o.display_page_one,4] = "Piso de Cesped 2"
o.display_description_item[o.display_page_one,5] = "Piso de Cesped 3"
o.display_description_item[o.display_page_one,6] = "Piso de Cesped 4"
o.display_description_item[o.display_page_one,7] = "Unknown Tile"
o.display_description_item[o.display_page_one,8] = "Unknown Tile"
o.display_description_item[o.display_page_one,9] = "Unknown Tile"
o.display_description_item[o.display_page_one,10] = "Unknown Tile"
o.display_description_item[o.display_page_one,11] = "Unknown Tile"
o.display_description_item[o.display_page_one,12] = "Unknown Tile"
o.display_description_item[o.display_page_one,13] = "Unknown Tile"
o.display_description_item[o.display_page_one,14] = "Unknown Tile"
o.display_description_item[o.display_page_one,15] = "Unknown Tile"
o.display_description_item[o.display_page_one,16] = "Unknown Tile"
o.display_description_item[o.display_page_one,17] = "Unknown Tile"
o.display_description_item[o.display_page_one,18] = "Unknown Tile"
o.display_description_item[o.display_page_one,19] = "Unknown Tile"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Estatua del Alcalde Zao"
o.display_description_item[o.display_page_two,1] = "Punta de Pilar"
o.display_description_item[o.display_page_two,2] = "Pared Grande"
o.display_description_item[o.display_page_two,3] = "Tienda Genérica"
o.display_description_item[o.display_page_two,4] = "Tienda de Ventas en Promoción"
o.display_description_item[o.display_page_two,5] = "Tienda Venta de Liquidación"
o.display_description_item[o.display_page_two,6] = "Tienda Mundo de Bicis"
o.display_description_item[o.display_page_two,7] = "Árbol"
o.display_description_item[o.display_page_two,8] = "Pilar"
o.display_description_item[o.display_page_two,9] = "Adorno de Pared"
o.display_description_item[o.display_page_two,10] = "Panel Decorativo 1"
o.display_description_item[o.display_page_two,11] = "Panel Decorativo 2"
o.display_description_item[o.display_page_two,12] = "Panel Decorativo 3"
o.display_description_item[o.display_page_two,13] = "Letrero Mundo de Bicis"
o.display_description_item[o.display_page_two,14] = "Letrero de Promoción"
o.display_description_item[o.display_page_two,15] = "Letrero Venta de Liquidación"
o.display_description_item[o.display_page_two,16] = "Unknown Tile"
o.display_description_item[o.display_page_two,17] = "Unknown Tile"
o.display_description_item[o.display_page_two,18] = "Unknown Tile"
o.display_description_item[o.display_page_two,19] = "Unknown Tile"
