///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Arena"
o.display_page_description[1] = "Plataformas"
o.display_page_description[2] = "Rampas"
o.display_page_description[3] = "Exterior"
o.display_page_description[4] = "Decoración 1"
o.display_page_description[5] = "Decoración 2"
o.display_page_description[6] = "Extra 1"
o.display_page_description[7] = "Pier"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Arena - Esquina Superficial Izquierda"
o.display_description_item[o.display_page_one,1] = "Arena - Capa Superficial"
o.display_description_item[o.display_page_one,2] = "Arena - Esquina Superficial Derecha"
o.display_description_item[o.display_page_one,3] = "Arena - Esquina Superficial Inferior Izquierda"
o.display_description_item[o.display_page_one,4] = "Arena - Capa Superficial Invertida"
o.display_description_item[o.display_page_one,5] = "Arena - Esquina Superficial Inferior Derecha"
o.display_description_item[o.display_page_one,6] = "Arena- Pared Izquierda"
o.display_description_item[o.display_page_one,7] = "Arena- Pared Derecha"
o.display_description_item[o.display_page_one,8] = "Arena - Pendiente 1"
o.display_description_item[o.display_page_one,9] = "Arena - Pendiente 2"
o.display_description_item[o.display_page_one,10] = "Arena - Pendiente 3"
o.display_description_item[o.display_page_one,11] = "Arena - Pendiente 4"
o.display_description_item[o.display_page_one,12] = "Capa de Arenisca"
o.display_description_item[o.display_page_one,13] = "Plataforma Rocosa - Esquina Izquieda"
o.display_description_item[o.display_page_one,14] = "Plataforma Rocosa  Superficie"
o.display_description_item[o.display_page_one,15] = "Plataforma Rocosa - Esquina Derecha"
o.display_description_item[o.display_page_one,16] = "Superficie de Mármol - Ancha"
o.display_description_item[o.display_page_one,17] = "Superficie de Mármol - Angosta"
o.display_description_item[o.display_page_one,18] = "Pared de Mármol - Izquierda "
o.display_description_item[o.display_page_one,19] = "Pared de Mármol - Derecha"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Riel de Madera - 1"
o.display_description_item[o.display_page_two,1] = "Riel de Madera - 2"
o.display_description_item[o.display_page_two,2] = "Riel de Madera - 3"
o.display_description_item[o.display_page_two,3] = "Riel de Madera - 4"
o.display_description_item[o.display_page_two,4] = "Vieja Viga de Soporte de Cobre 1"
o.display_description_item[o.display_page_two,5] = "Vieja Viga de Soporte de Cobre 2"
o.display_description_item[o.display_page_two,6] = "Riel de Madera - Simple 1"
o.display_description_item[o.display_page_two,7] = "Colina de Arena - Sencilla Izquierda "
o.display_description_item[o.display_page_two,8] = "Viga de Soporte de Madera 1"
o.display_description_item[o.display_page_two,9] = "Viga de Soporte de Madera 2"
o.display_description_item[o.display_page_two,10] = "Vieja Viga de Soporte de Cobre 3"
o.display_description_item[o.display_page_two,11] = "Vieja Viga de Soporte de Cobre 4"
o.display_description_item[o.display_page_two,12] = "Riel de Madera - Simple 2"
o.display_description_item[o.display_page_two,13] = "Colina de Arena - Sencilla Derecha"
o.display_description_item[o.display_page_two,14] = "Pinchos 1"
o.display_description_item[o.display_page_two,15] = "Pinchos 2"
o.display_description_item[o.display_page_two,16] = "Pinchos 3"
o.display_description_item[o.display_page_two,17] = "Pinchos 4"
o.display_description_item[o.display_page_two,18] = "Escalera"
o.display_description_item[o.display_page_two,19] = "Barra Suspendida"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Cuarto de Tubería Rocosa 1"
o.display_description_item[o.display_page_three,1] = "Cuarto de Tubería Rocosa 2"
o.display_description_item[o.display_page_three,2] = "Cuarto de Tubería Rocosa 3"
o.display_description_item[o.display_page_three,3] = "Cuarto de Tubería Rocosa 4"
o.display_description_item[o.display_page_three,4] = "Colina de Arena Izquierda"
o.display_description_item[o.display_page_three,5] = "Colina de Arena Derecha"
o.display_description_item[o.display_page_three,6] = "Caja de Madera"
o.display_description_item[o.display_page_three,7] = "Pieza de Bucle 1"
o.display_description_item[o.display_page_three,8] = "Pieza de Bucle 2"
o.display_description_item[o.display_page_three,9] = "Pieza de Bucle 3"
o.display_description_item[o.display_page_three,10] = "Pieza de Bucle 4"
o.display_description_item[o.display_page_three,11] = "Plataforma Flotante - 1"
o.display_description_item[o.display_page_three,12] = "Plataforma Flotante - 2"
o.display_description_item[o.display_page_three,13] = "Bucle de Madera 1"
o.display_description_item[o.display_page_three,14] = "Bucle de Madera 2"
o.display_description_item[o.display_page_three,15] = "Bucle de Madera 3"
o.display_description_item[o.display_page_three,16] = "Bucle de Madera 4"
o.display_description_item[o.display_page_three,17] = "Plataforma Flotante 3"
o.display_description_item[o.display_page_three,18] = "Plataforma Flotante 4"
o.display_description_item[o.display_page_three,19] = "Plataforma Piso-Sobre-Piso"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Viga de Madera - Izquierda"
o.display_description_item[o.display_page_four,1] = "Viga de Madera - Larga"
o.display_description_item[o.display_page_four,2] = "Viga de Madera - Derecha"
o.display_description_item[o.display_page_four,3] = "Viga de Madera - Pequeña"
o.display_description_item[o.display_page_four,4] = "Riel de Madera"
o.display_description_item[o.display_page_four,5] = "Soporte de Madera - Izquierda"
o.display_description_item[o.display_page_four,6] = "Soporte de Madera - Derecha"
o.display_description_item[o.display_page_four,7] = "Soporte de Madera - Viga"
o.display_description_item[o.display_page_four,8] = "Cerca de Madera - Pieza Inferior"
o.display_description_item[o.display_page_four,9] = "Cerca de Madera - Pieza Superior"
o.display_description_item[o.display_page_four,10] = "Ducha de Exteriores"
o.display_description_item[o.display_page_four,11] = "Grifo Exterior"
o.display_description_item[o.display_page_four,12] = "Poste de Luz"
o.display_description_item[o.display_page_four,13] = "Baño Portatil - Masculino"
o.display_description_item[o.display_page_four,14] = "Baño Portatil - Femenino"
o.display_description_item[o.display_page_four,15] = "Ventaña Angosta"
o.display_description_item[o.display_page_four,16] = "Sombrilla Grande"
o.display_description_item[o.display_page_four,17] = "Sombrilla Grande"
o.display_description_item[o.display_page_four,18] = "Castillo de Arena - Pequeño"
o.display_description_item[o.display_page_four,19] = "Castillo de Arena - Grande"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Palmera - Tronco"
o.display_description_item[o.display_page_five,1] = "Palmera - Hoja Superior-Izquierda"
o.display_description_item[o.display_page_five,2] = "Palmera - Hoja Izquierda"
o.display_description_item[o.display_page_five,3] = "Palmera - Hoja Inferior-Izquierda"
o.display_description_item[o.display_page_five,4] = "Palmera - Hoja Superior-Derecha"
o.display_description_item[o.display_page_five,5] = "Palmera - Hoja Derecha"
o.display_description_item[o.display_page_five,6] = "Palmera - Hoja Inferior-Derecha"
o.display_description_item[o.display_page_five,7] = "Concha de Caracol - Grande"
o.display_description_item[o.display_page_five,8] = "Concha Marina"
o.display_description_item[o.display_page_five,9] = "Concha de Caracol - Pequeña"
o.display_description_item[o.display_page_five,10] = "Nido de Pájaro"
o.display_description_item[o.display_page_five,11] = "Coco"
o.display_description_item[o.display_page_five,12] = "Racimo de Bananas"
o.display_description_item[o.display_page_five,13] = "Aviso: Boyas"
o.display_description_item[o.display_page_five,14] = "Aviso: Corrientes Poderosas"
o.display_description_item[o.display_page_five,15] = "Aviso: Rocas Resbaladizas"
o.display_description_item[o.display_page_five,16] = "Aviso: Quebrada Súbita"
o.display_description_item[o.display_page_five,17] = "Aviso: Nido de Tortugas Marinas"
o.display_description_item[o.display_page_five,18] = "Aviso: No Alimentar a las Gaviotas"
o.display_description_item[o.display_page_five,19] = "Aviso: Sin Socorrista en Turno"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Roca Pequeña"
o.display_description_item[o.display_page_six,1] = "Roca Grande - 1"
o.display_description_item[o.display_page_six,2] = "Roca Grande - 2"
o.display_description_item[o.display_page_six,3] = "Roca Grande - 3"
o.display_description_item[o.display_page_six,4] = "Roca Grande - 4"
o.display_description_item[o.display_page_six,5] = "Hierba Silvestre"
o.display_description_item[o.display_page_six,6] = "Pila de Arena"
o.display_description_item[o.display_page_six,7] = "Puesto de Frutas"
o.display_description_item[o.display_page_six,8] = "Puesto de Protector Solar"
o.display_description_item[o.display_page_six,9] = "Puesto Tienda de Regalos"
o.display_description_item[o.display_page_six,10] = "Cafeteria"
o.display_description_item[o.display_page_six,11] = "Heladeria"
o.display_description_item[o.display_page_six,12] = "Puesto de Perros Calientes"
o.display_description_item[o.display_page_six,13] = "Unknown Tile"
o.display_description_item[o.display_page_six,14] = "Unknown Tile"
o.display_description_item[o.display_page_six,15] = "Unknown Tile"
o.display_description_item[o.display_page_six,16] = "Unknown Tile"
o.display_description_item[o.display_page_six,17] = "Unknown Tile"
o.display_description_item[o.display_page_six,18] = "Unknown Tile"
o.display_description_item[o.display_page_six,19] = "Unknown Tile"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Roca de Arenisca"
o.display_description_item[o.display_page_seven,1] = "Arena Plana - Pequeña - 1"
o.display_description_item[o.display_page_seven,2] = "Arena Plana - Pequeña - 2"
o.display_description_item[o.display_page_seven,3] = "Arena Plana - Pequeña - 3"
o.display_description_item[o.display_page_seven,4] = "Arena Plana - Pequeña - 4"
o.display_description_item[o.display_page_seven,5] = "Pieza de Esquina de Arena - 1"
o.display_description_item[o.display_page_seven,6] = "Pieza de Esquina de Arena - 2"
o.display_description_item[o.display_page_seven,7] = "Pieza de Esquina de Arena - 3"
o.display_description_item[o.display_page_seven,8] = "Pieza de Esquina de Arena - 4"
o.display_description_item[o.display_page_seven,9] = "Roca de Arenisca - Pequeña"
o.display_description_item[o.display_page_seven,10] = "Riel de Madera - Vertical - Grande"
o.display_description_item[o.display_page_seven,11] = "Riel de Madera - Vertical - Pequeño"
o.display_description_item[o.display_page_seven,12] = "Casilla Vacia de Arena"
o.display_description_item[o.display_page_seven,13] = "Viga de Soporte de Madera - Pequeña"
o.display_description_item[o.display_page_seven,14] = "Viga de Soporte de Madera - Grande"
o.display_description_item[o.display_page_seven,15] = "Viga de Construcción - Oxidada"
o.display_description_item[o.display_page_seven,16] = "Campanilla"
o.display_description_item[o.display_page_seven,17] = "Camellia Japonica Roja"
o.display_description_item[o.display_page_seven,18] = "Unknown Tile"
o.display_description_item[o.display_page_seven,19] = "Unknown Tile"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Viejo Muelle de Madera 1"
o.display_description_item[o.display_page_eight,1] = "Viejo Muelle de Madera 2"
o.display_description_item[o.display_page_eight,2] = "Viejo Muelle de Madera 3"
o.display_description_item[o.display_page_eight,3] = "Viejo Muelle de Madera 4"
o.display_description_item[o.display_page_eight,4] = "Viejo Muelle de Madera 5"
o.display_description_item[o.display_page_eight,5] = "Viejo Muelle de Madera 6"
o.display_description_item[o.display_page_eight,6] = "Letrero de No Pescar"
o.display_description_item[o.display_page_eight,7] = "Viga de Soporte de Madera 1"
o.display_description_item[o.display_page_eight,8] = "Viga de Soporte de Madera 2"
o.display_description_item[o.display_page_eight,9] = "Viga de Soporte de Madera 3"
o.display_description_item[o.display_page_eight,10] = "Viga de Soporte de Madera 4"
o.display_description_item[o.display_page_eight,11] = "Viga de Soporte de Madera 5"
o.display_description_item[o.display_page_eight,12] = "Pasamanos de Muelle"
o.display_description_item[o.display_page_eight,13] = "Bucle de Madera 1"
o.display_description_item[o.display_page_eight,14] = "Bucle de Madera 2"
o.display_description_item[o.display_page_eight,15] = "Bucle de Madera 3"
o.display_description_item[o.display_page_eight,16] = "Bucle de Madera 4"
o.display_description_item[o.display_page_eight,17] = "Rampa de Madera 1"
o.display_description_item[o.display_page_eight,18] = "Rampa de Madera 2"
o.display_description_item[o.display_page_eight,19] = "Poste Salvavidas"

//Tile Descriptions (Page 9)
o.display_description_item[o.display_page_nine,0] = "Muelle de Madera 1"
o.display_description_item[o.display_page_nine,1] = "Muelle de Madera 2"
o.display_description_item[o.display_page_nine,2] = "Muelle de Madera 3"
o.display_description_item[o.display_page_nine,3] = "Muelle de Madera 4"
o.display_description_item[o.display_page_nine,4] = "Muelle de Madera 5"
o.display_description_item[o.display_page_nine,5] = "Pequeña Pendiente de Arena 1"
o.display_description_item[o.display_page_nine,6] = "Pequeña Pendiente de Arena 2"
o.display_description_item[o.display_page_nine,7] = "Bucle de Madera 5"
o.display_description_item[o.display_page_nine,8] = "Bucle de Madera 6"
o.display_description_item[o.display_page_nine,9] = "Viga de Construcción Pequeña 1"
o.display_description_item[o.display_page_nine,10] = "Viga de Construcción Pequeña 2"
o.display_description_item[o.display_page_nine,11] = "Viga de Construcción Pequeña 3"
o.display_description_item[o.display_page_nine,12] = "Viga de Construcción Pequeña 4"
o.display_description_item[o.display_page_nine,13] = "Bucle de Madera 7"
o.display_description_item[o.display_page_nine,14] = "Bucle de Madera 8"
o.display_description_item[o.display_page_nine,15] = "Unknown Tile"
o.display_description_item[o.display_page_nine,16] = "Unknown Tile"
o.display_description_item[o.display_page_nine,17] = "Unknown Tile"
o.display_description_item[o.display_page_nine,18] = "Unknown Tile"
o.display_description_item[o.display_page_nine,19] = "Unknown Tile"
