///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Interior 1"
o.display_page_description[1] = "Interior 2"
o.display_page_description[2] = "Scenery"
o.display_page_description[3] = "???"
o.display_page_description[4] = "???"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Floor Panel 1"
o.display_description_item[o.display_page_one,1] = "Floor Panel 2"
o.display_description_item[o.display_page_one,2] = "Floor Panel 3"
o.display_description_item[o.display_page_one,3] = "Wall Panel 1"
o.display_description_item[o.display_page_one,4] = "Wall Panel 2"
o.display_description_item[o.display_page_one,5] = "Ceiling Panel 1"
o.display_description_item[o.display_page_one,6] = "Ceiling Panel 2"
o.display_description_item[o.display_page_one,7] = "Ceiling Panel 3"
o.display_description_item[o.display_page_one,8] = "Corner Panel 1"
o.display_description_item[o.display_page_one,9] = "Corner Panel 2"
o.display_description_item[o.display_page_one,10] = "Corner Panel 3"
o.display_description_item[o.display_page_one,11] = "Corner Panel 4"
o.display_description_item[o.display_page_one,12] = "Corner Panel 5"
o.display_description_item[o.display_page_one,13] = "Floor Panel 4"
o.display_description_item[o.display_page_one,14] = "Floor Panel 5"
o.display_description_item[o.display_page_one,15] = "Wall Panel 3"
o.display_description_item[o.display_page_one,16] = "Wall Panel 4"
o.display_description_item[o.display_page_one,17] = "Wall Panel 5"
o.display_description_item[o.display_page_one,18] = "Wall Panel 6"
o.display_description_item[o.display_page_one,19] = "Wall Panel 7"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Floor Panel Alternate 1"
o.display_description_item[o.display_page_two,1] = "Floor Panel Alternate 2"
o.display_description_item[o.display_page_two,2] = "Floor Panel Alternate 3"
o.display_description_item[o.display_page_two,3] = "Metal Bridge"
o.display_description_item[o.display_page_two,4] = "Metal Pipe"
o.display_description_item[o.display_page_two,5] = ""
o.display_description_item[o.display_page_two,6] = ""
o.display_description_item[o.display_page_two,7] = "Wall Panel Alternate 1"
o.display_description_item[o.display_page_two,8] = "Wall Panel Alternate 2"
o.display_description_item[o.display_page_two,9] = "Wall Panel Alternate 3"
o.display_description_item[o.display_page_two,10] = ""
o.display_description_item[o.display_page_two,11] = "Rusted Loop 1"
o.display_description_item[o.display_page_two,12] = "Rusted Loop 2"
o.display_description_item[o.display_page_two,13] = "Ceiling Panel Alternate 1"
o.display_description_item[o.display_page_two,14] = "Ceiling Panel Alternate 2"
o.display_description_item[o.display_page_two,15] = "Ceiling Panel Alternate 3"
o.display_description_item[o.display_page_two,16] = ""
o.display_description_item[o.display_page_two,17] = ""
o.display_description_item[o.display_page_two,18] = "Rusted Loop 3"
o.display_description_item[o.display_page_two,19] = "Rusted Loop 4"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Pillar"
o.display_description_item[o.display_page_three,1] = "Hallway"
o.display_description_item[o.display_page_three,2] = "Door Panel 1"
o.display_description_item[o.display_page_three,3] = "Door Panel 2"
o.display_description_item[o.display_page_three,4] = "Decayed Plant"
o.display_description_item[o.display_page_three,5] = "Green Pillar"
o.display_description_item[o.display_page_three,6] = "Bronze Pillar"
o.display_description_item[o.display_page_three,7] = "Broken Transport Panel"
o.display_description_item[o.display_page_three,8] = "Rusted Vent"
o.display_description_item[o.display_page_three,9] = "Broken Monitor"
o.display_description_item[o.display_page_three,10] = "Shade Trooper Shell 1"
o.display_description_item[o.display_page_three,11] = "Shade Trooper Shell 2"
o.display_description_item[o.display_page_three,12] = "Shade Trooper Shell 3"
o.display_description_item[o.display_page_three,13] = "Status Monitor"
o.display_description_item[o.display_page_three,14] = ""
o.display_description_item[o.display_page_three,15] = ""
o.display_description_item[o.display_page_three,16] = ""
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""
