///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Suportes"
o.display_page_description[1] = "Paredes"
o.display_page_description[2] = "Rampas"
o.display_page_description[3] = "Plataformas"
o.display_page_description[4] = "Decoração 1"
o.display_page_description[5] = "Decoração 2"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Bloco de Madeira 1"
o.display_description_item[o.display_page_one,1] = "Piso"
o.display_description_item[o.display_page_one,2] = "Viga de Apoio 1"
o.display_description_item[o.display_page_one,3] = "Bloco de Madeira 2"
o.display_description_item[o.display_page_one,4] = "Bloco de Madeira 3"
o.display_description_item[o.display_page_one,5] = "Bloco de Madeira 4"
o.display_description_item[o.display_page_one,6] = "Bloco de Madeira 5"
o.display_description_item[o.display_page_one,7] = "Bloco de Madeira 6"
o.display_description_item[o.display_page_one,8] = "Viga de Apoio 2"
o.display_description_item[o.display_page_one,9] = "Bloco de Madeira 7"
o.display_description_item[o.display_page_one,10] = "Bloco de Madeira 8"
o.display_description_item[o.display_page_one,11] = "Bloco de Madeira 9"
o.display_description_item[o.display_page_one,12] = "Bloco de Madeira 10"
o.display_description_item[o.display_page_one,13] = "Viga de Apoio 3"
o.display_description_item[o.display_page_one,14] = "Peça de Canto - Esquerda"
o.display_description_item[o.display_page_one,15] = "Viga de Madeira"
o.display_description_item[o.display_page_one,16] = "Peça de Canto - Direita"
o.display_description_item[o.display_page_one,17] = "Bloco de Madeira 11"
o.display_description_item[o.display_page_one,18] = "Peça de Canto - Cima"
o.display_description_item[o.display_page_one,19] = "Peça de Canto - Baixo"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Parede - Direita"
o.display_description_item[o.display_page_two,1] = "Parede - Esquerda"
o.display_description_item[o.display_page_two,2] = "Chão"
o.display_description_item[o.display_page_two,3] = "Teto"
o.display_description_item[o.display_page_two,4] = "Canto Externo 1"
o.display_description_item[o.display_page_two,5] = "Canto Externo 2"
o.display_description_item[o.display_page_two,6] = "Canto Externo 3"
o.display_description_item[o.display_page_two,7] = "Canto Externo 4"
o.display_description_item[o.display_page_two,8] = "Canto Interno 1"
o.display_description_item[o.display_page_two,9] = "Canto Interno 2"
o.display_description_item[o.display_page_two,10] = "Canto Interno 3"
o.display_description_item[o.display_page_two,11] = "Canto Interno 4"
o.display_description_item[o.display_page_two,12] = "Sombra 1"
o.display_description_item[o.display_page_two,13] = "Espinhos 1"
o.display_description_item[o.display_page_two,14] = "Espinhos 2"
o.display_description_item[o.display_page_two,15] = "Espinhos 3"
o.display_description_item[o.display_page_two,16] = "Espinhos 4"
o.display_description_item[o.display_page_two,17] = "Escada"
o.display_description_item[o.display_page_two,18] = "Barra Suspensa 1"
o.display_description_item[o.display_page_two,19] = "Barra Suspensa 2"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Rampa Pequena - 1"
o.display_description_item[o.display_page_three,1] = "Rampa Pequena - 2"
o.display_description_item[o.display_page_three,2] = "Rampa Pequena - 3"
o.display_description_item[o.display_page_three,3] = "Rampa Pequena - 4"
o.display_description_item[o.display_page_three,4] = "Peça do Loop de Grama 1"
o.display_description_item[o.display_page_three,5] = "Peça do Loop de Grama 2"
o.display_description_item[o.display_page_three,6] = "Piso"
o.display_description_item[o.display_page_three,7] = "Peça do Loop-De-Loop 1"
o.display_description_item[o.display_page_three,8] = "Peça do Loop-De-Loop 2"
o.display_description_item[o.display_page_three,9] = "Peça do Loop-De-Loop 3"
o.display_description_item[o.display_page_three,10] = "Peça do Loop-De-Loop 4"
o.display_description_item[o.display_page_three,11] = "Peça do Loop de Grama 3"
o.display_description_item[o.display_page_three,12] = "Peça do Loop de Grama 4"
o.display_description_item[o.display_page_three,13] = "Peça de Loop Dupla Face 1"
o.display_description_item[o.display_page_three,14] = "Peça de Loop Dupla Face 2"
o.display_description_item[o.display_page_three,15] = "Peça de Loop Dupla Face 3"
o.display_description_item[o.display_page_three,16] = "Peça de Loop Dupla Face 4"
o.display_description_item[o.display_page_three,17] = "Peça Longa Inclinada 1"
o.display_description_item[o.display_page_three,18] = "Peça Longa Inclinada 2"
o.display_description_item[o.display_page_three,19] = "Plataforma Piso-sobre-Piso"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Declive - Raso 1"
o.display_description_item[o.display_page_four,1] = "Declive - Raso 2"
o.display_description_item[o.display_page_four,2] = "Declive - Íngreme 1"
o.display_description_item[o.display_page_four,3] = "Declive - Íngreme 2"
o.display_description_item[o.display_page_four,4] = "Declive - Raso 3"
o.display_description_item[o.display_page_four,5] = "Superfície Plana 1"
o.display_description_item[o.display_page_four,6] = "Declive - Raso 4"
o.display_description_item[o.display_page_four,7] = "Plataforma Flutuante 1"
o.display_description_item[o.display_page_four,8] = "Plataforma Flutuante 2"
o.display_description_item[o.display_page_four,9] = "Plataforma Flutuante 3"
o.display_description_item[o.display_page_four,10] = "Plataforma Flutuante 4"
o.display_description_item[o.display_page_four,11] = "Plataforma Flutuante 5"
o.display_description_item[o.display_page_four,12] = "Reversão do Curso da Plataforma"
o.display_description_item[o.display_page_four,13] = "Bloco de Grama"
o.display_description_item[o.display_page_four,14] = "Bloco de Terra"
o.display_description_item[o.display_page_four,15] = "Unknown Tile 3"
o.display_description_item[o.display_page_four,16] = "Unknown Tile 4"
o.display_description_item[o.display_page_four,17] = "Unknown Tile 5"
o.display_description_item[o.display_page_four,18] = "Unknown Tile 6"
o.display_description_item[o.display_page_four,19] = "Unknown Tile 7"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Decoração - Ponte 1"
o.display_description_item[o.display_page_five,1] = "Decoração - Coluna"
o.display_description_item[o.display_page_five,2] = "Decoração - Árvore 1"
o.display_description_item[o.display_page_five,3] = "Decoração - Grade"
o.display_description_item[o.display_page_five,4] = "Decoração - Plano de Fundo"
o.display_description_item[o.display_page_five,5] = "Decoração - Plataforma"
o.display_description_item[o.display_page_five,6] = "Decoração - Fusuma 1"
o.display_description_item[o.display_page_five,7] = "Decoração - Mural"
o.display_description_item[o.display_page_five,8] = "Decoração - Curtinas"
o.display_description_item[o.display_page_five,9] = "Decoração - Peça Final da Curtina"
o.display_description_item[o.display_page_five,10] = "Decoração - Corrimão 1"
o.display_description_item[o.display_page_five,11] = "Decoração - Suporte"
o.display_description_item[o.display_page_five,12] = "Decoração - Lanterna 1"
o.display_description_item[o.display_page_five,13] = "Decoração - Fusuma 2"
o.display_description_item[o.display_page_five,14] = "Decoração - Árvore 2"
o.display_description_item[o.display_page_five,15] = "Decoração - Árvore 3"
o.display_description_item[o.display_page_five,16] = "Decoração - Árvore 3 - Extra"
o.display_description_item[o.display_page_five,17] = "Decoração - Árvore 4"
o.display_description_item[o.display_page_five,18] = "Decoração - Bandeira"
o.display_description_item[o.display_page_five,19] = "Decoração - Lanterna 2"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Sombra 16x16"
o.display_description_item[o.display_page_six,1] = "Sombra 32x32"
o.display_description_item[o.display_page_six,2] = "Sombra 64x64"
o.display_description_item[o.display_page_six,3] = "Sombra 96x96"
o.display_description_item[o.display_page_six,4] = "Sombra 16x96"
o.display_description_item[o.display_page_six,5] = "Sombra 96x16"
o.display_description_item[o.display_page_six,6] = "Sombra 128x128"
o.display_description_item[o.display_page_six,7] = "Escuridão 128x128"
o.display_description_item[o.display_page_six,8] = "Decoração - Mesa Larga"
o.display_description_item[o.display_page_six,9] = "Decoração - Mesa Pequena"
o.display_description_item[o.display_page_six,10] = "Unknown Tile"
o.display_description_item[o.display_page_six,11] = "Unknown Tile"
o.display_description_item[o.display_page_six,12] = "Unknown Tile"
o.display_description_item[o.display_page_six,13] = "Unknown Tile"
o.display_description_item[o.display_page_six,14] = "Unknown Tile"
o.display_description_item[o.display_page_six,15] = "Unknown Tile"
o.display_description_item[o.display_page_six,16] = "Unknown Tile"
o.display_description_item[o.display_page_six,17] = "Unknown Tile"
o.display_description_item[o.display_page_six,18] = "Unknown Tile"
o.display_description_item[o.display_page_six,19] = "Unknown Tile"
