///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Ziemia"
o.display_page_description[1] = "Stoki 1"
o.display_page_description[2] = "Stoki 2"
o.display_page_description[3] = "Sceneria"
o.display_page_description[4] = "???"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Ziemia 1"
o.display_description_item[o.display_page_one,1] = "Ziemia 2"
o.display_description_item[o.display_page_one,2] = "Ziemia 3"
o.display_description_item[o.display_page_one,3] = "Ziemia 4"
o.display_description_item[o.display_page_one,4] = "Ziemia 5"
o.display_description_item[o.display_page_one,5] = "Ziemia 6"
o.display_description_item[o.display_page_one,6] = "Ziemia 7"
o.display_description_item[o.display_page_one,7] = "Ziemia 8"
o.display_description_item[o.display_page_one,8] = "Ziemia 9"
o.display_description_item[o.display_page_one,9] = "Długi Most"
o.display_description_item[o.display_page_one,10] = "Krótki Most"
o.display_description_item[o.display_page_one,11] = ""
o.display_description_item[o.display_page_one,12] = ""
o.display_description_item[o.display_page_one,13] = ""
o.display_description_item[o.display_page_one,14] = ""
o.display_description_item[o.display_page_one,15] = ""
o.display_description_item[o.display_page_one,16] = ""
o.display_description_item[o.display_page_one,17] = ""
o.display_description_item[o.display_page_one,18] = ""
o.display_description_item[o.display_page_one,19] = ""

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Błotna Rampa - Lewa"
o.display_description_item[o.display_page_two,1] = "Błotna Rampa - Prawa"
o.display_description_item[o.display_page_two,2] = "Kamienna Rampa - Lewa"
o.display_description_item[o.display_page_two,3] = "Kamienna Rampa - Prawa"
o.display_description_item[o.display_page_two,4] = "Kamienny Stok 1"
o.display_description_item[o.display_page_two,5] = "Kamienny Stok 2"
o.display_description_item[o.display_page_two,6] = ""
o.display_description_item[o.display_page_two,7] = "Cieńka Pętla 1"
o.display_description_item[o.display_page_two,8] = "Cieńka Pętla 2"
o.display_description_item[o.display_page_two,9] = "Kamienna Pętla 1"
o.display_description_item[o.display_page_two,10] = "Kamienna Pętla 2"
o.display_description_item[o.display_page_two,11] = "Okrągła Kamienna Pętla 1"
o.display_description_item[o.display_page_two,12] = "Okrągła Kamienna Pętla 2"
o.display_description_item[o.display_page_two,13] = "Cieńka Pętla 3"
o.display_description_item[o.display_page_two,14] = "Cieńka Pętla 4"
o.display_description_item[o.display_page_two,15] = "Kamienna Pętla 3"
o.display_description_item[o.display_page_two,16] = "Kamienna Pętla 4"
o.display_description_item[o.display_page_two,17] = "Okrągła Kamienna Pętla 3"
o.display_description_item[o.display_page_two,18] = "Okrągła Kamienna Pętla 4"
o.display_description_item[o.display_page_two,19] = ""

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Górka Gliny 1"
o.display_description_item[o.display_page_three,1] = "Trawa 1"
o.display_description_item[o.display_page_three,2] = "Górka Gliny 2"
o.display_description_item[o.display_page_three,3] = "Górka Gliny 3"
o.display_description_item[o.display_page_three,4] = "Górka Gliny 4"
o.display_description_item[o.display_page_three,5] = "Górka Gliny 5"
o.display_description_item[o.display_page_three,6] = "Kamienny Łuk 1"
o.display_description_item[o.display_page_three,7] = "Kamienny Łuk 2"
o.display_description_item[o.display_page_three,8] = "Kamienny Łuk 3"
o.display_description_item[o.display_page_three,9] = ""
o.display_description_item[o.display_page_three,10] = ""
o.display_description_item[o.display_page_three,11] = ""
o.display_description_item[o.display_page_three,12] = ""
o.display_description_item[o.display_page_three,13] = ""
o.display_description_item[o.display_page_three,14] = ""
o.display_description_item[o.display_page_three,15] = ""
o.display_description_item[o.display_page_three,16] = ""
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""
