//For calling in Story Mode object only, call BEFORE NPC spawn scripts
//Language Array; 0 = English; 1 = Portuguese; 2 = Polish; 3 = Spanish; 4 = German; 5 = Russian
var lang_num = 2;
//West District NPCs 1
lang_npc[lang_num,0]  = "Ta! Zaciągnięcie tych stworów gdziekolwiek jest ciężkim wyzwaniem!"     //Clyde
lang_npc[lang_num,1]  = "Stąd brakuje mi paru zębów!"   //Clyde
lang_npc[lang_num,2]  = "Ze wszystkich cudów miasta, najbardziej tęskniłem za pociągami!"   //Bucky
lang_npc[lang_num,3]  = "Przypominają mi stare czasy w wrestlingu!"           //Bucky
lang_npc[lang_num,4]  = "Przepraszam, Chiasa! Byłem głodnyy!"                  //Marshmallow
lang_npc[lang_num,5]  = "Podzielę się z tobą!"                              //Marshmallow
lang_npc[lang_num,6]  = "Nie rozumiem... gdzie się wszyscy podziali?"       //Candy
lang_npc[lang_num,7]  = "Na wypadek jakbyś to przegapiła!"                 //Allister
lang_npc[lang_num,8]  = "Przez miasto przetoczył się *czołg*!"        //Allister
lang_npc[lang_num,9]  = "Na co czekasz?! Dzieje się AKCJA!"        //Jett
lang_npc[lang_num,10] = "Czy na prawdę musieli postawić tu ścianę?"     //Trip
lang_npc[lang_num,11] = "Grr..."                                             //Axl
lang_npc[lang_num,12] = "Ten czołg zniszczył już wschodni most!"       //Lilac
lang_npc[lang_num,13] = "Nie możemy tak stać i nic nie robić..."                          //Lilac
lang_npc[lang_num,14] = "Chciałam coś zjeść zanim ruszymy, ale..."   //Carol
lang_npc[lang_num,15] = "Odechciało mi się przez te dźwięki obok!"            //Carol
lang_npc[lang_num,16] = "*dźwięki zdegustowanego szopa*"                        //Trash Can
lang_npc[lang_num,17] = "Hej dzieciaku! Daj mi jeść ten wykwintny obiad w spokoju!"       //Trash Can
lang_npc[lang_num,18] = "Przekąski tej pani są dziwne! Wgryzłam się w jedną..."    //Libbie Dark
lang_npc[lang_num,19] = "I nagle pojawiła się nad mną chmura deszczowa!"       //Libbie Dark
lang_npc[lang_num,20] = "Kto mi zabroni kupić drugi lunch?!"             //Tiwi
lang_npc[lang_num,21] = "Kto ma ochotę na świeże placki z bananów?"     //Harige
lang_npc[lang_num,22] = "Jest to jedno z popularnych dań w Parusie!"                   //Harige
lang_npc[lang_num,23] = "Mam *sporo* pytań o jedzeniu tego gościa!"     //Astum
lang_npc[lang_num,24] = "Paluszki rybne? Sałatka z hot dogów? Burito z zakwasu?!"   //Astum
lang_npc[lang_num,25] = "Czuje się tak zgubiona! Powinnam zapytać kogoś o drogę."       //Leela
lang_npc[lang_num,26] = "Ale to wymaga rozmowy z LUDŹMI! Ech!"           //Leela

//West District NPCs 2
lang_npc[lang_num,27] = "To był długi dzień, ale jestem już prawie gotów się zebrać."    //Harige
lang_npc[lang_num,28] = "Jacyś ostatni goście?"                        //Harige
lang_npc[lang_num,29] = "Taak... Przegięłam z lodami..."        //Shy
lang_npc[lang_num,30] = "Może jakieś prawdziwe jedzenie sprawi że poczuję się lepiej?"   //Shy
lang_npc[lang_num,31] = "Nie wiem co myśleć o tych nowych miksturach Mili!"               //Carol
lang_npc[lang_num,32] = "Dotknęłam jedną, i wybiło to wszystkie okna!"     //Carol
lang_npc[lang_num,33] = "Fju! To powinno być bezpieczne miejsce na drzemkę..."      //
lang_npc[lang_num,34] = "Zwiedzanie tego miasta jest męczące!"              //
lang_npc[lang_num,35] = "Zwiedzanie miasta było super! Cieszę się że zdecydowałam sie iść."   //Iris
lang_npc[lang_num,36] = "Miałam nawet szansę zobaczyć dziewczyny walczące z czołgiem!"          //Iris
lang_npc[lang_num,37] = "To miejsce niedługo się zamyka, ale nie jest mi żal." //Azuli
lang_npc[lang_num,38] = "Ostatnie spojrzenie na ten widok to wszystko czego mi potrzeba!"        //Azuli
lang_npc[lang_num,39] = "To ostatni raz kiedy zostawiam swoją bazukę w domu" //Rhyme
lang_npc[lang_num,40] = "Ale dobrze że nie ma już tutaj tego czołgu!"                //Rhyme
lang_npc[lang_num,41] = "Zastanawiasz się pewnie, jak ja tu się trzymam!"      //Bucky
lang_npc[lang_num,42] = "Proste, nie oddycham! Powietrze jest dla słabych! Chyp!"   //Bucky
lang_npc[lang_num,43] = "*Ech* Szkoda że nie znam innej drogi do domu..."         //Trip
lang_npc[lang_num,44] = "To miasto nigdy nie będzie takie same po ostatniej inwazji."      //Trip
lang_npc[lang_num,45] = "Na pewno chcesz tam iść dzieciaku?"            //Clyde
lang_npc[lang_num,46] = "Wszystko jest tam zaorane przez gąsienice tego czołgu."          //Clyde
lang_npc[lang_num,47] = "Co my tu robimy!? Bouncer jest po wschodniej stronie!"     //Lilac
lang_npc[lang_num,48] = "Ta strona miasta jest na razie bezpieczna!"                    //Lilac
lang_npc[lang_num,49] = "Ten kosz jest straszny!"                            //Chiasa
lang_npc[lang_num,50] = "Próbował zjeść światła z mojego skutera!"             //Chiasa
lang_npc[lang_num,51] = "Blech! Światła nie smakują tak jak kiedyś!!" //Trash Can
lang_npc[lang_num,52] = "Coś czuje że pojawi się niedługo nowa posada..."             //
lang_npc[lang_num,53] = "Słysze dużo raportów o incydentach w kanałach."   //
lang_npc[lang_num,54] = "Chcę dołączyć do cokolwiek dzieje się na wschodzie miasta!"   //Jett
lang_npc[lang_num,55] = "Cóż, zatem *sam* nakarmię mewy!"     //Astum
lang_npc[lang_num,56] = "Co złego może się stać?!"                 //Astum
lang_npc[lang_num,57] = "OCH ŁAŁ, nawet śmieci pachną tu dobrze!"  //Marshmallow

//West District NPCs 3
lang_npc[lang_num,58] = "Coś w tym koszu chciało zjeść moje włosy!" //Lilac
lang_npc[lang_num,59] = "Mmm! Smakowało jak drut kolczasty pokryty olejem silnikowym!"      //Trash can
lang_npc[lang_num,60] = "Próbuję zmyć graffiti które narysowała Jett!"    //Marshmallow
lang_npc[lang_num,61] = "Pokazywało naszego burmistrza jako pionek do kręgli!"             //Marshmallow
lang_npc[lang_num,62] = "Cóż, czas się zbierać!"                     //Garrett
lang_npc[lang_num,63] = "Bus coś długo nie przyjeżdża!"           //Abby
lang_npc[lang_num,64] = "Czy go też zjadł jakiś potwór?!"                //Abby
lang_npc[lang_num,65] = "Nie bądź zabawna, Abby!"                             //Alexis
lang_npc[lang_num,66] = "Chwila..."                                            //Alexis
lang_npc[lang_num,67] = "Właśnie powiedziałam mojej córce że jest adoptowana!" //Vela
lang_npc[lang_num,68] = "Była zbyt ciekawska dla własnego dobra..."           //Vela
lang_npc[lang_num,69] = "*Kot.exe przestał działać*"                //Chiasa
lang_npc[lang_num,70] = "Karmienie mew jest bardzo fajne!"             //Astum
lang_npc[lang_num,71] = "Mam tonę ptasich przyjaciół!"                    //Astum
lang_npc[lang_num,72] = "Przepraszam że nie ma mnie przy moim stoisku!"      //Milla
lang_npc[lang_num,73] = "Byłam głodna!"                                       //Milla
lang_npc[lang_num,74] = "Zbudowano mnie aby plotować trasy nisko orbitalne"          //Leo
lang_npc[lang_num,75] = "Ale aktualnie wyświetlam menu dla burgerowni!"   //Leo
lang_npc[lang_num,76] = "Tylko włóż mi tu kolejne opakowanie po gumie!"          //Cook
lang_npc[lang_num,77] = "Pokaże ci kto jest prawdziwym śmieciem!"                        //Cook
lang_npc[lang_num,78] = "Dalej, wrzuć tu kolejny kubek!"                 //Cook
lang_npc[lang_num,79] = "Nadal zamknięte?"                                //Azuli
lang_npc[lang_num,80] = "Wczorajsza droga do pracy była niezbyt zabawna!"       //Cassandre
lang_npc[lang_num,81] = "'Sorki szefie, żaba zjadła mój samochód' nie spotkało się ze śmiechem."   //Cassandre
lang_npc[lang_num,82] = "Świeże banany, i zupa ze skorupiaków!"           //Harige
lang_npc[lang_num,83] = "Specjalizuje się w przystawkach z Parusy!"         //Harige
lang_npc[lang_num,84] = "Wiesz co, chyba nigdy nie byłam w Parusie."   //Carol
lang_npc[lang_num,85] = "Ale ichnie jedzenie pachnie dobrze!"                  //Carol
lang_npc[lang_num,86] = "Chyba lubię bardziej ziemniaki Mili!"            //Carrie
lang_npc[lang_num,87] = "Mój ostatni eliksir podpalił pobliski kosz!"           //Carrie

//West District NPCs 4
lang_npc[lang_num,88]  = "Ta puszka ma szczęście, że jest poza moją jurysdykcją!"   //Bird Guard
lang_npc[lang_num,89]  = "Zjadł cały rower..."                         //Bird Guard
lang_npc[lang_num,90]  = "Hihihihihihihi..."                                   //Trash Can
lang_npc[lang_num,91]  = "Psst! Hej, ty! Chcesz trochę akcji rzepy?"          //Boss
lang_npc[lang_num,92]  = "Nie jesteś chyba tchórzem?"                              //Boss
lang_npc[lang_num,93]  = "Wczorajsze newsy w telewizji były niesamowite!"     //Axl
lang_npc[lang_num,94]  = "Dobra robota!"                          //Axl
lang_npc[lang_num,95]  = "Siopao są tak dobre..."                          //Carrie
lang_npc[lang_num,96]  = "Przegapiłem cały wczorajszy ubaw!"                  //Rhyme
lang_npc[lang_num,97]  = "Zazdroszczę ci..."                                  //Rhyme
lang_npc[lang_num,98]  = "Zamówisz mi cheeseburgera, #Milla?"          //Stumpy
lang_npc[lang_num,99]  = "To była dobra przerwa. Czas wracać do roboty!"   //Beibo
lang_npc[lang_num,100] = "Lody lody, lody dla ochłody!"     //Milla
lang_npc[lang_num,101] = "AAAAAAAAAAAAA#AAAAAAAAAAAAA#AAAAAAAAAAAAA"          //Milla
lang_npc[lang_num,102] = "Popatrz na nią! Chyba zjadła je razem z miską!"      //Carol
lang_npc[lang_num,103] = "Kocham i nienawidzę jak przewrotne jest to miasto."      //Kusei
lang_npc[lang_num,104] = "Trzy miesiące nudy, trzy minuty za dużej akcji..." //Kusei
lang_npc[lang_num,105] = "Odwiedź kiedyś Shuigang! Nie ma tam dnia bez jakichś wydarzeń"   //Millie
lang_npc[lang_num,106] = "Ahaha..."                                             //Millie
lang_npc[lang_num,107] = "Nie codziennie żaba zjada biura twojej firmy."    //Guage
lang_npc[lang_num,108] = "Witaj w lodziarni Zao!"                 //Leo
lang_npc[lang_num,109] = "I nie, nie mamy dzisiaj truskawek, skończyły się!"    //Leo
lang_npc[lang_num,110] = "Hej, chcesz zagrać 1 kontra 1 w salonie gier?"                  //Flavio
lang_npc[lang_num,111] = "Założę się że nie pokonasz mojego wyniku w Sumo F1!"       //Flavio

//West District NPCs 5
lang_npc[lang_num,112] = "Czemu nikt mi nie powiedział, że ten kosz żyje!"      //Flavio
lang_npc[lang_num,113] = "Zjadł mój GameBee..."                                //Flavio
lang_npc[lang_num,114] = "Spadaj dzieciaku! To MÓJ złom!"                        //Trash Can
lang_npc[lang_num,115] = "Mmm! Twoje włosy muszą smakować lepiej smażone!"    //Trash Can
lang_npc[lang_num,116] = "*dźwięki gryzienia przez szopa*"                        //Trash Can
lang_npc[lang_num,117] = "Ech... Czas przejechać się klaunowym rowerem."    //Mirdin
lang_npc[lang_num,118] = "*bip bip*"                                          //Mirdin
lang_npc[lang_num,119] = "Nadal nie zainteresowana akcjami rzepy?"         //Boss
lang_npc[lang_num,120] = "Ta górka jest tego warta! Darmowe pieniądze."     //Boss
lang_npc[lang_num,121] = "Hmm, ktoś cały czas rozwala mi auto..."          //Garrett
lang_npc[lang_num,122] = "Ej, Milla! Chcę bułeczkę z hot catem, proszę, hihi!"   //Pummpy
lang_npc[lang_num,123] = "Tato, możemy jeszcze raz?! To było WSPANIAŁE!!!"        //Zeia
lang_npc[lang_num,124] = "Heh, co ja z tobą zrobię, Zeia?"         //Guage
lang_npc[lang_num,125] = "Dzień dobry, dziewczyny! Jesteście już po lekcjach?"             //Millie
lang_npc[lang_num,126] = "Wciąż musimy sprawdzić świątynie w Wuzhen..."        //Lilac
lang_npc[lang_num,127] = "Milla, chcę zobaczyć góry!"                 //Stumpy
lang_npc[lang_num,128] = "Bardzo proszę o pięć bananów!"          //Tiwi
lang_npc[lang_num,129] = "Heh, dajesz stacji Tri Kingdom News sporo materiału!"          //Axl

//West District NPCs 6
lang_npc[lang_num,130] = "Ej Candy, byłoby zabawnie tak ukraść ten znak w środku dnia." //Umi
lang_npc[lang_num,131] = "Nie można mieć za wielu znaków stopu!"                //Umi
lang_npc[lang_num,132] = "Umi, nie starczy ci na razie przestępstw?!"                  //Candy
lang_npc[lang_num,133] = "Zabieram tego zwierza ze sobą!"                      //Neera
lang_npc[lang_num,134] = "Jest poszukiwany we wszystkich czterech królestwach!"                       //Neera
lang_npc[lang_num,135] = "*smutne dźwięki złego szopa*"                                  //Trash Can
lang_npc[lang_num,136] = "Chyba się znowu zgubiłem... #Hmm."                     //Tanner
lang_npc[lang_num,137] = lang_npc[lang_num,122]       //Pummpy
lang_npc[lang_num,138] = "Dzień dobry dziewczęta! Dobrze się bawicie w ten weekend?"                    //Millie
lang_npc[lang_num,139] = "Milla, chciałbym zobaczyć plażę!"                        //Milla (i assume it was meant to be Stumpy lol)

//West District NPCs 7
lang_npc[lang_num,140] = "Okej, dobrze, nie będę kraść znaków stopu!"               //Umi
lang_npc[lang_num,141] = "Nasza chatka zaczyna być już pełna..."          //Umi
lang_npc[lang_num,142] = "Tak lepiej! Chodźmy do domu, Umi."           //Candy
lang_npc[lang_num,143] = "oj, Milla! Chce burgerka, hihi!"             //Pumppy
lang_npc[lang_num,144] = "Mmm! To są najlepsze lody w mieście!"               //Marshmallow
lang_npc[lang_num,145] = "Chcę jeszcze jednego!"                                          //Marshmallow
lang_npc[lang_num,146] = "Och, mój drogi... Przynosisz mi spełnienie duszy."          //Bird Guard (Female)
lang_npc[lang_num,147] = "Łeh"                                                      //Bird Guard (Male)
lang_npc[lang_num,148] = "Ooch! Uwielbiam banany! Wezmę trzy."                //
lang_npc[lang_num,149] = "Och... Dlatego nie karmi się mew..."        //Astum
lang_npc[lang_num,150] = "Dziobały mi kostki GODZINAMI!!! AŁ!!!"             //Astum
lang_npc[lang_num,151] = "Nie wystarczająco!"                                      //Abby
lang_npc[lang_num,152] = "Czy wystarczająco wymęczyliśmy opiekunkę?!"                   //Alexis

