//Language Array (Pause Menu); 0 = English; 1 = Portuguese; 2 = Polish; 3 = Spanish; 4 = German

lang_gui[0,0] = "Play"
lang_gui[0,1] = "Editor"
lang_gui[0,2] = "Campaign"
lang_gui[0,3] = "Options"
lang_gui[0,4] = "Quit"
lang_gui[0,5] = "Story     Mode"
lang_gui[0,6] = "Classic     Mode"
lang_gui[0,7] = "Time     Attack"
lang_gui[0,8] = "Back"
//Options Menu
lang_gui[0,9] = "Screen       Size"
lang_gui[0,10] = "Palette     Shader"
lang_gui[0,11] = "Music       Volume"
lang_gui[0,12] = "Sound       Volume"
lang_gui[0,13] = "Controls.   .   ."
lang_gui[0,14] = "Language"
lang_gui[0,15] = "Gameplay       Settings.   .   ."
lang_gui[0,16] = "Okay"
//On/Off
lang_gui[0,17] = "Off"
lang_gui[0,18] = "On"
//Control Settings
lang_gui[0,19] = "(ESC - Reset defaults)"
lang_gui[0,20] = "Up"
lang_gui[0,21] = "Down"
lang_gui[0,22] = "Left"
lang_gui[0,23] = "Right"
lang_gui[0,24] = "UP"
lang_gui[0,25] = "DOWN"
lang_gui[0,26] = "LEFT"
lang_gui[0,27] = "RIGHT"
lang_gui[0,28] = "ACTION"
lang_gui[0,29] = "JUMP"
lang_gui[0,30] = "SPECIAL"
lang_gui[0,31] = "SWITCH"
lang_gui[0,32] = "START"
lang_gui[0,33] = "(ESC - Cancel changes)"
lang_gui[0,34] = "(Press/Scroll Up or Down)"
//Editor Control Settings
lang_gui[0,35] = "PLACE"
lang_gui[0,36] = "COPY"
lang_gui[0,37] = "DELETE"
lang_gui[0,38] = "NEW TILE"
lang_gui[0,39] = "UNDO"
lang_gui[0,40] = "REDO"
lang_gui[0,41] = "PLAY MODE"
lang_gui[0,42] = "EXIT"
lang_gui[0,43] = "LAYER"
lang_gui[0,44] = "SNAP"
lang_gui[0,45] = "ZOOM"
//Gameplay Settings
lang_gui[0,46] = "Gameplay"
lang_gui[0,47] = "Difficulty"
lang_gui[0,48] = "Camera     Shake"
lang_gui[0,49] = "Camera       Zoom"
lang_gui[0,50] = "Display       Moves"
lang_gui[0,51] = "Enemy      HP      Bars"
lang_gui[0,52] = "Sensitivity"
lang_gui[0,53] = "Easy"
lang_gui[0,54] = "Normal"
lang_gui[0,55] = "Hard"
lang_gui[0,56] = "Hardcore"
lang_gui[0,57] = "Insanity"
//Saving Prompts
lang_gui[0,58] = "Saving     .     .     ."
lang_gui[0,59] = "Saving     Defaults     .     .     ."
//Language
lang_gui[0,60] = "Language: English"
lang_gui[0,61] = "Type"
//Freeze Frames
lang_gui[0,62] = "Freeze     Frames"

//Brazilian Portuguese
lang_gui[1,0] = "Jogar"
lang_gui[1,1] = "Editor"
lang_gui[1,2] = "Campanha"
lang_gui[1,3] = "Opções"
lang_gui[1,4] = "Sair"
lang_gui[1,5] = "Modo     História"
lang_gui[1,6] = "Modo     Clássico"
lang_gui[1,7] = "Modo     Corrida"
lang_gui[1,8] = "Voltar"
//Options Menu
lang_gui[1,9] = "Tamanho     da     Tela"
lang_gui[1,10] = "Shaders       de       Paletas"
lang_gui[1,11] = "Volume       da       Música"
lang_gui[1,12] = "Volume       do       Som"
lang_gui[1,13] = "Controles.   .   ."
lang_gui[1,14] = "Idioma"
lang_gui[1,15] = "Configurações       da       Jogabilidade.   .   ."
lang_gui[1,16] = "CONFIRMAR"
//On/Off
lang_gui[1,17] = "Desligado"
lang_gui[1,18] = "Ligado"
//Control Settings
lang_gui[1,19] = "(ESC - Reiniciar para o Padrão)"
lang_gui[1,20] = "Cima"
lang_gui[1,21] = "Baixo"
lang_gui[1,22] = "Esquerda"
lang_gui[1,23] = "Direita"
lang_gui[1,24] = "CIMA"
lang_gui[1,25] = "BAIXO"
lang_gui[1,26] = "ESQUERDA"
lang_gui[1,27] = "DIREITA"
lang_gui[1,28] = "AÇÃO"
lang_gui[1,29] = "PULAR"
lang_gui[1,30] = "ESPECIAL"
lang_gui[1,31] = "TROCAR"
lang_gui[1,32] = "START"
lang_gui[1,33] = "(ESC - Cancelar Mudanças)"
lang_gui[1,34] = "(Pressione/Deslize para Cima/Baixo)"
//Editor Control Settings
lang_gui[1,35] = "COLOCAR"
lang_gui[1,36] = "COPIAR"
lang_gui[1,37] = "DELETAR"
lang_gui[1,38] = "NOVO OBJETO"
lang_gui[1,39] = "DESFAZER"
lang_gui[1,40] = "REFAZER"
lang_gui[1,41] = "MODO DE TESTE"
lang_gui[1,42] = "SAIR"
lang_gui[1,43] = "CAMADA"
lang_gui[1,44] = "FIXAR"
lang_gui[1,45] = "ZOOM"
//Gameplay Settings
lang_gui[1,46] = "Jogabilidade"
lang_gui[1,47] = "Dificuldade"
lang_gui[1,48] = "Tremor       na       Câmera"
lang_gui[1,49] = "Zoom       da       Câmera"
lang_gui[1,50] = "Mostrar      Movimentos"
lang_gui[1,51] = "Barras      PV      do      Inimigo"
lang_gui[1,52] = "Sensibilidade"
lang_gui[1,53] = "Fácil"
lang_gui[1,54] = "Normal"
lang_gui[1,55] = "Difícil"
lang_gui[1,56] = "Muito      Difícil"
lang_gui[1,57] = "Insano"
lang_gui[1,58] = "Salvando     .     .     ."
lang_gui[1,59] = "Salvando     Ausência     .     .     ."
//Language
lang_gui[1,60] = "Idioma: Português"
lang_gui[1,61] = "Tipo"
//Freeze Frames
lang_gui[1,62] = "Molduras     Congelar"

//Polish
lang_gui[2,0] = "Graj"
lang_gui[2,1] = "Edytor"
lang_gui[2,2] = "Kampania"
lang_gui[2,3] = "Opcje"
lang_gui[2,4] = "Wyjdź"
lang_gui[2,5] = "Tryb     Przygodowy"
lang_gui[2,6] = "Tryb     Klasyczny"
lang_gui[2,7] = "Tryb     na Czas"
lang_gui[2,8] = "Wstecz"
//Options Menu
lang_gui[2,9] = "Rozmiar     Ekranu"
lang_gui[2,10] = "Shadery     Palet"
lang_gui[2,11] = "Głośność     Muzyki"
lang_gui[2,12] = "Głośność     Dźwięków"
lang_gui[2,13] = "Sterowanie.   .   ."
lang_gui[2,14] = "Język"
lang_gui[2,15] = "Ustawienia     Gry.   .   ."
lang_gui[2,16] = "OK"
//On/Off
lang_gui[2,17] = "Wyłącz"
lang_gui[2,18] = "Włącz"
//Control Settings
lang_gui[2,19] = "(ESC - Przywróć domyślne)"
lang_gui[2,20] = "Góra"
lang_gui[2,21] = "Dół"
lang_gui[2,22] = "Lewy"
lang_gui[2,23] = "Prawy"
lang_gui[2,24] = "GÓRA"
lang_gui[2,25] = "DÓŁ"
lang_gui[2,26] = "LEWO"
lang_gui[2,27] = "PRAWO"
lang_gui[2,28] = "AKCJA"
lang_gui[2,29] = "SKOK"
lang_gui[2,30] = "SPECIAL"
lang_gui[2,31] = "SWITCH"
lang_gui[2,32] = "START"
lang_gui[2,33] = "(ESC - Anuluj zmiany)"
lang_gui[2,34] = "(Wciśnij/Przewiń w Górę lub Dół)"
//Editor Control Settings
lang_gui[2,35] = "POŁÓŹ"
lang_gui[2,36] = "KOPIUJ"
lang_gui[2,37] = "USUŃ"
lang_gui[2,38] = "NOWA PŁYTKA"
lang_gui[2,39] = "COFNIJ"
lang_gui[2,40] = "POWTÓRZ"
lang_gui[2,41] = "TRYB GRY"
lang_gui[2,42] = "WYJDŹ"
lang_gui[2,43] = "WARSTWA"
lang_gui[2,44] = "SNAP"
lang_gui[2,45] = "ZOOM"
//Gameplay Settings
lang_gui[2,46] = "Ustawienia Gry"
lang_gui[2,47] = "Poziom Trudności"
lang_gui[2,48] = "Wstrząsy       kamery"
lang_gui[2,49] = "Zoom       Kamery"
lang_gui[2,50] = "Wyświetlaj       Ruchy"
lang_gui[2,51] = "Paski       Życia       Wrogów"
lang_gui[2,52] = "Sensytywność"
lang_gui[2,53] = "Latwy"
lang_gui[2,54] = "Normalny"
lang_gui[2,55] = "Trudny"
lang_gui[2,56] = "Koszmarny"
lang_gui[2,57] = "Szalony"
//Saving Prompts
lang_gui[2,58] = "Zapisywanie     .     .     ."
lang_gui[2,59] = "Zapisywanie     Domyślnych     .     .     ."
//Language
lang_gui[2,60] = "Język: Polski"
lang_gui[2,61] = "Typ"
//Freeze Frames
lang_gui[2,62] = "Stopklatki"

//Spanish
lang_gui[3,0] = "Jugar"
lang_gui[3,1] = "Editor"
lang_gui[3,2] = "Campaña"
lang_gui[3,3] = "Opciones"
lang_gui[3,4] = "Salir"
lang_gui[3,5] = "Modo     Historia"
lang_gui[3,6] = "Modo     Clásico"
lang_gui[3,7] = "Modo     de     Carrera"
lang_gui[3,8] = "Atrás"
//Options Menu
lang_gui[3,9] = "Tamaño     de     la     Pantalla"
lang_gui[3,10] = "Shader     de     la     Paleta"
lang_gui[3,11] = "Volumen     de     Música"
lang_gui[3,12] = "Volumen     de     Sonidos"
lang_gui[3,13] = "Controles.   .   ."
lang_gui[3,14] = "Idioma"
lang_gui[3,15] = "Configuraciones     de     Jugabilidad.   .   ."
lang_gui[3,16] = "OK"
//On/Off
lang_gui[3,17] = "Desactivar"
lang_gui[3,18] = "Activar"
//Control Settings
lang_gui[3,19] = "(ESC - Reiniciar al defecto)"
lang_gui[3,20] = "Arriba"
lang_gui[3,21] = "Abajo"
lang_gui[3,22] = "Izquierda"
lang_gui[3,23] = "Derecha"
lang_gui[3,24] = "ARRIBA"
lang_gui[3,25] = "ABAJO"
lang_gui[3,26] = "IZQUIERDA"
lang_gui[3,27] = "DERECHA"
lang_gui[3,28] = "ACCIÓN"
lang_gui[3,29] = "SALTO"
lang_gui[3,30] = "ESPECIAL"
lang_gui[3,31] = "CAMBIAR"
lang_gui[3,32] = "COMENZAR"
lang_gui[3,33] = "(ESC - Reiniciar al defecto)"
lang_gui[3,34] = "(Pulsa/Arrastra Arriba o Abajo)"
//Editor Control Settings
lang_gui[3,35] = "COLOCAR"
lang_gui[3,36] = "COPIAR"
lang_gui[3,37] = "BORRAR"
lang_gui[3,38] = "NUEVO OBJETO"
lang_gui[3,39] = "DESHACER"
lang_gui[3,40] = "REHACER"
lang_gui[3,41] = "MODO DE JUEGO"
lang_gui[3,42] = "SALIR"
lang_gui[3,43] = "CAPA"
lang_gui[3,44] = "FIJAR"
lang_gui[3,45] = "ZOOM"
//Gameplay Settings
lang_gui[3,46] = "Jugabilidad"
lang_gui[3,47] = "Dificultad"
lang_gui[3,48] = "Temblor       de       Cámara"
lang_gui[3,49] = "Zoom       de       Cámara"
lang_gui[3,50] = "Mostrar       Movimientos"
lang_gui[3,51] = "Barras       de       PV       de       Enemigos"
lang_gui[3,52] = "Sensibilidad"
lang_gui[3,53] = "Fácil"
lang_gui[3,54] = "Normal"
lang_gui[3,55] = "Difícil"
lang_gui[3,56] = "Severo"
lang_gui[3,57] = "Insanidad"
//Saving Prompts
lang_gui[3,58] = "Guardando     .     .     ."
lang_gui[3,59] = "Guardando     Defecto     .     .     ."
//Language
lang_gui[3,60] = "Idioma: Español"
lang_gui[3,61] = "Tipo"
//Freeze Frames
lang_gui[3,62] = "Frames     de     Impacto"

//German
lang_gui[4,0] = "Spielen"
lang_gui[4,1] = "Editor"
lang_gui[4,2] = "kampagne"
lang_gui[4,3] = "Optionen"
lang_gui[4,4] = "Beenden"
lang_gui[4,5] = "Story     Modus"
lang_gui[4,6] = "Klassik     Modus"
lang_gui[4,7] = "Zeit     Attacke"
lang_gui[4,8] = "Zurück"
//Options Menu
lang_gui[4,9] = "Screen       Size"
lang_gui[4,10] = "Palette     Shader"
lang_gui[4,11] = "Music       Volume"
lang_gui[4,12] = "Sound       Volume"
lang_gui[4,13] = "Controls.   .   ."
lang_gui[4,14] = "Language"
lang_gui[4,15] = "Gameplay       Settings.   .   ."
lang_gui[4,16] = "Okay"
//On/Off
lang_gui[4,17] = "Aus"
lang_gui[4,18] = "An"
//Control Settings
lang_gui[4,19] = "(ESC - Standard zurücksetzen)"
lang_gui[4,20] = "Hoch"
lang_gui[4,21] = "Runter"
lang_gui[4,22] = "Links"
lang_gui[4,23] = "Rechts"
lang_gui[4,24] = "HOCH"
lang_gui[4,25] = "RUNTER"
lang_gui[4,26] = "LINKS"
lang_gui[4,27] = "RECHTS"
lang_gui[4,28] = "AKTION"
lang_gui[4,29] = "SPRINGEN"
lang_gui[4,30] = "SPEZIAL"
lang_gui[4,31] = "ÄNDERN"
lang_gui[4,32] = "START"
lang_gui[4,33] = "(ESC - Zurücksetzen)"
lang_gui[4,34] = "(Press/Scroll Up or Down)"
//Editor Control Settings
lang_gui[4,35] = "PLATZIEREN"
lang_gui[4,36] = "KOPIEREN"
lang_gui[4,37] = "LÖSCHEN"
lang_gui[4,38] = "NEUER TILE"
lang_gui[4,39] = "RÜCKG."
lang_gui[4,40] = "WIEDERH."
lang_gui[4,41] = "SPIELEN"
lang_gui[4,42] = "EXIT"
lang_gui[4,43] = "LAYER"
lang_gui[4,44] = "SNAP"
lang_gui[4,45] = "ZOOM"
//Gameplay Settings
lang_gui[4,46] = "Gameplay"
lang_gui[4,47] = "Schwierigkeit"
lang_gui[4,48] = "Kamera     Wackeln"
lang_gui[4,49] = "Kamera       Zoom"
lang_gui[4,50] = "Display       Moves"
lang_gui[4,51] = "Gegner     HP      Balken"
lang_gui[4,52] = "Sensibilität"
lang_gui[4,53] = "Leicht"
lang_gui[4,54] = "Mittel"
lang_gui[4,55] = "Schwer"
lang_gui[4,56] = "Hardcore"
lang_gui[4,57] = "Wahnsinn"
//Saving Prompts
lang_gui[4,58] = "Speichern    .     .     ."
lang_gui[4,59] = "Standardwerte speichern     .     .     ."
//Language
lang_gui[4,60] = "Sprache: Deutsch"
lang_gui[4,61] = "Typ"
//Freeze Frames
lang_gui[4,62] = "Standbilder"

//Russian
lang_gui[5,0] = "Играть"
lang_gui[5,1] = "Редактор"
lang_gui[5,2] = "Кампания"
lang_gui[5,3] = "Опции"
lang_gui[5,4] = "Выход"
lang_gui[5,5] = "Режим     Истории"
lang_gui[5,6] = "Классический     Режим"
lang_gui[5,7] = "Игра     На     Время"
lang_gui[5,8] = "Назад"
//Options Menu
lang_gui[5,9] = "Размер       Экрана"
lang_gui[5,10] = "Палитра     Шейдеров"
lang_gui[5,11] = "Громкость       Музыки"
lang_gui[5,12] = "Громкость       Звука"
lang_gui[5,13] = "Управление.   .   ."
lang_gui[5,14] = "Язык"
lang_gui[5,15] = "Настройки       Игрового       Процесса.   .   ."
lang_gui[5,16] = "Ок"
//On/Off
lang_gui[5,17] = "Выкл."
lang_gui[5,18] = "Вкл."
//Control Settings
lang_gui[5,19] = "(ESC - Настройки По Умолчанию)"
lang_gui[5,20] = "Вверх"
lang_gui[5,21] = "Вниз"
lang_gui[5,22] = "Влево"
lang_gui[5,23] = "Вправо"
lang_gui[5,24] = "ВВЕРХ"
lang_gui[5,25] = "ВНИЗ"
lang_gui[5,26] = "ВЛЕВО"
lang_gui[5,27] = "ВПРАВО"
lang_gui[5,28] = "ДЕЙСТВИЕ"
lang_gui[5,29] = "ПРЫЖОК"
lang_gui[5,30] = "СПЕЦИАЛЬНЫЙ"
lang_gui[5,31] = "ПЕРЕКЛЮЧИТЬ"
lang_gui[5,32] = "СТАРТ"
lang_gui[5,33] = "(ESC - Отменить Изменения)"
lang_gui[5,34] = "(Нажмите/Прокрутите ВВерх или Вниз)"
//Editor Control Settings
lang_gui[5,35] = "ПОСТАВИТЬ"
lang_gui[5,36] = "КОПИРОВАТЬ"
lang_gui[5,37] = "УДАЛИТЬ"
lang_gui[5,38] = "НОВЫЙ ТАЙЛ"
lang_gui[5,39] = "НАЗАД"
lang_gui[5,40] = "ВПЕРЁД"
lang_gui[5,41] = "РЕЖИМ ИГРЫ"
lang_gui[5,42] = "ВЫХОД"
lang_gui[5,43] = "СЛОЙ"
lang_gui[5,44] = "ЩЁЛК"
lang_gui[5,45] = "ЗУМ"
//Gameplay Settings
lang_gui[5,46] = "Игровой Процесс"
lang_gui[5,47] = "Сложность"
lang_gui[5,48] = "Тряска     Камеры"
lang_gui[5,49] = "Зум       Камеры"
lang_gui[5,50] = "Показывать       Движения"
lang_gui[5,51] = "Полоска      Здоровья      Врага"
lang_gui[5,52] = "Чувствительность"
lang_gui[5,53] = "Лёгкая"
lang_gui[5,54] = "Нормальная"
lang_gui[5,55] = "Трудная"
lang_gui[5,56] = "Хардкорная"
lang_gui[5,57] = "Безумие"
//Saving Prompts
lang_gui[5,58] = "Сохранение     .     .     ."
lang_gui[5,59] = "Сохранение     По     Умолчанию     .     .     ."
//Language
lang_gui[5,60] = "Язык: Русский"
lang_gui[5,61] = "Тип"
//Freeze Frames
lang_gui[5,62] = "Стопкадры"
