///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Interior 1"
o.display_page_description[1] = "Interior 2"
o.display_page_description[2] = "Decoración"
o.display_page_description[3] = "???"
o.display_page_description[4] = "???"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Panel de Piso 1"
o.display_description_item[o.display_page_one,1] = "Panel de Piso 2"
o.display_description_item[o.display_page_one,2] = "Panel de Piso 3"
o.display_description_item[o.display_page_one,3] = "Panel de Pared 1"
o.display_description_item[o.display_page_one,4] = "Panel de Pared 2"
o.display_description_item[o.display_page_one,5] = "Panel de Techo 1"
o.display_description_item[o.display_page_one,6] = "Panel de Techo 2"
o.display_description_item[o.display_page_one,7] = "Panel de Techo 3"
o.display_description_item[o.display_page_one,8] = "Panel de Esquina 1"
o.display_description_item[o.display_page_one,9] = "Panel de Esquina 2"
o.display_description_item[o.display_page_one,10] = "Panel de Esquina 3"
o.display_description_item[o.display_page_one,11] = "Panel de Esquina 4"
o.display_description_item[o.display_page_one,12] = "Panel de Esquina 5"
o.display_description_item[o.display_page_one,13] = "Panel de Piso 4"
o.display_description_item[o.display_page_one,14] = "Panel de Piso 5"
o.display_description_item[o.display_page_one,15] = "Panel de Pared 3"
o.display_description_item[o.display_page_one,16] = "Panel de Pared 4"
o.display_description_item[o.display_page_one,17] = "Panel de Pared 5"
o.display_description_item[o.display_page_one,18] = "Panel de Pared 6"
o.display_description_item[o.display_page_one,19] = "Panel de Pared 7"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Panel de Piso Alternativo 1"
o.display_description_item[o.display_page_two,1] = "Panel de Piso Alternativo 2"
o.display_description_item[o.display_page_two,2] = "Panel de Piso Alternativo 3"
o.display_description_item[o.display_page_two,3] = "Puente de Metal"
o.display_description_item[o.display_page_two,4] = "Tubería de Metal"
o.display_description_item[o.display_page_two,5] = ""
o.display_description_item[o.display_page_two,6] = ""
o.display_description_item[o.display_page_two,7] = "Panel de Pared Alternativo 1"
o.display_description_item[o.display_page_two,8] = "Panel de Pared Alternativo 2"
o.display_description_item[o.display_page_two,9] = "Panel de Pared Alternativo 3"
o.display_description_item[o.display_page_two,10] = ""
o.display_description_item[o.display_page_two,11] = "Bucle Oxidado 1"
o.display_description_item[o.display_page_two,12] = "Bucle Oxidado 2"
o.display_description_item[o.display_page_two,13] = "Panel de Techo Alternativo 1"
o.display_description_item[o.display_page_two,14] = "Panel de Techo Alternativo 2"
o.display_description_item[o.display_page_two,15] = "Panel de Techo Alternativo 3"
o.display_description_item[o.display_page_two,16] = ""
o.display_description_item[o.display_page_two,17] = ""
o.display_description_item[o.display_page_two,18] = "Bucle Oxidado 3"
o.display_description_item[o.display_page_two,19] = "Bucle Oxidado 4"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Pilar"
o.display_description_item[o.display_page_three,1] = "Pasillo"
o.display_description_item[o.display_page_three,2] = "Panel de Puerta 1"
o.display_description_item[o.display_page_three,3] = "Panel de Puerta 2"
o.display_description_item[o.display_page_three,4] = "Planta Marchitada"
o.display_description_item[o.display_page_three,5] = "Pilar Verde"
o.display_description_item[o.display_page_three,6] = "Pilar de Bronce"
o.display_description_item[o.display_page_three,7] = "Panel Transportador Roto"
o.display_description_item[o.display_page_three,8] = "Ventilación Oxidada"
o.display_description_item[o.display_page_three,9] = "Monitor Roto"
o.display_description_item[o.display_page_three,10] = "Shade Trooper Shell 1"
o.display_description_item[o.display_page_three,11] = "Shade Trooper Shell 2"
o.display_description_item[o.display_page_three,12] = "Shade Trooper Shell 3"
o.display_description_item[o.display_page_three,13] = "Monitor de Estado"
o.display_description_item[o.display_page_three,14] = ""
o.display_description_item[o.display_page_three,15] = ""
o.display_description_item[o.display_page_three,16] = ""
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""
