///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Plataformas"
o.display_page_description[1] = "Suportes"
o.display_page_description[2] = "Rampas"
o.display_page_description[3] = "Decoração 1"
o.display_page_description[4] = "Decoração 2"
o.display_page_description[5] = "Decoração 3"
o.display_page_description[6] = "Decoração 4"
o.display_page_description[7] = "Decoração 5"
o.display_page_description[8] = "Descartadas"
o.display_page_description[9] = "Extras 1"
o.display_page_description[10] = "Extras 2"
o.display_page_description[11] = "Tijolos Alternativos"
o.display_page_description[12] = "Extras 3"
o.display_page_description[13] = "Extras 4"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Plataforma de Tijolos 1"
o.display_description_item[o.display_page_one,1] = "Plataforma de Tijolos 2"
o.display_description_item[o.display_page_one,2] = "Parede de Tijolos 1"
o.display_description_item[o.display_page_one,3] = "Parede de Tijolos 2"
o.display_description_item[o.display_page_one,4] = "Parede de Tijolos 3"
o.display_description_item[o.display_page_one,5] = "Parede de Tijolos 4"
o.display_description_item[o.display_page_one,6] = "Bloco de Tijolos 1"
o.display_description_item[o.display_page_one,7] = "Bloco de Tijolos 2"
o.display_description_item[o.display_page_one,8] = "Bloco de Tijolos 3"
o.display_description_item[o.display_page_one,9] = "Tijolo Vermelho"
o.display_description_item[o.display_page_one,10] = "Tijolo Azul"
o.display_description_item[o.display_page_one,11] = "Divisor de Paredes 1"
o.display_description_item[o.display_page_one,12] = "Divisor de Paredes 2"
o.display_description_item[o.display_page_one,13] = "Cano Reto 1"
o.display_description_item[o.display_page_one,14] = "Cano Reto 2"
o.display_description_item[o.display_page_one,15] = "Cano Reto 3"
o.display_description_item[o.display_page_one,16] = "Cano Reto 4"
o.display_description_item[o.display_page_one,17] = "Pedaço Final do Cano 1"
o.display_description_item[o.display_page_one,18] = "Pedaço Final do Cano 2"
o.display_description_item[o.display_page_one,19] = "Pedaço Final do Cano 3"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Divisor de Paredes 1"
o.display_description_item[o.display_page_two,1] = "Divisor de Paredes 2"
o.display_description_item[o.display_page_two,2] = "Divisor de Paredes 3"
o.display_description_item[o.display_page_two,3] = "Divisor de Paredes 4"
o.display_description_item[o.display_page_two,4] = "Divisor de Paredes 5"
o.display_description_item[o.display_page_two,5] = "Divisor de Paredes 6"
o.display_description_item[o.display_page_two,6] = "Divisor de Paredes 7"
o.display_description_item[o.display_page_two,7] = "Divisor de Paredes 1"
o.display_description_item[o.display_page_two,8] = "Cano Reto 1"
o.display_description_item[o.display_page_two,9] = "Cano Reto 2"
o.display_description_item[o.display_page_two,10] = "Cano Reto 3"
o.display_description_item[o.display_page_two,11] = "Cano Reto 4"
o.display_description_item[o.display_page_two,12] = "Cano Reto 5"
o.display_description_item[o.display_page_two,13] = "Pedaço Final do Cano 1"
o.display_description_item[o.display_page_two,14] = "Pedaço Final do Cano 2"
o.display_description_item[o.display_page_two,15] = "Calçada - 1"
o.display_description_item[o.display_page_two,16] = "Calçada - 2"
o.display_description_item[o.display_page_two,17] = "Calçada - 3"
o.display_description_item[o.display_page_two,18] = "Calçada - 4"
o.display_description_item[o.display_page_two,19] = "Viga de Construção - Amarelo 3"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Viga de um Quarto de Cano 1"
o.display_description_item[o.display_page_three,1] = "Viga de um Quarto de Cano 2"
o.display_description_item[o.display_page_three,2] = "Viga de um Quarto de Cano 3"
o.display_description_item[o.display_page_three,3] = "Viga de um Quarto de Cano 4"
o.display_description_item[o.display_page_three,4] = "Viga de um Quarto de Cano 1 - Invertido"
o.display_description_item[o.display_page_three,5] = "Viga de um Quarto de Cano 2 - Invertido"
o.display_description_item[o.display_page_three,6] = "Plataforma Flutuante 1"
o.display_description_item[o.display_page_three,7] = "Peça do Loop-De-Loop 1"
o.display_description_item[o.display_page_three,8] = "Peça do Loop-De-Loop 2"
o.display_description_item[o.display_page_three,9] = "Peça do Loop-De-Loop 3"
o.display_description_item[o.display_page_three,10] = "Peça do Loop-De-Loop 4"
o.display_description_item[o.display_page_three,11] = "Viga de um Quarto de Cano 3 - Invertido"
o.display_description_item[o.display_page_three,12] = "Viga de um Quarto de Cano 4 - Invertido"
o.display_description_item[o.display_page_three,13] = "Colina da Estrada 1"
o.display_description_item[o.display_page_three,14] = "Colina da Estrada 2"
o.display_description_item[o.display_page_three,15] = "Colina da Estrada 3"
o.display_description_item[o.display_page_three,16] = "Colina da Estrada 4"
o.display_description_item[o.display_page_three,17] = "Declive da Estrada - Esquerda"
o.display_description_item[o.display_page_three,18] = "Declive da Estrada - Direita"
o.display_description_item[o.display_page_three,19] = "Plataforma Flutuante 2"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Janela - Grande"
o.display_description_item[o.display_page_four,1] = "Janela - Pequena 1"
o.display_description_item[o.display_page_four,2] = "Janela - Pequena 2"
o.display_description_item[o.display_page_four,3] = "Unidade de Ar-Condicionado 1"
o.display_description_item[o.display_page_four,4] = "Unidade de Ar-Condicionado 2"
o.display_description_item[o.display_page_four,5] = "Telescópio Refletor"
o.display_description_item[o.display_page_four,6] = "Telescópio Refrator"
o.display_description_item[o.display_page_four,7] = "Decoração - Cano - Conector Vertical"
o.display_description_item[o.display_page_four,8] = "Decoração - Cano - Conector Horizontal"
o.display_description_item[o.display_page_four,9] = "Decoração - Cano - Superior"
o.display_description_item[o.display_page_four,10] = "Decoração - Cano - Inferior"
o.display_description_item[o.display_page_four,11] = "Topo do Poste Utilitário"
o.display_description_item[o.display_page_four,12] = "Poste Utilitário"
o.display_description_item[o.display_page_four,13] = "Guarda-Sol"
o.display_description_item[o.display_page_four,14] = "Logo dos cometas de gelo da Ziyo"
o.display_description_item[o.display_page_four,15] = "Vaca-Preta 1"
o.display_description_item[o.display_page_four,16] = "Vaca-Preta 2"
o.display_description_item[o.display_page_four,17] = "Vaca-Preta 3"
o.display_description_item[o.display_page_four,18] = "Tigela de Sorvete"
o.display_description_item[o.display_page_four,19] = "Banana Split"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Decoração - Viga de Apoio 1"
o.display_description_item[o.display_page_five,1] = "Decoração - Defensa Metálica"
o.display_description_item[o.display_page_five,2] = "Decoração - Calçada"
o.display_description_item[o.display_page_five,3] = "Decoração - Rua"
o.display_description_item[o.display_page_five,4] = "Decoração - Moldura de Janela"
o.display_description_item[o.display_page_five,5] = "Decoração - Outdoor 1"
o.display_description_item[o.display_page_five,6] = "Decoração - Outdoor 2"
o.display_description_item[o.display_page_five,7] = "Decoração - Parede de Tijolos 1"
o.display_description_item[o.display_page_five,8] = "Decoração - Parede de Tijolos 2"
o.display_description_item[o.display_page_five,9] = "Decoração - Parede de Tijolos 3"
o.display_description_item[o.display_page_five,10] = "Decoração - Construção 1"
o.display_description_item[o.display_page_five,11] = "Decoração - Construção 2"
o.display_description_item[o.display_page_five,12] = "Decoração - Torre de Água"
o.display_description_item[o.display_page_five,13] = "Decoração - Pôster de Starbuster"
o.display_description_item[o.display_page_five,14] = "Decoração - Pôster de HavocFox"
o.display_description_item[o.display_page_five,15] = "Decoração - Anúncio 1"
o.display_description_item[o.display_page_five,16] = "Decoração - Anúncio 2"
o.display_description_item[o.display_page_five,17] = "Decoração - Placa de Pare"
o.display_description_item[o.display_page_five,18] = "Decoração - Placa de Rendimento"
o.display_description_item[o.display_page_five,19] = "Decoração - Travessia Ninja"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Lixeira de Reciclagem"
o.display_description_item[o.display_page_six,1] = "Caçamba de Lixo Reciclado"
o.display_description_item[o.display_page_six,2] = "Placa de Rua - Rua Leste"
o.display_description_item[o.display_page_six,3] = "Placa de Rua - Circlo Norte"
o.display_description_item[o.display_page_six,4] = "Placa de Rua - Unidade Sul"
o.display_description_item[o.display_page_six,5] = "Placa de Rua - Pista Oeste"
o.display_description_item[o.display_page_six,6] = "Placa de Rua em Branco"
o.display_description_item[o.display_page_six,7] = "Sinal de Seta"
o.display_description_item[o.display_page_six,8] = "Placa de Piso Molhado"
o.display_description_item[o.display_page_six,9] = "Semáforos"
o.display_description_item[o.display_page_six,10] = "Poste de Luz"
o.display_description_item[o.display_page_six,11] = "Poste de Luz 1"
o.display_description_item[o.display_page_six,12] = "Poste de Luz 2"
o.display_description_item[o.display_page_six,13] = "Poste de Luz 3"
o.display_description_item[o.display_page_six,14] = "Poste de Luz 1"
o.display_description_item[o.display_page_six,15] = "Berinjela Única"
o.display_description_item[o.display_page_six,16] = "Varal de Roupas"
o.display_description_item[o.display_page_six,17] = "Sinal de Passagem de Pedestres"
o.display_description_item[o.display_page_six,18] = "Sinal para Pedestres"
o.display_description_item[o.display_page_six,19] = "Lixeira   "

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Viga de Suporte Amarela - Completo 1"
o.display_description_item[o.display_page_seven,1] = "Viga de Suporte Amarela - Angulada 1"
o.display_description_item[o.display_page_seven,2] = "Viga de Suporte Amarela - Angulada 2"
o.display_description_item[o.display_page_seven,3] = "Viga de Suporte Vermelha - Angulada 1"
o.display_description_item[o.display_page_seven,4] = "Viga de Suporte Vermelha - Angulada 2"
o.display_description_item[o.display_page_seven,5] = "Viga de Suporte - Vermelho 3"
o.display_description_item[o.display_page_seven,6] = "Viga de Suporte Amarela - Completo 2"
o.display_description_item[o.display_page_seven,7] = "Viga de Suporte Amarela - Peça 1"
o.display_description_item[o.display_page_seven,8] = "Viga de Suporte Amarela - Peça 2"
o.display_description_item[o.display_page_seven,9] = "Viga de Suporte Amarela - Peça 3"
o.display_description_item[o.display_page_seven,10] = "Viga de Suporte Amarela - Peça 4"
o.display_description_item[o.display_page_seven,11] = "Viga de Suporte Amarela - Peça 5"
o.display_description_item[o.display_page_seven,12] = "Viga de Suporte Amarela - Peça 6"
o.display_description_item[o.display_page_seven,13] = "Viga de Apoio para Construção - Lateral"
o.display_description_item[o.display_page_seven,14] = "Cone de Trânsito - Grande"
o.display_description_item[o.display_page_seven,15] = "Cone de Trânsito - Pequeno"
o.display_description_item[o.display_page_seven,16] = "Cone de Trânsito - 1"
o.display_description_item[o.display_page_seven,17] = "Cone de Trânsito - 2"
o.display_description_item[o.display_page_seven,18] = "Cone de Trânsito - 3"
o.display_description_item[o.display_page_seven,19] = "Cone de Trânsito - 4"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Decoração - Cano - Parte Superior"
o.display_description_item[o.display_page_eight,1] = "Decoração - Cano - Conector Vertical"
o.display_description_item[o.display_page_eight,2] = "Decoração - Cano - Parte Inferior"
o.display_description_item[o.display_page_eight,3] = "Decoração - Cano - Conector Horizontal"
o.display_description_item[o.display_page_eight,4] = "Mesa de Restaurante"
o.display_description_item[o.display_page_eight,5] = "Estante Larga"
o.display_description_item[o.display_page_eight,6] = "Cano Horizontal"
o.display_description_item[o.display_page_eight,7] = "Viga de Construção - Médio 1"
o.display_description_item[o.display_page_eight,8] = "Viga de Construção - Médio 2"
o.display_description_item[o.display_page_eight,9] = "Viga de Construção - Médio 3"
o.display_description_item[o.display_page_eight,10] = "Viga de Construção - Médio 4"
o.display_description_item[o.display_page_eight,11] = "Decoração - Cerca"
o.display_description_item[o.display_page_eight,12] = "Viga de Apoio para Construção - Pequena"
o.display_description_item[o.display_page_eight,13] = "Espinhos de Metal - 1"
o.display_description_item[o.display_page_eight,14] = "Espinhos de Metal - 2"
o.display_description_item[o.display_page_eight,15] = "Espinhos de Metal - 3"
o.display_description_item[o.display_page_eight,16] = "Espinhos de Metal - 4"
o.display_description_item[o.display_page_eight,17] = "Escada 1"
o.display_description_item[o.display_page_eight,18] = "Escada 2"
o.display_description_item[o.display_page_eight,19] = "Barra Suspensa 1"

//Tile Descriptions (Page 9)
o.display_description_item[o.display_page_nine,0] = "Plataforma de Tijolos - Descartado 1"
o.display_description_item[o.display_page_nine,1] = "Plataforma de Tijolos - Descartado 2"
o.display_description_item[o.display_page_nine,2] = "Parede de Tijolos - Descartado 1"
o.display_description_item[o.display_page_nine,3] = "Parede de Tijolos - Descartado 2"
o.display_description_item[o.display_page_nine,4] = "Parede de Tijolos - Descartado 3"
o.display_description_item[o.display_page_nine,5] = "Plataforma de Tijolos - Descartado 3"
o.display_description_item[o.display_page_nine,6] = "Parede de Tijolos - Descartado 4"
o.display_description_item[o.display_page_nine,7] = "Parede de Tijolos - Descartado 5"
o.display_description_item[o.display_page_nine,8] = "Calçada - Descartado 1"
o.display_description_item[o.display_page_nine,9] = "Parede de Tijolos - Descartado 6"
o.display_description_item[o.display_page_nine,10] = "Parede de Tijolos - Descartado 7"
o.display_description_item[o.display_page_nine,11] = "Outdoor em Branco - Descartado 1"
o.display_description_item[o.display_page_nine,12] = "Outdoor em Branco - Descartado 2"
o.display_description_item[o.display_page_nine,13] = "Outdoor em Branco - Descartado 3"
o.display_description_item[o.display_page_nine,14] = "Cano - Descartado 1"
o.display_description_item[o.display_page_nine,15] = "Cano - Descartado 2"
o.display_description_item[o.display_page_nine,16] = "Cano - Descartado 3"
o.display_description_item[o.display_page_nine,17] = "Cano - Descartado 4"
o.display_description_item[o.display_page_nine,18] = "Unknown Tile"
o.display_description_item[o.display_page_nine,19] = "Unknown Tile"

//Tile Descriptions (Page 10)
o.display_description_item[o.display_page_ten,0] = "Parede de Tijolos - Extra 1"
o.display_description_item[o.display_page_ten,1] = "Parede de Tijolos - Extra 2"
o.display_description_item[o.display_page_ten,2] = "Parede de Tijolos - Extra 3"
o.display_description_item[o.display_page_ten,3] = "Parede de Tijolos - Extra 4"
o.display_description_item[o.display_page_ten,4] = "Parede de Tijolos - Extra 5"
o.display_description_item[o.display_page_ten,5] = "Parede de Tijolos - Extra 6"
o.display_description_item[o.display_page_ten,6] = "Parede de Tijolos - Extra 7"
o.display_description_item[o.display_page_ten,7] = "Peça de Canto 1"
o.display_description_item[o.display_page_ten,8] = "Peça de Canto 2"
o.display_description_item[o.display_page_ten,9] = "Peça de Canto 3"
o.display_description_item[o.display_page_ten,10] = "Peça de Canto 4"
o.display_description_item[o.display_page_ten,11] = "Parede de Tijolos - Extra 8"
o.display_description_item[o.display_page_ten,12] = "Parede de Tijolos - Extra 9"
o.display_description_item[o.display_page_ten,13] = "Peça de Canto 5"
o.display_description_item[o.display_page_ten,14] = "Peça de Canto 6"
o.display_description_item[o.display_page_ten,15] = "Peça de Canto 7"
o.display_description_item[o.display_page_ten,16] = "Plataforma de Tilojos - Borda Esquerda"
o.display_description_item[o.display_page_ten,17] = "Plataforma de Tilojos  - Parte do Meio"
o.display_description_item[o.display_page_ten,18] = "Plataforma de Tilojos  - Borda Direita"
o.display_description_item[o.display_page_ten,19] = "Parede de Tijolos - Extra 10"

//Tile Descriptions (Page 11)
o.display_description_item[o.display_page_eleven,0] = "Loop de Tijolos - 1"
o.display_description_item[o.display_page_eleven,1] = "Loop de Tijolos - 2"
o.display_description_item[o.display_page_eleven,2] = "Parede de Tijolos - Extra 3"
o.display_description_item[o.display_page_eleven,3] = "Parede de Tijolos - Extra 4"
o.display_description_item[o.display_page_eleven,4] = "Parede de Tijolos - Extra 5"
o.display_description_item[o.display_page_eleven,5] = "Parede de Tijolos - Extra 6"
o.display_description_item[o.display_page_eleven,6] = "Parede de Tijolos - Extra 7"
o.display_description_item[o.display_page_eleven,7] = "Loop de Tijolos - 3"
o.display_description_item[o.display_page_eleven,8] = "Loop de Tijolos - 4"
o.display_description_item[o.display_page_eleven,9] = "Peça de Canto 3"
o.display_description_item[o.display_page_eleven,10] = "Peça de Canto 4"
o.display_description_item[o.display_page_eleven,11] = "Parede de Tijolos - Extra 8"
o.display_description_item[o.display_page_eleven,12] = "Parede de Tijolos - Extra 9"
o.display_description_item[o.display_page_eleven,13] = "Peça de Canto 5"
o.display_description_item[o.display_page_eleven,14] = "Peça de Canto 6"
o.display_description_item[o.display_page_eleven,15] = "Peça de Canto 7"
o.display_description_item[o.display_page_eleven,16] = "Plataforma de Tilojos - Borda Esquerda"
o.display_description_item[o.display_page_eleven,17] = "Plataforma de Tilojos  - Parte do Meio"
o.display_description_item[o.display_page_eleven,18] = "Plataforma de Tilojos  - Borda Direita"
o.display_description_item[o.display_page_eleven,19] = "Parede de Tijolos - Extra 10"

//Tile Descriptions (Page 12)
o.display_description_item[o.display_page_twelve,0] = "Plataforma de Tijolos 1"
o.display_description_item[o.display_page_twelve,1] = "Plataforma de Tijolos 2"
o.display_description_item[o.display_page_twelve,2] = "Parede de Tijolos 1"
o.display_description_item[o.display_page_twelve,3] = "Parede de Tijolos 2"
o.display_description_item[o.display_page_twelve,4] = "Parede de Tijolos 3"
o.display_description_item[o.display_page_twelve,5] = "Parede de Tijolos 4"
o.display_description_item[o.display_page_twelve,6] = "Bloco de 1"
o.display_description_item[o.display_page_twelve,7] = "Bloco de 2"
o.display_description_item[o.display_page_twelve,8] = "Bloco de 3"
o.display_description_item[o.display_page_twelve,9] = "Tijolo Vermelho"
o.display_description_item[o.display_page_twelve,10] = "Tijolo Azul"
o.display_description_item[o.display_page_twelve,11] = "Divisor de Paredes 1"
o.display_description_item[o.display_page_twelve,12] = "Divisor de Paredes 2"
o.display_description_item[o.display_page_twelve,13] = "Cano Reto 1"
o.display_description_item[o.display_page_twelve,14] = "Cano Reto 2"
o.display_description_item[o.display_page_twelve,15] = "Cano Reto 3"
o.display_description_item[o.display_page_twelve,16] = "Cano Reto 4"
o.display_description_item[o.display_page_twelve,17] = "Pedaço Final do Cano 1"
o.display_description_item[o.display_page_twelve,18] = "Pedaço Final do Cano 2"
o.display_description_item[o.display_page_twelve,19] = "Pedaço Final do Cano 3"

//Tile Descriptions (Page 13)
o.display_description_item[o.display_page_thirteen,0] = "Placa Rua Dragão"
o.display_description_item[o.display_page_thirteen,1] = "Placa Pista Faisão"
o.display_description_item[o.display_page_thirteen,2] = "Placa Rua Fantail"
o.display_description_item[o.display_page_thirteen,3] = "Placa Praça Panya"
o.display_description_item[o.display_page_thirteen,4] = "Placa Pista Fuzhu"
o.display_description_item[o.display_page_thirteen,5] = "Placa Pista Qilin"
o.display_description_item[o.display_page_thirteen,6] = "Placa Rua Fênix"
o.display_description_item[o.display_page_thirteen,7] = "Placa Interestadual 1"
o.display_description_item[o.display_page_thirteen,8] = "Placa Interestadual 2"
o.display_description_item[o.display_page_thirteen,9] = "Suporte da Placa Interestadual 1"
o.display_description_item[o.display_page_thirteen,10] = "Suporte da Placa Interestadual 2"
o.display_description_item[o.display_page_thirteen,11] = "Suporte da Placa Interestadual 3"
o.display_description_item[o.display_page_thirteen,12] = "Suporte da Placa Interestadual 4"
o.display_description_item[o.display_page_thirteen,13] = "Templo do Dragão - Viga de Suporte"
o.display_description_item[o.display_page_thirteen,14] = "Templo do Dragão - Lâmpada"
o.display_description_item[o.display_page_thirteen,15] = "Templo do Dragão - Portão"
o.display_description_item[o.display_page_thirteen,16] = "Templo do Dragão - Cerca"
o.display_description_item[o.display_page_thirteen,17] = "Templo do Dragão - Poste da Cerca"
o.display_description_item[o.display_page_thirteen,18] = "Vaso de Bambu"
o.display_description_item[o.display_page_thirteen,19] = "Pintura de Fuzhu"

//Tile Descriptions (Page 14)
o.display_description_item[o.display_page_fourteen,0] = "Templo do Dragão - Estátua do Dragão"
o.display_description_item[o.display_page_fourteen,1] = "Templo do Dragão - Estátua de Fuzhu"
o.display_description_item[o.display_page_fourteen,2] = "Placa de Restaurant Alt - Sushi Panya"
o.display_description_item[o.display_page_fourteen,3] = "Templo do Dragão - Mural do Dragão"
o.display_description_item[o.display_page_fourteen,4] = "Bar de Sushi do Timmy Atum Para Crianças - Placa"
o.display_description_item[o.display_page_fourteen,5] = "Placa Aberto"
o.display_description_item[o.display_page_fourteen,6] = "Placa Fechado"
o.display_description_item[o.display_page_fourteen,7] = ""
o.display_description_item[o.display_page_fourteen,8] = ""
o.display_description_item[o.display_page_fourteen,9] = ""
o.display_description_item[o.display_page_fourteen,10] = ""
o.display_description_item[o.display_page_fourteen,11] = ""
o.display_description_item[o.display_page_fourteen,12] = ""
o.display_description_item[o.display_page_fourteen,13] = ""
o.display_description_item[o.display_page_fourteen,14] = ""
o.display_description_item[o.display_page_fourteen,15] = ""
o.display_description_item[o.display_page_fourteen,16] = ""
o.display_description_item[o.display_page_fourteen,17] = ""
o.display_description_item[o.display_page_fourteen,18] = ""
o.display_description_item[o.display_page_fourteen,19] = ""

