///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Platforms"
o.display_page_description[1] = "Walls"
o.display_page_description[2] = "Slopes"
o.display_page_description[3] = "Scenery"
o.display_page_description[4] = "Extras"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Floor Panel 1"
o.display_description_item[o.display_page_one,1] = "Floor Panel 2"
o.display_description_item[o.display_page_one,2] = "Floor Panel 3"
o.display_description_item[o.display_page_one,3] = "Bridge Piece 1"
o.display_description_item[o.display_page_one,4] = "Bridge Piece 2"
o.display_description_item[o.display_page_one,5] = "Bridge Piece 3"
o.display_description_item[o.display_page_one,6] = "Bridge Piece 4"
o.display_description_item[o.display_page_one,7] = "Wall Panel 1"
o.display_description_item[o.display_page_one,8] = "Wall Panel 2"
o.display_description_item[o.display_page_one,9] = "Wall Panel 3"
o.display_description_item[o.display_page_one,10] = "Bridge Piece 5"
o.display_description_item[o.display_page_one,11] = "Wall Panel 4"
o.display_description_item[o.display_page_one,12] = "Bridge Piece 6"
o.display_description_item[o.display_page_one,13] = "Ceiling Panel 1"
o.display_description_item[o.display_page_one,14] = "Ceiling Panel 2"
o.display_description_item[o.display_page_one,15] = "Ceiling Panel 3"
o.display_description_item[o.display_page_one,16] = "Inside Panel 1"
o.display_description_item[o.display_page_one,17] = "Inside Panel 2"
o.display_description_item[o.display_page_one,18] = "Inside Panel 3"
o.display_description_item[o.display_page_one,19] = "Inside Panel 4"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Wall Panel 4"
o.display_description_item[o.display_page_two,1] = "Wall Panel 5"
o.display_description_item[o.display_page_two,2] = "Wall Panel 6"
o.display_description_item[o.display_page_two,3] = "Large Fan"
o.display_description_item[o.display_page_two,4] = "Wall Panel 7"
o.display_description_item[o.display_page_two,5] = "Wall Panel 8"
o.display_description_item[o.display_page_two,6] = "Wall Panel 7"
o.display_description_item[o.display_page_two,7] = "Support Beam 1"
o.display_description_item[o.display_page_two,8] = "Support Beam 2"
o.display_description_item[o.display_page_two,9] = "Support Beam 3"
o.display_description_item[o.display_page_two,10] = ""
o.display_description_item[o.display_page_two,11] = ""
o.display_description_item[o.display_page_two,12] = ""
o.display_description_item[o.display_page_two,13] = ""
o.display_description_item[o.display_page_two,14] = ""
o.display_description_item[o.display_page_two,15] = ""
o.display_description_item[o.display_page_two,16] = ""
o.display_description_item[o.display_page_two,17] = ""
o.display_description_item[o.display_page_two,18] = ""
o.display_description_item[o.display_page_two,19] = ""

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Floor Panel Slope 1"
o.display_description_item[o.display_page_three,1] = "Floor Panel Slope 2"
o.display_description_item[o.display_page_three,2] = "Bridge Slope 1"
o.display_description_item[o.display_page_three,3] = "Bridge Slope 2"
o.display_description_item[o.display_page_three,4] = "Floating Platform 1"
o.display_description_item[o.display_page_three,5] = "Floating Orb"
o.display_description_item[o.display_page_three,6] = "Floating Cracked Orb"
o.display_description_item[o.display_page_three,7] = "Loop Panel 1"
o.display_description_item[o.display_page_three,8] = "Loop Panel 2"
o.display_description_item[o.display_page_three,9] = "Exposed Loop 1"
o.display_description_item[o.display_page_three,10] = "Exposed Loop 2"
o.display_description_item[o.display_page_three,11] = ""
o.display_description_item[o.display_page_three,12] = ""
o.display_description_item[o.display_page_three,13] = "Loop Panel 3"
o.display_description_item[o.display_page_three,14] = "Loop Panel 4"
o.display_description_item[o.display_page_three,15] = "Exposed Loop 3"
o.display_description_item[o.display_page_three,16] = "Exposed Loop 4"
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Laboratory Door"
o.display_description_item[o.display_page_four,1] = "Breaker Box (Closed)"
o.display_description_item[o.display_page_four,2] = "Breaker Box (Open)"
o.display_description_item[o.display_page_four,3] = "Box of Scraps 1"
o.display_description_item[o.display_page_four,4] = "Personal Protection Equipment Sign"
o.display_description_item[o.display_page_four,5] = "Box of Scraps 2"
o.display_description_item[o.display_page_four,6] = "Workstation"
o.display_description_item[o.display_page_four,7] = "Base Station"
o.display_description_item[o.display_page_four,8] = "WiFi Station"
o.display_description_item[o.display_page_four,9] = "Disabled Drone"
o.display_description_item[o.display_page_four,10] = "Railing"
o.display_description_item[o.display_page_four,11] = ""
o.display_description_item[o.display_page_four,12] = ""
o.display_description_item[o.display_page_four,13] = ""
o.display_description_item[o.display_page_four,14] = ""
o.display_description_item[o.display_page_four,15] = ""
o.display_description_item[o.display_page_four,16] = ""
o.display_description_item[o.display_page_four,17] = ""
o.display_description_item[o.display_page_four,18] = ""
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = ""
o.display_description_item[o.display_page_five,1] = ""
o.display_description_item[o.display_page_five,2] = ""
o.display_description_item[o.display_page_five,3] = ""
o.display_description_item[o.display_page_five,4] = ""
o.display_description_item[o.display_page_five,5] = ""
o.display_description_item[o.display_page_five,6] = ""
o.display_description_item[o.display_page_five,7] = ""
o.display_description_item[o.display_page_five,8] = ""
o.display_description_item[o.display_page_five,9] = ""
o.display_description_item[o.display_page_five,10] = ""
o.display_description_item[o.display_page_five,11] = ""
o.display_description_item[o.display_page_five,12] = ""
o.display_description_item[o.display_page_five,13] = ""
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = ""
o.display_description_item[o.display_page_six,1] = ""
o.display_description_item[o.display_page_six,2] = ""
o.display_description_item[o.display_page_six,3] = ""
o.display_description_item[o.display_page_six,4] = ""
o.display_description_item[o.display_page_six,5] = ""
o.display_description_item[o.display_page_six,6] = ""
o.display_description_item[o.display_page_six,7] = ""
o.display_description_item[o.display_page_six,8] = ""
o.display_description_item[o.display_page_six,9] = ""
o.display_description_item[o.display_page_six,10] = ""
o.display_description_item[o.display_page_six,11] = ""
o.display_description_item[o.display_page_six,12] = ""
o.display_description_item[o.display_page_six,13] = ""
o.display_description_item[o.display_page_six,14] = ""
o.display_description_item[o.display_page_six,15] = ""
o.display_description_item[o.display_page_six,16] = ""
o.display_description_item[o.display_page_six,17] = ""
o.display_description_item[o.display_page_six,18] = ""
o.display_description_item[o.display_page_six,19] = ""

