///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Tierra/Arcilla"
o.display_page_description[1] = "Pendientes 1"
o.display_page_description[2] = "Pendientes 2"
o.display_page_description[3] = "Decoración"
o.display_page_description[4] = "???"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Tierra 1"
o.display_description_item[o.display_page_one,1] = "Tierra 2"
o.display_description_item[o.display_page_one,2] = "Tierra 3"
o.display_description_item[o.display_page_one,3] = "Tierra 4"
o.display_description_item[o.display_page_one,4] = "Tierra 5"
o.display_description_item[o.display_page_one,5] = "Tierra 6"
o.display_description_item[o.display_page_one,6] = "Tierra 7"
o.display_description_item[o.display_page_one,7] = "Tierra 8"
o.display_description_item[o.display_page_one,8] = "Tierra 9"
o.display_description_item[o.display_page_one,9] = "Puente Largo"
o.display_description_item[o.display_page_one,10] = "Puente Corto"
o.display_description_item[o.display_page_one,11] = ""
o.display_description_item[o.display_page_one,12] = ""
o.display_description_item[o.display_page_one,13] = ""
o.display_description_item[o.display_page_one,14] = ""
o.display_description_item[o.display_page_one,15] = ""
o.display_description_item[o.display_page_one,16] = ""
o.display_description_item[o.display_page_one,17] = ""
o.display_description_item[o.display_page_one,18] = ""
o.display_description_item[o.display_page_one,19] = ""

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Rampa de Lodo - Izquierda"
o.display_description_item[o.display_page_two,1] = "Rampa de Lodo - Derecha"
o.display_description_item[o.display_page_two,2] = "Rampa de Roca - Izquierda"
o.display_description_item[o.display_page_two,3] = "Rampa de Roca - Derecha"
o.display_description_item[o.display_page_two,4] = "Pendiente de Roca 1"
o.display_description_item[o.display_page_two,5] = "Pendiente de Roca 2"
o.display_description_item[o.display_page_two,6] = ""
o.display_description_item[o.display_page_two,7] = "Bucle Delgado 1"
o.display_description_item[o.display_page_two,8] = "Bucle Delgado 2"
o.display_description_item[o.display_page_two,9] = "Bucle de Roca 1"
o.display_description_item[o.display_page_two,10] = "Bucle de Roca 2"
o.display_description_item[o.display_page_two,11] = "Bucle Circular de Roca 1"
o.display_description_item[o.display_page_two,12] = "Bucle Circular de Roca 2"
o.display_description_item[o.display_page_two,13] = "Bucle Delgado 3"
o.display_description_item[o.display_page_two,14] = "Bucle Delgado 4"
o.display_description_item[o.display_page_two,15] = "Bucle de Roca 3"
o.display_description_item[o.display_page_two,16] = "Bucle de Roca 4"
o.display_description_item[o.display_page_two,17] = "Bucle Circular de Roca 3"
o.display_description_item[o.display_page_two,18] = "Bucle Circular de Roca 3"
o.display_description_item[o.display_page_two,19] = ""

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Montículo de Arcilla 1"
o.display_description_item[o.display_page_three,1] = "Hierba 1"
o.display_description_item[o.display_page_three,2] = "Montículo de Arcilla 2"
o.display_description_item[o.display_page_three,3] = "Montículo de Arcilla 3"
o.display_description_item[o.display_page_three,4] = "Montículo de Arcilla 4"
o.display_description_item[o.display_page_three,5] = "Montículo de Arcilla 5"
o.display_description_item[o.display_page_three,6] = "Arco de Roca 1"
o.display_description_item[o.display_page_three,7] = "Arco de Roca 2"
o.display_description_item[o.display_page_three,8] = "Arco de Roca 3"
o.display_description_item[o.display_page_three,9] = ""
o.display_description_item[o.display_page_three,10] = ""
o.display_description_item[o.display_page_three,11] = ""
o.display_description_item[o.display_page_three,12] = ""
o.display_description_item[o.display_page_three,13] = ""
o.display_description_item[o.display_page_three,14] = ""
o.display_description_item[o.display_page_three,15] = ""
o.display_description_item[o.display_page_three,16] = ""
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""
