//For calling in Story Mode object only, call BEFORE NPC spawn scripts
//Language Array; 0 = English; 1 = Portuguese; 2 = Polish; 3 = Spanish; 4 = German; 5 = Russian
var lang_num = 2;
//Mall NPCs 1
lang_npc[lang_num,0]  = "Myślę że lody są smaczniejsze niż kawałki szkła!"          //Jett
lang_npc[lang_num,1]  = "Chrup #Chrup #Chrup!"                                    //Jett
lang_npc[lang_num,2]  = "KULKI KULKI #KULKI KULKI #KULKI KULKI!!!"                  //Marshmallow
lang_npc[lang_num,3]  = "Okej! Możemy zrobić przerwę na zakupy."                 //Lilac
lang_npc[lang_num,4]  = "Nie zapomnij o naszej wycieczce w góry!"             //Lilac
lang_npc[lang_num,5]  = "Witajcie w Timmy Tuna!"                                 //Beibo
lang_npc[lang_num,6]  = "Stolik dla trzech?"                        //Beibo
lang_npc[lang_num,7]  = "...kiedy szefostwo zainstaluje ten przycisk alarmowy?!"         //Beibo
lang_npc[lang_num,8]  = "Te robociki są dość podejrzane... Kto je robi?"       //Jamie
lang_npc[lang_num,9]  = "Na twoim miejscu miał bym na nie oko."            //Jamie
lang_npc[lang_num,10]  = "Cieszę się że moja siostra dostała pracę jako sekretarka!"        //Libbie
lang_npc[lang_num,11]  = "Świetnie się tam bawi, a ja wreszcie mam czas dla siebie!"      //Libbie
lang_npc[lang_num,12]  = "Czy chciałabyś zdjęcie?"                   //Uny
lang_npc[lang_num,13]  = "Nie porusz się! #*klik*"                                     //Uny
lang_npc[lang_num,14]  = "Witaj w Galerii #Shang Mu! Pierwszy raz tutaj?"         //Mirdin
lang_npc[lang_num,15]  = "Witaj w Galerii #Shang Mu!"                           //Mirdin
lang_npc[lang_num,16]  = "(Nie myśl że nie wiem kim jesteś, głąbie!)"         //Mirdin
lang_npc[lang_num,17]  = "Szukałam wszędzie!"                        //Chiasa
lang_npc[lang_num,18]  = "...Nikt nie ma nuggetsów z kurczaka!"                      //Chiasa
lang_npc[lang_num,19]  = "BUFET BEZ LIMITU?!?!?"                          //Marshmallow
lang_npc[lang_num,20]  = "CHIASA PROSZĘ CHODŹMY TAAAAAAAAAM!!!"                         //Marshmallow
lang_npc[lang_num,21]  = "Mmm! Mmm! Mmm! #Te roladki jajeczne są wspaniałe!"            //Tiwi
lang_npc[lang_num,22]  = "Harige mógłby zrobić pyszną kanapkę nawet z trawy!"              //Tiwi
lang_npc[lang_num,23]  = "Hej! #Co byś dzisiaj chciała?"                   //Harige
lang_npc[lang_num,24]  = "Specjałem dnia jest Zao Bowl!"                             //Harige
lang_npc[lang_num,25]  = "Jedzenie pachnie tu wspaniale, chyba tu kupie lunch!"       //Stella
lang_npc[lang_num,26]  = "Hihi! Ten piesek wygląda prawie jak ja!"           //Milla
lang_npc[lang_num,27]  = "Chwila... Czemu ja nie mam takiego nosa?"             //Milla
lang_npc[lang_num,28]  = "Nie przejmuj się mną... #Oglądam motocykle."                 //Ryusei
lang_npc[lang_num,29]  = "Nie żeby Shy pozwoliłaby mi kiedykolwiek jeden kupić..."           //Ryusei
lang_npc[lang_num,30]  = "Absolutnie, nie ma na to żadnych szans!"                     //Shy
lang_npc[lang_num,31]  = "Och! Też chciałabym próbkę sushi!"                   //Libbie Dark
lang_npc[lang_num,32]  = "Sprindog?! Do czego on służy?"                        //Astum
lang_npc[lang_num,33]  = "Hej! Dałyście dzisiaj niezły pokaz."             //Maria
lang_npc[lang_num,34]  = "Jesteście może zainteresowane ekskluzywnym wywiadzikiem?"                  //Maria
lang_npc[lang_num,35]  = "Moi ochroniarze mają cię na oku!"                    //Maria
lang_npc[lang_num,36]  = "Ha! Zawsze wiedziałam jaką porażką jest Zao..."             //Carol
lang_npc[lang_num,37]  = "Ale to najmocniej to potwierdza!"                                //Carol
lang_npc[lang_num,38]  = "Dzień dobry dzieciaki!"                                     //Savvy
lang_npc[lang_num,39]  = "Miłego poranka, #Lilac! Jestem z ciebie dumna."              //Savvy
lang_npc[lang_num,40]  = "Twoja ciężka praca ratuje życia, młoda panno!"            //Savvy
lang_npc[lang_num,41]  = "Cześć, Carol! Dokończyłaś swoje dokumenty?"           //Savvy
lang_npc[lang_num,42]  = "Daj znać jak potrzebujesz pomocy!!!"                         //Savvy
lang_npc[lang_num,43]  = "Och, Milla! Miło cię widzieć, hihi!"                 //Savvy
lang_npc[lang_num,44]  = "Kto jest dobrym małym pirotechnikiem! Ty!"             //Savvy
lang_npc[lang_num,45]  = "Nie byłbyś pierwszym z twojej grupki którego pokonałam."      //Savvy

//Mall NPCs 1
lang_npc[lang_num,46]  = "Pani Cosmos, co robisz tutaj o tej godzinie?"            //Jamie
lang_npc[lang_num,47]  = "Nie mów że nie spałaś całą noc?"                             //Jamie
lang_npc[lang_num,48]  = "Och! Będziemy niedługo oprowadzać inwestorów."           //Vela
lang_npc[lang_num,49]  = "Są to same problemy, ale na prawdę potrzeba nam tych środków!"       //Vela
lang_npc[lang_num,50]  = "Mogę cię zniknąć w dowolnym momencie!"           //Mirdin
lang_npc[lang_num,51]  = "Te nuggetsy smakują dziwnie!"                       //Chiasa
lang_npc[lang_num,52]  = "Zastanawiasz się co robię w takim dziecinnym miejscu?"          //Spade
lang_npc[lang_num,53]  = "Chciałabyś pewnie wiedzieć kogo szpieguje?!"          //Spade
lang_npc[lang_num,54]  = "Nadal nie chcesz moich akcji w rzepie?"                 //Boss
lang_npc[lang_num,55]  = "Opieka nad tymi gremlinami wymaga tony cierpliwości..."                      //Iris
lang_npc[lang_num,56]  = "Jakimś cudem wysadziły toaletę w powietrze..."                    //Iris
lang_npc[lang_num,57]  = "Jest tak dobry ze słowami!"                           //Bird Guard (Female)
lang_npc[lang_num,58]  = "Łeh"                                                      //Bird Guard (Male)
lang_npc[lang_num,59]  = "Ha!"                                                      //Neera
lang_npc[lang_num,60]  = "Nie wydaj wszystkiego naraz, Lilac!"                //Neera
lang_npc[lang_num,61]  = "Wiem że tego nie zrobisz, ale Carol..."         //Neera
lang_npc[lang_num,62]  = "Nie wydaj wszystkiego w jednym miejscu, kocie!"              //Neera
lang_npc[lang_num,63]  = "Widziałam jak się patrzysz na ten złoty motor..."         //Neera
lang_npc[lang_num,64]  = "Wydaj swoje pieniądze mądrze, Milla!"                         //Neera
lang_npc[lang_num,65]  = "Widziałam jak się patrzysz na ten złoty motor..."         //Neera
lang_npc[lang_num,66]  = "Masz szczęście że mam ważniejsze rzeczy na głowie, Spade"            //Neera
lang_npc[lang_num,67]  = "Gong jest zajęty zabawą w kierowanie ruchu"          //Neera
lang_npc[lang_num,68]  = "Mmm! Mhm!"                                                //Tiwi
lang_npc[lang_num,69]  = "Dzisiejszy specjał: #Pizza Zagłady!"                //Harige
lang_npc[lang_num,70]  = "Och! Poproszę próbkę! Hihi!"                          //Stella
lang_npc[lang_num,71]  = "Och, dzień dobry uczennico!"                              //Libbie Dark
lang_npc[lang_num,72]  = "Zajmę się twoimi papierami później, obiecuję!"              //Libbie Dark
lang_npc[lang_num,73]  = "Słyszałam pogłoski o obecności smoka w górach!"         //Maria
lang_npc[lang_num,74]  = "Mam przeczucie że wiecie o tym coś więcej!"            //Maria
lang_npc[lang_num,75]  = "Sorki! Nie ciebie szukam..."       //Maria
lang_npc[lang_num,76]  = "O je! To jest to!"                               //Carol
lang_npc[lang_num,77]  = "Och! Chciałabym taki motocykl jak ma Carol!"                    //Milla
lang_npc[lang_num,78]  = "...Ale najpierw powinniśmy oszczędzać na dom!"            //Milla
lang_npc[lang_num,79]  = lang_npc[lang_num,38]                                      //Savvy
lang_npc[lang_num,80]  = "Mam nadzieje że będziesz miała dobry weekend, Lilac!"                 //Savvy
lang_npc[lang_num,81]  = "Zasłużyłaś sobie na odpoczynek!"                      //Savvy
lang_npc[lang_num,82]  = "Miłego weekendu, Carol!"                            //Savvy
lang_npc[lang_num,83]  = "Nie zapomnij o pracy domowej!"                      //Savvy
lang_npc[lang_num,84]  = "Miłego weekendu, #Milla!"                     //Savvy
lang_npc[lang_num,85]  = "Daj mi znać jak będziesz odpalać więcej fajerwerków!"             //Savvy
lang_npc[lang_num,86]  = "Shaun cię obserwuje, chłopaczku!"                   //Savvy

//Mall NPCs 3
lang_npc[lang_num,87]  = "Ta pizza zagłady pachnie paskudnie! Kupuje ją!"      //Jett
lang_npc[lang_num,88]  = "Czy masz może bajgle, Panie Kotku?"                     //Marshmallow
lang_npc[lang_num,89]  = "Poproszę bajgla z bekonem i sosem ogórkowym!"              //Marshmallow
lang_npc[lang_num,90]  = "Nie zapomnijmy o naszej wycieczce nad morze!"                 //Lilac
lang_npc[lang_num,91]  = "O mój kamieniu! Tyle postępów, tak mało czasu!"        //Jamie
lang_npc[lang_num,92]  = "'Kurczak morza'?! Co za oszustwo!"                    //Chiasa
lang_npc[lang_num,93]  = "To NIE był #kurczak! Blech!"                             //Chiasa
lang_npc[lang_num,94]  = "Jak to nie robiłem nic cały dzień?"     //Spade
lang_npc[lang_num,95]  = "Nie zaprzeczam tym zarzutom!"                     //Spade
lang_npc[lang_num,96]  = "Nie mogę powstrzymać ich przed zjeżdżaniem po schodach..."           //Iris
lang_npc[lang_num,97]  = "Dobra robota dziewczęta! Magister będzie zadowolony."         //Neera
lang_npc[lang_num,98]  = "I do tego bez zniszczeń- Tym razem!"                     //Neera
lang_npc[lang_num,99]  = lang_npc[lang_num,66]            //Neera
lang_npc[lang_num,100] = lang_npc[lang_num,67]          //Neera
lang_npc[lang_num,101] = "A więc, być może wziąłem chorobowe w pracy..."           //Tiwi
lang_npc[lang_num,102] = "MOGŁEM zjeść dość dużo kanapek!"                   //Tiwi
lang_npc[lang_num,103] = "Dzisiejszy speciał: Umami Delight"                          //Harige
lang_npc[lang_num,104] = "W tej galerii jest wszystko oprócz komputerów..."       //Kubo
lang_npc[lang_num,105] = "Trudno, pozostaje mi czytanie katalogów."                     //Kubo
lang_npc[lang_num,106] = "Hej! Mamy nagrania pokazujące dużego latającego rekina."         //Maria
lang_npc[lang_num,107] = "Mam przeczucie że możesz wiedzieć o tym coś więcej!"            //Maria
lang_npc[lang_num,108] = "Tak fajnie mi tańczyć! Czas na super taniec!"              //Milla
lang_npc[lang_num,109] = "Dzień dobry dzieciaki!"                                     //Savvy
lang_npc[lang_num,110] = "Widziałam newsy! Niesamowita robota Lilac!"               //Savvy
lang_npc[lang_num,111] = "Ale odpocznij przed jutrem, okej?"                     //Savvy
lang_npc[lang_num,112] = "Carol, byłaś niesamowita w telewizji!"                //Savvy
lang_npc[lang_num,113] = "Tylko nie zapomnij o pracy domowej!"                 //Savvy
lang_npc[lang_num,114] = "Och, Milla! Masz tak duży potencjał."                 //Savvy
lang_npc[lang_num,115] = "Daj mi znać jak potrzebowałabyś stypendium!"                 //Savvy
