///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Plattforms"
o.display_page_description[1] = "Röhrensystem"
o.display_page_description[2] = "Landschaft"
o.display_page_description[3] = "Gras/Dreck"
o.display_page_description[4] = "Extras"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Ziegelplattform - Gerissen 1"
o.display_description_item[o.display_page_one,1] = "Ziegelplattform - Gerissen 2"
o.display_description_item[o.display_page_one,2] = "Ziegelplattform - Gerissen 3"
o.display_description_item[o.display_page_one,3] = "Ziegelwand - Gerissen 1"
o.display_description_item[o.display_page_one,4] = "Ziegelwand - Gerissen 2"
o.display_description_item[o.display_page_one,5] = "Ziegelwand - Gerissen 3"
o.display_description_item[o.display_page_one,6] = "Ziegelwand 1"
o.display_description_item[o.display_page_one,7] = "Ziegelwand 2"
o.display_description_item[o.display_page_one,8] = "Ziegelwand 3"
o.display_description_item[o.display_page_one,9] = "Ziegelwand 4"
o.display_description_item[o.display_page_one,10] = "Ziegelwand 5"
o.display_description_item[o.display_page_one,11] = "Kleiner Ziegel 1"
o.display_description_item[o.display_page_one,12] = "Kleiner Ziegel 2"
o.display_description_item[o.display_page_one,13] = "Kleine Röhre 1"
o.display_description_item[o.display_page_one,14] = "Große Röhre 1"
o.display_description_item[o.display_page_one,15] = "Große Röhre 2"
o.display_description_item[o.display_page_one,16] = "Große Röhre 3"
o.display_description_item[o.display_page_one,17] = "Röhrenverbindung 1"
o.display_description_item[o.display_page_one,18] = "Röhrenverbindung 2"
o.display_description_item[o.display_page_one,19] = "Röhrenverbindung 3"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Kanalwand 1"
o.display_description_item[o.display_page_two,1] = "Kanalwand 2"
o.display_description_item[o.display_page_two,2] = "Landschaft - Kanal 1"
o.display_description_item[o.display_page_two,3] = "Landschaft - Kanal 2"
o.display_description_item[o.display_page_two,4] = "Landschaft - Kanal 3"
o.display_description_item[o.display_page_two,5] = "Landschaft - Kanal 4"
o.display_description_item[o.display_page_two,6] = "Landschaft - Kanal 5"
o.display_description_item[o.display_page_two,7] = "Gedr. Röhre 1"
o.display_description_item[o.display_page_two,8] = "Gedr. Röhre 2"
o.display_description_item[o.display_page_two,9] = "Gedr. Röhre 3"
o.display_description_item[o.display_page_two,10] = "Gedr. Röhre 4"
o.display_description_item[o.display_page_two,11] = "Konstruktionsstützbalken 1"
o.display_description_item[o.display_page_two,12] = "Konstruktionsstützbalken 2"
o.display_description_item[o.display_page_two,13] = "Stacheln 1"
o.display_description_item[o.display_page_two,14] = "Stacheln 2"
o.display_description_item[o.display_page_two,15] = "Stacheln 3"
o.display_description_item[o.display_page_two,16] = "Stacheln 4"
o.display_description_item[o.display_page_two,17] = "Leiter 1"
o.display_description_item[o.display_page_two,18] = "Leiter 2"
o.display_description_item[o.display_page_two,19] = "Hangbar 1"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Glasfenster - Grün - Groß"
o.display_description_item[o.display_page_three,1] = "Glasfenster - Grün - Klein"
o.display_description_item[o.display_page_three,2] = "Glasfenster - Blau - Klein"
o.display_description_item[o.display_page_three,3] = "Stützbalken 1"
o.display_description_item[o.display_page_three,4] = "Stützbalken 2"
o.display_description_item[o.display_page_three,5] = "Stützbalken 3"
o.display_description_item[o.display_page_three,6] = "Gedr. Stützbalken - Komplett"
o.display_description_item[o.display_page_three,7] = "Gedr. Stützbalken - Unten"
o.display_description_item[o.display_page_three,8] = "Gedr. Stützbalken - Mitte"
o.display_description_item[o.display_page_three,9] = "Gedr. Stützbalken - Oben"
o.display_description_item[o.display_page_three,10] = "Gedr. Stützbalken - Unten"
o.display_description_item[o.display_page_three,11] = "Gedr. Stützbalken - Mitte"
o.display_description_item[o.display_page_three,12] = "Gedr. Stützbalken - Oben"
o.display_description_item[o.display_page_three,13] = "Eckteil - 1"
o.display_description_item[o.display_page_three,14] = "Eckteil - 2"
o.display_description_item[o.display_page_three,15] = "Eckteil - 3"
o.display_description_item[o.display_page_three,16] = "Eckteil - 4"
o.display_description_item[o.display_page_three,17] = "Eckteil - 5"
o.display_description_item[o.display_page_three,18] = "Eckteil - 6"
o.display_description_item[o.display_page_three,19] = "Eckteil - Mitte"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Gras - Kante Links"
o.display_description_item[o.display_page_four,1] = "Gras - Oben"
o.display_description_item[o.display_page_four,2] = "Gras - Kante Rechts"
o.display_description_item[o.display_page_four,3] = "Grasneigung 1"
o.display_description_item[o.display_page_four,4] = "Grasneigung 2"
o.display_description_item[o.display_page_four,5] = "Grasneigung 3"
o.display_description_item[o.display_page_four,6] = "Landschaft - Gras"
o.display_description_item[o.display_page_four,7] = "Dreck - Wand Links"
o.display_description_item[o.display_page_four,8] = "Dreck - Klein"
o.display_description_item[o.display_page_four,9] = "Dreck - Wand Rechts"
o.display_description_item[o.display_page_four,10] = "Gras - Flach - Groß"
o.display_description_item[o.display_page_four,11] = "Gras - Gemischt"
o.display_description_item[o.display_page_four,12] = "Gras - Flach - Klein"
o.display_description_item[o.display_page_four,13] = "Gras - Kante - Links"
o.display_description_item[o.display_page_four,14] = "Gras - Unten"
o.display_description_item[o.display_page_four,15] = "Gras - Kante Rechts"
o.display_description_item[o.display_page_four,16] = "Dreck Groß"
o.display_description_item[o.display_page_four,17] = "Dreck Neigung 1"
o.display_description_item[o.display_page_four,18] = "Dreck Neigung 2"
o.display_description_item[o.display_page_four,19] = "Dreck Neigung 3"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Kreisschleife 1"
o.display_description_item[o.display_page_five,1] = "Kreisschleife 2"
o.display_description_item[o.display_page_five,2] = "Röhrenschleife 1"
o.display_description_item[o.display_page_five,3] = "Röhrenschleife 2"
o.display_description_item[o.display_page_five,4] = "Flacher Dreck Tile - Extra 1"
o.display_description_item[o.display_page_five,5] = "Flacher Dreck Tile - Extra 2"
o.display_description_item[o.display_page_five,6] = "Flacher Dreck Tile - Extra 3"
o.display_description_item[o.display_page_five,7] = "Kreisschleife 3"
o.display_description_item[o.display_page_five,8] = "Kreisschleife 4"
o.display_description_item[o.display_page_five,9] = "Röhrenschleife 3"
o.display_description_item[o.display_page_five,10] = "Röhrenschleife 4"
o.display_description_item[o.display_page_five,11] = "Flacher Dreck Tile - Extra 4"
o.display_description_item[o.display_page_five,12] = "Flacher Dreck Tile - Extra 5"
o.display_description_item[o.display_page_five,13] = "Saubere Wand 1"
o.display_description_item[o.display_page_five,14] = "Saubere Wand 2"
o.display_description_item[o.display_page_five,15] = "Saubere Boden 1"
o.display_description_item[o.display_page_five,16] = "Saubere Wand 3"
o.display_description_item[o.display_page_five,17] = "Saubere Boden 2"
o.display_description_item[o.display_page_five,18] = "Saubere Boden 3"
o.display_description_item[o.display_page_five,19] = "Saubere Wand 4"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Müllcontainer"
o.display_description_item[o.display_page_six,1] = "Ninjakreuzung Schild"
o.display_description_item[o.display_page_six,2] = "East Road Street Schild"
o.display_description_item[o.display_page_six,3] = "North Circle Street Schild"
o.display_description_item[o.display_page_six,4] = "South Drive Street Schild"
o.display_description_item[o.display_page_six,5] = "West Lane Street Schild"
o.display_description_item[o.display_page_six,6] = "Blank Street Schild"
o.display_description_item[o.display_page_six,7] = "Arrow Schild"
o.display_description_item[o.display_page_six,8] = "Mülleimer"
o.display_description_item[o.display_page_six,9] = "Traffic Lights"
o.display_description_item[o.display_page_six,10] = "Lampenposten"
o.display_description_item[o.display_page_six,11] = "Lampenstange 1"
o.display_description_item[o.display_page_six,12] = "Lampenstange 2"
o.display_description_item[o.display_page_six,13] = "Lampenstange 3"
o.display_description_item[o.display_page_six,14] = "Busch"
o.display_description_item[o.display_page_six,15] = "Spezielle Aubergine"
o.display_description_item[o.display_page_six,16] = "Wäscheleine"
o.display_description_item[o.display_page_six,17] = "Fußgängerkreuzung Schild"
o.display_description_item[o.display_page_six,18] = "Fußgängerampel"
o.display_description_item[o.display_page_six,19] = "Papierkorb"
