///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Dirt/Clay"
o.display_page_description[1] = "Slopes 1"
o.display_page_description[2] = "Slopes 2"
o.display_page_description[3] = "Scenery"
o.display_page_description[4] = "???"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Dirt 1"
o.display_description_item[o.display_page_one,1] = "Dirt 2"
o.display_description_item[o.display_page_one,2] = "Dirt 3"
o.display_description_item[o.display_page_one,3] = "Dirt 4"
o.display_description_item[o.display_page_one,4] = "Dirt 5"
o.display_description_item[o.display_page_one,5] = "Dirt 6"
o.display_description_item[o.display_page_one,6] = "Dirt 7"
o.display_description_item[o.display_page_one,7] = "Dirt 8"
o.display_description_item[o.display_page_one,8] = "Dirt 9"
o.display_description_item[o.display_page_one,9] = "Bridge Long"
o.display_description_item[o.display_page_one,10] = "Bridge Short"
o.display_description_item[o.display_page_one,11] = ""
o.display_description_item[o.display_page_one,12] = ""
o.display_description_item[o.display_page_one,13] = ""
o.display_description_item[o.display_page_one,14] = ""
o.display_description_item[o.display_page_one,15] = ""
o.display_description_item[o.display_page_one,16] = ""
o.display_description_item[o.display_page_one,17] = ""
o.display_description_item[o.display_page_one,18] = ""
o.display_description_item[o.display_page_one,19] = ""

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Mud Ramp Left"
o.display_description_item[o.display_page_two,1] = "Mud Ramp Right"
o.display_description_item[o.display_page_two,2] = "Rock Ramp Left"
o.display_description_item[o.display_page_two,3] = "Rock Ramp Right"
o.display_description_item[o.display_page_two,4] = "Rock Slope 1"
o.display_description_item[o.display_page_two,5] = "Rock Slope 2"
o.display_description_item[o.display_page_two,6] = ""
o.display_description_item[o.display_page_two,7] = "Skinny Loop 1"
o.display_description_item[o.display_page_two,8] = "Skinny Loop 2"
o.display_description_item[o.display_page_two,9] = "Rock Loop 1"
o.display_description_item[o.display_page_two,10] = "Rock Loop 2"
o.display_description_item[o.display_page_two,11] = "Rock Circle Loop 1"
o.display_description_item[o.display_page_two,12] = "Rock Circle Loop 2"
o.display_description_item[o.display_page_two,13] = "Skinny Loop 3"
o.display_description_item[o.display_page_two,14] = "Skinny Loop 4"
o.display_description_item[o.display_page_two,15] = "Rock Loop 3"
o.display_description_item[o.display_page_two,16] = "Rock Loop 4"
o.display_description_item[o.display_page_two,17] = "Rock Circle Loop 3"
o.display_description_item[o.display_page_two,18] = "Rock Circle Loop 3"
o.display_description_item[o.display_page_two,19] = ""

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Clay Mound 1"
o.display_description_item[o.display_page_three,1] = "Grass 1"
o.display_description_item[o.display_page_three,2] = "Clay Mound 2"
o.display_description_item[o.display_page_three,3] = "Clay Mound 3"
o.display_description_item[o.display_page_three,4] = "Clay Mound 4"
o.display_description_item[o.display_page_three,5] = "Clay Mound 5"
o.display_description_item[o.display_page_three,6] = "Rock Arch 1"
o.display_description_item[o.display_page_three,7] = "Rock Arch 2"
o.display_description_item[o.display_page_three,8] = "Rock Arch 3"
o.display_description_item[o.display_page_three,9] = ""
o.display_description_item[o.display_page_three,10] = ""
o.display_description_item[o.display_page_three,11] = ""
o.display_description_item[o.display_page_three,12] = ""
o.display_description_item[o.display_page_three,13] = ""
o.display_description_item[o.display_page_three,14] = ""
o.display_description_item[o.display_page_three,15] = ""
o.display_description_item[o.display_page_three,16] = ""
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""
