//For calling in Story Mode object only, call BEFORE NPC spawn scripts
//Language Array; 0 = English; 1 = Portuguese; 2 = Polish; 3 = Spanish; 4 = German; 5 = Russian
var lang_num = 4;
//Mall NPCs 1
lang_npc[lang_num,0]  = "I think ice cream #is better with #broken glass!"          //Jett
lang_npc[lang_num,1]  = "Crunch crunch #crunch!"                                    //Jett
lang_npc[lang_num,2]  = "BALLS BALLS #BALLS BALLS #BALLS BALLS!!!"                  //Marshmallow
lang_npc[lang_num,3]  = "Okay! We can #shop for #supplies for now."                 //Lilac
lang_npc[lang_num,4]  = "Let's not forget #our trip to the #mountains!"             //Lilac
lang_npc[lang_num,5]  = "Welcome to Timmy #Tuna's!"                                 //Beibo
lang_npc[lang_num,6]  = "Would you like a #table for three?"                        //Beibo
lang_npc[lang_num,7]  = "...When will this #dump install a #panic button?!"         //Beibo
lang_npc[lang_num,8]  = "Real sus on the #robbits here... #Who's makin' 'em?"       //Jamie
lang_npc[lang_num,9]  = "Ah'd still keep #an ey' on her if #ah were ye."            //Jamie
lang_npc[lang_num,10]  = "I'm so excited my #sister got the #assistant job!"        //Libbie
lang_npc[lang_num,11]  = "She loves it #already, and I'll #have my 'me' time!"      //Libbie
lang_npc[lang_num,12]  = "Would you like me #to take a #picture?"                   //Uny
lang_npc[lang_num,13]  = "Hold still! #*click*"                                     //Uny
lang_npc[lang_num,14]  = "Welcome to the #Shang Mu Mall! #You must be new."         //Mirdin
lang_npc[lang_num,15]  = "Welcome to the #Shang Mu Mall!"                           //Mirdin
lang_npc[lang_num,16]  = "(Don't think I #don't know who #you are, idiot!)"         //Mirdin
lang_npc[lang_num,17]  = "I looked and #looked #everywhere!"                        //Chiasa
lang_npc[lang_num,18]  = "...Nobody has any #chimkin nuggies!"                      //Chiasa
lang_npc[lang_num,19]  = "AN ALL YOU CAN #EAT BUFFET?!?!?"                          //Marshmallow
lang_npc[lang_num,20]  = "CHIASA PLEASE #LET'S GOOOOOOO!!!"                         //Marshmallow
lang_npc[lang_num,21]  = "Mmm! Mmm! Mmm! #These eggrolls #hit the spot!"            //Tiwi
lang_npc[lang_num,22]  = "Harige could #make a grass #sandwich tasty!"              //Tiwi
lang_npc[lang_num,23]  = "Hello, there! #What will it be #today?"                   //Harige
lang_npc[lang_num,24]  = "We have a Zao #Bowl Special!"                             //Harige
lang_npc[lang_num,25]  = "I'm getting lunch #here! The food #smells so good!"       //Stella
lang_npc[lang_num,26]  = "Ehehe! This #doggy has a face #just like mine!"           //Milla
lang_npc[lang_num,27]  = "Wait... Why don't #I have a nose #like that?"             //Milla
lang_npc[lang_num,28]  = "Don't mind me... #Looking at the #bikes."                 //Ryusei
lang_npc[lang_num,29]  = "Not that Shy #would ever let me #get on one..."           //Ryusei
lang_npc[lang_num,30]  = "You're darn #right I won't, #buster!"                     //Shy
lang_npc[lang_num,31]  = "Ooh! I'd like a #sushi sample #myself!"                   //Libbie Dark
lang_npc[lang_num,32]  = "Sprindog?! What #does it even do?"                        //Astum
lang_npc[lang_num,33]  = "Hey! You girls #were great out #there today."             //Maria
lang_npc[lang_num,34]  = "Interested in an #exclusive #interview?"                  //Maria
lang_npc[lang_num,35]  = "My security #detail is #watching you!"                    //Maria
lang_npc[lang_num,36]  = "Ha! I always knew #Zao was for the #birds..."             //Carol
lang_npc[lang_num,37]  = "But this takes #the cake!"                                //Carol
lang_npc[lang_num,38]  = "Good morning, #kids!"                                     //Savvy
lang_npc[lang_num,39]  = "Good morning, #Lilac! I'm so #proud of you."              //Savvy
lang_npc[lang_num,40]  = "Your hard work #is saving lives, #young lady!"            //Savvy
lang_npc[lang_num,41]  = "Mornin', Carol! #Finished your #paperwork yet?"           //Savvy
lang_npc[lang_num,42]  = "Let me know if #you need help!!!"                         //Savvy
lang_npc[lang_num,43]  = "Oh, Milla! I'm #happy to see #you, hehe!"                 //Savvy
lang_npc[lang_num,44]  = "You are fire #tech material, #girl! Yes yes!"             //Savvy
lang_npc[lang_num,45]  = "You wouldn't be #the first scarf #I took down, son."      //Savvy

//Mall NPCs 1
lang_npc[lang_num,46]  = "Ms. Cosmos, #what're ya doin' #up this early?"            //Jamie
lang_npc[lang_num,47]  = "Don't ya stay up #all night?"                             //Jamie
lang_npc[lang_num,48]  = "Oh! There's an #investor tour #coming up soon."           //Vela
lang_npc[lang_num,49]  = "They're a lot of #trouble, but we #need the funds!"       //Vela
lang_npc[lang_num,50]  = "I can make you #disappear any #time, you know!"           //Mirdin
lang_npc[lang_num,51]  = "These chimkin #nuggies are #weird!"                       //Chiasa
lang_npc[lang_num,52]  = "What am I doing #in this kiddy #joint, you ask?"          //Spade
lang_npc[lang_num,53]  = "Wouldn't you like #to know who I'm #spying on?!"          //Spade
lang_npc[lang_num,54]  = "Still don't want #my turnip #stocks, eh?"                 //Boss
lang_npc[lang_num,55]  = "Babysitting gremlins#sure is fun..."                      //Iris
lang_npc[lang_num,56]  = "Those two already#blew up a toilet..."                    //Iris
lang_npc[lang_num,57]  = "He has such a #way with words!"                           //Bird Guard (Female)
lang_npc[lang_num,58]  = "Weh"                                                      //Bird Guard (Male)
lang_npc[lang_num,59]  = "Ha!"                                                      //Neera
lang_npc[lang_num,60]  = "Don't spend it #all in one place, #Lilac!"                //Neera
lang_npc[lang_num,61]  = "I trust you #won't! Carol, on #the other hand..."         //Neera
lang_npc[lang_num,62]  = "Don't spend it #all in one place, #Wildcat!"              //Neera
lang_npc[lang_num,63]  = "I saw you eying #that golden bike #over there..."         //Neera
lang_npc[lang_num,64]  = "Be wise with your #money, Milla!"                         //Neera
lang_npc[lang_num,65]  = "I saw you eying #that golden bike #over there..."         //Neera
lang_npc[lang_num,66]  = "You're lucky I #have other #priorities, Spade"            //Neera
lang_npc[lang_num,67]  = "Gong is busy #playing traffic #warden right now"          //Neera
lang_npc[lang_num,68]  = "Mmm! Mhm!"                                                //Tiwi
lang_npc[lang_num,69]  = "Today's special: #The Widow Maker #pizza!"                //Harige
lang_npc[lang_num,70]  = "Oh! I'll take a #sampler! Hehe!"                          //Stella
lang_npc[lang_num,71]  = "Oh, good morning, #student!"                              //Libbie Dark
lang_npc[lang_num,72]  = "I'll finish your #papers later, I #promise!"              //Libbie Dark
lang_npc[lang_num,73]  = "I heard rumors #about a dragon #on the mountain!"         //Maria
lang_npc[lang_num,74]  = "I have a feeling #you three would #know more!"            //Maria
lang_npc[lang_num,75]  = "Sorry! You're #not the persons #I'm looking for..."       //Maria
lang_npc[lang_num,76]  = "Aw yeah! This is #awesome!"                               //Carol
lang_npc[lang_num,77]  = "Oh! I want a bike #just like Carol's!"                    //Milla
lang_npc[lang_num,78]  = "...But I need to #save up for a #house first!"            //Milla
lang_npc[lang_num,79]  = "Good morning, #kids!"                                     //Savvy
lang_npc[lang_num,80]  = "I hope you have #a good weekend, #Lilac!"                 //Savvy
lang_npc[lang_num,81]  = "You better #believe you #earned it!"                      //Savvy
lang_npc[lang_num,82]  = "Have a great #weekend, Carol!"                            //Savvy
lang_npc[lang_num,83]  = "Don't forget #about your #homework!"                      //Savvy
lang_npc[lang_num,84]  = "I wish you a #great weekend, #Milla!"                     //Savvy
lang_npc[lang_num,85]  = "Let me know if #you set off more #fireworks!"             //Savvy
lang_npc[lang_num,86]  = "Shaun's watching #you right now, #son!"                   //Savvy

//Mall NPCs 3
lang_npc[lang_num,87]  = "The widow maker #pizza smells so #gross! I want it!"      //Jett
lang_npc[lang_num,88]  = "But do you have #bagels, Mr. #Kitty?"                     //Marshmallow
lang_npc[lang_num,89]  = "I want a bacon #bagel with #cucumber sauce!"              //Marshmallow
lang_npc[lang_num,90]  = "Let's not forget #about our beach #trip!"                 //Lilac
lang_npc[lang_num,91]  = "Oh my stones! So #much progress, #so little time!"        //Jamie
lang_npc[lang_num,92]  = "'Chicken of the #sea'?! What a #scam!"                    //Chiasa
lang_npc[lang_num,93]  = "That was NOT #chimkin! Yuck!"                             //Chiasa
lang_npc[lang_num,94]  = "What do you mean #I did absolutely #nothing all day?"     //Spade
lang_npc[lang_num,95]  = "I will not deny #these #allegations!"                     //Spade
lang_npc[lang_num,96]  = "Can't keep 'em from#sliding down escalators..."           //Iris
lang_npc[lang_num,97]  = "Good job, girls! #The magister will #be pleased."         //Neera
lang_npc[lang_num,98]  = "And no property #damage- This #time!"                     //Neera
lang_npc[lang_num,99]  = "You're lucky I #have other #priorities, Spade"            //Neera
lang_npc[lang_num,100] = "Gong is busy #playing traffic #warden right now"          //Neera
lang_npc[lang_num,101] = "So, I may have #called out sick #at the job..."           //Tiwi
lang_npc[lang_num,102] = "I MAY have eaten #several #sandwiches!"                   //Tiwi
lang_npc[lang_num,103] = "Today's special: #Umami Delight"                          //Harige
lang_npc[lang_num,104] = "This mall seems #to have it all, #but computers..."       //Kubo
lang_npc[lang_num,105] = "Back to the #catalog books I #guess."                     //Kubo
lang_npc[lang_num,106] = "Hey there! We #got footage of #the flying shark."         //Maria
lang_npc[lang_num,107] = "I have a feeling #you three would #know more!"            //Maria
lang_npc[lang_num,108] = "Dancing is so #much fun! Dancy #dancy! Yay!"              //Milla
lang_npc[lang_num,109] = "Good morning, #kids!"                                     //Savvy
lang_npc[lang_num,110] = "I saw the news! #That was #amazing, Lilac!"               //Savvy
lang_npc[lang_num,111] = "But please rest #up tomorrow, #okay?"                     //Savvy
lang_npc[lang_num,112] = "Carol, you were #*dynamite* on #the news!"                //Savvy
lang_npc[lang_num,113] = "But please don't #forget your #homework!"                 //Savvy
lang_npc[lang_num,114] = "Oh, Milla! You #have so much #potential."                 //Savvy
lang_npc[lang_num,115] = "Let me know if #you need a #scholarship!"                 //Savvy
