var op = obj_game_logic;

//Language Array (Pause Menu); 0 = English; 1 = Portuguese; 2 = Polish
op.lang_gui[0,0] = "Resume"
op.lang_gui[0,1] = "Potions"
op.lang_gui[0,2] = "Checkpoint"
op.lang_gui[0,3] = "Options"
op.lang_gui[0,4] = "Quit"
//Potions Menu
op.lang_gui[0,5] = "Petal Potion"
op.lang_gui[0,6] = "Stamina Drink"
op.lang_gui[0,7] = "Feather Potion"
op.lang_gui[0,8] = "Petal Core"
op.lang_gui[0,9] = "Stamina Core"
op.lang_gui[0,10] = "Mystery"
//Options Menu
op.lang_gui[0,11] = "Camera     Shake     :     "
op.lang_gui[0,12] = "Camera     Zoom     :     "
op.lang_gui[0,13] = "Display       Moves     :     "
op.lang_gui[0,14] = "Enemy      HP      Bars     :     "
op.lang_gui[0,15] = "Sensitivity     :     "
op.lang_gui[0,16] = "Back"
op.lang_gui[0,17] = "Off"
op.lang_gui[0,18] = "On"
op.lang_gui[0,19] = "Paused"
op.lang_gui[0,20] = "Quit      To      Title"
op.lang_gui[0,21] = "Stop      Test"
op.lang_gui[0,22] = "Saving     .     .     ."
//Controllers
op.lang_gui[0,23] = "Select"
op.lang_gui[0,24] = "Start"
op.lang_gui[0,25] = "Left Click"
op.lang_gui[0,26] = "Right Click"
op.lang_gui[0,27] = "Up"
op.lang_gui[0,28] = "Down"
op.lang_gui[0,29] = "Left"
op.lang_gui[0,30] = "Right"

//Brazilian Portuguese
op.lang_gui[1,0] = "Continuar"
op.lang_gui[1,1] = "Poções"
op.lang_gui[1,2] = "Posto     De     Controle"
op.lang_gui[1,3] = "Opções"
op.lang_gui[1,4] = "Sair"
op.lang_gui[1,5] = "Poção de Pétala"
op.lang_gui[1,6] = "Poção de Energia"
op.lang_gui[1,7] = "Poção da Pena"
op.lang_gui[1,8] = "Núcleo de Pétala"
op.lang_gui[1,9] = "Núcleo de Energia"
op.lang_gui[1,10] = "Mistério"
//Options Menu
op.lang_gui[1,11] = "Tremor       na       Câmera     :     "
op.lang_gui[1,12] = "Zoom       da       Câmera     :     "
op.lang_gui[1,13] = "Mostrar      Movimentos     :     "
op.lang_gui[1,14] = "Barras      PV      do      Inimigo     :     "
op.lang_gui[1,15] = "Sensibilidade     :     "
op.lang_gui[1,16] = "Voltar"
op.lang_gui[1,17] = "Desligado"
op.lang_gui[1,18] = "Ligado"
op.lang_gui[1,19] = "Pausar"
op.lang_gui[1,20] = "Sair      para      Título"
op.lang_gui[1,21] = "Stop      Test"
op.lang_gui[1,22] = "Salvando     .     .     ."
//Controllers
op.lang_gui[1,23] = "Selecionar"
op.lang_gui[1,24] = "Começar"
op.lang_gui[1,25] = "Esquerda"
op.lang_gui[1,26] = "Direita"
op.lang_gui[1,27] = "Cima"
op.lang_gui[1,28] = "Baixo"
op.lang_gui[1,29] = "Esquerda"
op.lang_gui[1,30] = "Direita"

//Polish
op.lang_gui[2,0] = "Kontynuuj"
op.lang_gui[2,1] = "Eliksiry"
op.lang_gui[2,2] = "Checkpoint"
op.lang_gui[2,3] = "Opcje"
op.lang_gui[2,4] = "Wyjście"
//Potions Menu
op.lang_gui[2,5] = "Płatkonapój"
op.lang_gui[2,6] = "Siłonapój"
op.lang_gui[2,7] = "Piórkonapój"
op.lang_gui[2,8] = "Płatkordzeń"
op.lang_gui[2,9] = "Energiordzeń"
op.lang_gui[2,10] = "Tajemnica"
//Options Menu
op.lang_gui[2,11] = "Wstrząsy     kamery     :     "
op.lang_gui[2,12] = "Zoom     Kamery     :     "
op.lang_gui[2,13] = "Wyświetlaj     Ruchy     :     "
op.lang_gui[2,14] = "Paski     Życia     Wrogów     :     "
op.lang_gui[2,15] = "Sensytywność     :     "
op.lang_gui[2,16] = "Wstecz"
op.lang_gui[2,17] = "Wyłącz"
op.lang_gui[2,18] = "Włącz"
op.lang_gui[2,19] = "Pauza"
op.lang_gui[2,20] = "Wyjdź      Do      Menu"
op.lang_gui[2,21] = "Skończ      Test"
op.lang_gui[2,22] = "Zapisywanie     .     .     ."
//Controllers
op.lang_gui[2,23] = "Select"
op.lang_gui[2,24] = "Start"
op.lang_gui[2,25] = "Lewy Klik"
op.lang_gui[2,26] = "Prawy Klik"
op.lang_gui[2,27] = "Góra"
op.lang_gui[2,28] = "Dół"
op.lang_gui[2,29] = "Lewo"
op.lang_gui[2,30] = "Prawo"
