///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Платформы"
o.display_page_description[1] = "Трава"
o.display_page_description[2] = "Рампы"
o.display_page_description[3] = "Платформы"
o.display_page_description[4] = "Декорации"
o.display_page_description[5] = "Камень"
o.display_page_description[6] = "Снег"
o.display_page_description[7] = "Храм 1"
o.display_page_description[8] = "Храм 2"
o.display_page_description[9] = "Внутри"
o.display_page_description[10] = "Дополнительно 1"
o.display_page_description[11] = "Дополнительно 2"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Плосский Камень 1"
o.display_description_item[o.display_page_one,1] = "Плосский Край Скалы - Left"
o.display_description_item[o.display_page_one,2] = "Плосский Край Скалы - Right"
o.display_description_item[o.display_page_one,3] = "Плосская Каменная Стена 1"
o.display_description_item[o.display_page_one,4] = "Плосская Каменная Стена 2"
o.display_description_item[o.display_page_one,5] = "Край Деревянной Балки - Левый"
o.display_description_item[o.display_page_one,6] = "Деревянная Балка"
o.display_description_item[o.display_page_one,7] = "Край Деревянной Балки - Правый"
o.display_description_item[o.display_page_one,8] = "Бамбуковый Стебель - Большой"
o.display_description_item[o.display_page_one,9] = "Бамбуковый Стебель - Малый"
o.display_description_item[o.display_page_one,10] = "Бамбуковые Стебли - Тонкие"
o.display_description_item[o.display_page_one,11] = "Бамбуковый Стебель - Большой Жёлтый"
o.display_description_item[o.display_page_one,12] = "Бамбуковый Стебель - Тонкий Жёлтый"
o.display_description_item[o.display_page_one,13] = "Бамбуковый Стебель - Платформа"
o.display_description_item[o.display_page_one,14] = "Бамбуковый Стебель - Жёлтая Платформа"
o.display_description_item[o.display_page_one,15] = "Бамбуковый Стебель - Малая Платформа"
o.display_description_item[o.display_page_one,16] = "Бамбуковый Стебель - Малая Жёлтая Платформа"
o.display_description_item[o.display_page_one,17] = "Горная Трава"
o.display_description_item[o.display_page_one,18] = "Горная Земля - Широкая"
o.display_description_item[o.display_page_one,19] = "Горная Земля - Малая"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Горная Трава - Открытый Правый Край"
o.display_description_item[o.display_page_two,1] = "Горная Трава - Открытая Левая Стена"
o.display_description_item[o.display_page_two,2] = "Горная Трава - Открытый Левый Край"
o.display_description_item[o.display_page_two,3] = "Горная Трава - Открытая Левая Стена"
o.display_description_item[o.display_page_two,4] = "Горная Трава - Перевёрнутая"
o.display_description_item[o.display_page_two,5] = "Горная Трава - Левая Угловая Часть"
o.display_description_item[o.display_page_two,6] = "Горная Трава - Левая Стена"
o.display_description_item[o.display_page_two,7] = "Горная Трава - Правый Край"
o.display_description_item[o.display_page_two,8] = "Горная Трава - Правая Угловая Часть"
o.display_description_item[o.display_page_two,9] = "Горная Трава - Правая Стена"
o.display_description_item[o.display_page_two,10] = "Горная Трава - Левый Край"
o.display_description_item[o.display_page_two,11] = "Горная Трава - Перевёрнутый Край"
o.display_description_item[o.display_page_two,12] = "Горная Трава - Перевёрнутый Край"
o.display_description_item[o.display_page_two,13] = "Каменные Шипы 1"
o.display_description_item[o.display_page_two,14] = "Каменные Шипы 2"
o.display_description_item[o.display_page_two,15] = "Каменные Шипы 3"
o.display_description_item[o.display_page_two,16] = "Каменные Шипы 4"
o.display_description_item[o.display_page_two,17] = "Лестница"
o.display_description_item[o.display_page_two,18] = "Деревянная Перекладина 1"
o.display_description_item[o.display_page_two,19] = "Деревянная Перекладина 2"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Маленькая Рампа - 1"
o.display_description_item[o.display_page_three,1] = "Маленькая Рампа - 2"
o.display_description_item[o.display_page_three,2] = "Маленькая Рампа - 3"
o.display_description_item[o.display_page_three,3] = "Маленькая Рампа - 4"
o.display_description_item[o.display_page_three,4] = "Каменная Петля - Внешняя 1"
o.display_description_item[o.display_page_three,5] = "Каменная Петля - Внешняя 2"
o.display_description_item[o.display_page_three,6] = "Перекладина 2"
o.display_description_item[o.display_page_three,7] = "Каменная Петля - Внутренняя 1"
o.display_description_item[o.display_page_three,8] = "Каменная Петля - Внутренняя 2"
o.display_description_item[o.display_page_three,9] = "Каменная Петля - Внутренняя 3"
o.display_description_item[o.display_page_three,10] = "Каменная Петля - Внутренняя 4"
o.display_description_item[o.display_page_three,11] = "Каменная Петля - Внешняя 3"
o.display_description_item[o.display_page_three,12] = "Каменная Петля - Внешняя 4"
o.display_description_item[o.display_page_three,13] = "Часть Травянистой Петли 1"
o.display_description_item[o.display_page_three,14] = "Часть Травянистой Петли2"
o.display_description_item[o.display_page_three,15] = "Часть Травянистой Петли 3"
o.display_description_item[o.display_page_three,16] = "Часть Травянистой Петли 4"
o.display_description_item[o.display_page_three,17] = "Длинный Травянистый Спуск 1"
o.display_description_item[o.display_page_three,18] = "Длинный Травянистый Спуск 2"
o.display_description_item[o.display_page_three,19] = "Каменная Многоуровневая Платформа"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Каменный Спуск"
o.display_description_item[o.display_page_four,1] = "Каменный Подъём"
o.display_description_item[o.display_page_four,2] = "Травянистый Спуск"
o.display_description_item[o.display_page_four,3] = "Травянистый Подъём"
o.display_description_item[o.display_page_four,4] = "Спуск - Поверхность 3"
o.display_description_item[o.display_page_four,5] = "Плосская Поверхность 1"
o.display_description_item[o.display_page_four,6] = "Спуск - Поверхность 4"
o.display_description_item[o.display_page_four,7] = "Парящая Платформа 1"
o.display_description_item[o.display_page_four,8] = "Парящая Платформа 2"
o.display_description_item[o.display_page_four,9] = "Парящая Платформа 3"
o.display_description_item[o.display_page_four,10] = "Парящая Платформа 4"
o.display_description_item[o.display_page_four,11] = "Парящая Платформа 5"
o.display_description_item[o.display_page_four,12] = "Изменение Направления Платформы"
o.display_description_item[o.display_page_four,13] = "Декор - Часть Каменной Маски 1"
o.display_description_item[o.display_page_four,14] = "Декор - Часть Каменной Маски 2"
o.display_description_item[o.display_page_four,15] = "Декор - Часть Каменной Маски 3"
o.display_description_item[o.display_page_four,16] = "Декор - Часть Каменной Маски 4"
o.display_description_item[o.display_page_four,17] = "Декор - Цветочная Красная Лампа Шанг Му"
o.display_description_item[o.display_page_four,18] = "Декор - Цветочная Оранжевая Лампа Шанг Му"
o.display_description_item[o.display_page_four,19] = "Декор - Тёмный Тайл"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Декор - Камень 1"
o.display_description_item[o.display_page_five,1] = "Декор - Камень 2"
o.display_description_item[o.display_page_five,2] = "Декор - Камень 3"
o.display_description_item[o.display_page_five,3] = "Декор - Камень 4"
o.display_description_item[o.display_page_five,4] = "Декор - Камень 5"
o.display_description_item[o.display_page_five,5] = "Декор - Каменная Стена 1"
o.display_description_item[o.display_page_five,6] = "Декор - Каменная Стена 2"
o.display_description_item[o.display_page_five,7] = "Декор - Каменная Маска - Горизонтальная"
o.display_description_item[o.display_page_five,8] = "Декор - Каменная Маска - Вертикальная"
o.display_description_item[o.display_page_five,9] = "Декор - Подпорка Моста"
o.display_description_item[o.display_page_five,10] = "Декор - Часть Моста"
o.display_description_item[o.display_page_five,11] = "Декор - Дерево 1"
o.display_description_item[o.display_page_five,12] = "Декор - Трава"
o.display_description_item[o.display_page_five,13] = "Декор - Каменная Маска - Альтернативная"
o.display_description_item[o.display_page_five,14] = "Декор - Цветок Бамбука"
o.display_description_item[o.display_page_five,15] = "Декор - Бамбуковый Стебель"
o.display_description_item[o.display_page_five,16] = "Декор - Дерево 2"
o.display_description_item[o.display_page_five,17] = "Декор - Куст"
o.display_description_item[o.display_page_five,18] = "Декор - Ветви Дерева"
o.display_description_item[o.display_page_five,19] = "Бамбуковый Стебель - Большая Стена"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Каменный Пол 1"
o.display_description_item[o.display_page_six,1] = "Каменный Пол 2"
o.display_description_item[o.display_page_six,2] = "Каменный Потолок 1"
o.display_description_item[o.display_page_six,3] = "Каменный Потолок 2"
o.display_description_item[o.display_page_six,4] = "Каменный Край 1"
o.display_description_item[o.display_page_six,5] = "Каменный Пол 3"
o.display_description_item[o.display_page_six,6] = "Каменный Край 2"
o.display_description_item[o.display_page_six,7] = "Камень Тайл 1"
o.display_description_item[o.display_page_six,8] = "Камень Тайл 2"
o.display_description_item[o.display_page_six,9] = "Каменный Потолок 3"
o.display_description_item[o.display_page_six,10] = "Каменная Стена 1"
o.display_description_item[o.display_page_six,11] = "Каменная Стена 2"
o.display_description_item[o.display_page_six,12] = "Каменная Стена 3"
o.display_description_item[o.display_page_six,13] = "Камень Тайл 3"
o.display_description_item[o.display_page_six,14] = "Камень Тайл 4"
o.display_description_item[o.display_page_six,15] = "Каменная Стена 4"
o.display_description_item[o.display_page_six,16] = "Каменная Стена 5"
o.display_description_item[o.display_page_six,17] = "Каменный Потолок 4"
o.display_description_item[o.display_page_six,18] = "Каменный Потолок 5"
o.display_description_item[o.display_page_six,19] = "Каменный Потолок 6"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Снежный Пол 1"
o.display_description_item[o.display_page_seven,1] = "Снежный Пол 2"
o.display_description_item[o.display_page_seven,2] = "Снежный Пол 3"
o.display_description_item[o.display_page_seven,3] = "Снежный Пол 4"
o.display_description_item[o.display_page_seven,4] = "Снежный Пол 5"
o.display_description_item[o.display_page_seven,5] = "Снежный Пол 6"
o.display_description_item[o.display_page_seven,6] = "Снежный Пол 7"
o.display_description_item[o.display_page_seven,7] = "Снежный Пол 1"
o.display_description_item[o.display_page_seven,8] = "Снежный Пол 2"
o.display_description_item[o.display_page_seven,9] = "Снежный Пол 3"
o.display_description_item[o.display_page_seven,10] = "Снежная Стена 1"
o.display_description_item[o.display_page_seven,11] = "Снежная Стена 2"
o.display_description_item[o.display_page_seven,12] = "Снежная Стена 3"
o.display_description_item[o.display_page_seven,13] = "Дерево В Снегу 1"
o.display_description_item[o.display_page_seven,14] = "Снеговик - Панда 1"
o.display_description_item[o.display_page_seven,15] = "Снеговик - Панда 2"
o.display_description_item[o.display_page_seven,16] = "Снеговик - Кошка"
o.display_description_item[o.display_page_seven,17] = "Маленький Снеговик 1"
o.display_description_item[o.display_page_seven,18] = "Маленький Снеговик 2"
o.display_description_item[o.display_page_seven,19] = "Маленький Снеговик 3"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Храм - Fusama 1"
o.display_description_item[o.display_page_eight,1] = "Храм - Fusama 2"
o.display_description_item[o.display_page_eight,2] = "Храм - Fusama 3"
o.display_description_item[o.display_page_eight,3] = "Храм - Fusama 4"
o.display_description_item[o.display_page_eight,4] = "Храм - Fusama 5"
o.display_description_item[o.display_page_eight,5] = "Храм - Fusama 6"
o.display_description_item[o.display_page_eight,6] = "Храм - Wall 1"
o.display_description_item[o.display_page_eight,7] = "Храм - Wall 2"
o.display_description_item[o.display_page_eight,8] = "Храм - Wall 3"
o.display_description_item[o.display_page_eight,9] = "Храм - Wall 4"
o.display_description_item[o.display_page_eight,10] = "Храм - Roof - Left"
o.display_description_item[o.display_page_eight,11] = "Храм - Roof - Middle"
o.display_description_item[o.display_page_eight,12] = "Храм - Roof - Right"
o.display_description_item[o.display_page_eight,13] = "Храм - Beam"
o.display_description_item[o.display_page_eight,14] = "Храм - Beam - Small"
o.display_description_item[o.display_page_eight,15] = "Храм - Beam - Large"
o.display_description_item[o.display_page_eight,16] = "Храм - Beam - Corner 1"
o.display_description_item[o.display_page_eight,17] = "Храм - Beam - Corner 2"
o.display_description_item[o.display_page_eight,18] = "Храм - Beam - Corner 3"
o.display_description_item[o.display_page_eight,19] = "Храм - Beam - Corner 4"

//Tile Descriptions (Page 9)
o.display_description_item[o.display_page_nine,0] = "Храм - Torii"
o.display_description_item[o.display_page_nine,1] = "Храм - Complete Roof"
o.display_description_item[o.display_page_nine,2] = "Храм - Lantern Stand"
o.display_description_item[o.display_page_nine,3] = "Храм - Lamppost"
o.display_description_item[o.display_page_nine,4] = "Храм - Signpost"
o.display_description_item[o.display_page_nine,5] = "Храм - Rooftop Statue"
o.display_description_item[o.display_page_nine,6] = "Храм - Flag"
o.display_description_item[o.display_page_nine,7] = "Wood Beam - Left"
o.display_description_item[o.display_page_nine,8] = "Wood Beam - Middle"
o.display_description_item[o.display_page_nine,9] = "Wood Beam - Right"
o.display_description_item[o.display_page_nine,10] = "Wood Beam - Top"
o.display_description_item[o.display_page_nine,11] = "Wood Beam - Middle"
o.display_description_item[o.display_page_nine,12] = "Wood Beam - Bottom"
o.display_description_item[o.display_page_nine,13] = "Tent"
o.display_description_item[o.display_page_nine,14] = "Folding Chair"
o.display_description_item[o.display_page_nine,15] = "Roasted Marshmallow On A Stick"
o.display_description_item[o.display_page_nine,16] = "Campire - Embers"
o.display_description_item[o.display_page_nine,17] = "Temple - Welcome Banner"
o.display_description_item[o.display_page_nine,18] = "Stinger Nest Stalk"
o.display_description_item[o.display_page_nine,19] = "Stinger Nest End Piece"

//Tile Descriptions (Page 10)
o.display_description_item[o.display_page_ten,0] = "Bookshelf - Large"
o.display_description_item[o.display_page_ten,1] = "Bookshelf - Small"
o.display_description_item[o.display_page_ten,2] = "Cabinet - Left"
o.display_description_item[o.display_page_ten,3] = "Cabinet - Right"
o.display_description_item[o.display_page_ten,4] = "Refrigerator"
o.display_description_item[o.display_page_ten,5] = "Table - Small"
o.display_description_item[o.display_page_ten,6] = "Table - Large"
o.display_description_item[o.display_page_ten,7] = "Hallway Lamp"
o.display_description_item[o.display_page_ten,8] = "TV Set"
o.display_description_item[o.display_page_ten,9] = "Living Room Couch"
o.display_description_item[o.display_page_ten,10] = "Bed"
o.display_description_item[o.display_page_ten,11] = "Oven and Stovetop"
o.display_description_item[o.display_page_ten,12] = "Wooden Chair"
o.display_description_item[o.display_page_ten,13] = "Cabinet - Small"
o.display_description_item[o.display_page_ten,14] = "Toaster"
o.display_description_item[o.display_page_ten,15] = "Curtains - Large"
o.display_description_item[o.display_page_ten,16] = "Curtains - Small"
o.display_description_item[o.display_page_ten,17] = "Wall Clock"
o.display_description_item[o.display_page_ten,18] = "Alarm Clock"
o.display_description_item[o.display_page_ten,19] = "Unknown Tile"

//Tile Descriptions (Page 11)
o.display_description_item[o.display_page_eleven,0] = "Grass Flat Left"
o.display_description_item[o.display_page_eleven,1] = "Grass Flat"
o.display_description_item[o.display_page_eleven,2] = "Grass Flat Right"
o.display_description_item[o.display_page_eleven,3] = "Grass Flat Large"
o.display_description_item[o.display_page_eleven,4] = "Grass Flat Thin"
o.display_description_item[o.display_page_eleven,5] = "Dirt"
o.display_description_item[o.display_page_eleven,6] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,7] = "Dirt Wall Left"
o.display_description_item[o.display_page_eleven,8] = "Dirt"
o.display_description_item[o.display_page_eleven,9] = "Dirt Wall Right"
o.display_description_item[o.display_page_eleven,10] = "Grassy Slope 1"
o.display_description_item[o.display_page_eleven,11] = "Grassy Slope 1"
o.display_description_item[o.display_page_eleven,12] = "Grassy Slope 1"
o.display_description_item[o.display_page_eleven,13] = "Dirt Ceiling Left"
o.display_description_item[o.display_page_eleven,14] = "Dirt Ceiling"
o.display_description_item[o.display_page_eleven,15] = "Dirt Ceiling Right"
o.display_description_item[o.display_page_eleven,16] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,17] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,18] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,19] = "Unknown Tile"

//Tile Descriptions (Page 12)
o.display_description_item[o.display_page_twelve,0] = "Wood Block Left"
o.display_description_item[o.display_page_twelve,1] = "Wood Block Horizontal"
o.display_description_item[o.display_page_twelve,2] = "Wood Block Right"
o.display_description_item[o.display_page_twelve,3] = "Wood Block Top"
o.display_description_item[o.display_page_twelve,4] = "Wood Block Vertical"
o.display_description_item[o.display_page_twelve,5] = "Wood Block Bottom"
o.display_description_item[o.display_page_twelve,6] = "Broken Paper Lamp"
o.display_description_item[o.display_page_twelve,7] = "Wood Ramp Left"
o.display_description_item[o.display_page_twelve,8] = "Wood Ramp Right"
o.display_description_item[o.display_page_twelve,9] = "Unknown Tile"
o.display_description_item[o.display_page_twelve,10] = "Unknown Tile"
o.display_description_item[o.display_page_twelve,11] = "Unknown Tile"
o.display_description_item[o.display_page_twelve,12] = "Unknown Tile"
o.display_description_item[o.display_page_twelve,13] = "Damaged Wall 1"
o.display_description_item[o.display_page_twelve,14] = "Damaged Wall 2"
o.display_description_item[o.display_page_twelve,15] = "Dragon Scroll"
o.display_description_item[o.display_page_twelve,16] = "Katana in Stone"
o.display_description_item[o.display_page_twelve,17] = "Unknown Tile"
o.display_description_item[o.display_page_twelve,18] = "Unknown Tile"
o.display_description_item[o.display_page_twelve,19] = "Unknown Tile"
