///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Wnętrze 1"
o.display_page_description[1] = "Wnętrze 2"
o.display_page_description[2] = "Sceneria"
o.display_page_description[3] = "???"
o.display_page_description[4] = "???"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Panel Podłogowy 1"
o.display_description_item[o.display_page_one,1] = "Panel Podłogowy 2"
o.display_description_item[o.display_page_one,2] = "Panel Podłogowy 3"
o.display_description_item[o.display_page_one,3] = "Panel Ścienny 1"
o.display_description_item[o.display_page_one,4] = "Panel Ścienny 2"
o.display_description_item[o.display_page_one,5] = "Panel Sufitowy 1"
o.display_description_item[o.display_page_one,6] = "Panel Sufitowy 2"
o.display_description_item[o.display_page_one,7] = "Panel Sufitowy 3"
o.display_description_item[o.display_page_one,8] = "Panel Krawędziowy 1"
o.display_description_item[o.display_page_one,9] = "Panel Krawędziowy 2"
o.display_description_item[o.display_page_one,10] = "Panel Krawędziowy 3"
o.display_description_item[o.display_page_one,11] = "Panel Krawędziowy 4"
o.display_description_item[o.display_page_one,12] = "Panel Krawędziowy 5"
o.display_description_item[o.display_page_one,13] = "Panel Podłogowy 4"
o.display_description_item[o.display_page_one,14] = "Panel Podłogowy 5"
o.display_description_item[o.display_page_one,15] = "Panel Ścienny 3"
o.display_description_item[o.display_page_one,16] = "Panel Ścienny 4"
o.display_description_item[o.display_page_one,17] = "Panel Ścienny 5"
o.display_description_item[o.display_page_one,18] = "Panel Ścienny 6"
o.display_description_item[o.display_page_one,19] = "Panel Ścienny 7"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Alternatywny Panel Podłogowy 1"
o.display_description_item[o.display_page_two,1] = "Alternatywny Panel Podłogowy 2"
o.display_description_item[o.display_page_two,2] = "Alternatywny Panel Podłogowy 3"
o.display_description_item[o.display_page_two,3] = "Metalowy Most"
o.display_description_item[o.display_page_two,4] = "Metalowa Rura"
o.display_description_item[o.display_page_two,5] = ""
o.display_description_item[o.display_page_two,6] = ""
o.display_description_item[o.display_page_two,7] = "Alternatywny Panel Ścienny 1"
o.display_description_item[o.display_page_two,8] = "Alternatywny Panel Ścienny 2"
o.display_description_item[o.display_page_two,9] = "Alternatywny Panel Ścienny 3"
o.display_description_item[o.display_page_two,10] = ""
o.display_description_item[o.display_page_two,11] = "Zerdzewiała Pętla 1"
o.display_description_item[o.display_page_two,12] = "Zerdzewiała Pętla 2"
o.display_description_item[o.display_page_two,13] = "Alternatywny Panel Sufitowy 1"
o.display_description_item[o.display_page_two,14] = "Alternatywny Panel Sufitowy 2"
o.display_description_item[o.display_page_two,15] = "Alternatywny Panel Sufitowy 3"
o.display_description_item[o.display_page_two,16] = ""
o.display_description_item[o.display_page_two,17] = ""
o.display_description_item[o.display_page_two,18] = "Zerdzewiała Pętla 3"
o.display_description_item[o.display_page_two,19] = "Zerdzewiała Pętla 4"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Kolumna"
o.display_description_item[o.display_page_three,1] = "Korytarz"
o.display_description_item[o.display_page_three,2] = "Drzwi 1"
o.display_description_item[o.display_page_three,3] = "Drzwi 2"
o.display_description_item[o.display_page_three,4] = "Zwiędły Kwiat"
o.display_description_item[o.display_page_three,5] = "Zielona Kolumna"
o.display_description_item[o.display_page_three,6] = "Brązowa Kolumna"
o.display_description_item[o.display_page_three,7] = "Uszkodzony Transporter"
o.display_description_item[o.display_page_three,8] = "Zerdzewiała Wentylacja"
o.display_description_item[o.display_page_three,9] = "Zniszczony Monitor"
o.display_description_item[o.display_page_three,10] = "Skorupa Shade Troopera 1"
o.display_description_item[o.display_page_three,11] = "Skorupa Shade Troopera 2"
o.display_description_item[o.display_page_three,12] = "Skorupa Shade Troopera 3"
o.display_description_item[o.display_page_three,13] = "Monitor ze Statusem"
o.display_description_item[o.display_page_three,14] = ""
o.display_description_item[o.display_page_three,15] = ""
o.display_description_item[o.display_page_three,16] = ""
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""
