///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Platformy"
o.display_page_description[1] = "Hydraulika"
o.display_page_description[2] = "Sceneria"
o.display_page_description[3] = "Trawa/Ziemia"
o.display_page_description[4] = "Extra"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Ukruszona Ceglana Platforma - 1"
o.display_description_item[o.display_page_one,1] = "Ukruszona Ceglana Platforma - 2"
o.display_description_item[o.display_page_one,2] = "Ukruszona Ceglana Platforma - 3"
o.display_description_item[o.display_page_one,3] = "Ukruszona Ceglana Ściana - 1"
o.display_description_item[o.display_page_one,4] = "Ukruszona Ceglana Ściana - 2"
o.display_description_item[o.display_page_one,5] = "Ukruszona Ceglana Ściana - 3"
o.display_description_item[o.display_page_one,6] = "Ceglana Ściana - 1"
o.display_description_item[o.display_page_one,7] = "Ceglana Ściana - 2"
o.display_description_item[o.display_page_one,8] = "Ceglana Ściana - 3"
o.display_description_item[o.display_page_one,9] = "Ceglana Ściana - 4"
o.display_description_item[o.display_page_one,10] = "Ceglana Ściana - 5"
o.display_description_item[o.display_page_one,11] = "Cegiełka - 1"
o.display_description_item[o.display_page_one,12] = "Cegiełka - 2"
o.display_description_item[o.display_page_one,13] = "Mała Rura 1"
o.display_description_item[o.display_page_one,14] = "Duża Rura 1"
o.display_description_item[o.display_page_one,15] = "Duża Rura 2"
o.display_description_item[o.display_page_one,16] = "Duża Rura 3"
o.display_description_item[o.display_page_one,17] = "Łącznik Rur 1"
o.display_description_item[o.display_page_one,18] = "Łącznik Rur 2"
o.display_description_item[o.display_page_one,19] = "Łącznik Rur 3"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Ściana - Kanały 1"
o.display_description_item[o.display_page_two,1] = "Ściana - Kanały 2"
o.display_description_item[o.display_page_two,2] = "Sceneria - Kanały 1"
o.display_description_item[o.display_page_two,3] = "Sceneria - Kanały 2"
o.display_description_item[o.display_page_two,4] = "Sceneria - Kanały 3"
o.display_description_item[o.display_page_two,5] = "Sceneria - Kanały 4"
o.display_description_item[o.display_page_two,6] = "Sceneria - Kanały 5"
o.display_description_item[o.display_page_two,7] = "Kątowa Rura 1"
o.display_description_item[o.display_page_two,8] = "Kątowa Rura 2"
o.display_description_item[o.display_page_two,9] = "Kątowa Rura 3"
o.display_description_item[o.display_page_two,10] = "Kątowa Rura 4"
o.display_description_item[o.display_page_two,11] = "Podpora Budowlana 1"
o.display_description_item[o.display_page_two,12] = "Podpora Budowlana 2"
o.display_description_item[o.display_page_two,13] = "Kolce 1"
o.display_description_item[o.display_page_two,14] = "Kolce 2"
o.display_description_item[o.display_page_two,15] = "Kolce 3"
o.display_description_item[o.display_page_two,16] = "Kolce 4"
o.display_description_item[o.display_page_two,17] = "Drabina 1"
o.display_description_item[o.display_page_two,18] = "Drabina 2"
o.display_description_item[o.display_page_two,19] = "Uchwyt 1"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Okno - Zielone - Duże"
o.display_description_item[o.display_page_three,1] = "Okno - Zielone - Małe"
o.display_description_item[o.display_page_three,2] = "Okno - Niebieskie - Małe"
o.display_description_item[o.display_page_three,3] = "Podpora 1"
o.display_description_item[o.display_page_three,4] = "Podpora 2"
o.display_description_item[o.display_page_three,5] = "Podpora 3"
o.display_description_item[o.display_page_three,6] = "Kątowa Podpora - Całość"
o.display_description_item[o.display_page_three,7] = "Kątowa Podpora - Dół"
o.display_description_item[o.display_page_three,8] = "Kątowa Podpora - Środek"
o.display_description_item[o.display_page_three,9] = "Kątowa Podpora - Góra"
o.display_description_item[o.display_page_three,10] = "Kątowa Podpora - Dół"
o.display_description_item[o.display_page_three,11] = "Kątowa Podpora - Środek"
o.display_description_item[o.display_page_three,12] = "Kątowa Podpora - Góra"
o.display_description_item[o.display_page_three,13] = "Narożnik - 1"
o.display_description_item[o.display_page_three,14] = "Narożnik - 2"
o.display_description_item[o.display_page_three,15] = "Narożnik - 3"
o.display_description_item[o.display_page_three,16] = "Narożnik - 4"
o.display_description_item[o.display_page_three,17] = "Narożnik - 5"
o.display_description_item[o.display_page_three,18] = "Narożnik - 6"
o.display_description_item[o.display_page_three,19] = "Narożnik - Środek"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Trawa - Lewa Krawędź"
o.display_description_item[o.display_page_four,1] = "Trawa - Góra"
o.display_description_item[o.display_page_four,2] = "Trawa - Prawa Krawędź"
o.display_description_item[o.display_page_four,3] = "Trawiasty Stok 1"
o.display_description_item[o.display_page_four,4] = "Trawiasty Stok 2"
o.display_description_item[o.display_page_four,5] = "Trawiasty Stok 3"
o.display_description_item[o.display_page_four,6] = "Sceneria - Trawa"
o.display_description_item[o.display_page_four,7] = "Ziemia - Lewa Ściana"
o.display_description_item[o.display_page_four,8] = "Ziemia - Mała"
o.display_description_item[o.display_page_four,9] = "Ziemia - Prawa Ściana"
o.display_description_item[o.display_page_four,10] = "Trawa - Płaska - Duża"
o.display_description_item[o.display_page_four,11] = "Trawa - Nierówna"
o.display_description_item[o.display_page_four,12] = "Trawa - Płaska - Mała"
o.display_description_item[o.display_page_four,13] = "Trawa - Krawędź - Lewa"
o.display_description_item[o.display_page_four,14] = "Trawa - Dół"
o.display_description_item[o.display_page_four,15] = "Trawa - Krawędź - Prawa"
o.display_description_item[o.display_page_four,16] = "Duża Ziemia"
o.display_description_item[o.display_page_four,17] = "Ziemny Stok 1"
o.display_description_item[o.display_page_four,18] = "Ziemny Stok 2"
o.display_description_item[o.display_page_four,19] = "Ziemny Stok 3"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Okrągła Pętla 1"
o.display_description_item[o.display_page_five,1] = "Okrągła Pętla 2"
o.display_description_item[o.display_page_five,2] = "Rurowa Pętla 1"
o.display_description_item[o.display_page_five,3] = "Rurowa Pętla 2"
o.display_description_item[o.display_page_five,4] = "Płaski Blok Ziemi - Extra 1"
o.display_description_item[o.display_page_five,5] = "Płaski Blok Ziemi - Extra 2"
o.display_description_item[o.display_page_five,6] = "Płaski Blok Ziemi - Extra 3"
o.display_description_item[o.display_page_five,7] = "Okrągła Pętla 3"
o.display_description_item[o.display_page_five,8] = "Okrągła Pętla 4"
o.display_description_item[o.display_page_five,9] = "Rurowa Pętla 3"
o.display_description_item[o.display_page_five,10] = "Rurowa Pętla 4"
o.display_description_item[o.display_page_five,11] = "Płaski Blok Ziemi - Extra 4"
o.display_description_item[o.display_page_five,12] = "Płaski Blok Ziemi - Extra 5"
o.display_description_item[o.display_page_five,13] = "Czysta Ściana 1"
o.display_description_item[o.display_page_five,14] = "Czysta Ściana 2"
o.display_description_item[o.display_page_five,15] = "Czysta Podłoga 1"
o.display_description_item[o.display_page_five,16] = "Czysta Ściana 3"
o.display_description_item[o.display_page_five,17] = "Czysta Podłoga 2"
o.display_description_item[o.display_page_five,18] = "Czysta Podłoga 3"
o.display_description_item[o.display_page_five,19] = "Czysta Ściana 4"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Recycling Dumpster"
o.display_description_item[o.display_page_six,1] = "Ninja Crossing Sign"
o.display_description_item[o.display_page_six,2] = "East Road Street Sign"
o.display_description_item[o.display_page_six,3] = "North Circle Street Sign"
o.display_description_item[o.display_page_six,4] = "South Drive Street Sign"
o.display_description_item[o.display_page_six,5] = "West Lane Street Sign"
o.display_description_item[o.display_page_six,6] = "Blank Street Sign"
o.display_description_item[o.display_page_six,7] = "Arrow Sign"
o.display_description_item[o.display_page_six,8] = "Recycle Bin"
o.display_description_item[o.display_page_six,9] = "Traffic Lights"
o.display_description_item[o.display_page_six,10] = "Lamp Post"
o.display_description_item[o.display_page_six,11] = "Lamp Pole 1"
o.display_description_item[o.display_page_six,12] = "Lamp Pole 2"
o.display_description_item[o.display_page_six,13] = "Lamp Pole 3"
o.display_description_item[o.display_page_six,14] = "Bush"
o.display_description_item[o.display_page_six,15] = "One Of A Kind Eggplant"
o.display_description_item[o.display_page_six,16] = "Clothes Line"
o.display_description_item[o.display_page_six,17] = "Pedestrian Crossing Sign"
o.display_description_item[o.display_page_six,18] = "Pedestrian Signal"
o.display_description_item[o.display_page_six,19] = "Trash Can"

