///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Plataformas"
o.display_page_description[1] = "Pasto/Tierra"
o.display_page_description[2] = "Rampas"
o.display_page_description[3] = "Plataformas"
o.display_page_description[4] = "Decoracion"
o.display_page_description[5] = "Rocas"
o.display_page_description[6] = "Nieve"
o.display_page_description[7] = "Templo 1"
o.display_page_description[8] = "Templo 2"
o.display_page_description[9] = "Interior"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Roca Plana 1"
o.display_description_item[o.display_page_one,1] = "Borde de Acantilado Plano - Izquierda"
o.display_description_item[o.display_page_one,2] = "Borde de Acantilado Plano - Izquierda"
o.display_description_item[o.display_page_one,3] = "Pared de Roca Plana 1"
o.display_description_item[o.display_page_one,4] = "Pared de Roca Plana 2"
o.display_description_item[o.display_page_one,5] = "Borde de Viga de Madera - Izquierda"
o.display_description_item[o.display_page_one,6] = "Viga de Madera"
o.display_description_item[o.display_page_one,7] = "Borde de Viga de Madera - Derecha"
o.display_description_item[o.display_page_one,8] = "Tallo de Bambú - Grande"
o.display_description_item[o.display_page_one,9] = "Tallo de Bambú - Pequeño"
o.display_description_item[o.display_page_one,10] = "Tallos de Bambú - Delgado"
o.display_description_item[o.display_page_one,11] = "Tallo de Bambú - Amarillo Grande"
o.display_description_item[o.display_page_one,12] = "Tallo de Bambú - Amarillo Delgado"
o.display_description_item[o.display_page_one,13] = "Tallo de Bambú - Plataforma"
o.display_description_item[o.display_page_one,14] = "Tallo de Bambú - Plataforma Amarilla"
o.display_description_item[o.display_page_one,15] = "Tallo de Bambú - Plataforma Pequeña"
o.display_description_item[o.display_page_one,16] = "Tallo de Bambú - Plataforma Amarilla Pequeña"
o.display_description_item[o.display_page_one,17] = "Hierba de Montaña"
o.display_description_item[o.display_page_one,18] = "Tierra de Montaña - Amplia"
o.display_description_item[o.display_page_one,19] = "Tierra de Montaña - Pequeña"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Hierba de Montaña - Esquina Derecha Expuesta"
o.display_description_item[o.display_page_two,1] = "Hierba de Montaña - Muro Izquierdo Expuesto"
o.display_description_item[o.display_page_two,2] = "Hierba de Montaña - Esquina Izquierda Expuesta"
o.display_description_item[o.display_page_two,3] = "Hierba de Montaña - Muro Derecho Expuesto"
o.display_description_item[o.display_page_two,4] = "Hierba de Montaña - Bocabajo"
o.display_description_item[o.display_page_two,5] = "Hierba de Montaña - Pieza de Esquina Izquierda"
o.display_description_item[o.display_page_two,6] = "Hierba de Montaña - Pared Izquierda"
o.display_description_item[o.display_page_two,7] = "Hierba de Montaña - Esquina Derecha"
o.display_description_item[o.display_page_two,8] = "Hierba de Montaña - Pieza de Esquina Derecha"
o.display_description_item[o.display_page_two,9] = "Hierba de Montaña - Pared Derecha"
o.display_description_item[o.display_page_two,10] = "Hierba de Montaña - Esquina Izquierda"
o.display_description_item[o.display_page_two,11] = "Hierba de Montaña - Esquina Bocabajo"
o.display_description_item[o.display_page_two,12] = "Hierba de Montaña - Esquina Bocabajo"
o.display_description_item[o.display_page_two,13] = "Pinchos Rocosos 1"
o.display_description_item[o.display_page_two,14] = "Pinchos Rocosos 2"
o.display_description_item[o.display_page_two,15] = "Pinchos Rocosos 3"
o.display_description_item[o.display_page_two,16] = "Pinchos Rocosos 4"
o.display_description_item[o.display_page_two,17] = "Escalera"
o.display_description_item[o.display_page_two,18] = "Barra Suspendida de Madera 1"
o.display_description_item[o.display_page_two,19] = "Barra Suspendida de Madera 2"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Rampa Pequeña - 1"
o.display_description_item[o.display_page_three,1] = "Rampa Pequeña - 2"
o.display_description_item[o.display_page_three,2] = "Rampa Pequeña - 3"
o.display_description_item[o.display_page_three,3] = "Rampa Pequeña - 4"
o.display_description_item[o.display_page_three,4] = "Bucle Rocoso en Dona - Exterior 1"
o.display_description_item[o.display_page_three,5] = "Bucle Rocoso en Dona - Exterior 2"
o.display_description_item[o.display_page_three,6] = "Barra Suspendida 2"
o.display_description_item[o.display_page_three,7] = "Bucle Rocoso en Dona - Interior 1"
o.display_description_item[o.display_page_three,8] = "Bucle Rocoso en Dona - Interior 2"
o.display_description_item[o.display_page_three,9] = "Bucle Rocoso en Dona - Interior 3"
o.display_description_item[o.display_page_three,10] = "Bucle Rocoso en Dona - Interior 4"
o.display_description_item[o.display_page_three,11] = "Bucle Rocoso en Dona - Exterior 3"
o.display_description_item[o.display_page_three,12] = "Bucle Rocoso en Dona - Exterior 4"
o.display_description_item[o.display_page_three,13] = "Pieza de Bucle de Hierba 1"
o.display_description_item[o.display_page_three,14] = "Pieza de Bucle de Hierba 2"
o.display_description_item[o.display_page_three,15] = "Pieza de Bucle de Hierba 3"
o.display_description_item[o.display_page_three,16] = "Pieza de Bucle de Hierba 4"
o.display_description_item[o.display_page_three,17] = "Pieza Larga de Hierba Inclinada 1"
o.display_description_item[o.display_page_three,18] = "Pieza Larga de Hierba Inclinada 2"
o.display_description_item[o.display_page_three,19] = "Plataforma Piso-Sobre-Piso Rocosa"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Roca Descendiente"
o.display_description_item[o.display_page_four,1] = "Roca Ascendente"
o.display_description_item[o.display_page_four,2] = "Hierba Descendiente"
o.display_description_item[o.display_page_four,3] = "Hierba Ascendente"
o.display_description_item[o.display_page_four,4] = "Pendiente en Descenso - Simple 3"
o.display_description_item[o.display_page_four,5] = "Superficie Plana 1"
o.display_description_item[o.display_page_four,6] = "Pendiente en Descenso - Simple 4"
o.display_description_item[o.display_page_four,7] = "Plataforma Flotante 1"
o.display_description_item[o.display_page_four,8] = "Plataforma Flotante 2"
o.display_description_item[o.display_page_four,9] = "Plataforma Flotante 3"
o.display_description_item[o.display_page_four,10] = "Plataforma Flotante 4"
o.display_description_item[o.display_page_four,11] = "Plataforma Flotante 5"
o.display_description_item[o.display_page_four,12] = "Sendero Invertido de Plataforma"
o.display_description_item[o.display_page_four,13] = "Ambiente - Pieza de Esquina - Máscara de Roca 1"
o.display_description_item[o.display_page_four,14] = "Ambiente - Pieza de Esquina - Máscara de Roca 2"
o.display_description_item[o.display_page_four,15] = "Ambiente - Pieza de Esquina - Máscara de Roca 3"
o.display_description_item[o.display_page_four,16] = "Ambiente - Pieza de Esquina - Máscara de Roca 4"
o.display_description_item[o.display_page_four,17] = "Ambiente - Planta Linterna Roja de Shang Mu"
o.display_description_item[o.display_page_four,18] = "Ambiente - Planta Linterna Anaranjada de Shang Mu"
o.display_description_item[o.display_page_four,19] = "Ambiente - Cuadro Oscuro"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Ambiente - Roca 1"
o.display_description_item[o.display_page_five,1] = "Ambiente - Roca 2"
o.display_description_item[o.display_page_five,2] = "Ambiente - Roca3"
o.display_description_item[o.display_page_five,3] = "Ambiente - Roca 4"
o.display_description_item[o.display_page_five,4] = "Ambiente - Roca 5"
o.display_description_item[o.display_page_five,5] = "Ambiente - Pared de Roca 1"
o.display_description_item[o.display_page_five,6] = "Ambiente - Pared de Roca 2"
o.display_description_item[o.display_page_five,7] = "Ambiente - Máscara de Roca - Horizontal"
o.display_description_item[o.display_page_five,8] = "Ambiente - Máscara de Roca - Vertical"
o.display_description_item[o.display_page_five,9] = "Ambiente - Poste de Puente"
o.display_description_item[o.display_page_five,10] = "Ambiente - Pieza de Puente"
o.display_description_item[o.display_page_five,11] = "Ambiente - Árbol 1"
o.display_description_item[o.display_page_five,12] = "Ambiente - Hierba"
o.display_description_item[o.display_page_five,13] = "Ambiente - Máscara de Roca - Alternativa"
o.display_description_item[o.display_page_five,14] = "Ambiente - Flor de Bambú"
o.display_description_item[o.display_page_five,15] = "Ambiente - Tallo de Bambú"
o.display_description_item[o.display_page_five,16] = "Ambiente - Árbol 2"
o.display_description_item[o.display_page_five,17] = "Ambiente - Arbusto"
o.display_description_item[o.display_page_five,18] = "Ambiente - Ramas de Árbol"
o.display_description_item[o.display_page_five,19] = "Tallo de Bambú - Pared Grande"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Superficie Rocosa 1"
o.display_description_item[o.display_page_six,1] = "Superficie Rocosa 2"
o.display_description_item[o.display_page_six,2] = "Techo Rocoso 1"
o.display_description_item[o.display_page_six,3] = "Techo Rocoso 2"
o.display_description_item[o.display_page_six,4] = "Borde Rocoso 1"
o.display_description_item[o.display_page_six,5] = "Superficie Rocosa 3"
o.display_description_item[o.display_page_six,6] = "Borde Rocoso 2"
o.display_description_item[o.display_page_six,7] = "Interior de Roca 1"
o.display_description_item[o.display_page_six,8] = "Interior de Roca 2"
o.display_description_item[o.display_page_six,9] = "Interior de Roca 3"
o.display_description_item[o.display_page_six,10] = "Pared Rocosa 1"
o.display_description_item[o.display_page_six,11] = "Pared Rocosa 2"
o.display_description_item[o.display_page_six,12] = "Pared Rocosa 3"
o.display_description_item[o.display_page_six,13] = "Interior de Roca 3"
o.display_description_item[o.display_page_six,14] = "Interior de Roca 4"
o.display_description_item[o.display_page_six,15] = "Pared Rocosa 4"
o.display_description_item[o.display_page_six,16] = "Pared Rocosa 5"
o.display_description_item[o.display_page_six,17] = "Techo Rocoso 4"
o.display_description_item[o.display_page_six,18] = "Techo Rocoso 5"
o.display_description_item[o.display_page_six,19] = "Techo Rocoso 6"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Superficie de Nieve 1"
o.display_description_item[o.display_page_seven,1] = "Superficie de Nieve 2"
o.display_description_item[o.display_page_seven,2] = "Superficie de Nieve 3"
o.display_description_item[o.display_page_seven,3] = "Superficie de Nieve 4"
o.display_description_item[o.display_page_seven,4] = "Superficie de Nieve 5"
o.display_description_item[o.display_page_seven,5] = "Superficie de Nieve 6"
o.display_description_item[o.display_page_seven,6] = "Superficie de Nieve 7"
o.display_description_item[o.display_page_seven,7] = "Techo de Nieve 1"
o.display_description_item[o.display_page_seven,8] = "Techo de Nieve 2"
o.display_description_item[o.display_page_seven,9] = "Techo de Nieve 3"
o.display_description_item[o.display_page_seven,10] = "Pared de Nieve 1"
o.display_description_item[o.display_page_seven,11] = "Pared de Nieve 2"
o.display_description_item[o.display_page_seven,12] = "Pared de Nieve 3"
o.display_description_item[o.display_page_seven,13] = "Árbol Nevado 1"
o.display_description_item[o.display_page_seven,14] = "Panda de Nieve 1"
o.display_description_item[o.display_page_seven,15] = "Panda de Nieve 2"
o.display_description_item[o.display_page_seven,16] = "Gato de Nieve"
o.display_description_item[o.display_page_seven,17] = "Niño de Nieve 1"
o.display_description_item[o.display_page_seven,18] = "Niño de Nieve 2"
o.display_description_item[o.display_page_seven,19] = "Niño de Nieve 3"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Templo - Fusama 1"
o.display_description_item[o.display_page_eight,1] = "Templo - Fusama 2"
o.display_description_item[o.display_page_eight,2] = "Templo - Fusama 3"
o.display_description_item[o.display_page_eight,3] = "Templo - Fusama 4"
o.display_description_item[o.display_page_eight,4] = "Templo - Fusama 5"
o.display_description_item[o.display_page_eight,5] = "Templo - Fusama 6"
o.display_description_item[o.display_page_eight,6] = "Templo - Pared 1"
o.display_description_item[o.display_page_eight,7] = "Templo - Pared 2"
o.display_description_item[o.display_page_eight,8] = "Templo - Pared 3"
o.display_description_item[o.display_page_eight,9] = "Templo - Pared 4"
o.display_description_item[o.display_page_eight,10] = "Templo - Techo - Izquierda"
o.display_description_item[o.display_page_eight,11] = "Templo - Techo - Medio"
o.display_description_item[o.display_page_eight,12] = "Templo - Techo - Derecha"
o.display_description_item[o.display_page_eight,13] = "Templo - Viga"
o.display_description_item[o.display_page_eight,14] = "Templo - Viga - Pequeña"
o.display_description_item[o.display_page_eight,15] = "Templo - Viga - Grande"
o.display_description_item[o.display_page_eight,16] = "Templo - Viga - Esquina 1"
o.display_description_item[o.display_page_eight,17] = "Templo - Viga - Esquina 2"
o.display_description_item[o.display_page_eight,18] = "Templo - Viga - Esquina 3"
o.display_description_item[o.display_page_eight,19] = "Templo - Viga - Esquina 4"

//Tile Descriptions (Page 9)
o.display_description_item[o.display_page_nine,0] = "Templo - Torii"
o.display_description_item[o.display_page_nine,1] = "Templo - Techo Completo"
o.display_description_item[o.display_page_nine,2] = "Templo - Soporte de Linterna"
o.display_description_item[o.display_page_nine,3] = "Templo - Poste de Luz"
o.display_description_item[o.display_page_nine,4] = "Templo - Letrero"
o.display_description_item[o.display_page_nine,5] = "Templo - Estatua en el Tejado"
o.display_description_item[o.display_page_nine,6] = "Templo - Bandera"
o.display_description_item[o.display_page_nine,7] = "Viga de Madera - Izquierda"
o.display_description_item[o.display_page_nine,8] = "Viga de Madera - Medio"
o.display_description_item[o.display_page_nine,9] = "Viga de Madera - Derecha"
o.display_description_item[o.display_page_nine,10] = "Viga de Madera - Superior"
o.display_description_item[o.display_page_nine,11] = "Viga de Madera - Medio"
o.display_description_item[o.display_page_nine,12] = "Viga de Madera - Inferior"
o.display_description_item[o.display_page_nine,13] = "Tienda"
o.display_description_item[o.display_page_nine,14] = "Silla Plegable"
o.display_description_item[o.display_page_nine,15] = "Malvavisco Asado En Un Palo"
o.display_description_item[o.display_page_nine,16] = "Hoguera - Ascuas"
o.display_description_item[o.display_page_nine,17] = "Templo - Bandera de Bienvenida"
o.display_description_item[o.display_page_nine,18] = "Unknown Tile"
o.display_description_item[o.display_page_nine,19] = "Unknown Tile"

//Tile Descriptions (Page 10)
o.display_description_item[o.display_page_ten,0] = "Estanteria - Grande"
o.display_description_item[o.display_page_ten,1] = "Estanteria - Pequeña"
o.display_description_item[o.display_page_ten,2] = "Gabinete - Izquierdo"
o.display_description_item[o.display_page_ten,3] = "Gabinete - Derecho"
o.display_description_item[o.display_page_ten,4] = "Refrigerador"
o.display_description_item[o.display_page_ten,5] = "Mesa - Pequeña"
o.display_description_item[o.display_page_ten,6] = "Mesa - Grande"
o.display_description_item[o.display_page_ten,7] = "Lampara de Pasillo"
o.display_description_item[o.display_page_ten,8] = "Televisión"
o.display_description_item[o.display_page_ten,9] = "Sofá"
o.display_description_item[o.display_page_ten,10] = "Cama"
o.display_description_item[o.display_page_ten,11] = "Cocina"
o.display_description_item[o.display_page_ten,12] = "Silla de Madera"
o.display_description_item[o.display_page_ten,13] = "Gabinete- Pequeño"
o.display_description_item[o.display_page_ten,14] = "Tostadora"
o.display_description_item[o.display_page_ten,15] = "Cortinas - Grande"
o.display_description_item[o.display_page_ten,16] = "Cortinas - Pequeña"
o.display_description_item[o.display_page_ten,17] = "Reloj de Pared"
o.display_description_item[o.display_page_ten,18] = "Reloj de Alarma"
o.display_description_item[o.display_page_ten,19] = "Unknown Tile"

//Tile Descriptions (Page 11)
o.display_description_item[o.display_page_eleven,0] = "Grass Flat Left"
o.display_description_item[o.display_page_eleven,1] = "Grass Flat"
o.display_description_item[o.display_page_eleven,2] = "Grass Flat Right"
o.display_description_item[o.display_page_eleven,3] = "Grass Flat Large"
o.display_description_item[o.display_page_eleven,4] = "Grass Flat Thin"
o.display_description_item[o.display_page_eleven,5] = "Dirt"
o.display_description_item[o.display_page_eleven,6] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,7] = "Dirt Wall Left"
o.display_description_item[o.display_page_eleven,8] = "Dirt"
o.display_description_item[o.display_page_eleven,9] = "Dirt Wall Right"
o.display_description_item[o.display_page_eleven,10] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,11] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,12] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,13] = "Dirt Ceiling Left"
o.display_description_item[o.display_page_eleven,14] = "Dirt Ceiling"
o.display_description_item[o.display_page_eleven,15] = "Dirt Ceiling Right"
o.display_description_item[o.display_page_eleven,16] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,17] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,18] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,19] = "Unknown Tile"
