///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Short Hand Alias For Each Page
o.display_page_one = 0
o.display_page_two = 1
o.display_page_three = 2
o.display_page_four  = 3
o.display_page_five  = 4
o.display_page_six   = 5
o.display_page_seven = 6
o.display_page_eight = 7
o.display_page_nine  = 8
o.display_page_ten  = 9
o.display_page_max = 9

//Page Descriptions
o.display_page_description[0] = "Plataformas"
o.display_page_description[1] = "Grama/Terra"
o.display_page_description[2] = "Rampas"
o.display_page_description[3] = "Plataformas"
o.display_page_description[4] = "Decoração"
o.display_page_description[5] = "Pedregulhos"
o.display_page_description[6] = "Neve"
o.display_page_description[7] = "Templo 1"
o.display_page_description[8] = "Templo 2"
o.display_page_description[9] = "Interior"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Pedra Plana 1"
o.display_description_item[o.display_page_one,1] = "Borda do Penhasco Plano - Esquerda"
o.display_description_item[o.display_page_one,2] = "Borda do Penhasco Plano - Direita"
o.display_description_item[o.display_page_one,3] = "Parede de Pedra Plana 1"
o.display_description_item[o.display_page_one,4] = "Parede de Pedra Plana 2"
o.display_description_item[o.display_page_one,5] = "Borda da Viga de Madeira - Esquerda"
o.display_description_item[o.display_page_one,6] = "Viga de Madeira"
o.display_description_item[o.display_page_one,7] = "Borda da Viga de Madeira - Direita"
o.display_description_item[o.display_page_one,8] = "Talo de Bambu - Grande"
o.display_description_item[o.display_page_one,9] = "Talo de Bambu - Pequeno"
o.display_description_item[o.display_page_one,10] = "Talos de Bambu - Fino"
o.display_description_item[o.display_page_one,11] = "Talo de Bambu - Amarelo e Grande"
o.display_description_item[o.display_page_one,12] = "Talo de Bambu - Amarelo e Fino"
o.display_description_item[o.display_page_one,13] = "Talo de Bambu - Plataforma"
o.display_description_item[o.display_page_one,14] = "Talo de Bambu - Plataforma Amarela"
o.display_description_item[o.display_page_one,15] = "Talo de Bambu - Plataforma Pequena"
o.display_description_item[o.display_page_one,16] = "Talo de Bambu - Plataforma Pequena e Amarela"
o.display_description_item[o.display_page_one,17] = "Grama da Montanha"
o.display_description_item[o.display_page_one,18] = "Terra da Montanha - Largo"
o.display_description_item[o.display_page_one,19] = "Terra da Montanha - Pequeno"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Grama da Montanha - Borda Exposta Direita"
o.display_description_item[o.display_page_two,1] = "Grama da Montanha - Parede Exposta Esquerda"
o.display_description_item[o.display_page_two,2] = "Grama da Montanha - Borda Exposta Esquerda"
o.display_description_item[o.display_page_two,3] = "Grama da Montanha - Parede Exposta Direita"
o.display_description_item[o.display_page_two,4] = "Grama da Montanha - De Cabeça para Baixo"
o.display_description_item[o.display_page_two,5] = "Grama da Montanha - Peça de Canto Esquerdo"
o.display_description_item[o.display_page_two,6] = "Grama da Montanha - Parede de Grama Esquerdo"
o.display_description_item[o.display_page_two,7] = "Grama da Montanha - Borda de Grama Direita"
o.display_description_item[o.display_page_two,8] = "Grama da Montanha - Peça de Canto Direito"
o.display_description_item[o.display_page_two,9] = "Grama da Montanha - Parede de Grama Direito"
o.display_description_item[o.display_page_two,10] = "Grama da Montanha - Borda de Grama Esquerdo"
o.display_description_item[o.display_page_two,11] = "Grama da Montanha - Borda de Grama de Cabeça Para Baixo"
o.display_description_item[o.display_page_two,12] = "Grama da Montanha - Borda de Grama de Cabeça Para Baixo"
o.display_description_item[o.display_page_two,13] = "Espinhos Rochosos 1"
o.display_description_item[o.display_page_two,14] = "Espinhos Rochosos 2"
o.display_description_item[o.display_page_two,15] = "Espinhos Rochosos 3"
o.display_description_item[o.display_page_two,16] = "Espinhos Rochosos 4"
o.display_description_item[o.display_page_two,17] = "Escada"
o.display_description_item[o.display_page_two,18] = "Barra Suspensa de Madeira 1"
o.display_description_item[o.display_page_two,19] = "Barra Suspensa de Madeira 2"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Rampa Pequena - 1"
o.display_description_item[o.display_page_three,1] = "Rampa Pequena - 2"
o.display_description_item[o.display_page_three,2] = "Rampa Pequena - 3"
o.display_description_item[o.display_page_three,3] = "Rampa Pequena - 4"
o.display_description_item[o.display_page_three,4] = "Loop de Rosquinha Rochosa - Exterior 1"
o.display_description_item[o.display_page_three,5] = "Loop de Rosquinha Rochosa - Exterior 2"
o.display_description_item[o.display_page_three,6] = "Barra Suspensa 2"
o.display_description_item[o.display_page_three,7] = "Loop de Rosquinha Rochosa - Interior 1"
o.display_description_item[o.display_page_three,8] = "Loop de Rosquinha Rochosa - Interior 2"
o.display_description_item[o.display_page_three,9] = "Loop de Rosquinha Rochosa - Interior 3"
o.display_description_item[o.display_page_three,10] = "Loop de Rosquinha Rochosa - Interior 4"
o.display_description_item[o.display_page_three,11] = "Loop de Rosquinha Rochosa - Interior 5"
o.display_description_item[o.display_page_three,12] = "Loop de Rosquinha Rochosa - Interior 6"
o.display_description_item[o.display_page_three,13] = "Peça do Loop Gramado 1"
o.display_description_item[o.display_page_three,14] = "Peça do Loop Gramado 2"
o.display_description_item[o.display_page_three,15] = "Peça do Loop Gramado 3"
o.display_description_item[o.display_page_three,16] = "Peça do Loop Gramado 4"
o.display_description_item[o.display_page_three,17] = "Peça Longa de Gramado Inclinado 1"
o.display_description_item[o.display_page_three,18] = "Peça Longa de Gramado Inclinado 2"
o.display_description_item[o.display_page_three,19] = "Plataforma Chão-Sobre-Chão Rochoso"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Rocha em Declive"
o.display_description_item[o.display_page_four,1] = "Rocha em Aclive"
o.display_description_item[o.display_page_four,2] = "Grama em Declive"
o.display_description_item[o.display_page_four,3] = "Grama em Aclive"
o.display_description_item[o.display_page_four,4] = "Declive - Raso 3"
o.display_description_item[o.display_page_four,5] = "Superfície Plana 1"
o.display_description_item[o.display_page_four,6] = "Declive - Raso 4"
o.display_description_item[o.display_page_four,7] = "Plataforma Flutuante 1"
o.display_description_item[o.display_page_four,8] = "Plataforma Flutuante 2"
o.display_description_item[o.display_page_four,9] = "Plataforma Flutuante 3"
o.display_description_item[o.display_page_four,10] = "Plataforma Flutuante 4"
o.display_description_item[o.display_page_four,11] = "Plataforma Flutuante 5"
o.display_description_item[o.display_page_four,12] = "Reversão do Curso da Plataforma"
o.display_description_item[o.display_page_four,13] = "Peça de Canto da Máscara de Pedra 1"
o.display_description_item[o.display_page_four,14] = "Peça de Canto da Máscara de Pedra 2"
o.display_description_item[o.display_page_four,15] = "Peça de Canto da Máscara de Pedra 3"
o.display_description_item[o.display_page_four,16] = "Peça de Canto da Máscara de Pedra 4"
o.display_description_item[o.display_page_four,17] = "Planta Lanterna Vermelha de Shang Mu"
o.display_description_item[o.display_page_four,18] = "Planta Lanterna Laranja de Shang Mu"
o.display_description_item[o.display_page_four,19] = "Decoração - Objeto Escuro"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Decoração - Pedra 1"
o.display_description_item[o.display_page_five,1] = "Decoração - Pedra 2"
o.display_description_item[o.display_page_five,2] = "Decoração - Pedra 3"
o.display_description_item[o.display_page_five,3] = "Decoração - Pedra 4"
o.display_description_item[o.display_page_five,4] = "Decoração - Pedra 5"
o.display_description_item[o.display_page_five,5] = "Decoração - Parede de Pedra 1"
o.display_description_item[o.display_page_five,6] = "Decoração - Parede de Pedra 2"
o.display_description_item[o.display_page_five,7] = "Decoração - Máscara de Pedra - Horizontal"
o.display_description_item[o.display_page_five,8] = "Decoração - Máscara de Pedra - Vertical"
o.display_description_item[o.display_page_five,9] = "Decoração - Posto da Ponte"
o.display_description_item[o.display_page_five,10] = "Decoração - Peça da Ponte"
o.display_description_item[o.display_page_five,11] = "Decoração - Árvore 1"
o.display_description_item[o.display_page_five,12] = "Decoração - Grama"
o.display_description_item[o.display_page_five,13] = "Decoração - Máscara de Pedra - Alternativo"
o.display_description_item[o.display_page_five,14] = "Decoração - Flor do Bambu"
o.display_description_item[o.display_page_five,15] = "Decoração - Talo de Bambu"
o.display_description_item[o.display_page_five,16] = "Decoração - Árvore 2"
o.display_description_item[o.display_page_five,17] = "Decoração -  Arbusto"
o.display_description_item[o.display_page_five,18] = "Decoração - Galhos de árvore"
o.display_description_item[o.display_page_five,19] = "Talo de Bambu - Parede Grande"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Superfície Rochosa 1"
o.display_description_item[o.display_page_six,1] = "Superfície Rochosa 2"
o.display_description_item[o.display_page_six,2] = "Teto Rochoso 1"
o.display_description_item[o.display_page_six,3] = "Teto Rochoso 2"
o.display_description_item[o.display_page_six,4] = "Borda Rochosa 1"
o.display_description_item[o.display_page_six,5] = "Superfície Rochosa 3"
o.display_description_item[o.display_page_six,6] = "Borda Rochosa 2"
o.display_description_item[o.display_page_six,7] = "Rocha Interna 1"
o.display_description_item[o.display_page_six,8] = "Rocha Interna 2"
o.display_description_item[o.display_page_six,9] = "Rocha Interna 3"
o.display_description_item[o.display_page_six,10] = "Parede Rochosa 1"
o.display_description_item[o.display_page_six,11] = "Parede Rochosa 2"
o.display_description_item[o.display_page_six,12] = "Parede Rochosa 3"
o.display_description_item[o.display_page_six,13] = "Rocha Interna 3"
o.display_description_item[o.display_page_six,14] = "Rocha Interna 4"
o.display_description_item[o.display_page_six,15] = "Parede Rochosa 4"
o.display_description_item[o.display_page_six,16] = "Parede Rochosa 5"
o.display_description_item[o.display_page_six,17] = "Teto Rochoso 4"
o.display_description_item[o.display_page_six,18] = "Teto Rochoso 5"
o.display_description_item[o.display_page_six,19] = "Teto Rochoso 6"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Superfície de Neve 1"
o.display_description_item[o.display_page_seven,1] = "Superfície de Neve 2"
o.display_description_item[o.display_page_seven,2] = "Superfície de Neve 3"
o.display_description_item[o.display_page_seven,3] = "Superfície de Neve 4"
o.display_description_item[o.display_page_seven,4] = "Superfície de Neve 5"
o.display_description_item[o.display_page_seven,5] = "Superfície de Neve 6"
o.display_description_item[o.display_page_seven,6] = "Superfície de Neve 7"
o.display_description_item[o.display_page_seven,7] = "Teto de Neve 1"
o.display_description_item[o.display_page_seven,8] = "Teto de Neve 2"
o.display_description_item[o.display_page_seven,9] = "Teto de Neve 3"
o.display_description_item[o.display_page_seven,10] = "Parede de Neve 1"
o.display_description_item[o.display_page_seven,11] = "SParede de Neve 2"
o.display_description_item[o.display_page_seven,12] = "Parede de Neve 3"
o.display_description_item[o.display_page_seven,13] = "Árvore com Neve 1"
o.display_description_item[o.display_page_seven,14] = "Panda de Neve 1"
o.display_description_item[o.display_page_seven,15] = "Panda de Neve 2"
o.display_description_item[o.display_page_seven,16] = "Gato de Neve"
o.display_description_item[o.display_page_seven,17] = "Criança de Neve 1"
o.display_description_item[o.display_page_seven,18] = "Criança de Neve 2"
o.display_description_item[o.display_page_seven,19] = "Criança de Neve 3"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Templo - Fusama 1"
o.display_description_item[o.display_page_eight,1] = "Templo - Fusama 2"
o.display_description_item[o.display_page_eight,2] = "Templo - Fusama 3"
o.display_description_item[o.display_page_eight,3] = "Templo - Fusama 4"
o.display_description_item[o.display_page_eight,4] = "Templo - Fusama 5"
o.display_description_item[o.display_page_eight,5] = "Templo - Fusama 6"
o.display_description_item[o.display_page_eight,6] = "Templo - Parede 1"
o.display_description_item[o.display_page_eight,7] = "Templo - Parede 2"
o.display_description_item[o.display_page_eight,8] = "Templo - Parede 3"
o.display_description_item[o.display_page_eight,9] = "Templo - Parede 4"
o.display_description_item[o.display_page_eight,10] = "Templo - Telhado - Esquerda"
o.display_description_item[o.display_page_eight,11] = "Templo - Telhado - Meio"
o.display_description_item[o.display_page_eight,12] = "Templo - Telhado - Direita"
o.display_description_item[o.display_page_eight,13] = "Templo - Viga"
o.display_description_item[o.display_page_eight,14] = "Templo - Viga - Pequeno"
o.display_description_item[o.display_page_eight,15] = "Templo - Viga - Grande"
o.display_description_item[o.display_page_eight,16] = "Templo - Viga - Canto 1"
o.display_description_item[o.display_page_eight,17] = "Templo - Viga - Canto 2"
o.display_description_item[o.display_page_eight,18] = "Templo - Viga - Canto 3"
o.display_description_item[o.display_page_eight,19] = "Templo - Viga - Canto 4"

//Tile Descriptions (Page 9)
o.display_description_item[o.display_page_nine,0] = "Templo - Torii"
o.display_description_item[o.display_page_nine,1] = "Templo - Telhado Completo"
o.display_description_item[o.display_page_nine,2] = "Templo - Suporte de Lanterna"
o.display_description_item[o.display_page_nine,3] = "Templo - Poste de Luz"
o.display_description_item[o.display_page_nine,4] = "Templo - Indicador"
o.display_description_item[o.display_page_nine,5] = "Templo - Estátua do Terraço"
o.display_description_item[o.display_page_nine,6] = "Templo - Bandeira"
o.display_description_item[o.display_page_nine,7] = "Viga de Madeira - Esquerda"
o.display_description_item[o.display_page_nine,8] = "Viga de Madeira - Meio"
o.display_description_item[o.display_page_nine,9] = "Viga de Madeira - Direitat"
o.display_description_item[o.display_page_nine,10] = "Viga de Madeira - Superior"
o.display_description_item[o.display_page_nine,11] = "Viga de Madeira - Meio"
o.display_description_item[o.display_page_nine,12] = "Viga de Madeira - Inferior"
o.display_description_item[o.display_page_nine,13] = "Tenda"
o.display_description_item[o.display_page_nine,14] = "Cadeira Dobrável"
o.display_description_item[o.display_page_nine,15] = "Marshmallow Torrado em um Palito"
o.display_description_item[o.display_page_nine,16] = "Fogueira - Brasas"
o.display_description_item[o.display_page_nine,17] = "Templo - Banner de Bem-Vindo"
o.display_description_item[o.display_page_nine,18] = "Unknown Tile"
o.display_description_item[o.display_page_nine,19] = "Unknown Tile"

//Tile Descriptions (Page 10)
o.display_description_item[o.display_page_ten,0] = "Estante - Grande"
o.display_description_item[o.display_page_ten,1] = "Estante - Pequeno"
o.display_description_item[o.display_page_ten,2] = "Armário - Esquerda"
o.display_description_item[o.display_page_ten,3] = "Armário - Direita"
o.display_description_item[o.display_page_ten,4] = "Geladeira"
o.display_description_item[o.display_page_ten,5] = "Mesa - Pequeno"
o.display_description_item[o.display_page_ten,6] = "Mesa - Grande"
o.display_description_item[o.display_page_ten,7] = "Lâmpada de Corredor"
o.display_description_item[o.display_page_ten,8] = "Televisão"
o.display_description_item[o.display_page_ten,9] = "Sofá"
o.display_description_item[o.display_page_ten,10] = "Cama"
o.display_description_item[o.display_page_ten,11] = "Fogão"
o.display_description_item[o.display_page_ten,12] = "Cadeira de Madeira"
o.display_description_item[o.display_page_ten,13] = "Armário - Pequeno"
o.display_description_item[o.display_page_ten,14] = "Torradeira"
o.display_description_item[o.display_page_ten,15] = "Curtinas - Grande"
o.display_description_item[o.display_page_ten,16] = "Curtinas - Pequeno"
o.display_description_item[o.display_page_ten,17] = "Relógio de Parede"
o.display_description_item[o.display_page_ten,18] = "Alarme"
o.display_description_item[o.display_page_ten,19] = "Unknown Tile"

  //Tile Descriptions (Page 11)
o.display_description_item[o.display_page_eleven,0] = "Grass Flat Left"
o.display_description_item[o.display_page_eleven,1] = "Grass Flat"
o.display_description_item[o.display_page_eleven,2] = "Grass Flat Right"
o.display_description_item[o.display_page_eleven,3] = "Grass Flat Large"
o.display_description_item[o.display_page_eleven,4] = "Grass Flat Thin"
o.display_description_item[o.display_page_eleven,5] = "Dirt"
o.display_description_item[o.display_page_eleven,6] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,7] = "Dirt Wall Left"
o.display_description_item[o.display_page_eleven,8] = "Dirt"
o.display_description_item[o.display_page_eleven,9] = "Dirt Wall Right"
o.display_description_item[o.display_page_eleven,10] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,11] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,12] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,13] = "Dirt Ceiling Left"
o.display_description_item[o.display_page_eleven,14] = "Dirt Ceiling"
o.display_description_item[o.display_page_eleven,15] = "Dirt Ceiling Right"
o.display_description_item[o.display_page_eleven,16] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,17] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,18] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,19] = "Unknown Tile"
