//Language Array (Pause Menu); 0 = English; 1 = Portuguese; 2 = Polish
lang_gui[0,0] = "Start"
lang_gui[0,1] = "Return"
lang_gui[0,2] = "only"
lang_gui[0,3] = "Carol's Bike"
lang_gui[0,4] = "Hold To Change Character"
lang_gui[0,5] = "Hit     The     Targets!"
lang_gui[0,6] = "Reach     The     Target!"
lang_gui[0,7] = "Defeat     The     Boss!"

lang_gui[1,0] = "COMEÇAR"
lang_gui[1,1] = "Voltar"
lang_gui[1,2] = "somente"
lang_gui[1,3] = "Bicicleta"
lang_gui[1,4] = "Segure para Trocar de Personagem"
lang_gui[1,5] = "Acerte     os     Alvos!!"
lang_gui[1,6] = "Alcance     o     Alvo!"
lang_gui[1,7] = "Derrote     o     Chefe!"

lang_gui[2,0] = "Start"
lang_gui[2,1] = "Wróć"
lang_gui[2,2] = "tylko"
lang_gui[2,3] = "Motocykl"
lang_gui[2,4] = "Przytrzymaj aby Zmienić Postać!"
lang_gui[2,5] = "Zniszcz     cele!"
lang_gui[2,6] = "Dotrzyj     do     celu"
lang_gui[2,7] = "Pokonaj     bossa"
