///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Платформы"
o.display_page_description[1] = "Балки"
o.display_page_description[2] = "Склоны"
o.display_page_description[3] = "Декор 1"
o.display_page_description[4] = "Декор 2"
o.display_page_description[5] = "Декор 3"
o.display_page_description[6] = "Декор 4"
o.display_page_description[7] = "Декор 5"
o.display_page_description[8] = "Обломки"
o.display_page_description[9] = "Ещё 1"
o.display_page_description[10] = "Ещё 2"
o.display_page_description[11] = "Кирпичи"
o.display_page_description[12] = "Ещё 3"
o.display_page_description[13] = "Ещё 4"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Кирпичная Платформа 1"
o.display_description_item[o.display_page_one,1] = "Кирпичная Платформа 2"
o.display_description_item[o.display_page_one,2] = "Кирпичная Стена 1"
o.display_description_item[o.display_page_one,3] = "Кирпичная Стена 2"
o.display_description_item[o.display_page_one,4] = "Кирпичная Стена 3"
o.display_description_item[o.display_page_one,5] = "Кирпичная Стена 4"
o.display_description_item[o.display_page_one,6] = "Кирпичный Блок 1"
o.display_description_item[o.display_page_one,7] = "Кирпичный Блок 2"
o.display_description_item[o.display_page_one,8] = "Кирпичный Блок 3"
o.display_description_item[o.display_page_one,9] = "Красный Кирпич"
o.display_description_item[o.display_page_one,10] = "Синий Кирпич"
o.display_description_item[o.display_page_one,11] = "Перегородка 1"
o.display_description_item[o.display_page_one,12] = "Перегородка 2"
o.display_description_item[o.display_page_one,13] = "Плоская Труба 1"
o.display_description_item[o.display_page_one,14] = "Плоская Труба 2"
o.display_description_item[o.display_page_one,15] = "Плоская Труба 3"
o.display_description_item[o.display_page_one,16] = "Плоская Труба 4"
o.display_description_item[o.display_page_one,17] = "Наконечник Трубы 1"
o.display_description_item[o.display_page_one,18] = "Наконечник Трубы 2"
o.display_description_item[o.display_page_one,19] = "Наконечник Трубы 3"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Строительная Балка - Красная 1"
o.display_description_item[o.display_page_two,1] = "Строительная Балка - Красная 2"
o.display_description_item[o.display_page_two,2] = "Строительная Балка - Жёлтая 1"
o.display_description_item[o.display_page_two,3] = "Строительная Балка - Жёлтая 2"
o.display_description_item[o.display_page_two,4] = "Строительная Балка - Красная 3"
o.display_description_item[o.display_page_two,5] = "Строительная Балка - Красная 4"
o.display_description_item[o.display_page_two,6] = "Строительная Балка - Жёлтая 3"
o.display_description_item[o.display_page_two,7] = "Опорная Балка - Жёлтая 1"
o.display_description_item[o.display_page_two,8] = "Опорная Балка - Жёлтая 2"
o.display_description_item[o.display_page_two,9] = "Опорная Балка - Красная 1"
o.display_description_item[o.display_page_two,10] = "Опорная Балка - Красная 2"
o.display_description_item[o.display_page_two,11] = "Опорная Балка - Красная 3"
o.display_description_item[o.display_page_two,12] = "Опорная Балка - Жёлтая 3"
o.display_description_item[o.display_page_two,13] = "Бетонная Стена - 1"
o.display_description_item[o.display_page_two,14] = "Бетонная Стена - 2"
o.display_description_item[o.display_page_two,15] = "Тротуар - 1"
o.display_description_item[o.display_page_two,16] = "Тротуар - 2"
o.display_description_item[o.display_page_two,17] = "Тротуар - 3"
o.display_description_item[o.display_page_two,18] = "Тротуар - 4"
o.display_description_item[o.display_page_two,19] = "Строительная Балка - Жёлтая 3"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Четверть Трубы 1"
o.display_description_item[o.display_page_three,1] = "Четверть Трубы 2"
o.display_description_item[o.display_page_three,2] = "Четверть Трубы 3"
o.display_description_item[o.display_page_three,3] = "Четверть Трубы 4"
o.display_description_item[o.display_page_three,4] = "Четверть Трубы 1 - Инвертированная"
o.display_description_item[o.display_page_three,5] = "Четверть Трубы 2 - Инвертированная"
o.display_description_item[o.display_page_three,6] = "Парящая Платформа 1"
o.display_description_item[o.display_page_three,7] = "Часть Петли 1"
o.display_description_item[o.display_page_three,8] = "Часть Петли 2"
o.display_description_item[o.display_page_three,9] = "Часть Петли 3"
o.display_description_item[o.display_page_three,10] = "Часть Петли 4"
o.display_description_item[o.display_page_three,11] = "Четверть Трубы 3 - Инвертированная"
o.display_description_item[o.display_page_three,12] = "Четверть Трубы 4 - Инвертированная"
o.display_description_item[o.display_page_three,13] = "Дорога - Склон 1"
o.display_description_item[o.display_page_three,14] = "Дорога - Склон 2"
o.display_description_item[o.display_page_three,15] = "Дорога - Склон 3"
o.display_description_item[o.display_page_three,16] = "Дорога - Склон 4"
o.display_description_item[o.display_page_three,17] = "Дорога - Спуск левый"
o.display_description_item[o.display_page_three,18] = "Дорога - Спуск правый"
o.display_description_item[o.display_page_three,19] = "Парящая Платформа 2"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Окно - Большое"
o.display_description_item[o.display_page_four,1] = "Окно - Малое 1"
o.display_description_item[o.display_page_four,2] = "Окно - Малое 2"
o.display_description_item[o.display_page_four,3] = "Кондиционер 1"
o.display_description_item[o.display_page_four,4] = "Кондиционер 2"
o.display_description_item[o.display_page_four,5] = "Телескоп - Рефлектор"
o.display_description_item[o.display_page_four,6] = "Телескоп - Рефрактор"
o.display_description_item[o.display_page_four,7] = "Декор - Труба - Вертикальный Конектор"
o.display_description_item[o.display_page_four,8] = "Декор - Труба - Горизонтальный Конектор"
o.display_description_item[o.display_page_four,9] = "Декор - Труба - Верхняя"
o.display_description_item[o.display_page_four,10] = "Декор - Труба - Нижняя"
o.display_description_item[o.display_page_four,11] = "Наконечник Электрического столба"
o.display_description_item[o.display_page_four,12] = "Электрический Столб"
o.display_description_item[o.display_page_four,13] = "Зонт"
o.display_description_item[o.display_page_four,14] = "Вывеска Ледяные Кометы Зы-юэ "
o.display_description_item[o.display_page_four,15] = "Коктейль С Мороженым 1"
o.display_description_item[o.display_page_four,16] = "Коктейль С Мороженым 2"
o.display_description_item[o.display_page_four,17] = "Коктейль С Мороженым 3"
o.display_description_item[o.display_page_four,18] = "Тарелка С Морожкным"
o.display_description_item[o.display_page_four,19] = "Банановый Сплит"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Декор - Опорная Балка 1"
o.display_description_item[o.display_page_five,1] = "Декор - Защита рельс"
o.display_description_item[o.display_page_five,2] = "Декор - Тротуар"
o.display_description_item[o.display_page_five,3] = "Декор - Дорога"
o.display_description_item[o.display_page_five,4] = "Декор - Оконная Рама"
o.display_description_item[o.display_page_five,5] = "Декор - Рекламный Щит 1"
o.display_description_item[o.display_page_five,6] = "Декор - Рекламный Щит 2"
o.display_description_item[o.display_page_five,7] = "Декор - Кирпичная Стена 1"
o.display_description_item[o.display_page_five,8] = "Декор - Кирпичная Стена 2"
o.display_description_item[o.display_page_five,9] = "Декор - Кирпичная Стена 3"
o.display_description_item[o.display_page_five,10] = "Декор - Здание 1"
o.display_description_item[o.display_page_five,11] = "Декор - Здание 2"
o.display_description_item[o.display_page_five,12] = "Декор - Водная Башня"
o.display_description_item[o.display_page_five,13] = "Декор - Плакат Starbuster"
o.display_description_item[o.display_page_five,14] = "Декор - Плакат HavocFox"
o.display_description_item[o.display_page_five,15] = "Декор - Реклама 1"
o.display_description_item[o.display_page_five,16] = "Декор - Реклама 2"
o.display_description_item[o.display_page_five,17] = "Декор - Знак Стоп"
o.display_description_item[o.display_page_five,18] = "Декор - Знак Приоритета"
o.display_description_item[o.display_page_five,19] = "Декор - Переход Для Ниндзя"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Мусорный бак"
o.display_description_item[o.display_page_six,1] = "Мусорное ведро"
o.display_description_item[o.display_page_six,2] = "Дорожный Знак East Road"
o.display_description_item[o.display_page_six,3] = "Дорожный Знак North Circle"
o.display_description_item[o.display_page_six,4] = "Дорожный Знак South Drive"
o.display_description_item[o.display_page_six,5] = "Дорожный Знак West Lane"
o.display_description_item[o.display_page_six,6] = "Пустой Дорожный Знак"
o.display_description_item[o.display_page_six,7] = "Стрелка"
o.display_description_item[o.display_page_six,8] = "Табличка Мокрый Пол"
o.display_description_item[o.display_page_six,9] = "Светофор"
o.display_description_item[o.display_page_six,10] = "Уличное Освещение"
o.display_description_item[o.display_page_six,11] = "Фонарный Столб 1"
o.display_description_item[o.display_page_six,12] = "Фонарный Столб 2"
o.display_description_item[o.display_page_six,13] = "Фонарный Столб 3"
o.display_description_item[o.display_page_six,14] = "Куст"
o.display_description_item[o.display_page_six,15] = "Тот Самый Баклажан"
o.display_description_item[o.display_page_six,16] = "Бельевая Верёвка"
o.display_description_item[o.display_page_six,17] = "Дорожный Знак Пешеходный Переход"
o.display_description_item[o.display_page_six,18] = "Дорожный Сигнал Стоп"
o.display_description_item[o.display_page_six,19] = "Мусорная Корзина"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Жёлтая Опорная Балка - Целая 1"
o.display_description_item[o.display_page_seven,1] = "Жёлтая Опорная Балка - Угловая 1"
o.display_description_item[o.display_page_seven,2] = "Жёлтая Опорная Балка - Угловая 2"
o.display_description_item[o.display_page_seven,3] = "Красная Опорная Балка - Угловая 1"
o.display_description_item[o.display_page_seven,4] = "Красная Опорная Балка - Угловая 2"
o.display_description_item[o.display_page_seven,5] = "Опорная Балка - Красная 3"
o.display_description_item[o.display_page_seven,6] = "Жёлтая Опорная Балка - Целая 2"
o.display_description_item[o.display_page_seven,7] = "Жёлтая Опорная Балка - Часть 1"
o.display_description_item[o.display_page_seven,8] = "Жёлтая Опорная Балка - Часть 2"
o.display_description_item[o.display_page_seven,9] = "Жёлтая Опорная Балка - Часть 3"
o.display_description_item[o.display_page_seven,10] = "Жёлтая Опорная Балка - Часть 4"
o.display_description_item[o.display_page_seven,11] = "Жёлтая Опорная Балка - Часть 5"
o.display_description_item[o.display_page_seven,12] = "Жёлтая Опорная Балка - Часть 6"
o.display_description_item[o.display_page_seven,13] = "Строительная Опорная Балка - Боковая"
o.display_description_item[o.display_page_seven,14] = "Дорожный Конус - Большой"
o.display_description_item[o.display_page_seven,15] = "Дорожный Конус - Малый"
o.display_description_item[o.display_page_seven,16] = "Дорожный Конус - 1"
o.display_description_item[o.display_page_seven,17] = "Дорожный Конус - 2"
o.display_description_item[o.display_page_seven,18] = "Дорожный Конус - 3"
o.display_description_item[o.display_page_seven,19] = "Дорожный Конус - 4"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Декор - Труба - Верхняя"
o.display_description_item[o.display_page_eight,1] = "Декор - Труба - Вертикальный Конектор"
o.display_description_item[o.display_page_eight,2] = "Декор - Труба - Нижняя"
o.display_description_item[o.display_page_eight,3] = "Декор - Труба - Горизонтальный Конектор"
o.display_description_item[o.display_page_eight,4] = "Ресторанный Столик"
o.display_description_item[o.display_page_eight,5] = "Большая Полка"
o.display_description_item[o.display_page_eight,6] = "Горизонтальная Труба"
o.display_description_item[o.display_page_eight,7] = "Строительная Балка - Средняя 1"
o.display_description_item[o.display_page_eight,8] = "Строительная Балка - Средняя 2"
o.display_description_item[o.display_page_eight,9] = "Строительная Балка - Средняя 3"
o.display_description_item[o.display_page_eight,10] = "Строительная Балка - Средняя 4"
o.display_description_item[o.display_page_eight,11] = "Декор - Забор"
o.display_description_item[o.display_page_eight,12] = "Строительная Опорная Балка - Малая"
o.display_description_item[o.display_page_eight,13] = "Металлические Шипы - 1"
o.display_description_item[o.display_page_eight,14] = "Металлические Шипы - 2"
o.display_description_item[o.display_page_eight,15] = "Металлические Шипы - 3"
o.display_description_item[o.display_page_eight,16] = "Металлические Шипы - 4"
o.display_description_item[o.display_page_eight,17] = "Лестница 1"
o.display_description_item[o.display_page_eight,18] = "Лестница 2"
o.display_description_item[o.display_page_eight,19] = "Перекладина 1"

//Tile Descriptions (Page 9)
o.display_description_item[o.display_page_nine,0] = "Кирпичная Платформа - Обломки 1"
o.display_description_item[o.display_page_nine,1] = "Кирпичная Платформа - Обломки 2"
o.display_description_item[o.display_page_nine,2] = "Кирпичная Стена - Обломки 1"
o.display_description_item[o.display_page_nine,3] = "Кирпичная Стена - Обломки 2"
o.display_description_item[o.display_page_nine,4] = "Кирпичная Стена - Обломки 3"
o.display_description_item[o.display_page_nine,5] = "Кирпичная Платформа - Обломки 3"
o.display_description_item[o.display_page_nine,6] = "Кирпичная Стена - Обломки 4"
o.display_description_item[o.display_page_nine,7] = "Кирпичная Стена - Обломки 5"
o.display_description_item[o.display_page_nine,8] = "Тротуар - Обломки 1"
o.display_description_item[o.display_page_nine,9] = "Кирпичная Стена - Обломки 6"
o.display_description_item[o.display_page_nine,10] = "Кирпичная Стена - Обломки 7"
o.display_description_item[o.display_page_nine,11] = "Пустой Рекламный Щит - Обломки 1"
o.display_description_item[o.display_page_nine,12] = "Пустой Рекламный Щит - Обломки 2"
o.display_description_item[o.display_page_nine,13] = "Пустой Рекламный Щит - Обломки 3"
o.display_description_item[o.display_page_nine,14] = "Труба - Обломки 1"
o.display_description_item[o.display_page_nine,15] = "Труба - Обломки 2"
o.display_description_item[o.display_page_nine,16] = "Труба - Обломки 3"
o.display_description_item[o.display_page_nine,17] = "Труба - Обломки 4"
o.display_description_item[o.display_page_nine,18] = "Неизвестный Тайл"
o.display_description_item[o.display_page_nine,19] = "Неизвестный Тайл"

//Tile Descriptions (Page 10)
o.display_description_item[o.display_page_ten,0] = "Кирпичная Стена - Доп. 1"
o.display_description_item[o.display_page_ten,1] = "Кирпичная Стена - Доп. 2"
o.display_description_item[o.display_page_ten,2] = "Кирпичная Стена - Доп. 3"
o.display_description_item[o.display_page_ten,3] = "Кирпичная Стена - Доп. 4"
o.display_description_item[o.display_page_ten,4] = "Кирпичная Стена - Доп. 5"
o.display_description_item[o.display_page_ten,5] = "Кирпичная Стена - Доп. 6"
o.display_description_item[o.display_page_ten,6] = "Кирпичная Стена - Доп. 7"
o.display_description_item[o.display_page_ten,7] = "Уголок 1"
o.display_description_item[o.display_page_ten,8] = "Уголок 2"
o.display_description_item[o.display_page_ten,9] = "Уголок 3"
o.display_description_item[o.display_page_ten,10] = "Уголок 4"
o.display_description_item[o.display_page_ten,11] = "Кирпичная Стена - Доп. 8"
o.display_description_item[o.display_page_ten,12] = "Кирпичная Стена - Доп. 9"
o.display_description_item[o.display_page_ten,13] = "Уголок 5"
o.display_description_item[o.display_page_ten,14] = "Уголок 6"
o.display_description_item[o.display_page_ten,15] = "Уголок 7"
o.display_description_item[o.display_page_ten,16] = "Кирпичная Платформа - Левый Край"
o.display_description_item[o.display_page_ten,17] = "Кирпичная Платформа - Серединка"
o.display_description_item[o.display_page_ten,18] = "Кирпичная Платформа - Правый Край"
o.display_description_item[o.display_page_ten,19] = "Кирпичная Стена - Доп. 10"

//Tile Descriptions (Page 11)
o.display_description_item[o.display_page_eleven,0] = "Кирпичная Петля - 1"
o.display_description_item[o.display_page_eleven,1] = "Кирпичная Петля - 2"
o.display_description_item[o.display_page_eleven,2] = "Кирпичная Стена - Доп. 3"
o.display_description_item[o.display_page_eleven,3] = "Кирпичная Стена - Доп. 4"
o.display_description_item[o.display_page_eleven,4] = "Кирпичная Стена - Доп. 5"
o.display_description_item[o.display_page_eleven,5] = "Кирпичная Стена - Доп. 6"
o.display_description_item[o.display_page_eleven,6] = "Кирпичная Стена - Доп. 7"
o.display_description_item[o.display_page_eleven,7] = "Кирпичная Петля - 3"
o.display_description_item[o.display_page_eleven,8] = "Кирпичная Петля - 4"
o.display_description_item[o.display_page_eleven,9] = "Уголок 3"
o.display_description_item[o.display_page_eleven,10] = "Уголок 4"
o.display_description_item[o.display_page_eleven,11] = "Кирпичная Стена - Доп. 8"
o.display_description_item[o.display_page_eleven,12] = "Кирпичная Стена - Доп. 9"
o.display_description_item[o.display_page_eleven,13] = "Уголок 5"
o.display_description_item[o.display_page_eleven,14] = "Уголок 6"
o.display_description_item[o.display_page_eleven,15] = "Уголок 7"
o.display_description_item[o.display_page_eleven,16] = "Кирпичная Платформа - Левый Край"
o.display_description_item[o.display_page_eleven,17] = "Кирпичная Платформа - Серединка"
o.display_description_item[o.display_page_eleven,18] = "Кирпичная Платформа - Правый Край"
o.display_description_item[o.display_page_eleven,19] = "Кирпичная Стена - Доп. 10"

//Tile Descriptions (Page 12)
o.display_description_item[o.display_page_twelve,0] = "Кирпичная Платформа 1"
o.display_description_item[o.display_page_twelve,1] = "Кирпичная Платформа 2"
o.display_description_item[o.display_page_twelve,2] = "Кирпичная Стена 1"
o.display_description_item[o.display_page_twelve,3] = "Кирпичная Стена 2"
o.display_description_item[o.display_page_twelve,4] = "Кирпичная Стена 3"
o.display_description_item[o.display_page_twelve,5] = "Кирпичная Стена 4"
o.display_description_item[o.display_page_twelve,6] = "Кирпичный Блок 1"
o.display_description_item[o.display_page_twelve,7] = "Кирпичный Блок 2"
o.display_description_item[o.display_page_twelve,8] = "Кирпичный Блок 3"
o.display_description_item[o.display_page_twelve,9] = "Красный Кирпич"
o.display_description_item[o.display_page_twelve,10] = "Синий Кирпич"
o.display_description_item[o.display_page_twelve,11] = "Перегородка 1"
o.display_description_item[o.display_page_twelve,12] = "Перегородка 2"
o.display_description_item[o.display_page_twelve,13] = "Плоская Труба 1"
o.display_description_item[o.display_page_twelve,14] = "Плоская Труба 2"
o.display_description_item[o.display_page_twelve,15] = "Плоская Труба 3"
o.display_description_item[o.display_page_twelve,16] = "Плоская Труба 4"
o.display_description_item[o.display_page_twelve,17] = "Наконечник Трубы 1"
o.display_description_item[o.display_page_twelve,18] = "Наконечник Трубы 2"
o.display_description_item[o.display_page_twelve,19] = "Наконечник Трубы 3"

//Tile Descriptions (Page 13)
o.display_description_item[o.display_page_thirteen,0] = "Знак Dragon Road"
o.display_description_item[o.display_page_thirteen,1] = "Знак Pheasant Lane"
o.display_description_item[o.display_page_thirteen,2] = "Знак Fantail Road"
o.display_description_item[o.display_page_thirteen,3] = "Знак Panya Plaza"
o.display_description_item[o.display_page_thirteen,4] = "Знак Fuzhu Lane"
o.display_description_item[o.display_page_thirteen,5] = "Знак Qilin Lane"
o.display_description_item[o.display_page_thirteen,6] = "Знак Phoenix Road"
o.display_description_item[o.display_page_thirteen,7] = "Знак Автострады 1"
o.display_description_item[o.display_page_thirteen,8] = "Знак Автострады 2"
o.display_description_item[o.display_page_thirteen,9] = "Знак Автострады - Опора 1"
o.display_description_item[o.display_page_thirteen,10] = "Знак Автострады - Опора 2"
o.display_description_item[o.display_page_thirteen,11] = "Знак Автострады - Опора 3"
o.display_description_item[o.display_page_thirteen,12] = "Знак Автострады - Опора 4"
o.display_description_item[o.display_page_thirteen,13] = "Храм Дракона - Опорная Балка"
o.display_description_item[o.display_page_thirteen,14] = "Храм Дракона - Лампа"
o.display_description_item[o.display_page_thirteen,15] = "Храм Дракона - Врата"
o.display_description_item[o.display_page_thirteen,16] = "Храм Дракона - Забор"
o.display_description_item[o.display_page_thirteen,17] = "Храм Дракона - Столбик Забора"
o.display_description_item[o.display_page_thirteen,18] = "Росток Бамбука"
o.display_description_item[o.display_page_thirteen,19] = "Картина Фу-шу"

//Tile Descriptions (Page 14)
o.display_description_item[o.display_page_fourteen,0] = "Храм Дракона - Статуя Дракона"
o.display_description_item[o.display_page_fourteen,1] = "Храм Дракона - Статуя Фу-шу"
o.display_description_item[o.display_page_fourteen,2] = "Альт Табличка Ресторана - Суши Пании"
o.display_description_item[o.display_page_fourteen,3] = "Храм Дракона - Фреска Дракона"
o.display_description_item[o.display_page_fourteen,4] = "Суши Бар Для Детей Тимми Туна - Табличка"
o.display_description_item[o.display_page_fourteen,5] = "Табличка - Закрыто"
o.display_description_item[o.display_page_fourteen,6] = "Табличка - Открыто"
o.display_description_item[o.display_page_fourteen,7] = ""
o.display_description_item[o.display_page_fourteen,8] = ""
o.display_description_item[o.display_page_fourteen,9] = ""
o.display_description_item[o.display_page_fourteen,10] = ""
o.display_description_item[o.display_page_fourteen,11] = ""
o.display_description_item[o.display_page_fourteen,12] = ""
o.display_description_item[o.display_page_fourteen,13] = ""
o.display_description_item[o.display_page_fourteen,14] = ""
o.display_description_item[o.display_page_fourteen,15] = ""
o.display_description_item[o.display_page_fourteen,16] = ""
o.display_description_item[o.display_page_fourteen,17] = ""
o.display_description_item[o.display_page_fourteen,18] = ""
o.display_description_item[o.display_page_fourteen,19] = ""
