///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Sand"
o.display_page_description[1] = "Platformen"
o.display_page_description[2] = "Pisten"
o.display_page_description[3] = "Außerhalb"
o.display_page_description[4] = "Landschaft 1"
o.display_page_description[5] = "Landschaft 2"
o.display_page_description[6] = "Extra 1"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Sand - Oberfläche Kante Links"
o.display_description_item[o.display_page_one,1] = "Sand - Oberflächenlayer"
o.display_description_item[o.display_page_one,2] = "Sand - Oberfläche Kante Rechts"
o.display_description_item[o.display_page_one,3] = "Sand - Oberfläche Kante Unten Links"
o.display_description_item[o.display_page_one,4] = "Sand - Oberfläche Layer Invertiert"
o.display_description_item[o.display_page_one,5] = "Sand - Oberfläche Kante Unten Rechts"
o.display_description_item[o.display_page_one,6] = "Sand - Wand Links"
o.display_description_item[o.display_page_one,7] = "Sand - Wand Rechts"
o.display_description_item[o.display_page_one,8] = "Sand - Piste 1"
o.display_description_item[o.display_page_one,9] = "Sand - Piste 2"
o.display_description_item[o.display_page_one,10] = "Sand - Piste 3"
o.display_description_item[o.display_page_one,11] = "Sand - Piste 4"
o.display_description_item[o.display_page_one,12] = "Sandstein Layer"
o.display_description_item[o.display_page_one,13] = "Steinplattform - Kante Links"
o.display_description_item[o.display_page_one,14] = "Steinplattform - Oberfläche"
o.display_description_item[o.display_page_one,15] = "Steinplattform - Kante Rechts"
o.display_description_item[o.display_page_one,16] = "Marmor Oberfläche - Weit"
o.display_description_item[o.display_page_one,17] = "Marmor Oberfläche - Schmal"
o.display_description_item[o.display_page_one,18] = "Marmor Wand - Links"
o.display_description_item[o.display_page_one,19] = "Marmor Wand - Rechts"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Holzschiene - 1"
o.display_description_item[o.display_page_two,1] = "Holzschiene - 2"
o.display_description_item[o.display_page_two,2] = "Holzschiene - 3"
o.display_description_item[o.display_page_two,3] = "Holzschiene - 4"
o.display_description_item[o.display_page_two,4] = "Alter Kuperstützbalken 1"
o.display_description_item[o.display_page_two,5] = "Alter Kuperstützbalken 2"
o.display_description_item[o.display_page_two,6] = "Holzschiene - Flach 1"
o.display_description_item[o.display_page_two,7] = "Sandhügel - Flach Links"
o.display_description_item[o.display_page_two,8] = "Holzstützbalken 1"
o.display_description_item[o.display_page_two,9] = "Holzstützbalken 2"
o.display_description_item[o.display_page_two,10] = "Alter Kuperstützbalken 3"
o.display_description_item[o.display_page_two,11] = "Alter Kuperstützbalken 3"
o.display_description_item[o.display_page_two,12] = "Holzschiene - Flach 2"
o.display_description_item[o.display_page_two,13] = "Sandhügel - Flach Rechts"
o.display_description_item[o.display_page_two,14] = "Stacheln 1"
o.display_description_item[o.display_page_two,15] = "Stacheln 2"
o.display_description_item[o.display_page_two,16] = "Stacheln 3"
o.display_description_item[o.display_page_two,17] = "Stacheln 4"
o.display_description_item[o.display_page_two,18] = "Leiter"
o.display_description_item[o.display_page_two,19] = "Hangbar"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Viertelröhrenstein 1"
o.display_description_item[o.display_page_three,1] = "Viertelröhrenstein 2"
o.display_description_item[o.display_page_three,2] = "Viertelröhrenstein 3"
o.display_description_item[o.display_page_three,3] = "Viertelröhrenstein 4"
o.display_description_item[o.display_page_three,4] = "Sandhügel Links"
o.display_description_item[o.display_page_three,5] = "Sandhügel Rechts"
o.display_description_item[o.display_page_three,6] = "Holzkiste"
o.display_description_item[o.display_page_three,7] = "Schleusenteil 1"
o.display_description_item[o.display_page_three,8] = "Schleusenteil 2"
o.display_description_item[o.display_page_three,9] = "Schleusenteil 3"
o.display_description_item[o.display_page_three,10] = "Schleusenteil 4"
o.display_description_item[o.display_page_three,11] = "Schweb. Plattform - 1"
o.display_description_item[o.display_page_three,12] = "Schweb. Plattform - 2"
o.display_description_item[o.display_page_three,13] = "Holzschleuße 1"
o.display_description_item[o.display_page_three,14] = "Holzschleuße 2"
o.display_description_item[o.display_page_three,15] = "Holzschleuße 3"
o.display_description_item[o.display_page_three,16] = "Holzschleuße 4"
o.display_description_item[o.display_page_three,17] = "Schweb. Plattform 3"
o.display_description_item[o.display_page_three,18] = "Schweb. Plattform 4"
o.display_description_item[o.display_page_three,19] = "Bodenüberplattform"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Holzbalken - Links"
o.display_description_item[o.display_page_four,1] = "Holzbalken - Lang"
o.display_description_item[o.display_page_four,2] = "Holzbalken - Rechts"
o.display_description_item[o.display_page_four,3] = "Holzbalken - Klein"
o.display_description_item[o.display_page_four,4] = "Holzschiene"
o.display_description_item[o.display_page_four,5] = "Holzstütze - Links"
o.display_description_item[o.display_page_four,6] = "Holzstütze - Rechts"
o.display_description_item[o.display_page_four,7] = "Holzstütze - Balken"
o.display_description_item[o.display_page_four,8] = "Holzzaun - Unterteil"
o.display_description_item[o.display_page_four,9] = "Holzzaun - Oberteil"
o.display_description_item[o.display_page_four,10] = "Freie Dusche"
o.display_description_item[o.display_page_four,11] = "Freier Wasserhahn"
o.display_description_item[o.display_page_four,12] = "Straßenlampe"
o.display_description_item[o.display_page_four,13] = "Plumpsklo - Mann"
o.display_description_item[o.display_page_four,14] = "Plumpsklo - Frau"
o.display_description_item[o.display_page_four,15] = "Enges Fenster"
o.display_description_item[o.display_page_four,16] = "Großer Regenschirm"
o.display_description_item[o.display_page_four,17] = "Kleiner Regenschirm"
o.display_description_item[o.display_page_four,18] = "Sandburg - Klein"
o.display_description_item[o.display_page_four,19] = "Sandburg - Groß"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Palme - Stamm"
o.display_description_item[o.display_page_five,1] = "Palme - Blatt Oben-Links"
o.display_description_item[o.display_page_five,2] = "Palme - Blatt Links"
o.display_description_item[o.display_page_five,3] = "Palme - Blatt Unten-Links"
o.display_description_item[o.display_page_five,4] = "Palme - Blatt Oben-Rechts"
o.display_description_item[o.display_page_five,5] = "Palme - Blatt Rechts"
o.display_description_item[o.display_page_five,6] = "Palme - Blatt Unten-Rechts"
o.display_description_item[o.display_page_five,7] = "Schneckenhaus - Groß"
o.display_description_item[o.display_page_five,8] = "Muschel"
o.display_description_item[o.display_page_five,9] = "Schneckenhaus - Klein"
o.display_description_item[o.display_page_five,10] = "Vogelnest"
o.display_description_item[o.display_page_five,11] = "Kokosnuss"
o.display_description_item[o.display_page_five,12] = "Bananen-Cluster"
o.display_description_item[o.display_page_five,13] = "Warnschild: BuoyBuoys"
o.display_description_item[o.display_page_five,14] = "Warnschild: Starke Strömungen"
o.display_description_item[o.display_page_five,15] = "Warnschild: Rutschende Steine"
o.display_description_item[o.display_page_five,16] = "Warnschild: Plötzlicher Abfall"
o.display_description_item[o.display_page_five,17] = "Warnschild: Schildkrötennest"
o.display_description_item[o.display_page_five,18] = "Warnschild: Füttern Verboten"
o.display_description_item[o.display_page_five,19] = "Warnschild: Kein Bademeister"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Klein Stein"
o.display_description_item[o.display_page_six,1] = "Großer Stein - 1"
o.display_description_item[o.display_page_six,2] = "Großer Stein - 2"
o.display_description_item[o.display_page_six,3] = "Großer Stein - 3"
o.display_description_item[o.display_page_six,4] = "Großer Stein - 4"
o.display_description_item[o.display_page_six,5] = "Wildes Grass"
o.display_description_item[o.display_page_six,6] = "Sandhaufen"
o.display_description_item[o.display_page_six,7] = "Fruchtstand"
o.display_description_item[o.display_page_six,8] = "Sonnencremestand"
o.display_description_item[o.display_page_six,9] = "Geschenkstand"
o.display_description_item[o.display_page_six,10] = "Kaffeestand"
o.display_description_item[o.display_page_six,11] = "Ice Cream Stand"
o.display_description_item[o.display_page_six,12] = "Hot Dog Stand"
o.display_description_item[o.display_page_six,13] = "Unknown Tile"
o.display_description_item[o.display_page_six,14] = "Unknown Tile"
o.display_description_item[o.display_page_six,15] = "Unknown Tile"
o.display_description_item[o.display_page_six,16] = "Unknown Tile"
o.display_description_item[o.display_page_six,17] = "Unknown Tile"
o.display_description_item[o.display_page_six,18] = "Unknown Tile"
o.display_description_item[o.display_page_six,19] = "Unknown Tile"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Sandstone Rock"
o.display_description_item[o.display_page_seven,1] = "Sand Flat - Small - 1"
o.display_description_item[o.display_page_seven,2] = "Sand Flat - Small - 2"
o.display_description_item[o.display_page_seven,3] = "Sand Flat - Small - 3"
o.display_description_item[o.display_page_seven,4] = "Sand Flat - Small - 4"
o.display_description_item[o.display_page_seven,5] = "Sand Corner Piece - 1"
o.display_description_item[o.display_page_seven,6] = "Sand Corner Piece - 2"
o.display_description_item[o.display_page_seven,7] = "Sand Corner Piece - 3"
o.display_description_item[o.display_page_seven,8] = "Sand Corner Piece - 4"
o.display_description_item[o.display_page_seven,9] = "Sandstone Rock - Small"
o.display_description_item[o.display_page_seven,10] = "Wooden Rail - Vertical - Large"
o.display_description_item[o.display_page_seven,11] = "Wooden Rail - Vertical - Small"
o.display_description_item[o.display_page_seven,12] = "Empty Sand Tile"
o.display_description_item[o.display_page_seven,13] = "Wooden Support Beam - Small"
o.display_description_item[o.display_page_seven,14] = "Wooden Support Beam - Large"
o.display_description_item[o.display_page_seven,15] = "Construction Beam - Oxidized"
o.display_description_item[o.display_page_seven,16] = "Morning Glory"
o.display_description_item[o.display_page_seven,17] = "Red Camellia Japonica"
o.display_description_item[o.display_page_seven,18] = "Unknown Tile"
o.display_description_item[o.display_page_seven,19] = "Unknown Tile"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Wooden Pier Weathered 1"
o.display_description_item[o.display_page_eight,1] = "Wooden Pier Weathered 2"
o.display_description_item[o.display_page_eight,2] = "Wooden Pier Weathered 3"
o.display_description_item[o.display_page_eight,3] = "Wooden Pier Weathered 4"
o.display_description_item[o.display_page_eight,4] = "Wooden Pier Weathered 5"
o.display_description_item[o.display_page_eight,5] = "Wooden Pier Weathered 6"
o.display_description_item[o.display_page_eight,6] = "Wooden Pier 1"
o.display_description_item[o.display_page_eight,7] = "Wooden Support Beam 1"
o.display_description_item[o.display_page_eight,8] = "Wooden Support Beam 2"
o.display_description_item[o.display_page_eight,9] = "Wooden Support Beam 3"
o.display_description_item[o.display_page_eight,10] = "Wooden Support Beam 4"
o.display_description_item[o.display_page_eight,11] = "Wooden Support Beam 5"
o.display_description_item[o.display_page_eight,12] = "Pier Railings"
o.display_description_item[o.display_page_eight,13] = "Wooden Pier 2"
o.display_description_item[o.display_page_eight,14] = "Wooden Pier 3"
o.display_description_item[o.display_page_eight,15] = "Wooden Pier 4"
o.display_description_item[o.display_page_eight,16] = "Wooden Pier 5"
o.display_description_item[o.display_page_eight,17] = "Unknown Tile"
o.display_description_item[o.display_page_eight,18] = "Unknown Tile"
o.display_description_item[o.display_page_eight,19] = "Lifesaver Post"
