//For calling in Story Mode object only, call BEFORE NPC spawn scripts
//Language Array; 0 = English; 1 = Portuguese; 2 = Polish; 3 = Spanish; 4 = German; 5 = Russian
var lang_num = 1;
//West District NPCs 1
lang_npc[lang_num,0]  = "É! Essas coisinhas tá difícil de levar nos lugar!"  //Clyde
lang_npc[lang_num,1]  = "Por isso meus dente tá tudo quebrado, heh!"         //Clyde
lang_npc[lang_num,2]  = "Com toda essa saudade de casa, senti falta dos trem!" //Bucky
lang_npc[lang_num,3]  = "Me lembra dos dia de emu wrestling!"                //Bucky
lang_npc[lang_num,4]  = "Desculpaa, #Chiasa! Eu estava com fome!"            //Marshmallow
lang_npc[lang_num,5]  = "Eu vou compartilhar com você!"                      //Marshmallow
lang_npc[lang_num,6]  = "Não entendo... a onde foi tudo mundo?"              //Candy
lang_npc[lang_num,7]  = "Bem, caso você não tinha percebido!"                //Allister
lang_npc[lang_num,8]  = "Tem um *tanque* atravessando a cidade agora mesmo!" //Allister
lang_npc[lang_num,9]  = "O que estamos esperando?! Tá na hora da AÇÃO!"      //Jett
lang_npc[lang_num,10] = "Eles *realmente* colocaram uma parede de tijolos?"  //Trip
lang_npc[lang_num,11] = "Grr..."                                             //Axl
lang_npc[lang_num,12] = "Aquele tanque destruiu a Ponte do Leste!"           //Lilac
lang_npc[lang_num,13] = "Não podemos ficar parado aqui..."                   //Lilac
lang_npc[lang_num,14] = "Queria um lanchinho antes da gente sair, mas..."    //Carol
lang_npc[lang_num,15] = "Aqueles barulhos vindo de lá... eu estou bem agora!" //Carol
lang_npc[lang_num,16] = "*barulhos nojentos de guaxinim*"                    //Trash Can
lang_npc[lang_num,17] = "Ou jovem! Me deixa comer um muffler fresco em paz!" //Trash Can
lang_npc[lang_num,18] = "O lanche dessa senhorita são estranhos! Eu comi um..." //Libbie Dark
lang_npc[lang_num,19] = "É uma nuvem pequenina apareceu acima da minha cabeça!" //Libbie Dark
lang_npc[lang_num,20] = "Quem disse que você não pode comprar um segundo lanche?" //Tiwi
lang_npc[lang_num,21] = "Quem tem vontade de comer bananas frescas?"         //Harige
lang_npc[lang_num,22] = "É bem comum em Parusa!"                             //Harige
lang_npc[lang_num,23] = "Eu tenho muitas perguntas sobre a comida desse cara!" //Astum
lang_npc[lang_num,24] = "Dedos de Peixe? Salad de Hotdog? BURRITOS AMARGOS?!" //Astum
lang_npc[lang_num,25] = "Eu me sinto perdida! Eu deveria perguntar por direções." //Leela
lang_npc[lang_num,26] = "Mas eu não quero falar com PESSOAS! Ugh!"           //Leela

//West District NPCs 2
lang_npc[lang_num,27] = "Foi um dia longo, estou quase pronto para ir."      //Harige
lang_npc[lang_num,28] = "Algum cliente de último minuto?"                    //Harige
lang_npc[lang_num,29] = "Éee... Exagerei com o sorvete..."                   //Shy
lang_npc[lang_num,30] = "Talvez alguma comida de verdade vai me fazer sentir melhor?" //Shy
lang_npc[lang_num,31] = "Não tenho certeza sobre a nova poção da Milla!"     //Carol
lang_npc[lang_num,32] = "Eu peguei uma e ela vôou para fora da janela!"      //Carol
lang_npc[lang_num,33] = "Uhew! Aqui deve ser um lugar seguro para cochilar..." //
lang_npc[lang_num,34] = "Essa cidade é cansativo de explorar!"               //
lang_npc[lang_num,35] = "Visitar a cidade foi divertido! Ainda bem que vim"  //Iris
lang_npc[lang_num,36] = "Até mesmo vi as garotas lutarem contra tanques!"    //Iris
lang_npc[lang_num,37] = "Este lugar vai fechar em breve, mas eu não me importo." //Azuli
lang_npc[lang_num,38] = "Mais uma olhada nesta vista é tudo que eu preciso!" //Azuli
lang_npc[lang_num,39] = "Essa é a última vez que eu deixo a bazuca em casa"  //Rhyme
lang_npc[lang_num,40] = "Rapaz, estou feliz que aquele tanque se foi!"       //Rhyme
lang_npc[lang_num,41] = "Cê deve tá se perguntando como eu respiro!"         //Bucky
lang_npc[lang_num,42] = "Fácil, não respira! Água é pra fracotes! Hyunk!"    //Bucky
lang_npc[lang_num,43] = "*Suspira* Eu queria outro caminho para casa..."     //Trip
lang_npc[lang_num,44] = "Está cidade não é a mesma desde a guerra."          //Trip
lang_npc[lang_num,45] = "Certeza que tu quer voltar lá, jovem?"              //Clyde
lang_npc[lang_num,46] = "O centro tá tudo quebrado com os traços do tanque!" //Clyde
lang_npc[lang_num,47] = "Por que estamos aqui? O Bouncer está no lado leste!" //Lilac
lang_npc[lang_num,48] = "Está parte da cidade está segura agora!"            //Lilac
lang_npc[lang_num,49] = "Essa lata é assustadora!"                           //Chiasa
lang_npc[lang_num,50] = "Ela tentou comer as luzes do meu scooter!"          //Chiasa
lang_npc[lang_num,51] = "Eca! Faróis não tem o mesmo gosto que tinham antes!!" //Trash Can
lang_npc[lang_num,52] = "Sinto cheiro de oportunidade para um trabalho novo próximo..." //
lang_npc[lang_num,53] = "Tem muitas denúncias de incidentes nos esgotos ultimamente..."   //
lang_npc[lang_num,54] = "Eu quero me meter em problemas no lado leste!"      //Jett
lang_npc[lang_num,55] = "Bem, *eu* vou alimentar as gaivotas eu mesmo!"      //Astum
lang_npc[lang_num,56] = "O que tem de tão ruim sobre eles?!"                 //Astum
lang_npc[lang_num,57] = "Caramba, até o lixo cheira bem aqui!"               //Marshmallow

//West District NPCs 3
lang_npc[lang_num,58] = "Alguma coisa na lixeira tentou comer o meu cabelo!" //Lilac
lang_npc[lang_num,59] = "Mmm! Tem gosto de arame farpado e óleo de motor!"   //Trash can
lang_npc[lang_num,60] = "Estou tentando limpar os grafites de Jett!"         //Marshmallow
lang_npc[lang_num,61] = "Ela desenhou nosso prefeito como um pino de boliche!" //Marshmallow
lang_npc[lang_num,62] = "Bem, está na hora de ir!"                           //Garrett
lang_npc[lang_num,63] = "O ônibus realmente está levando seu tempo!"         //Abby
lang_npc[lang_num,64] = "Será que o monstro comeu o ônibus também?!"         //Abby
lang_npc[lang_num,65] = "Não seja bobo, Abby!"                               //Alexis
lang_npc[lang_num,66] = "Espera..."                                          //Alexis
lang_npc[lang_num,67] = "Oh, querida! Eu disse para a minha filha que ela é adotada!" //Vela
lang_npc[lang_num,68] = "A sua curiosidade superou ela..."                   //Vela
lang_npc[lang_num,69] = "*Gato.exe parou de funcionar*"                      //Chiasa
lang_npc[lang_num,70] = "Alimentar as gaivotas é tão divertido!"             //Astum
lang_npc[lang_num,71] = "Estou fazendo muitas avés amigas!"                  //Astum
lang_npc[lang_num,72] = "Me desculpe se eu não estiver na minha estande no momento!" //Milla
lang_npc[lang_num,73] = "Eu estava com fome!"                                //Milla
lang_npc[lang_num,74] = "Eu desenho caminhos para órbita de terra baixa! (LEO)" //Leo
lang_npc[lang_num,75] = "Mas aqui estou exibindo um menu para porcaria!"     //Leo
lang_npc[lang_num,76] = "Joga outra embalagem de pirulito em mim, menina!"   //Cook
lang_npc[lang_num,77] = "E eu vou mostrar quem é o lixo!"                    //Cook
lang_npc[lang_num,78] = "Joga outro copo plástico em mim, rapaz!"            //Cook
lang_npc[lang_num,79] = "Ainda tá fechado?"                                  //Azuli
lang_npc[lang_num,80] = "Caminhar até o meu trabalho paralelo foi divertido noite passada!" //Cassandre
lang_npc[lang_num,81] = "Desculpa chefe, um sapo comeu o meu carro, NÃO correu bem!" //Cassandre
lang_npc[lang_num,82] = "Bananas frescas e sopa de mariscos!"                //Harige
lang_npc[lang_num,83] = "Eu especializo em pratos de acompanhamentos de Parusa!" //Harige
lang_npc[lang_num,84] = "Sabe, eu acho que nunca fui para Parusa."           //Carol
lang_npc[lang_num,85] = "Mas a comida de lá cheira bem!"                     //Carol
lang_npc[lang_num,86] = "Eu acho que gosto mais das batatas de Milla"        //Carrie
lang_npc[lang_num,87] = "Minha última poção tacou fogo numa lixeira!"        //Carrie

//West District NPCs 4
lang_npc[lang_num,88]  = "That can is lucky #he's out of my #jurisdiction!"   //Bird Guard
lang_npc[lang_num,89]  = "He ate a whole #bicycle..."                         //Bird Guard
lang_npc[lang_num,90]  = "Ehehehehehehe..."                                   //Trash Can
lang_npc[lang_num,91]  = "Psst! Hey, kid! #You want turnip #stocks?"          //Boss
lang_npc[lang_num,92]  = "Not chicken, are #ya?"                              //Boss
lang_npc[lang_num,93]  = "That was some #big news on the #TV last night!"     //Axl
lang_npc[lang_num,94]  = "You do pretty #good, kid!"                          //Axl
lang_npc[lang_num,95]  = "Siopaos are sooo #good..."                          //Carrie
lang_npc[lang_num,96]  = "I missed all the #fun last night!"                  //Rhyme
lang_npc[lang_num,97]  = "I'm so jealous..."                                  //Rhyme
lang_npc[lang_num,98]  = "Can you order me #a cheeseburger, #Milla?"          //Stumpy
lang_npc[lang_num,99]  = "That was a good #lunch break. #Right back to it!"   //Beibo
lang_npc[lang_num,100] = "Ice cream ice #cream, I scream #for ice cream!"     //Milla
lang_npc[lang_num,101] = "AAAAAAAAAAAAA#AAAAAAAAAAAAA#AAAAAAAAAAAAA"          //Milla
lang_npc[lang_num,102] = "Look at her! I #think she's #eating the bowl!"      //Carol
lang_npc[lang_num,103] = "I love and hate #how topsy-turvy #this city is."      //Kusei
lang_npc[lang_num,104] = "Boring 3 months, #way too exciting #for 3 minutes..." //Kusei
lang_npc[lang_num,105] = "You should try #Shuigang! Never #a boring day, aha"   //Millie
lang_npc[lang_num,106] = "Ahaha..."                                             //Millie
lang_npc[lang_num,107] = "Not everyday #your HR office is #eaten by a toad."    //Guage
lang_npc[lang_num,108] = "Welcome to Zao's #Ice Cream #Parlor!"                 //Leo
lang_npc[lang_num,109] = "And no, we're out #of strawberries #today, sorry!"    //Leo
lang_npc[lang_num,110] = "Hey kid, wanna #1v1 at the #arcade?"                  //Flavio
lang_npc[lang_num,111] = "Bet you can't #beat my high #score at Sumo F1!"       //Flavio

//West District NPCs 5
lang_npc[lang_num,112] = "Why did nobody #tell me that can #was sentient!"      //Flavio
lang_npc[lang_num,113] = "It ate my #GameBee..."                                //Flavio
lang_npc[lang_num,114] = "Scram kid! #This is MY scrap!"                        //Trash Can
lang_npc[lang_num,115] = "Mmm! Bet your #hair would taste #good deep-fried!"    //Trash Can
lang_npc[lang_num,116] = "*evil racoon #chewing noises*"                        //Trash Can
lang_npc[lang_num,117] = "Ugh... Guess I #gotta take the #clown bike again."    //Mirdin
lang_npc[lang_num,118] = "*honk honk*"                                          //Mirdin
lang_npc[lang_num,119] = "Still not up for #those turnip #stocks, huh?"         //Boss
lang_npc[lang_num,120] = "Ya gotta ride #this peak, kid! #It's free lunch."     //Boss
lang_npc[lang_num,121] = "Hmm, somebody #keeps smashing #up my car..."          //Garrett
lang_npc[lang_num,122] = "oi, Milla! Me wan #hotcat on a bun, #please, hehe!"   //Pummpy
lang_npc[lang_num,123] = "Dad can we get #seconds?! This is #AWESOME!!!"        //Zeia
lang_npc[lang_num,124] = "Heh, what am I #going to do with #you, Zeia?"         //Guage
lang_npc[lang_num,125] = "Mornin', kids! #School let out #already?"             //Millie
lang_npc[lang_num,126] = "We still need to #check out #Wuzhen Temple..."        //Lilac
lang_npc[lang_num,127] = "Milla, I want to #see the #mountain!"                 //Stumpy
lang_npc[lang_num,128] = "I'll take five #plaintains, #pretty please!"          //Tiwi
lang_npc[lang_num,129] = "Heh, you're keeping #Tri-Kingdom News busy!"          //Axl

//West District NPCs 6
lang_npc[lang_num,130] = "'ey Candy, it'd be #fun to steal this #in broad daylight" //Umi
lang_npc[lang_num,131] = "You can never #have too many #stop signs!"                //Umi
lang_npc[lang_num,132] = "Umi, don't you #commit enough #crimes?!"                  //Candy
lang_npc[lang_num,133] = "I'm taking this #creature with #me!"                      //Neera
lang_npc[lang_num,134] = "He's wanted in #all four kingdoms!"                       //Neera
lang_npc[lang_num,135] = "*evil raccoon #sadness*"                                  //Trash Can
lang_npc[lang_num,136] = "I think I got #lost already... #Hmm."                     //Tanner
lang_npc[lang_num,137] = "oi, Milla! Me wan #hotcat on a bun, #please, hehe!"       //Pummpy
lang_npc[lang_num,138] = "Mornin', kids! #Enjoying the weekend?"                    //Millie
lang_npc[lang_num,139] = "Milla, I want to #see the #beach!"                        //Milla

//West District NPCs 7
lang_npc[lang_num,140] = "Okay, fine, I #won't steal the #stop sign!"               //Umi
lang_npc[lang_num,141] = "I guess our #shack IS getting #kinda crowded..."          //Umi
lang_npc[lang_num,142] = "Now that's more #like it! Let's go #home, Umi."           //Candy
lang_npc[lang_num,143] = "oi, Milla! Me wan #humboiger, #please, hehe!"             //Pumppy
lang_npc[lang_num,144] = "Mmm! This ice #cream is the #best in town!"               //Marshmallow
lang_npc[lang_num,145] = "I want seconds!"                                          //Marshmallow
lang_npc[lang_num,146] = "Oh, my dear... You #bring me true #contentment."          //Bird Guard (Female)
lang_npc[lang_num,147] = "Weh"                                                      //Bird Guard (Male)
lang_npc[lang_num,148] = "Ooh! I love #plantains! I'll #take three."                //
lang_npc[lang_num,149] = "Oh... That's why #you don't feed #the seagulls..."        //Astum
lang_npc[lang_num,150] = "They pecked at #my knees for #HOURS!!! OW!!!"             //Astum
lang_npc[lang_num,151] = "Not nearly #enough!"                                      //Abby
lang_npc[lang_num,152] = "Did we annoy the #babysitter #enough?!"                   //Alexis

