///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Drabiny"
o.display_page_description[1] = "Kolce"
o.display_page_description[2] = "Szkło"
o.display_page_description[3] = "Barierki 1"
o.display_page_description[4] = "Barierki 2"
o.display_page_description[5] = "Sceneria"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Drabina 1"
o.display_description_item[o.display_page_one,1] = "Drabina 2"
o.display_description_item[o.display_page_one,2] = "Drabina 3"
o.display_description_item[o.display_page_one,3] = "Drabina 4"
o.display_description_item[o.display_page_one,4] = "Drabina 5"
o.display_description_item[o.display_page_one,5] = "Drabina 6"
o.display_description_item[o.display_page_one,6] = "Uchwyt 1"
o.display_description_item[o.display_page_one,7] = "Uchwyt 2"
o.display_description_item[o.display_page_one,8] = "Uchwyt 3"
o.display_description_item[o.display_page_one,9] = "Uchwyt 4"
o.display_description_item[o.display_page_one,10] = "Uchwyt 5"
o.display_description_item[o.display_page_one,11] = "Szyna 2"
o.display_description_item[o.display_page_one,12] = "Szyna 3"
o.display_description_item[o.display_page_one,13] = "Szyna 4"
o.display_description_item[o.display_page_one,14] = "Szyna 5"
o.display_description_item[o.display_page_one,15] = "Szyna 6"
o.display_description_item[o.display_page_one,16] = "Szyna 7"
o.display_description_item[o.display_page_one,17] = "Szyna 8"
o.display_description_item[o.display_page_one,18] = "Szyna 9"
o.display_description_item[o.display_page_one,19] = "Szyna 10"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Metalowe Kolce 1"
o.display_description_item[o.display_page_two,1] = "Metalowe Kolce 2"
o.display_description_item[o.display_page_two,2] = "Metalowe Kolce 3"
o.display_description_item[o.display_page_two,3] = "Metalowe Kolce 4"
o.display_description_item[o.display_page_two,4] = "Kolce z Drewna 1"
o.display_description_item[o.display_page_two,5] = "Kolce z Drewna 2"
o.display_description_item[o.display_page_two,6] = "Kolce z Drewna 3"
o.display_description_item[o.display_page_two,7] = "Kolce z Drewna 4"
o.display_description_item[o.display_page_two,8] = "Kamienne Kolce 1"
o.display_description_item[o.display_page_two,9] = "Kamienne Kolce 1"
o.display_description_item[o.display_page_two,10] = "Kamienne Kolce 3"
o.display_description_item[o.display_page_two,11] = "Kamienne Kolce 4"
o.display_description_item[o.display_page_two,12] = "Drewniane Kolce 1"
o.display_description_item[o.display_page_two,13] = "Drewniane Kolce 2"
o.display_description_item[o.display_page_two,14] = "Drewniane Kolce 3"
o.display_description_item[o.display_page_two,15] = "Drewniane Kolce 4"
o.display_description_item[o.display_page_two,16] = "Zębate Kolce 1"
o.display_description_item[o.display_page_two,17] = "Zębate Kolce 2"
o.display_description_item[o.display_page_two,18] = "Zębate Kolce 3"
o.display_description_item[o.display_page_two,19] = "Zębate Kolce 4"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Ciemne Szkło - Duże"
o.display_description_item[o.display_page_three,1] = "Ciemne Szkło - Małe"
o.display_description_item[o.display_page_three,2] = "Ciemne Szkło - Średnie"
o.display_description_item[o.display_page_three,3] = "Ciemne Szkło - Pionowe"
o.display_description_item[o.display_page_three,4] = "Ciemne Szkło - Wąskie"
o.display_description_item[o.display_page_three,5] = "Cześć Szklanej Pętli 1"
o.display_description_item[o.display_page_three,6] = "Cześć Szklanej Pętli 2"
o.display_description_item[o.display_page_three,7] = "Długa Szklana Rampa 1"
o.display_description_item[o.display_page_three,8] = "Długa Szklana Rampa 2"
o.display_description_item[o.display_page_three,9] = "Krótka Szklana Rampa 1"
o.display_description_item[o.display_page_three,10] = "Krótka Szklana Rampa 2"
o.display_description_item[o.display_page_three,11] = "Część Szklanej Pętli 3"
o.display_description_item[o.display_page_three,12] = "Część Szklanej Pętli 4"
o.display_description_item[o.display_page_three,13] = "Długa Szklana Rampa 3"
o.display_description_item[o.display_page_three,14] = "Długa Szklana Rampa 4"
o.display_description_item[o.display_page_three,15] = "Krótka Szklana Rampa 3"
o.display_description_item[o.display_page_three,16] = "Krótka Szklana Rampa 4"
o.display_description_item[o.display_page_three,17] = "Okno - Zielone - Duże"
o.display_description_item[o.display_page_three,18] = "Okno - Zielone - Małe"
o.display_description_item[o.display_page_three,19] = "Okno - Niebieskie - Małe"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Szynowa Pętla - Lewy Górny Róg"
o.display_description_item[o.display_page_four,1] = "Szynowa Pętla - Prawy Górny Róg"
o.display_description_item[o.display_page_four,2] = "Szynowa Rampa 1"
o.display_description_item[o.display_page_four,3] = "Szynowa Rampa 2"
o.display_description_item[o.display_page_four,4] = "Lewa Szynowa Rampa"
o.display_description_item[o.display_page_four,5] = "Płaska Szyna 1"
o.display_description_item[o.display_page_four,6] = "Prawa Szynowa Rampa"
o.display_description_item[o.display_page_four,7] = "Szynowa Pętla - Lewy Dolny Róg"
o.display_description_item[o.display_page_four,8] = "Szynowa Pętla - Prawy Dolny Róg"
o.display_description_item[o.display_page_four,9] = "Szynowa Rampa - Lewa - Czerwona"
o.display_description_item[o.display_page_four,10] = "Szynowa Rampa - Płaska - Czerwona"
o.display_description_item[o.display_page_four,11] = "Szynowa Rampa - Prawa - Czerwona"
o.display_description_item[o.display_page_four,12] = "Płaska Drewniana Szyna"
o.display_description_item[o.display_page_four,13] = "Szynowa Rampa - Lewa - Niebieska"
o.display_description_item[o.display_page_four,14] = "Szynowa Rampa - Płaska - Niebieska"
o.display_description_item[o.display_page_four,15] = "Szynowa Rampa - Prawa - Niebieska"
o.display_description_item[o.display_page_four,16] = "Szynowa Rampa - Prawa - Żółta"
o.display_description_item[o.display_page_four,17] = "Szynowa Rampa - Płaska - Żółta"
o.display_description_item[o.display_page_four,18] = "Szynowa Rampa - Lewa - Żółta"
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Szyna - Czerwona 1"
o.display_description_item[o.display_page_five,1] = "Szyna - Niebieska 1"
o.display_description_item[o.display_page_five,2] = "Szyna - Żółta 1"
o.display_description_item[o.display_page_five,3] = "Szyna - Czerwona 2"
o.display_description_item[o.display_page_five,4] = "Szyna - Niebieska 2"
o.display_description_item[o.display_page_five,5] = "Szyna - Żółta 2"
o.display_description_item[o.display_page_five,6] = ""
o.display_description_item[o.display_page_five,7] = "Szyna - Czerwona 3"
o.display_description_item[o.display_page_five,8] = "Szyna - Czerwona 4"
o.display_description_item[o.display_page_five,9] = "Szyna - Żółta 3"
o.display_description_item[o.display_page_five,10] = "Szyna - Żółta 4"
o.display_description_item[o.display_page_five,11] = "Szyna - Niebieska 3"
o.display_description_item[o.display_page_five,12] = "Szyna - Niebieska 4"
o.display_description_item[o.display_page_five,13] = ""
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Sceneria - Reset Zoomu Kamery"
o.display_description_item[o.display_page_six,1] = "Sceneria - 50% Zoomu Kamery"
o.display_description_item[o.display_page_six,2] = "Sceneria - 25% Zoomu Kamery"
o.display_description_item[o.display_page_six,3] = "Szyna 11"
o.display_description_item[o.display_page_six,4] = "Szyna 12"
o.display_description_item[o.display_page_six,5] = "Znak Drogowy West Lane"
o.display_description_item[o.display_page_six,6] = "Pusty Znak Drogowy"
o.display_description_item[o.display_page_six,7] = "Strzałka"
o.display_description_item[o.display_page_six,8] = "Kosz na Śmieci"
o.display_description_item[o.display_page_six,9] = "Światła Uliczne"
o.display_description_item[o.display_page_six,10] = "Latarnia Uliczna"
o.display_description_item[o.display_page_six,11] = "Słup Lampy 1"
o.display_description_item[o.display_page_six,12] = "Słup Lampy 2"
o.display_description_item[o.display_page_six,13] = "Słup Lampy 3"
o.display_description_item[o.display_page_six,14] = "Krzak"
o.display_description_item[o.display_page_six,15] = "Unikatowy Bakłażan"
o.display_description_item[o.display_page_six,16] = "Linka na Ubrania"
o.display_description_item[o.display_page_six,17] = "Znak Przejścia dla Pieszych"
o.display_description_item[o.display_page_six,18] = "Światła dla Pieszych"
o.display_description_item[o.display_page_six,19] = "Kosz"

