//Language Array (Pause Menu); 0 = English; 1 = Portuguese; 2 = Polish
lang_gui[0,0] = "File Select"
lang_gui[0,1] = "Delete this file?"
lang_gui[0,2] = ""
lang_gui[0,3] = "Confirm"
lang_gui[0,4] = "Cancel"
lang_gui[0,5] = "Return"
lang_gui[0,6] = "Delete"
//Portuguese
lang_gui[1,0] = "Selecionar Arquivo"
lang_gui[1,1] = "Deletar este arquivo?"
lang_gui[1,2] = ""
lang_gui[1,3] = "Confirmar"
lang_gui[1,4] = "Cancelar"
lang_gui[1,5] = "Voltar"
lang_gui[1,6] = "Deletar"
//Polish
lang_gui[2,0] = "Wybór Pliku"
lang_gui[2,1] = "Usunąć ten plik?"
lang_gui[2,2] = ""
lang_gui[2,3] = "Potwierdź"
lang_gui[2,4] = "Anuluj"
lang_gui[2,5] = "Wróć"
lang_gui[2,6] = "Usuń"
