///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Песок"
o.display_page_description[1] = "Платформы"
o.display_page_description[2] = "Склоны"
o.display_page_description[3] = "Снаружи"
o.display_page_description[4] = "Декор 1"
o.display_page_description[5] = "Декор 2"
o.display_page_description[6] = "Ещё1"
o.display_page_description[7] = "Пирс"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Песок - Левый Край"
o.display_description_item[o.display_page_one,1] = "Песок - Поврхность"
o.display_description_item[o.display_page_one,2] = "Песок - Правый Край"
o.display_description_item[o.display_page_one,3] = "Песок - Нижний Левый Край"
o.display_description_item[o.display_page_one,4] = "Песок - Поверхность Инвертированная"
o.display_description_item[o.display_page_one,5] = "Песок - Нижний Правый Край"
o.display_description_item[o.display_page_one,6] = "Песок - Левая Стена"
o.display_description_item[o.display_page_one,7] = "Песок - Правая Стена"
o.display_description_item[o.display_page_one,8] = "Песок - Спуск 1"
o.display_description_item[o.display_page_one,9] = "Песок - Спуск 2"
o.display_description_item[o.display_page_one,10] = "Песок - Спуск 3"
o.display_description_item[o.display_page_one,11] = "Песок - Спуск 4"
o.display_description_item[o.display_page_one,12] = "Слой Песчаника"
o.display_description_item[o.display_page_one,13] = "Каменная Платформа - Левый Край"
o.display_description_item[o.display_page_one,14] = "Каменная Платформа - Поверхность"
o.display_description_item[o.display_page_one,15] = "Каменная Платформа - Правый Край"
o.display_description_item[o.display_page_one,16] = "Мраморная Поверхность - Широкая"
o.display_description_item[o.display_page_one,17] = "Мраморная Поверхность - Узкая"
o.display_description_item[o.display_page_one,18] = "Мраморная Стена - Левая"
o.display_description_item[o.display_page_one,19] = "Мраморная Стена - Правая"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Деревянный Рельсы - 1"
o.display_description_item[o.display_page_two,1] = "Деревянный Рельсы - 2"
o.display_description_item[o.display_page_two,2] = "Деревянный Рельсы - 3"
o.display_description_item[o.display_page_two,3] = "Деревянный Рельсы - 4"
o.display_description_item[o.display_page_two,4] = "Старая Медная Опора 1"
o.display_description_item[o.display_page_two,5] = "Старая Медная Опора 2"
o.display_description_item[o.display_page_two,6] = "Деревянные Рельсы - Подъём 1"
o.display_description_item[o.display_page_two,7] = "Песочный Холм - Подъём Влево"
o.display_description_item[o.display_page_two,8] = "Деревянная Опора 1"
o.display_description_item[o.display_page_two,9] = "Деревянная Опора 2"
o.display_description_item[o.display_page_two,10] = "Старая Медная Опора 3"
o.display_description_item[o.display_page_two,11] = "Старая Медная Опора 4"
o.display_description_item[o.display_page_two,12] = "Деревянные Рельсы - Подъём 2"
o.display_description_item[o.display_page_two,13] = "Песчаный Холм - Подъём Вправо"
o.display_description_item[o.display_page_two,14] = "Шипы 1"
o.display_description_item[o.display_page_two,15] = "Шипы 2"
o.display_description_item[o.display_page_two,16] = "Шипы 3"
o.display_description_item[o.display_page_two,17] = "Шипы 4"
o.display_description_item[o.display_page_two,18] = "Лестница"
o.display_description_item[o.display_page_two,19] = "Перекладина"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Четвертинка Каменной Рампы 1"
o.display_description_item[o.display_page_three,1] = "Четвертинка Каменной Рампы 2"
o.display_description_item[o.display_page_three,2] = "Четвертинка Каменной Рампы 3"
o.display_description_item[o.display_page_three,3] = "Четвертинка Каменной Рампы 4"
o.display_description_item[o.display_page_three,4] = "Песчаный Холм Слева"
o.display_description_item[o.display_page_three,5] = "Песчаный Холм Справа"
o.display_description_item[o.display_page_three,6] = "Деревянный Ящик"
o.display_description_item[o.display_page_three,7] = "Часть Петли 1"
o.display_description_item[o.display_page_three,8] = "Часть Петли 2"
o.display_description_item[o.display_page_three,9] = "Часть Петли 3"
o.display_description_item[o.display_page_three,10] = "Часть Петли 4"
o.display_description_item[o.display_page_three,11] = "Парящая Платформа - 1"
o.display_description_item[o.display_page_three,12] = "Парящая Платформа - 2"
o.display_description_item[o.display_page_three,13] = "Деревянная Петля 1"
o.display_description_item[o.display_page_three,14] = "Деревянная Петля 2"
o.display_description_item[o.display_page_three,15] = "Деревянная Петля 3"
o.display_description_item[o.display_page_three,16] = "Деревянная Петля 4"
o.display_description_item[o.display_page_three,17] = "Парящая Платформа 3"
o.display_description_item[o.display_page_three,18] = "Парящая Платформа 4"
o.display_description_item[o.display_page_three,19] = "Двухъярусная Платформа"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Деревянная Балка - Левая"
o.display_description_item[o.display_page_four,1] = "Деревянная Балка - Длинная"
o.display_description_item[o.display_page_four,2] = "Деревянная Балка - Правая"
o.display_description_item[o.display_page_four,3] = "Деревянная Балка - Малая"
o.display_description_item[o.display_page_four,4] = "Деревянные Рельсы"
o.display_description_item[o.display_page_four,5] = "Деревянная Опора - Левая"
o.display_description_item[o.display_page_four,6] = "Деревянная Опора - Правая"
o.display_description_item[o.display_page_four,7] = "Деревянная Опора - Балка"
o.display_description_item[o.display_page_four,8] = "Деревянный Занавес - Нижняя Часть"
o.display_description_item[o.display_page_four,9] = "Деревянный Занавес - Верхняя Часть"
o.display_description_item[o.display_page_four,10] = "Уличный Душ"
o.display_description_item[o.display_page_four,11] = "Уличный Кран"
o.display_description_item[o.display_page_four,12] = "Уличный Фонарь"
o.display_description_item[o.display_page_four,13] = "Биотуалет - Мужской"
o.display_description_item[o.display_page_four,14] = "Биотуалет - Женский"
o.display_description_item[o.display_page_four,15] = "Узкое Окно"
o.display_description_item[o.display_page_four,16] = "Большой Зонтик"
o.display_description_item[o.display_page_four,17] = "Малый Зонтик"
o.display_description_item[o.display_page_four,18] = "Песочный Замок - Маленький"
o.display_description_item[o.display_page_four,19] = "Песочный Замок - Большой"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Пальма - Свол"
o.display_description_item[o.display_page_five,1] = "Пальма - Верхний Левый Лист"
o.display_description_item[o.display_page_five,2] = "Пальма - Левый Лист"
o.display_description_item[o.display_page_five,3] = "Пальма - Нижний Левый Лист"
o.display_description_item[o.display_page_five,4] = "Пальма - Верхний Правый Лист"
o.display_description_item[o.display_page_five,5] = "Пальма - Правый Лист"
o.display_description_item[o.display_page_five,6] = "Пальма - Нижний Правый Лист"
o.display_description_item[o.display_page_five,7] = "Ракушка - Большая"
o.display_description_item[o.display_page_five,8] = "Морская Ракушка"
o.display_description_item[o.display_page_five,9] = "Ракушка - Малая"
o.display_description_item[o.display_page_five,10] = "Птичье Гнездо С Яйцами"
o.display_description_item[o.display_page_five,11] = "Кокос"
o.display_description_item[o.display_page_five,12] = "Связка Бананов"
o.display_description_item[o.display_page_five,13] = "Предупреждающий Знак: Бойо-бойо"
o.display_description_item[o.display_page_five,14] = "Предупреждающий Знак: Сильное Течение"
o.display_description_item[o.display_page_five,15] = "Предупреждающий Знак: Скользкие Камни"
o.display_description_item[o.display_page_five,16] = "Предупреждающий Знак: Не Упадите"
o.display_description_item[o.display_page_five,17] = "Предупреждающий Знак: Гнездо Морской Черепахи"
o.display_description_item[o.display_page_five,18] = "Предупреждающий Знак: Чаек Не Кормить"
o.display_description_item[o.display_page_five,19] = "Предупреждающий Знак: Спасатель Не Дежжурит"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Малый Камень"
o.display_description_item[o.display_page_six,1] = "Большой Камень - 1"
o.display_description_item[o.display_page_six,2] = "Большой Камень - 2"
o.display_description_item[o.display_page_six,3] = "Большой Камень - 3"
o.display_description_item[o.display_page_six,4] = "Большой Камень - 4"
o.display_description_item[o.display_page_six,5] = "Дикая Трава"
o.display_description_item[o.display_page_six,6] = "Куча Песка"
o.display_description_item[o.display_page_six,7] = "Стойка С Фруктами"
o.display_description_item[o.display_page_six,8] = "Стойка С Кремами От Солнца"
o.display_description_item[o.display_page_six,9] = "Стойка Магазина С Подарками"
o.display_description_item[o.display_page_six,10] = "Стойка С Коффе"
o.display_description_item[o.display_page_six,11] = "Стойка С Мороженым"
o.display_description_item[o.display_page_six,12] = "Стойка С Хот-догами"
o.display_description_item[o.display_page_six,13] = "Unknown Tile"
o.display_description_item[o.display_page_six,14] = "Unknown Tile"
o.display_description_item[o.display_page_six,15] = "Unknown Tile"
o.display_description_item[o.display_page_six,16] = "Unknown Tile"
o.display_description_item[o.display_page_six,17] = "Unknown Tile"
o.display_description_item[o.display_page_six,18] = "Unknown Tile"
o.display_description_item[o.display_page_six,19] = "Unknown Tile"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Песчаник"
o.display_description_item[o.display_page_seven,1] = "Плоский Песок - Мелкий - 1"
o.display_description_item[o.display_page_seven,2] = "Плоский Песок - Мелкий - 2"
o.display_description_item[o.display_page_seven,3] = "Плоский Песок - Мелкий - 3"
o.display_description_item[o.display_page_seven,4] = "Плоский Песок - Мелкий - 4"
o.display_description_item[o.display_page_seven,5] = "Песчаный Угол - 1"
o.display_description_item[o.display_page_seven,6] = "Песчаный Угол - 2"
o.display_description_item[o.display_page_seven,7] = "Песчаный Угол - 3"
o.display_description_item[o.display_page_seven,8] = "Песчаный Угол - 4"
o.display_description_item[o.display_page_seven,9] = "Песчаник - Малый"
o.display_description_item[o.display_page_seven,10] = "Деревянные Рельсы - Вертикальные - Большие"
o.display_description_item[o.display_page_seven,11] = "Деревянные Рельсы - Вертикальные - Малые"
o.display_description_item[o.display_page_seven,12] = "Пустой Тайл Песка"
o.display_description_item[o.display_page_seven,13] = "Деревянная Опора - Малая"
o.display_description_item[o.display_page_seven,14] = "Деревянная Опора - Большая"
o.display_description_item[o.display_page_seven,15] = "Строительная Балка - Окисленная"
o.display_description_item[o.display_page_seven,16] = "Слава Утром"
o.display_description_item[o.display_page_seven,17] = "Красная Камелия Японская"
o.display_description_item[o.display_page_seven,18] = "Unknown Tile"
o.display_description_item[o.display_page_seven,19] = "Unknown Tile"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Старый Деревянный Пирс 1"
o.display_description_item[o.display_page_eight,1] = "Старый Деревянный Пирс 2"
o.display_description_item[o.display_page_eight,2] = "Старый Деревянный Пирс 3"
o.display_description_item[o.display_page_eight,3] = "Старый Деревянный Пирс 4"
o.display_description_item[o.display_page_eight,4] = "Старый Деревянный Пирс 5"
o.display_description_item[o.display_page_eight,5] = "Старый Деревянный Пирс 6"
o.display_description_item[o.display_page_eight,6] = "Знак Не Рыбачить"
o.display_description_item[o.display_page_eight,7] = "Деревянная Опора 1"
o.display_description_item[o.display_page_eight,8] = "Деревянная Опора 2"
o.display_description_item[o.display_page_eight,9] = "Деревянная Опора 3"
o.display_description_item[o.display_page_eight,10] = "Деревянная Опора 4"
o.display_description_item[o.display_page_eight,11] = "Деревянная Опора 5"
o.display_description_item[o.display_page_eight,12] = "Перила Для Пирса"
o.display_description_item[o.display_page_eight,13] = "Деревянная Петля 1"
o.display_description_item[o.display_page_eight,14] = "Деревянная Петля 2"
o.display_description_item[o.display_page_eight,15] = "Деревянная Петля 3"
o.display_description_item[o.display_page_eight,16] = "Деревянная Петля 4"
o.display_description_item[o.display_page_eight,17] = "Деревянная Рампа 1"
o.display_description_item[o.display_page_eight,18] = "Деревянная Рампа 2"
o.display_description_item[o.display_page_eight,19] = "Пост Спасателя"

//Tile Descriptions (Page 9)
o.display_description_item[o.display_page_nine,0] = "Деревянный Пирс 1"
o.display_description_item[o.display_page_nine,1] = "Деревянный Пирс 2"
o.display_description_item[o.display_page_nine,2] = "Деревянный Пирс 3"
o.display_description_item[o.display_page_nine,3] = "Деревянный Пирс 4"
o.display_description_item[o.display_page_nine,4] = "Деревянный Пирс 5"
o.display_description_item[o.display_page_nine,5] = "Unknown Tile"
o.display_description_item[o.display_page_nine,6] = "Unknown Tile"
o.display_description_item[o.display_page_nine,7] = "Unknown Tile"
o.display_description_item[o.display_page_nine,8] = "Unknown Tile"
o.display_description_item[o.display_page_nine,9] = "Unknown Tile"
o.display_description_item[o.display_page_nine,10] = "Unknown Tile"
o.display_description_item[o.display_page_nine,11] = "Unknown Tile"
o.display_description_item[o.display_page_nine,12] = "Unknown Tile"
o.display_description_item[o.display_page_nine,13] = "Unknown Tile"
o.display_description_item[o.display_page_nine,14] = "Unknown Tile"
o.display_description_item[o.display_page_nine,15] = "Unknown Tile"
o.display_description_item[o.display_page_nine,16] = "Unknown Tile"
o.display_description_item[o.display_page_nine,17] = "Unknown Tile"
o.display_description_item[o.display_page_nine,18] = "Unknown Tile"
o.display_description_item[o.display_page_nine,19] = "Unknown Tile"
