//For calling in Story Mode object only, call BEFORE NPC spawn scripts
//Language Array; 0 = English; 1 = Portuguese; 2 = Polish; 3 = Spanish; 4 = German; 5 = Russian
var lang_num = 1;

//Temple NPCs 1
lang_npc[lang_num,0] = "Hmm, antes de nós irmos! Um banho de pétalas primeiro! "    //Lilac
lang_npc[lang_num,1] = "É um complemento para o meu cuidado de cabelo!"             //Lilac
lang_npc[lang_num,2] = "Ahaha! Chiasa! Você viu aquele panda mais cedo?!"           //Jett
lang_npc[lang_num,3] = "Aposto que a mãe dele ainda escolhe as roupas dele!"        //Jett
lang_npc[lang_num,4] = "Por favor, me diz que você sorvete de bacon, senhor!"       //Marshmallow
lang_npc[lang_num,5] = "Bem-Vindo ao Templo Shang Mu! Or eu diria isso."            //Leo
lang_npc[lang_num,6] = "ALGUÉM esqueceu de inserir o meu disco de guia!"            //Leo
lang_npc[lang_num,7] = "*Dormitórios estão fechados até ás 6 da manhã para manuntenção*"  //Sign
lang_npc[lang_num,8] = "*Por conta de explosões e destroços #-EVS"                  //Sign
lang_npc[lang_num,9] = "Por favor, procure pelo Bouncer, Por favor!"                //Savvy
lang_npc[lang_num,10] = "Não podemos lidar com *dois* incidentes em uma noite!"     //Savvy
lang_npc[lang_num,11] = "Hmm...alguém fica deixando essas abóboras em todo canto."  //Rhyme
lang_npc[lang_num,12] = "E não estamos em época ainda! Como?"                       //Rhyme
lang_npc[lang_num,13] = "Então... é aqui onde iremos treinar?"                      //Xavier
lang_npc[lang_num,14] = "Nunca soube desse lugar. É tão remoto"                     //Xavier
lang_npc[lang_num,15] = "Você sabia que isso tem 200 anos? É tão ANTIGO!"           //Mei
lang_npc[lang_num,16] = "Wow, essa árvore e tão linda!"                             //Mei
lang_npc[lang_num,17] = "Boa noite! Estou arrumando as coisas antes de ir."         //Harige
lang_npc[lang_num,18] = "Tem algum último pedido?"                                  //Harige
lang_npc[lang_num,19] = "SIM, POR FAVOR!!!"                                         //Chiasa
lang_npc[lang_num,20] = "EU VI QUE VOCÊ TEM NUGGITOS DE FRANGO!!!"                  //Chiasa
lang_npc[lang_num,21] = "Essa água não é tão gostoso quanto parece!"                //Astum
lang_npc[lang_num,22] = "E também fede muito!"                                      //Carol
lang_npc[lang_num,23] = "Eu não sei como a senhorita heroína... Uhm, Oi Lilac!!!"   //Carol
lang_npc[lang_num,24] = "Isto fede!"                                                //Alexis
lang_npc[lang_num,25] = "TINHA que ser um dos garotos, eu sabia!"                   //Alexis
lang_npc[lang_num,26] = "Ah, criança. você também ouve a água?"                     //Ness
lang_npc[lang_num,27] = "Ela leva suas preocupações, como essas rochas."            //Ness
lang_npc[lang_num,28] = "Ooh! Ooh! Isto vai ser uma exposição longa e perfeita!"    //Uny
lang_npc[lang_num,29] = "*click!*"                                                  //Uny
lang_npc[lang_num,30] = "Mas eu apenas queria saber!"                               //Maria
lang_npc[lang_num,31] = "Temos informações de um panda perseguindo um orbe GIGANTE!" //Maria
lang_npc[lang_num,32] = "Perdoe-me, senhorita!"                                     //Beldr
lang_npc[lang_num,33] = "Mas você alguma vez já dormiu?"                            //Beldr

//Temple NPCs 2
lang_npc[lang_num,34] = "Uau, essa foi uma longa noite!"                            //Lilac
lang_npc[lang_num,35] = "Dessa vez, talvez eu vou me juntar com Carol em tirar um cochilo!" //Lilac
lang_npc[lang_num,36] = "Aww! Olha para essa abóborazinha."                         //Jett
lang_npc[lang_num,37] = "Eu quero coloca-lá no lançador de batatas do Marshmallow!" //Jett
lang_npc[lang_num,38] = "Mmm! Isso é cheiro de abóbora?"                            //Marshmallow
lang_npc[lang_num,39] = "Eu Amoooo abóbora!"                                        //Marshmallow
lang_npc[lang_num,40] = "Considere descansar em breve, criança, dormir é vital."    //Dr. Dean
lang_npc[lang_num,41] = "Nenhum inimigo prejudica nossos órgãos mais do que a falta deles." //Dr. Dean
lang_npc[lang_num,42] = "Esse lugar é muito melhor que a cidade barulhenta!"        //Wacky
lang_npc[lang_num,43] = "Este é o meu lugar favorito para um cochilo..."            //Wacky
lang_npc[lang_num,44] = "Oláaa, e bem-vinda ao meu laboratório!"                    //Milla
lang_npc[lang_num,45] = "Aquela explosão não foi eu, promessa de mindinho!"         //Milla
lang_npc[lang_num,46] = "Mmm! Eu precisava disso antes de trabalhar!"               //Tiwi
lang_npc[lang_num,47] = "Uweu! Finalmente consegui!"                                //Iris
lang_npc[lang_num,48] = "É melhor eu não ter esquecido a orientação!"               //Iris
lang_npc[lang_num,49] = "Bom dia é Bom dia, crianças!"                              //Jamie
lang_npc[lang_num,50] = "Se sentindo melhor hoje depois de ter fechado os olhos!"   //Jamie
lang_npc[lang_num,51] = "'Por que não olha em volta? É de graça!' #-Diretor"        //Sign
lang_npc[lang_num,52] = "*rabisco que diz 'é melhor ser!'*"                         //Sign
lang_npc[lang_num,53] = "Ah, maravilha! O fim de semana está próximo!"              //Mei
lang_npc[lang_num,54] = "Mal posso esperar ir fazer body-boarding na praia!"        //Mei
lang_npc[lang_num,55] = "Eí, jovem! Você viu um algum panda-vermelho?"              //Beldr
lang_npc[lang_num,56] = "Estou ouvindo informações dele andando por aí..."          //Beldr
lang_npc[lang_num,57] = "Hehe! Estou tão feliz que estamos indo as aulas."          //Carrie
lang_npc[lang_num,58] = "Mal posso esperar em conhecer todos vocês melhor!"         //Carrie
lang_npc[lang_num,59] = "Olha, apenas me dá carne e batatas..."                     //Leela
lang_npc[lang_num,60] = "Eu vou ter um dia longo a frente."                         //Leela
lang_npc[lang_num,61] = "Dormitório dos estudantes está aberto agora!"              //Sign
lang_npc[lang_num,62] = "Por favor checar os periódos de silêncio postado!"         //Sign
lang_npc[lang_num,63] = "Alguém injetou uma pizza no meu slot de disquete..."       //Leo
lang_npc[lang_num,64] = "E então tocou a minha tela!, Eu tenho um TRACKBALL, criança!" //Leo
lang_npc[lang_num,65] = "Olá, prazer em te conhecer, eu sou o técnico."             //Elric
lang_npc[lang_num,66] = "Eu mantenho os robôs em forma para os treinos!"           //Elric
lang_npc[lang_num,67] = "Será que eu quero gastar mais dinheiro depois de comer tanto?" //Shy
lang_npc[lang_num,68] = "É claro que eu quero!"                                     //Shy
lang_npc[lang_num,69] = "Bom dia, jovens!"                                          //Savvy
lang_npc[lang_num,70] = "Muito obrigada de novo, Lilac, você é uma trabalhadora milagrosa!" //Savvy
lang_npc[lang_num,71] = "Obrigada de novo, Carol! Você fez parecer fácil!"          //Savvy
lang_npc[lang_num,72] = "Obrigadinha, Milla!"                                       //Savvy
lang_npc[lang_num,73] = "Dinamites realmente vêm em pacotes pequenos!"              //Savvy
lang_npc[lang_num,74] = "Olá, gostaria de ter o menu impresso?"                     //Harige
lang_npc[lang_num,75] = "Mal posso esperar em começar o nosso primeiro dia de treino!" //Chiasa
lang_npc[lang_num,76] = "Já me enchi de nuggitos de frango, estou tão pronta!"      //Chiasa
lang_npc[lang_num,77] = "Oh! Essa abóbora estava por aqui esse dia inteiro."        //Astum
lang_npc[lang_num,78] = "É meu agora, eu vou come-lá!."                             //Astum
lang_npc[lang_num,79] = "Estou bem feliz que encontramos o lugar certo!"            //Ryusei
lang_npc[lang_num,80] = "Não acredito que estávamos no edifício errado!"            //Ryusei
lang_npc[lang_num,81] = "Não se preocupa comigo! ainda estou procurando pelo observatório" //Allister
lang_npc[lang_num,82] = "Essa prateleira parece confortável o bastante para dormir!" //Carol
lang_npc[lang_num,83] = "Eu tentar as camas, confia em mim... isso é melhor!"       //Carol
lang_npc[lang_num,84] = "Está água é bem curiosa!"                                  //Ness
lang_npc[lang_num,85] = "Faz cocégas nas minhas nadadeiras, hehe..."                //Ness
lang_npc[lang_num,86] = "Mas eu preciso saber!"                                     //Maria
lang_npc[lang_num,87] = "Temos informações de um panda perseguindo um orbe GIGANTE!" //Maria

//Temple NPCs 3
lang_npc[lang_num,88] = "Zzzzz...zzzzzz...!"                                        //Wacky
lang_npc[lang_num,89] = "Ooh! Eu deveria levar essa coisinha comigo!"               //Milla
lang_npc[lang_num,90] = "Gulp! Está quase na hora de trabalhar de novo! *chomp*"    //Tiwi
lang_npc[lang_num,91] = "Bom dia e cia, jovens!"                                    //Jamie
lang_npc[lang_num,92] = "Se sentindo melhor hoje depois de fechar os olhos!"        //Jamie
lang_npc[lang_num,93] = "Nenhuma gema desse mundo é mais linda que as estrelas!"    //Mei
lang_npc[lang_num,94] = "Robôs selvagens estão mais erráticos nessa hora. Cuidado." //Beldr
lang_npc[lang_num,95] = "Típicol! Ninguém me colocou no modo suspensão... DE NOVO!" //Leo
lang_npc[lang_num,96] = "Olá, prazer em te conhecer, eu sou o técnico."             //Elric
lang_npc[lang_num,97] = "Eu mantenho os robôs em forma para os treinos!"            //Elric
lang_npc[lang_num,98] = "Não são vocês garotas que são cotovias!"                   //Savvy
lang_npc[lang_num,99] = "Aqui está uma missão! Examinaremos seu feedback depois."   //Savvy
lang_npc[lang_num,100] = "Uhew! Talvez eu esteja seguro, por agora..."              //Pumppy
lang_npc[lang_num,101] = "Zzz...bem...vindo...a minha rádio... #Zzz!"               //Maria
lang_npc[lang_num,102] = "Zzz...mesmo canal de mocergo...mesma estação de mocergo..." //Maria

//Temple NPCs 4
lang_npc[lang_num,103] = "Nós deveríamos ir logo, como Savvy tinha dito!"           //Lilac
lang_npc[lang_num,104] = "Ela confiou em nós para inspecionar o Templo Wuzhen!"     //Lilac
lang_npc[lang_num,105] = "Eu sinto que consigo pular sobre a montanha!"             //Wacky
lang_npc[lang_num,106] = "Agora isso que é um banho!"                               //Wacky
lang_npc[lang_num,107] = "Ah! Estou tendo muitos problemas com minhas batatas"      //Milla
lang_npc[lang_num,108] = "Eu queria uma prateleira com poções estáveis, não explosivas!" //Milla
lang_npc[lang_num,109] = "*Milla, poderia desenhar um sorriso em mim hoje?*"        //Stumpy
lang_npc[lang_num,110] = "Espera, você já completou suas aulas hoje?"               //Mei
lang_npc[lang_num,111] = "Mas meu dia só começou... *suspira*"                      //Mei
lang_npc[lang_num,112] = "Quem confia em um cotoco para contar seus feijões?!"      //Leo
lang_npc[lang_num,113] = "Eu estou, tipo, bem aqui!!!"                              //Leo
lang_npc[lang_num,114] = "O trêm pode levar você para as montanhas, também!"        //Savvy
lang_npc[lang_num,115] = "Estudantes do Templo de Wuzhen precisam de você hoje!"    //Savvy
lang_npc[lang_num,116] = "Oi-Oi, Milla!"                                            //Pumppy
lang_npc[lang_num,117] = "Bom dia, estudantes! Quem está faminto?"                  //Harige
lang_npc[lang_num,118] = "Oh, eu acho que você vai amar a nossa culinária de Parusa, senhorita!" //Harige
lang_npc[lang_num,119] = "Não é todo que eu encontro dragões aquáticos por aqui!"   //Harige
lang_npc[lang_num,120] = "Bom dia, Sra. Carol!"                                     //Harige
lang_npc[lang_num,121] = "Ouvi dizer que você gosta bastante dos meus Burgers de sushi! Agradeço!" //Harige
lang_npc[lang_num,122] = "Bom dia, jovemzinha!"                                     //Harige
lang_npc[lang_num,123] = "Posso sugerir o meu especial batata carregada?"           //Harige
lang_npc[lang_num,124] = "Bom dia, estudante! você precisa comer coisas saudáveis por aqui..." //Harige
lang_npc[lang_num,125] = "Treinar é trabalho pesado! Que tal alguns bifes quentes?" //Harige
lang_npc[lang_num,126] = "Bem, eu estou bem empolgado, mas..."                      //Ryusei
lang_npc[lang_num,127] = "É melhor esses robôs não terem facas de VERDADE!!!"       //Ryusei
lang_npc[lang_num,128] = "Oh, isso é tão excitante, Ryu!"                           //Shy
lang_npc[lang_num,129] = "Eles vão deixar a gente treinar com robôs reais!"         //Shy
lang_npc[lang_num,130] = "Isso foi bem divertido! Eu quero quebrar mais robôs!"     //Carol
lang_npc[lang_num,131] = "Eí, Lilac! Isso foi só uma brincadeira, vamos fazer isso de novo." //Carol
lang_npc[lang_num,132] = "Eí, Milla! Você mostrou para aquele grandão quem é o chefão!" //Carol
lang_npc[lang_num,133] = "Mas você me assusta as vezes..."                          //Carol
lang_npc[lang_num,134] = "Há! Olha quem veio da Cidade Boboca!"                     //Carol

//Temple NPCs 5
lang_npc[lang_num,135] = "C'mon, let's go to #the beach! It's #Friday."             //Lilac
lang_npc[lang_num,136] = "This room is nice #too!"                                  //Milla
lang_npc[lang_num,137] = "And um... I didn't #clog your toilet!"                    //Milla
lang_npc[lang_num,138] = "*Milla, did you #get a refund on #that package?*"         //Stumpy
lang_npc[lang_num,139] = "We'll never get #this dump open in #time!"                //Jamie
lang_npc[lang_num,140] = "All these #plugged p-traps #AND explosions?"              //Jamie
lang_npc[lang_num,141] = "You're lucky #you're so cute, #pup!"                      //Jamie
lang_npc[lang_num,142] = "That woulda sent #me sky-high, and #then to court!"       //Jamie
lang_npc[lang_num,143] = "How does a kid #even think I'm a #vending machine?"       //Leo
lang_npc[lang_num,144] = "I'd be rich if I #was pushed into #the snack shop!"       //Leo
lang_npc[lang_num,145] = "Hmm, I did send #the C4 to the #right address?"           //Elric
lang_npc[lang_num,146] = "Ehh... It'll turn #up later."                             //Elric
lang_npc[lang_num,147] = "Well... Keeping up #hasn't been #easy, I'll say."         //Ryusei
lang_npc[lang_num,148] = "But I was not #prepared for #robots with guns"            //Ryusei
lang_npc[lang_num,149] = "So, what do you #think of our #training so far?"          //Shy
lang_npc[lang_num,150] = "Beating up #robots is so #much fun!"                      //Shy
lang_npc[lang_num,151] = "Mmm... So close to #that lead..."                         //Maria
lang_npc[lang_num,152] = "I'm so ready for #a sun nap at the #beach."               //Carol

//Temple NPCs 6
lang_npc[lang_num,153] = "C'mon, let's get #back to the bay!"                       //Lilac
lang_npc[lang_num,154] = "Oh, Ms. Panini, #we're going to #have so much fun"        //Milla
lang_npc[lang_num,155] = "Fish are so cool!"                                        //Milla
lang_npc[lang_num,156] = "*Phew, I'm glad #you found me, #Milla!*"                  //Stumpy
lang_npc[lang_num,157] = "*That shark #sent me flying!*"                            //Stumpy
lang_npc[lang_num,158] = "C'mon! What's #wrong with that #snack machine?!"          //Astum
lang_npc[lang_num,159] = "I put my dollar #in, but no donuts #came out!"            //Astum
lang_npc[lang_num,160] = "Hoi, Milla! Can #has candy?"                              //Pumppy
lang_npc[lang_num,161] = "Well, I'll be! I #love you too, #Shy..."                  //Ryusei
lang_npc[lang_num,162] = "...Can a guy ask #for a tougher #girlfriend?"             //Ryusei
lang_npc[lang_num,163] = "Tada! It's a ring #I got out of the #bubblegum slots!"    //Shy
lang_npc[lang_num,164] = "Only had to beat #it outta mutant #toad's maw!"           //Shy
lang_npc[lang_num,165] = "Mmm... So close to #that lead..."                         //Maria
lang_npc[lang_num,166] = "I don't know, #maybe you scare #them, heh heh..."         //Abby
lang_npc[lang_num,167] = "You know, Alexis. #Why do they keep #letting us in?"      //Alexis
lang_npc[lang_num,168] = "We're not even #old enough to be #students here!"         //Alexis
lang_npc[lang_num,169] = "That's right, the #mission at the #bay!"                  //Carol
lang_npc[lang_num,170] = "Sorry, I forgot #something, #haha..."                     //Carol
