///Shang Mu Temple Tile Definition Table
gml_pragma("forcedinline")
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Plataformas"
o.display_page_description[1] = "Encanamento"
o.display_page_description[2] = "Decoração"
o.display_page_description[3] = "Grama/Terra"
o.display_page_description[4] = "Extras"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Plataforma de Tijolos - Rachado 1"
o.display_description_item[o.display_page_one,1] = "Plataforma de Tijolos - Rachado 2"
o.display_description_item[o.display_page_one,2] = "Plataforma de Tijolos - Rachado 3"
o.display_description_item[o.display_page_one,3] = "Parede de Tijolos - Rachado 1"
o.display_description_item[o.display_page_one,4] = "Parede de Tijolos - Rachado 2"
o.display_description_item[o.display_page_one,5] = "Parede de Tijolos - Rachado 3"
o.display_description_item[o.display_page_one,6] = "Parede de Tijolos 1"
o.display_description_item[o.display_page_one,7] = "Parede de Tijolos 2"
o.display_description_item[o.display_page_one,8] = "Parede de Tijolos 3"
o.display_description_item[o.display_page_one,9] = "Parede de Tijolos 4"
o.display_description_item[o.display_page_one,10] = "Parede de Tijolos 5"
o.display_description_item[o.display_page_one,11] = "Tijolo Pequeno 1"
o.display_description_item[o.display_page_one,12] = "Tijolo Pequeno 2"
o.display_description_item[o.display_page_one,13] = "Cano Pequeno 1"
o.display_description_item[o.display_page_one,14] = "Cano Grande 1"
o.display_description_item[o.display_page_one,15] = "Cano Grande 2"
o.display_description_item[o.display_page_one,16] = "Cano Grande 3"
o.display_description_item[o.display_page_one,17] = "Conector do Cano 1"
o.display_description_item[o.display_page_one,18] = "Conector do Cano 2"
o.display_description_item[o.display_page_one,19] = "Conector do Cano 3"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Parede do Esgoto 1"
o.display_description_item[o.display_page_two,1] = "Parede do Esgoto 2"
o.display_description_item[o.display_page_two,2] = "Decoração - Esgoto 1"
o.display_description_item[o.display_page_two,3] = "Decoração - Esgoto 2"
o.display_description_item[o.display_page_two,4] = "Decoração - Esgoto 3"
o.display_description_item[o.display_page_two,5] = "Decoração - Esgoto 4"
o.display_description_item[o.display_page_two,6] = "Decoração - Esgoto 5"
o.display_description_item[o.display_page_two,7] = "Cano Inclinado 1"
o.display_description_item[o.display_page_two,8] = "Cano Inclinado 2"
o.display_description_item[o.display_page_two,9] = "Cano Inclinado 3"
o.display_description_item[o.display_page_two,10] = "Cano Inclinado 4"
o.display_description_item[o.display_page_two,11] = "Viga de Apoio para Construção 1"
o.display_description_item[o.display_page_two,12] = "Viga de Apoio para Construção 2"
o.display_description_item[o.display_page_two,13] = "Espinhos 1"
o.display_description_item[o.display_page_two,14] = "Espinhos 2"
o.display_description_item[o.display_page_two,15] = "Espinhos 3"
o.display_description_item[o.display_page_two,16] = "Espinhos 4"
o.display_description_item[o.display_page_two,17] = "Escada 1"
o.display_description_item[o.display_page_two,18] = "Escada 2"
o.display_description_item[o.display_page_two,19] = "Barra Suspensa 1"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Janela - Verde - Grande"
o.display_description_item[o.display_page_three,1] = "Janela - Verde - Pequeno"
o.display_description_item[o.display_page_three,2] = "Janela - Azul - Pequeno"
o.display_description_item[o.display_page_three,3] = "Viga de Apoio 1"
o.display_description_item[o.display_page_three,4] = "Viga de Apoio 2"
o.display_description_item[o.display_page_three,5] = "Viga de Apoio 3"
o.display_description_item[o.display_page_three,6] = "Viga de Apoio Inclinado - Completo"
o.display_description_item[o.display_page_three,7] = "Viga de Apoio Inclinado - Parte Inferior"
o.display_description_item[o.display_page_three,8] = "Viga de Apoio Inclinado - Parte do Meio"
o.display_description_item[o.display_page_three,9] = "Viga de Apoio Inclinado - Parte Superior"
o.display_description_item[o.display_page_three,10] = "Viga de Apoio Inclinado - Parte Inferior"
o.display_description_item[o.display_page_three,11] = "Viga de Apoio Inclinado - Parte do Meio"
o.display_description_item[o.display_page_three,12] = "Viga de Apoio Inclinado - Parte Superior"
o.display_description_item[o.display_page_three,13] = "Peça do Canto - 1"
o.display_description_item[o.display_page_three,14] = "Peça do Canto - 2"
o.display_description_item[o.display_page_three,15] = "Peça do Canto - 3"
o.display_description_item[o.display_page_three,16] = "Peça do Canto - 4"
o.display_description_item[o.display_page_three,17] = "Peça do Canto - 5"
o.display_description_item[o.display_page_three,18] = "Peça do Canto - 6"
o.display_description_item[o.display_page_three,19] = "Peça do Canto - Parte Central"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Grama - Borda Esquerda"
o.display_description_item[o.display_page_four,1] = "Grama - Parte Superior"
o.display_description_item[o.display_page_four,2] = "Grama - Borda Direita"
o.display_description_item[o.display_page_four,3] = "Declive Gramado 1"
o.display_description_item[o.display_page_four,4] = "Declive Gramado 2"
o.display_description_item[o.display_page_four,5] = "Declive Gramado 3"
o.display_description_item[o.display_page_four,6] = "Decoração - Grama"
o.display_description_item[o.display_page_four,7] = "Terra - Parede da Esquerda"
o.display_description_item[o.display_page_four,8] = "Terra - Pequeno"
o.display_description_item[o.display_page_four,9] = "Terra- Parede da Direita"
o.display_description_item[o.display_page_four,10] = "Grama - Plano - Grande"
o.display_description_item[o.display_page_four,11] = "Grama - Irregular"
o.display_description_item[o.display_page_four,12] = "Grama - Plano - Pequeno"
o.display_description_item[o.display_page_four,13] = "Grama - Borda - Esquerda"
o.display_description_item[o.display_page_four,14] = "Grama - Parte Inferior"
o.display_description_item[o.display_page_four,15] = "Grama - Borda Direita"
o.display_description_item[o.display_page_four,16] = "Terra Grande"
o.display_description_item[o.display_page_four,17] = "Declive de Terra 1"
o.display_description_item[o.display_page_four,18] = "Declive de Terra 2"
o.display_description_item[o.display_page_four,19] = "Declive de Terra 3"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Loop Circular 1"
o.display_description_item[o.display_page_five,1] = "Loop Circular 2"
o.display_description_item[o.display_page_five,2] = "Loop de Cano 1"
o.display_description_item[o.display_page_five,3] = "Loop de Cano 2"
o.display_description_item[o.display_page_five,4] = "Bloco de Terra Plano - Extra 1"
o.display_description_item[o.display_page_five,5] = "Bloco de Terra Plano - Extra 2"
o.display_description_item[o.display_page_five,6] = "Bloco de Terra Plano - Extra 3"
o.display_description_item[o.display_page_five,7] = "Loop Circular 3"
o.display_description_item[o.display_page_five,8] = "Loop Circular 4"
o.display_description_item[o.display_page_five,9] = "Loop de Cano 3"
o.display_description_item[o.display_page_five,10] = "Loop de Cano 4"
o.display_description_item[o.display_page_five,11] = "Bloco de Terra Plano - Extra 4"
o.display_description_item[o.display_page_five,12] = "Bloco de Terra Plano - Extra 5"
o.display_description_item[o.display_page_five,13] = "Parede Limpa 1"
o.display_description_item[o.display_page_five,14] = "Parede Limpa 2"
o.display_description_item[o.display_page_five,15] = "Chão Limpo 1"
o.display_description_item[o.display_page_five,16] = "Parede Limpa 3"
o.display_description_item[o.display_page_five,17] = "Chão Limpo 2"
o.display_description_item[o.display_page_five,18] = "Chão Limpo 3"
o.display_description_item[o.display_page_five,19] = "Parede Limpa 4"

