///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Платформы"
o.display_page_description[1] = "Трубы"
o.display_page_description[2] = "Декор"
o.display_page_description[3] = "Земля"
o.display_page_description[4] = "Ещё"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Кирпичная Платформа - Треснувшая 1"
o.display_description_item[o.display_page_one,1] = "Кирпичная Платформа - Треснувшая 2"
o.display_description_item[o.display_page_one,2] = "Кирпичная Платформа - Треснувшая 3"
o.display_description_item[o.display_page_one,3] = "Кирпрчная Стена - Треснувшая 1"
o.display_description_item[o.display_page_one,4] = "Кирпрчная Стена - Треснувшая 2"
o.display_description_item[o.display_page_one,5] = "Кирпрчная Стена - Треснувшая 3"
o.display_description_item[o.display_page_one,6] = "Кирпрчная Стена 1"
o.display_description_item[o.display_page_one,7] = "Кирпрчная Стена 2"
o.display_description_item[o.display_page_one,8] = "Кирпрчная Стена 3"
o.display_description_item[o.display_page_one,9] = "Кирпрчная Стена 4"
o.display_description_item[o.display_page_one,10] = "Кирпрчная Стена 5"
o.display_description_item[o.display_page_one,11] = "Малый Кирпич 1"
o.display_description_item[o.display_page_one,12] = "Малый Кирпич 2"
o.display_description_item[o.display_page_one,13] = "Малая Труба 1"
o.display_description_item[o.display_page_one,14] = "Большая Труба 1"
o.display_description_item[o.display_page_one,15] = "Большая Труба 2"
o.display_description_item[o.display_page_one,16] = "Большая Труба 3"
o.display_description_item[o.display_page_one,17] = "Соединитель Трубы 1"
o.display_description_item[o.display_page_one,18] = "Соединитель Трубы 2"
o.display_description_item[o.display_page_one,19] = "Соединитель Трубы 3"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Труба - Стена 1"
o.display_description_item[o.display_page_two,1] = "Труба - Стена 2"
o.display_description_item[o.display_page_two,2] = "Декор - Труба 1"
o.display_description_item[o.display_page_two,3] = "Декор - Труба 2"
o.display_description_item[o.display_page_two,4] = "Декор - Труба 3"
o.display_description_item[o.display_page_two,5] = "Декор - Труба 4"
o.display_description_item[o.display_page_two,6] = "Декор - Труба 5"
o.display_description_item[o.display_page_two,7] = "Угловая Труба 1"
o.display_description_item[o.display_page_two,8] = "Угловая Труба 2"
o.display_description_item[o.display_page_two,9] = "Угловая Труба 3"
o.display_description_item[o.display_page_two,10] = "Угловая Труба 4"
o.display_description_item[o.display_page_two,11] = "Строительная Опора 1"
o.display_description_item[o.display_page_two,12] = "Строительная Опора 2"
o.display_description_item[o.display_page_two,13] = "Шипы 1"
o.display_description_item[o.display_page_two,14] = "Шипы 2"
o.display_description_item[o.display_page_two,15] = "Шипы 3"
o.display_description_item[o.display_page_two,16] = "Шипы 4"
o.display_description_item[o.display_page_two,17] = "Лестница 1"
o.display_description_item[o.display_page_two,18] = "Лестница 2"
o.display_description_item[o.display_page_two,19] = "Перекладина 1"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Стеклянное Окно - Зелёное - Большое"
o.display_description_item[o.display_page_three,1] = "Стеклянное Окно - Зелёное - Малое"
o.display_description_item[o.display_page_three,2] = "Стеклянное Окно - Синее - Малое"
o.display_description_item[o.display_page_three,3] = "Опорная Балка 1"
o.display_description_item[o.display_page_three,4] = "Опорная Балка 2"
o.display_description_item[o.display_page_three,5] = "Опорная Балка 3"
o.display_description_item[o.display_page_three,6] = "Угловая Опора - Целая"
o.display_description_item[o.display_page_three,7] = "Угловая Опора - Низ"
o.display_description_item[o.display_page_three,8] = "Угловая Опора - Серединка"
o.display_description_item[o.display_page_three,9] = "Угловая Опора - Верх"
o.display_description_item[o.display_page_three,10] = "Угловая Опора - Низ"
o.display_description_item[o.display_page_three,11] = "Угловая Опора - Серединка"
o.display_description_item[o.display_page_three,12] = "Угловая Опора - Верх"
o.display_description_item[o.display_page_three,13] = "Уголок - 1"
o.display_description_item[o.display_page_three,14] = "Уголок - 2"
o.display_description_item[o.display_page_three,15] = "Уголок - 3"
o.display_description_item[o.display_page_three,16] = "Уголок - 4"
o.display_description_item[o.display_page_three,17] = "Уголок - 5"
o.display_description_item[o.display_page_three,18] = "Уголок - 6"
o.display_description_item[o.display_page_three,19] = "Уголок - Середина"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Трава - Левый Край"
o.display_description_item[o.display_page_four,1] = "Трава - Верх"
o.display_description_item[o.display_page_four,2] = "Трава - Правый Край"
o.display_description_item[o.display_page_four,3] = "Травянистый Спуск 1"
o.display_description_item[o.display_page_four,4] = "Травянистый Спуск 2"
o.display_description_item[o.display_page_four,5] = "Травянистый Спуск 3"
o.display_description_item[o.display_page_four,6] = "Декор - Трава"
o.display_description_item[o.display_page_four,7] = "Земля - Левая Стена"
o.display_description_item[o.display_page_four,8] = "Земля - Малая"
o.display_description_item[o.display_page_four,9] = "Земля - Правая Стена"
o.display_description_item[o.display_page_four,10] = "Трава - Плосская - Большая"
o.display_description_item[o.display_page_four,11] = "Трава - Неровная"
o.display_description_item[o.display_page_four,12] = "Трава - Плоская - Малая"
o.display_description_item[o.display_page_four,13] = "Трава - Левый Край"
o.display_description_item[o.display_page_four,14] = "Трава - Низ"
o.display_description_item[o.display_page_four,15] = "Трава - Правый Край"
o.display_description_item[o.display_page_four,16] = "Земля - Большая"
o.display_description_item[o.display_page_four,17] = "Земляной Спуск 1"
o.display_description_item[o.display_page_four,18] = "Земляной Спуск 2"
o.display_description_item[o.display_page_four,19] = "Земляной Спуск 3"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Петля 1"
o.display_description_item[o.display_page_five,1] = "Петля 2"
o.display_description_item[o.display_page_five,2] = "Петля - Труба 1"
o.display_description_item[o.display_page_five,3] = "Петля - Труба 2"
o.display_description_item[o.display_page_five,4] = "Тайл Плосской Земли - Доп. 1"
o.display_description_item[o.display_page_five,5] = "Тайл Плосской Земли - Доп. 2"
o.display_description_item[o.display_page_five,6] = "Тайл Плосской Земли - Доп. 3"
o.display_description_item[o.display_page_five,7] = "Петля 3"
o.display_description_item[o.display_page_five,8] = "Петля 4"
o.display_description_item[o.display_page_five,9] = "Петля - Труба 3"
o.display_description_item[o.display_page_five,10] = "Петля - Труба 4"
o.display_description_item[o.display_page_five,11] = "Тайл Плосской Земли - Доп. 4"
o.display_description_item[o.display_page_five,12] = "Тайл Плосской Земли - Доп. 5"
o.display_description_item[o.display_page_five,13] = "Чистая Стена 1"
o.display_description_item[o.display_page_five,14] = "Чистая Стена 2"
o.display_description_item[o.display_page_five,15] = "Чистая Стена 1"
o.display_description_item[o.display_page_five,16] = "Чистая Стена 3"
o.display_description_item[o.display_page_five,17] = "Чистая Стена 2"
o.display_description_item[o.display_page_five,18] = "Чистая Стена 3"
o.display_description_item[o.display_page_five,19] = "Чистая Стена 4"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Контейнер Для Переработки"
o.display_description_item[o.display_page_six,1] = "Проезд Для Ниндзя"
o.display_description_item[o.display_page_six,2] = "Дорожный Знак East Road"
o.display_description_item[o.display_page_six,3] = "Дорожный Знак North Circle"
o.display_description_item[o.display_page_six,4] = "Дорожный Знак South Drive"
o.display_description_item[o.display_page_six,5] = "Дорожный Знак West Lane"
o.display_description_item[o.display_page_six,6] = "Пустой Дорожный Знак"
o.display_description_item[o.display_page_six,7] = "Стрелка"
o.display_description_item[o.display_page_six,8] = "Мусорный Контейнер"
o.display_description_item[o.display_page_six,9] = "Светофор"
o.display_description_item[o.display_page_six,10] = "Фонарь"
o.display_description_item[o.display_page_six,11] = "Фонарный Столб 1"
o.display_description_item[o.display_page_six,12] = "Фонарный Столб 2"
o.display_description_item[o.display_page_six,13] = "Фонарный Столб 3"
o.display_description_item[o.display_page_six,14] = "Куст"
o.display_description_item[o.display_page_six,15] = "Тот Самый Баклажан"
o.display_description_item[o.display_page_six,16] = "Вешалка Для Одежды"
o.display_description_item[o.display_page_six,17] = "Пешеходный Переход"
o.display_description_item[o.display_page_six,18] = "Пешеходный Сигнал"
o.display_description_item[o.display_page_six,19] = "Мусорное Ведро"
