///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Платформы"
o.display_page_description[1] = "Декор"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Тонкая Стена"
o.display_description_item[o.display_page_one,1] = "Красная Дорожка"
o.display_description_item[o.display_page_one,2] = "Большая Стена"
o.display_description_item[o.display_page_one,3] = "Газон 1"
o.display_description_item[o.display_page_one,4] = "Газон 2"
o.display_description_item[o.display_page_one,5] = "Газон 3"
o.display_description_item[o.display_page_one,6] = "Газон 4"
o.display_description_item[o.display_page_one,7] = "Unknown Tile"
o.display_description_item[o.display_page_one,8] = "Unknown Tile"
o.display_description_item[o.display_page_one,9] = "Unknown Tile"
o.display_description_item[o.display_page_one,10] = "Unknown Tile"
o.display_description_item[o.display_page_one,11] = "Unknown Tile"
o.display_description_item[o.display_page_one,12] = "Unknown Tile"
o.display_description_item[o.display_page_one,13] = "Unknown Tile"
o.display_description_item[o.display_page_one,14] = "Unknown Tile"
o.display_description_item[o.display_page_one,15] = "Unknown Tile"
o.display_description_item[o.display_page_one,16] = "Unknown Tile"
o.display_description_item[o.display_page_one,17] = "Unknown Tile"
o.display_description_item[o.display_page_one,18] = "Unknown Tile"
o.display_description_item[o.display_page_one,19] = "Unknown Tile"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Статуя Мэра Зао"
o.display_description_item[o.display_page_two,1] = "Верxушка Колонны"
o.display_description_item[o.display_page_two,2] = "Большая Стена"
o.display_description_item[o.display_page_two,3] = "Шаблон Магазина"
o.display_description_item[o.display_page_two,4] = "Акционный Магазин"
o.display_description_item[o.display_page_two,5] = "Магазин Распродаж"
o.display_description_item[o.display_page_two,6] = "Мир Байков"
o.display_description_item[o.display_page_two,7] = "Дерево"
o.display_description_item[o.display_page_two,8] = "Колонна"
o.display_description_item[o.display_page_two,9] = "Обрезок Стены"
o.display_description_item[o.display_page_two,10] = "Декоративная Панель 1"
o.display_description_item[o.display_page_two,11] = "Декоративная Панель 2"
o.display_description_item[o.display_page_two,12] = "Декоративная Панель 3"
o.display_description_item[o.display_page_two,13] = "Вывезка Мира Байков"
o.display_description_item[o.display_page_two,14] = "Акционная Вывезка"
o.display_description_item[o.display_page_two,15] = "Вывезка Распродаж"
o.display_description_item[o.display_page_two,16] = "Unknown Tile"
o.display_description_item[o.display_page_two,17] = "Unknown Tile"
o.display_description_item[o.display_page_two,18] = "Unknown Tile"
o.display_description_item[o.display_page_two,19] = "Unknown Tile"
