if obj_game_logic.use_cuts_select = "WestDistrictHub01.map"
or obj_game_logic.use_cuts_select = "WestDistrictHub02.map"
or obj_game_logic.use_cuts_select = "WestDistrictHub03.map"
or obj_game_logic.use_cuts_select = "WestDistrictHub04.map"
or obj_game_logic.use_cuts_select = "WestDistrictHub05.map"
or obj_game_logic.use_cuts_select = "WestDistrictHub06.map"
or obj_game_logic.use_cuts_select = "WestDistrictHub07.map"
or obj_game_logic.use_cuts_select = "WestDistrictHub08.map"
or obj_game_logic.use_cuts_select = "WestDistrictHub09.map"

or obj_game_logic.use_cuts_select = "EastDistrictHub01.map"
or obj_game_logic.use_cuts_select = "EastDistrictHub02.map"
or obj_game_logic.use_cuts_select = "EastDistrictHub03.map"
or obj_game_logic.use_cuts_select = "EastDistrictHub04.map"
or obj_game_logic.use_cuts_select = "EastDistrictHub05.map"
or obj_game_logic.use_cuts_select = "EastDistrictHub06.map"
or obj_game_logic.use_cuts_select = "EastDistrictHub07.map"
or obj_game_logic.use_cuts_select = "EastDistrictHub08.map"
or obj_game_logic.use_cuts_select = "EastDistrictHub09.map"

or obj_game_logic.use_cuts_select = "ShangMuMallHub0.map"
or obj_game_logic.use_cuts_select = "ShangMuMallHub1.map"
or obj_game_logic.use_cuts_select = "ShangMuMallHub2.map"
or obj_game_logic.use_cuts_select = "ShangMuMallHub3.map"
or obj_game_logic.use_cuts_select = "ShangMuMallHub4.map"
or obj_game_logic.use_cuts_select = "ShangMuMallHub5.map"
or obj_game_logic.use_cuts_select = "ShangMuMallHub6.map"
or obj_game_logic.use_cuts_select = "ShangMuMallHub7.map"
or obj_game_logic.use_cuts_select = "ShangMuMallHub8.map"
or obj_game_logic.use_cuts_select = "ShangMuMallHub9.map"

or obj_game_logic.use_cuts_select = "AcademyHub00.map"
or obj_game_logic.use_cuts_select = "AcademyHub01.map"
or obj_game_logic.use_cuts_select = "AcademyHub02.map"
or obj_game_logic.use_cuts_select = "AcademyHub03.map"
or obj_game_logic.use_cuts_select = "AcademyHub04.map"
or obj_game_logic.use_cuts_select = "AcademyHub05.map"
or obj_game_logic.use_cuts_select = "AcademyHub06.map"
or obj_game_logic.use_cuts_select = "AcademyHub07.map"
or obj_game_logic.use_cuts_select = "AcademyHub08.map"
or obj_game_logic.use_cuts_select = "AcademyHub09.map"

or obj_game_logic.use_cuts_select = "TempleHub00.map"
or obj_game_logic.use_cuts_select = "TempleHub01.map"
or obj_game_logic.use_cuts_select = "TempleHub02.map"
or obj_game_logic.use_cuts_select = "TempleHub03.map"
or obj_game_logic.use_cuts_select = "TempleHub04.map"
or obj_game_logic.use_cuts_select = "TempleHub05.map"
or obj_game_logic.use_cuts_select = "TempleHub5A.map"
or obj_game_logic.use_cuts_select = "TempleHub06.map"
or obj_game_logic.use_cuts_select = "TempleHub07.map"
or obj_game_logic.use_cuts_select = "TempleHub08.map"
or obj_game_logic.use_cuts_select = "TempleHub09.map"

or obj_game_logic.use_cuts_select = "TaishanHub00.map"
or obj_game_logic.use_cuts_select = "TaishanHub01.map"
or obj_game_logic.use_cuts_select = "TaishanHub02.map"
or obj_game_logic.use_cuts_select = "TaishanHub03.map"
or obj_game_logic.use_cuts_select = "TaishanHub04.map"
or obj_game_logic.use_cuts_select = "TaishanHub05.map"
or obj_game_logic.use_cuts_select = "TaishanHub06.map"
or obj_game_logic.use_cuts_select = "TaishanHub07.map"
or obj_game_logic.use_cuts_select = "TaishanHub08.map"
or obj_game_logic.use_cuts_select = "TaishanHub09.map"

or obj_game_logic.use_cuts_select = "TrainStation00.map"
or obj_game_logic.use_cuts_select = "TrainStation01.map"
or obj_game_logic.use_cuts_select = "TrainStation02.map"
or obj_game_logic.use_cuts_select = "TrainStation03.map"
or obj_game_logic.use_cuts_select = "TrainStation04.map"
or obj_game_logic.use_cuts_select = "TrainStation05.map"
or obj_game_logic.use_cuts_select = "TrainStation06.map"
or obj_game_logic.use_cuts_select = "TrainStation07.map"
or obj_game_logic.use_cuts_select = "TrainStation08.map"
or obj_game_logic.use_cuts_select = "TrainStation09.map"

or obj_game_logic.use_cuts_select = "LagoonHub01.map"
or obj_game_logic.use_cuts_select = "LagoonHub02.map"
or obj_game_logic.use_cuts_select = "LagoonHub03.map"
or obj_game_logic.use_cuts_select = "LagoonHub04.map"
or obj_game_logic.use_cuts_select = "LagoonHub05.map"
or obj_game_logic.use_cuts_select = "LagoonHub06.map"
or obj_game_logic.use_cuts_select = "LagoonHub07.map"
or obj_game_logic.use_cuts_select = "LagoonHub08.map"
or obj_game_logic.use_cuts_select = "LagoonHub09.map"
    return 0;
else
    return 1;
