//Language Array (Pause Menu); 0 = English; 1 = Portuguese; 2 = Polish; 3 = Spanish; 4 = German; 5 = Russian
lang_gui[0,0] = "Stage Select"
lang_gui[0,1] = "Tutorial Stage"
lang_gui[0,2] = ""
lang_gui[0,3] = "Confirm"
lang_gui[0,4] = "Cancel"
lang_gui[0,5] = "Return"
lang_gui[0,6] = "Start?"
lang_gui[0,7] = "Yes"
lang_gui[0,8] = "No"
//Portuguese
lang_gui[1,0] = "Selecionar Personagem"
lang_gui[1,1] = "Fase Tutorial"
lang_gui[1,2] = ""
lang_gui[1,3] = "Confirmar"
lang_gui[1,4] = "Cancelar"
lang_gui[1,5] = "Voltar"
lang_gui[1,6] = "Começar?"
lang_gui[1,7] = "Sim"
lang_gui[1,8] = "Não"
//Polish
lang_gui[2,0] = "Wybór Poziomu"
lang_gui[2,1] = "Samouczek"
lang_gui[2,2] = ""
lang_gui[2,3] = "Potwierdź"
lang_gui[2,4] = "Anuluj"
lang_gui[2,5] = "Wróć"
lang_gui[2,6] = "Start?"
lang_gui[2,7] = "Tak"
lang_gui[2,8] = "Nie"
//Spanish
lang_gui[3,0] = "Seleccionar Nivel"
lang_gui[3,1] = "Nivel Tutorial"
lang_gui[3,2] = ""
lang_gui[3,3] = "Confirmar"
lang_gui[3,4] = "Cancelar"
lang_gui[3,5] = "Volver"
lang_gui[3,6] = "¿Comenzar?"
lang_gui[3,7] = "Sí"
lang_gui[3,8] = "No"
//German
lang_gui[4,0] = "Stage Auswählen"
lang_gui[4,1] = "Tutorial Stage"
lang_gui[4,2] = ""
lang_gui[4,3] = "Bestä."
lang_gui[4,4] = "Abbrechen"
lang_gui[4,5] = "Zurück"
lang_gui[4,6] = "Start?"
lang_gui[4,7] = "Ja"
lang_gui[4,8] = "Nein"
//Russian
lang_gui[5,0] = "Выбрать Уровень"
lang_gui[5,1] = "Обучение"
lang_gui[5,2] = ""
lang_gui[5,3] = "Принять"
lang_gui[5,4] = "Отмена"
lang_gui[5,5] = "Вернуться"
lang_gui[5,6] = "Начать?"
lang_gui[5,7] = "Да"
lang_gui[5,8] = "Нет"
