///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Балки"
o.display_page_description[1] = "Стены"
o.display_page_description[2] = "Спуски"
o.display_page_description[3] = "Платформы"
o.display_page_description[4] = "Декор 1"
o.display_page_description[5] = "Декор 2"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Блок Дерева 1"
o.display_description_item[o.display_page_one,1] = "Тайл Пола"
o.display_description_item[o.display_page_one,2] = "Опора 1"
o.display_description_item[o.display_page_one,3] = "Блок Дерева 2"
o.display_description_item[o.display_page_one,4] = "Блок Дерева 3"
o.display_description_item[o.display_page_one,5] = "Блок Дерева 4"
o.display_description_item[o.display_page_one,6] = "Блок Дерева 5"
o.display_description_item[o.display_page_one,7] = "Блок Дерева 6"
o.display_description_item[o.display_page_one,8] = "Опора 2"
o.display_description_item[o.display_page_one,9] = "Блок Дерева 7"
o.display_description_item[o.display_page_one,10] = "Блок Дерева 8"
o.display_description_item[o.display_page_one,11] = "Блок Дерева 9"
o.display_description_item[o.display_page_one,12] = "Блок Дерева 10"
o.display_description_item[o.display_page_one,13] = "Опора 3"
o.display_description_item[o.display_page_one,14] = "Край - Левый"
o.display_description_item[o.display_page_one,15] = "Деревянная Балка"
o.display_description_item[o.display_page_one,16] = "Край - Правый"
o.display_description_item[o.display_page_one,17] = "Блок Дерева 11"
o.display_description_item[o.display_page_one,18] = "Край - Верхний"
o.display_description_item[o.display_page_one,19] = "Край - Нижний"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Стена - Правая"
o.display_description_item[o.display_page_two,1] = "Стена - Левая"
o.display_description_item[o.display_page_two,2] = "Пол"
o.display_description_item[o.display_page_two,3] = "Потолок"
o.display_description_item[o.display_page_two,4] = "Внешний Угол 1"
o.display_description_item[o.display_page_two,5] = "Внешний Угол 2"
o.display_description_item[o.display_page_two,6] = "Внешний Угол 3"
o.display_description_item[o.display_page_two,7] = "Внешний Угол 4"
o.display_description_item[o.display_page_two,8] = "Внутренний Угол 1"
o.display_description_item[o.display_page_two,9] = "Внутренний Угол 2"
o.display_description_item[o.display_page_two,10] = "Внутренний Угол 3"
o.display_description_item[o.display_page_two,11] = "Внутренний Угол 4"
o.display_description_item[o.display_page_two,12] = "Тайл Затенения 1"
o.display_description_item[o.display_page_two,13] = "Шипы 1"
o.display_description_item[o.display_page_two,14] = "Шипы 2"
o.display_description_item[o.display_page_two,15] = "Шипы 3"
o.display_description_item[o.display_page_two,16] = "Шипы 4"
o.display_description_item[o.display_page_two,17] = "Лестница"
o.display_description_item[o.display_page_two,18] = "Перекладина 1"
o.display_description_item[o.display_page_two,19] = "Перекладина 2"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Малая Рампа - 1"
o.display_description_item[o.display_page_three,1] = "Малая Рампа - 2"
o.display_description_item[o.display_page_three,2] = "Малая Рампа - 3"
o.display_description_item[o.display_page_three,3] = "Малая Рампа - 4"
o.display_description_item[o.display_page_three,4] = "Часть Травянистой Петли 1"
o.display_description_item[o.display_page_three,5] = "Часть Травянистой Петли 2"
o.display_description_item[o.display_page_three,6] = "Тайл Пола"
o.display_description_item[o.display_page_three,7] = "Часть Петли 1"
o.display_description_item[o.display_page_three,8] = "Часть Петли 2"
o.display_description_item[o.display_page_three,9] = "Часть Петли 3"
o.display_description_item[o.display_page_three,10] = "Часть Петли 4"
o.display_description_item[o.display_page_three,11] = "Часть Травянистой Петли 3"
o.display_description_item[o.display_page_three,12] = "Часть Травянистой Петли 4"
o.display_description_item[o.display_page_three,13] = "Часть Двусторонней петли 1"
o.display_description_item[o.display_page_three,14] = "Часть Двусторонней петли 2"
o.display_description_item[o.display_page_three,15] = "Часть Двусторонней петли 3"
o.display_description_item[o.display_page_three,16] = "Часть Двусторонней петли 4"
o.display_description_item[o.display_page_three,17] = "Длинная Рампа 1"
o.display_description_item[o.display_page_three,18] = "Длинная Рампа 2"
o.display_description_item[o.display_page_three,19] = "Многоуровневая Платформа"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Склон – мелкий 1"
o.display_description_item[o.display_page_four,1] = "Склон – мелкий 2"
o.display_description_item[o.display_page_four,2] = "Склон - Крутой 1"
o.display_description_item[o.display_page_four,3] = "Склон - Крутой 2"
o.display_description_item[o.display_page_four,4] = "Склон – мелкий 3"
o.display_description_item[o.display_page_four,5] = "Плоская Поверхность 1"
o.display_description_item[o.display_page_four,6] = "Склон – мелкий 4"
o.display_description_item[o.display_page_four,7] = "Парящая Платформа 1"
o.display_description_item[o.display_page_four,8] = "Парящая Платформа 2"
o.display_description_item[o.display_page_four,9] = "Парящая Платформа 3"
o.display_description_item[o.display_page_four,10] = "Парящая Платформа 4"
o.display_description_item[o.display_page_four,11] = "Парящая Платформа 5"
o.display_description_item[o.display_page_four,12] = "Изменение Направления Платформы"
o.display_description_item[o.display_page_four,13] = "Тайл Травы"
o.display_description_item[o.display_page_four,14] = "Тайл Земли"
o.display_description_item[o.display_page_four,15] = "Unknown Tile 3"
o.display_description_item[o.display_page_four,16] = "Unknown Tile 4"
o.display_description_item[o.display_page_four,17] = "Unknown Tile 5"
o.display_description_item[o.display_page_four,18] = "Unknown Tile 6"
o.display_description_item[o.display_page_four,19] = "Unknown Tile 7"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Декор - Мост 1"
o.display_description_item[o.display_page_five,1] = "Декор - Колонна"
o.display_description_item[o.display_page_five,2] = "Декор - Дерево 1"
o.display_description_item[o.display_page_five,3] = "Декор - Решётка"
o.display_description_item[o.display_page_five,4] = "Декор - Фон"
o.display_description_item[o.display_page_five,5] = "Декор - Платформа"
o.display_description_item[o.display_page_five,6] = "Декор - Фусума 1"
o.display_description_item[o.display_page_five,7] = "Декор - Фреска"
o.display_description_item[o.display_page_five,8] = "Декор - Занавески"
o.display_description_item[o.display_page_five,9] = "Декор - Конец Занавески"
o.display_description_item[o.display_page_five,10] = "Декор - Перила 1"
o.display_description_item[o.display_page_five,11] = "Декор - Опора"
o.display_description_item[o.display_page_five,12] = "Декор - Фонарь 1"
o.display_description_item[o.display_page_five,13] = "Декор - Фусума 2"
o.display_description_item[o.display_page_five,14] = "Декор - Дерево 2"
o.display_description_item[o.display_page_five,15] = "Декор - Дерево 3"
o.display_description_item[o.display_page_five,16] = "Декор - Дерево 3 - Доп. Декорации"
o.display_description_item[o.display_page_five,17] = "Декор - Дерево 4"
o.display_description_item[o.display_page_five,18] = "Декор - Флаг 1"
o.display_description_item[o.display_page_five,19] = "Декор - Фонарь 2"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Тайл Затенения 16x16"
o.display_description_item[o.display_page_six,1] = "Тайл Затенения 32x32"
o.display_description_item[o.display_page_six,2] = "Тайл Затенения 64x64"
o.display_description_item[o.display_page_six,3] = "Тайл Затенения 96x96"
o.display_description_item[o.display_page_six,4] = "Тайл Затенения 16x96"
o.display_description_item[o.display_page_six,5] = "Тайл Затенения 96x16"
o.display_description_item[o.display_page_six,6] = "Тайл Затенения 128x128"
o.display_description_item[o.display_page_six,7] = "Тайл Темноты 128x128"
o.display_description_item[o.display_page_six,8] = "Декор - Большой Стол"
o.display_description_item[o.display_page_six,9] = "Декор - Талый Стол"
o.display_description_item[o.display_page_six,10] = "Unknown Tile"
o.display_description_item[o.display_page_six,11] = "Unknown Tile"
o.display_description_item[o.display_page_six,12] = "Unknown Tile"
o.display_description_item[o.display_page_six,13] = "Unknown Tile"
o.display_description_item[o.display_page_six,14] = "Unknown Tile"
o.display_description_item[o.display_page_six,15] = "Unknown Tile"
o.display_description_item[o.display_page_six,16] = "Unknown Tile"
o.display_description_item[o.display_page_six,17] = "Unknown Tile"
o.display_description_item[o.display_page_six,18] = "Unknown Tile"
o.display_description_item[o.display_page_six,19] = "Unknown Tile"
