///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Plataformas"
o.display_page_description[1] = "Soportes"
o.display_page_description[2] = "Rampas"
o.display_page_description[3] = "Decoración 1"
o.display_page_description[4] = "Decoración 2"
o.display_page_description[5] = "Decoración 3"
o.display_page_description[6] = "Decoración 4"
o.display_page_description[7] = "Decoración 5"
o.display_page_description[8] = "Descartados"
o.display_page_description[9] = "Extras 1"
o.display_page_description[10] = "Extras 2"
o.display_page_description[11] = "Ladrillos Alternativos"
o.display_page_description[12] = "Extras 3"
o.display_page_description[13] = "Extras 4"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Plataforma de Ladrillos 1"
o.display_description_item[o.display_page_one,1] = "Plataforma de Ladrillos 2"
o.display_description_item[o.display_page_one,2] = "Pared de Ladrillos 1"
o.display_description_item[o.display_page_one,3] = "Pared de Ladrillos 2"
o.display_description_item[o.display_page_one,4] = "Pared de Ladrillos 3"
o.display_description_item[o.display_page_one,5] = "Pared de Ladrillos 4"
o.display_description_item[o.display_page_one,6] = "Bloque de Ladrillos 1"
o.display_description_item[o.display_page_one,7] = "Bloque de Ladrillos 2"
o.display_description_item[o.display_page_one,8] = "Bloque de Ladrillos 3"
o.display_description_item[o.display_page_one,9] = "Ladrillo Rojo"
o.display_description_item[o.display_page_one,10] = "Ladrillo Azul"
o.display_description_item[o.display_page_one,11] = "Divisor de Paredes 1"
o.display_description_item[o.display_page_one,12] = "Divisor de Paredes 2"
o.display_description_item[o.display_page_one,13] = "Tuberia Recta 1"
o.display_description_item[o.display_page_one,14] = "Tuberia Recta 2"
o.display_description_item[o.display_page_one,15] = "Tuberia Recta 3"
o.display_description_item[o.display_page_one,16] = "Tuberia Recta 4"
o.display_description_item[o.display_page_one,17] = "Pieza Final de Tubería 1"
o.display_description_item[o.display_page_one,18] = "Pieza Final de Tubería 2"
o.display_description_item[o.display_page_one,19] = "Pieza Final de Tubería 3"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Viga de Construcción - Roja 1"
o.display_description_item[o.display_page_two,1] = "Viga de Construcción - Roja 2"
o.display_description_item[o.display_page_two,2] = "Viga de Construcción - Amarilla 1"
o.display_description_item[o.display_page_two,3] = "Viga de Construcción - Amarilla 2"
o.display_description_item[o.display_page_two,4] = "Viga de Construcción - Roja 3"
o.display_description_item[o.display_page_two,5] = "Viga de Construcción - Roja 4"
o.display_description_item[o.display_page_two,6] = "Viga de Construcción - Amarilla 3"
o.display_description_item[o.display_page_two,7] = "Viga de Soporte - Amarilla 1"
o.display_description_item[o.display_page_two,8] = "Viga de Soporte - Amarilla 2"
o.display_description_item[o.display_page_two,9] = "Viga de Soporte - Roja 1"
o.display_description_item[o.display_page_two,10] = "Viga de Soporte - Roja 2"
o.display_description_item[o.display_page_two,11] = "Viga de Soporte - Roja 3"
o.display_description_item[o.display_page_two,12] = "Viga de Soporte - Amarilla 3"
o.display_description_item[o.display_page_two,13] = "Pared de Concreto - 1"
o.display_description_item[o.display_page_two,14] = "Pared de Concreto - 2"
o.display_description_item[o.display_page_two,15] = "Acera - 1"
o.display_description_item[o.display_page_two,16] = "Acera - 2"
o.display_description_item[o.display_page_two,17] = "Acera - 3"
o.display_description_item[o.display_page_two,18] = "Acera - 4"
o.display_description_item[o.display_page_two,19] = "Viga de Construcción - Amarilla 3"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Cuarto de Tubería 1"
o.display_description_item[o.display_page_three,1] = "Cuarto de Tubería 2"
o.display_description_item[o.display_page_three,2] = "Cuarto de Tubería 3"
o.display_description_item[o.display_page_three,3] = "Cuarto de Tubería 4"
o.display_description_item[o.display_page_three,4] = "Cuarto de Tuberia 1 - Invertido"
o.display_description_item[o.display_page_three,5] = "Cuarto de Tuberia 2 - Invertido"
o.display_description_item[o.display_page_three,6] = "Plataforma Flotante 1"
o.display_description_item[o.display_page_three,7] = "Pieza de Bucle 1"
o.display_description_item[o.display_page_three,8] = "Pieza de Bucle 2"
o.display_description_item[o.display_page_three,9] = "Pieza de Bucle 3"
o.display_description_item[o.display_page_three,10] = "Pieza de Bucle 4"
o.display_description_item[o.display_page_three,11] = "Cuarto de Tubería 3 - Invertido"
o.display_description_item[o.display_page_three,12] = "Cuarto de Tubería 4 - Invertido"
o.display_description_item[o.display_page_three,13] = "Sendero de Colina 1"
o.display_description_item[o.display_page_three,14] = "Sendero de Colina 2"
o.display_description_item[o.display_page_three,15] = "Sendero de Colina 3"
o.display_description_item[o.display_page_three,16] = "Sendero de Colina 4"
o.display_description_item[o.display_page_three,17] = "Camino en Pendiente - Izquierdo"
o.display_description_item[o.display_page_three,18] = "Camino en Pendiente - Derecho"
o.display_description_item[o.display_page_three,19] = "Plataforma Flotante 2"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Ventana - Grande"
o.display_description_item[o.display_page_four,1] = "Ventana - Pequeña 1"
o.display_description_item[o.display_page_four,2] = "Ventana - Pequeña 2"
o.display_description_item[o.display_page_four,3] = "Unidad de Aire Acondicionado 1"
o.display_description_item[o.display_page_four,4] = "Unidad de Aire Acondicionado 2"
o.display_description_item[o.display_page_four,5] = "Telescopio Reflector"
o.display_description_item[o.display_page_four,6] = "Telescopio Refractor"
o.display_description_item[o.display_page_four,7] = "Ambiente - Tuberia - Conector Vertical"
o.display_description_item[o.display_page_four,8] = "Ambiente - Tuberia - Conector Horizontal"
o.display_description_item[o.display_page_four,9] = "Ambiente - Tuberia - Superior"
o.display_description_item[o.display_page_four,10] = "Ambiente - Tuberia - Inferior"
o.display_description_item[o.display_page_four,11] = "Tapa de Poste Electrico"
o.display_description_item[o.display_page_four,12] = "Poste Electrico"
o.display_description_item[o.display_page_four,13] = "Sombrilla"
o.display_description_item[o.display_page_four,14] = "Logo de los Cometas Helados de Ziyo"
o.display_description_item[o.display_page_four,15] = "Helado Flotante 1"
o.display_description_item[o.display_page_four,16] = "Helado Flotante 2"
o.display_description_item[o.display_page_four,17] = "Helado Flotante 3"
o.display_description_item[o.display_page_four,18] = "Bowl de Helado"
o.display_description_item[o.display_page_four,19] = "Banana Split"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Ambiente - Viga de Soporte 1"
o.display_description_item[o.display_page_five,1] = "Ambiente - Barandilla"
o.display_description_item[o.display_page_five,2] = "Ambiente - Acera"
o.display_description_item[o.display_page_five,3] = "Ambiente - Camino"
o.display_description_item[o.display_page_five,4] = "Ambiente - Marco de Ventana"
o.display_description_item[o.display_page_five,5] = "Ambiente - Cartelera 1"
o.display_description_item[o.display_page_five,6] = "Ambiente - Cartelera 2"
o.display_description_item[o.display_page_five,7] = "Ambiente - Pared de Ladrillos 1"
o.display_description_item[o.display_page_five,8] = "Ambiente - Pared de Ladrillos 2"
o.display_description_item[o.display_page_five,9] = "Ambiente - Pared de Ladrillos 3"
o.display_description_item[o.display_page_five,10] = "Ambiente - Construcción 1"
o.display_description_item[o.display_page_five,11] = "Ambiente - Construcción 2"
o.display_description_item[o.display_page_five,12] = "Ambiente - Torre de Agua"
o.display_description_item[o.display_page_five,13] = "Ambiente - Poster de Starbuster"
o.display_description_item[o.display_page_five,14] = "Ambiente - Poster de HavocFox"
o.display_description_item[o.display_page_five,15] = "Ambiente - Anuncio 1"
o.display_description_item[o.display_page_five,16] = "Ambiente - Anuncio 2"
o.display_description_item[o.display_page_five,17] = "Ambiente - Señal de Pare"
o.display_description_item[o.display_page_five,18] = "Ambiente - Señal de Paso"
o.display_description_item[o.display_page_five,19] = "Ambiente - Cruce de Ninjas"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Papelera de Reciclaje"
o.display_description_item[o.display_page_six,1] = "Basurero de Reciclaje"
o.display_description_item[o.display_page_six,2] = "Señal de Avenida Este"
o.display_description_item[o.display_page_six,3] = "Señal de Glorieta Norte"
o.display_description_item[o.display_page_six,4] = "Señal de Calle Sur"
o.display_description_item[o.display_page_six,5] = "Señal de Via Oeste"
o.display_description_item[o.display_page_six,6] = "Señal en Blanco"
o.display_description_item[o.display_page_six,7] = "Señal de Flecha"
o.display_description_item[o.display_page_six,8] = "Señal de Piso Mojado"
o.display_description_item[o.display_page_six,9] = "Semáforo"
o.display_description_item[o.display_page_six,10] = "Poste de Luz"
o.display_description_item[o.display_page_six,11] = "Poste de Luz 1"
o.display_description_item[o.display_page_six,12] = "Poste de Luz 2"
o.display_description_item[o.display_page_six,13] = "Poste de Luz 3"
o.display_description_item[o.display_page_six,14] = "Arbusto"
o.display_description_item[o.display_page_six,15] = "Berenjena Única"
o.display_description_item[o.display_page_six,16] = "Tendedero"
o.display_description_item[o.display_page_six,17] = "Señal de Cruce de Peatones"
o.display_description_item[o.display_page_six,18] = "Señal de Peatones"
o.display_description_item[o.display_page_six,19] = "Cesto de Basura"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Viga de Soporte Amarilla - Completa 1"
o.display_description_item[o.display_page_seven,1] = "Viga de Soporte Amarilla - Angulada 1"
o.display_description_item[o.display_page_seven,2] = "Viga de Soporte Amarilla - Angulada 2"
o.display_description_item[o.display_page_seven,3] = "Viga de Soporte Roja - Angulada 1"
o.display_description_item[o.display_page_seven,4] = "Viga de Soporte Roja - Angulada 2"
o.display_description_item[o.display_page_seven,5] = "Viga de Soporte - Roja 3"
o.display_description_item[o.display_page_seven,6] = "Viga de Soporte Amarilla - Completa 2"
o.display_description_item[o.display_page_seven,7] = "Viga de Soporte Amarilla - Pieza 1"
o.display_description_item[o.display_page_seven,8] = "Viga de Soporte Amarilla - Pieza 2"
o.display_description_item[o.display_page_seven,9] = "Viga de Soporte Amarilla - Pieza 3"
o.display_description_item[o.display_page_seven,10] = "Viga de Soporte Amarilla - Pieza 4"
o.display_description_item[o.display_page_seven,11] = "Viga de Soporte Amarilla - Pieza 5"
o.display_description_item[o.display_page_seven,12] = "Viga de Soporte Amarilla - Pieza 6"
o.display_description_item[o.display_page_seven,13] = "Viga de Soporte para Construcción - Lateral"
o.display_description_item[o.display_page_seven,14] = "Cono de Transito - Grande"
o.display_description_item[o.display_page_seven,15] = "Cono de Transito - Pequeño"
o.display_description_item[o.display_page_seven,16] = "Cono de Transito - 1"
o.display_description_item[o.display_page_seven,17] = "Cono de Transito - 2"
o.display_description_item[o.display_page_seven,18] = "Cono de Transito - 3"
o.display_description_item[o.display_page_seven,19] = "Cono de Transito - 4"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Ambiente - Tuberia - Parte Superior"
o.display_description_item[o.display_page_eight,1] = "Ambiente - Tuberia - Conector Vertical"
o.display_description_item[o.display_page_eight,2] = "Ambiente - Tuberia - Parte Inferior"
o.display_description_item[o.display_page_eight,3] = "Ambiente - Tuberia - Conector Horizontal"
o.display_description_item[o.display_page_eight,4] = "Mesa de Restaurante"
o.display_description_item[o.display_page_eight,5] = "Estanteria Grande"
o.display_description_item[o.display_page_eight,6] = "Tuberia Horizontal"
o.display_description_item[o.display_page_eight,7] = "Viga de Construcción - Mediana 1"
o.display_description_item[o.display_page_eight,8] = "Viga de Construcción - Mediana 2"
o.display_description_item[o.display_page_eight,9] = "Viga de Construcción - Mediana 3"
o.display_description_item[o.display_page_eight,10] = "Viga de Construcción - Mediana 4"
o.display_description_item[o.display_page_eight,11] = "Ambiente - Cerca"
o.display_description_item[o.display_page_eight,12] = "Viga de Soporte para Construcción - Pequeña"
o.display_description_item[o.display_page_eight,13] = "Pinchos Metalicos - 1"
o.display_description_item[o.display_page_eight,14] = "Pinchos Metalicos - 2"
o.display_description_item[o.display_page_eight,15] = "Pinchos Metalicos - 3"
o.display_description_item[o.display_page_eight,16] = "Pinchos Metalicos - 4"
o.display_description_item[o.display_page_eight,17] = "Escalera 1"
o.display_description_item[o.display_page_eight,18] = "Escalera 2"
o.display_description_item[o.display_page_eight,19] = "Barra Suspendida 1"

//Tile Descriptions (Page 9)
o.display_description_item[o.display_page_nine,0] = "Plataforma de Ladrillos - Sin Usar 1"
o.display_description_item[o.display_page_nine,1] = "Plataforma de Ladrillos - Sin Usar 2"
o.display_description_item[o.display_page_nine,2] = "Pared de Ladrillos - Sin usar 1"
o.display_description_item[o.display_page_nine,3] = "Pared de Ladrillos - Sin usar 2"
o.display_description_item[o.display_page_nine,4] = "Pared de Ladrillos - Sin usar 3"
o.display_description_item[o.display_page_nine,5] = "Plataforma de Ladrillos - Sin Usar 3"
o.display_description_item[o.display_page_nine,6] = "Pared de Ladrillos - Sin Usar 4"
o.display_description_item[o.display_page_nine,7] = "Pared de Ladrillos - Sin Usar 5"
o.display_description_item[o.display_page_nine,8] = "Acera - Sin Usar 1"
o.display_description_item[o.display_page_nine,9] = "Pared de Ladrillos - Sin Usar 6"
o.display_description_item[o.display_page_nine,10] = "Pared de Ladrillos - Sin Usar 7"
o.display_description_item[o.display_page_nine,11] = "Cartelera en Blanco - Sin Usar 1"
o.display_description_item[o.display_page_nine,12] = "Cartelera en Blanco - Sin Usar 2"
o.display_description_item[o.display_page_nine,13] = "Cartelera en Blanco - Sin Usar 3"
o.display_description_item[o.display_page_nine,14] = "Tuberia - Sin Usar 1"
o.display_description_item[o.display_page_nine,15] = "Tuberia - Sin Usar 2"
o.display_description_item[o.display_page_nine,16] = "Tuberia - Sin Usar 3"
o.display_description_item[o.display_page_nine,17] = "Tuberia - Sin Usar 4"
o.display_description_item[o.display_page_nine,18] = "Unknown Tile"
o.display_description_item[o.display_page_nine,19] = "Unknown Tile"

//Tile Descriptions (Page 10)
o.display_description_item[o.display_page_ten,0] = "Pared de Ladrillos - Extra 1"
o.display_description_item[o.display_page_ten,1] = "Pared de Ladrillos - Extra 2"
o.display_description_item[o.display_page_ten,2] = "Pared de Ladrillos - Extra 3"
o.display_description_item[o.display_page_ten,3] = "Pared de Ladrillos - Extra 4"
o.display_description_item[o.display_page_ten,4] = "Pared de Ladrillos - Extra 5"
o.display_description_item[o.display_page_ten,5] = "Pared de Ladrillos - Extra 6"
o.display_description_item[o.display_page_ten,6] = "Pared de Ladrillos - Extra 7"
o.display_description_item[o.display_page_ten,7] = "Pieza de Esquina 1"
o.display_description_item[o.display_page_ten,8] = "Pieza de Esquina 2"
o.display_description_item[o.display_page_ten,9] = "Pieza de Esquina 3"
o.display_description_item[o.display_page_ten,10] = "Pieza de Esquina 4"
o.display_description_item[o.display_page_ten,11] = "Pared de Ladrillos - Extra 8"
o.display_description_item[o.display_page_ten,12] = "Pared de Ladrillos - Extra 9"
o.display_description_item[o.display_page_ten,13] = "Pieza de Esquina 5"
o.display_description_item[o.display_page_ten,14] = "Pieza de Esquina 6"
o.display_description_item[o.display_page_ten,15] = "Pieza de Esquina 7"
o.display_description_item[o.display_page_ten,16] = "Plataforma de Ladrillos - Esquina Izquierda"
o.display_description_item[o.display_page_ten,17] = "Plataforma de Ladrillos - Parte Central"
o.display_description_item[o.display_page_ten,18] = "Plataforma de Ladrillos - Esquina Derecha"
o.display_description_item[o.display_page_ten,19] = "Pared de Ladrillos - Extra 10"

//Tile Descriptions (Page 11)
o.display_description_item[o.display_page_eleven,0] = "Bucle de Ladrillos - 1"
o.display_description_item[o.display_page_eleven,1] = "Bucle de Ladrillos - 2"
o.display_description_item[o.display_page_eleven,2] = "Pared de Ladrillos 3"
o.display_description_item[o.display_page_eleven,3] = "Pared de Ladrillos 4"
o.display_description_item[o.display_page_eleven,4] = "Pared de Ladrillos 5"
o.display_description_item[o.display_page_eleven,5] = "Pared de Ladrillos 6"
o.display_description_item[o.display_page_eleven,6] = "Pared de Ladrillos 7"
o.display_description_item[o.display_page_eleven,7] = "Bucle de Ladrillos - 3"
o.display_description_item[o.display_page_eleven,8] = "Bucle de Ladrillos - 4"
o.display_description_item[o.display_page_eleven,9] = "Pieza de Esquina 3"
o.display_description_item[o.display_page_eleven,10] = "Pieza de Esquina 4"
o.display_description_item[o.display_page_eleven,11] = "Pieza de Esquina 8"
o.display_description_item[o.display_page_eleven,12] = "Pieza de Esquina 9"
o.display_description_item[o.display_page_eleven,13] = "Pieza de Esquina 5"
o.display_description_item[o.display_page_eleven,14] = "Pieza de Esquina 6"
o.display_description_item[o.display_page_eleven,15] = "Pieza de Esquina 7"
o.display_description_item[o.display_page_eleven,16] = "Plataforma de Ladrillos - Esquina Izquierda"
o.display_description_item[o.display_page_eleven,17] = "Plataforma de Ladrillos - Parte Central"
o.display_description_item[o.display_page_eleven,18] = "Plataforma de Ladrillos - Esquina Derecha"
o.display_description_item[o.display_page_eleven,19] = "Pared de Ladrillos - Extra 10"

//Tile Descriptions (Page 12)
o.display_description_item[o.display_page_twelve,0] = "Plataforma de Ladrillos 1"
o.display_description_item[o.display_page_twelve,1] = "Plataforma de Ladrillos 2"
o.display_description_item[o.display_page_twelve,2] = "Pared de Ladrillos 1"
o.display_description_item[o.display_page_twelve,3] = "Pared de Ladrillos 2"
o.display_description_item[o.display_page_twelve,4] = "Pared de Ladrillos 3"
o.display_description_item[o.display_page_twelve,5] = "Pared de Ladrillos 4"
o.display_description_item[o.display_page_twelve,6] = "Bloque de Ladrillos 1"
o.display_description_item[o.display_page_twelve,7] = "Bloque de Ladrillos 2"
o.display_description_item[o.display_page_twelve,8] = "Bloque de Ladrillos 3"
o.display_description_item[o.display_page_twelve,9] = "Ladrillo Rojo"
o.display_description_item[o.display_page_twelve,10] = "Ladrillo Azul"
o.display_description_item[o.display_page_twelve,11] = "Divisor de Paredes 1"
o.display_description_item[o.display_page_twelve,12] = "Divisor de Paredes 2"
o.display_description_item[o.display_page_twelve,13] = "Tuberia Plana 1"
o.display_description_item[o.display_page_twelve,14] = "Tuberia Plana 2"
o.display_description_item[o.display_page_twelve,15] = "Tuberia Plana 3"
o.display_description_item[o.display_page_twelve,16] = "Tuberia Plana 4"
o.display_description_item[o.display_page_twelve,17] = "Pieza Final de Tubería 1"
o.display_description_item[o.display_page_twelve,18] = "Pieza Final de Tubería 2"
o.display_description_item[o.display_page_twelve,19] = "Pieza Final de Tubería 3"

//Tile Descriptions (Page 13)
o.display_description_item[o.display_page_thirteen,0] = "Señal de Sendero del Dragón"
o.display_description_item[o.display_page_thirteen,1] = "Señal de Via Pheasant"
o.display_description_item[o.display_page_thirteen,2] = "Señal de Camino Fantail"
o.display_description_item[o.display_page_thirteen,3] = "Señal de Plaza Panya"
o.display_description_item[o.display_page_thirteen,4] = "Señal de Avenida Fuzhu"
o.display_description_item[o.display_page_thirteen,5] = "Señal de Pista Qilin"
o.display_description_item[o.display_page_thirteen,6] = "Señal de Ruta Fénixn"
o.display_description_item[o.display_page_thirteen,7] = "Señal Interestatal 1"
o.display_description_item[o.display_page_thirteen,8] = "Señal Interestatal 2"
o.display_description_item[o.display_page_thirteen,9] = "Soporte de Señal Interestatal 1"
o.display_description_item[o.display_page_thirteen,10] = "Soporte de Señal Interestatal 2"
o.display_description_item[o.display_page_thirteen,11] = "Soporte de Señal Interestatal 3"
o.display_description_item[o.display_page_thirteen,12] = "Soporte de Señal Interestatal 4"
o.display_description_item[o.display_page_thirteen,13] = "Templo del Dragón - Viga de Soporte"
o.display_description_item[o.display_page_thirteen,14] = "Templo del Dragón - Lampara"
o.display_description_item[o.display_page_thirteen,15] = "Templo del Dragón - Puerta"
o.display_description_item[o.display_page_thirteen,16] = "Templo del Dragón - Cerca"
o.display_description_item[o.display_page_thirteen,17] = "Templo del Dragón - Poste de Cerca"
o.display_description_item[o.display_page_thirteen,18] = "Planta de Bambú"
o.display_description_item[o.display_page_thirteen,19] = "Pintura de Fuzhu"

//Tile Descriptions (Page 14)
o.display_description_item[o.display_page_fourteen,0] = "Templo del Dragón - Estatua de Dragón"
o.display_description_item[o.display_page_fourteen,1] = "Templo del Dragón - Estatua de Fuzhu"
o.display_description_item[o.display_page_fourteen,2] = "Letrero de Restaurante Alt - Sushi Panya"
o.display_description_item[o.display_page_fourteen,3] = "Templo del Dragón - Mural de Dragón"
o.display_description_item[o.display_page_fourteen,4] = "Bar de Sushi de Atún para Niños de Timmy - Letrero"
o.display_description_item[o.display_page_fourteen,5] = "Señal de Cerrado"
o.display_description_item[o.display_page_fourteen,6] = "Señal de Abierto"
o.display_description_item[o.display_page_fourteen,7] = ""
o.display_description_item[o.display_page_fourteen,8] = ""
o.display_description_item[o.display_page_fourteen,9] = ""
o.display_description_item[o.display_page_fourteen,10] = ""
o.display_description_item[o.display_page_fourteen,11] = ""
o.display_description_item[o.display_page_fourteen,12] = ""
o.display_description_item[o.display_page_fourteen,13] = ""
o.display_description_item[o.display_page_fourteen,14] = ""
o.display_description_item[o.display_page_fourteen,15] = ""
o.display_description_item[o.display_page_fourteen,16] = ""
o.display_description_item[o.display_page_fourteen,17] = ""
o.display_description_item[o.display_page_fourteen,18] = ""
o.display_description_item[o.display_page_fourteen,19] = ""

