///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Ladders"
o.display_page_description[1] = "Spikes"
o.display_page_description[2] = "Glass Set"
o.display_page_description[3] = "Railings 1"
o.display_page_description[4] = "Railings 2"
o.display_page_description[5] = "Scenery"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Ladder 1"
o.display_description_item[o.display_page_one,1] = "Ladder 2"
o.display_description_item[o.display_page_one,2] = "Ladder 3"
o.display_description_item[o.display_page_one,3] = "Ladder 4"
o.display_description_item[o.display_page_one,4] = "Ladder 5"
o.display_description_item[o.display_page_one,5] = "Ladder 6"
o.display_description_item[o.display_page_one,6] = "Hangbar 1"
o.display_description_item[o.display_page_one,7] = "Hangbar 2"
o.display_description_item[o.display_page_one,8] = "Hangbar 3"
o.display_description_item[o.display_page_one,9] = "Hangbar 4"
o.display_description_item[o.display_page_one,10] = "Hangbar 5"
o.display_description_item[o.display_page_one,11] = "Grind Rail 2"
o.display_description_item[o.display_page_one,12] = "Grind Rail 3"
o.display_description_item[o.display_page_one,13] = "Grind Rail 4"
o.display_description_item[o.display_page_one,14] = "Grind Rail 5"
o.display_description_item[o.display_page_one,15] = "Grind Rail 6"
o.display_description_item[o.display_page_one,16] = "Grind Rail 7"
o.display_description_item[o.display_page_one,17] = "Grind Rail 8"
o.display_description_item[o.display_page_one,18] = "Grind Rail 9"
o.display_description_item[o.display_page_one,19] = "Grind Rail 10"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Metal Spikes 1"
o.display_description_item[o.display_page_two,1] = "Metal Spikes 2"
o.display_description_item[o.display_page_two,2] = "Metal Spikes 3"
o.display_description_item[o.display_page_two,3] = "Metal Spikes 4"
o.display_description_item[o.display_page_two,4] = "Wooden Spikes 1"
o.display_description_item[o.display_page_two,5] = "Wooden Spikes 2"
o.display_description_item[o.display_page_two,6] = "Wooden Spikes 3"
o.display_description_item[o.display_page_two,7] = "Wooden Spikes 4"
o.display_description_item[o.display_page_two,8] = "Rock Spikes 1"
o.display_description_item[o.display_page_two,9] = "Rock Spikes 2"
o.display_description_item[o.display_page_two,10] = "Rock Spikes 3"
o.display_description_item[o.display_page_two,11] = "Rock Spikes 4"
o.display_description_item[o.display_page_two,12] = "Wood Spikes 1"
o.display_description_item[o.display_page_two,13] = "Wood Spikes 2"
o.display_description_item[o.display_page_two,14] = "Wood Spikes 3"
o.display_description_item[o.display_page_two,15] = "Wood Spikes 4"
o.display_description_item[o.display_page_two,16] = "Serrated Spikes 1"
o.display_description_item[o.display_page_two,17] = "Serrated Spikes 2"
o.display_description_item[o.display_page_two,18] = "Serrated Spikes 3"
o.display_description_item[o.display_page_two,19] = "Serrated Spikes 4"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Glass Black - Large"
o.display_description_item[o.display_page_three,1] = "Glass Black - Small"
o.display_description_item[o.display_page_three,2] = "Glass Black - Medium"
o.display_description_item[o.display_page_three,3] = "Glass Black - Vertical"
o.display_description_item[o.display_page_three,4] = "Glass Black - Skinny"
o.display_description_item[o.display_page_three,5] = "Glass Loop-De-Loop Piece 1"
o.display_description_item[o.display_page_three,6] = "Glass Loop-De-Loop Piece 2"
o.display_description_item[o.display_page_three,7] = "Glass Long Ramp 1"
o.display_description_item[o.display_page_three,8] = "Glass Long Ramp 2"
o.display_description_item[o.display_page_three,9] = "Glass Short Ramp 1"
o.display_description_item[o.display_page_three,10] = "Glass Short Ramp 2"
o.display_description_item[o.display_page_three,11] = "Glass Loop-De-Loop Piece 3"
o.display_description_item[o.display_page_three,12] = "Glass Loop-De-Loop Piece 4"
o.display_description_item[o.display_page_three,13] = "Glass Long Ramp 3"
o.display_description_item[o.display_page_three,14] = "Glass Long Ramp 4"
o.display_description_item[o.display_page_three,15] = "Glass Short Ramp 3"
o.display_description_item[o.display_page_three,16] = "Glass Short Ramp 4"
o.display_description_item[o.display_page_three,17] = "Glass Window - Green - Large"
o.display_description_item[o.display_page_three,18] = "Glass Window - Green - Small"
o.display_description_item[o.display_page_three,19] = "Glass Window - Blue - Small"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Rail Loop - Top Left"
o.display_description_item[o.display_page_four,1] = "Rail Loop - Top Right"
o.display_description_item[o.display_page_four,2] = "Rail Slope 1"
o.display_description_item[o.display_page_four,3] = "Rail Slope 2"
o.display_description_item[o.display_page_four,4] = "Rail Ramp Left"
o.display_description_item[o.display_page_four,5] = "Rail Flat 1"
o.display_description_item[o.display_page_four,6] = "Rail Ramp Right"
o.display_description_item[o.display_page_four,7] = "Rail Loop - Bottom Left"
o.display_description_item[o.display_page_four,8] = "Rail Loop - Bottom Right"
o.display_description_item[o.display_page_four,9] = "Rail Ramp - Left - Red"
o.display_description_item[o.display_page_four,10] = "Rail Ramp - Flat - Red"
o.display_description_item[o.display_page_four,11] = "Rail Ramp - Right - Red"
o.display_description_item[o.display_page_four,12] = "Rail Flat - Wood"
o.display_description_item[o.display_page_four,13] = "Rail Ramp - Left - Blue"
o.display_description_item[o.display_page_four,14] = "Rail Ramp - Flat - Blue"
o.display_description_item[o.display_page_four,15] = "Rail Ramp - Right - Blue"
o.display_description_item[o.display_page_four,16] = "Rail Ramp - Right - Yellow"
o.display_description_item[o.display_page_four,17] = "Rail Ramp - Flat - Yellow"
o.display_description_item[o.display_page_four,18] = "Rail Ramp - Left - Yellow"
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Rail Flat - Red 1"
o.display_description_item[o.display_page_five,1] = "Rail Flat - Blue 1"
o.display_description_item[o.display_page_five,2] = "Rail Flat - Yellow 1"
o.display_description_item[o.display_page_five,3] = "Rail Flat - Red 2"
o.display_description_item[o.display_page_five,4] = "Rail Flat - Blue 2"
o.display_description_item[o.display_page_five,5] = "Rail Flat - Yellow 2"
o.display_description_item[o.display_page_five,6] = ""
o.display_description_item[o.display_page_five,7] = "Rail Flat - Red 3"
o.display_description_item[o.display_page_five,8] = "Rail Flat - Red 4"
o.display_description_item[o.display_page_five,9] = "Rail Flat - Yellow 3"
o.display_description_item[o.display_page_five,10] = "Rail Flat - Yellow 4"
o.display_description_item[o.display_page_five,11] = "Rail Flat - Blue 3"
o.display_description_item[o.display_page_five,12] = "Rail Flat - Blue 4"
o.display_description_item[o.display_page_five,13] = ""
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Scenery - Camera Zoom Reset"
o.display_description_item[o.display_page_six,1] = "Scenery - Camera Zoom 50 Percent"
o.display_description_item[o.display_page_six,2] = "Scenery - Camera Zoom 25 Percent"
o.display_description_item[o.display_page_six,3] = "Grind Rail 11"
o.display_description_item[o.display_page_six,4] = "Grind Rail 12"
o.display_description_item[o.display_page_six,5] = "West Lane Street Sign"
o.display_description_item[o.display_page_six,6] = "Blank Street Sign"
o.display_description_item[o.display_page_six,7] = "Arrow Sign"
o.display_description_item[o.display_page_six,8] = "Recycle Bin"
o.display_description_item[o.display_page_six,9] = "Traffic Lights"
o.display_description_item[o.display_page_six,10] = "Lamp Post"
o.display_description_item[o.display_page_six,11] = "Lamp Pole 1"
o.display_description_item[o.display_page_six,12] = "Lamp Pole 2"
o.display_description_item[o.display_page_six,13] = "Lamp Pole 3"
o.display_description_item[o.display_page_six,14] = "Bush"
o.display_description_item[o.display_page_six,15] = "One Of A Kind Eggplant"
o.display_description_item[o.display_page_six,16] = "Clothes Line"
o.display_description_item[o.display_page_six,17] = "Pedestrian Crossing Sign"
o.display_description_item[o.display_page_six,18] = "Pedestrian Signal"
o.display_description_item[o.display_page_six,19] = "Trash Can"

