///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Платформы"
o.display_page_description[1] = "Стены"
o.display_page_description[2] = "Рампы"
o.display_page_description[3] = "Декор"
o.display_page_description[4] = "Доп."
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Панельный Пол 1"
o.display_description_item[o.display_page_one,1] = "Панельный Пол 2"
o.display_description_item[o.display_page_one,2] = "Панельный Пол 3"
o.display_description_item[o.display_page_one,3] = "Часть Моста 1"
o.display_description_item[o.display_page_one,4] = "Часть Моста 2"
o.display_description_item[o.display_page_one,5] = "Часть Моста 3"
o.display_description_item[o.display_page_one,6] = "Часть Моста 4"
o.display_description_item[o.display_page_one,7] = "Панельная Стена 1"
o.display_description_item[o.display_page_one,8] = "Панельная Стена 2"
o.display_description_item[o.display_page_one,9] = "Панельная Стена 3"
o.display_description_item[o.display_page_one,10] = "Часть Моста 5"
o.display_description_item[o.display_page_one,11] = "Панельная Стена 4"
o.display_description_item[o.display_page_one,12] = "Часть Моста 6"
o.display_description_item[o.display_page_one,13] = "Панельный Потолок 1"
o.display_description_item[o.display_page_one,14] = "Панельный Потолок 2"
o.display_description_item[o.display_page_one,15] = "Панельный Потолок 3"
o.display_description_item[o.display_page_one,16] = "Внутренняя Панель 1"
o.display_description_item[o.display_page_one,17] = "Внутренняя Панель 2"
o.display_description_item[o.display_page_one,18] = "Внутренняя Панель 3"
o.display_description_item[o.display_page_one,19] = "Внутренняя Панель 4"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Панельная Стена 4"
o.display_description_item[o.display_page_two,1] = "Панельная Стена 5"
o.display_description_item[o.display_page_two,2] = "Панельная Стена 6"
o.display_description_item[o.display_page_two,3] = "Большой Вентилятор"
o.display_description_item[o.display_page_two,4] = "Панельная Стена 7"
o.display_description_item[o.display_page_two,5] = "Панельная Стена 8"
o.display_description_item[o.display_page_two,6] = "Панельная Стена 7"
o.display_description_item[o.display_page_two,7] = "Опорная Балка 1"
o.display_description_item[o.display_page_two,8] = "Опорная Балка 2"
o.display_description_item[o.display_page_two,9] = "Опорная Балка 3"
o.display_description_item[o.display_page_two,10] = ""
o.display_description_item[o.display_page_two,11] = ""
o.display_description_item[o.display_page_two,12] = ""
o.display_description_item[o.display_page_two,13] = ""
o.display_description_item[o.display_page_two,14] = ""
o.display_description_item[o.display_page_two,15] = ""
o.display_description_item[o.display_page_two,16] = ""
o.display_description_item[o.display_page_two,17] = ""
o.display_description_item[o.display_page_two,18] = ""
o.display_description_item[o.display_page_two,19] = ""

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Панельная Рампа 1"
o.display_description_item[o.display_page_three,1] = "Панельная Рампа 2"
o.display_description_item[o.display_page_three,2] = "Мост - Рампа 1"
o.display_description_item[o.display_page_three,3] = "Мост - Рампа 2"
o.display_description_item[o.display_page_three,4] = "Парящая Платформа 1"
o.display_description_item[o.display_page_three,5] = "Парящая Сфера"
o.display_description_item[o.display_page_three,6] = "Треснувшая Парящая Сфера"
o.display_description_item[o.display_page_three,7] = "Панельная Петля 1"
o.display_description_item[o.display_page_three,8] = "Панельная Петля 2"
o.display_description_item[o.display_page_three,9] = "Незащищённая Петля 1"
o.display_description_item[o.display_page_three,10] = "Незащищённая Петля 2"
o.display_description_item[o.display_page_three,11] = ""
o.display_description_item[o.display_page_three,12] = ""
o.display_description_item[o.display_page_three,13] = "Панельная Петля 3"
o.display_description_item[o.display_page_three,14] = "Панельная Петля 4"
o.display_description_item[o.display_page_three,15] = "Незащищённая Петля 3"
o.display_description_item[o.display_page_three,16] = "Незащищённая Петля 4"
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Лаборатрная Дверь"
o.display_description_item[o.display_page_four,1] = "Рубильники (Закрытые)"
o.display_description_item[o.display_page_four,2] = "Рубильники (Открытые)"
o.display_description_item[o.display_page_four,3] = "Коробка с Мусором 1"
o.display_description_item[o.display_page_four,4] = "Personal Protection Equipment Sign"
o.display_description_item[o.display_page_four,5] = "Коробка с Мусором 2"
o.display_description_item[o.display_page_four,6] = "Рабочая Станция"
o.display_description_item[o.display_page_four,7] = "Передатчик"
o.display_description_item[o.display_page_four,8] = "Передатчик WiFi"
o.display_description_item[o.display_page_four,9] = "Неработающий Дрон"
o.display_description_item[o.display_page_four,10] = "Рельсы"
o.display_description_item[o.display_page_four,11] = ""
o.display_description_item[o.display_page_four,12] = ""
o.display_description_item[o.display_page_four,13] = ""
o.display_description_item[o.display_page_four,14] = ""
o.display_description_item[o.display_page_four,15] = ""
o.display_description_item[o.display_page_four,16] = ""
o.display_description_item[o.display_page_four,17] = ""
o.display_description_item[o.display_page_four,18] = ""
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = ""
o.display_description_item[o.display_page_five,1] = ""
o.display_description_item[o.display_page_five,2] = ""
o.display_description_item[o.display_page_five,3] = ""
o.display_description_item[o.display_page_five,4] = ""
o.display_description_item[o.display_page_five,5] = ""
o.display_description_item[o.display_page_five,6] = ""
o.display_description_item[o.display_page_five,7] = ""
o.display_description_item[o.display_page_five,8] = ""
o.display_description_item[o.display_page_five,9] = ""
o.display_description_item[o.display_page_five,10] = ""
o.display_description_item[o.display_page_five,11] = ""
o.display_description_item[o.display_page_five,12] = ""
o.display_description_item[o.display_page_five,13] = ""
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = ""
o.display_description_item[o.display_page_six,1] = ""
o.display_description_item[o.display_page_six,2] = ""
o.display_description_item[o.display_page_six,3] = ""
o.display_description_item[o.display_page_six,4] = ""
o.display_description_item[o.display_page_six,5] = ""
o.display_description_item[o.display_page_six,6] = ""
o.display_description_item[o.display_page_six,7] = ""
o.display_description_item[o.display_page_six,8] = ""
o.display_description_item[o.display_page_six,9] = ""
o.display_description_item[o.display_page_six,10] = ""
o.display_description_item[o.display_page_six,11] = ""
o.display_description_item[o.display_page_six,12] = ""
o.display_description_item[o.display_page_six,13] = ""
o.display_description_item[o.display_page_six,14] = ""
o.display_description_item[o.display_page_six,15] = ""
o.display_description_item[o.display_page_six,16] = ""
o.display_description_item[o.display_page_six,17] = ""
o.display_description_item[o.display_page_six,18] = ""
o.display_description_item[o.display_page_six,19] = ""

