switch(argument0)
    {
        //Items
        case spr_gem: {return 1; break;}
        case spr_petal_flower:  {return 1; break;}
        case spr_petal_shard:   {return 1; break;}
        case spr_chibililac_cage:  {return 1; break;}
        case spr_target:  {return 1; break;}
        case spr_checkpoint:  {return 1; break;}
        case spr_bubbles_air:  {return 1; break;}
        case spr_shield_earth:  {return 1; break;}
        case spr_shield_fire_front:  {return 1; break;}
        case spr_shield_metal:  {return 1; break;}
        case spr_shield_water:  {return 1; break;}
        case spr_shield_wood:  {return 1; break;}
        case spr_shield_rock:  {return 1; break;}
        case spr_mu_ball_spike:  {return 1; break;}
        case spr_mu_rotating_spikes:  {return 1; break;}
        case spr_train_station_spawner:  {return 1; break;}
        case spr_keycard: {return 1; break;}
        case spr_keycard_terminal: {return 1; break;}
        case spr_keycard_door: {return 1; break;}
        case spr_respawn_plane: {return 1; break;}
        case spr_smart_pool_slime: {return 1; break;}
        case spr_slime_cube:       {return 1; break;}
        case spr_sludge_cube:      {return 1; break;}
        case spr_smart_pool_sludge: {return 1; break;}
        case spr_water_type_sludge:       {return 1; break;}
        case spr_slimefall_node:   {return 1; break;}
        case spr_camera_zoom_reset: {return 1; break;}
        case spr_camera_zoom_out_2x: {return 1; break;}
        case spr_camera_zoom_out_4x: {return 1; break;}
        case spr_crystal_gem_flower: {return 1; break;}
        case spr_crystal_gold_flower: {return 1; break;}
        case spr_crystal_green_flower: {return 1; break;}
        case spr_crystal_gem_float:    {return 1; break;}
        case spr_health_petal_flower: {return 1; break;}
        case spr_crate_0_copy: {return 1; break;}
        case spr_flower_2_copy: {return 1; break;}
        case spr_flower_3_copy: {return 1; break;}
        case spr_flower_4_copy: {return 1; break;}
        case spr_flower_5_copy: {return 1; break;}
        case spr_flower_6_copy: {return 1; break;}
        case spr_flower_7_copy: {return 1; break;}
        case spr_flower_8_copy: {return 1; break;}
        case spr_flower_10_copy: {return 1; break;}
        case spr_bomb_flower: {return 1; break;}
        case spr_gascan_0_copy: {return 1; break;}
        case spr_boost_pad: {return 1; break;}
        case spr_mega_crate: {return 1; break;}
        case spr_mega_bomb: {return 1; break;}
        case spr_mega_melon: {return 1; break;}
        case spr_disc_ball: {return 1; break;}
        case spr_weather_clear: {return 1; break;}
        case spr_weather_rain: {return 1; break;}
        case spr_weather_storm: {return 1; break;}
        case spr_weather_tempest: {return 1; break;}
        case spr_weather_slime: {return 1; break;}
        case spr_weather_drizzle: {return 1; break;}
        case spr_crosswalk_signal: {return 1; break;}
        case spr_mega_car: {return 1; break;}
        case spr_mega_milk: {return 1; break;}
        case spr_mega_dumpster: {return 1; break;}
        case spr_cube_mega_item: {return 1; break;}
        case spr_cube_mega_bouncy: {return 1; break;}
        case spr_cube_mega_spring: {return 1; break;}
        case spr_cube_rogue_spring: {return 1; break;}
        case spr_rogue_cube: {return 1; break;}
        case spr_campfire: {return 1; break;}
        case spr_bench_0: {return 1; break;}
        case spr_bench_1: {return 1; break;}
        case spr_bench_2: {return 1; break;}
        case spr_speed_booster: {return 1; break;}
        case spr_bench_3: {return 1; break;}
        case spr_bench_4: {return 1; break;}
        case spr_water_cube: {return 1; break;}
        case spr_green_pot_destructible: {return 1; break;}
        case spr_yellow_pot_destructible: {return 1; break;}
        case spr_mega_green_pot: {return 1; break;}
        case spr_mega_yellow_pot: {return 1; break;}
        case spr_rock_destructible: {return 1; break;}
        case spr_bird: {return 1; break;}
        case spr_gold_gem: {return 1; break;}
        case spr_wind_turbine: {return 1; break;}
        case spr_wind_turbine_stopper: {return 1; break;}
        case spr_soda_can: {return 1; break;}
        case spr_basket_ball: {return 1; break;}
        case spr_platform_modifier_circular: {return 1; break;}
        case spr_platform_modifier_halfcircle: {return 1; break;}
        case spr_loop_changer_l: {return 1; break;}
        case spr_loop_changer_r: {return 1; break;}
        case spr_loop_layer_changer: {return 1; break;}
        case spr_loop_layer_changer_l: {return 1; break;}
        case spr_music_on: {return 1; break;}
        case spr_music_off: {return 1; break;}
        case spr_stop_music: {return 1; break;}
        case spr_start_music: {return 1; break;}
        case spr_water_type_slime: {return 1; break;}
        case spr_water_type_mud: {return 1; break;}
        case spr_water_type_petal: {return 1; break;}
        case spr_water_type_oil: {return 1; break;}
        case spr_slime_water: {return 1; break;}
        case spr_stop_ambient_sounds: {return 1; break;}
        case spr_platform_modifier_bell_hammer: {return 1; break;}
        case obj_moving_platform: {return 1; break;}
        case obj_cube_generator: {return 1; break;}
        case spr_wasp_nest: {return 1; break;}
        case spr_stinger_nest: {return 1; break;}
        case spr_bench_5: {return 1; break;}
        case spr_bivalve_pop: {return 1; break;}
        case spr_lagoon_boat: {return 1; break;}
        case spr_diveboard: {return 1; break;}
        case spr_diveboard_left: {return 1; break;}
        case spr_boss_runaway_star_marine: {return 1; break;}
        case spr_kiwi: {return 1; break;}
        case spr_buoy_flying: {return 1; break;}
        case spr_bubble_orbiter: {return 1; break;}
        //Springs
        case spr_spring_0: {return 1; break;}
        case spr_spring_1: {return 1; break;}
        case spr_spring_2: {return 1; break;}
        case spr_spring_3: {return 1; break;}
        case spr_spring_4: {return 1; break;}
        case spr_spring_5: {return 1; break;}
        case spr_spring_6: {return 1; break;}
        case spr_spring_7: {return 1; break;}
        case spr_spring_8: {return 1; break;}
        case spr_spring_9: {return 1; break;}
        case spr_spring_10: {return 1; break;}
        case spr_spring_11: {return 1; break;}
        case spr_spring_12: {return 1; break;}
        case spr_spring_13: {return 1; break;}
        case spr_spring_14: {return 1; break;}
        case spr_spring_15: {return 1; break;}
        case spr_spring_16: {return 1; break;}
        case spr_spring_17: {return 1; break;}
        case spr_spring_18: {return 1; break;}
        case spr_spring_19: {return 1; break;}
        case spr_spring_20: {return 1; break;}
        case spr_spring_21: {return 1; break;}
        case spr_spring_22: {return 1; break;}
        case spr_spring_23: {return 1; break;}
        case spr_spring_24: {return 1; break;}
        case spr_spring_25: {return 1; break;}
        case spr_spring_26: {return 1; break;}
        case spr_spring_27: {return 1; break;}
        case spr_spring_28: {return 1; break;}
        case spr_spring_29: {return 1; break;}
        case spr_spring_30: {return 1; break;}
        case spr_spring_31: {return 1; break;}
        case spr_spring_32: {return 1; break;}
        case spr_spring_33: {return 1; break;}
        case spr_spring_34: {return 1; break;}
        case spr_spring_35: {return 1; break;}
        case spr_spring_36: {return 1; break;}
        case spr_spring_37: {return 1; break;}
        case spr_boost_ring_right: {return 1; break;}
        case spr_boost_ring_left:  {return 1; break;}
        case spr_boost_ring_up:    {return 1; break;}
        case spr_boost_ring_down:  {return 1; break;}
        case spr_super_boost_ring_right: {return 1; break;}
        case spr_super_boost_ring_left:  {return 1; break;}
        case spr_super_boost_ring_up:    {return 1; break;}
        case spr_super_boost_ring_down:  {return 1; break;}
        case spr_temple_bell:  {return 1; break;}
        case spr_pinwheel_pulley:  {return 1; break;}
        //Enemies
        case spr_metal_pup:  {return 1; break;}
        case spr_blade_orbiter:  {return 1; break;}
        case spr_rocket_puncher: {return 1; break;}
        case spr_turretus: {return 1; break;}
        case star_flounder: {return 1; break;}
        case spr_saw_flounder: {return 1; break;}
        case spr_shark_torpedo_unloaded: {return 1; break;}
        case spr_dna_cannon: {return 1; break;}
        case spr_fire_spitter: {return 1; break;}
        case spr_buoybuoy: {return 1; break;}
        case spr_ghetto_blaster: {return 1; break;}
        case spr_bullfrag: {return 1; break;}
        case spr_rna_cannon: {return 1; break;}
        case spr_malleus:   {return 1; break;}
        case spr_sprindog:  {return 1; break;}
        case spr_wasp:  {return 1; break;}
        case spr_ant_bomb:  {return 1; break;}
        case spr_stinger:  {return 1; break;}
        case spr_iris:  {return 1; break;}
        case spr_sushi_roller:  {return 1; break;}
        case spr_sea_turretus:  {return 1; break;}
        case spr_pushup:  {return 1; break;}
        case spr_plasma_squid:  {return 1; break;}
        case spr_algae_cutter:  {return 1; break;}
        case spr_snappy:  {return 1; break;}
        case spr_ring_hammer_idle:  {return 1; break;}
        case spr_axle_turret_thumbnail: {return 1; break;}
        case spr_fireworks_tank_thumbnail: {return 1; break;}
        case spr_blade_subordinate: {return 1; break;}
        case spr_star_marine_base_1: {return 1; break;}
        case spr_platform_midboss_gate: {return 1; break;}
        case spr_boss_runaway_bouncer: {return 1; break;}
        case spr_boss_runaway_fireworks_tank: {return 1; break;}
        case spr_mud_cube: {return 1; break;}
        case spr_mud_block: {return 1; break;}
        case spr_smart_pool_mud: {return 1; break;}
        case spr_portal_1A: {return 1; break;}
        case spr_portal_1B: {return 1; break;}
        case spr_portal_2A: {return 1; break;}
        case spr_portal_2B: {return 1; break;}
        case spr_portal_3A: {return 1; break;}
        case spr_portal_3B: {return 1; break;}
        case spr_sliding_door_a: {return 1; break;}
        case spr_sliding_door_b: {return 1; break;}
        case spr_instant_water: {return 1; break;}
        case spr_instant_water_specify: {return 1; break;}
        case spr_ballpit_balls: {return 1; break;}
        case spr_ballbit_gems: {return 1; break;}
        case spr_male_potty: {return 1; break;}
        case spr_female_potty: {return 1; break;}
        case spr_trans_potty: {return 1; break;}
        case spr_basketball_hoop: {return 1; break;}
        case spr_hangbar_sprite: {return 1; break;}
        case spr_pulley_rope_hor: {return 1; break;}
        case spr_pulley_rope_ver: {return 1; break;}
        case spr_pulley: {return 1; break;}
        case spr_guardian_head: {return 1; break;}
        case spr_pusher_up: {return 1; break;}
        case spr_pusher_down: {return 1; break;}
        case spr_pusher_left: {return 1; break;}
        case spr_pusher_right: {return 1; break;}
        case spr_boss_runaway_guardian: {return 1; break;}
        case spr_minecart: {return 1; break;}
        case spr_spikes_21: {return 1; break;}
        case spr_chum_bucket: {return 1; break;}
        case spr_photo_poster: {return 1; break;}
        case spr_led_arrows: {return 1; break;}
        case obj_buoy: {return 1; break;}
        case spr_escalator_top: {return 1; break;}
        case spr_escalator_middle: {return 1; break;}
        case spr_escalator_bottom: {return 1; break;}
        case spr_escalator_top_flipped: {return 1; break;}
        case spr_escalator_middle_flipped: {return 1; break;}
        case spr_escalator_bottom_flipped: {return 1; break;}
        case spr_camera_stop_plane: {return 1; break;}
        case spr_bb_elevator: {return 1; break;}
        case spr_elevator_stopper: {return 1; break;}
        //Angle Gears
        case spr_angle_gear:     {return 1; break;}
        case spr_angle_gear_90:  {return 1; break;}
        case spr_angle_gear_180: {return 1; break;}
        case spr_angle_gear_270: {return 1; break;}
        //Background Changers
        case spr_bg_change_0: {return 1; break;}
        case spr_bg_change_1: {return 1; break;}
        case spr_bg_change_2: {return 1; break;}
        case spr_bg_change_3: {return 1; break;}
        case spr_bg_change_4: {return 1; break;}
        case spr_bg_change_5: {return 1; break;}
        case spr_bg_change_6: {return 1; break;}
        case spr_bg_change_7: {return 1; break;}
        case spr_bg_change_8: {return 1; break;}
        case spr_bg_change_9: {return 1; break;}
        case spr_bg_change_10: {return 1; break;}
        case spr_bg_change_11: {return 1; break;}
        case spr_bg_change_12: {return 1; break;}
        case spr_bg_change_13: {return 1; break;}
        case spr_bg_change_14: {return 1; break;}
        case spr_bg_change_15: {return 1; break;}
        case spr_bg_change_16: {return 1; break;}
        case spr_bg_change_17: {return 1; break;}
        case spr_bg_change_18: {return 1; break;}
        case spr_bg_change_19: {return 1; break;}
        case spr_bg_change_20: {return 1; break;}
        case spr_bg_changer_21: {return 1; break;}
        case spr_bg_changer_22: {return 1; break;}
        case spr_bg_changer_23: {return 1; break;}
        case spr_bg_changer_24: {return 1; break;}
        case spr_bg_changer_25: {return 1; break;}
        case spr_bg_changer_26: {return 1; break;}
        case spr_bg_changer_27: {return 1; break;}
        case spr_bg_changer_28: {return 1; break;}
        case spr_door_2: {return 1; break;}
        case spr_door_3: {return 1; break;}
        case spr_floor_panel: {return 1; break;}
        case spr_monitor_0: {return 1; break;}
        case spr_monitor_1: {return 1; break;}
        case spr_monitor_2: {return 1; break;}
        case spr_monitor_3: {return 1; break;}
        case spr_monitor_4: {return 1; break;}
        case spr_sj_fountain: {return 1; break;}
        case spr_barrel: {return 1; break;}
        //NPCs
        case spr_lilac_cs_talking_neutral:      {return 1; break;}
        case spr_carol_cs_talking_neutral:      {return 1; break;}
        case spr_milla_cs_talking_neutral:      {return 1; break;}
        case spr_milla_cs_excited:              {return 1; break;}
        case spr_npc_stella_idle:               {return 1; break;}
        case spr_npc_shy_idle:                  {return 1; break;}
        case spr_npc_tiwi_idle:                 {return 1; break;}
        case spr_npc_sign_idle:                 {return 1; break;}
        case spr_npc_stumpy_idle:               {return 1; break;}
        case spr_npc_cook_idle:                 {return 1; break;}
        case spr_npc_wacky_idle:                {return 1; break;}
        case spr_npc_harige_idle:               {return 1; break;}
        case spr_npc_bird_guard_idle:           {return 1; break;}
        case spr_npc_jamie_idle:                {return 1; break;}
        case spr_npc_cassandre_idle:            {return 1; break;}
        case spr_npc_azuli_idle:                {return 1; break;}
        case spr_spade_cs_talking_neutral:      {return 1; break;}
        case spr_npc_astum_idle:                {return 1; break;}
        case spr_npc_beibo_idle:                {return 1; break;}
        case spr_npc_trip_idle:                 {return 1; break;}
        case spr_npc_axl_idle:                  {return 1; break;}
        case spr_npc_candy_idle:                {return 1; break;}
        case spr_npc_umi_idle:                  {return 1; break;}
        case spr_npc_allister_idle:             {return 1; break;}
        case spr_npc_abby_idle:                 {return 1; break;}
        case spr_npc_alexis_idle:               {return 1; break;}
        case spr_npc_kyomi_idle:                {return 1; break;}
        case spr_npc_xavier_idle:               {return 1; break;}
        case spr_npc_carrie_idle:               {return 1; break;}
        case spr_npc_ryusei_idle:               {return 1; break;}
        case spr_npc_savvy_idle:                {return 1; break;}
        case spr_npc_rhyme_idle:                {return 1; break;}
        case spr_npc_clyde_idle:                {return 1; break;}
        case spr_npc_bucky_idle:                {return 1; break;}
        case spr_npc_ness_idle:                 {return 1; break;}
        case spr_npc_hyper_idle:                {return 1; break;}
        case spr_npc_iris_idle:                 {return 1; break;}
        case spr_npc_maika_idle:                {return 1; break;}
        case spr_npc_leela_idle:                {return 1; break;}
        case spr_npc_tsuki_idle:                {return 1; break;}
        case spr_npc_libbie_dark_idle:          {return 1; break;}
        case spr_npc_pumppy_idle:               {return 1; break;}
        case spr_npc_libbie_idle:               {return 1; break;}
        case spr_npc_serena_idle:               {return 1; break;}
        case spr_npc_chiasa_idle:               {return 1; break;}
        case spr_npc_dean_idle:                 {return 1; break;}
        case spr_npc_shan_idle:                 {return 1; break;}
        case spr_npc_mei_idle:                  {return 1; break;}
        case spr_npc_vivid_idle:                {return 1; break;}
        case spr_npc_garrett_idle:              {return 1; break;}
        case spr_npc_elric_idle:                {return 1; break;}
        case spr_npc_beldr_idle:                {return 1; break;}
        case spr_npc_leo_idle:                  {return 1; break;}
        case spr_npc_maria_idle:                {return 1; break;}
        case spr_npc_jett_idle:                 {return 1; break;}
        case spr_npc_marshmallow_idle:          {return 1; break;}
        case spr_npc_vela:                      {return 1; break;}
        case spr_npc_leone_idle:                {return 1; break;}
        case spr_npc_pat_idle:                  {return 1; break;}
        case spr_npc_uny_idle:                  {return 1; break;}
        case spr_npc_kii_idle:                  {return 1; break;}
        case spr_npc_kyoti_idle:                {return 1; break;}
        case spr_npc_yuuka_idle:                {return 1; break;}
        case spr_npc_kubo:                      {return 1; break;}
        case spr_npc_zeia:                      {return 1; break;}
        case spr_npc_gauge:                     {return 1; break;}
        case spr_npc_tanner:                    {return 1; break;}
        case spr_npc_amy:                       {return 1; break;}
        case spr_npc_alan:                      {return 1; break;}
        case spr_npc_kai:                       {return 1; break;}
        case spr_npc_neera:                     {return 1; break;}
        case spr_npc_run_lilac:                 {return 1; break;}
        case spr_npc_run_carol:                 {return 1; break;}
        case spr_npc_run_milla:                 {return 1; break;}
        case spr_npc_run_spade:                 {return 1; break;}
        case spr_npc_run_carrie:                {return 1; break;}
        case spr_npc_run_chiasa:                {return 1; break;}
        case spr_npc_run_bike:                  {return 1; break;}
        case spr_npc_mirdin:                    {return 1; break;}
        case spr_npc_boss:                      {return 1; break;}
        case spr_npc_dexter:                    {return 1; break;}
        case spr_npc_kusei:                     {return 1; break;}
        case spr_npc_flavio:                    {return 1; break;}
        case spr_npc_millie:                    {return 1; break;}
        case spr_npc_bird_guard_male:           {return 1; break;}
        case spr_npc_sabre:                     {return 1; break;}
        case spr_npc_miko:                      {return 1; break;}
        case spr_npc_vergil:                    {return 1; break;}
        case spr_npc_tyler:                     {return 1; break;}
        case spr_npc_nougat:                    {return 1; break;}
        case spr_npc_luna:                      {return 1; break;}
        case spr_npc_jonas:                     {return 1; break;}
        default: {return 0; break;}
    }
