///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Belki"
o.display_page_description[1] = "Ściany"
o.display_page_description[2] = "Rampy"
o.display_page_description[3] = "Platformy"
o.display_page_description[4] = "Sceneria 1"
o.display_page_description[5] = "Sceneria 2"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Blok Drewna 1"
o.display_description_item[o.display_page_one,1] = "Podłoga"
o.display_description_item[o.display_page_one,2] = "Podpora 1"
o.display_description_item[o.display_page_one,3] = "Blok Drewna 2"
o.display_description_item[o.display_page_one,4] = "Blok Drewna 3"
o.display_description_item[o.display_page_one,5] = "Blok Drewna 4"
o.display_description_item[o.display_page_one,6] = "Blok Drewna 5"
o.display_description_item[o.display_page_one,7] = "Blok Drewna 6"
o.display_description_item[o.display_page_one,8] = "Podpora 2"
o.display_description_item[o.display_page_one,9] = "Blok Drewna 7"
o.display_description_item[o.display_page_one,10] = "Blok Drewna 8"
o.display_description_item[o.display_page_one,11] = "Blok Drewna 9"
o.display_description_item[o.display_page_one,12] = "Blok Drewna 10"
o.display_description_item[o.display_page_one,13] = "Podpora 3"
o.display_description_item[o.display_page_one,14] = "Narożnik - Lewo"
o.display_description_item[o.display_page_one,15] = "Drewniana Belka"
o.display_description_item[o.display_page_one,16] = "Narożnik - Prawo"
o.display_description_item[o.display_page_one,17] = "Blok Drewna 11"
o.display_description_item[o.display_page_one,18] = "Narożnik - Góra"
o.display_description_item[o.display_page_one,19] = "Narożnik - Dół"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Ściana - Prawo"
o.display_description_item[o.display_page_two,1] = "Ściana - Lewo"
o.display_description_item[o.display_page_two,2] = "Podłoga"
o.display_description_item[o.display_page_two,3] = "Sufit"
o.display_description_item[o.display_page_two,4] = "Zewnętrzny Narożnik 1"
o.display_description_item[o.display_page_two,5] = "Zewnętrzny Narożnik 2"
o.display_description_item[o.display_page_two,6] = "Zewnętrzny Narożnik 3"
o.display_description_item[o.display_page_two,7] = "Zewnętrzny Narożnik 4"
o.display_description_item[o.display_page_two,8] = "Wewnętrzny Narożnik 1"
o.display_description_item[o.display_page_two,9] = "Wewnętrzny Narożnik 2"
o.display_description_item[o.display_page_two,10] = "Wewnętrzny Narożnik 3"
o.display_description_item[o.display_page_two,11] = "Wewnętrzny Narożnik 4"
o.display_description_item[o.display_page_two,12] = "Cień 1"
o.display_description_item[o.display_page_two,13] = "Kolce 1"
o.display_description_item[o.display_page_two,14] = "Kolce 2"
o.display_description_item[o.display_page_two,15] = "Kolce 3"
o.display_description_item[o.display_page_two,16] = "Kolce 4"
o.display_description_item[o.display_page_two,17] = "Drabina"
o.display_description_item[o.display_page_two,18] = "Uchwyt 1"
o.display_description_item[o.display_page_two,19] = "Uchwyt 2"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Mała Rampa - 1"
o.display_description_item[o.display_page_three,1] = "Mała Rampa - 2"
o.display_description_item[o.display_page_three,2] = "Mała Rampa - 3"
o.display_description_item[o.display_page_three,3] = "Mała Rampa - 4"
o.display_description_item[o.display_page_three,4] = "Część Trawiastej Pętli 1"
o.display_description_item[o.display_page_three,5] = "Część Trawiastej Pętli 2"
o.display_description_item[o.display_page_three,6] = "Podłoga"
o.display_description_item[o.display_page_three,7] = "Część Pętli 1"
o.display_description_item[o.display_page_three,8] = "Część Pętli 2"
o.display_description_item[o.display_page_three,9] = "Część Pętli  3"
o.display_description_item[o.display_page_three,10] = "Część Pętli  4"
o.display_description_item[o.display_page_three,11] = "Część Trawiastej Pętli 3"
o.display_description_item[o.display_page_three,12] = "Część Trawiastej Pętli 4"
o.display_description_item[o.display_page_three,13] = "Część Dwustronnej Pętli 1"
o.display_description_item[o.display_page_three,14] = "Część Dwustronnej Pętli 2"
o.display_description_item[o.display_page_three,15] = "Część Dwustronnej Pętli 3"
o.display_description_item[o.display_page_three,16] = "Część Dwustronnej Pętli 4"
o.display_description_item[o.display_page_three,17] = "Długa Rampa 1"
o.display_description_item[o.display_page_three,18] = "Długa Rampa 2"
o.display_description_item[o.display_page_three,19] = "Piętrowa Platforma"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Płytki Zjazd w Dół - 1"
o.display_description_item[o.display_page_four,1] = "Płytki Zjazd w Dół - 2"
o.display_description_item[o.display_page_four,2] = "Ostry Zjazd w Dół - 1"
o.display_description_item[o.display_page_four,3] = "Ostry Zjazd w Dół - 2"
o.display_description_item[o.display_page_four,4] = "Płytki Zjazd w Dół - 3"
o.display_description_item[o.display_page_four,5] = "Płaska Powierzchnia 1"
o.display_description_item[o.display_page_four,6] = "Płytki Zjazd w Dół - 4"
o.display_description_item[o.display_page_four,7] = "Latająca Platforma 1"
o.display_description_item[o.display_page_four,8] = "Latająca Platforma 2"
o.display_description_item[o.display_page_four,9] = "Latająca Platforma 3"
o.display_description_item[o.display_page_four,10] = "Latająca Platforma 4"
o.display_description_item[o.display_page_four,11] = "Latająca Platforma 5"
o.display_description_item[o.display_page_four,12] = "Odwrót Trasy Platformy"
o.display_description_item[o.display_page_four,13] = "Blok Trawy"
o.display_description_item[o.display_page_four,14] = "Blok Ziemi"
o.display_description_item[o.display_page_four,15] = "Unknown Tile 3"
o.display_description_item[o.display_page_four,16] = "Unknown Tile 4"
o.display_description_item[o.display_page_four,17] = "Unknown Tile 5"
o.display_description_item[o.display_page_four,18] = "Unknown Tile 6"
o.display_description_item[o.display_page_four,19] = "Unknown Tile 7"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Sceneria - Most 1"
o.display_description_item[o.display_page_five,1] = "Sceneria - Kolumna"
o.display_description_item[o.display_page_five,2] = "Sceneria - Drzewo 1"
o.display_description_item[o.display_page_five,3] = "Sceneria - Krata"
o.display_description_item[o.display_page_five,4] = "Sceneria - Tło"
o.display_description_item[o.display_page_five,5] = "Sceneria - Platforma"
o.display_description_item[o.display_page_five,6] = "Sceneria - Fusuma 1"
o.display_description_item[o.display_page_five,7] = "Sceneria - Mural"
o.display_description_item[o.display_page_five,8] = "Sceneria - Zasłony"
o.display_description_item[o.display_page_five,9] = "Sceneria - Zasłony (Koniec)"
o.display_description_item[o.display_page_five,10] = "Sceneria - Barierka 1"
o.display_description_item[o.display_page_five,11] = "Sceneria - Podpora"
o.display_description_item[o.display_page_five,12] = "Sceneria - Latarnia 1"
o.display_description_item[o.display_page_five,13] = "Sceneria - Fusuma 2"
o.display_description_item[o.display_page_five,14] = "Sceneria - Drzewo 2"
o.display_description_item[o.display_page_five,15] = "Sceneria - Drzewo 3"
o.display_description_item[o.display_page_five,16] = "Sceneria - Drzewo 3 z Dekoracjami"
o.display_description_item[o.display_page_five,17] = "Sceneria - Drzewo 4"
o.display_description_item[o.display_page_five,18] = "Sceneria - Flaga 1"
o.display_description_item[o.display_page_five,19] = "Sceneria - Latarnia 2"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Cień 16x16"
o.display_description_item[o.display_page_six,1] = "Cień 32x32"
o.display_description_item[o.display_page_six,2] = "Cień 64x64"
o.display_description_item[o.display_page_six,3] = "Cień 96x96"
o.display_description_item[o.display_page_six,4] = "Cień 16x96"
o.display_description_item[o.display_page_six,5] = "Cień 96x16"
o.display_description_item[o.display_page_six,6] = "Cień 128x128"
o.display_description_item[o.display_page_six,7] = "Ciemność 128x128"
o.display_description_item[o.display_page_six,8] = "Sceneria - Duży Stół"
o.display_description_item[o.display_page_six,9] = "Sceneria - Mały Stół"
o.display_description_item[o.display_page_six,10] = "Unknown Tile"
o.display_description_item[o.display_page_six,11] = "Unknown Tile"
o.display_description_item[o.display_page_six,12] = "Unknown Tile"
o.display_description_item[o.display_page_six,13] = "Unknown Tile"
o.display_description_item[o.display_page_six,14] = "Unknown Tile"
o.display_description_item[o.display_page_six,15] = "Unknown Tile"
o.display_description_item[o.display_page_six,16] = "Unknown Tile"
o.display_description_item[o.display_page_six,17] = "Unknown Tile"
o.display_description_item[o.display_page_six,18] = "Unknown Tile"
o.display_description_item[o.display_page_six,19] = "Unknown Tile"

