switch(argument0)
    {
        case mu_slope_0:  {return 1; break;}
        case mu_slope_1:  {return 1; break;}
        case mu_slope_6:  {return 1; break;}
        case mu_slope_7:  {return 1; break;}
        case mu_slope_8:  {return 1; break;}
        case mu_slope_9:  {return 1; break;}
        case mu_slope_2:  {return 1; break;}
        case mu_slope_3:  {return 1; break;}
        case mu_slope_4:  {return 1; break;}
        case mu_slope_5:  {return 1; break;}
        case mu_slope_10: {return 1; break;}
        case mu_slope_11: {return 1; break;}
        case mu_slope_12: {return 1; break;}
        case mu_slope_13: {return 1; break;}
        case mu_slope_14: {return 1; break;}
        case mu_slope_15: {return 1; break;}
        case mu_slope_16: {return 1; break;}
        case mu_slope_17: {return 1; break;}
        case mu_slope_18: {return 1; break;}
        case mu_slope_19: {return 1; break;}
        case mu_slope_20: {return 1; break;}
        case mu_slope_21: {return 1; break;}
        case mu_slope_22: {return 1; break;}
        case mu_slope_23: {return 1; break;}
        case mu_slope_24: {return 1; break;}
        case mu_slope_25: {return 1; break;}
        case mu_slope_26: {return 1; break;}
        case mu_slope_27: {return 1; break;}
        case mu_ramp_0:   {return 1; break;}
        case mu_ramp_1:   {return 1; break;}
        case mu_ramp_2:   {return 1; break;}
        case mu_ramp_3:   {return 1; break;}
        case mu_ramp_4:   {return 1; break;}
        case mu_ramp_5:   {return 1; break;}
        case mu_ramp_6:   {return 1; break;}
        case mu_ramp_7:   {return 1; break;}
        case mu_ramp_8:   {return 1; break;}
        case mu_ramp_9:   {return 1; break;}
        case mu_ramp_16:  {return 1; break;}
        case mu_ramp_17:  {return 1; break;}
        case mu_ramp_18:  {return 1; break;}
        case mu_ramp_19:  {return 1; break;}
        case mu_ramp_20:  {return 1; break;}
        case mu_ramp_21:  {return 1; break;}
        case mu_ramp_22:  {return 1; break;}
        case mu_ramp_23:  {return 1; break;}
        case mu_ramp_24:  {return 1; break;}
        case mu_ramp_25:  {return 1; break;}
        case wd_ramp_0:   {return 1; break;}
        case wd_ramp_1:   {return 1; break;}
        case wd_ramp_2:   {return 1; break;}
        case wd_ramp_3:   {return 1; break;}
        case wd_ramp_4:   {return 1; break;}
        case wd_ramp_5:   {return 1; break;}
        case wd_ramp_6:   {return 1; break;}
        case wd_ramp_7:   {return 1; break;}
        case wd_ramp_8:   {return 1; break;}
        case wd_ramp_9:   {return 1; break;}
        case wd_ramp_10:  {return 1; break;}
        case wd_ramp_11:  {return 1; break;}
        case wd_ramp_12:  {return 1; break;}
        case wd_ramp_13:  {return 1; break;}
        case wd_ramp_14:  {return 1; break;}
        case wd_ramp_15:  {return 1; break;}
        case wd_slope_0:  {return 1; break;}
        case wd_slope_1:  {return 1; break;}
        case wd_slope_2:  {return 1; break;}
        case wd_slope_3:  {return 1; break;}
        case wd_slope_4:  {return 1; break;}
        case wd_slope_5:  {return 1; break;}
        case wd_slope_6:  {return 1; break;}
        case wd_slope_7:  {return 1; break;}
        case wd_slope_8:  {return 1; break;}
        case wd_slope_9:  {return 1; break;}
        case wd_slope_10: {return 1; break;}
        case wd_slope_11: {return 1; break;}
        case wd_slope_12: {return 1; break;}
        case wd_slope_13: {return 1; break;}
        case wd_slope_14: {return 1; break;}
        case wd_slope_15: {return 1; break;}
        case wd_slope_16: {return 1; break;}
        case wd_slope_17: {return 1; break;}
        case wd_slope_18: {return 1; break;}
        case wd_slope_19: {return 1; break;}
        case wd_slope_20: {return 1; break;}
        case wd_slope_21: {return 1; break;}
        case wd_slope_22: {return 1; break;}
        case wd_slope_23: {return 1; break;}
        case wd_slope_24: {return 1; break;}
        case wd_slope_25: {return 1; break;}
        case wd_slope_26: {return 1; break;}
        case wd_slope_27: {return 1; break;}
        case wd_slope_28: {return 1; break;}
        case wd_slope_29: {return 1; break;}
        case wd_slope_30: {return 1; break;}
        case wd_slope_31: {return 1; break;}
        case wd_donut_2: {return 1; break;}
        case wd_donut_3: {return 1; break;}
        case wd_donut_4: {return 1; break;}
        case wd_donut_5: {return 1; break;}
        case wd_donut_6: {return 1; break;}
        case wd_donut_7: {return 1; break;}
        case wd_donut_8: {return 1; break;}
        case wd_donut_9: {return 1; break;}
        case cs_ramp_6:   {return 1; break;}
        case cs_ramp_7:   {return 1; break;}
        case cs_ramp_8:   {return 1; break;}
        case cs_ramp_9:   {return 1; break;}
        case cs_ramp_18:  {return 1; break;}
        case cs_ramp_19:  {return 1; break;}
        case cs_ramp_20:  {return 1; break;}
        case cs_ramp_21:  {return 1; break;}
        case cs_loop_0:  {return 1; break;}
        case cs_loop_1:  {return 1; break;}
        case cs_loop_2:  {return 1; break;}
        case cs_loop_3:  {return 1; break;}
        case cs_loop_8:  {return 1; break;}
        case cs_loop_9:  {return 1; break;}
        case cs_loop_10: {return 1; break;}
        case cs_donut_2: {return 1; break;}
        case cs_donut_3: {return 1; break;}
        case cs_donut_4: {return 1; break;}
        case cs_donut_5: {return 1; break;}
        case cs_donut_6: {return 1; break;}
        case cs_donut_7: {return 1; break;}
        case cs_donut_8: {return 1; break;}
        case cs_donut_9: {return 1; break;}
        case mnt_slope_0: {return 1; break;}
        case mnt_slope_1: {return 1; break;}
        case mnt_slope_2: {return 1; break;}
        case mnt_slope_3: {return 1; break;}
        case mnt_slope_4: {return 1; break;}
        case mnt_slope_5: {return 1; break;}
        case mnt_slope_6: {return 1; break;}
        case mnt_slope_7: {return 1; break;}
        case mnt_slope_8: {return 1; break;}
        case mnt_slope_9: {return 1; break;}
        case mnt_slope_10: {return 1; break;}
        case mnt_slope_11: {return 1; break;}
        case mnt_slope_12: {return 1; break;}
        case mnt_slope_13: {return 1; break;}
        case mnt_slope_14: {return 1; break;}
        case mnt_slope_15: {return 1; break;}
        case mnt_slope_16: {return 1; break;}
        case mnt_slope_17: {return 1; break;}
        case mnt_slope_18: {return 1; break;}
        case mnt_slope_19: {return 1; break;}
        case mnt_slope_20: {return 1; break;}
        case mnt_slope_21: {return 1; break;}
        case mnt_slope_22: {return 1; break;}
        case mnt_slope_23: {return 1; break;}
        case mnt_slope_24: {return 1; break;}
        case mnt_slope_25: {return 1; break;}
        case mnt_slope_26: {return 1; break;}
        case mnt_slope_27: {return 1; break;}
        case mnt_slope_28: {return 1; break;}
        case mnt_slope_29: {return 1; break;}
        case mnt_slope_30: {return 1; break;}
        case mnt_slope_31: {return 1; break;}
        case mnt_ramp_0:  {return 1; break;}
        case mnt_ramp_1:  {return 1; break;}
        case mnt_ramp_2:  {return 1; break;}
        case mnt_ramp_3:  {return 1; break;}
        case mnt_ramp_4:  {return 1; break;}
        case mnt_ramp_5:  {return 1; break;}
        case mnt_ramp_6:  {return 1; break;}
        case mnt_ramp_7:  {return 1; break;}
        case mnt_ramp_8:  {return 1; break;}
        case mnt_ramp_9:  {return 1; break;}
        case mnt_ramp_10: {return 1; break;}
        case mnt_ramp_11: {return 1; break;}
        case mnt_ramp_12: {return 1; break;}
        case mnt_ramp_13: {return 1; break;}
        case mnt_ramp_14: {return 1; break;}
        case mnt_ramp_15: {return 1; break;}
        case mnt_ramp_22: {return 1; break;}
        case mnt_ramp_23: {return 1; break;}
        case mnt_ramp_24: {return 1; break;}
        case mnt_ramp_25: {return 1; break;}
        case ll_slope_4:  {return 1; break;}
        case ll_slope_5:  {return 1; break;}
        case ll_slope_6:  {return 1; break;}
        case ll_slope_7:  {return 1; break;}
        case ll_slope_8:  {return 1; break;}
        case ll_slope_9:  {return 1; break;}
        case ll_slope_10: {return 1; break;}
        case ll_slope_11: {return 1; break;}
        case ll_slope_12: {return 1; break;}
        case ll_slope_13: {return 1; break;}
        case ll_slope_14: {return 1; break;}
        case ll_slope_15: {return 1; break;}
        case ll_slope_16: {return 1; break;}
        case ll_slope_17: {return 1; break;}
        case ll_slope_18: {return 1; break;}
        case ll_slope_19: {return 1; break;}
        case ll_slope_20: {return 1; break;}
        case ll_slope_21: {return 1; break;}
        case ll_slope_22: {return 1; break;}
        case ll_slope_23: {return 1; break;}
        case ll_slope_39: {return 1; break;}
        case ll_slope_40: {return 1; break;}
        case ll_slope_41: {return 1; break;}
        case ll_slope_42: {return 1; break;}
        case ll_loop_2:   {return 1; break;}
        case ll_loop_3:   {return 1; break;}
        case ll_loop_4:   {return 1; break;}
        case ll_loop_5:   {return 1; break;}
        case ll_loop_6:   {return 1; break;}
        case ll_loop_7:   {return 1; break;}
        case ll_loop_8:   {return 1; break;}
        case ll_loop_9:   {return 1; break;}
        case ll_donut_2: {return 1; break;}
        case ll_donut_3: {return 1; break;}
        case ll_donut_4: {return 1; break;}
        case ll_donut_5: {return 1; break;}
        case ll_donut_6: {return 1; break;}
        case ll_donut_7: {return 1; break;}
        case ll_donut_8: {return 1; break;}
        case ll_donut_9: {return 1; break;}
        //case bb_slope_0: {return 1; break;}
        //case bb_slope_1: {return 1; break;}
        //case bb_slope_2: {return 1; break;}
        //case bb_slope_3: {return 1; break;}
        case bb_slope_10: {return 1; break;}
        case bb_slope_11: {return 1; break;}
        case bb_slope_12: {return 1; break;}
        case bb_slope_13: {return 1; break;}
        case bb_slope_14: {return 1; break;}
        case bb_slope_15: {return 1; break;}
        case bb_slope_16: {return 1; break;}
        case bb_slope_17: {return 1; break;}
        case bb_donut_6:  {return 1; break;}
        case bb_donut_7:  {return 1; break;}
        case bb_donut_8:  {return 1; break;}
        case bb_donut_9:  {return 1; break;}
        case bb_donut_2:  {return 1; break;}
        case bb_donut_3:  {return 1; break;}
        case bb_donut_4:  {return 1; break;}
        case bb_donut_5:  {return 1; break;}
        case bb_donut_6_alt:  {return 1; break;}
        case bb_donut_7_alt:  {return 1; break;}
        case bb_donut_8_alt:  {return 1; break;}
        case bb_donut_9_alt:  {return 1; break;}
        case bb_donut_2_alt:  {return 1; break;}
        case bb_donut_3_alt:  {return 1; break;}
        case bb_donut_4_alt:  {return 1; break;}
        case bb_donut_5_alt:  {return 1; break;}
        case sj_slope_10:     {return 1; break;}
        case sj_slope_11:     {return 1; break;}
        case sj_slope_12:     {return 1; break;}
        case sj_slope_13:     {return 1; break;}
        case sj_slope_14:     {return 1; break;}
        case sj_slope_15:     {return 1; break;}
        case sj_slope_16:     {return 1; break;}
        case sj_slope_17:     {return 1; break;}
        case sj_slope_10_alt: {return 1; break;}
        case sj_slope_11_alt: {return 1; break;}
        case sj_slope_12_alt: {return 1; break;}
        case sj_slope_13_alt: {return 1; break;}
        case sj_slope_14_alt: {return 1; break;}
        case sj_slope_15_alt: {return 1; break;}
        case sj_slope_16_alt: {return 1; break;}
        case sj_slope_17_alt: {return 1; break;}
        case sj_slope_2:      {return 1; break;}
        case sj_slope_3:      {return 1; break;}
        case sj_slope_4:      {return 1; break;}
        case sj_slope_5:      {return 1; break;}
        case sj_slope_6:      {return 1; break;}
        case sj_slope_7:      {return 1; break;}
        case sj_slope_8:      {return 1; break;}
        case sj_slope_9:      {return 1; break;}
        case sj_donut_2:      {return 1; break;}
        case sj_donut_3:      {return 1; break;}
        case sj_donut_4:      {return 1; break;}
        case sj_donut_5:      {return 1; break;}
        case sj_donut_6:      {return 1; break;}
        case sj_donut_7:      {return 1; break;}
        case sj_donut_8:      {return 1; break;}
        case sj_donut_9:      {return 1; break;}
        case sj_ramp_4:       {return 1; break;}
        case sj_ramp_5:       {return 1; break;}
        case sj_ramp_16:       {return 1; break;}
        case sj_ramp_17:       {return 1; break;}
        case rg_rail_sloped_1: {return 1; break;}
        case rg_rail_sloped_2: {return 1; break;}
        case rg_rail_slope_6:  {return 1; break;}
        case rg_rail_slope_7:  {return 1; break;}
        case rg_rail_slope_8:  {return 1; break;}
        case rg_rail_slope_9:  {return 1; break;}
        case rg_rail_slope_2:  {return 1; break;}
        case rg_rail_slope_3:  {return 1; break;}
        case rg_rail_slope_4:  {return 1; break;}
        case rg_rail_slope_5:  {return 1; break;}
        case rg_rail_ramp_4:   {return 1; break;}
        case rg_rail_ramp_5:   {return 1; break;}
        case rg_rail_ramp_16:  {return 1; break;}
        case rg_rail_ramp_17:  {return 1; break;}
        default: {return 0; break;}
    }
