///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Plattformen"
o.display_page_description[1] = "Gras"
o.display_page_description[2] = "Pisten"
o.display_page_description[3] = "Plattformen"
o.display_page_description[4] = "Landschaft"
o.display_page_description[5] = "Steinig"
o.display_page_description[6] = "Schnee"
o.display_page_description[7] = "Tempel 1"
o.display_page_description[8] = "Tempel 2"
o.display_page_description[9] = "Innen"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Flacher Stein 1"
o.display_description_item[o.display_page_one,1] = "Flacher Klippenrand - Links"
o.display_description_item[o.display_page_one,2] = "Flacher Klippenrand - Rechts"
o.display_description_item[o.display_page_one,3] = "Flache Steinwand 1"
o.display_description_item[o.display_page_one,4] = "Flache Steinwand 2"
o.display_description_item[o.display_page_one,5] = "Holzbalken Kante - Links"
o.display_description_item[o.display_page_one,6] = "Holzbalken"
o.display_description_item[o.display_page_one,7] = "Holzbalken Kante - Rechts"
o.display_description_item[o.display_page_one,8] = "Bambusstiel - Groß"
o.display_description_item[o.display_page_one,9] = "Bambusstiel - Klein"
o.display_description_item[o.display_page_one,10] = "Bambusstiele - Dünn"
o.display_description_item[o.display_page_one,11] = "Bambusstiel - Groß Gelb"
o.display_description_item[o.display_page_one,12] = "Bambusstiel - Dünn Gelb"
o.display_description_item[o.display_page_one,13] = "Bambusstiel - Plattform"
o.display_description_item[o.display_page_one,14] = "Bambusstiel - Plattform Gelb"
o.display_description_item[o.display_page_one,15] = "Bambusstiel - Klein Plattform"
o.display_description_item[o.display_page_one,16] = "Bambusstiel - Klein Plattform Gelb"
o.display_description_item[o.display_page_one,17] = "Berggras"
o.display_description_item[o.display_page_one,18] = "Bergdreck - Breit"
o.display_description_item[o.display_page_one,19] = "Bergdreck - Klein"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Berggras - Ausgesetzte Kante Rechts"
o.display_description_item[o.display_page_two,1] = "Berggras - Ausgesetzte Wand Links"
o.display_description_item[o.display_page_two,2] = "Berggras - Ausgesetzte Kante Links"
o.display_description_item[o.display_page_two,3] = "Berggras - Ausgesetzte Wand Rechts"
o.display_description_item[o.display_page_two,4] = "Berggras - Upside Down"
o.display_description_item[o.display_page_two,5] = "Berggras - Ecke Piece Links"
o.display_description_item[o.display_page_two,6] = "Berggras - Grass Wand Links"
o.display_description_item[o.display_page_two,7] = "Berggras - Grass Kante Rechts"
o.display_description_item[o.display_page_two,8] = "Berggras - Ecke Piece Rechts"
o.display_description_item[o.display_page_two,9] = "Berggras - Grass Wand Rechts"
o.display_description_item[o.display_page_two,10] = "Berggras - Grass Kante Links"
o.display_description_item[o.display_page_two,11] = "Berggras - Grass Kante Upside-Down"
o.display_description_item[o.display_page_two,12] = "Berggras - Grass Kante Upside-Down"
o.display_description_item[o.display_page_two,13] = "Steinige Stacheln 1"
o.display_description_item[o.display_page_two,14] = "Steinige Stacheln 2"
o.display_description_item[o.display_page_two,15] = "Steinige Stacheln 3"
o.display_description_item[o.display_page_two,16] = "Steinige Stacheln 4"
o.display_description_item[o.display_page_two,17] = "Leiter"
o.display_description_item[o.display_page_two,18] = "Holzhangbar 1"
o.display_description_item[o.display_page_two,19] = "Holzhangbar 2"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Kleine Rampe - 1"
o.display_description_item[o.display_page_three,1] = "Kleine Rampe - 2"
o.display_description_item[o.display_page_three,2] = "Kleine Rampe - 3"
o.display_description_item[o.display_page_three,3] = "Kleine Rampe - 4"
o.display_description_item[o.display_page_three,4] = "Stein. Donutschleuße - Außen 1"
o.display_description_item[o.display_page_three,5] = "Stein. Donutschleuße - Außen 2"
o.display_description_item[o.display_page_three,6] = "Hangbar 2"
o.display_description_item[o.display_page_three,7] = "Stein. Donutschleuße - Innen 1"
o.display_description_item[o.display_page_three,8] = "Stein. Donutschleuße - Innen 2"
o.display_description_item[o.display_page_three,9] = "Stein. Donutschleuße - Innen 3"
o.display_description_item[o.display_page_three,10] = "Stein. Donutschleuße - Innen 4"
o.display_description_item[o.display_page_three,11] = "Stein. Donutschleuße - Außen 3"
o.display_description_item[o.display_page_three,12] = "Stein. Donutschleuße - Außen 4"
o.display_description_item[o.display_page_three,13] = "Gras. Schleußenteil 1"
o.display_description_item[o.display_page_three,14] = "Gras. Schleußenteil 2"
o.display_description_item[o.display_page_three,15] = "Gras. Schleußenteil 3"
o.display_description_item[o.display_page_three,16] = "Gras. Schleußenteil 4"
o.display_description_item[o.display_page_three,17] = "Gras. Pistenlangteil 1"
o.display_description_item[o.display_page_three,18] = "Gras. Pistenlangteil 2"
o.display_description_item[o.display_page_three,19] = "Stein. Bodenüberplattform"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Steinpiste Runter"
o.display_description_item[o.display_page_four,1] = "Steinpiste Herauf"
o.display_description_item[o.display_page_four,2] = "Graspiste Runter"
o.display_description_item[o.display_page_four,3] = "Graspiste Herauf"
o.display_description_item[o.display_page_four,4] = "Runtergeh. Piste - Flach 3"
o.display_description_item[o.display_page_four,5] = "Flache Ebene 1"
o.display_description_item[o.display_page_four,6] = "Runtergeh. Piste - Flach 4"
o.display_description_item[o.display_page_four,7] = "Schweb. Plattform 1"
o.display_description_item[o.display_page_four,8] = "Schweb. Plattform 2"
o.display_description_item[o.display_page_four,9] = "Schweb. Plattform 3"
o.display_description_item[o.display_page_four,10] = "Schweb. Plattform 4"
o.display_description_item[o.display_page_four,11] = "Schweb. Plattform 5"
o.display_description_item[o.display_page_four,12] = "Umgek. Plattform"
o.display_description_item[o.display_page_four,13] = "Landschaft - Verdecktes Eckteil Stein 1"
o.display_description_item[o.display_page_four,14] = "Landschaft - Verdecktes Eckteil Stein 2"
o.display_description_item[o.display_page_four,15] = "Landschaft - Verdecktes Eckteil Stein 3"
o.display_description_item[o.display_page_four,16] = "Landschaft - Verdecktes Eckteil Stein 4"
o.display_description_item[o.display_page_four,17] = "Landschaft - Shang Mu Rote Laternenpflanze"
o.display_description_item[o.display_page_four,18] = "Landschaft - Shang Mu Orangene Laternenpflanze"
o.display_description_item[o.display_page_four,19] = "Landschaft - Dunkles Tile"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Landschaft - Stein 1"
o.display_description_item[o.display_page_five,1] = "Landschaft - Stein 2"
o.display_description_item[o.display_page_five,2] = "Landschaft - Stein 3"
o.display_description_item[o.display_page_five,3] = "Landschaft - Stein 4"
o.display_description_item[o.display_page_five,4] = "Landschaft - Stein 5"
o.display_description_item[o.display_page_five,5] = "Landschaft - Stein Wand 1"
o.display_description_item[o.display_page_five,6] = "Landschaft - Stein Wand 2"
o.display_description_item[o.display_page_five,7] = "Landschaft - Stein verd. - Horizontal"
o.display_description_item[o.display_page_five,8] = "Landschaft - Stein verd. - Vertikal"
o.display_description_item[o.display_page_five,9] = "Landschaft - Brückenposten"
o.display_description_item[o.display_page_five,10] = "Landschaft - Brückenteil"
o.display_description_item[o.display_page_five,11] = "Landschaft - Baum 1"
o.display_description_item[o.display_page_five,12] = "Landschaft - Grass"
o.display_description_item[o.display_page_five,13] = "Landschaft - Stein verd. - Alt."
o.display_description_item[o.display_page_five,14] = "Landschaft - Bambusblume"
o.display_description_item[o.display_page_five,15] = "Landschaft - Bambusstiel"
o.display_description_item[o.display_page_five,16] = "Landschaft - Baum 2"
o.display_description_item[o.display_page_five,17] = "Landschaft - Busch"
o.display_description_item[o.display_page_five,18] = "Landschaft - Baumäste"
o.display_description_item[o.display_page_five,19] = "Bambusstiel - Groß Wand"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Stein Oberfläche 1"
o.display_description_item[o.display_page_six,1] = "Stein Oberfläche 2"
o.display_description_item[o.display_page_six,2] = "Stein Decke 1"
o.display_description_item[o.display_page_six,3] = "Stein Decke 2"
o.display_description_item[o.display_page_six,4] = "Stein Kante 1"
o.display_description_item[o.display_page_six,5] = "Stein Oberfläche 3"
o.display_description_item[o.display_page_six,6] = "Stein Kante 2"
o.display_description_item[o.display_page_six,7] = "Stein Innen 1"
o.display_description_item[o.display_page_six,8] = "Stein Innen 2"
o.display_description_item[o.display_page_six,9] = "Stein Decke 3"
o.display_description_item[o.display_page_six,10] = "Stein Wand 1"
o.display_description_item[o.display_page_six,11] = "Stein Wand 2"
o.display_description_item[o.display_page_six,12] = "Stein Wand 3"
o.display_description_item[o.display_page_six,13] = "Stein Innen 3"
o.display_description_item[o.display_page_six,14] = "Stein Innen 4"
o.display_description_item[o.display_page_six,15] = "Stein Wand 4"
o.display_description_item[o.display_page_six,16] = "Stein Wand 5"
o.display_description_item[o.display_page_six,17] = "Stein Decke 4"
o.display_description_item[o.display_page_six,18] = "Stein Decke 5"
o.display_description_item[o.display_page_six,19] = "Stein Decke 6"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Schnee Oberfläche 1"
o.display_description_item[o.display_page_seven,1] = "Schnee Oberfläche 2"
o.display_description_item[o.display_page_seven,2] = "Schnee Oberfläche 3"
o.display_description_item[o.display_page_seven,3] = "Schnee Oberfläche 4"
o.display_description_item[o.display_page_seven,4] = "Schnee Oberfläche 5"
o.display_description_item[o.display_page_seven,5] = "Schnee Oberfläche 6"
o.display_description_item[o.display_page_seven,6] = "Schnee Oberfläche 7"
o.display_description_item[o.display_page_seven,7] = "Schnee Decke 1"
o.display_description_item[o.display_page_seven,8] = "Schnee Decke 2"
o.display_description_item[o.display_page_seven,9] = "Schnee Decke 3"
o.display_description_item[o.display_page_seven,10] = "Schnee Wand 1"
o.display_description_item[o.display_page_seven,11] = "Schnee Wand 2"
o.display_description_item[o.display_page_seven,12] = "Schnee Wand 3"
o.display_description_item[o.display_page_seven,13] = "Snowy Baum 1"
o.display_description_item[o.display_page_seven,14] = "Schnee Panda 1"
o.display_description_item[o.display_page_seven,15] = "Schnee Panda 2"
o.display_description_item[o.display_page_seven,16] = "Schnee Cat"
o.display_description_item[o.display_page_seven,17] = "Schnee Kid 1"
o.display_description_item[o.display_page_seven,18] = "Schnee Kid 2"
o.display_description_item[o.display_page_seven,19] = "Schnee Kid 3"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Tempel - Fusama 1"
o.display_description_item[o.display_page_eight,1] = "Tempel - Fusama 2"
o.display_description_item[o.display_page_eight,2] = "Tempel - Fusama 3"
o.display_description_item[o.display_page_eight,3] = "Tempel - Fusama 4"
o.display_description_item[o.display_page_eight,4] = "Tempel - Fusama 5"
o.display_description_item[o.display_page_eight,5] = "Tempel - Fusama 6"
o.display_description_item[o.display_page_eight,6] = "Tempel - Wand 1"
o.display_description_item[o.display_page_eight,7] = "Tempel - Wand 2"
o.display_description_item[o.display_page_eight,8] = "Tempel - Wand 3"
o.display_description_item[o.display_page_eight,9] = "Tempel - Wand 4"
o.display_description_item[o.display_page_eight,10] = "Tempel - Decke - Links"
o.display_description_item[o.display_page_eight,11] = "Tempel - Decke - Mitte"
o.display_description_item[o.display_page_eight,12] = "Tempel - Decke - Rechts"
o.display_description_item[o.display_page_eight,13] = "Tempel - Balken"
o.display_description_item[o.display_page_eight,14] = "Tempel - Balken - Klein"
o.display_description_item[o.display_page_eight,15] = "Tempel - Balken - Groß"
o.display_description_item[o.display_page_eight,16] = "Tempel - Balken - Ecke 1"
o.display_description_item[o.display_page_eight,17] = "Tempel - Balken - Ecke 2"
o.display_description_item[o.display_page_eight,18] = "Tempel - Balken - Ecke 3"
o.display_description_item[o.display_page_eight,19] = "Tempel - Balken - Ecke 4"

//Tile Descriptions (Page 9)
o.display_description_item[o.display_page_nine,0] = "Tempel - Torii"
o.display_description_item[o.display_page_nine,1] = "Tempel - Komplette Decke"
o.display_description_item[o.display_page_nine,2] = "Tempel - Laternenstand"
o.display_description_item[o.display_page_nine,3] = "Tempel - Lampenposten"
o.display_description_item[o.display_page_nine,4] = "Tempel - Schildposten"
o.display_description_item[o.display_page_nine,5] = "Tempel - Dächerstatue"
o.display_description_item[o.display_page_nine,6] = "Tempel - Flagge"
o.display_description_item[o.display_page_nine,7] = "Holzbalken - Links"
o.display_description_item[o.display_page_nine,8] = "Holzbalken - Mitte"
o.display_description_item[o.display_page_nine,9] = "Holzbalken - Rechts"
o.display_description_item[o.display_page_nine,10] = "Holzbalken - Oben"
o.display_description_item[o.display_page_nine,11] = "Holzbalken - Mitte"
o.display_description_item[o.display_page_nine,12] = "Holzbalken - Unten"
o.display_description_item[o.display_page_nine,13] = "Zelt"
o.display_description_item[o.display_page_nine,14] = "Klappstuhl"
o.display_description_item[o.display_page_nine,15] = "Geröstete Marshmallows"
o.display_description_item[o.display_page_nine,16] = "Campfeuer - Flammen"
o.display_description_item[o.display_page_nine,17] = "Tempel - Willkommen"
o.display_description_item[o.display_page_nine,18] = "Unknown Tile"
o.display_description_item[o.display_page_nine,19] = "Unknown Tile"

//Tile Descriptions (Page 10)
o.display_description_item[o.display_page_ten,0] = "Bücherregal - Groß"
o.display_description_item[o.display_page_ten,1] = "Bücherregal - Klein"
o.display_description_item[o.display_page_ten,2] = "Kabinett - Links"
o.display_description_item[o.display_page_ten,3] = "Kabinett - Rechts"
o.display_description_item[o.display_page_ten,4] = "Kühlschrank"
o.display_description_item[o.display_page_ten,5] = "Tisch - Klein"
o.display_description_item[o.display_page_ten,6] = "Tisch - Groß"
o.display_description_item[o.display_page_ten,7] = "Hallenlampe"
o.display_description_item[o.display_page_ten,8] = "TV Set"
o.display_description_item[o.display_page_ten,9] = "Wohnzimmercouch"
o.display_description_item[o.display_page_ten,10] = "Bett"
o.display_description_item[o.display_page_ten,11] = "Ofen und Herd"
o.display_description_item[o.display_page_ten,12] = "Holzstuhl"
o.display_description_item[o.display_page_ten,13] = "Kabinett - Klein"
o.display_description_item[o.display_page_ten,14] = "Toaster"
o.display_description_item[o.display_page_ten,15] = "Gardinen - Groß"
o.display_description_item[o.display_page_ten,16] = "Gardinen - Klein"
o.display_description_item[o.display_page_ten,17] = "Wanduhr"
o.display_description_item[o.display_page_ten,18] = "Alarm"
o.display_description_item[o.display_page_ten,19] = "Unknown Tile"

//Tile Descriptions (Page 11)
o.display_description_item[o.display_page_eleven,0] = "Grass Flat Left"
o.display_description_item[o.display_page_eleven,1] = "Grass Flat"
o.display_description_item[o.display_page_eleven,2] = "Grass Flat Right"
o.display_description_item[o.display_page_eleven,3] = "Grass Flat Large"
o.display_description_item[o.display_page_eleven,4] = "Grass Flat Thin"
o.display_description_item[o.display_page_eleven,5] = "Dirt"
o.display_description_item[o.display_page_eleven,6] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,7] = "Dirt Wall Left"
o.display_description_item[o.display_page_eleven,8] = "Dirt"
o.display_description_item[o.display_page_eleven,9] = "Dirt Wall Right"
o.display_description_item[o.display_page_eleven,10] = "Grassy Slope 1"
o.display_description_item[o.display_page_eleven,11] = "Grassy Slope 1"
o.display_description_item[o.display_page_eleven,12] = "Grassy Slope 1"
o.display_description_item[o.display_page_eleven,13] = "Dirt Ceiling Left"
o.display_description_item[o.display_page_eleven,14] = "Dirt Ceiling"
o.display_description_item[o.display_page_eleven,15] = "Dirt Ceiling Right"
o.display_description_item[o.display_page_eleven,16] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,17] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,18] = "Unknown Tile"
o.display_description_item[o.display_page_eleven,19] = "Unknown Tile"

//Tile Descriptions (Page 12)
o.display_description_item[o.display_page_twelve,0] = "Wood Block Left"
o.display_description_item[o.display_page_twelve,1] = "Wood Block Horizontal"
o.display_description_item[o.display_page_twelve,2] = "Wood Block Right"
o.display_description_item[o.display_page_twelve,3] = "Wood Block Top"
o.display_description_item[o.display_page_twelve,4] = "Wood Block Vertical"
o.display_description_item[o.display_page_twelve,5] = "Wood Block Bottom"
o.display_description_item[o.display_page_twelve,6] = "Broken Paper Lamp"
o.display_description_item[o.display_page_twelve,7] = "Wood Ramp Left"
o.display_description_item[o.display_page_twelve,8] = "Wood Ramp Right"
o.display_description_item[o.display_page_twelve,9] = "Unknown Tile"
o.display_description_item[o.display_page_twelve,10] = "Unknown Tile"
o.display_description_item[o.display_page_twelve,11] = "Unknown Tile"
o.display_description_item[o.display_page_twelve,12] = "Unknown Tile"
o.display_description_item[o.display_page_twelve,13] = "Damaged Wall 1"
o.display_description_item[o.display_page_twelve,14] = "Damaged Wall 2"
o.display_description_item[o.display_page_twelve,15] = "Dragon Scroll"
o.display_description_item[o.display_page_twelve,16] = "Katana in Stone"
o.display_description_item[o.display_page_twelve,17] = "Unknown Tile"
o.display_description_item[o.display_page_twelve,18] = "Unknown Tile"
o.display_description_item[o.display_page_twelve,19] = "Unknown Tile"

