///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Platformy"
o.display_page_description[1] = "Ściany"
o.display_page_description[2] = "Rampy"
o.display_page_description[3] = "Sceneria"
o.display_page_description[4] = "Extra"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Panelowa Podłoga 1"
o.display_description_item[o.display_page_one,1] = "Panelowa Podłoga 2"
o.display_description_item[o.display_page_one,2] = "Panelowa Podłoga 3"
o.display_description_item[o.display_page_one,3] = "Część Mostu 1"
o.display_description_item[o.display_page_one,4] = "Część Mostu 2"
o.display_description_item[o.display_page_one,5] = "Część Mostu 3"
o.display_description_item[o.display_page_one,6] = "Część Mostu 4"
o.display_description_item[o.display_page_one,7] = "Panel Ścienny 1"
o.display_description_item[o.display_page_one,8] = "Panel Ścienny 2"
o.display_description_item[o.display_page_one,9] = "Panel Ścienny 3"
o.display_description_item[o.display_page_one,10] = "Część Mostu 5"
o.display_description_item[o.display_page_one,11] = "Panel Ścienny 4"
o.display_description_item[o.display_page_one,12] = "Część Mostu 6"
o.display_description_item[o.display_page_one,13] = "Panel Sufitowy 1"
o.display_description_item[o.display_page_one,14] = "Panel Sufitowy 2"
o.display_description_item[o.display_page_one,15] = "Panel Sufitowy 3"
o.display_description_item[o.display_page_one,16] = "Wewnętrzny Panel 1"
o.display_description_item[o.display_page_one,17] = "Wewnętrzny Panel 2"
o.display_description_item[o.display_page_one,18] = "Wewnętrzny Panel 3"
o.display_description_item[o.display_page_one,19] = "Wewnętrzny Panel 4"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Panel Ścienny 4"
o.display_description_item[o.display_page_two,1] = "Panel Ścienny 5"
o.display_description_item[o.display_page_two,2] = "Panel Ścienny 6"
o.display_description_item[o.display_page_two,3] = "Duży Wentylator"
o.display_description_item[o.display_page_two,4] = "Panel Ścienny 7"
o.display_description_item[o.display_page_two,5] = "Panel Ścienny 8"
o.display_description_item[o.display_page_two,6] = "Panel Ścienny 9"
o.display_description_item[o.display_page_two,7] = "Podpora 1"
o.display_description_item[o.display_page_two,8] = "Podpora 2"
o.display_description_item[o.display_page_two,9] = "Podpora 3"
o.display_description_item[o.display_page_two,10] = ""
o.display_description_item[o.display_page_two,11] = ""
o.display_description_item[o.display_page_two,12] = ""
o.display_description_item[o.display_page_two,13] = ""
o.display_description_item[o.display_page_two,14] = ""
o.display_description_item[o.display_page_two,15] = ""
o.display_description_item[o.display_page_two,16] = ""
o.display_description_item[o.display_page_two,17] = ""
o.display_description_item[o.display_page_two,18] = ""
o.display_description_item[o.display_page_two,19] = ""

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Panelowa Podłoga - Rampa 1"
o.display_description_item[o.display_page_three,1] = "Panelowa Podłoga - Rampa 2"
o.display_description_item[o.display_page_three,2] = "Most - Rampa 1"
o.display_description_item[o.display_page_three,3] = "Most - Rampa 2"
o.display_description_item[o.display_page_three,4] = "Latająca Platforma 1"
o.display_description_item[o.display_page_three,5] = "Latająca Sfera"
o.display_description_item[o.display_page_three,6] = "Latająca Ukruszona Sfera"
o.display_description_item[o.display_page_three,7] = "Panelowa Pętla 1"
o.display_description_item[o.display_page_three,8] = "Panelowa Pętla 2"
o.display_description_item[o.display_page_three,9] = "Odsłonięta Pętla 1"
o.display_description_item[o.display_page_three,10] = "Odsłonięta Pętla 2"
o.display_description_item[o.display_page_three,11] = ""
o.display_description_item[o.display_page_three,12] = ""
o.display_description_item[o.display_page_three,13] = "Panelowa Pętla 3"
o.display_description_item[o.display_page_three,14] = "Panelowa Pętla 4"
o.display_description_item[o.display_page_three,15] = "Odsłonięta Pętla 3"
o.display_description_item[o.display_page_three,16] = "Odsłonięta Pętla 4"
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Drzwi Laboratoryjne"
o.display_description_item[o.display_page_four,1] = "Bezpieczniki (Zamknięte)"
o.display_description_item[o.display_page_four,2] = "Bezpieczniki (Otwarte)"
o.display_description_item[o.display_page_four,3] = "Pudełko z Częściami 1"
o.display_description_item[o.display_page_four,4] = "Znak Personal Protection Equipment"
o.display_description_item[o.display_page_four,5] = "Pudełko z Częściami 2"
o.display_description_item[o.display_page_four,6] = "Stacja Robocza"
o.display_description_item[o.display_page_four,7] = "Nadajnik"
o.display_description_item[o.display_page_four,8] = "Nadajnik Wi-Fi"
o.display_description_item[o.display_page_four,9] = "Wyłączony Dron"
o.display_description_item[o.display_page_four,10] = "Barierka"
o.display_description_item[o.display_page_four,11] = ""
o.display_description_item[o.display_page_four,12] = ""
o.display_description_item[o.display_page_four,13] = ""
o.display_description_item[o.display_page_four,14] = ""
o.display_description_item[o.display_page_four,15] = ""
o.display_description_item[o.display_page_four,16] = ""
o.display_description_item[o.display_page_four,17] = ""
o.display_description_item[o.display_page_four,18] = ""
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = ""
o.display_description_item[o.display_page_five,1] = ""
o.display_description_item[o.display_page_five,2] = ""
o.display_description_item[o.display_page_five,3] = ""
o.display_description_item[o.display_page_five,4] = ""
o.display_description_item[o.display_page_five,5] = ""
o.display_description_item[o.display_page_five,6] = ""
o.display_description_item[o.display_page_five,7] = ""
o.display_description_item[o.display_page_five,8] = ""
o.display_description_item[o.display_page_five,9] = ""
o.display_description_item[o.display_page_five,10] = ""
o.display_description_item[o.display_page_five,11] = ""
o.display_description_item[o.display_page_five,12] = ""
o.display_description_item[o.display_page_five,13] = ""
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = ""
o.display_description_item[o.display_page_six,1] = ""
o.display_description_item[o.display_page_six,2] = ""
o.display_description_item[o.display_page_six,3] = ""
o.display_description_item[o.display_page_six,4] = ""
o.display_description_item[o.display_page_six,5] = ""
o.display_description_item[o.display_page_six,6] = ""
o.display_description_item[o.display_page_six,7] = ""
o.display_description_item[o.display_page_six,8] = ""
o.display_description_item[o.display_page_six,9] = ""
o.display_description_item[o.display_page_six,10] = ""
o.display_description_item[o.display_page_six,11] = ""
o.display_description_item[o.display_page_six,12] = ""
o.display_description_item[o.display_page_six,13] = ""
o.display_description_item[o.display_page_six,14] = ""
o.display_description_item[o.display_page_six,15] = ""
o.display_description_item[o.display_page_six,16] = ""
o.display_description_item[o.display_page_six,17] = ""
o.display_description_item[o.display_page_six,18] = ""
o.display_description_item[o.display_page_six,19] = ""

