///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Platformy"
o.display_page_description[1] = "Belki"
o.display_page_description[2] = "Rampy"
o.display_page_description[3] = "Sceneria 1"
o.display_page_description[4] = "Sceneria 2"
o.display_page_description[5] = "Sceneria 3"
o.display_page_description[6] = "Sceneria 4"
o.display_page_description[7] = "Sceneria 5"
o.display_page_description[8] = "Nieużytki"
o.display_page_description[9] = "Extra 1"
o.display_page_description[10] = "Extras 2"
o.display_page_description[11] = "Alt. Cegły"
o.display_page_description[12] = "Extras 3"
o.display_page_description[13] = "Extras 4"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Ceglana Platforma 1"
o.display_description_item[o.display_page_one,1] = "Ceglana Platforma 2"
o.display_description_item[o.display_page_one,2] = "Ceglana Ściana 1"
o.display_description_item[o.display_page_one,3] = "Ceglana Ściana 2"
o.display_description_item[o.display_page_one,4] = "Ceglana Ściana 3"
o.display_description_item[o.display_page_one,5] = "Ceglana Ściana 4"
o.display_description_item[o.display_page_one,6] = "Ceglany Blok 1"
o.display_description_item[o.display_page_one,7] = "Ceglany Blok 2"
o.display_description_item[o.display_page_one,8] = "Ceglany Blok 3"
o.display_description_item[o.display_page_one,9] = "Czerwona Cegła"
o.display_description_item[o.display_page_one,10] = "Niebieska Cegła"
o.display_description_item[o.display_page_one,11] = "Rozdzielacz Ścian 1"
o.display_description_item[o.display_page_one,12] = "Rozdzielacz Ścian 2"
o.display_description_item[o.display_page_one,13] = "Rura - Płaska 1"
o.display_description_item[o.display_page_one,14] = "Rura - Płaska 2"
o.display_description_item[o.display_page_one,15] = "Rura - Płaska 3"
o.display_description_item[o.display_page_one,16] = "Rura - Płaska 4"
o.display_description_item[o.display_page_one,17] = "Końcówka Rury 1"
o.display_description_item[o.display_page_one,18] = "Końcówka Rury 2"
o.display_description_item[o.display_page_one,19] = "Końcówka Rury 3"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Belka Budowlana - Czerwona 1"
o.display_description_item[o.display_page_two,1] = "Belka Budowlana - Czerwona 2"
o.display_description_item[o.display_page_two,2] = "Belka Budowlana - Żółta 1"
o.display_description_item[o.display_page_two,3] = "Belka Budowlana - Żółta 2"
o.display_description_item[o.display_page_two,4] = "Belka Budowlana - Czerwona 3"
o.display_description_item[o.display_page_two,5] = "Belka Budowlana - Czerwona 4"
o.display_description_item[o.display_page_two,6] = "Belka Budowlana - Żółta 3"
o.display_description_item[o.display_page_two,7] = "Podpora - Żółta 1"
o.display_description_item[o.display_page_two,8] = "Podpora - Żółta 2"
o.display_description_item[o.display_page_two,9] = "Podpora - Czerwona 1"
o.display_description_item[o.display_page_two,10] = "Podpora - Czerwona 2"
o.display_description_item[o.display_page_two,11] = "Podpora - Czerwona 3"
o.display_description_item[o.display_page_two,12] = "Podpora - Żółta 3"
o.display_description_item[o.display_page_two,13] = "Betonowa Ściana - 1"
o.display_description_item[o.display_page_two,14] = "Betonowa Ściana - 2"
o.display_description_item[o.display_page_two,15] = "Chodnik - 1"
o.display_description_item[o.display_page_two,16] = "Chodnik - 2"
o.display_description_item[o.display_page_two,17] = "Chodnik - 3"
o.display_description_item[o.display_page_two,18] = "Chodnik - 4"
o.display_description_item[o.display_page_two,19] = "Belka Budowlana - Żółta 3"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Ćwierć Rury 1"
o.display_description_item[o.display_page_three,1] = "Ćwierć Rury 2"
o.display_description_item[o.display_page_three,2] = "Ćwierć Rury 3"
o.display_description_item[o.display_page_three,3] = "Ćwierć Rury 4"
o.display_description_item[o.display_page_three,4] = "Ćwierć Rury 1 - Odwrócona"
o.display_description_item[o.display_page_three,5] = "Ćwierć Rury 2 - Odwrócona"
o.display_description_item[o.display_page_three,6] = "Latająca Platforma 1"
o.display_description_item[o.display_page_three,7] = "Część Pętli 1"
o.display_description_item[o.display_page_three,8] = "Część Pętli 2"
o.display_description_item[o.display_page_three,9] = "Część Pętli 3"
o.display_description_item[o.display_page_three,10] = "Część Pętli 4"
o.display_description_item[o.display_page_three,11] = "Ćwierć Rury 3 - Odwrócona"
o.display_description_item[o.display_page_three,12] = "Ćwierć Rury 4 - Odwrócona"
o.display_description_item[o.display_page_three,13] = "Ulica - Rampa 1"
o.display_description_item[o.display_page_three,14] = "Ulica - Rampa 2"
o.display_description_item[o.display_page_three,15] = "Ulica - Rampa 3"
o.display_description_item[o.display_page_three,16] = "Ulica - Rampa 4"
o.display_description_item[o.display_page_three,17] = "Nachylona Ulica - Lewo"
o.display_description_item[o.display_page_three,18] = "Nachylona Ulica - Prawo"
o.display_description_item[o.display_page_three,19] = "Latająca Platforma 2"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Okno - Duże"
o.display_description_item[o.display_page_four,1] = "Okno - Małe 1"
o.display_description_item[o.display_page_four,2] = "Okno - Małe 2"
o.display_description_item[o.display_page_four,3] = "Klimatyzacja 1"
o.display_description_item[o.display_page_four,4] = "Klimatyzacja 2"
o.display_description_item[o.display_page_four,5] = "Teleskop reflektorowy"
o.display_description_item[o.display_page_four,6] = "Teleskop refraktorowy"
o.display_description_item[o.display_page_four,7] = "Sceneria - Rura - Łącznik Pionowy"
o.display_description_item[o.display_page_four,8] = "Sceneria - Rura - Łącznik Poziomy"
o.display_description_item[o.display_page_four,9] = "Sceneria - Rura - Góra"
o.display_description_item[o.display_page_four,10] = "Sceneria - Rura - Dół"
o.display_description_item[o.display_page_four,11] = "Słup Elektryczny - Czubek"
o.display_description_item[o.display_page_four,12] = "Słup Elektryczny"
o.display_description_item[o.display_page_four,13] = "Parasol"
o.display_description_item[o.display_page_four,14] = "Logo Lodowych Komet Ziyo"
o.display_description_item[o.display_page_four,15] = "Napój Lodowy 1"
o.display_description_item[o.display_page_four,16] = "Napój Lodowy 2"
o.display_description_item[o.display_page_four,17] = "Napój Lodowy 3"
o.display_description_item[o.display_page_four,18] = "Miska z Lodami"
o.display_description_item[o.display_page_four,19] = "Banana Split"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Sceneria - Podpora 1"
o.display_description_item[o.display_page_five,1] = "Sceneria - Barierka"
o.display_description_item[o.display_page_five,2] = "Sceneria - Chodnik"
o.display_description_item[o.display_page_five,3] = "Sceneria - Ulica"
o.display_description_item[o.display_page_five,4] = "Sceneria - Rama Okna"
o.display_description_item[o.display_page_five,5] = "Sceneria - Billboard 1"
o.display_description_item[o.display_page_five,6] = "Sceneria - Billboard 2"
o.display_description_item[o.display_page_five,7] = "Sceneria - Ceglana Ściana 1"
o.display_description_item[o.display_page_five,8] = "Sceneria - Ceglana Ściana 2"
o.display_description_item[o.display_page_five,9] = "Sceneria - Ceglana Ściana 3"
o.display_description_item[o.display_page_five,10] = "Sceneria - Budynek 1"
o.display_description_item[o.display_page_five,11] = "Sceneria - Budynek 2"
o.display_description_item[o.display_page_five,12] = "Sceneria - Wieża Ciśnień"
o.display_description_item[o.display_page_five,13] = "Sceneria - Plakat Starbuster"
o.display_description_item[o.display_page_five,14] = "Sceneria - Plakat HavocFox"
o.display_description_item[o.display_page_five,15] = "Sceneria - Reklama 1"
o.display_description_item[o.display_page_five,16] = "Sceneria - Reklama 2"
o.display_description_item[o.display_page_five,17] = "Sceneria - Znak Stop"
o.display_description_item[o.display_page_five,18] = "Sceneria - Znak Pierwszeństwa"
o.display_description_item[o.display_page_five,19] = "Sceneria - Przejście dla Ninja"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Kosz do Recyklingu"
o.display_description_item[o.display_page_six,1] = "Pojemnik na Śmieci"
o.display_description_item[o.display_page_six,2] = "Znak Drogowy - East Road"
o.display_description_item[o.display_page_six,3] = "Znak Drogowy - North Circle"
o.display_description_item[o.display_page_six,4] = "Znak Drogowy - South Drive"
o.display_description_item[o.display_page_six,5] = "Znak Drogowy - West Lane"
o.display_description_item[o.display_page_six,6] = "Znak Drogowy - Pusty"
o.display_description_item[o.display_page_six,7] = "Strzałka"
o.display_description_item[o.display_page_six,8] = "Znak - Mokra Podłoga"
o.display_description_item[o.display_page_six,9] = "Światła Drogowe"
o.display_description_item[o.display_page_six,10] = "Oświetlenie Uliczne"
o.display_description_item[o.display_page_six,11] = "Lampa Uliczna 1"
o.display_description_item[o.display_page_six,12] = "Lampa Uliczna 2"
o.display_description_item[o.display_page_six,13] = "Lampa Uliczna 3"
o.display_description_item[o.display_page_six,14] = "Krzak"
o.display_description_item[o.display_page_six,15] = "Wyjątkowy Bakłażan"
o.display_description_item[o.display_page_six,16] = "Linka na Ubrania"
o.display_description_item[o.display_page_six,17] = "Znak - Przejście dla Pieszych"
o.display_description_item[o.display_page_six,18] = "Światła dla Pieszych"
o.display_description_item[o.display_page_six,19] = "Kosz na Śmieci"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Żółta Podpora - Cała 1"
o.display_description_item[o.display_page_seven,1] = "Kątowa Żółta Podpora 1"
o.display_description_item[o.display_page_seven,2] = "Kątowa Żółta Podpora 2"
o.display_description_item[o.display_page_seven,3] = "Kątowa Czerwona Podpora 1"
o.display_description_item[o.display_page_seven,4] = "Kątowa Czerwona Podpora 2"
o.display_description_item[o.display_page_seven,5] = "Podpora - Czerwona 3"
o.display_description_item[o.display_page_seven,6] = "Żółta Podpora - Cała 2"
o.display_description_item[o.display_page_seven,7] = "Żółta Podpora - Część 1"
o.display_description_item[o.display_page_seven,8] = "Żółta Podpora - Część 2"
o.display_description_item[o.display_page_seven,9] = "Żółta Podpora - Część 3"
o.display_description_item[o.display_page_seven,10] = "Żółta Podpora - Część 4"
o.display_description_item[o.display_page_seven,11] = "Żółta Podpora - Część 5"
o.display_description_item[o.display_page_seven,12] = "Żółta Podpora - Część 6"
o.display_description_item[o.display_page_seven,13] = "Podpora Budowlana - Pozioma"
o.display_description_item[o.display_page_seven,14] = "Stożek drogowy - Duży"
o.display_description_item[o.display_page_seven,15] = "Stożek drogowy - Mały"
o.display_description_item[o.display_page_seven,16] = "Stożek drogowy - 1"
o.display_description_item[o.display_page_seven,17] = "Stożek drogowy - 2"
o.display_description_item[o.display_page_seven,18] = "Stożek drogowy - 3"
o.display_description_item[o.display_page_seven,19] = "Stożek drogowy - 4"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Sceneria - Rura - Góra"
o.display_description_item[o.display_page_eight,1] = "Sceneria - Rura - Pionowe Łącze"
o.display_description_item[o.display_page_eight,2] = "Sceneria - Rura - Dół"
o.display_description_item[o.display_page_eight,3] = "Sceneria - Rura - Poziome Łącze"
o.display_description_item[o.display_page_eight,4] = "Stół Restauracyjny"
o.display_description_item[o.display_page_eight,5] = "Duża Półka"
o.display_description_item[o.display_page_eight,6] = "Pozioma Rura"
o.display_description_item[o.display_page_eight,7] = "Belka Budowlana - Średnia 1"
o.display_description_item[o.display_page_eight,8] = "Belka Budowlana - Średnia 2"
o.display_description_item[o.display_page_eight,9] = "Belka Budowlana - Średnia 3"
o.display_description_item[o.display_page_eight,10] = "Belka Budowlana - Średnia 4"
o.display_description_item[o.display_page_eight,11] = "Sceneria - Płot Pikietowy"
o.display_description_item[o.display_page_eight,12] = "Podpora Budowlana - Mała"
o.display_description_item[o.display_page_eight,13] = "Metalowe Kolce - 1"
o.display_description_item[o.display_page_eight,14] = "Metalowe Kolce - 2"
o.display_description_item[o.display_page_eight,15] = "Metalowe Kolce - 3"
o.display_description_item[o.display_page_eight,16] = "Metalowe Kolce - 4"
o.display_description_item[o.display_page_eight,17] = "Drabina 1"
o.display_description_item[o.display_page_eight,18] = "Drabina 2"
o.display_description_item[o.display_page_eight,19] = "Uchwyt 1"

//Tile Descriptions (Page 9)
o.display_description_item[o.display_page_nine,0] = "Ceglana Platforma - Nieużywana 1"
o.display_description_item[o.display_page_nine,1] = "Ceglana Platforma - Nieużywana 2"
o.display_description_item[o.display_page_nine,2] = "Ceglana Ściana - Nieużywana 1"
o.display_description_item[o.display_page_nine,3] = "Ceglana Ściana - Nieużywana 2"
o.display_description_item[o.display_page_nine,4] = "Ceglana Ściana - Nieużywana 3"
o.display_description_item[o.display_page_nine,5] = "Ceglana Platforma - Nieużywana 3"
o.display_description_item[o.display_page_nine,6] = "Ceglana Ściana - Nieużywana 4"
o.display_description_item[o.display_page_nine,7] = "Ceglana Ściana - Nieużywana 5"
o.display_description_item[o.display_page_nine,8] = "Chodnik - Nieużywany 1"
o.display_description_item[o.display_page_nine,9] = "Ceglana Ściana - Nieużywana 6"
o.display_description_item[o.display_page_nine,10] = "Ceglana Ściana - Nieużywana 7"
o.display_description_item[o.display_page_nine,11] = "Pusty Billboard - Nieużywany 1"
o.display_description_item[o.display_page_nine,12] = "Pusty Billboard - Nieużywany 2"
o.display_description_item[o.display_page_nine,13] = "Pusty Billboard - Nieużywany 3"
o.display_description_item[o.display_page_nine,14] = "Rura - Nieużywana 1"
o.display_description_item[o.display_page_nine,15] = "Rura - Nieużywana 2"
o.display_description_item[o.display_page_nine,16] = "Rura - Nieużywana 3"
o.display_description_item[o.display_page_nine,17] = "Rura - Nieużywana 4"
o.display_description_item[o.display_page_nine,18] = "Unknown Tile"
o.display_description_item[o.display_page_nine,19] = "Unknown Tile"

//Tile Descriptions (Page 10)
o.display_description_item[o.display_page_ten,0] = "Ceglana Ściana - Extra 1"
o.display_description_item[o.display_page_ten,1] = "Ceglana Ściana - Extra 2"
o.display_description_item[o.display_page_ten,2] = "Ceglana Ściana - Extra 3"
o.display_description_item[o.display_page_ten,3] = "Ceglana Ściana - Extra 4"
o.display_description_item[o.display_page_ten,4] = "Ceglana Ściana - Extra 5"
o.display_description_item[o.display_page_ten,5] = "Ceglana Ściana - Extra 6"
o.display_description_item[o.display_page_ten,6] = "Ceglana Ściana - Extra 7"
o.display_description_item[o.display_page_ten,7] = "Narożnik 1"
o.display_description_item[o.display_page_ten,8] = "Narożnik 2"
o.display_description_item[o.display_page_ten,9] = "Narożnik 3"
o.display_description_item[o.display_page_ten,10] = "Narożnik 4"
o.display_description_item[o.display_page_ten,11] = "Ceglana Ściana - Extra 8"
o.display_description_item[o.display_page_ten,12] = "Ceglana Ściana - Extra 9"
o.display_description_item[o.display_page_ten,13] = "Narożnik 5"
o.display_description_item[o.display_page_ten,14] = "Narożnik 6"
o.display_description_item[o.display_page_ten,15] = "Narożnik 7"
o.display_description_item[o.display_page_ten,16] = "Ceglana Platforma - Lewa Krawędź"
o.display_description_item[o.display_page_ten,17] = "Ceglana Platforma - Środek"
o.display_description_item[o.display_page_ten,18] = "Ceglana Platforma - Prawa Krawędź"
o.display_description_item[o.display_page_ten,19] = "Ceglana Ściana - Extra 10"

//Tile Descriptions (Page 11)
o.display_description_item[o.display_page_eleven,0] = "Ceglana Pętla - 1"
o.display_description_item[o.display_page_eleven,1] = "Ceglana Pętla - 2"
o.display_description_item[o.display_page_eleven,2] = "Ceglana Ściana - Extra 3"
o.display_description_item[o.display_page_eleven,3] = "Ceglana Ściana - Extra 4"
o.display_description_item[o.display_page_eleven,4] = "Ceglana Ściana - Extra 5"
o.display_description_item[o.display_page_eleven,5] = "Ceglana Ściana - Extra 6"
o.display_description_item[o.display_page_eleven,6] = "Ceglana Ściana - Extra 7"
o.display_description_item[o.display_page_eleven,7] = "Ceglana Pętla - 3"
o.display_description_item[o.display_page_eleven,8] = "Ceglana Pętla - 4"
o.display_description_item[o.display_page_eleven,9] = "Narożnik 3"
o.display_description_item[o.display_page_eleven,10] = "Narożnik 4"
o.display_description_item[o.display_page_eleven,11] = "Ceglana Ściana - Extra 8"
o.display_description_item[o.display_page_eleven,12] = "Ceglana Ściana - Extra 9"
o.display_description_item[o.display_page_eleven,13] = "Narożnik 5"
o.display_description_item[o.display_page_eleven,14] = "Narożnik 6"
o.display_description_item[o.display_page_eleven,15] = "Narożnik 7"
o.display_description_item[o.display_page_eleven,16] = "Ceglana Platforma - Lewa Krawędź"
o.display_description_item[o.display_page_eleven,17] = "Ceglana Platforma - Środek"
o.display_description_item[o.display_page_eleven,18] = "Ceglana Platforma - Prawa Krawędź"
o.display_description_item[o.display_page_eleven,19] = "Ceglana Ściana - Extra 10"

//Tile Descriptions (Page 12)
o.display_description_item[o.display_page_twelve,0] = "Ceglana Platforma 1"
o.display_description_item[o.display_page_twelve,1] = "Ceglana Platforma 2"
o.display_description_item[o.display_page_twelve,2] = "Ceglana Ściana 1"
o.display_description_item[o.display_page_twelve,3] = "Ceglana Ściana 2"
o.display_description_item[o.display_page_twelve,4] = "Ceglana Ściana 3"
o.display_description_item[o.display_page_twelve,5] = "Ceglana Ściana 4"
o.display_description_item[o.display_page_twelve,6] = "Ceglany Blok 1"
o.display_description_item[o.display_page_twelve,7] = "Ceglany Blok 2"
o.display_description_item[o.display_page_twelve,8] = "Ceglany Blok 3"
o.display_description_item[o.display_page_twelve,9] = "Czerwona Cegła"
o.display_description_item[o.display_page_twelve,10] = "Niebieska Cegła"
o.display_description_item[o.display_page_twelve,11] = "Rozdzielacz Ścian 1"
o.display_description_item[o.display_page_twelve,12] = "Rozdzielacz Ścian 2"
o.display_description_item[o.display_page_twelve,13] = "Rura - Płaska 1"
o.display_description_item[o.display_page_twelve,14] = "Rura - Płaska 2"
o.display_description_item[o.display_page_twelve,15] = "Rura - Płaska 3"
o.display_description_item[o.display_page_twelve,16] = "Rura - Płaska 4"
o.display_description_item[o.display_page_twelve,17] = "Końcówka Rury 1"
o.display_description_item[o.display_page_twelve,18] = "Końcówka Rury 2"
o.display_description_item[o.display_page_twelve,19] = "Końcówka Rury 3"

//Tile Descriptions (Page 13)
o.display_description_item[o.display_page_thirteen,0] = "Znak - Dragon Road"
o.display_description_item[o.display_page_thirteen,1] = "Znak - Pheasant Lane"
o.display_description_item[o.display_page_thirteen,2] = "Znak - Fantail Road"
o.display_description_item[o.display_page_thirteen,3] = "Znak - Panya Plaza"
o.display_description_item[o.display_page_thirteen,4] = "Znak - Fuzhu Lane"
o.display_description_item[o.display_page_thirteen,5] = "Znak - Qilin Lane"
o.display_description_item[o.display_page_thirteen,6] = "Znak - Pheonix Road"
o.display_description_item[o.display_page_thirteen,7] = "Znak Autostradowy 1"
o.display_description_item[o.display_page_thirteen,8] = "Znak Autostradowy 2"
o.display_description_item[o.display_page_thirteen,9] = "Znak Autostradowy - Podpora 1"
o.display_description_item[o.display_page_thirteen,10] = "Znak Autostradowy - Podpora 2"
o.display_description_item[o.display_page_thirteen,11] = "Znak Autostradowy - Podpora 3"
o.display_description_item[o.display_page_thirteen,12] = "Znak Autostradowy - Podpora 4"
o.display_description_item[o.display_page_thirteen,13] = "Smocza Świątynia - Podpora"
o.display_description_item[o.display_page_thirteen,14] = "Smocza Świątynia - Lampa"
o.display_description_item[o.display_page_thirteen,15] = "Smocza Świątynia - Brama"
o.display_description_item[o.display_page_thirteen,16] = "Smocza Świątynia - Barierka"
o.display_description_item[o.display_page_thirteen,17] = "Smocza Świątynia - Słup Barierki"
o.display_description_item[o.display_page_thirteen,18] = "Bambus"
o.display_description_item[o.display_page_thirteen,19] = "Obraz Fuzhu"

//Tile Descriptions (Page 14)
o.display_description_item[o.display_page_fourteen,0] = "Smocza Świątynia - Statua Smoka"
o.display_description_item[o.display_page_fourteen,1] = "Smocza Świątynia - Statua Fuzhu"
o.display_description_item[o.display_page_fourteen,2] = "Alt. Znak Restauracji - Sushi Panya"
o.display_description_item[o.display_page_fourteen,3] = "Smocza Świątynia - Mural Smoka"
o.display_description_item[o.display_page_fourteen,4] = "Bar Sushi Tuńczyka Timmiego - Znak"
o.display_description_item[o.display_page_fourteen,5] = "Tabliczka Zamknięte"
o.display_description_item[o.display_page_fourteen,6] = "Tabliczka Otwarte"
o.display_description_item[o.display_page_fourteen,7] = ""
o.display_description_item[o.display_page_fourteen,8] = ""
o.display_description_item[o.display_page_fourteen,9] = ""
o.display_description_item[o.display_page_fourteen,10] = ""
o.display_description_item[o.display_page_fourteen,11] = ""
o.display_description_item[o.display_page_fourteen,12] = ""
o.display_description_item[o.display_page_fourteen,13] = ""
o.display_description_item[o.display_page_fourteen,14] = ""
o.display_description_item[o.display_page_fourteen,15] = ""
o.display_description_item[o.display_page_fourteen,16] = ""
o.display_description_item[o.display_page_fourteen,17] = ""
o.display_description_item[o.display_page_fourteen,18] = ""
o.display_description_item[o.display_page_fourteen,19] = ""

