///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Plataformas "
o.display_page_description[1] = "Plomería"
o.display_page_description[2] = "Decoracion"
o.display_page_description[3] = "Pasto/Tierra"
o.display_page_description[4] = "Extras"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Plataforma de Ladrillos - Agrietada 1"
o.display_description_item[o.display_page_one,1] = "Plataforma de Ladrillos - Agrietada 2"
o.display_description_item[o.display_page_one,2] = "Plataforma de Ladrillos - Agrietada 3"
o.display_description_item[o.display_page_one,3] = "Pared de Ladrillos - Agrietada 1"
o.display_description_item[o.display_page_one,4] = "Pared de Ladrillos - Agrietada 2"
o.display_description_item[o.display_page_one,5] = "Pared de Ladrillos - Agrietada 3"
o.display_description_item[o.display_page_one,6] = "Pared de Ladrillos 1"
o.display_description_item[o.display_page_one,7] = "Pared de Ladrillos 2"
o.display_description_item[o.display_page_one,8] = "Pared de Ladrillos 3"
o.display_description_item[o.display_page_one,9] = "Pared de Ladrillos 4"
o.display_description_item[o.display_page_one,10] = "Pared de Ladrillos 5"
o.display_description_item[o.display_page_one,11] = "Ladrillo Pequeño 1"
o.display_description_item[o.display_page_one,12] = "Ladrillo Pequeño 2"
o.display_description_item[o.display_page_one,13] = "Tuberia Pequeña 1"
o.display_description_item[o.display_page_one,14] = "Tubería Grande 1"
o.display_description_item[o.display_page_one,15] = "Tubería Grande 2"
o.display_description_item[o.display_page_one,16] = "Tubería Grande 3"
o.display_description_item[o.display_page_one,17] = "Conector de Tubería 1"
o.display_description_item[o.display_page_one,18] = "Conector de Tubería 2"
o.display_description_item[o.display_page_one,19] = "Conector de Tubería 3"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Pared de Alcantarilla 1"
o.display_description_item[o.display_page_two,1] = "Pared de Alcantarilla 2"
o.display_description_item[o.display_page_two,2] = "Pared de Alcantarilla 1"
o.display_description_item[o.display_page_two,3] = "Pared de Alcantarilla 2"
o.display_description_item[o.display_page_two,4] = "Pared de Alcantarilla 3"
o.display_description_item[o.display_page_two,5] = "Pared de Alcantarilla 4"
o.display_description_item[o.display_page_two,6] = "Pared de Alcantarilla 5"
o.display_description_item[o.display_page_two,7] = "Tubería Inclinada 1"
o.display_description_item[o.display_page_two,8] = "Tubería Inclinada 2"
o.display_description_item[o.display_page_two,9] = "Tubería Inclinada 3"
o.display_description_item[o.display_page_two,10] = "Tubería Inclinada 4"
o.display_description_item[o.display_page_two,11] = "Viga de Soporte para Construcción 1"
o.display_description_item[o.display_page_two,12] = "Viga de Soporte para Construcción 2"
o.display_description_item[o.display_page_two,13] = "Pinchos 1"
o.display_description_item[o.display_page_two,14] = "Pinchos 2"
o.display_description_item[o.display_page_two,15] = "Pinchos 3"
o.display_description_item[o.display_page_two,16] = "Pinchos 4"
o.display_description_item[o.display_page_two,17] = "Escalera 1"
o.display_description_item[o.display_page_two,18] = "Escalera 2"
o.display_description_item[o.display_page_two,19] = "Barra Suspendida 1"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Ventana - Verde - Grande"
o.display_description_item[o.display_page_three,1] = "Ventana - Verde - Pequeña"
o.display_description_item[o.display_page_three,2] = "Ventana - Azul - Pequeña"
o.display_description_item[o.display_page_three,3] = "Viga de Soporte 1"
o.display_description_item[o.display_page_three,4] = "Viga de Soporte 2"
o.display_description_item[o.display_page_three,5] = "Viga de Soporte 3"
o.display_description_item[o.display_page_three,6] = "Viga de Soporte Angulada - Completa"
o.display_description_item[o.display_page_three,7] = "Viga de Soporte Angulada - Inferior"
o.display_description_item[o.display_page_three,8] = "Viga de Soporte Angulada - Parte Central"
o.display_description_item[o.display_page_three,9] = "Viga de Soporte Angulada - Superior"
o.display_description_item[o.display_page_three,10] = "Viga de Soporte Angulada - Inferior"
o.display_description_item[o.display_page_three,11] = "Viga de Soporte Angulada - Parte Central"
o.display_description_item[o.display_page_three,12] = "Viga de Soporte Angulada - Superior"
o.display_description_item[o.display_page_three,13] = "Pieza de Esquina - 1"
o.display_description_item[o.display_page_three,14] = "Pieza de Esquina - 2"
o.display_description_item[o.display_page_three,15] = "Pieza de Esquina - 3"
o.display_description_item[o.display_page_three,16] = "Pieza de Esquina - 4"
o.display_description_item[o.display_page_three,17] = "Pieza de Esquina - 5"
o.display_description_item[o.display_page_three,18] = "Pieza de Esquina - 6"
o.display_description_item[o.display_page_three,19] = "Pieza de Esquina - Parte Central"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Hierba - Esquina Izquierda"
o.display_description_item[o.display_page_four,1] = "Hierba- Superior"
o.display_description_item[o.display_page_four,2] = "Hierba - Esquina Derecha"
o.display_description_item[o.display_page_four,3] = "Pendiente de Hierba 1"
o.display_description_item[o.display_page_four,4] = "Pendiente de Hierba 2"
o.display_description_item[o.display_page_four,5] = "Pendiente de Hierba 3"
o.display_description_item[o.display_page_four,6] = "Ambiente - Hierba"
o.display_description_item[o.display_page_four,7] = "Tierra - Pared Izquierda "
o.display_description_item[o.display_page_four,8] = "Tierra - Pequeña"
o.display_description_item[o.display_page_four,9] = "Tierra - Pared Derecha"
o.display_description_item[o.display_page_four,10] = "Hierba - Plana - Grande"
o.display_description_item[o.display_page_four,11] = "Hierba - Imparejo"
o.display_description_item[o.display_page_four,12] = "Hierba - Plana - Grande"
o.display_description_item[o.display_page_four,13] = "Hierba - Esquina - Izquierda"
o.display_description_item[o.display_page_four,14] = "Hierba - Inferior"
o.display_description_item[o.display_page_four,15] = "Hierba - Esquina Derecha"
o.display_description_item[o.display_page_four,16] = "Tierra Grande"
o.display_description_item[o.display_page_four,17] = "Pendiente de Tierra 1"
o.display_description_item[o.display_page_four,18] = "Pendiente de Tierra 2"
o.display_description_item[o.display_page_four,19] = "Pendiente de Tierra 3"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Bucle Circular 1"
o.display_description_item[o.display_page_five,1] = "Bucle Circular 2"
o.display_description_item[o.display_page_five,2] = "Bucle de Tuberías 1"
o.display_description_item[o.display_page_five,3] = "Bucle de Tuberías 2"
o.display_description_item[o.display_page_five,4] = "Bloque de Tierra Plana - Extra 1"
o.display_description_item[o.display_page_five,5] = "Bloque de Tierra Plana - Extra 2"
o.display_description_item[o.display_page_five,6] = "Bloque de Tierra Plana - Extra 3"
o.display_description_item[o.display_page_five,7] = "Bucle Circular 3"
o.display_description_item[o.display_page_five,8] = "Bucle Circular 4"
o.display_description_item[o.display_page_five,9] = "Bucle de Tuberías 3"
o.display_description_item[o.display_page_five,10] = "Bucle de Tuberías 4"
o.display_description_item[o.display_page_five,11] = "Bloque de Tierra Plana - Extra 4"
o.display_description_item[o.display_page_five,12] = "Bloque de Tierra Plana - Extra 5"
o.display_description_item[o.display_page_five,13] = "Pared Limpia 1"
o.display_description_item[o.display_page_five,14] = "Pared Limpia 2"
o.display_description_item[o.display_page_five,15] = "Piso Limpio 1"
o.display_description_item[o.display_page_five,16] = "Piso Limpio 1"
o.display_description_item[o.display_page_five,17] = "Piso Limpio 2"
o.display_description_item[o.display_page_five,18] = "Piso Limpio 3"
o.display_description_item[o.display_page_five,19] = "Pared Limpia 4"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Basurero de Reciclaje"
o.display_description_item[o.display_page_six,1] = "Señal de Cruce de Ninjas"
o.display_description_item[o.display_page_six,2] = "Señal de Avenida Este"
o.display_description_item[o.display_page_six,3] = "Señal de Glorieta Norte"
o.display_description_item[o.display_page_six,4] = "Señal de Calle Sur"
o.display_description_item[o.display_page_six,5] = "Señal de Via Oeste"
o.display_description_item[o.display_page_six,6] = "Señal en Blanco"
o.display_description_item[o.display_page_six,7] = "Señal de Flecha"
o.display_description_item[o.display_page_six,8] = "Papelera de Reciclaje"
o.display_description_item[o.display_page_six,9] = "Semáforo"
o.display_description_item[o.display_page_six,10] = "Poste de Luz"
o.display_description_item[o.display_page_six,11] = "Poste 1"
o.display_description_item[o.display_page_six,12] = "Poste 2"
o.display_description_item[o.display_page_six,13] = "Poste 3"
o.display_description_item[o.display_page_six,14] = "Arbusto"
o.display_description_item[o.display_page_six,15] = "Berenjena Única"
o.display_description_item[o.display_page_six,16] = "Tendedero"
o.display_description_item[o.display_page_six,17] = "Señal de Cruce de Peatones"
o.display_description_item[o.display_page_six,18] = "Señal de Peatones"
o.display_description_item[o.display_page_six,19] = "Cesto de Basura"

