ini_open_ns(program_directory + "gamedata.dat")
//Keyboard Bindings (Player Mode)
ini_write_string("keyboard_editor_bindings","move_left",string(o.key_move_left))
ini_write_string("keyboard_editor_bindings","move_right",string(o.key_move_right))
ini_write_string("keyboard_editor_bindings","move_up",string(o.key_move_up))
ini_write_string("keyboard_editor_bindings","move_down",string(o.key_move_down))
ini_write_string("keyboard_editor_bindings","mode",string(o.key_mode))
ini_write_string("keyboard_editor_bindings","delete",string(o.key_delete))
ini_write_string("keyboard_editor_bindings","put_here",string(o.key_put_here))
ini_write_string("keyboard_editor_bindings","copy",string(o.key_copy))
ini_write_string("keyboard_editor_bindings","layer_up",string(o.key_layer_up))
ini_write_string("keyboard_editor_bindings","layer_down",string(o.key_layer_down))
ini_write_string("keyboard_editor_bindings","snap_up",string(o.key_snap_up))
ini_write_string("keyboard_editor_bindings","zoom",string(o.key_zoom))
ini_write_string("keyboard_editor_bindings","pause",string(o.key_pause))
ini_write_string("keyboard_editor_bindings","new_tile",string(o.key_new_tile))
ini_write_string("keyboard_editor_bindings","undo",string(o.key_undo))
ini_write_string("keyboard_editor_bindings","redo",string(o.key_redo))
//Joystick Modern Bindings (Player Mode)
ini_write_string("joystick_modern_editor_bindings","move_left",string(o.joy_move_left))
ini_write_string("joystick_modern_editor_bindings","move_right",string(o.joy_move_right))
ini_write_string("joystick_modern_editor_bindings","move_up",string(o.joy_move_up))
ini_write_string("joystick_modern_editor_bindings","move_down",string(o.joy_move_down))
ini_write_string("joystick_modern_editor_bindings","mode",string(o.joy_mode))
ini_write_string("joystick_modern_editor_bindings","delete",string(o.joy_delete))
ini_write_string("joystick_modern_editor_bindings","put_here",string(o.joy_put_here))
ini_write_string("joystick_modern_editor_bindings","copy",string(o.joy_copy))
ini_write_string("joystick_modern_editor_bindings","layer_up",string(o.joy_layer_up))
ini_write_string("joystick_modern_editor_bindings","layer_down",string(o.joy_layer_down))
ini_write_string("joystick_modern_editor_bindings","snap_up",string(o.joy_snap_up))
ini_write_string("joystick_modern_editor_bindings","zoom",string(o.joy_zoom))
ini_write_string("joystick_modern_editor_bindings","pause",string(o.joy_pause))
ini_write_string("joystick_modern_editor_bindings","new_tile",string(o.joy_new_tile))
ini_write_string("joystick_modern_editor_bindings","undo",string(o.joy_undo))
ini_write_string("joystick_modern_editor_bindings","redo",string(o.joy_redo))
//Close INI Configuration File
ini_close_ns();
saving_prompt = 120
