///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Beams"
o.display_page_description[1] = "Walls"
o.display_page_description[2] = "Slopes"
o.display_page_description[3] = "Platforms"
o.display_page_description[4] = "Scenery 1"
o.display_page_description[5] = "Scenery 2"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Wood Block 1"
o.display_description_item[o.display_page_one,1] = "Floor Tile"
o.display_description_item[o.display_page_one,2] = "Support Beam 1"
o.display_description_item[o.display_page_one,3] = "Wood Block 2"
o.display_description_item[o.display_page_one,4] = "Wood Block 3"
o.display_description_item[o.display_page_one,5] = "Wood Block 4"
o.display_description_item[o.display_page_one,6] = "Wood Block 5"
o.display_description_item[o.display_page_one,7] = "Wood Block 6"
o.display_description_item[o.display_page_one,8] = "Support Beam 2"
o.display_description_item[o.display_page_one,9] = "Wood Block 7"
o.display_description_item[o.display_page_one,10] = "Wood Block 8"
o.display_description_item[o.display_page_one,11] = "Wood Block 9"
o.display_description_item[o.display_page_one,12] = "Wood Block 10"
o.display_description_item[o.display_page_one,13] = "Support Beam 3"
o.display_description_item[o.display_page_one,14] = "Corner Piece - Left"
o.display_description_item[o.display_page_one,15] = "Wooden Beam"
o.display_description_item[o.display_page_one,16] = "Corner Piece - Right"
o.display_description_item[o.display_page_one,17] = "Wood Block 11"
o.display_description_item[o.display_page_one,18] = "Corner Piece - Up"
o.display_description_item[o.display_page_one,19] = "Corner Piece - Down"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Wall - Right"
o.display_description_item[o.display_page_two,1] = "Wall - Left"
o.display_description_item[o.display_page_two,2] = "Floor"
o.display_description_item[o.display_page_two,3] = "Ceiling"
o.display_description_item[o.display_page_two,4] = "Outside Corner 1"
o.display_description_item[o.display_page_two,5] = "Outside Corner 2"
o.display_description_item[o.display_page_two,6] = "Outside Corner 3"
o.display_description_item[o.display_page_two,7] = "Outside Corner 4"
o.display_description_item[o.display_page_two,8] = "Inside Corner 1"
o.display_description_item[o.display_page_two,9] = "Inside Corner 2"
o.display_description_item[o.display_page_two,10] = "Inside Corner 3"
o.display_description_item[o.display_page_two,11] = "Inside Corner 4"
o.display_description_item[o.display_page_two,12] = "Shading Tile 1"
o.display_description_item[o.display_page_two,13] = "Spikes 1"
o.display_description_item[o.display_page_two,14] = "Spikes 2"
o.display_description_item[o.display_page_two,15] = "Spikes 3"
o.display_description_item[o.display_page_two,16] = "Spikes 4"
o.display_description_item[o.display_page_two,17] = "Ladder"
o.display_description_item[o.display_page_two,18] = "Hangbar 1"
o.display_description_item[o.display_page_two,19] = "Hangbar 2"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Small Ramp - 1"
o.display_description_item[o.display_page_three,1] = "Small Ramp - 2"
o.display_description_item[o.display_page_three,2] = "Small Ramp - 3"
o.display_description_item[o.display_page_three,3] = "Small Ramp - 4"
o.display_description_item[o.display_page_three,4] = "Grass Loop Piece 1"
o.display_description_item[o.display_page_three,5] = "Grass Loop Piece 2"
o.display_description_item[o.display_page_three,6] = "Floor Tile"
o.display_description_item[o.display_page_three,7] = "Loop-De-Loop Piece 1"
o.display_description_item[o.display_page_three,8] = "Loop-De-Loop Piece 2"
o.display_description_item[o.display_page_three,9] = "Loop-De-Loop Piece 3"
o.display_description_item[o.display_page_three,10] = "Loop-De-Loop Piece 4"
o.display_description_item[o.display_page_three,11] = "Grass Loop Piece 3"
o.display_description_item[o.display_page_three,12] = "Grass Loop Piece 4"
o.display_description_item[o.display_page_three,13] = "Double-Sided Loop Piece 1"
o.display_description_item[o.display_page_three,14] = "Double-Sided Loop Piece 2"
o.display_description_item[o.display_page_three,15] = "Double-Sided Loop Piece 3"
o.display_description_item[o.display_page_three,16] = "Double-Sided Loop Piece 4"
o.display_description_item[o.display_page_three,17] = "Sloped Long Piece 1"
o.display_description_item[o.display_page_three,18] = "Sloped Long Piece 2"
o.display_description_item[o.display_page_three,19] = "Floor-Over-Floor Platform"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Downward Slope - Shallow 1"
o.display_description_item[o.display_page_four,1] = "Downward Slope - Shallow 2"
o.display_description_item[o.display_page_four,2] = "Downward Slope - Steep 1"
o.display_description_item[o.display_page_four,3] = "Downward Slope - Steep 2"
o.display_description_item[o.display_page_four,4] = "Downward Slope - Shallow 3"
o.display_description_item[o.display_page_four,5] = "Flat Surface 1"
o.display_description_item[o.display_page_four,6] = "Downward Slope - Shallow 4"
o.display_description_item[o.display_page_four,7] = "Floating Platform 1"
o.display_description_item[o.display_page_four,8] = "Floating Platform 2"
o.display_description_item[o.display_page_four,9] = "Floating Platform 3"
o.display_description_item[o.display_page_four,10] = "Floating Platform 4"
o.display_description_item[o.display_page_four,11] = "Floating Platform 5"
o.display_description_item[o.display_page_four,12] = "Platform Reverse Course"
o.display_description_item[o.display_page_four,13] = "Grass Tile"
o.display_description_item[o.display_page_four,14] = "Dirt Tile"
o.display_description_item[o.display_page_four,15] = "Unknown Tile 3"
o.display_description_item[o.display_page_four,16] = "Unknown Tile 4"
o.display_description_item[o.display_page_four,17] = "Unknown Tile 5"
o.display_description_item[o.display_page_four,18] = "Unknown Tile 6"
o.display_description_item[o.display_page_four,19] = "Unknown Tile 7"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Scenery - Bridge 1"
o.display_description_item[o.display_page_five,1] = "Scenery - Column"
o.display_description_item[o.display_page_five,2] = "Scenery - Tree 1"
o.display_description_item[o.display_page_five,3] = "Scenery - Grate"
o.display_description_item[o.display_page_five,4] = "Scenery - Backdrop"
o.display_description_item[o.display_page_five,5] = "Scenery - Platform"
o.display_description_item[o.display_page_five,6] = "Scenery - Fusuma 1"
o.display_description_item[o.display_page_five,7] = "Scenery - Mural"
o.display_description_item[o.display_page_five,8] = "Scenery - Curtains"
o.display_description_item[o.display_page_five,9] = "Scenery - Curtain End Piece"
o.display_description_item[o.display_page_five,10] = "Scenery - Railing 1"
o.display_description_item[o.display_page_five,11] = "Scenery - Support"
o.display_description_item[o.display_page_five,12] = "Scenery - Lantern 1"
o.display_description_item[o.display_page_five,13] = "Scenery - Fusuma 2"
o.display_description_item[o.display_page_five,14] = "Scenery - Tree 2"
o.display_description_item[o.display_page_five,15] = "Scenery - Tree 3"
o.display_description_item[o.display_page_five,16] = "Scenery - Tree 3 - Extra Decorations"
o.display_description_item[o.display_page_five,17] = "Scenery - Tree 4"
o.display_description_item[o.display_page_five,18] = "Scenery - Flag 1"
o.display_description_item[o.display_page_five,19] = "Scenery - Lantern 2"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Shading Tile 16x16"
o.display_description_item[o.display_page_six,1] = "Shading Tile 32x32"
o.display_description_item[o.display_page_six,2] = "Shading Tile 64x64"
o.display_description_item[o.display_page_six,3] = "Shading Tile 96x96"
o.display_description_item[o.display_page_six,4] = "Shading Tile 16x96"
o.display_description_item[o.display_page_six,5] = "Shading Tile 96x16"
o.display_description_item[o.display_page_six,6] = "Shading Tile 128x128"
o.display_description_item[o.display_page_six,7] = "Darkness Tile 128x128"
o.display_description_item[o.display_page_six,8] = "Scenery - Large Table"
o.display_description_item[o.display_page_six,9] = "Scenery - Small Table"
o.display_description_item[o.display_page_six,10] = "Unknown Tile"
o.display_description_item[o.display_page_six,11] = "Unknown Tile"
o.display_description_item[o.display_page_six,12] = "Unknown Tile"
o.display_description_item[o.display_page_six,13] = "Unknown Tile"
o.display_description_item[o.display_page_six,14] = "Unknown Tile"
o.display_description_item[o.display_page_six,15] = "Unknown Tile"
o.display_description_item[o.display_page_six,16] = "Unknown Tile"
o.display_description_item[o.display_page_six,17] = "Unknown Tile"
o.display_description_item[o.display_page_six,18] = "Unknown Tile"
o.display_description_item[o.display_page_six,19] = "Unknown Tile"
