///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Platforms"
o.display_page_description[1] = "Pipework"
o.display_page_description[2] = "Scenery"
o.display_page_description[3] = "Grass/Dirt"
o.display_page_description[4] = "Extras"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Brick Platform - Cracked 1"
o.display_description_item[o.display_page_one,1] = "Brick Platform - Cracked 2"
o.display_description_item[o.display_page_one,2] = "Brick Platform - Cracked 3"
o.display_description_item[o.display_page_one,3] = "Brick Wall - Cracked 1"
o.display_description_item[o.display_page_one,4] = "Brick Wall - Cracked 2"
o.display_description_item[o.display_page_one,5] = "Brick Wall - Cracked 3"
o.display_description_item[o.display_page_one,6] = "Brick Wall 1"
o.display_description_item[o.display_page_one,7] = "Brick Wall 2"
o.display_description_item[o.display_page_one,8] = "Brick Wall 3"
o.display_description_item[o.display_page_one,9] = "Brick Wall 4"
o.display_description_item[o.display_page_one,10] = "Brick Wall 5"
o.display_description_item[o.display_page_one,11] = "Small Brick 1"
o.display_description_item[o.display_page_one,12] = "Small Brick 2"
o.display_description_item[o.display_page_one,13] = "Small Pipe 1"
o.display_description_item[o.display_page_one,14] = "Large Pipe 1"
o.display_description_item[o.display_page_one,15] = "Large Pipe 2"
o.display_description_item[o.display_page_one,16] = "Large Pipe 3"
o.display_description_item[o.display_page_one,17] = "Pipe Connector 1"
o.display_description_item[o.display_page_one,18] = "Pipe Connector 2"
o.display_description_item[o.display_page_one,19] = "Pipe Connector 3"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Sewer Wall 1"
o.display_description_item[o.display_page_two,1] = "Sewer Wall 2"
o.display_description_item[o.display_page_two,2] = "Scenery - Sewer 1"
o.display_description_item[o.display_page_two,3] = "Scenery - Sewer 2"
o.display_description_item[o.display_page_two,4] = "Scenery - Sewer 3"
o.display_description_item[o.display_page_two,5] = "Scenery - Sewer 4"
o.display_description_item[o.display_page_two,6] = "Scenery - Sewer 5"
o.display_description_item[o.display_page_two,7] = "Angled Pipe 1"
o.display_description_item[o.display_page_two,8] = "Angled Pipe 2"
o.display_description_item[o.display_page_two,9] = "Angled Pipe 3"
o.display_description_item[o.display_page_two,10] = "Angled Pipe 4"
o.display_description_item[o.display_page_two,11] = "Construction Support Beam 1"
o.display_description_item[o.display_page_two,12] = "Construction Support Beam 2"
o.display_description_item[o.display_page_two,13] = "Spikes 1"
o.display_description_item[o.display_page_two,14] = "Spikes 2"
o.display_description_item[o.display_page_two,15] = "Spikes 3"
o.display_description_item[o.display_page_two,16] = "Spikes 4"
o.display_description_item[o.display_page_two,17] = "Ladder 1"
o.display_description_item[o.display_page_two,18] = "Ladder 2"
o.display_description_item[o.display_page_two,19] = "Hangbar 1"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Glass Window - Green - Large"
o.display_description_item[o.display_page_three,1] = "Glass Window - Green - Small"
o.display_description_item[o.display_page_three,2] = "Glass Window - Blue - Small"
o.display_description_item[o.display_page_three,3] = "Support Beam 1"
o.display_description_item[o.display_page_three,4] = "Support Beam 2"
o.display_description_item[o.display_page_three,5] = "Support Beam 3"
o.display_description_item[o.display_page_three,6] = "Angled Support Beam - Completed"
o.display_description_item[o.display_page_three,7] = "Angled Support Beam - Bottom"
o.display_description_item[o.display_page_three,8] = "Angled Support Beam - Mid-Section"
o.display_description_item[o.display_page_three,9] = "Angled Support Beam - Top"
o.display_description_item[o.display_page_three,10] = "Angled Support Beam - Bottom"
o.display_description_item[o.display_page_three,11] = "Angled Support Beam - Mid-Section"
o.display_description_item[o.display_page_three,12] = "Angled Support Beam - Top"
o.display_description_item[o.display_page_three,13] = "Corner Piece - 1"
o.display_description_item[o.display_page_three,14] = "Corner Piece - 2"
o.display_description_item[o.display_page_three,15] = "Corner Piece - 3"
o.display_description_item[o.display_page_three,16] = "Corner Piece - 4"
o.display_description_item[o.display_page_three,17] = "Corner Piece - 5"
o.display_description_item[o.display_page_three,18] = "Corner Piece - 6"
o.display_description_item[o.display_page_three,19] = "Corner Piece - Centerpiece"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Grass - Edge Lefy"
o.display_description_item[o.display_page_four,1] = "Grass - Top"
o.display_description_item[o.display_page_four,2] = "Grass - Right Edge"
o.display_description_item[o.display_page_four,3] = "Grassy Slope 1"
o.display_description_item[o.display_page_four,4] = "Grassy Slope 2"
o.display_description_item[o.display_page_four,5] = "Grassy Slope 3"
o.display_description_item[o.display_page_four,6] = "Scenery - Grass"
o.display_description_item[o.display_page_four,7] = "Dirt - Wall Left"
o.display_description_item[o.display_page_four,8] = "Dirt - Small"
o.display_description_item[o.display_page_four,9] = "Dirt - Wall Right"
o.display_description_item[o.display_page_four,10] = "Grass - Flat - Large"
o.display_description_item[o.display_page_four,11] = "Grass - Uneven"
o.display_description_item[o.display_page_four,12] = "Grass - Flat - Small"
o.display_description_item[o.display_page_four,13] = "Grass - Edge - Left"
o.display_description_item[o.display_page_four,14] = "Grass - Bottom"
o.display_description_item[o.display_page_four,15] = "Grass - Edge Right"
o.display_description_item[o.display_page_four,16] = "Dirt Large"
o.display_description_item[o.display_page_four,17] = "Dirt Slope 1"
o.display_description_item[o.display_page_four,18] = "Dirt Slope 2"
o.display_description_item[o.display_page_four,19] = "Dirt Slope 3"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Circle Loop 1"
o.display_description_item[o.display_page_five,1] = "Circle Loop 2"
o.display_description_item[o.display_page_five,2] = "Pipe Loop 1"
o.display_description_item[o.display_page_five,3] = "Pipe Loop 2"
o.display_description_item[o.display_page_five,4] = "Flat Dirt Tile - Extra 1"
o.display_description_item[o.display_page_five,5] = "Flat Dirt Tile - Extra 2"
o.display_description_item[o.display_page_five,6] = "Flat Dirt Tile - Extra 3"
o.display_description_item[o.display_page_five,7] = "Circle Loop 3"
o.display_description_item[o.display_page_five,8] = "Circle Loop 4"
o.display_description_item[o.display_page_five,9] = "Pipe Loop 3"
o.display_description_item[o.display_page_five,10] = "Pipe Loop 4"
o.display_description_item[o.display_page_five,11] = "Flat Dirt Tile - Extra 4"
o.display_description_item[o.display_page_five,12] = "Flat Dirt Tile - Extra 5"
o.display_description_item[o.display_page_five,13] = "Clean Wall 1"
o.display_description_item[o.display_page_five,14] = "Clean Wall 2"
o.display_description_item[o.display_page_five,15] = "Clean Floor 1"
o.display_description_item[o.display_page_five,16] = "Clean Wall 3"
o.display_description_item[o.display_page_five,17] = "Clean Floor 2"
o.display_description_item[o.display_page_five,18] = "Clean Floor 3"
o.display_description_item[o.display_page_five,19] = "Clean Wall 4"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Recycling Dumpster"
o.display_description_item[o.display_page_six,1] = "Ninja Crossing Sign"
o.display_description_item[o.display_page_six,2] = "East Road Street Sign"
o.display_description_item[o.display_page_six,3] = "North Circle Street Sign"
o.display_description_item[o.display_page_six,4] = "South Drive Street Sign"
o.display_description_item[o.display_page_six,5] = "West Lane Street Sign"
o.display_description_item[o.display_page_six,6] = "Blank Street Sign"
o.display_description_item[o.display_page_six,7] = "Arrow Sign"
o.display_description_item[o.display_page_six,8] = "Recycle Bin"
o.display_description_item[o.display_page_six,9] = "Traffic Lights"
o.display_description_item[o.display_page_six,10] = "Lamp Post"
o.display_description_item[o.display_page_six,11] = "Lamp Pole 1"
o.display_description_item[o.display_page_six,12] = "Lamp Pole 2"
o.display_description_item[o.display_page_six,13] = "Lamp Pole 3"
o.display_description_item[o.display_page_six,14] = "Bush"
o.display_description_item[o.display_page_six,15] = "One Of A Kind Eggplant"
o.display_description_item[o.display_page_six,16] = "Clothes Line"
o.display_description_item[o.display_page_six,17] = "Pedestrian Crossing Sign"
o.display_description_item[o.display_page_six,18] = "Pedestrian Signal"
o.display_description_item[o.display_page_six,19] = "Trash Can"

