///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Leitern"
o.display_page_description[1] = "Stacheln"
o.display_page_description[2] = "Glas Set"
o.display_page_description[3] = "Geländer 1"
o.display_page_description[4] = "Geländer 2"
o.display_page_description[5] = "Landschaft"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Leiter 1"
o.display_description_item[o.display_page_one,1] = "Leiter 2"
o.display_description_item[o.display_page_one,2] = "Leiter 3"
o.display_description_item[o.display_page_one,3] = "Leiter 4"
o.display_description_item[o.display_page_one,4] = "Leiter 5"
o.display_description_item[o.display_page_one,5] = "Leiter 6"
o.display_description_item[o.display_page_one,6] = "Hangbar 1"
o.display_description_item[o.display_page_one,7] = "Hangbar 2"
o.display_description_item[o.display_page_one,8] = "Hangbar 3"
o.display_description_item[o.display_page_one,9] = "Hangbar 4"
o.display_description_item[o.display_page_one,10] = "Hangbar 5"
o.display_description_item[o.display_page_one,11] = "Schienen 2"
o.display_description_item[o.display_page_one,12] = "Schienen 3"
o.display_description_item[o.display_page_one,13] = "Schienen 4"
o.display_description_item[o.display_page_one,14] = "Schienen 5"
o.display_description_item[o.display_page_one,15] = "Schienen 6"
o.display_description_item[o.display_page_one,16] = "Schienen 7"
o.display_description_item[o.display_page_one,17] = "Schienen 8"
o.display_description_item[o.display_page_one,18] = "Schienen 9"
o.display_description_item[o.display_page_one,19] = "Schienen 10"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Metallstacheln 1"
o.display_description_item[o.display_page_two,1] = "Metallstacheln 2"
o.display_description_item[o.display_page_two,2] = "Metallstacheln 3"
o.display_description_item[o.display_page_two,3] = "Metallstacheln 4"
o.display_description_item[o.display_page_two,4] = "Holzstacheln 1"
o.display_description_item[o.display_page_two,5] = "Holzstacheln 2"
o.display_description_item[o.display_page_two,6] = "Holzstacheln 3"
o.display_description_item[o.display_page_two,7] = "Holzstacheln 4"
o.display_description_item[o.display_page_two,8] = "Steinstacheln 1"
o.display_description_item[o.display_page_two,9] = "Steinstacheln 2"
o.display_description_item[o.display_page_two,10] = "Steinstacheln 3"
o.display_description_item[o.display_page_two,11] = "Steinstacheln 4"
o.display_description_item[o.display_page_two,12] = "Holzstacheln 1"
o.display_description_item[o.display_page_two,13] = "Holzstacheln 2"
o.display_description_item[o.display_page_two,14] = "Holzstacheln 3"
o.display_description_item[o.display_page_two,15] = "Holzstacheln 4"
o.display_description_item[o.display_page_two,16] = "Gezackte Stacheln 1"
o.display_description_item[o.display_page_two,17] = "Gezackte Stacheln 2"
o.display_description_item[o.display_page_two,18] = "Gezackte Stacheln 3"
o.display_description_item[o.display_page_two,19] = "Gezackte Stacheln 4"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Schwarzes Glas - Groß"
o.display_description_item[o.display_page_three,1] = "Schwarzes Glas - Klein"
o.display_description_item[o.display_page_three,2] = "Schwarzes Glas - Mittel"
o.display_description_item[o.display_page_three,3] = "Schwarzes Glas - Vertikal"
o.display_description_item[o.display_page_three,4] = "Schwarzes Glas - Dünn"
o.display_description_item[o.display_page_three,5] = "Glasschleußenteil 1"
o.display_description_item[o.display_page_three,6] = "Glasschleußenteil 2"
o.display_description_item[o.display_page_three,7] = "Lange Glasrampe 1"
o.display_description_item[o.display_page_three,8] = "Lange Glasrampe 2"
o.display_description_item[o.display_page_three,9] = "Kurze Glasrampe 1"
o.display_description_item[o.display_page_three,10] = "Kurze Glasrampe 2"
o.display_description_item[o.display_page_three,11] = "Glasschleußenteil 3"
o.display_description_item[o.display_page_three,12] = "Glasschleußenteil 4"
o.display_description_item[o.display_page_three,13] = "Lange Glasrampe 3"
o.display_description_item[o.display_page_three,14] = "Lange Glasrampe 4"
o.display_description_item[o.display_page_three,15] = "Kurze Glasrampe 3"
o.display_description_item[o.display_page_three,16] = "Kurze Glasrampe 4"
o.display_description_item[o.display_page_three,17] = "Glasfenster - Grün - Groß"
o.display_description_item[o.display_page_three,18] = "Glasfenster - Grün - Klein"
o.display_description_item[o.display_page_three,19] = "Glasfenster - Blau - Klein"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Schienenschleuße - Oben Links"
o.display_description_item[o.display_page_four,1] = "Schienenschleuße - Oben Rechts"
o.display_description_item[o.display_page_four,2] = "Schienenneigung 1"
o.display_description_item[o.display_page_four,3] = "Schienenneigung 2"
o.display_description_item[o.display_page_four,4] = "Schienenrampe Links"
o.display_description_item[o.display_page_four,5] = "Schiene Flach 1"
o.display_description_item[o.display_page_four,6] = "Schienenrampe Rechts"
o.display_description_item[o.display_page_four,7] = "Schienenschleuße - Unten Links"
o.display_description_item[o.display_page_four,8] = "Schienenschleuße - Unten Rechts"
o.display_description_item[o.display_page_four,9] = "Schienenrampe - Links - Rot"
o.display_description_item[o.display_page_four,10] = "Schienenrampe - Flach - Rot"
o.display_description_item[o.display_page_four,11] = "Schienenrampe - Rechts - Rot"
o.display_description_item[o.display_page_four,12] = "Schiene Flach - Holz"
o.display_description_item[o.display_page_four,13] = "Schienenrampe - Links - Blau"
o.display_description_item[o.display_page_four,14] = "Schienenrampe - Flach - Blau"
o.display_description_item[o.display_page_four,15] = "Schienenrampe - Rechts - Blau"
o.display_description_item[o.display_page_four,16] = "Schienenrampe - Rechts - Gelb"
o.display_description_item[o.display_page_four,17] = "Schienenrampe - Flach - Gelb"
o.display_description_item[o.display_page_four,18] = "Schienenrampe - Links - Gelb"
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Schiene Flach - Rot 1"
o.display_description_item[o.display_page_five,1] = "Schiene Flach - Blau 1"
o.display_description_item[o.display_page_five,2] = "Schiene Flach - Gelb 1"
o.display_description_item[o.display_page_five,3] = "Schiene Flach - Rot 2"
o.display_description_item[o.display_page_five,4] = "Schiene Flach - Blau 2"
o.display_description_item[o.display_page_five,5] = "Schiene Flach - Gelb 2"
o.display_description_item[o.display_page_five,6] = ""
o.display_description_item[o.display_page_five,7] = "Schiene Flach - Rot 3"
o.display_description_item[o.display_page_five,8] = "Schiene Flach - Rot 4"
o.display_description_item[o.display_page_five,9] = "Schiene Flach - Gelb 3"
o.display_description_item[o.display_page_five,10] = "Schiene Flach - Gelb 4"
o.display_description_item[o.display_page_five,11] = "Schiene Flach - Blau 3"
o.display_description_item[o.display_page_five,12] = "Schiene Flach - Blau 4"
o.display_description_item[o.display_page_five,13] = ""
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Landschaft - Kamera Zoom Reset"
o.display_description_item[o.display_page_six,1] = "Landschaft - Kamera Zoom 50 Prozent"
o.display_description_item[o.display_page_six,2] = "Landschaft - Kamera Zoom 25 Prozent"
o.display_description_item[o.display_page_six,3] = "Schienen 11"
o.display_description_item[o.display_page_six,4] = "Schienen 12"
o.display_description_item[o.display_page_six,5] = "West Lane Street Schild"
o.display_description_item[o.display_page_six,6] = "Blank Street Schild"
o.display_description_item[o.display_page_six,7] = "Pfeilschild"
o.display_description_item[o.display_page_six,8] = "Papierkorb"
o.display_description_item[o.display_page_six,9] = "Straßenlampen"
o.display_description_item[o.display_page_six,10] = "Lampenposten"
o.display_description_item[o.display_page_six,11] = "Lampenstange 1"
o.display_description_item[o.display_page_six,12] = "Lampenstange 2"
o.display_description_item[o.display_page_six,13] = "Lampenstange 3"
o.display_description_item[o.display_page_six,14] = "Busch"
o.display_description_item[o.display_page_six,15] = "Spezielle Aubergine" 
o.display_description_item[o.display_page_six,16] = "Wäscheleine"
o.display_description_item[o.display_page_six,17] = "Fußgängerschild"
o.display_description_item[o.display_page_six,18] = "Fußgängerampel"
o.display_description_item[o.display_page_six,19] = "Mülleimer"

