///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Plataformas"
o.display_page_description[1] = "Cenário"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Pedaço de Parede Fina"
o.display_description_item[o.display_page_one,1] = "Carpete Vermelho"
o.display_description_item[o.display_page_one,2] = "Pedaço de ParedeGrossa"
o.display_description_item[o.display_page_one,3] = "Gramado 1"
o.display_description_item[o.display_page_one,4] = "Gramado 2"
o.display_description_item[o.display_page_one,5] = "Gramado 3"
o.display_description_item[o.display_page_one,6] = "Gramado 4"
o.display_description_item[o.display_page_one,7] = "Emergency Ladder"
o.display_description_item[o.display_page_one,8] = "Unknown Tile"
o.display_description_item[o.display_page_one,9] = "Unknown Tile"
o.display_description_item[o.display_page_one,10] = "Unknown Tile"
o.display_description_item[o.display_page_one,11] = "Unknown Tile"
o.display_description_item[o.display_page_one,12] = "Unknown Tile"
o.display_description_item[o.display_page_one,13] = "Unknown Tile"
o.display_description_item[o.display_page_one,14] = "Unknown Tile"
o.display_description_item[o.display_page_one,15] = "Unknown Tile"
o.display_description_item[o.display_page_one,16] = "Unknown Tile"
o.display_description_item[o.display_page_one,17] = "Unknown Tile"
o.display_description_item[o.display_page_one,18] = "Unknown Tile"
o.display_description_item[o.display_page_one,19] = "Unknown Tile"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Estátua do Prefeito Zao"
o.display_description_item[o.display_page_two,1] = "Peça Final do Pilar"
o.display_description_item[o.display_page_two,2] = "Parede Larga"
o.display_description_item[o.display_page_two,3] = "Modelo de Loja"
o.display_description_item[o.display_page_two,4] = "Loja Promocional"
o.display_description_item[o.display_page_two,5] = "Loja de Liquidação"
o.display_description_item[o.display_page_two,6] = "Loja Mundo da Bike"
o.display_description_item[o.display_page_two,7] = "Árvore"
o.display_description_item[o.display_page_two,8] = "Pilar"
o.display_description_item[o.display_page_two,9] = "Recorte de Parede"
o.display_description_item[o.display_page_two,10] = "Painel Decorativo 1"
o.display_description_item[o.display_page_two,11] = "Painel Decorativo 2"
o.display_description_item[o.display_page_two,12] = "Painel Decorativo 3"
o.display_description_item[o.display_page_two,13] = "Placa Mundo da Bike"
o.display_description_item[o.display_page_two,14] = "Placa Promocional"
o.display_description_item[o.display_page_two,15] = "Placa de Liquidação"
o.display_description_item[o.display_page_two,16] = "Unknown Tile"
o.display_description_item[o.display_page_two,17] = "Unknown Tile"
o.display_description_item[o.display_page_two,18] = "Unknown Tile"
o.display_description_item[o.display_page_two,19] = "Unknown Tile"
