obj_game_logic.carol_crouch_leap_timer     = 0   //How long should Carol leap upward?
obj_game_logic.carol_crouch_leap_switch    = 0   //Are we starting the forward leap in the air, or on the ground?
obj_game_logic.carol_special_key_lock      = 0   //Should we detect only one button press, instead of all of them?
obj_game_logic.carol_stamina_count         = 100 //How much stamina do we have before performing the wildclaws attack?
obj_game_logic.carol_stamina_drain         = 100 //How much stamina have we drained during the wildclaws attack?
obj_game_logic.carol_wall_jump_lock_timer  = 0   //How long are we allowed to jump?
obj_game_logic.carol_jump_confirm_key      = 0   //Jump confirm key (Prevents iterative inputs)
obj_game_logic.carol_spring_confirm_key    = 0   //Spring confirm key (Prevents locked inputs)
obj_game_logic.carol_jump_press            = 0   //Have we pressed the jump key once?
obj_game_logic.carol_jump_lock             = 0   //Have we jumped while rolling
obj_game_logic.carol_jump_timer            = 0   //How long are we allowed to jump?
obj_game_logic.carol_attack_frame          = 0   //Animation frames for the attack sprites
obj_game_logic.carol_attack_frame_repeat   = 0   //Animation loop point for the attack sprites
obj_game_logic.carol_action_distance       = 0   //Animation offsets for the attack sprites
obj_game_logic.carol_wildclaws_stage       = 0   //Which stage of the wildclaws attack are we performing?
obj_game_logic.carol_roll_lock             = 0   //Should we prevent rolling during the golden claws attack?
obj_game_logic.carol_roll_timer            = 0   //How long should we roll?
obj_game_logic.carol_hang_bar_jump         = 0   //How many frames should we wait to enable forward leaping?
obj_game_logic.carol_attack_lock           = 0   //Disable golden claw attacks after unrolling
obj_game_logic.carol_wall_jump_sound       = 0   //Play the wall jump sound only once
obj_game_logic.carol_tail_sprite           = 0   //Current sprite of the tail's sprite
obj_game_logic.carol_tail_sprite_frame     = 0   //Current frame of the tail's sprite
obj_game_logic.carol_tail_x                = 0   //X position of the tail's sprite
obj_game_logic.carol_tail_y                = 0   //Y position of the tail's sprite
obj_game_logic.carol_tail_x_anchor         = 0   //X position of the tail's sprite
obj_game_logic.carol_tail_y_anchor         = 0   //Y position of the tail's sprite
obj_game_logic.carol_tail_animation_end    = 0   //Animation length of the tail's sprite
obj_game_logic.carol_tail_offset_x         = -4  //What X position should the tail be, relative to the player's feet?
obj_game_logic.carol_tail_offset_y         = 18  //What Y position should the tail be, relative to the player's feet?
obj_game_logic.carol_tail_dir              = 0   //Which direction should the tail be facing?
obj_game_logic.carol_animation_speed_mod   = 0   //Modify animation speed based on horizontal speed
obj_game_logic.carol_switch_button         = 0   //Carol's Switch Button Press
obj_game_logic.skidding_override           = 0   //Allow Carol to use existing skidding particle system;
                                                 //no copypasta allowed
obj_game_logic.carol_speed_up              = 0
obj_game_logic.bike_confirm                = 0   //Override switch for Carol's bike or non-bike animations
obj_game_logic.bike_x                      = -64 //X position of the bike's tile
obj_game_logic.bike_y                      = -64 //Y position of the bike's tile
obj_game_logic.bike_dir                    = 0   //Horizontal scaling of the bike's tile
obj_game_logic.bike_angle                  = 0   //Angle of the bike's tile
obj_game_logic.bike_init_timer             = 0   //Timer for looping the init animation
obj_game_logic.bike_gravity_speed          = 0   //Speed of the bike while driving up walls
obj_game_logic.bike_jump_speed             = 0   //Speed of the bike while jumping off the walls
obj_game_logic.bike_jump_trigger           = 0   //Trigger for the bike while jumping off the walls
obj_game_logic.bike_jump_roll              = 0   //Trigger for the bike's double jump attack
obj_game_logic.bike_jump_roll_speed        = 0   //Speed for the bike's double jump attack
obj_game_logic.bike_boost_trigger          = 0   //Trigger for the bike while boosting
obj_game_logic.bike_mount_trigger          = 0   //Trigger for landing on the bike
obj_game_logic.bike_landing_sound          = 0   //Trigger for the bike's landing sound
obj_game_logic.bike_double_jump_lock       = 0   //Trigger for the bike's double jump
obj_game_logic.bike_double_jump_trigger    = 0   //Trigger for the bike's double jump after picking up a gas can
obj_game_logic.bike_attack_sprite_frame    = 0   //Animation frames for the bike's double jump attack sprites
obj_game_logic.bike_particles_rotate_x     = 0   //X position for bike particles' spawn point
obj_game_logic.bike_particles_rotate_y     = 0   //Y position for bike particles' spawn point
obj_game_logic.bike_fling_speed            = 0   //Fling speed for launching from a wall
obj_game_logic.bike_gears                  = 0   //Bike's Gear Shifts
obj_game_logic.fof_disable                 = 0   //Disable FOF collisions
obj_game_logic.sit = 0
obj_game_logic.sit_timer = 0
obj_game_logic.push_timer = 0
obj_game_logic.boot_swipe_jump = 4

//Pitch of the bike's moving sound
obj_game_logic.bike_pitch                  = carol_bike_moving
