///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Areia"
o.display_page_description[1] = "Plataformas"
o.display_page_description[2] = "Rampas"
o.display_page_description[3] = "Exterior"
o.display_page_description[4] = "Decoração 1"
o.display_page_description[5] = "Decoração 2"
o.display_page_description[6] = "Extra 1"
o.display_page_description[7] = "Pier 1"
o.display_page_description[8] = "Pier 2"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Areia - Borda da Superfície Esquerdo"
o.display_description_item[o.display_page_one,1] = "Areia - Camada da Superfície "
o.display_description_item[o.display_page_one,2] = "Areia - Borda da Superfície Direito"
o.display_description_item[o.display_page_one,3] = "Areia - Borda da Superfície Inferior Esquerdo"
o.display_description_item[o.display_page_one,4] = "Areia - Camada da Superfície Invertida"
o.display_description_item[o.display_page_one,5] = "Areia - Borda da Superfície Inferior Direito"
o.display_description_item[o.display_page_one,6] = "Areia - Parede Esquerda"
o.display_description_item[o.display_page_one,7] = "Areia - Parede Direita"
o.display_description_item[o.display_page_one,8] = "Areia - Declive 1"
o.display_description_item[o.display_page_one,9] = "Areia - Declive 2"
o.display_description_item[o.display_page_one,10] = "Areia - Declive 3"
o.display_description_item[o.display_page_one,11] = "Areia - Declive 4"
o.display_description_item[o.display_page_one,12] = "Camada de Arenito"
o.display_description_item[o.display_page_one,13] = "Plataforma de Pedra - Borda Esquerda"
o.display_description_item[o.display_page_one,14] = "Plataforma de Pedra - Superfície"
o.display_description_item[o.display_page_one,15] = "Plataforma de Pedra - Borda Direita"
o.display_description_item[o.display_page_one,16] = "Superfície de Mármore - Largo"
o.display_description_item[o.display_page_one,17] = "Superfície de Mármore - Estreito"
o.display_description_item[o.display_page_one,18] = "Parede de Mármore - Esquerda"
o.display_description_item[o.display_page_one,19] = "Parede de Mármore - Direita"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Grade de Madeira - 1"
o.display_description_item[o.display_page_two,1] = "Grade de Madeira - 2"
o.display_description_item[o.display_page_two,2] = "Grade de Madeira - 3"
o.display_description_item[o.display_page_two,3] = "Grade de Madeira - 4"
o.display_description_item[o.display_page_two,4] = "Viga de Apoio Antiga de Cobre 1"
o.display_description_item[o.display_page_two,5] = "Viga de Apoio Antiga de Cobre 2"
o.display_description_item[o.display_page_two,6] = "Grade de Madeira - Raso 1"
o.display_description_item[o.display_page_two,7] = "Morro de Areia - Raso Esquerdo"
o.display_description_item[o.display_page_two,8] = "Viga de Suporte de Madeira 1"
o.display_description_item[o.display_page_two,9] = "Viga de Suporte de Madeira 2"
o.display_description_item[o.display_page_two,10] = "Viga de Apoio Antiga de Cobre 3"
o.display_description_item[o.display_page_two,11] = "Viga de Apoio Antiga de Cobre 4"
o.display_description_item[o.display_page_two,12] = "Grade de Madeira - Raso 2"
o.display_description_item[o.display_page_two,13] = "Morro de Areia - Raso Esquerdo"
o.display_description_item[o.display_page_two,14] = "Espinhos 1"
o.display_description_item[o.display_page_two,15] = "Espinhos 2"
o.display_description_item[o.display_page_two,16] = "Espinhos 3"
o.display_description_item[o.display_page_two,17] = "Espinhos 4"
o.display_description_item[o.display_page_two,18] = "Escada"
o.display_description_item[o.display_page_two,19] = "Barra Suspensa"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Pedra Quarter Pipe 1"
o.display_description_item[o.display_page_three,1] = "Pedra Quarter Pipe 2"
o.display_description_item[o.display_page_three,2] = "Pedra Quarter Pipe 3"
o.display_description_item[o.display_page_three,3] = "Pedra Quarter Pipe 4"
o.display_description_item[o.display_page_three,4] = "Morro de Areia Esquerda"
o.display_description_item[o.display_page_three,5] = "Morro de Areia Direita"
o.display_description_item[o.display_page_three,6] = "Caixa de Madeira"
o.display_description_item[o.display_page_three,7] = "Peça Loop-De-Loop 1"
o.display_description_item[o.display_page_three,8] = "Peça Loop-De-Loop 2"
o.display_description_item[o.display_page_three,9] = "Peça Loop-De-Loop 3"
o.display_description_item[o.display_page_three,10] = "Peça Loop-De-Loop 4"
o.display_description_item[o.display_page_three,11] = "Plataforma Flutuante - 1"
o.display_description_item[o.display_page_three,12] = "Plataforma Flutuante - 2"
o.display_description_item[o.display_page_three,13] = "Loop de Madeira 1"
o.display_description_item[o.display_page_three,14] = "Loop de Madeira 2"
o.display_description_item[o.display_page_three,15] = "Loop de Madeira 3"
o.display_description_item[o.display_page_three,16] = "Loop de Madeira 4"
o.display_description_item[o.display_page_three,17] = "Plataforma Flutuante 3"
o.display_description_item[o.display_page_three,18] = "Plataforma Flutuante 4"
o.display_description_item[o.display_page_three,19] = "Plataforma Chão-Sobre-Chão"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Viga de Madeira - Esquerda"
o.display_description_item[o.display_page_four,1] = "Viga de Madeira - Longo"
o.display_description_item[o.display_page_four,2] = "Viga de Madeira - Direita"
o.display_description_item[o.display_page_four,3] = "Viga de Madeira - Pequeno"
o.display_description_item[o.display_page_four,4] = "Grade de Madeira"
o.display_description_item[o.display_page_four,5] = "Suporte de Madeira - Esquerda"
o.display_description_item[o.display_page_four,6] = "Suporte de Madeira - Direita"
o.display_description_item[o.display_page_four,7] = "Suporte de Madeira - Viga"
o.display_description_item[o.display_page_four,8] = "Suporte de Madeira - Peça Inferior"
o.display_description_item[o.display_page_four,9] = "Suporte de Madeira - Peça Superior"
o.display_description_item[o.display_page_four,10] = "Chuveiro Externo"
o.display_description_item[o.display_page_four,11] = "Torneira Externa"
o.display_description_item[o.display_page_four,12] = "Poste de Luz"
o.display_description_item[o.display_page_four,13] = "Banheiro Portátil - Masculino"
o.display_description_item[o.display_page_four,14] = "Banheiro Portátil - Feminino"
o.display_description_item[o.display_page_four,15] = "Janela Estreita"
o.display_description_item[o.display_page_four,16] = "Guarda-Sol Grande"
o.display_description_item[o.display_page_four,17] = "Guarda-Sol Pequeno"
o.display_description_item[o.display_page_four,18] = "Castelo de Areia - Pequeno"
o.display_description_item[o.display_page_four,19] = "Castelo de Areia - Grande"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Palmeira - Tronco"
o.display_description_item[o.display_page_five,1] = "Palmeira - Folha Cima-Esquerda"
o.display_description_item[o.display_page_five,2] = "Palmeira - Folha Esquerda"
o.display_description_item[o.display_page_five,3] = "Palmeira - Baixo-Esquerda"
o.display_description_item[o.display_page_five,4] = "Palmeira - Folha Cima-Direita"
o.display_description_item[o.display_page_five,5] = "Palmeira - Folha Direita"
o.display_description_item[o.display_page_five,6] = "Palmeira - Folha Baixo-Direita"
o.display_description_item[o.display_page_five,7] = "Concha de Caracol - Grande"
o.display_description_item[o.display_page_five,8] = "Concha Marinha"
o.display_description_item[o.display_page_five,9] = "Concha de Caracol - Pequeno"
o.display_description_item[o.display_page_five,10] = "Ninho de Passáro"
o.display_description_item[o.display_page_five,11] = "Coco"
o.display_description_item[o.display_page_five,12] = "Conjunto de Bananas"
o.display_description_item[o.display_page_five,13] = "Placa de Aviso: BuoyBuoys"
o.display_description_item[o.display_page_five,14] = "Placa de Aviso: Correntes Fortes"
o.display_description_item[o.display_page_five,15] = "Placa de Aviso: Pedras Escorregadias"
o.display_description_item[o.display_page_five,16] = "Placa de Aviso: Queda Súbita"
o.display_description_item[o.display_page_five,17] = "Placa de Aviso: Ninho de Tartaruga Marinha"
o.display_description_item[o.display_page_five,18] = "Placa de Aviso: Não Alimente as Gaivotas"
o.display_description_item[o.display_page_five,19] = "Placa de Aviso: Não há Salva-Vidas em Serviço"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Pedra Pequena"
o.display_description_item[o.display_page_six,1] = "Pedra Gigante - 1"
o.display_description_item[o.display_page_six,2] = "Pedra Gigante - 2"
o.display_description_item[o.display_page_six,3] = "Pedra Gigante - 3"
o.display_description_item[o.display_page_six,4] = "Pedra Gigante - 4"
o.display_description_item[o.display_page_six,5] = "Grama Selvagem"
o.display_description_item[o.display_page_six,6] = "Pilha de Areia"
o.display_description_item[o.display_page_six,7] = "Fruteira"
o.display_description_item[o.display_page_six,8] = "Banca do Protetor Solar"
o.display_description_item[o.display_page_six,9] = "Estande da Loja de Presentes"
o.display_description_item[o.display_page_six,10] = "Banca do Café"
o.display_description_item[o.display_page_six,11] = "Sorveteria"
o.display_description_item[o.display_page_six,12] = "Carrinho do Cachorro-Quente"
o.display_description_item[o.display_page_six,13] = "Unknown Tile"
o.display_description_item[o.display_page_six,14] = "Unknown Tile"
o.display_description_item[o.display_page_six,15] = "Unknown Tile"
o.display_description_item[o.display_page_six,16] = "Unknown Tile"
o.display_description_item[o.display_page_six,17] = "Unknown Tile"
o.display_description_item[o.display_page_six,18] = "Unknown Tile"
o.display_description_item[o.display_page_six,19] = "Unknown Tile"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Pedra de Arenito"
o.display_description_item[o.display_page_seven,1] = "Areia Plana - Pequeno - 1"
o.display_description_item[o.display_page_seven,2] = "Areia Plana - Pequeno - 2"
o.display_description_item[o.display_page_seven,3] = "Areia Plana - Pequeno - 3"
o.display_description_item[o.display_page_seven,4] = "Areia Plana - Pequeno - 4"
o.display_description_item[o.display_page_seven,5] = "Pedaço de canto de Areia - 1"
o.display_description_item[o.display_page_seven,6] = "Pedaço de canto de Areia - 2"
o.display_description_item[o.display_page_seven,7] = "Pedaço de canto de Areia- 3"
o.display_description_item[o.display_page_seven,8] = "Pedaço de canto de Areia - 4"
o.display_description_item[o.display_page_seven,9] = "Arenito - Pequeno"
o.display_description_item[o.display_page_seven,10] = "Trilha de Madeira - Vertical - Grande"
o.display_description_item[o.display_page_seven,11] = "Trilha de Madeira - Vertical - Pequeno"
o.display_description_item[o.display_page_seven,12] = "Pedaço de Areia Vaizo"
o.display_description_item[o.display_page_seven,13] = "Viga de Suporte de Madeira - Pequeno"
o.display_description_item[o.display_page_seven,14] = "Viga de Suporte de Madeira - Grande"
o.display_description_item[o.display_page_seven,15] = "Construction Beam  Viga de Construção - Oxidado"
o.display_description_item[o.display_page_seven,16] = "Flor da Corriola"
o.display_description_item[o.display_page_seven,17] = "Camélia Japônica Vermelha"
o.display_description_item[o.display_page_seven,18] = "Unknown Tile"
o.display_description_item[o.display_page_seven,19] = "Unknown Tile"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Madeira do Píer Envelhecido 1"
o.display_description_item[o.display_page_eight,1] = "Madeira do Píer Envelhecido 2"
o.display_description_item[o.display_page_eight,2] = "Madeira do Píer Envelhecido 3"
o.display_description_item[o.display_page_eight,3] = "Madeira do Píer Envelhecido 4"
o.display_description_item[o.display_page_eight,4] = "Madeira do Píer Envelhecido 5"
o.display_description_item[o.display_page_eight,5] = "Madeira do Píer Envelhecido 6"
o.display_description_item[o.display_page_eight,6] = "Placa Proibido Pescar"
o.display_description_item[o.display_page_eight,7] = "Viga de Suporte de Madeira 1"
o.display_description_item[o.display_page_eight,8] = "Viga de Suporte de Madeira 2"
o.display_description_item[o.display_page_eight,9] = "Viga de Suporte de Madeira 3"
o.display_description_item[o.display_page_eight,10] = "Viga de Suporte de Madeira 4"
o.display_description_item[o.display_page_eight,11] = "Viga de Suporte de Madeira 5"
o.display_description_item[o.display_page_eight,12] = "Trilhas do Píer"
o.display_description_item[o.display_page_eight,13] = "Loop de Madeira 1"
o.display_description_item[o.display_page_eight,14] = "Loop de Madeira 2"
o.display_description_item[o.display_page_eight,15] = "Loop de Madeira 3"
o.display_description_item[o.display_page_eight,16] = "Loop de Madeira 4"
o.display_description_item[o.display_page_eight,17] = "Rampa de Madeira 1"
o.display_description_item[o.display_page_eight,18] = "Rampa de Madeira 2"
o.display_description_item[o.display_page_eight,19] = "Posto de Salva-Vidas"

//Tile Descriptions (Page 9)
o.display_description_item[o.display_page_nine,0] = "Madeira do Píer 1"
o.display_description_item[o.display_page_nine,1] = "Madeira do Píer 2"
o.display_description_item[o.display_page_nine,2] = "Madeira do Píer 3"
o.display_description_item[o.display_page_nine,3] = "Madeira do Píer 4"
o.display_description_item[o.display_page_nine,4] = "Madeira do Píer 5"
o.display_description_item[o.display_page_nine,5] = "Small Sand Slope 1"
o.display_description_item[o.display_page_nine,6] = "Small Sand Slope 2"
o.display_description_item[o.display_page_nine,7] = "Wooden Loop 5"
o.display_description_item[o.display_page_nine,8] = "Wooden Loop 6"
o.display_description_item[o.display_page_nine,9] = "Construction Beam Small 1"
o.display_description_item[o.display_page_nine,10] = "Construction Beam Small 2"
o.display_description_item[o.display_page_nine,11] = "Construction Beam Small 3"
o.display_description_item[o.display_page_nine,12] = "Construction Beam Small 4"
o.display_description_item[o.display_page_nine,13] = "Wooden Loop 7"
o.display_description_item[o.display_page_nine,14] = "Wooden Loop 8"
o.display_description_item[o.display_page_nine,15] = "Unknown Tile"
o.display_description_item[o.display_page_nine,16] = "Unknown Tile"
o.display_description_item[o.display_page_nine,17] = "Unknown Tile"
o.display_description_item[o.display_page_nine,18] = "Unknown Tile"
o.display_description_item[o.display_page_nine,19] = "Unknown Tile"

