//Create shorthand alias for the Level Editor Object
o = obj_level_editor;

//Sentinel check on layer value for current tile; at the end of the mouse click, check to see if the tile should belong
//to a certain layer, or shouldn't be placed on a specific layer
if o.user_cursor_display_mode = 0
    {
        //If we do have a tile on a layer it shouldn't be, change the currently selected layer for the user's safety
        switch(o.user_tile_selected)
            {
                //Shang Mu Temple Tile Set
                //Flats
                case mu_flat_0: {scr_set_layer_flats(); break;}
                case mu_flat_1: {scr_set_layer_flats(); break;}
                case mu_flat_2: {scr_set_layer_flats(); break;}
                case mu_flat_3: {scr_set_layer_flats(); break;}
                case mu_flat_4: {scr_set_layer_flats(); break;}
                case mu_flat_5: {scr_set_layer_flats(); break;}
                case mu_flat_6: {scr_set_layer_flats(); break;}
                case mu_flat_7: {scr_set_layer_flats(); break;}
                case mu_flat_8: {scr_set_layer_flats(); break;}
                case mu_flat_9: {scr_set_layer_flats(); break;}
                case mu_flat_10: {scr_set_layer_flats(); break;}
                case mu_flat_11: {scr_set_layer_flats(); break;}
                case mu_flat_12: {scr_set_layer_flats(); break;}
                case mu_flat_13: {scr_set_layer_flats(); break;}
                case mu_flat_14: {scr_set_layer_flats(); break;}
                case mu_flat_15: {scr_set_layer_flats(); break;}
                case mu_flat_16: {scr_set_layer_flats(); break;}
                case mu_flat_17: {scr_set_layer_flats(); break;}
                case mu_flat_18: {scr_set_layer_flats(); break;}
                case mu_flat_19: {scr_set_layer_flats(); break;}
                case mu_flat_20: {scr_set_layer_flats(); break;}
                case mu_flat_21: {scr_set_layer_flats(); break;}
                case mu_flat_22: {scr_set_layer_flats(); break;}
                case mu_flat_23: {scr_set_layer_flats(); break;}
                case mu_flat_24: {scr_set_layer_flats(); break;}
                case mu_flat_25: {scr_set_layer_flats(); break;}
                case mu_flat_26: {scr_set_layer_flats(); break;}
                case mu_flat_27: {scr_set_layer_flats(); break;}
                case mu_flat_28: {scr_set_layer_flats(); break;}
                case mu_flat_29: {scr_set_layer_flats(); break;}
                case mu_flat_30: {scr_set_layer_flats(); break;}
                case mu_flat_31: {scr_set_layer_flats(); break;}
                case mu_flat_32: {scr_set_layer_flats(); break;}
                case mu_flat_33: {scr_set_layer_flats(); break;}
                case mu_flat_34: {scr_set_layer_flats(); break;}
                case mu_flat_35: {scr_set_layer_flats(); break;}
                case mu_flat_36: {scr_set_layer_flats(); break;}
                case mu_flat_37: {scr_set_layer_flats(); break;}
                case mu_flat_38: {scr_set_layer_flats(); break;}
                case mu_flat_39: {scr_set_layer_flats(); break;}
                case mu_flat_40: {scr_set_layer_flats(); break;}
                case mu_flat_41: {scr_set_layer_flats(); break;}
                case mu_flat_42: {scr_set_layer_flats(); break;}
                case mu_flat_43: {scr_set_layer_flats(); break;}
                case ma_flat_0:  {scr_set_layer_flats(); break;}
                case ma_flat_1:  {scr_set_layer_flats(); break;}
                case ma_flat_2:  {scr_set_layer_flats(); break;}
                case ma_flat_3:  {scr_set_layer_flats(); break;}
                case ma_flat_7:  {scr_set_layer_flats(); break;}
                case ma_flat_8:  {scr_set_layer_flats(); break;}
                case ma_flat_9:  {scr_set_layer_flats(); break;}
                //Ramps
                case mu_ramp_0: {scr_set_layer_slopes(); break;}
                case mu_ramp_1: {scr_set_layer_slopes(); break;}
                case mu_ramp_2: {scr_set_layer_slopes(); break;}
                case mu_ramp_3: {scr_set_layer_slopes(); break;}
                case mu_ramp_4: {scr_set_layer_slopes(); break;}
                case mu_ramp_5: {scr_set_layer_slopes(); break;}
                case mu_ramp_6: {scr_set_layer_slopes(); break;}
                case mu_ramp_7: {scr_set_layer_slopes(); break;}
                case mu_ramp_8: {scr_set_layer_slopes(); break;}
                case mu_ramp_9: {scr_set_layer_slopes(); break;}
                case mu_ramp_10: {scr_set_layer_slopes(); break;}
                case mu_ramp_11: {scr_set_layer_slopes(); break;}
                case mu_ramp_12: {scr_set_layer_slopes(); break;}
                case mu_ramp_13: {scr_set_layer_slopes(); break;}
                case mu_ramp_14: {scr_set_layer_slopes(); break;}
                case mu_ramp_15: {scr_set_layer_slopes(); break;}
                case mu_ramp_16: {scr_set_layer_slopes(); break;}
                case mu_ramp_17: {scr_set_layer_slopes(); break;}
                case mu_ramp_18: {scr_set_layer_slopes(); break;}
                case mu_ramp_19: {scr_set_layer_slopes(); break;}
                case mu_ramp_20: {scr_set_layer_slopes(); break;}
                case mu_ramp_21: {scr_set_layer_slopes(); break;}
                case mu_ramp_22: {scr_set_layer_slopes(); break;}
                case mu_ramp_23: {scr_set_layer_slopes(); break;}
                case mu_ramp_24: {scr_set_layer_slopes(); break;}
                case mu_ramp_25: {scr_set_layer_slopes(); break;}
                //Slopes
                case mu_slope_0: {scr_set_layer_slopes(); break;}
                case mu_slope_1: {scr_set_layer_slopes(); break;}
                case mu_slope_2: {scr_set_layer_slopes(); break;}
                case mu_slope_3: {scr_set_layer_slopes(); break;}
                case mu_slope_4: {scr_set_layer_slopes(); break;}
                case mu_slope_5: {scr_set_layer_slopes(); break;}
                case mu_slope_6: {scr_set_layer_slopes(); break;}
                case mu_slope_7: {scr_set_layer_slopes(); break;}
                case mu_slope_8: {scr_set_layer_slopes(); break;}
                case mu_slope_9: {scr_set_layer_slopes(); break;}
                case mu_slope_10: {scr_set_layer_slopes(); break;}
                case mu_slope_11: {scr_set_layer_slopes(); break;}
                case mu_slope_12: {scr_set_layer_slopes(); break;}
                case mu_slope_13: {scr_set_layer_slopes(); break;}
                case mu_slope_14: {scr_set_layer_slopes(); break;}
                case mu_slope_15: {scr_set_layer_slopes(); break;}
                case mu_slope_16: {scr_set_layer_slopes(); break;}
                case mu_slope_17: {scr_set_layer_slopes(); break;}
                case mu_slope_18: {scr_set_layer_slopes(); break;}
                case mu_slope_19: {scr_set_layer_slopes(); break;}
                case mu_slope_20: {scr_set_layer_slopes(); break;}
                case mu_slope_21: {scr_set_layer_slopes(); break;}
                case mu_slope_22: {scr_set_layer_slopes(); break;}
                case mu_slope_23: {scr_set_layer_slopes(); break;}
                case mu_slope_24: {scr_set_layer_slopes(); break;}
                case mu_slope_25: {scr_set_layer_slopes(); break;}
                case mu_slope_26: {scr_set_layer_slopes(); break;}
                case mu_slope_27: {scr_set_layer_slopes(); break;}
                //Slope Masks
                case tile_ramp_entry: {scr_set_layer_slopes(); break;}
                case mu_slope_ceiling_16: {scr_set_layer_slopes(); break;}
                case mu_slope_ceiling_64: {scr_set_layer_slopes(); break;}
                //FOFs
                case mu_fof_0:  {scr_set_layer_slopes(); break;}
                case mu_fof_10: {scr_set_layer_slopes(); break;}
                case mu_fof_2:  {scr_set_layer_slopes(); break;}
                case mu_fof_11: {scr_set_layer_slopes(); break;}
                case mu_fof_12: {scr_set_layer_slopes(); break;}
                case mu_fof_13: {scr_set_layer_slopes(); break;}
                //Flags
                case tile_layer_changer: {scr_set_layer_flags(); break;}
                case tile_layer_changer_left: {scr_set_layer_flags(); break;}
                case tile_reverse_course_32: {scr_set_layer_flags(); break;}
                //Scene Tiles
                case mu_scene_0: {scr_set_layer_scene(); break;}
                case mu_scene_1: {scr_set_layer_scene(); break;}
                case mu_scene_2: {scr_set_layer_scene(); break;}
                case mu_scene_3: {scr_set_layer_scene(); break;}
                case mu_scene_4: {scr_set_layer_scene(); break;}
                case mu_scene_5: {scr_set_layer_scene(); break;}
                case mu_scene_6: {scr_set_layer_scene(); break;}
                case mu_scene_8: {scr_set_layer_scene(); break;}
                case mu_scene_9: {scr_set_layer_scene(); break;}
                case mu_scene_10: {scr_set_layer_scene(); break;}
                case mu_scene_11: {scr_set_layer_scene(); break;}
                case mu_scene_12: {scr_set_layer_scene(); break;}
                case mu_scene_13: {scr_set_layer_scene(); break;}
                case mu_scene_14: {scr_set_layer_scene(); break;}
                case mu_scene_15: {scr_set_layer_scene(); break;}
                case mu_scene_16: {scr_set_layer_scene(); break;}
                case mu_scene_17: {scr_set_layer_scene(); break;}
                case mu_scene_18: {scr_set_layer_scene(); break;}
                case mu_scene_19: {scr_set_layer_scene(); break;}
                case mu_scene_20: {scr_set_layer_scene(); break;}
                case mu_scene_21: {scr_set_layer_scene(); break;}
                case mu_scene_22: {scr_set_layer_scene(); break;}
                case mu_scene_23: {scr_set_layer_scene(); break;}
                case mu_scene24:  {scr_set_layer_scene(); break;}
                case mu_scene_25: {scr_set_layer_scene(); break;}
                case mu_scene_27: {scr_set_layer_scene(); break;}
                case mu_scene_28: {scr_set_layer_scene(); break;}
                case mu_scene_29: {scr_set_layer_scene(); break;}
                case mu_scene_30: {scr_set_layer_scene(); break;}
                case mu_scene_31: {scr_set_layer_scene(); break;}
                case mu_scene_32: {scr_set_layer_scene(); break;}
                case mu_scene_33: {scr_set_layer_scene(); break;}
                case mu_scene_34: {scr_set_layer_scene(); break;}
                case mu_paint_black: {scr_set_layer_scene(); break;}
                case mu_paint_white: {scr_set_layer_scene(); break;}
                case mu_paint_red: {scr_set_layer_scene(); break;}
                case mu_paint_burgundy: {scr_set_layer_scene(); break;}
                case mu_paint_yellow: {scr_set_layer_scene(); break;}
                case mu_paint_dark_yellow: {scr_set_layer_scene(); break;}
                case mu_paint_green: {scr_set_layer_scene(); break;}
                case mu_paint_dark_green: {scr_set_layer_scene(); break;}
                case mu_paint_cyan: {scr_set_layer_scene(); break;}
                case mu_paint_dark_cyan: {scr_set_layer_scene(); break;}
                case mu_paint_blue: {scr_set_layer_scene(); break;}
                case mu_paint_pink: {scr_set_layer_scene(); break;}
                case mu_paint_purple: {scr_set_layer_scene(); break;}
                //Spikes
                case spr_spikes_10: {scr_set_layer_flats(); break;}
                case spr_spikes_18: {scr_set_layer_flats(); break;}
                case spr_spikes_19: {scr_set_layer_flats(); break;}
                case spr_spikes_20: {scr_set_layer_flats(); break;}
                //Ladders
                case spr_ladder_0: {scr_set_layer_slopes(); break;}
                case spr_ladder_1: {scr_set_layer_slopes(); break;}
                case spr_ladder_2: {scr_set_layer_slopes(); break;}
                case spr_ladder_3: {scr_set_layer_slopes(); break;}
                case spr_ladder_4: {scr_set_layer_slopes(); break;}
                case spr_ladder_5: {scr_set_layer_slopes(); break;}
                case spr_ladder_6: {scr_set_layer_slopes(); break;}
                //Hangbars
                case spr_hangbar_0: {scr_set_layer_slopes(); break;}
                case spr_hangbar_1: {scr_set_layer_slopes(); break;}
                case spr_hangbar_2: {scr_set_layer_slopes(); break;}
                case spr_hangbar_3: {scr_set_layer_slopes(); break;}
                case spr_hangbar_4: {scr_set_layer_slopes(); break;}
                //Dirt
                case spr_dirt_0: {scr_set_layer_slopes(); break;}
                case spr_dirt_1: {scr_set_layer_flats(); break;}
                //Items
                case spr_flower_0: {scr_set_layer_items(); break;}
                case spr_flower_1: {scr_set_layer_items(); break;}
                case spr_flower_2: {scr_set_layer_items(); break;}
                case spr_flower_3: {scr_set_layer_items(); break;}
                case spr_flower_4: {scr_set_layer_items(); break;}
                case spr_flower_5: {scr_set_layer_items(); break;}
                case spr_flower_6: {scr_set_layer_items(); break;}
                case spr_flower_7: {scr_set_layer_items(); break;}
                case spr_flower_8: {scr_set_layer_items(); break;}
                case spr_crate_0:  {scr_set_layer_items(); break;}
                case spr_gascan_0: {scr_set_layer_items(); break;}
                case spr_switch_0: {scr_set_layer_items(); break;}
                case spr_switch_2: {scr_set_layer_items(); break;}
                case spr_switch_4: {scr_set_layer_items(); break;}
                //Springs
                case spr_spring_0_0: {scr_set_layer_items(); break;}
                case spr_spring_1_0: {scr_set_layer_items(); break;}
                case spr_spring_2_0: {scr_set_layer_items(); break;}
                case spr_spring_3_0: {scr_set_layer_items(); break;}
                case spr_spring_4_0: {scr_set_layer_items(); break;}
                case spr_spring_5_0: {scr_set_layer_items(); break;}
                case spr_spring_6_0: {scr_set_layer_items(); break;}
                case spr_spring_7_0: {scr_set_layer_items(); break;}
                case spr_spring_8_0: {scr_set_layer_items(); break;}
                case spr_spring_9_0: {scr_set_layer_items(); break;}
                case spr_spring_10_0: {scr_set_layer_items(); break;}
                case spr_spring_11_0: {scr_set_layer_items(); break;}
                case spr_spring_12_0: {scr_set_layer_items(); break;}
                case spr_spring_13_0: {scr_set_layer_items(); break;}
                case spr_spring_14_0: {scr_set_layer_items(); break;}
                case spr_spring_15_0: {scr_set_layer_items(); break;}
                //City Tile Set
                //Flats
                case wd_flat_0: {scr_set_layer_flats(); break;}
                case wd_flat_1: {scr_set_layer_flats(); break;}
                case wd_flat_2: {scr_set_layer_flats(); break;}
                case wd_flat_3: {scr_set_layer_flats(); break;}
                case wd_flat_4: {scr_set_layer_flats(); break;}
                case wd_flat_5: {scr_set_layer_flats(); break;}
                case wd_flat_6: {scr_set_layer_flats(); break;}
                case wd_flat_7: {scr_set_layer_flats(); break;}
                case wd_flat_8: {scr_set_layer_flats(); break;}
                case wd_flat_9: {scr_set_layer_flats(); break;}
                case wd_flat_10: {scr_set_layer_flats(); break;}
                case wd_flat_11: {scr_set_layer_flats(); break;}
                case wd_flat_12: {scr_set_layer_flats(); break;}
                case wd_flat_13: {scr_set_layer_flats(); break;}
                case wd_flat_14: {scr_set_layer_flats(); break;}
                case wd_flat_15: {scr_set_layer_flats(); break;}
                case wd_flat_16: {scr_set_layer_flats(); break;}
                case wd_flat_18: {scr_set_layer_flats(); break;}
                case wd_flat_19: {scr_set_layer_flats(); break;}
                case wd_flat_20: {scr_set_layer_flats(); break;}
                case wd_flat_21: {scr_set_layer_flats(); break;}
                case wd_flat_22: {scr_set_layer_flats(); break;}
                case wd_flat_23: {scr_set_layer_flats(); break;}
                case wd_flat_24: {scr_set_layer_flats(); break;}
                case wd_flat_25: {scr_set_layer_flats(); break;}
                case wd_flat_26: {scr_set_layer_flats(); break;}
                case wd_flat_27: {scr_set_layer_flats(); break;}
                case wd_flat_28: {scr_set_layer_flats(); break;}
                case wd_flat_29: {scr_set_layer_flats(); break;}
                case wd_flat_30: {scr_set_layer_flats(); break;}
                case wd_flat_31: {scr_set_layer_flats(); break;}
                case wd_flat_32: {scr_set_layer_flats(); break;}
                case wd_flat_33: {scr_set_layer_flats(); break;}
                case wd_flat_34: {scr_set_layer_flats(); break;}
                case wd_flat_35: {scr_set_layer_flats(); break;}
                case wd_flat_36: {scr_set_layer_flats(); break;}
                case wd_flat_37: {scr_set_layer_flats(); break;}
                case wd_flat_38: {scr_set_layer_flats(); break;}
                case wd_flat_39: {scr_set_layer_flats(); break;}
                case wd_flat_40: {scr_set_layer_flats(); break;}
                case wd_flat_41: {scr_set_layer_flats(); break;}
                case wd_flat_42: {scr_set_layer_flats(); break;}
                case wd_flat_43: {scr_set_layer_flats(); break;}
                case wd_flat_44: {scr_set_layer_flats(); break;}
                case wd_flat_45: {scr_set_layer_flats(); break;}
                case wd_flat_46: {scr_set_layer_flats(); break;}
                case wd_flat_47: {scr_set_layer_flats(); break;}
                case wd_flat_48: {scr_set_layer_flats(); break;}
                case wd_flat_49: {scr_set_layer_flats(); break;}
                case wd_flat_50: {scr_set_layer_flats(); break;}
                case wd_flat_51: {scr_set_layer_flats(); break;}
                case wd_flat_52: {scr_set_layer_flats(); break;}
                case wd_flat_53: {scr_set_layer_flats(); break;}
                case wd_flat_54: {scr_set_layer_flats(); break;}
                case wd_flat_55: {scr_set_layer_flats(); break;}
                case wd_flat_56: {scr_set_layer_flats(); break;}
                case wd_flat_57: {scr_set_layer_flats(); break;}
                case wd_flat_58: {scr_set_layer_flats(); break;}
                case wd_flat_59: {scr_set_layer_flats(); break;}
                case wd_flat_60: {scr_set_layer_flats(); break;}
                case wd_flat_61: {scr_set_layer_flats(); break;}
                case wd_flat_62: {scr_set_layer_flats(); break;}
                case wd_flat_63: {scr_set_layer_flats(); break;}
                case wd_flat_64: {scr_set_layer_flats(); break;}
                case wd_flat_65: {scr_set_layer_flats(); break;}
                case wd_flat_66: {scr_set_layer_flats(); break;}
                case wd_flat_67: {scr_set_layer_flats(); break;}
                case wd_flat_68: {scr_set_layer_flats(); break;}
                case wd_flat_69: {scr_set_layer_flats(); break;}
                case wd_flat_70: {scr_set_layer_flats(); break;}
                case wd_flat_71: {scr_set_layer_flats(); break;}
                case wd_flat_72: {scr_set_layer_flats(); break;}
                case wd_flat_73: {scr_set_layer_flats(); break;}
                case wd_flat_74: {scr_set_layer_flats(); break;}
                case wd_flat_75: {scr_set_layer_flats(); break;}
                case wd_flat_76: {scr_set_layer_flats(); break;}
                case wd_flat_77: {scr_set_layer_flats(); break;}
                case wd_flat_78: {scr_set_layer_flats(); break;}
                case wd_flat_79: {scr_set_layer_flats(); break;}
                case wd_flat_80: {scr_set_layer_flats(); break;}
                case wd_flat_81: {scr_set_layer_flats(); break;}
                case wd_flat_82: {scr_set_layer_flats(); break;}
                case wd_flat_83: {scr_set_layer_flats(); break;}
                case wd_flat_84: {scr_set_layer_flats(); break;}
                case wd_flat_85: {scr_set_layer_flats(); break;}
                case wd_flat_86: {scr_set_layer_flats(); break;}
                case wd_flat_87: {scr_set_layer_flats(); break;}
                case wd_flat_88: {scr_set_layer_flats(); break;}
                case wd_flat_89: {scr_set_layer_flats(); break;}
                case wd_flat_90: {scr_set_layer_flats(); break;}
                case wd_flat_91: {scr_set_layer_flats(); break;}
                case wd_flat_92: {scr_set_layer_flats(); break;}
                case wd_flat_93: {scr_set_layer_flats(); break;}
                case wd_flat_94: {scr_set_layer_flats(); break;}
                case wd_flat_95: {scr_set_layer_flats(); break;}
                case wd_flat_96: {scr_set_layer_flats(); break;}
                case wd_flat_97: {scr_set_layer_flats(); break;}
                case wd_flat_98: {scr_set_layer_flats(); break;}
                case wd_flat_99: {scr_set_layer_flats(); break;}
                case wd_flat_100: {scr_set_layer_flats(); break;}
                case wd_flat_101: {scr_set_layer_flats(); break;}
                case wd_flat_102: {scr_set_layer_flats(); break;}
                case wd_flat_103: {scr_set_layer_flats(); break;}
                case wd_flat_104: {scr_set_layer_flats(); break;}
                case wd_flat_105: {scr_set_layer_flats(); break;}
                case wd_flat_106: {scr_set_layer_flats(); break;}
                case wd_flat_107: {scr_set_layer_flats(); break;}
                case wd_flat_108: {scr_set_layer_flats(); break;}
                case wd_flat_109: {scr_set_layer_flats(); break;}
                case wd_flat_110: {scr_set_layer_flats(); break;}
                case wd_flat_111: {scr_set_layer_flats(); break;}
                case wd_flat_112: {scr_set_layer_flats(); break;}
                case wd_flat_113: {scr_set_layer_flats(); break;}
                case wd_flat_114: {scr_set_layer_flats(); break;}
                case wd_flat_115: {scr_set_layer_flats(); break;}
                case wd_flat_116: {scr_set_layer_flats(); break;}
                case wd_flat_117: {scr_set_layer_flats(); break;}
                case wd_flat_118: {scr_set_layer_flats(); break;}
                case wd_flat_119: {scr_set_layer_flats(); break;}
                case wd_flat_120: {scr_set_layer_flats(); break;}
                case wd_flat_121: {scr_set_layer_flats(); break;}
                case wd_flat_122: {scr_set_layer_flats(); break;}
                case wd_flat_123: {scr_set_layer_flats(); break;}
                case wd_flat_124: {scr_set_layer_flats(); break;}
                case wd_flat_125: {scr_set_layer_flats(); break;}
                case wd_flat_126: {scr_set_layer_flats(); break;}
                case wd_flat_127: {scr_set_layer_flats(); break;}
                case wd_flat_128: {scr_set_layer_flats(); break;}
                case wd_flat_129: {scr_set_layer_flats(); break;}
                case wd_flat_130: {scr_set_layer_flats(); break;}
                case wd_flat_131: {scr_set_layer_flats(); break;}
                case wd_flat_132: {scr_set_layer_flats(); break;}
                case wd_flat_133: {scr_set_layer_flats(); break;}
                case wd_flat_134: {scr_set_layer_flats(); break;}
                case wd_flat_135: {scr_set_layer_flats(); break;}
                case wd_flat_136: {scr_set_layer_flats(); break;}
                case wd_flat_137: {scr_set_layer_flats(); break;}
                case wd_flat_138: {scr_set_layer_flats(); break;}
                case wd_flat_139: {scr_set_layer_flats(); break;}
                case wd_flat_140: {scr_set_layer_flats(); break;}
                case wd_flat_141: {scr_set_layer_flats(); break;}
                case wd_flat_142: {scr_set_layer_flats(); break;}
                case wd_flat_143: {scr_set_layer_flats(); break;}
                case wd_flat_144: {scr_set_layer_flats(); break;}
                case wd_flat_145: {scr_set_layer_flats(); break;}
                case wd_flat_146: {scr_set_layer_flats(); break;}
                case wd_flat_147: {scr_set_layer_flats(); break;}
                case wd_flat_148: {scr_set_layer_flats(); break;}
                case wd_flat_149: {scr_set_layer_flats(); break;}
                case wd_flat_150: {scr_set_layer_flats(); break;}
                case wd_flat_151: {scr_set_layer_flats(); break;}
                case wd_flat_152: {scr_set_layer_flats(); break;}
                case wd_flat_153: {scr_set_layer_flats(); break;}
                case wd_flat_154: {scr_set_layer_flats(); break;}
                case wd_flat_155: {scr_set_layer_flats(); break;}
                case wd_flat_156: {scr_set_layer_flats(); break;}
                case wd_flat_157: {scr_set_layer_flats(); break;}
                //Ramps
                case wd_ramp_0: {scr_set_layer_slopes(); break;}
                case wd_ramp_1: {scr_set_layer_slopes(); break;}
                case wd_ramp_2: {scr_set_layer_slopes(); break;}
                case wd_ramp_3: {scr_set_layer_slopes(); break;}
                case wd_ramp_4: {scr_set_layer_slopes(); break;}
                case wd_ramp_5: {scr_set_layer_slopes(); break;}
                case wd_ramp_6: {scr_set_layer_slopes(); break;}
                case wd_ramp_7: {scr_set_layer_slopes(); break;}
                case wd_ramp_8: {scr_set_layer_slopes(); break;}
                case wd_ramp_9: {scr_set_layer_slopes(); break;}
                case wd_ramp_10: {scr_set_layer_slopes(); break;}
                case wd_ramp_11: {scr_set_layer_slopes(); break;}
                case wd_ramp_12: {scr_set_layer_slopes(); break;}
                case wd_ramp_13: {scr_set_layer_slopes(); break;}
                case wd_ramp_14: {scr_set_layer_slopes(); break;}
                case wd_ramp_15: {scr_set_layer_slopes(); break;}
                case wd_ramp_16: {scr_set_layer_slopes(); break;}
                case wd_ramp_17: {scr_set_layer_slopes(); break;}
                case wd_ramp_18: {scr_set_layer_slopes(); break;}
                case wd_ramp_19: {scr_set_layer_slopes(); break;}
                case wd_ramp_20: {scr_set_layer_slopes(); break;}
                case wd_ramp_21: {scr_set_layer_slopes(); break;}
                case wd_ramp_22: {scr_set_layer_slopes(); break;}
                case wd_ramp_23: {scr_set_layer_slopes(); break;}
                case wd_ramp_24: {scr_set_layer_slopes(); break;}
                case wd_ramp_25: {scr_set_layer_slopes(); break;}
                case wd_ramp_26: {scr_set_layer_slopes(); break;}
                case wd_ramp_27: {scr_set_layer_slopes(); break;}
                case cs_ramp_6:  {scr_set_layer_slopes(); break;}
                case cs_ramp_7:  {scr_set_layer_slopes(); break;}
                case cs_ramp_8:  {scr_set_layer_slopes(); break;}
                case cs_ramp_9:  {scr_set_layer_slopes(); break;}
                case cs_ramp_18: {scr_set_layer_slopes(); break;}
                case cs_ramp_19: {scr_set_layer_slopes(); break;}
                case cs_ramp_20: {scr_set_layer_slopes(); break;}
                case cs_ramp_21: {scr_set_layer_slopes(); break;}
                case cs_loop_0: {scr_set_layer_slopes(); break;}
                case cs_loop_1: {scr_set_layer_slopes(); break;}
                case cs_loop_2: {scr_set_layer_slopes(); break;}
                case cs_loop_3: {scr_set_layer_slopes(); break;}
                case cs_loop_8: {scr_set_layer_slopes(); break;}
                case cs_loop_9: {scr_set_layer_slopes(); break;}
                case cs_loop_10: {scr_set_layer_slopes(); break;}
                case cs_loop_11: {scr_set_layer_slopes(); break;}
                case cs_donut_2: {scr_set_layer_slopes(); break;}
                case cs_donut_3: {scr_set_layer_slopes(); break;}
                case cs_donut_4: {scr_set_layer_slopes(); break;}
                case cs_donut_5: {scr_set_layer_slopes(); break;}
                case cs_donut_6: {scr_set_layer_slopes(); break;}
                case cs_donut_7: {scr_set_layer_slopes(); break;}
                case cs_donut_8: {scr_set_layer_slopes(); break;}
                case cs_donut_9: {scr_set_layer_slopes(); break;}
                //Slopes
                case wd_slope_0: {scr_set_layer_slopes(); break;}
                case wd_slope_1: {scr_set_layer_slopes(); break;}
                case wd_slope_2: {scr_set_layer_slopes(); break;}
                case wd_slope_3: {scr_set_layer_slopes(); break;}
                case wd_slope_4: {scr_set_layer_slopes(); break;}
                case wd_slope_5: {scr_set_layer_slopes(); break;}
                case wd_slope_6: {scr_set_layer_slopes(); break;}
                case wd_slope_7: {scr_set_layer_slopes(); break;}
                case wd_slope_8: {scr_set_layer_slopes(); break;}
                case wd_slope_9: {scr_set_layer_slopes(); break;}
                case wd_slope_10: {scr_set_layer_slopes(); break;}
                case wd_slope_11: {scr_set_layer_slopes(); break;}
                case wd_slope_12: {scr_set_layer_slopes(); break;}
                case wd_slope_13: {scr_set_layer_slopes(); break;}
                case wd_slope_14: {scr_set_layer_slopes(); break;}
                case wd_slope_15: {scr_set_layer_slopes(); break;}
                case wd_slope_16: {scr_set_layer_slopes(); break;}
                case wd_slope_17: {scr_set_layer_slopes(); break;}
                case wd_slope_18: {scr_set_layer_slopes(); break;}
                case wd_slope_19: {scr_set_layer_slopes(); break;}
                case wd_slope_20: {scr_set_layer_slopes(); break;}
                case wd_slope_21: {scr_set_layer_slopes(); break;}
                case wd_slope_22: {scr_set_layer_slopes(); break;}
                case wd_slope_23: {scr_set_layer_slopes(); break;}
                case wd_slope_24: {scr_set_layer_slopes(); break;}
                case wd_slope_25: {scr_set_layer_slopes(); break;}
                case wd_slope_26: {scr_set_layer_slopes(); break;}
                case wd_slope_27: {scr_set_layer_slopes(); break;}
                case wd_slope_28: {scr_set_layer_slopes(); break;}
                case wd_slope_29: {scr_set_layer_slopes(); break;}
                case wd_slope_30: {scr_set_layer_slopes(); break;}
                case wd_slope_31: {scr_set_layer_slopes(); break;}
                case wd_donut_2: {scr_set_layer_slopes(); break;}
                case wd_donut_3: {scr_set_layer_slopes(); break;}
                case wd_donut_4: {scr_set_layer_slopes(); break;}
                case wd_donut_5: {scr_set_layer_slopes(); break;}
                case wd_donut_6: {scr_set_layer_slopes(); break;}
                case wd_donut_7: {scr_set_layer_slopes(); break;}
                case wd_donut_8: {scr_set_layer_slopes(); break;}
                case wd_donut_9: {scr_set_layer_slopes(); break;}
                case cs_slope_0: {scr_set_layer_slopes(); break;}
                case cs_slope_1: {scr_set_layer_slopes(); break;}
                case cs_slope_2: {scr_set_layer_slopes(); break;}
                case cs_slope_3: {scr_set_layer_slopes(); break;}
                case cs_slope_alt_0: {scr_set_layer_slopes(); break;}
                case cs_slope_alt_1: {scr_set_layer_slopes(); break;}
                case cs_slope_alt_2: {scr_set_layer_slopes(); break;}
                //FOFs
                case wd_fof_0:    {scr_set_layer_slopes(); break;}
                case wd_fof_1:    {scr_set_layer_slopes(); break;}
                case wd_fof_2:    {scr_set_layer_slopes(); break;}
                case wd_fof_3:    {scr_set_layer_slopes(); break;}
                case wd_fof_4:    {scr_set_layer_slopes(); break;}
                //Rails
                case rg_rail_0:    {scr_set_layer_slopes(); break;}
                case rg_rail_1:    {scr_set_layer_slopes(); break;}
                case rg_rail_2:    {scr_set_layer_slopes(); break;}
                case rg_rail_3:    {scr_set_layer_slopes(); break;}
                case rg_rail_4:    {scr_set_layer_slopes(); break;}
                case rg_rail_5:    {scr_set_layer_slopes(); break;}
                case rg_rail_6:    {scr_set_layer_slopes(); break;}
                case rg_rail_7:    {scr_set_layer_slopes(); break;}
                case rg_rail_12:    {scr_set_layer_slopes(); break;}
                case rg_rail_13:    {scr_set_layer_slopes(); break;}
                case rg_rail_14:    {scr_set_layer_slopes(); break;}
                case rg_rail_15:    {scr_set_layer_slopes(); break;}
                case rg_rail_16:    {scr_set_layer_slopes(); break;}
                case rg_rail_17:    {scr_set_layer_slopes(); break;}
                case rg_rail_sloped_1:   {scr_set_layer_slopes(); break;}
                case rg_rail_sloped_2:   {scr_set_layer_slopes(); break;}
                case rg_rail_slope_6:    {scr_set_layer_slopes(); break;}
                case rg_rail_slope_7:    {scr_set_layer_slopes(); break;}
                case rg_rail_slope_8:    {scr_set_layer_slopes(); break;}
                case rg_rail_slope_9:    {scr_set_layer_slopes(); break;}
                case rg_rail_slope_2:    {scr_set_layer_slopes(); break;}
                case rg_rail_slope_3:    {scr_set_layer_slopes(); break;}
                case rg_rail_slope_4:    {scr_set_layer_slopes(); break;}
                case rg_rail_slope_5:    {scr_set_layer_slopes(); break;}
                case rg_rail_flat_0:    {scr_set_layer_flats(); break;}
                case rg_rail_flat_1:    {scr_set_layer_flats(); break;}
                case rg_rail_flat_2:    {scr_set_layer_flats(); break;}
                case rg_rail_flat_3:    {scr_set_layer_flats(); break;}
                case rg_rail_flat_4:    {scr_set_layer_flats(); break;}
                case rg_rail_flat_5:    {scr_set_layer_flats(); break;}
                case rg_rail_flat_6:    {scr_set_layer_flats(); break;}
                case rg_rail_flat_7:    {scr_set_layer_flats(); break;}
                case rg_rail_flat_8:    {scr_set_layer_flats(); break;}
                case rg_rail_flat_9:    {scr_set_layer_flats(); break;}
                case rg_rail_flat_10:   {scr_set_layer_flats(); break;}
                case rg_rail_flat_11:   {scr_set_layer_flats(); break;}
                case rg_rail_ramp_4:    {scr_set_layer_slopes(); break;}
                case rg_rail_ramp_5:    {scr_set_layer_slopes(); break;}
                case rg_rail_ramp_16:   {scr_set_layer_slopes(); break;}
                case rg_rail_ramp_17:   {scr_set_layer_slopes(); break;}
                //Scenery
                case wd_scenery_0: {scr_set_layer_scene(); break;}
                case wd_scenery_1: {scr_set_layer_scene(); break;}
                case wd_scenery_2: {scr_set_layer_scene(); break;}
                case wd_scenery_3: {scr_set_layer_scene(); break;}
                case wd_scenery_4: {scr_set_layer_scene(); break;}
                case wd_scenery_5: {scr_set_layer_scene(); break;}
                case wd_scenery_6: {scr_set_layer_scene(); break;}
                case wd_scenery_7: {scr_set_layer_scene(); break;}
                case wd_scenery_8: {scr_set_layer_scene(); break;}
                case wd_scenery_9: {scr_set_layer_scene(); break;}
                case wd_scenery_10: {scr_set_layer_scene(); break;}
                case wd_scenery_11: {scr_set_layer_scene(); break;}
                case wd_scenery_12: {scr_set_layer_scene(); break;}
                case wd_scenery_13: {scr_set_layer_scene(); break;}
                case wd_scenery_14: {scr_set_layer_scene(); break;}
                case wd_scenery_15: {scr_set_layer_scene(); break;}
                case wd_scenery_16: {scr_set_layer_scene(); break;}
                case wd_scenery_17: {scr_set_layer_scene(); break;}
                case wd_scenery_18: {scr_set_layer_scene(); break;}
                case wd_scenery_19: {scr_set_layer_scene(); break;}
                case wd_scenery_20: {scr_set_layer_scene(); break;}
                case wd_scenery_21: {scr_set_layer_scene(); break;}
                case wd_scenery_22: {scr_set_layer_scene(); break;}
                case wd_scenery_23: {scr_set_layer_scene(); break;}
                case wd_scenery_24: {scr_set_layer_scene(); break;}
                case wd_scenery_25: {scr_set_layer_scene(); break;}
                case wd_scenery_26: {scr_set_layer_scene(); break;}
                case wd_scenery_27: {scr_set_layer_scene(); break;}
                case wd_scenery_28: {scr_set_layer_scene(); break;}
                case wd_scenery_29: {scr_set_layer_scene(); break;}
                case wd_scenery_30: {scr_set_layer_scene(); break;}
                case wd_scenery_31: {scr_set_layer_scene(); break;}
                case wd_scenery_32: {scr_set_layer_scene(); break;}
                case wd_scenery_33: {scr_set_layer_scene(); break;}
                case wd_scenery_34: {scr_set_layer_scene(); break;}
                case wd_scenery_35: {scr_set_layer_scene(); break;}
                case wd_scenery_36: {scr_set_layer_scene(); break;}
                case wd_scenery_37: {scr_set_layer_scene(); break;}
                case wd_scenery_38: {scr_set_layer_scene(); break;}
                case wd_scenery_39: {scr_set_layer_scene(); break;}
                case wd_scenery_40: {scr_set_layer_scene(); break;}
                case wd_scenery_41: {scr_set_layer_scene(); break;}
                case wd_scenery_42: {scr_set_layer_scene(); break;}
                case wd_scenery_43: {scr_set_layer_scene(); break;}
                case wd_scenery_44: {scr_set_layer_scene(); break;}
                case wd_scenery_45: {scr_set_layer_scene(); break;}
                case wd_scenery_46: {scr_set_layer_scene(); break;}
                case wd_scenery_47: {scr_set_layer_scene(); break;}
                case wd_scenery_48: {scr_set_layer_scene(); break;}
                case wd_scenery_49: {scr_set_layer_scene(); break;}
                case wd_scenery_50: {scr_set_layer_scene(); break;}
                case wd_scenery_51: {scr_set_layer_scene(); break;}
                case wd_scenery_52: {scr_set_layer_scene(); break;}
                case wd_scenery_53: {scr_set_layer_scene(); break;}
                case wd_scenery_54: {scr_set_layer_scene(); break;}
                case wd_scenery_55: {scr_set_layer_scene(); break;}
                case wd_scenery_56: {scr_set_layer_scene(); break;}
                case wd_scenery_57: {scr_set_layer_scene(); break;}
                case wd_scenery_58: {scr_set_layer_scene(); break;}
                case wd_scenery_59: {scr_set_layer_scene(); break;}
                case wd_scenery_60: {scr_set_layer_scene(); break;}
                case wd_scenery_61: {scr_set_layer_scene(); break;}
                case wd_scenery_62: {scr_set_layer_scene(); break;}
                case wd_scenery_63: {scr_set_layer_scene(); break;}
                case wd_scenery_64: {scr_set_layer_scene(); break;}
                case wd_scenery_65: {scr_set_layer_scene(); break;}
                case wd_scenery_66: {scr_set_layer_scene(); break;}
                case wd_scenery_67: {scr_set_layer_scene(); break;}
                case wd_scenery_68: {scr_set_layer_scene(); break;}
                case wd_scenery_69: {scr_set_layer_scene(); break;}
                case wd_scenery_70: {scr_set_layer_scene(); break;}
                case wd_scenery_71: {scr_set_layer_scene(); break;}
                case wd_scenery_72: {scr_set_layer_scene(); break;}
                case wd_scenery_73: {scr_set_layer_scene(); break;}
                case wd_scenery_74: {scr_set_layer_scene(); break;}
                case wd_scenery_75: {scr_set_layer_scene(); break;}
                case wd_scenery_76: {scr_set_layer_scene(); break;}
                case wd_scenery_77: {scr_set_layer_scene(); break;}
                case wd_scenery_78: {scr_set_layer_scene(); break;}
                case wd_scenery_79: {scr_set_layer_scene(); break;}
                case wd_scenery_80: {scr_set_layer_scene(); break;}
                case wd_scenery_81: {scr_set_layer_scene(); break;}
                case wd_scenery_82: {scr_set_layer_scene(); break;}
                case wd_scenery_83: {scr_set_layer_scene(); break;}
                case wd_scenery_84: {scr_set_layer_scene(); break;}
                case wd_scenery_85: {scr_set_layer_scene(); break;}
                case wd_scenery_86: {scr_set_layer_scene(); break;}
                case wd_scenery_87: {scr_set_layer_scene(); break;}
                case wd_scenery_88: {scr_set_layer_scene(); break;}
                case wd_scenery_89: {scr_set_layer_scene(); break;}
                case wd_scenery_90: {scr_set_layer_scene(); break;}
                case wd_scenery_91: {scr_set_layer_scene(); break;}
                case wd_scenery_92: {scr_set_layer_scene(); break;}
                case wd_scenery_93: {scr_set_layer_scene(); break;}
                case wd_scenery_94: {scr_set_layer_scene(); break;}
                case wd_scenery_95: {scr_set_layer_scene(); break;}
                case wd_scenery_96: {scr_set_layer_scene(); break;}
                case wd_scenery_97: {scr_set_layer_scene(); break;}
                case wd_scenery_98: {scr_set_layer_scene(); break;}
                case wd_scenery_99: {scr_set_layer_scene(); break;}
                case wd_scenery_100: {scr_set_layer_scene(); break;}
                case wd_scenery_101: {scr_set_layer_scene(); break;}
                case wd_scenery_102: {scr_set_layer_scene(); break;}
                case wd_scenery_103: {scr_set_layer_scene(); break;}
                case wd_scenery_104: {scr_set_layer_scene(); break;}
                case wd_scenery_105: {scr_set_layer_scene(); break;}
                case wd_scenery_106: {scr_set_layer_scene(); break;}
                case wd_scenery_107: {scr_set_layer_scene(); break;}
                case wd_scenery_108: {scr_set_layer_scene(); break;}
                case wd_scenery_109: {scr_set_layer_scene(); break;}
                case wd_scenery_110: {scr_set_layer_scene(); break;}
                case wd_scenery_111: {scr_set_layer_scene(); break;}
                case wd_scenery_112: {scr_set_layer_scene(); break;}
                case wd_scenery_113: {scr_set_layer_scene(); break;}
                case wd_scenery_114: {scr_set_layer_scene(); break;}
                case wd_scenery_115: {scr_set_layer_scene(); break;}
                case wd_scenery_116: {scr_set_layer_scene(); break;}
                case wd_scenery_117: {scr_set_layer_scene(); break;}
                case wd_scenery_118: {scr_set_layer_scene(); break;}
                case wd_scenery_119: {scr_set_layer_scene(); break;}
                case wd_scenery_120: {scr_set_layer_scene(); break;}
                case wd_scenery_121: {scr_set_layer_scene(); break;}
                case wd_scenery_122: {scr_set_layer_scene(); break;}
                case wd_scenery_123: {scr_set_layer_scene(); break;}
                case wd_scenery_124: {scr_set_layer_scene(); break;}
                case wd_scenery_125: {scr_set_layer_scene(); break;}
                case wd_scenery_126: {scr_set_layer_scene(); break;}
                case wd_scenery_127: {scr_set_layer_flats(); break;}
                case wd_scenery_128: {scr_set_layer_scene(); break;}
                case wd_scenery_129: {scr_set_layer_scene(); break;}
                case wd_scenery_130: {scr_set_layer_scene(); break;}
                case wd_scenery_131: {scr_set_layer_scene(); break;}
                case wd_scenery_312: {scr_set_layer_scene(); break;}
                case wd_scenery_313: {scr_set_layer_scene(); break;}
                case wd_scenery_314: {scr_set_layer_scene(); break;}
                case wd_scenery_315: {scr_set_layer_scene(); break;}
                case wd_scenery_316: {scr_set_layer_scene(); break;}
                case wd_scenery_317: {scr_set_layer_scene(); break;}
                case wd_scenery_318: {scr_set_layer_scene(); break;}
                case wd_scenery_319: {scr_set_layer_scene(); break;}
                case wd_scenery_320: {scr_set_layer_scene(); break;}
                case wd_scenery_321: {scr_set_layer_scene(); break;}
                case wd_scenery_322: {scr_set_layer_scene(); break;}
                case wd_scenery_323: {scr_set_layer_scene(); break;}
                case wd_scenery_324: {scr_set_layer_scene(); break;}
                case wd_scenery_325: {scr_set_layer_scene(); break;}
                case wd_scenery_326: {scr_set_layer_scene(); break;}
                case wd_scenery_327: {scr_set_layer_scene(); break;}
                case wd_scenery_328: {scr_set_layer_scene(); break;}
                case wd_scenery_329: {scr_set_layer_scene(); break;}
                case wd_scenery_330: {scr_set_layer_scene(); break;}
                case wd_scenery_331: {scr_set_layer_scene(); break;}
                case wd_scenery_332: {scr_set_layer_scene(); break;}
                case wd_scenery_333: {scr_set_layer_scene(); break;}
                case wd_scenery_334: {scr_set_layer_scene(); break;}
                case ma_scene_0:     {scr_set_layer_scene(); break;}
                case ma_scene_1:     {scr_set_layer_scene(); break;}
                case ma_scene_2:     {scr_set_layer_scene(); break;}
                case ma_scene_3:     {scr_set_layer_scene(); break;}
                case ma_scene_4:     {scr_set_layer_scene(); break;}
                case ma_scene_5:     {scr_set_layer_scene(); break;}
                case ma_scene_6:     {scr_set_layer_scene(); break;}
                case ma_scene_7:     {scr_set_layer_scene(); break;}
                case ma_scene_8:     {scr_set_layer_scene(); break;}
                case ma_scene_9:     {scr_set_layer_scene(); break;}
                case ma_scene_10:    {scr_set_layer_scene(); break;}
                case ma_scene_11:    {scr_set_layer_scene(); break;}
                case ma_scene_12:    {scr_set_layer_scene(); break;}
                case ma_flat_4:      {scr_set_layer_scene(); break;}
                case ma_flat_5:      {scr_set_layer_scene(); break;}
                case ma_flat_6:      {scr_set_layer_scene(); break;}
                //Mountain Tile Set
                case mnt_flat_0:    {scr_set_layer_flats(); break;}
                case mnt_flat_1:    {scr_set_layer_flats(); break;}
                case mnt_flat_2:    {scr_set_layer_flats(); break;}
                case mnt_flat_3:    {scr_set_layer_flats(); break;}
                case mnt_flat_4:    {scr_set_layer_flats(); break;}
                case mnt_flat_5:    {scr_set_layer_flats(); break;}
                case mnt_flat_6:    {scr_set_layer_flats(); break;}
                case mnt_flat_7:    {scr_set_layer_flats(); break;}
                case mnt_flat_8:    {scr_set_layer_flats(); break;}
                case mnt_flat_9:    {scr_set_layer_flats(); break;}
                case mnt_flat_10:   {scr_set_layer_flats(); break;}
                case mnt_flat_11:   {scr_set_layer_flats(); break;}
                case mnt_flat_12:   {scr_set_layer_flats(); break;}
                case mnt_flat_13:   {scr_set_layer_flats(); break;}
                case mnt_flat_14:   {scr_set_layer_flats(); break;}
                case mnt_flat_15:   {scr_set_layer_flats(); break;}
                case mnt_flat_16:   {scr_set_layer_flats(); break;}
                case mnt_flat_17:   {scr_set_layer_flats(); break;}
                case mnt_flat_18:   {scr_set_layer_flats(); break;}
                case mnt_flat_19:   {scr_set_layer_flats(); break;}
                case mnt_flat_20:   {scr_set_layer_flats(); break;}
                case mnt_flat_21:   {scr_set_layer_flats(); break;}
                case mnt_flat_22:   {scr_set_layer_flats(); break;}
                case mnt_flat_23:   {scr_set_layer_flats(); break;}
                case mnt_flat_24:   {scr_set_layer_flats(); break;}
                case mnt_flat_25:   {scr_set_layer_flats(); break;}
                case mnt_flat_26:   {scr_set_layer_flats(); break;}
                case mnt_flat_27:   {scr_set_layer_flats(); break;}
                case mnt_flat_28:   {scr_set_layer_flats(); break;}
                case mnt_flat_29:   {scr_set_layer_flats(); break;}
                case mnt_flat_30:   {scr_set_layer_flats(); break;}
                case mnt_flat_31:   {scr_set_layer_flats(); break;}
                case mnt_flat_32:   {scr_set_layer_flats(); break;}
                case mnt_flat_33:   {scr_set_layer_flats(); break;}
                case mnt_flat_34:   {scr_set_layer_flats(); break;}
                case mnt_flat_35:   {scr_set_layer_flats(); break;}
                case mnt_flat_36:   {scr_set_layer_flats(); break;}
                case mnt_flat_37:   {scr_set_layer_flats(); break;}
                case mnt_flat_38:   {scr_set_layer_flats(); break;}
                case mnt_flat_39:   {scr_set_layer_flats(); break;}
                case mnt_flat_40:   {scr_set_layer_flats(); break;}
                case mnt_flat_41:   {scr_set_layer_flats(); break;}
                case mnt_flat_42:   {scr_set_layer_flats(); break;}
                case mnt_flat_43:   {scr_set_layer_flats(); break;}
                case mnt_flat_44:   {scr_set_layer_flats(); break;}
                case mnt_flat_45:   {scr_set_layer_flats(); break;}
                case mnt_flat_46:   {scr_set_layer_flats(); break;}
                case mnt_flat_47:   {scr_set_layer_flats(); break;}
                case mnt_flat_48:   {scr_set_layer_flats(); break;}
                case mnt_flat_49:   {scr_set_layer_flats(); break;}
                case mnt_flat_50:   {scr_set_layer_flats(); break;}
                case mnt_flat_51:   {scr_set_layer_flats(); break;}
                case mnt_flat_52:   {scr_set_layer_flats(); break;}
                case mnt_flat_53:   {scr_set_layer_flats(); break;}
                case mnt_flat_54:   {scr_set_layer_flats(); break;}
                case mnt_flat_55:   {scr_set_layer_flats(); break;}
                case mnt_flat_56:   {scr_set_layer_flats(); break;}
                case mnt_flat_57:   {scr_set_layer_flats(); break;}
                case mnt_flat_58:   {scr_set_layer_flats(); break;}
                case mnt_flat_59:   {scr_set_layer_flats(); break;}
                case mnt_flat_60:   {scr_set_layer_flats(); break;}
                case mnt_flat_61:   {scr_set_layer_flats(); break;}
                case mnt_flat_62:   {scr_set_layer_flats(); break;}
                case mnt_flat_63:   {scr_set_layer_flats(); break;}
                case mnt_flat_64:   {scr_set_layer_flats(); break;}
                case mnt_flat_65:   {scr_set_layer_flats(); break;}
                case mnt_flat_66:   {scr_set_layer_flats(); break;}
                case mnt_flat_67:   {scr_set_layer_flats(); break;}
                case mnt_flat_68:   {scr_set_layer_flats(); break;}
                case mnt_flat_69:   {scr_set_layer_flats(); break;}
                case mnt_flat_70:   {scr_set_layer_flats(); break;}
                case mnt_flat_71:   {scr_set_layer_flats(); break;}
                case mnt_flat_72:   {scr_set_layer_flats(); break;}
                case mnt_flat_73:   {scr_set_layer_flats(); break;}
                case mnt_flat_74:   {scr_set_layer_flats(); break;}
                case mnt_flat_75:   {scr_set_layer_flats(); break;}
                case mnt_flat_76:   {scr_set_layer_flats(); break;}
                case mnt_flat_77:   {scr_set_layer_flats(); break;}
                case mnt_flat_78:   {scr_set_layer_flats(); break;}
                case mnt_flat_79:   {scr_set_layer_flats(); break;}
                case mnt_flat_80:   {scr_set_layer_flats(); break;}
                case mnt_flat_81:   {scr_set_layer_flats(); break;}
                case mnt_flat_82:   {scr_set_layer_flats(); break;}
                case mnt_flat_83:   {scr_set_layer_flats(); break;}
                case mnt_flat_84:   {scr_set_layer_flats(); break;}
                case mnt_flat_85:   {scr_set_layer_flats(); break;}
                case mnt_flat_86:   {scr_set_layer_flats(); break;}
                case mnt_flat_87:   {scr_set_layer_flats(); break;}
                case mnt_flat_88:   {scr_set_layer_flats(); break;}
                case mnt_flat_89:   {scr_set_layer_flats(); break;}
                case mnt_flat_90:   {scr_set_layer_flats(); break;}
                case mnt_ramp_22:   {scr_set_layer_slopes(); break;}
                case mnt_ramp_23:   {scr_set_layer_slopes(); break;}
                case mnt_ramp_24:   {scr_set_layer_slopes(); break;}
                case mnt_ramp_25:   {scr_set_layer_slopes(); break;}
                case mnt_scene_79:  {scr_set_layer_scene(); break;}
                case mnt_scene_80:  {scr_set_layer_scene(); break;}
                case mnt_scene_81:  {scr_set_layer_scene(); break;}
                case spr_spikes_11: {scr_set_layer_flats(); break;}
                case spr_spikes_12: {scr_set_layer_flats(); break;}
                case spr_spikes_13: {scr_set_layer_flats(); break;}
                case mnt_ramp_0:   {scr_set_layer_slopes(); break;}
                case mnt_ramp_1:   {scr_set_layer_slopes(); break;}
                case mnt_ramp_2:   {scr_set_layer_slopes(); break;}
                case mnt_ramp_3:   {scr_set_layer_slopes(); break;}
                case mnt_ramp_4:   {scr_set_layer_slopes(); break;}
                case mnt_ramp_5:   {scr_set_layer_slopes(); break;}
                case mnt_ramp_6:   {scr_set_layer_slopes(); break;}
                case mnt_ramp_7:   {scr_set_layer_slopes(); break;}
                case mnt_ramp_8:   {scr_set_layer_slopes(); break;}
                case mnt_ramp_9:   {scr_set_layer_slopes(); break;}
                case mnt_ramp_10:  {scr_set_layer_slopes(); break;}
                case mnt_ramp_11:  {scr_set_layer_slopes(); break;}
                case mnt_ramp_12:  {scr_set_layer_slopes(); break;}
                case mnt_ramp_13:  {scr_set_layer_slopes(); break;}
                case mnt_ramp_14:  {scr_set_layer_slopes(); break;}
                case mnt_ramp_15:  {scr_set_layer_slopes(); break;}
                case mnt_slope_0:  {scr_set_layer_slopes(); break;}
                case mnt_slope_1:  {scr_set_layer_slopes(); break;}
                case mnt_slope_2:  {scr_set_layer_slopes(); break;}
                case mnt_slope_3:  {scr_set_layer_slopes(); break;}
                case mnt_slope_4:  {scr_set_layer_slopes(); break;}
                case mnt_slope_5:  {scr_set_layer_slopes(); break;}
                case mnt_slope_6:  {scr_set_layer_slopes(); break;}
                case mnt_slope_7:  {scr_set_layer_slopes(); break;}
                case mnt_slope_8:  {scr_set_layer_slopes(); break;}
                case mnt_slope_9:  {scr_set_layer_slopes(); break;}
                case mnt_slope_10: {scr_set_layer_slopes(); break;}
                case mnt_slope_11: {scr_set_layer_slopes(); break;}
                case mnt_slope_12: {scr_set_layer_slopes(); break;}
                case mnt_slope_13: {scr_set_layer_slopes(); break;}
                case mnt_slope_14: {scr_set_layer_slopes(); break;}
                case mnt_slope_15: {scr_set_layer_slopes(); break;}
                case mnt_slope_16: {scr_set_layer_slopes(); break;}
                case mnt_slope_17: {scr_set_layer_slopes(); break;}
                case mnt_slope_18: {scr_set_layer_slopes(); break;}
                case mnt_slope_19: {scr_set_layer_slopes(); break;}
                case mnt_slope_20: {scr_set_layer_slopes(); break;}
                case mnt_slope_21: {scr_set_layer_slopes(); break;}
                case mnt_slope_22: {scr_set_layer_slopes(); break;}
                case mnt_slope_23: {scr_set_layer_slopes(); break;}
                case mnt_slope_24: {scr_set_layer_slopes(); break;}
                case mnt_slope_25: {scr_set_layer_slopes(); break;}
                case mnt_slope_26: {scr_set_layer_slopes(); break;}
                case mnt_slope_27: {scr_set_layer_slopes(); break;}
                case mnt_slope_28: {scr_set_layer_slopes(); break;}
                case mnt_slope_29: {scr_set_layer_slopes(); break;}
                case mnt_slope_30: {scr_set_layer_slopes(); break;}
                case mnt_slope_31: {scr_set_layer_slopes(); break;}
                case mnt_slope_snow_0: {scr_set_layer_slopes(); break;}
                case mnt_slope_snow_1: {scr_set_layer_slopes(); break;}
                case mnt_slope_snow_2: {scr_set_layer_slopes(); break;}
                case mnt_slope_grass_0: {scr_set_layer_slopes(); break;}
                case mnt_slope_grass_1: {scr_set_layer_slopes(); break;}
                case mnt_slope_grass_2: {scr_set_layer_slopes(); break;}
                
                //Scenery
                case mnt_scene_0: {scr_set_layer_scene(); break;}
                case mnt_scene_1: {scr_set_layer_scene(); break;}
                case mnt_scene_2: {scr_set_layer_scene(); break;}
                case mnt_scene_3: {scr_set_layer_scene(); break;}
                case mnt_scene_4: {scr_set_layer_scene(); break;}
                case mnt_scene_5: {scr_set_layer_scene(); break;}
                case mnt_scene_6: {scr_set_layer_scene(); break;}
                case mnt_scene_7: {scr_set_layer_scene(); break;}
                case mnt_scene_8: {scr_set_layer_scene(); break;}
                case mnt_scene_9: {scr_set_layer_scene(); break;}
                case mnt_scene_10: {scr_set_layer_scene(); break;}
                case mnt_scene_11: {scr_set_layer_scene(); break;}
                case mnt_scene_12: {scr_set_layer_scene(); break;}
                case mnt_scene_13: {scr_set_layer_scene(); break;}
                case mnt_scene_14: {scr_set_layer_scene(); break;}
                case mnt_scene_15: {scr_set_layer_scene(); break;}
                case mnt_scene_16: {scr_set_layer_scene(); break;}
                case mnt_scene_17: {scr_set_layer_scene(); break;}
                case mnt_scene_18: {scr_set_layer_scene(); break;}
                case mnt_scene_19: {scr_set_layer_scene(); break;}
                case mnt_scene_20: {scr_set_layer_scene(); break;}
                case mnt_scene_21: {scr_set_layer_scene(); break;}
                case mnt_scene_22: {scr_set_layer_scene(); break;}
                case mnt_scene_23: {scr_set_layer_scene(); break;}
                case mnt_scene_24: {scr_set_layer_scene(); break;}
                case mnt_scene_25: {scr_set_layer_scene(); break;}
                case mnt_scene_26: {scr_set_layer_scene(); break;}
                case mnt_scene_27: {scr_set_layer_scene(); break;}
                case mnt_scene_28: {scr_set_layer_scene(); break;}
                case mnt_scene_29: {scr_set_layer_scene(); break;}
                case mnt_scene_30: {scr_set_layer_scene(); break;}
                case mnt_scene_31: {scr_set_layer_scene(); break;}
                case mnt_scene_32: {scr_set_layer_scene(); break;}
                case mnt_scene_33: {scr_set_layer_scene(); break;}
                case mnt_scene_34: {scr_set_layer_scene(); break;}
                case mnt_scene_35: {scr_set_layer_scene(); break;}
                case mnt_scene_36: {scr_set_layer_scene(); break;}
                case mnt_scene_37: {scr_set_layer_scene(); break;}
                case mnt_scene_38: {scr_set_layer_scene(); break;}
                case mnt_scene_39: {scr_set_layer_scene(); break;}
                case mnt_scene_40: {scr_set_layer_scene(); break;}
                case mnt_scene_41: {scr_set_layer_scene(); break;}
                case mnt_scene_42: {scr_set_layer_scene(); break;}
                case mnt_scene_43: {scr_set_layer_scene(); break;}
                case mnt_scene_44: {scr_set_layer_scene(); break;}
                case mnt_scene_45: {scr_set_layer_scene(); break;}
                case mnt_scene_46: {scr_set_layer_scene(); break;}
                case mnt_scene_47: {scr_set_layer_scene(); break;}
                case mnt_scene_48: {scr_set_layer_scene(); break;}
                case mnt_scene_49: {scr_set_layer_scene(); break;}
                case mnt_scene_50: {scr_set_layer_scene(); break;}
                case mnt_scene_51: {scr_set_layer_scene(); break;}
                case mnt_scene_52: {scr_set_layer_scene(); break;}
                case mnt_scene_53: {scr_set_layer_scene(); break;}
                case mnt_scene_54: {scr_set_layer_scene(); break;}
                case mnt_scene_55: {scr_set_layer_scene(); break;}
                case mnt_scene_56: {scr_set_layer_scene(); break;}
                case mnt_scene_57: {scr_set_layer_scene(); break;}
                case mnt_scene_58: {scr_set_layer_scene(); break;}
                case mnt_scene_59: {scr_set_layer_scene(); break;}
                case mnt_scene_60: {scr_set_layer_scene(); break;}
                case mnt_scene_61: {scr_set_layer_scene(); break;}
                case mnt_scene_62: {scr_set_layer_scene(); break;}
                case mnt_scene_63: {scr_set_layer_scene(); break;}
                case mnt_scene_64: {scr_set_layer_scene(); break;}
                case mnt_scene_65: {scr_set_layer_scene(); break;}
                case mnt_scene_66: {scr_set_layer_scene(); break;}
                case mnt_scene_67: {scr_set_layer_scene(); break;}
                case mnt_scene_68: {scr_set_layer_scene(); break;}
                case mnt_scene_69: {scr_set_layer_scene(); break;}
                case mnt_scene_70: {scr_set_layer_scene(); break;}
                case mnt_scene_71: {scr_set_layer_scene(); break;}
                case mnt_scene_72: {scr_set_layer_scene(); break;}
                case mnt_scene_73: {scr_set_layer_scene(); break;}
                case mnt_scene_74: {scr_set_layer_scene(); break;}
                case mnt_scene_75: {scr_set_layer_scene(); break;}
                case mnt_scene_76: {scr_set_layer_scene(); break;}
                case mnt_scene_77: {scr_set_layer_scene(); break;}
                case mnt_scene_78: {scr_set_layer_scene(); break;}
                case mnt_scene_82: {scr_set_layer_scene(); break;}
                //FOFs
                case mnt_fof_0: {scr_set_layer_slopes(); break;}
                case mnt_fof_1: {scr_set_layer_slopes(); break;}
                case mnt_fof_2: {scr_set_layer_slopes(); break;}
                case mnt_fof_3: {scr_set_layer_slopes(); break;}
                case mnt_fof_4: {scr_set_layer_slopes(); break;}
                //Lagoon Tile Set
                //Flats
                case ll_flat_0: {scr_set_layer_flats(); break;}
                case ll_flat_1: {scr_set_layer_flats(); break;}
                case ll_flat_2: {scr_set_layer_flats(); break;}
                case ll_flat_3: {scr_set_layer_flats(); break;}
                case ll_flat_4: {scr_set_layer_flats(); break;}
                case ll_flat_5: {scr_set_layer_flats(); break;}
                case ll_flat_6: {scr_set_layer_flats(); break;}
                case ll_flat_7: {scr_set_layer_flats(); break;}
                case ll_flat_8: {scr_set_layer_flats(); break;}
                case ll_flat_9: {scr_set_layer_flats(); break;}
                case ll_flat_10: {scr_set_layer_flats(); break;}
                case ll_flat_11: {scr_set_layer_flats(); break;}
                case ll_flat_12: {scr_set_layer_flats(); break;}
                case ll_flat_13: {scr_set_layer_flats(); break;}
                case ll_flat_14: {scr_set_layer_flats(); break;}
                case ll_flat_15: {scr_set_layer_flats(); break;}
                case ll_flat_16: {scr_set_layer_flats(); break;}
                case ll_flat_17: {scr_set_layer_flats(); break;}
                case ll_flat_18: {scr_set_layer_flats(); break;}
                case ll_flat_19: {scr_set_layer_flats(); break;}
                case ll_flat_20: {scr_set_layer_flats(); break;}
                case ll_flat_21: {scr_set_layer_flats(); break;}
                case ll_flat_22: {scr_set_layer_flats(); break;}
                case ll_flat_23: {scr_set_layer_flats(); break;}
                case ll_flat_24: {scr_set_layer_flats(); break;}
                case ll_flat_25: {scr_set_layer_flats(); break;}
                case ll_flat_26: {scr_set_layer_flats(); break;}
                case ll_flat_27: {scr_set_layer_flats(); break;}
                case ll_flat_28: {scr_set_layer_flats(); break;}
                case ll_flat_29: {scr_set_layer_flats(); break;}
                case ll_flat_30: {scr_set_layer_flats(); break;}
                case ll_flat_31: {scr_set_layer_flats(); break;}
                case ll_flat_32: {scr_set_layer_flats(); break;}
                case ll_flat_33: {scr_set_layer_flats(); break;}
                case ll_flat_34: {scr_set_layer_flats(); break;}
                case ll_flat_35: {scr_set_layer_flats(); break;}
                case ll_flat_36: {scr_set_layer_flats(); break;}
                case ll_flat_37: {scr_set_layer_flats(); break;}
                case ll_flat_38: {scr_set_layer_flats(); break;}
                case ll_flat_39: {scr_set_layer_flats(); break;}
                case ll_flat_40: {scr_set_layer_flats(); break;}
                case ll_flat_41: {scr_set_layer_flats(); break;}
                case ll_flat_42: {scr_set_layer_flats(); break;}
                case ll_flat_43: {scr_set_layer_flats(); break;}
                case ll_flat_44: {scr_set_layer_flats(); break;}
                case ll_flat_45: {scr_set_layer_flats(); break;}
                case ll_flat_46: {scr_set_layer_flats(); break;}
                case ll_flat_47: {scr_set_layer_flats(); break;}
                case ll_flat_48: {scr_set_layer_flats(); break;}
                case ll_flat_49: {scr_set_layer_flats(); break;}
                case ll_flat_50: {scr_set_layer_flats(); break;}
                case ll_flat_51: {scr_set_layer_flats(); break;}
                case ll_flat_52: {scr_set_layer_flats(); break;}
                case ll_flat_53: {scr_set_layer_flats(); break;}
                case ll_flat_54: {scr_set_layer_flats(); break;}
                case ll_flat_55: {scr_set_layer_flats(); break;}
                case ll_flat_56: {scr_set_layer_flats(); break;}
                case ll_flat_57: {scr_set_layer_flats(); break;}
                //Slopes
                case ll_slope_0: {scr_set_layer_slopes(); break;}
                case ll_slope_1: {scr_set_layer_slopes(); break;}
                case ll_slope_2: {scr_set_layer_slopes(); break;}
                case ll_slope_3: {scr_set_layer_slopes(); break;}
                case ll_slope_4: {scr_set_layer_slopes(); break;}
                case ll_slope_5: {scr_set_layer_slopes(); break;}
                case ll_slope_6: {scr_set_layer_slopes(); break;}
                case ll_slope_7: {scr_set_layer_slopes(); break;}
                case ll_slope_8: {scr_set_layer_slopes(); break;}
                case ll_slope_9: {scr_set_layer_slopes(); break;}
                case ll_slope_10: {scr_set_layer_slopes(); break;}
                case ll_slope_11: {scr_set_layer_slopes(); break;}
                case ll_slope_12: {scr_set_layer_slopes(); break;}
                case ll_slope_13: {scr_set_layer_slopes(); break;}
                case ll_slope_14: {scr_set_layer_slopes(); break;}
                case ll_slope_15: {scr_set_layer_slopes(); break;}
                case ll_slope_16: {scr_set_layer_slopes(); break;}
                case ll_slope_17: {scr_set_layer_slopes(); break;}
                case ll_slope_18: {scr_set_layer_slopes(); break;}
                case ll_slope_19: {scr_set_layer_slopes(); break;}
                case ll_slope_20: {scr_set_layer_slopes(); break;}
                case ll_slope_21: {scr_set_layer_slopes(); break;}
                case ll_slope_22: {scr_set_layer_slopes(); break;}
                case ll_slope_23: {scr_set_layer_slopes(); break;}
                case ll_slope_24: {scr_set_layer_slopes(); break;}
                case ll_slope_25: {scr_set_layer_slopes(); break;}
                case ll_slope_26: {scr_set_layer_slopes(); break;}
                case ll_slope_27: {scr_set_layer_slopes(); break;}
                case ll_slope_28: {scr_set_layer_slopes(); break;}
                case ll_slope_29: {scr_set_layer_slopes(); break;}
                case ll_slope_30: {scr_set_layer_slopes(); break;}
                case ll_slope_31: {scr_set_layer_slopes(); break;}
                case ll_slope_32: {scr_set_layer_slopes(); break;}
                case ll_slope_33: {scr_set_layer_slopes(); break;}
                case ll_slope_34: {scr_set_layer_slopes(); break;}
                case ll_slope_35: {scr_set_layer_slopes(); break;}
                case ll_slope_36: {scr_set_layer_slopes(); break;}
                case ll_slope_37: {scr_set_layer_slopes(); break;}
                case ll_slope_38: {scr_set_layer_slopes(); break;}
                case ll_slope_39: {scr_set_layer_slopes(); break;}
                case ll_slope_40: {scr_set_layer_slopes(); break;}
                case ll_slope_41: {scr_set_layer_slopes(); break;}
                case ll_slope_42: {scr_set_layer_slopes(); break;}
                case ll_slope_43: {scr_set_layer_slopes(); break;}
                case ll_slope_44: {scr_set_layer_slopes(); break;}
                case ll_slope_47: {scr_set_layer_slopes(); break;}
                case ll_slope_48: {scr_set_layer_slopes(); break;}
                case ll_donut_2: {scr_set_layer_slopes(); break;}
                case ll_donut_3: {scr_set_layer_slopes(); break;}
                case ll_donut_4: {scr_set_layer_slopes(); break;}
                case ll_donut_5: {scr_set_layer_slopes(); break;}
                case ll_donut_6: {scr_set_layer_slopes(); break;}
                case ll_donut_7: {scr_set_layer_slopes(); break;}
                case ll_donut_8: {scr_set_layer_slopes(); break;}
                case ll_donut_9: {scr_set_layer_slopes(); break;}
                //FOFs
                case ll_fof_0: {scr_set_layer_slopes(); break;}
                case ll_fof_1: {scr_set_layer_slopes(); break;}
                case ll_fof_2: {scr_set_layer_slopes(); break;}
                case ll_fof_3: {scr_set_layer_slopes(); break;}
                case ll_fof_4: {scr_set_layer_slopes(); break;}
                case ll_fof_7: {scr_set_layer_slopes(); break;}
                case ll_fof_8: {scr_set_layer_slopes(); break;}
                //Spikes
                case spr_spikes_14: {scr_set_layer_flats(); break;}
                case spr_spikes_15: {scr_set_layer_flats(); break;}
                case spr_spikes_16: {scr_set_layer_flats(); break;}
                case spr_spikes_17: {scr_set_layer_flats(); break;}
                //Loops
                case ll_loop_2: {scr_set_layer_slopes(); break;}
                case ll_loop_3: {scr_set_layer_slopes(); break;}
                case ll_loop_4: {scr_set_layer_slopes(); break;}
                case ll_loop_5: {scr_set_layer_slopes(); break;}
                case ll_loop_6: {scr_set_layer_slopes(); break;}
                case ll_loop_7: {scr_set_layer_slopes(); break;}
                case ll_loop_8: {scr_set_layer_slopes(); break;}
                case ll_loop_9: {scr_set_layer_slopes(); break;}
                //Scenery
                case ll_scene_0: {scr_set_layer_scene(); break;}
                case ll_scene_1: {scr_set_layer_scene(); break;}
                case ll_scene_2: {scr_set_layer_scene(); break;}
                case ll_scene_3: {scr_set_layer_scene(); break;}
                case ll_scene_4: {scr_set_layer_scene(); break;}
                case ll_scene_5: {scr_set_layer_scene(); break;}
                case ll_scene_6: {scr_set_layer_scene(); break;}
                case ll_scene_7: {scr_set_layer_scene(); break;}
                case ll_scene_8: {scr_set_layer_scene(); break;}
                case ll_scene_9: {scr_set_layer_scene(); break;}
                case ll_scene_10: {scr_set_layer_scene(); break;}
                case ll_scene_11: {scr_set_layer_scene(); break;}
                case ll_scene_12: {scr_set_layer_scene(); break;}
                case ll_scene_13: {scr_set_layer_scene(); break;}
                case ll_scene_14: {scr_set_layer_scene(); break;}
                case ll_scene_15: {scr_set_layer_scene(); break;}
                case ll_scene_16: {scr_set_layer_scene(); break;}
                case ll_scene_17: {scr_set_layer_scene(); break;}
                case ll_scene_18: {scr_set_layer_scene(); break;}
                case ll_scene_19: {scr_set_layer_scene(); break;}
                case ll_scene_20: {scr_set_layer_scene(); break;}
                case ll_scene_21: {scr_set_layer_scene(); break;}
                case ll_scene_22: {scr_set_layer_scene(); break;}
                case ll_scene_23: {scr_set_layer_scene(); break;}
                case ll_scene_24: {scr_set_layer_scene(); break;}
                case ll_scene_25: {scr_set_layer_scene(); break;}
                case ll_scene_26: {scr_set_layer_scene(); break;}
                case ll_scene_27: {scr_set_layer_scene(); break;}
                case ll_scene_28: {scr_set_layer_scene(); break;}
                case ll_scene_29: {scr_set_layer_scene(); break;}
                case ll_scene_30: {scr_set_layer_scene(); break;}
                case ll_scene_31: {scr_set_layer_scene(); break;}
                case ll_scene_32: {scr_set_layer_scene(); break;}
                case ll_scene_33: {scr_set_layer_scene(); break;}
                case ll_scene_34: {scr_set_layer_scene(); break;}
                case ll_scene_35: {scr_set_layer_scene(); break;}
                case ll_scene_36: {scr_set_layer_scene(); break;}
                case ll_scene_37: {scr_set_layer_scene(); break;}
                case ll_scene_38: {scr_set_layer_scene(); break;}
                case ll_scene_39: {scr_set_layer_scene(); break;}
                case ll_scene_40: {scr_set_layer_scene(); break;}
                case ll_scene_41: {scr_set_layer_scene(); break;}
                case ll_scene_42: {scr_set_layer_scene(); break;}
                case ll_scene_43: {scr_set_layer_scene(); break;}
                case ll_scene_44: {scr_set_layer_scene(); break;}
                case ll_scene_45: {scr_set_layer_scene(); break;}
                case ll_scene_46: {scr_set_layer_scene(); break;}
                case ll_scene_47: {scr_set_layer_scene(); break;}
                case ll_scene_48: {scr_set_layer_scene(); break;}
                case ll_scene_49: {scr_set_layer_scene(); break;}
                case ll_scene_50: {scr_set_layer_scene(); break;}
                case ll_scene_51: {scr_set_layer_scene(); break;}
                case ll_scene_52: {scr_set_layer_scene(); break;}
                case ll_scene_53: {scr_set_layer_scene(); break;}
                case ll_scene_54: {scr_set_layer_scene(); break;}
                case ll_scene_55: {scr_set_layer_scene(); break;}
                case ll_scene_56: {scr_set_layer_scene(); break;}
                case ll_scene_57: {scr_set_layer_scene(); break;}
                case ll_scene_58: {scr_set_layer_scene(); break;}
                case ll_scene_59: {scr_set_layer_scene(); break;}
                case ll_scene_60: {scr_set_layer_scene(); break;}
                //Flat Surface Tiles
                case bb_flat_0:   {scr_set_layer_flats(); break;}
                case bb_flat_1:   {scr_set_layer_flats(); break;}
                case bb_flat_2:   {scr_set_layer_flats(); break;}
                case bb_flat_3:   {scr_set_layer_flats(); break;}
                case bb_flat_4:   {scr_set_layer_flats(); break;}
                case bb_flat_5:   {scr_set_layer_flats(); break;}
                case bb_flat_6:   {scr_set_layer_flats(); break;}
                case bb_flat_7:   {scr_set_layer_flats(); break;}
                case bb_flat_8:   {scr_set_layer_flats(); break;}
                case bb_flat_9:   {scr_set_layer_flats(); break;}
                case bb_flat_10:  {scr_set_layer_flats(); break;}
                case bb_flat_11:  {scr_set_layer_flats(); break;}
                case bb_flat_12:  {scr_set_layer_flats(); break;}
                case bb_flat_13:  {scr_set_layer_flats(); break;}
                case bb_flat_14:  {scr_set_layer_flats(); break;}
                case bb_flat_15:  {scr_set_layer_flats(); break;}
                case bb_flat_16:  {scr_set_layer_flats(); break;}
                case bb_flat_17:  {scr_set_layer_flats(); break;}
                case bb_flat_18:  {scr_set_layer_flats(); break;}
                case bb_flat_19:  {scr_set_layer_flats(); break;}
                case bb_flat_20:  {scr_set_layer_flats(); break;}
                case bb_flat_21:  {scr_set_layer_flats(); break;}
                case bb_flat_22:  {scr_set_layer_flats(); break;}
                case bb_flat_23:  {scr_set_layer_flats(); break;}
                case bb_flat_24:  {scr_set_layer_flats(); break;}
                case bb_flat_25:  {scr_set_layer_flats(); break;}
                case bb_flat_26:  {scr_set_layer_flats(); break;}
                case bb_flat_27:  {scr_set_layer_flats(); break;}
                case bb_flat_28:  {scr_set_layer_flats(); break;}
                case bb_flat_29:  {scr_set_layer_flats(); break;}
                case bb_flat_30:  {scr_set_layer_flats(); break;}
                case bb_flat_31:  {scr_set_layer_flats(); break;}
                case bb_slope_0:  {scr_set_layer_slopes(); break;}
                case bb_slope_1:  {scr_set_layer_slopes(); break;}
                case bb_slope_2:  {scr_set_layer_slopes(); break;}
                case bb_slope_3:  {scr_set_layer_slopes(); break;}
                case bb_slope_10: {scr_set_layer_slopes(); break;}
                case bb_slope_11: {scr_set_layer_slopes(); break;}
                case bb_slope_12: {scr_set_layer_slopes(); break;}
                case bb_slope_13: {scr_set_layer_slopes(); break;}
                case bb_slope_14: {scr_set_layer_slopes(); break;}
                case bb_slope_15: {scr_set_layer_slopes(); break;}
                case bb_slope_16: {scr_set_layer_slopes(); break;}
                case bb_slope_17: {scr_set_layer_slopes(); break;}
                case bb_donut_2:  {scr_set_layer_slopes(); break;}
                case bb_donut_3:  {scr_set_layer_slopes(); break;}
                case bb_donut_4:  {scr_set_layer_slopes(); break;}
                case bb_donut_5:  {scr_set_layer_slopes(); break;}
                case bb_donut_6:  {scr_set_layer_slopes(); break;}
                case bb_donut_7:  {scr_set_layer_slopes(); break;}
                case bb_donut_8:  {scr_set_layer_slopes(); break;}
                case bb_donut_9:  {scr_set_layer_slopes(); break;}
                case bb_donut_2_alt: {scr_set_layer_slopes(); break;}
                case bb_donut_3_alt: {scr_set_layer_slopes(); break;}
                case bb_donut_4_alt: {scr_set_layer_slopes(); break;}
                case bb_donut_5_alt: {scr_set_layer_slopes(); break;}
                case bb_donut_6_alt: {scr_set_layer_slopes(); break;}
                case bb_donut_7_alt: {scr_set_layer_slopes(); break;}
                case bb_donut_8_alt: {scr_set_layer_slopes(); break;}
                case bb_donut_9_alt: {scr_set_layer_slopes(); break;}
                case bb_fof_0:    {scr_set_layer_slopes(); break;}
                case bb_fof_1:    {scr_set_layer_slopes(); break;}
                case bb_fof_2:    {scr_set_layer_slopes(); break;}
                case bb_fof_3:    {scr_set_layer_slopes(); break;}
                case bb_scene_0:  {scr_set_layer_scene(); break;}
                case bb_scene_1:  {scr_set_layer_scene(); break;}
                case bb_scene_2:  {scr_set_layer_scene(); break;}
                case bb_scene_3:  {scr_set_layer_scene(); break;}
                case bb_scene_4:  {scr_set_layer_scene(); break;}
                case bb_scene_5:  {scr_set_layer_scene(); break;}
                case bb_scene_6:  {scr_set_layer_scene(); break;}
                case bb_scene_7:  {scr_set_layer_scene(); break;}
                case bb_scene_8:  {scr_set_layer_scene(); break;}
                case bb_scene_9:  {scr_set_layer_scene(); break;}
                case bb_scene_10: {scr_set_layer_scene(); break;}
                case bb_scene_11: {scr_set_layer_scene(); break;}
                case bb_scene_12: {scr_set_layer_scene(); break;}
                case bb_scene_13: {scr_set_layer_scene(); break;}
                //Sapphire Jungle
                case sj_flat_0: {scr_set_layer_flats(); break;}
                case sj_flat_1: {scr_set_layer_flats(); break;}
                case sj_flat_2: {scr_set_layer_flats(); break;}
                case sj_flat_3: {scr_set_layer_flats(); break;}
                case sj_flat_4: {scr_set_layer_flats(); break;}
                case sj_flat_5: {scr_set_layer_flats(); break;}
                case sj_flat_6: {scr_set_layer_flats(); break;}
                case sj_flat_7: {scr_set_layer_flats(); break;}
                case sj_flat_8: {scr_set_layer_flats(); break;}
                case sj_flat_9: {scr_set_layer_flats(); break;}
                case sj_flat_10: {scr_set_layer_flats(); break;}
                case sj_flat_11: {scr_set_layer_flats(); break;}
                case sj_flat_12: {scr_set_layer_flats(); break;}
                case sj_flat_13: {scr_set_layer_flats(); break;}
                case sj_flat_14: {scr_set_layer_flats(); break;}
                case sj_flat_15: {scr_set_layer_flats(); break;}
                case sj_flat_16: {scr_set_layer_flats(); break;}
                case sj_flat_17: {scr_set_layer_flats(); break;}
                case sj_flat_18: {scr_set_layer_flats(); break;}
                case sj_flat_19: {scr_set_layer_flats(); break;}
                case sj_flat_20: {scr_set_layer_flats(); break;}
                case sj_flat_21: {scr_set_layer_flats(); break;}
                case sj_flat_22: {scr_set_layer_flats(); break;}
                case sj_flat_23: {scr_set_layer_flats(); break;}
                case sj_flat_24: {scr_set_layer_flats(); break;}
                case sj_flat_25: {scr_set_layer_flats(); break;}
                case sj_flat_26: {scr_set_layer_flats(); break;}
                case sj_flat_27: {scr_set_layer_flats(); break;}
                case sj_flat_28: {scr_set_layer_flats(); break;}
                case sj_flat_29: {scr_set_layer_flats(); break;}
                case sj_flat_30: {scr_set_layer_flats(); break;}
                case sj_flat_31: {scr_set_layer_flats(); break;}
                case sj_flat_32: {scr_set_layer_flats(); break;}
                case sj_flat_33: {scr_set_layer_flats(); break;}
                case sj_flat_34: {scr_set_layer_flats(); break;}
                case sj_flat_35: {scr_set_layer_flats(); break;}
                case sj_flat_36: {scr_set_layer_flats(); break;}
                case sj_flat_37: {scr_set_layer_flats(); break;}
                case sj_flat_38: {scr_set_layer_flats(); break;}
                case sj_flat_39: {scr_set_layer_flats(); break;}
                case sj_flat_40: {scr_set_layer_flats(); break;}
                case sj_flat_41: {scr_set_layer_flats(); break;}
                case sj_flat_42: {scr_set_layer_flats(); break;}
                case sj_flat_43: {scr_set_layer_flats(); break;}
                case sj_flat_44: {scr_set_layer_flats(); break;}
                case sj_flat_45: {scr_set_layer_flats(); break;}
                case sj_flat_46: {scr_set_layer_flats(); break;}
                case sj_flat_47: {scr_set_layer_flats(); break;}
                case sj_flat_48: {scr_set_layer_flats(); break;}
                case sj_flat_49: {scr_set_layer_flats(); break;}
                case sj_flat_50: {scr_set_layer_flats(); break;}
                case sj_slope_2: {scr_set_layer_slopes(); break;}
                case sj_slope_3: {scr_set_layer_slopes(); break;}
                case sj_slope_4: {scr_set_layer_slopes(); break;}
                case sj_slope_5: {scr_set_layer_slopes(); break;}
                case sj_slope_6: {scr_set_layer_slopes(); break;}
                case sj_slope_7: {scr_set_layer_slopes(); break;}
                case sj_slope_8: {scr_set_layer_slopes(); break;}
                case sj_slope_9: {scr_set_layer_slopes(); break;}
                case sj_donut_2: {scr_set_layer_slopes(); break;}
                case sj_donut_3: {scr_set_layer_slopes(); break;}
                case sj_donut_4: {scr_set_layer_slopes(); break;}
                case sj_donut_5: {scr_set_layer_slopes(); break;}
                case sj_donut_6: {scr_set_layer_slopes(); break;}
                case sj_donut_7: {scr_set_layer_slopes(); break;}
                case sj_donut_8: {scr_set_layer_slopes(); break;}
                case sj_donut_9: {scr_set_layer_slopes(); break;}
                case sj_slope_10: {scr_set_layer_slopes(); break;}
                case sj_ramp_4:   {scr_set_layer_slopes(); break;}
                case sj_ramp_5:   {scr_set_layer_slopes(); break;}
                case sj_ramp_16:  {scr_set_layer_slopes(); break;}
                case sj_ramp_17:  {scr_set_layer_slopes(); break;}
                case sj_slope_11: {scr_set_layer_slopes(); break;}
                case sj_slope_12: {scr_set_layer_slopes(); break;}
                case sj_slope_13: {scr_set_layer_slopes(); break;}
                case sj_slope_14: {scr_set_layer_slopes(); break;}
                case sj_slope_15: {scr_set_layer_slopes(); break;}
                case sj_slope_16: {scr_set_layer_slopes(); break;}
                case sj_slope_17: {scr_set_layer_slopes(); break;}
                case sj_slope_10_alt: {scr_set_layer_slopes(); break;}
                case sj_slope_11_alt: {scr_set_layer_slopes(); break;}
                case sj_slope_12_alt: {scr_set_layer_slopes(); break;}
                case sj_slope_13_alt: {scr_set_layer_slopes(); break;}
                case sj_slope_14_alt: {scr_set_layer_slopes(); break;}
                case sj_slope_15_alt: {scr_set_layer_slopes(); break;}
                case sj_slope_16_alt: {scr_set_layer_slopes(); break;}
                case sj_slope_17_alt: {scr_set_layer_slopes(); break;}
                case sj_fof_0: {scr_set_layer_slopes(); break;}
                case sj_scene_0: {scr_set_layer_scene(); break;}
                case sj_scene_1: {scr_set_layer_scene(); break;}
                case sj_scene_2: {scr_set_layer_scene(); break;}
                case sj_scene_3: {scr_set_layer_scene(); break;}
                case sj_scene_4: {scr_set_layer_scene(); break;}
                case sj_scene_5: {scr_set_layer_scene(); break;}
                case sj_scene_6: {scr_set_layer_scene(); break;}
                case sj_scene_7: {scr_set_layer_scene(); break;}
                case sj_scene_8: {scr_set_layer_scene(); break;}
                case sj_scene_9: {scr_set_layer_scene(); break;}
                case sj_scene_10: {scr_set_layer_scene(); break;}
                case sj_scene_11: {scr_set_layer_scene(); break;}
                case sj_scene_12: {scr_set_layer_scene(); break;}
                case sj_scene_13: {scr_set_layer_scene(); break;}
                case sj_scene_14: {scr_set_layer_scene(); break;}
                case sj_scene_15: {scr_set_layer_scene(); break;}                
                //Camera Tiles
                case cm_camera_100: {scr_set_layer_scene(); break;}
                case cm_camera_50:  {scr_set_layer_scene(); break;}
                case cm_camera_25:  {scr_set_layer_scene(); break;}
                //Set decided layer if it is not a registered tile
                default: {o.user_layer_selected = 0; o.user_layer_iteration = 0; break;}
            }
    }
