obj_game_logic.lilac_cyclone_ceiling_check  = 0   //Have we touched a ceiling during the cyclone attack?
obj_game_logic.lilac_cyclone_ground_check   = 0   //Have we touched the ground and performed a ground cyclone?
obj_game_logic.lilac_cyclone_refresh        = 0   //Are we allowed to perform another cyclone in mid-air?
obj_game_logic.lilac_divekick_speed_check   = 0   //Have we applied 7px/s of momentum at least once?
obj_game_logic.lilac_stamina_count          = 100 //How much stamina do we have before performing the cyclone attack?
obj_game_logic.lilac_stamina_drain          = 100 //How much stamina have we drained during the cyclone attack?
obj_game_logic.lilac_stamina_hop            = 0   //How high can we hop up during a cyclone attack?
obj_game_logic.lilac_stamina_hop_mod        = 0   //Slowly drain the vertical speed of the cyclone attack's hop in mid-air
obj_game_logic.lilac_dragon_boost_lock      = 0   //Lock the angle of the dragon boost
obj_game_logic.lilac_dragon_boost_angle     = 0   //Angle of the dragon boost attack
obj_game_logic.lilac_dragon_boost_dir       = 1   //Direction of the dragon boost
obj_game_logic.lilac_dragon_boost_taper     = 0   //Is the dragon boost allowed to taper after it ends?
obj_game_logic.lilac_dragon_boost_taper_mod = 0   //Is the dragon boost allowed to taper after it ends?
obj_game_logic.lilac_dragon_boost_timer     = 30  //How long before we enter the second phase of the dragon boost?
obj_game_logic.lilac_dragon_boost_visible   = -1  //How long should the dragon boost particles be visible?
obj_game_logic.lilac_dragon_boost_offset    = 0   //Y Offset For The Dragon Boost Sprites
obj_game_logic.lilac_uppercut_ceiling       = 0   //Are we touching the ceiling during the uppercut attack?
obj_game_logic.lilac_tail_frame             = 0   //What frame of animation for Lilac's tail are we?
obj_game_logic.lilac_tail_frame_2           = 0   //What frame of animation for Lilac's tail are we?
obj_game_logic.lilac_direction_lock         = 0   //Which direction are we performing an attack?
obj_game_logic.lilac_tail_frame_1           = 0   //Current frame of the tail's sprite
obj_game_logic.lilac_cyclone_sprite_frame   = 0   //Current frame of the cyclone's sprite
obj_game_logic.lilac_cyclone_x              = 0   //X position of the cyclone's sprite
obj_game_logic.lilac_cyclone_y              = 0   //Y position of the cyclone's sprite
obj_game_logic.lilac_cyclone_decay          = 0   //Rate at which the cyclone's animation speed slows down
obj_game_logic.lilac_cyclone_jump_timer     = 0   //Jump timer for the cyclone jump (Flat surface)
obj_game_logic.lilac_uppercut_sound_check   = 0   //Check if we're allowed to play the second half of the uppercut sound effect
obj_game_logic.lilac_uppercut_anim_frame    = 0   //Animation frames for the uppercut slash's sprites
obj_game_logic.lilac_uppercut_x             = 0   //X position of the uppercut slash's sprite
obj_game_logic.lilac_uppercut_y             = 0   //Y position of the uppercut slash's sprite
obj_game_logic.lilac_animation_speed_mod    = 0   //Modify animation speed based on horizontal speed
obj_game_logic.lilac_jump_press             = 0   //Have we pressed the jump key once?
obj_game_logic.lilac_glitch_jump            = 0   //Are we performing a glitch jump?
obj_game_logic.lilac_glitch_jump_timer      = 0   //Timer window for performing the glitch jump
obj_game_logic.lilac_uppercut_gravity       = 0   //Gravity speed for the uppercut attack
obj_game_logic.lilac_uppercut_glitch_height = 0   //Gravity speed for the uppercut attack
obj_game_logic.lilac_hang_bar_jump          = 0   //Timer for hang bar locking
obj_game_logic.lilac_boost_speed            = 0   //Lilac's Dragon Boosting Speed
obj_game_logic.lilac_boost_sprite           = 0   //Lilac's Dragon Boost Drawn Sprite 0 = Disabled; 1 = Enabled
obj_game_logic.lilac_boost_cancel           = 0   //Lilac's Dragon Boost Cancel
obj_game_logic.lilac_boost_cancel_stamina   = 0   //Lilac's Dragon Boost Cancel Stamina
obj_game_logic.lilac_boost_frame            = 0
obj_game_logic.lilac_boost_launch           = 0   //Can we launch Lilac upwards from a 90 degree sloped surface?
obj_game_logic.lilac_boost_dir              = 0
obj_game_logic.lilac_boost_clip             = 0
obj_game_logic.lilac_boost_fling_dir        = 0
obj_game_logic.lilac_boost_fling_timer      = 0
obj_game_logic.lilac_boost_flight_controls  = 0
obj_game_logic.lilac_sprite_offset_x        = 0   //Lilac's X Offsets
obj_game_logic.lilac_sprite_offset_y        = 0   //Lilac's Y Offsets
obj_game_logic.lilac_tail_offset_x        = 0   //Lilac's X Offsets
obj_game_logic.lilac_tail_offset_y        = 0   //Lilac's Y Offsets
obj_game_logic.fof_disable                  = 0   //Disable FOF collisions
obj_game_logic.sit = 0
obj_game_logic.sit_timer = 0
obj_game_logic.push_timer = 0
