///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Platforms"
o.display_page_description[1] = "Beams"
o.display_page_description[2] = "Slopes"
o.display_page_description[3] = "Scenery 1"
o.display_page_description[4] = "Scenery 2"
o.display_page_description[5] = "Scenery 3"
o.display_page_description[6] = "Scenery 4"
o.display_page_description[7] = "Scenery 5"
o.display_page_description[8] = "Scraps"
o.display_page_description[9] = "Extras 1"
o.display_page_description[10] = "Extras 2"
o.display_page_description[11] = "Alt Bricks"
o.display_page_description[12] = "Extras 3"
o.display_page_description[13] = "Extras 4"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Brick Platform 1"
o.display_description_item[o.display_page_one,1] = "Brick Platform 2"
o.display_description_item[o.display_page_one,2] = "Brick Wall 1"
o.display_description_item[o.display_page_one,3] = "Brick Wall 2"
o.display_description_item[o.display_page_one,4] = "Brick Wall 3"
o.display_description_item[o.display_page_one,5] = "Brick Wall 4"
o.display_description_item[o.display_page_one,6] = "Brick Block 1"
o.display_description_item[o.display_page_one,7] = "Brick Block 2"
o.display_description_item[o.display_page_one,8] = "Brick Block 3"
o.display_description_item[o.display_page_one,9] = "Red Brick"
o.display_description_item[o.display_page_one,10] = "Blue Brick"
o.display_description_item[o.display_page_one,11] = "Wall Divider 1"
o.display_description_item[o.display_page_one,12] = "Wall Divider 2"
o.display_description_item[o.display_page_one,13] = "Pipe Flat 1"
o.display_description_item[o.display_page_one,14] = "Pipe Flat 2"
o.display_description_item[o.display_page_one,15] = "Pipe Flat 3"
o.display_description_item[o.display_page_one,16] = "Pipe Flat 4"
o.display_description_item[o.display_page_one,17] = "Pipe End Piece 1"
o.display_description_item[o.display_page_one,18] = "Pipe End Piece 2"
o.display_description_item[o.display_page_one,19] = "Pipe End Piece 3"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Construction Beam - Red 1"
o.display_description_item[o.display_page_two,1] = "Construction Beam - Red 2"
o.display_description_item[o.display_page_two,2] = "Construction Beam - Yellow 1"
o.display_description_item[o.display_page_two,3] = "Construction Beam - Yellow 2"
o.display_description_item[o.display_page_two,4] = "Construction Beam - Red 3"
o.display_description_item[o.display_page_two,5] = "Construction Beam - Red 4"
o.display_description_item[o.display_page_two,6] = "Construction Beam - Yellow 3"
o.display_description_item[o.display_page_two,7] = "Support Beam - Yellow 1"
o.display_description_item[o.display_page_two,8] = "Support Beam - Yellow 2"
o.display_description_item[o.display_page_two,9] = "Support Beam - Red 1"
o.display_description_item[o.display_page_two,10] = "Support Beam - Red 2"
o.display_description_item[o.display_page_two,11] = "Support Beam - Red 3"
o.display_description_item[o.display_page_two,12] = "Support Beam - Yellow 3"
o.display_description_item[o.display_page_two,13] = "Concrete Wall - 1"
o.display_description_item[o.display_page_two,14] = "Concrete Wall - 2"
o.display_description_item[o.display_page_two,15] = "Sidewalk - 1"
o.display_description_item[o.display_page_two,16] = "Sidewalk - 2"
o.display_description_item[o.display_page_two,17] = "Sidewalk - 3"
o.display_description_item[o.display_page_two,18] = "Sidewalk - 4"
o.display_description_item[o.display_page_two,19] = "Construction Beam - Yellow 3"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Quarter Pipe Beam 1"
o.display_description_item[o.display_page_three,1] = "Quarter Pipe Beam 2"
o.display_description_item[o.display_page_three,2] = "Quarter Pipe Beam 3"
o.display_description_item[o.display_page_three,3] = "Quarter Pipe Beam 4"
o.display_description_item[o.display_page_three,4] = "Quarter Pipe Beam 1 - Inverted"
o.display_description_item[o.display_page_three,5] = "Quarter Pipe Beam 2 - Inverted"
o.display_description_item[o.display_page_three,6] = "Floating Platform 1"
o.display_description_item[o.display_page_three,7] = "Loop-De-Loop Piece 1"
o.display_description_item[o.display_page_three,8] = "Loop-De-Loop Piece 2"
o.display_description_item[o.display_page_three,9] = "Loop-De-Loop Piece 3"
o.display_description_item[o.display_page_three,10] = "Loop-De-Loop Piece 4"
o.display_description_item[o.display_page_three,11] = "Quarter Pipe Beam 3 - Inverted"
o.display_description_item[o.display_page_three,12] = "Quarter Pipe Beam 4 - Inverted"
o.display_description_item[o.display_page_three,13] = "Road Hill 1"
o.display_description_item[o.display_page_three,14] = "Road Hill 2"
o.display_description_item[o.display_page_three,15] = "Road Hill 3"
o.display_description_item[o.display_page_three,16] = "Road Hill 4"
o.display_description_item[o.display_page_three,17] = "Road Slope - Left"
o.display_description_item[o.display_page_three,18] = "Road Slope - Right"
o.display_description_item[o.display_page_three,19] = "Floating Platform 2"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Glass Window - Large"
o.display_description_item[o.display_page_four,1] = "Glass Window - Small 1"
o.display_description_item[o.display_page_four,2] = "Glass Window - Small 2"
o.display_description_item[o.display_page_four,3] = "Air Conditioning Unit 1"
o.display_description_item[o.display_page_four,4] = "Air Conditioning Unit 2"
o.display_description_item[o.display_page_four,5] = "Reflector Telescope"
o.display_description_item[o.display_page_four,6] = "Refractor Telescope"
o.display_description_item[o.display_page_four,7] = "Scenery - Pipe - Vertical Connector"
o.display_description_item[o.display_page_four,8] = "Scenery - Pipe - Horizontal Connector"
o.display_description_item[o.display_page_four,9] = "Scenery - Pipe - Top"
o.display_description_item[o.display_page_four,10] = "Scenery - Pipe - Bottom"
o.display_description_item[o.display_page_four,11] = "Utility Pole Cap"
o.display_description_item[o.display_page_four,12] = "Utility Pole"
o.display_description_item[o.display_page_four,13] = "Umbrella"
o.display_description_item[o.display_page_four,14] = "Ziyo's Ice Comets Logo"
o.display_description_item[o.display_page_four,15] = "Ice Cream Float 1"
o.display_description_item[o.display_page_four,16] = "Ice Cream Float 2"
o.display_description_item[o.display_page_four,17] = "Ice Cream Float 3"
o.display_description_item[o.display_page_four,18] = "Ice Cream Bowl"
o.display_description_item[o.display_page_four,19] = "Banana Split"

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Scenery - Support Beam 1"
o.display_description_item[o.display_page_five,1] = "Scenery - Rail Guard"
o.display_description_item[o.display_page_five,2] = "Scenery - Sidewalk"
o.display_description_item[o.display_page_five,3] = "Scenery - Road"
o.display_description_item[o.display_page_five,4] = "Scenery - Window Frame"
o.display_description_item[o.display_page_five,5] = "Scenery - Billboard 1"
o.display_description_item[o.display_page_five,6] = "Scenery - Billboard 2"
o.display_description_item[o.display_page_five,7] = "Scenery - Brick Wall 1"
o.display_description_item[o.display_page_five,8] = "Scenery - Brick Wall 2"
o.display_description_item[o.display_page_five,9] = "Scenery - Brick Wall 3"
o.display_description_item[o.display_page_five,10] = "Scenery - Building 1"
o.display_description_item[o.display_page_five,11] = "Scenery - Building 2"
o.display_description_item[o.display_page_five,12] = "Scenery - Water Tower"
o.display_description_item[o.display_page_five,13] = "Scenery - Starbuster Poster"
o.display_description_item[o.display_page_five,14] = "Scenery - HavocFox Poster"
o.display_description_item[o.display_page_five,15] = "Scenery - Advertisement 1"
o.display_description_item[o.display_page_five,16] = "Scenery - Advertisement 2"
o.display_description_item[o.display_page_five,17] = "Scenery - Stop Sign"
o.display_description_item[o.display_page_five,18] = "Scenery - Yield Sign"
o.display_description_item[o.display_page_five,19] = "Scenery - Ninja Crossing"

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Recycle Bin"
o.display_description_item[o.display_page_six,1] = "Recycling Dumpster"
o.display_description_item[o.display_page_six,2] = "East Road Street Sign"
o.display_description_item[o.display_page_six,3] = "North Circle Street Sign"
o.display_description_item[o.display_page_six,4] = "South Drive Street Sign"
o.display_description_item[o.display_page_six,5] = "West Lane Street Sign"
o.display_description_item[o.display_page_six,6] = "Blank Street Sign"
o.display_description_item[o.display_page_six,7] = "Arrow Sign"
o.display_description_item[o.display_page_six,8] = "Wet Floor Sign"
o.display_description_item[o.display_page_six,9] = "Traffic Lights"
o.display_description_item[o.display_page_six,10] = "Lamp Post"
o.display_description_item[o.display_page_six,11] = "Lamp Pole 1"
o.display_description_item[o.display_page_six,12] = "Lamp Pole 2"
o.display_description_item[o.display_page_six,13] = "Lamp Pole 3"
o.display_description_item[o.display_page_six,14] = "Bush"
o.display_description_item[o.display_page_six,15] = "One Of A Kind Eggplant"
o.display_description_item[o.display_page_six,16] = "Clothes Line"
o.display_description_item[o.display_page_six,17] = "Pedestrian Crossing Sign"
o.display_description_item[o.display_page_six,18] = "Pedestrian Signal"
o.display_description_item[o.display_page_six,19] = "Trash Can"

//Tile Descriptions (Page 7)
o.display_description_item[o.display_page_seven,0] = "Yellow Support Beam - Complete 1"
o.display_description_item[o.display_page_seven,1] = "Yellow Support Beam - Angled 1"
o.display_description_item[o.display_page_seven,2] = "Yellow Support Beam - Angled 2"
o.display_description_item[o.display_page_seven,3] = "Red Support Beam - Angled 1"
o.display_description_item[o.display_page_seven,4] = "Red Support Beam - Angled 2"
o.display_description_item[o.display_page_seven,5] = "Support Beam - Red 3"
o.display_description_item[o.display_page_seven,6] = "Yellow Support Beam - Complete 2"
o.display_description_item[o.display_page_seven,7] = "Yellow Support Beam - Piece 1"
o.display_description_item[o.display_page_seven,8] = "Yellow Support Beam - Piece 2"
o.display_description_item[o.display_page_seven,9] = "Yellow Support Beam - Piece 3"
o.display_description_item[o.display_page_seven,10] = "Yellow Support Beam - Piece 4"
o.display_description_item[o.display_page_seven,11] = "Yellow Support Beam - Piece 5"
o.display_description_item[o.display_page_seven,12] = "Yellow Support Beam - Piece 6"
o.display_description_item[o.display_page_seven,13] = "Construction Support Beam - Sideways"
o.display_description_item[o.display_page_seven,14] = "Traffic Cone - Large"
o.display_description_item[o.display_page_seven,15] = "Traffic Cone - Small"
o.display_description_item[o.display_page_seven,16] = "Traffic Cone - 1"
o.display_description_item[o.display_page_seven,17] = "Traffic Cone - 2"
o.display_description_item[o.display_page_seven,18] = "Traffic Cone - 3"
o.display_description_item[o.display_page_seven,19] = "Traffic Cone - 4"

//Tile Descriptions (Page 8)
o.display_description_item[o.display_page_eight,0] = "Scenery - Pipe - Top"
o.display_description_item[o.display_page_eight,1] = "Scenery - Pipe - Vertical Connector"
o.display_description_item[o.display_page_eight,2] = "Scenery - Pipe - Bottom"
o.display_description_item[o.display_page_eight,3] = "Scenery - Pipe - Horizontal Connector"
o.display_description_item[o.display_page_eight,4] = "Restaurant Table"
o.display_description_item[o.display_page_eight,5] = "Large Shelf"
o.display_description_item[o.display_page_eight,6] = "Horizontal Pipe"
o.display_description_item[o.display_page_eight,7] = "Construction Beam - Medium 1"
o.display_description_item[o.display_page_eight,8] = "Construction Beam - Medium 2"
o.display_description_item[o.display_page_eight,9] = "Construction Beam - Medium 3"
o.display_description_item[o.display_page_eight,10] = "Construction Beam - Medium 4"
o.display_description_item[o.display_page_eight,11] = "Scenery - Picket Fence"
o.display_description_item[o.display_page_eight,12] = "Construction Support Beam - Small"
o.display_description_item[o.display_page_eight,13] = "Metal Spikes - 1"
o.display_description_item[o.display_page_eight,14] = "Metal Spikes - 2"
o.display_description_item[o.display_page_eight,15] = "Metal Spikes - 3"
o.display_description_item[o.display_page_eight,16] = "Metal Spikes - 4"
o.display_description_item[o.display_page_eight,17] = "Ladder 1"
o.display_description_item[o.display_page_eight,18] = "Ladder 2"
o.display_description_item[o.display_page_eight,19] = "Hangbar 1"

//Tile Descriptions (Page 9)
o.display_description_item[o.display_page_nine,0] = "Brick Platform - Scrapped 1"
o.display_description_item[o.display_page_nine,1] = "Brick Platform - Scrapped 2"
o.display_description_item[o.display_page_nine,2] = "Brick Wall - Scrapped 1"
o.display_description_item[o.display_page_nine,3] = "Brick Wall - Scrapped 2"
o.display_description_item[o.display_page_nine,4] = "Brick Wall - Scrapped 3"
o.display_description_item[o.display_page_nine,5] = "Brick Platform - Scrapped 3"
o.display_description_item[o.display_page_nine,6] = "Brick Wall - Scrapped 4"
o.display_description_item[o.display_page_nine,7] = "Brick Wall - Scrapped 5"
o.display_description_item[o.display_page_nine,8] = "Sidewalk - Scrapped 1"
o.display_description_item[o.display_page_nine,9] = "Brick Wall - Scrapped 6"
o.display_description_item[o.display_page_nine,10] = "Brick Wall - Scrapped 7"
o.display_description_item[o.display_page_nine,11] = "Blank Billboard - Scrapped 1"
o.display_description_item[o.display_page_nine,12] = "Blank Billboard - Scrapped 2"
o.display_description_item[o.display_page_nine,13] = "Blank Billboard - Scrapped 3"
o.display_description_item[o.display_page_nine,14] = "Pipe - Scrapped 1"
o.display_description_item[o.display_page_nine,15] = "Pipe - Scrapped 2"
o.display_description_item[o.display_page_nine,16] = "Pipe - Scrapped 3"
o.display_description_item[o.display_page_nine,17] = "Pipe - Scrapped 4"
o.display_description_item[o.display_page_nine,18] = "Unknown Tile"
o.display_description_item[o.display_page_nine,19] = "Unknown Tile"

//Tile Descriptions (Page 10)
o.display_description_item[o.display_page_ten,0] = "Brick Wall - Extra 1"
o.display_description_item[o.display_page_ten,1] = "Brick Wall - Extra 2"
o.display_description_item[o.display_page_ten,2] = "Brick Wall - Extra 3"
o.display_description_item[o.display_page_ten,3] = "Brick Wall - Extra 4"
o.display_description_item[o.display_page_ten,4] = "Brick Wall - Extra 5"
o.display_description_item[o.display_page_ten,5] = "Brick Wall - Extra 6"
o.display_description_item[o.display_page_ten,6] = "Brick Wall - Extra 7"
o.display_description_item[o.display_page_ten,7] = "Corner Piece 1"
o.display_description_item[o.display_page_ten,8] = "Corner Piece 2"
o.display_description_item[o.display_page_ten,9] = "Corner Piece 3"
o.display_description_item[o.display_page_ten,10] = "Corner Piece 4"
o.display_description_item[o.display_page_ten,11] = "Brick Wall - Extra 8"
o.display_description_item[o.display_page_ten,12] = "Brick Wall - Extra 9"
o.display_description_item[o.display_page_ten,13] = "Corner Piece 5"
o.display_description_item[o.display_page_ten,14] = "Corner Piece 6"
o.display_description_item[o.display_page_ten,15] = "Corner Piece 7"
o.display_description_item[o.display_page_ten,16] = "Brick Platform - Edge Left"
o.display_description_item[o.display_page_ten,17] = "Brick Platform - Mid-Section"
o.display_description_item[o.display_page_ten,18] = "Brick Platform - Edge Right"
o.display_description_item[o.display_page_ten,19] = "Brick Wall - Extra 10"

//Tile Descriptions (Page 11)
o.display_description_item[o.display_page_eleven,0] = "Brick Loop - 1"
o.display_description_item[o.display_page_eleven,1] = "Brick Loop - 2"
o.display_description_item[o.display_page_eleven,2] = "Brick Wall - Extra 3"
o.display_description_item[o.display_page_eleven,3] = "Brick Wall - Extra 4"
o.display_description_item[o.display_page_eleven,4] = "Brick Wall - Extra 5"
o.display_description_item[o.display_page_eleven,5] = "Brick Wall - Extra 6"
o.display_description_item[o.display_page_eleven,6] = "Brick Wall - Extra 7"
o.display_description_item[o.display_page_eleven,7] = "Brick Loop - 3"
o.display_description_item[o.display_page_eleven,8] = "Brick Loop - 4"
o.display_description_item[o.display_page_eleven,9] = "Corner Piece 3"
o.display_description_item[o.display_page_eleven,10] = "Corner Piece 4"
o.display_description_item[o.display_page_eleven,11] = "Brick Wall - Extra 8"
o.display_description_item[o.display_page_eleven,12] = "Brick Wall - Extra 9"
o.display_description_item[o.display_page_eleven,13] = "Corner Piece 5"
o.display_description_item[o.display_page_eleven,14] = "Corner Piece 6"
o.display_description_item[o.display_page_eleven,15] = "Corner Piece 7"
o.display_description_item[o.display_page_eleven,16] = "Brick Platform - Edge Left"
o.display_description_item[o.display_page_eleven,17] = "Brick Platform - Mid-Section"
o.display_description_item[o.display_page_eleven,18] = "Brick Platform - Edge Right"
o.display_description_item[o.display_page_eleven,19] = "Brick Wall - Extra 10"

//Tile Descriptions (Page 12)
o.display_description_item[o.display_page_twelve,0] = "Brick Platform 1"
o.display_description_item[o.display_page_twelve,1] = "Brick Platform 2"
o.display_description_item[o.display_page_twelve,2] = "Brick Wall 1"
o.display_description_item[o.display_page_twelve,3] = "Brick Wall 2"
o.display_description_item[o.display_page_twelve,4] = "Brick Wall 3"
o.display_description_item[o.display_page_twelve,5] = "Brick Wall 4"
o.display_description_item[o.display_page_twelve,6] = "Brick Block 1"
o.display_description_item[o.display_page_twelve,7] = "Brick Block 2"
o.display_description_item[o.display_page_twelve,8] = "Brick Block 3"
o.display_description_item[o.display_page_twelve,9] = "Red Brick"
o.display_description_item[o.display_page_twelve,10] = "Blue Brick"
o.display_description_item[o.display_page_twelve,11] = "Wall Divider 1"
o.display_description_item[o.display_page_twelve,12] = "Wall Divider 2"
o.display_description_item[o.display_page_twelve,13] = "Pipe Flat 1"
o.display_description_item[o.display_page_twelve,14] = "Pipe Flat 2"
o.display_description_item[o.display_page_twelve,15] = "Pipe Flat 3"
o.display_description_item[o.display_page_twelve,16] = "Pipe Flat 4"
o.display_description_item[o.display_page_twelve,17] = "Pipe End Piece 1"
o.display_description_item[o.display_page_twelve,18] = "Pipe End Piece 2"
o.display_description_item[o.display_page_twelve,19] = "Pipe End Piece 3"

//Tile Descriptions (Page 13)
o.display_description_item[o.display_page_thirteen,0] = "Dragon Road Sign"
o.display_description_item[o.display_page_thirteen,1] = "Pheasant Lane Sign"
o.display_description_item[o.display_page_thirteen,2] = "Fantail Road Sign"
o.display_description_item[o.display_page_thirteen,3] = "Panya Plaza Sign"
o.display_description_item[o.display_page_thirteen,4] = "Fuzhu Lane Sign"
o.display_description_item[o.display_page_thirteen,5] = "Qilin Lane Sign"
o.display_description_item[o.display_page_thirteen,6] = "Phoenix Road Sign"
o.display_description_item[o.display_page_thirteen,7] = "Interstate Sign 1"
o.display_description_item[o.display_page_thirteen,8] = "Interstate Sign 2"
o.display_description_item[o.display_page_thirteen,9] = "Interstate Sign Support 1"
o.display_description_item[o.display_page_thirteen,10] = "Interstate Sign Support 2"
o.display_description_item[o.display_page_thirteen,11] = "Interstate Sign Support 3"
o.display_description_item[o.display_page_thirteen,12] = "Interstate Sign Support 4"
o.display_description_item[o.display_page_thirteen,13] = "Dragon Temple - Support Beam"
o.display_description_item[o.display_page_thirteen,14] = "Dragon Temple - Lamp"
o.display_description_item[o.display_page_thirteen,15] = "Dragon Temple - Gate"
o.display_description_item[o.display_page_thirteen,16] = "Dragon Temple - Fence"
o.display_description_item[o.display_page_thirteen,17] = "Dragon Temple - Fence Post"
o.display_description_item[o.display_page_thirteen,18] = "Bamboo Plant"
o.display_description_item[o.display_page_thirteen,19] = "Fuzhu Painting"

//Tile Descriptions (Page 14)
o.display_description_item[o.display_page_fourteen,0] = "Dragon Temple - Dragon Statue"
o.display_description_item[o.display_page_fourteen,1] = "Dragon Temple - Fuzhu Statue"
o.display_description_item[o.display_page_fourteen,2] = "Alt Restaurant Sign - Panya Sushi"
o.display_description_item[o.display_page_fourteen,3] = "Dragon Temple - Dragon Mural"
o.display_description_item[o.display_page_fourteen,4] = "Timmy Tuna's Sushi Bar For Kids - Sign"
o.display_description_item[o.display_page_fourteen,5] = "Closed Sign"
o.display_description_item[o.display_page_fourteen,6] = "Open Sign"
o.display_description_item[o.display_page_fourteen,7] = ""
o.display_description_item[o.display_page_fourteen,8] = ""
o.display_description_item[o.display_page_fourteen,9] = ""
o.display_description_item[o.display_page_fourteen,10] = ""
o.display_description_item[o.display_page_fourteen,11] = ""
o.display_description_item[o.display_page_fourteen,12] = ""
o.display_description_item[o.display_page_fourteen,13] = ""
o.display_description_item[o.display_page_fourteen,14] = ""
o.display_description_item[o.display_page_fourteen,15] = ""
o.display_description_item[o.display_page_fourteen,16] = ""
o.display_description_item[o.display_page_fourteen,17] = ""
o.display_description_item[o.display_page_fourteen,18] = ""
o.display_description_item[o.display_page_fourteen,19] = ""

