///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Escaleras"
o.display_page_description[1] = "Pinchos"
o.display_page_description[2] = "Conjunto de Vidrio"
o.display_page_description[3] = "Rieles 1"
o.display_page_description[4] = "Rieles 2"
o.display_page_description[5] = "Decoración"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Escalera 1"
o.display_description_item[o.display_page_one,1] = "Escalera 2"
o.display_description_item[o.display_page_one,2] = "Escalera 3"
o.display_description_item[o.display_page_one,3] = "Escalera 4"
o.display_description_item[o.display_page_one,4] = "Escalera 5"
o.display_description_item[o.display_page_one,5] = "Escalera 6"
o.display_description_item[o.display_page_one,6] = "Barra Suspendida 1"
o.display_description_item[o.display_page_one,7] = "Barra Suspendida 2"
o.display_description_item[o.display_page_one,8] = "Barra Suspendida 3"
o.display_description_item[o.display_page_one,9] = "Barra Suspendida 4"
o.display_description_item[o.display_page_one,10] = "Barra Suspendida 5"
o.display_description_item[o.display_page_one,11] = "Riel 2"
o.display_description_item[o.display_page_one,12] = "Riel 3"
o.display_description_item[o.display_page_one,13] = "Riel 4"
o.display_description_item[o.display_page_one,14] = "Riel 5"
o.display_description_item[o.display_page_one,15] = "Riel 6"
o.display_description_item[o.display_page_one,16] = "Riel 7"
o.display_description_item[o.display_page_one,17] = "Riel 8"
o.display_description_item[o.display_page_one,18] = "Riel 9"
o.display_description_item[o.display_page_one,19] = "Riel 10"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Pinchos Metalicos 1"
o.display_description_item[o.display_page_two,1] = "Pinchos Metalicos 2"
o.display_description_item[o.display_page_two,2] = "Pinchos Metalicos 3"
o.display_description_item[o.display_page_two,3] = "Pinchos Metalicos 4"
o.display_description_item[o.display_page_two,4] = "Pinchos de Madera 1"
o.display_description_item[o.display_page_two,5] = "Pinchos de Madera 2"
o.display_description_item[o.display_page_two,6] = "Pinchos de Madera 3"
o.display_description_item[o.display_page_two,7] = "Pinchos de Madera 4"
o.display_description_item[o.display_page_two,8] = "Pinchos de Roca 1"
o.display_description_item[o.display_page_two,9] = "Pinchos de Roca 2"
o.display_description_item[o.display_page_two,10] = "Pinchos de Roca 3"
o.display_description_item[o.display_page_two,11] = "Pinchos de Roca 4"
o.display_description_item[o.display_page_two,12] = "Pinchos de Madera 1"
o.display_description_item[o.display_page_two,13] = "Pinchos de Madera 2"
o.display_description_item[o.display_page_two,14] = "Pinchos de Madera 3"
o.display_description_item[o.display_page_two,15] = "Pinchos de Madera 4"
o.display_description_item[o.display_page_two,16] = "Pinchos Serrados 1"
o.display_description_item[o.display_page_two,17] = "Pinchos Serrados 2"
o.display_description_item[o.display_page_two,18] = "Pinchos Serrados 3"
o.display_description_item[o.display_page_two,19] = "Pinchos Serrados 4"

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Vidrio Oscuro - Grande"
o.display_description_item[o.display_page_three,1] = "Vidrio Oscuro - Pequeño"
o.display_description_item[o.display_page_three,2] = "Vidrio Oscuro - Mediano"
o.display_description_item[o.display_page_three,3] = "Vidrio Oscuro - Vertical"
o.display_description_item[o.display_page_three,4] = "Vidrio Oscuro - Delgado"
o.display_description_item[o.display_page_three,5] = "Pieza de Bucle de Vidrio 1"
o.display_description_item[o.display_page_three,6] = "Pieza de Bucle de Vidrio 2"
o.display_description_item[o.display_page_three,7] = "Pieza de Bucle de Vidrio 1"
o.display_description_item[o.display_page_three,8] = "Pieza de Bucle de Vidrio 2"
o.display_description_item[o.display_page_three,9] = "Rampa Larga de Vidrio 1"
o.display_description_item[o.display_page_three,10] = "Rampa Larga de Vidrio 2"
o.display_description_item[o.display_page_three,11] = "Pieza de Bucle de Vidrio 3"
o.display_description_item[o.display_page_three,12] = "Pieza de Bucle de Vidrio 4"
o.display_description_item[o.display_page_three,13] = "Rampa Larga de Vidrio 3"
o.display_description_item[o.display_page_three,14] = "Rampa Larga de Vidrio 4"
o.display_description_item[o.display_page_three,15] = "Rampa Corta de Vidrio 3"
o.display_description_item[o.display_page_three,16] = "Rampa Corta de Vidrio 4"
o.display_description_item[o.display_page_three,17] = "Ventana - Verde - Grande"
o.display_description_item[o.display_page_three,18] = "Ventana - Verde - Pequeña"
o.display_description_item[o.display_page_three,19] = "Ventana - Azul - Pequeña"

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Bucle de Riel - Superior Izquierdo"
o.display_description_item[o.display_page_four,1] = "Bucle de Riel - Superior Derecho"
o.display_description_item[o.display_page_four,2] = "Riel en Pendiente 1"
o.display_description_item[o.display_page_four,3] = "Riel en Pendiente 2"
o.display_description_item[o.display_page_four,4] = "Rampa de Riel - Izquierda"
o.display_description_item[o.display_page_four,5] = "Riel Recto 1"
o.display_description_item[o.display_page_four,6] = "Rampa de Riel - Derecha"
o.display_description_item[o.display_page_four,7] = "Bucle de Riel - Inferior Izquierdo"
o.display_description_item[o.display_page_four,8] = "Bucle de Riel - Inferior Derecho"
o.display_description_item[o.display_page_four,9] = "Rampa de Riel - Izquierdo - Rojo"
o.display_description_item[o.display_page_four,10] = "Rampa de Riel - Recto - Rojo"
o.display_description_item[o.display_page_four,11] = "Rampa de Riel - Derecho - Rojo"
o.display_description_item[o.display_page_four,12] = "Riel Recto - Madera"
o.display_description_item[o.display_page_four,13] = "Rampa de Riel - Izquierdo - Azul"
o.display_description_item[o.display_page_four,14] = "Rampa de Riel - Recto - Azul"
o.display_description_item[o.display_page_four,15] = "Rampa de Riel - Derecho - Azul"
o.display_description_item[o.display_page_four,16] = "Rampa de Riel - Derecho - Amarillo"
o.display_description_item[o.display_page_four,17] = "Rampa de Riel - Recto - Amarillo"
o.display_description_item[o.display_page_four,18] = "Rampa de Riel - Izquierdo - Amarillo"
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = "Riel Recto - Rojo 1"
o.display_description_item[o.display_page_five,1] = "Riel Recto - Azul 1"
o.display_description_item[o.display_page_five,2] = "Riel Recto - Amarillo 1"
o.display_description_item[o.display_page_five,3] = "Riel Recto - Rojo 2"
o.display_description_item[o.display_page_five,4] = "Riel Recto - Azul 2"
o.display_description_item[o.display_page_five,5] = "Riel Recto - Amarillo 2"
o.display_description_item[o.display_page_five,6] = ""
o.display_description_item[o.display_page_five,7] = "Riel Recto - Rojo 3"
o.display_description_item[o.display_page_five,8] = "Riel Recto - Rojo 4"
o.display_description_item[o.display_page_five,9] = "Riel Recto - Amarillo 3"
o.display_description_item[o.display_page_five,10] = "Riel Recto - Amarillo 4"
o.display_description_item[o.display_page_five,11] = "Riel Recto - Azul 3"
o.display_description_item[o.display_page_five,12] = "Riel Recto - Azul 4"
o.display_description_item[o.display_page_five,13] = ""
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = "Ambiente - Reiniciar Zoom de Camara"
o.display_description_item[o.display_page_six,1] = "Ambiente - Zoom de Camara al 50 Porciento"
o.display_description_item[o.display_page_six,2] = "Ambiente - Zoom de Camara al 25 Porciento"
o.display_description_item[o.display_page_six,3] = "Riel 11"
o.display_description_item[o.display_page_six,4] = "Riel 12"
o.display_description_item[o.display_page_six,5] = "Señal de Via Oeste"
o.display_description_item[o.display_page_six,6] = "Señal en Blanco"
o.display_description_item[o.display_page_six,7] = "Señal de Flecha"
o.display_description_item[o.display_page_six,8] = "Papelera de Reciclaje"
o.display_description_item[o.display_page_six,9] = "Semáforo"
o.display_description_item[o.display_page_six,10] = "Poste de Luz"
o.display_description_item[o.display_page_six,11] = "Poste 1"
o.display_description_item[o.display_page_six,12] = "Poste 2"
o.display_description_item[o.display_page_six,13] = "Poste 3"
o.display_description_item[o.display_page_six,14] = "Arbusto"
o.display_description_item[o.display_page_six,15] = "Berenjena Única"
o.display_description_item[o.display_page_six,16] = "Tendedero"
o.display_description_item[o.display_page_six,17] = "Señal de Cruce de Peatones"
o.display_description_item[o.display_page_six,18] = "Señal de Peatones"
o.display_description_item[o.display_page_six,19] = "Cesto de Basura"

