///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Platforms"
o.display_page_description[1] = "Scenery"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Cieńka Ściana"
o.display_description_item[o.display_page_one,1] = "Czerwony Dywan"
o.display_description_item[o.display_page_one,2] = "Duża Ściana"
o.display_description_item[o.display_page_one,3] = "Trawiasta Podłoga 1"
o.display_description_item[o.display_page_one,4] = "Trawiasta Podłoga 2"
o.display_description_item[o.display_page_one,5] = "Trawiasta Podłoga 3"
o.display_description_item[o.display_page_one,6] = "Trawiasta Podłoga 4"
o.display_description_item[o.display_page_one,7] = "Emergency Ladder"
o.display_description_item[o.display_page_one,8] = "Unknown Tile"
o.display_description_item[o.display_page_one,9] = "Unknown Tile"
o.display_description_item[o.display_page_one,10] = "Unknown Tile"
o.display_description_item[o.display_page_one,11] = "Unknown Tile"
o.display_description_item[o.display_page_one,12] = "Unknown Tile"
o.display_description_item[o.display_page_one,13] = "Unknown Tile"
o.display_description_item[o.display_page_one,14] = "Unknown Tile"
o.display_description_item[o.display_page_one,15] = "Unknown Tile"
o.display_description_item[o.display_page_one,16] = "Unknown Tile"
o.display_description_item[o.display_page_one,17] = "Unknown Tile"
o.display_description_item[o.display_page_one,18] = "Unknown Tile"
o.display_description_item[o.display_page_one,19] = "Unknown Tile"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Pomnik Burmistrza Zao"
o.display_description_item[o.display_page_two,1] = "Końcówka Filaru"
o.display_description_item[o.display_page_two,2] = "Duża Ściana"
o.display_description_item[o.display_page_two,3] = "Szablon Sklepu"
o.display_description_item[o.display_page_two,4] = "Sklep z Promocjami"
o.display_description_item[o.display_page_two,5] = "Sklep z Wyprzedażą"
o.display_description_item[o.display_page_two,6] = "Sklep Bike World"
o.display_description_item[o.display_page_two,7] = "Drzewo"
o.display_description_item[o.display_page_two,8] = "Filar"
o.display_description_item[o.display_page_two,9] = "Wykończenie Ściany"
o.display_description_item[o.display_page_two,10] = "Ozdobny Panel 1"
o.display_description_item[o.display_page_two,11] = "Ozdobny Panel 2"
o.display_description_item[o.display_page_two,12] = "Ozdobny Panel 3"
o.display_description_item[o.display_page_two,13] = "Znak - Bike World"
o.display_description_item[o.display_page_two,14] = "Znak - Promocje"
o.display_description_item[o.display_page_two,15] = "Znak - Wyprzedaż"
o.display_description_item[o.display_page_two,16] = "Unknown Tile"
o.display_description_item[o.display_page_two,17] = "Unknown Tile"
o.display_description_item[o.display_page_two,18] = "Unknown Tile"
o.display_description_item[o.display_page_two,19] = "Unknown Tile"
