obj_game_logic.milla_jump_confirm_key      = 0   //Jump confirm key (Prevents iterative inputs)
obj_game_logic.milla_jump_press            = 0   //Have we pressed the jump key once?
obj_game_logic.milla_float_timer           = -1  //How long are we floating in the air?
obj_game_logic.milla_float_sound_timer     = 0   //How often should we repeat the flutter sound?
obj_game_logic.milla_float_acceleration    = 0   //How fast should we repeat the floating animation?
obj_game_logic.milla_digging               = 0   //Are we digging?
obj_game_logic.milla_digging_timer         = 0   //How long has it been since the last key press?
obj_game_logic.milla_digging_sound         = 0   //How often should we cycle through sound effects?
obj_game_logic.milla_digging_acceleration  = 0   //How fast should we repeat the digging animation?
obj_game_logic.milla_digging_tile_id       = -1  //Tile ID for dirt decoration tile
obj_game_logic.milla_digging_tile_stage    = 0   //How large is our decorative dirt tile?
obj_game_logic.milla_digging_direction     = 0   //Which direction is the player digging in?
obj_game_logic.milla_digging_prompt_timer  = 0   //How often should the digging prompt flash?
obj_game_logic.milla_digging_prompt_stop   = 0   //Should we stop reminding the player when they can dig?
obj_game_logic.milla_digging_x             = 0   //Should we stop reminding the player when they can dig?
obj_game_logic.milla_digging_y             = 0   //Should we stop reminding the player when they can dig?
obj_game_logic.milla_digging_index         = spr_milla_dirt_0 //Should we stop reminding the player when they can dig?
obj_game_logic.milla_special_key_lock      = 0   //Should we detect only one button press, instead of all of them?
obj_game_logic.milla_special_direction     = 0   //Which direction are we holding in?
obj_game_logic.milla_special_attack        = 0   //Are we attacking?
obj_game_logic.milla_special_shield_frame  = 0   //Animation frames for shield burst
obj_game_logic.milla_special_shield_angle  = 0   //What is the angle of our attack sprites?
obj_game_logic.milla_action_distance       = 0   //Animation offsets for attack sprites
obj_game_logic.milla_action_distance_param = 24  //Distance  offsets for attack sprites
obj_game_logic.milla_special_length_x1     = 0   //Point of origin for attack sprites
obj_game_logic.milla_special_length_y1     = 0   //Point of origin for attack sprites
obj_game_logic.milla_special_length_x2     = 0   //Point of origin for attack sprites
obj_game_logic.milla_special_length_y2     = 0   //Point of origin for attack sprites
//Which sprite does our phantom cube assume? (Allows changing the cube to "copies" of items)
obj_game_logic.milla_phantom_attack_sprite = spr_cube
obj_game_logic.milla_phantom_attack_frame  = 0   //Animation frames for phantom cube
obj_game_logic.milla_phantom_attack_frame2 = 0   //Animation frames for item attachments
obj_game_logic.milla_phantom_attack_frame3 = 0   //Animation frames for shield attachments
obj_game_logic.milla_phantom_attack_framed = 0   //Direction of animation frames for held gem flower
obj_game_logic.milla_phantom_attack_frames = 0   //Delay timer for the chest sprites
obj_game_logic.milla_phantom_length_x      = 0   //Point of origin for phantom cube sprites
obj_game_logic.milla_phantom_length_y      = 0   //Point of origin for phantom cube sprites
obj_game_logic.milla_phantom_cube_x        = 0   //Position X for remotely thrown cube sprites
obj_game_logic.milla_phantom_cube_y        = 0   //Position Y for remotely thrown cube sprites
obj_game_logic.milla_phantom_cube_angle    = 0   //Angle storage for remotely thrown cube sprites
obj_game_logic.milla_phantom_cube_offset   = 42  //Vertical offset for cube sprites
obj_game_logic.milla_phantom_cube_offset_x = -16 //Horizontal offset for item sprites
obj_game_logic.milla_phantom_cube_offset_y = 0   //Vertical offset for item sprites
obj_game_logic.milla_phantom_cube_walkset  = 0   //What Y position should the cube bob while walking or standing?
obj_game_logic.milla_phantom_cube_xdir     = 0   //What is our cube's facing direction?
obj_game_logic.milla_phantom_cube_collided = 0   //Has our cube collided with any terrain?
obj_game_logic.milla_phantom_cube_speed    = 0   //How fast is our cube flying?
obj_game_logic.milla_phantom_cube_gravity  = 0   //How fast is our cube falling?
obj_game_logic.milla_phantom_mode          = 0   //Are we holding a phantom cube?
obj_game_logic.milla_phantom_timer         = 0   //How long should the phantom cube take to spawn?
obj_game_logic.milla_phantom_cube_confirm  = 0   //Are we spawning a cube or an item?
obj_game_logic.milla_phantom_rocket_dog    = 0   //How fast are we allowed to fly?
obj_game_logic.milla_phantom_rocket_speed  = 0   //How fast are we flying?
obj_game_logic.milla_particle_frame        = -1  //Animation frames for explosion particle
obj_game_logic.milla_shield_x              = 0   //Position X for shield sprites of held item
obj_game_logic.milla_shield_y              = 0   //Position Y for shield sprites of held item
obj_game_logic.milla_shield_angle          = 0   //Angle for the shield sprites of held item
obj_game_logic.milla_orb_type              = 0   //Which type of orb are we spawning?
obj_game_logic.milla_gem_flower_particle   = 0   //Animatione frames for the gem flower's particle
obj_game_logic.milla_gem_flower_x          = 0   //X position for gem flower's particle
obj_game_logic.milla_gem_flower_x2         = 0   //X position of gem flower's particle
obj_game_logic.milla_gem_flower_y          = 0   //Y position of gem flower's particle
obj_game_logic.milla_gem_flower_z          = 0   //Z position of gem flower's particle
obj_game_logic.milla_bomb_frame_timer      = 0   //Animation timers for bomb
obj_game_logic.milla_bomb_frame_decay      = 14  //Animation timers decay
obj_game_logic.milla_bomb_create_x         = 0   //X position of created bomb
obj_game_logic.milla_bomb_create_y         = 0   //Y position of created bomb
obj_game_logic.flower_particle_x           = 0   //X position of gem flower's particle rotation
obj_game_logic.flower_particle_y           = 0   //X position of gem flower's particle rotation
obj_game_logic.milla_hang_bar_jump         = 0   //How many frames should we wait to enable floating?
obj_game_logic.milla_tail_sprite_frame     = 0   //Current frame of the tail's sprite
obj_game_logic.milla_tail_visible          = 0   //Visibility of the tail's sprite
obj_game_logic.milla_tail_x                = 0   //X position of the tail's sprite
obj_game_logic.milla_tail_y                = 0   //Y position of the tail's sprite
obj_game_logic.milla_tail_offset           = 16  //What Y position should the tail be, relative to the player's feet?
obj_game_logic.milla_tail_dir              = 0   //Which direction should the tail be facing?
obj_game_logic.milla_animation_speed_mod   = 0   //Modify animation speed based on horizontal speed
obj_game_logic.milla_flutter_block_trigger = 0   //Are we allowed to perform the flutter block?
obj_game_logic.milla_flutter_block_timer   = 0   //How long are we allowed to perform the flutter block?
obj_game_logic.milla_flutter_stamina_bar   = 65  //How long are we allowed to perform the flutter block?
obj_game_logic.milla_xdir                  = 1   //How long are we allowed to perform the flutter block?
obj_game_logic.milla_cube_override         = 0   //How long are we allowed to perform the flutter block?
obj_game_logic.milla_direction_override    = 0   //How long are we allowed to perform the flutter block?
obj_game_logic.milla_pause_logic           = 0
obj_game_logic.milla_item_id               = 0
obj_game_logic.fof_disable                 = 0   //Disable FOF collisions
obj_game_logic.milla_attack_skin = spr_cube
obj_game_logic.milla_attack_skin_allow = 0
obj_game_logic.milla_attack_skin_iterate = 0
obj_game_logic.milla_attack_bomb_cube_scale = 1
obj_game_logic.milla_attack_bomb_cube_pitch = milla_draw_bomb
obj_game_logic.milla_switch_button_timer = 0
obj_game_logic.sit = 0
obj_game_logic.sit_timer = 0
obj_game_logic.push_timer = 0
