///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Platforms"
o.display_page_description[1] = "Scenery"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Thin Wall Piece"
o.display_description_item[o.display_page_one,1] = "Red Carpet Floor"
o.display_description_item[o.display_page_one,2] = "Large Wall Piece"
o.display_description_item[o.display_page_one,3] = "Grass Floor 1"
o.display_description_item[o.display_page_one,4] = "Grass Floor 2"
o.display_description_item[o.display_page_one,5] = "Grass Floor 3"
o.display_description_item[o.display_page_one,6] = "Grass Floor 4"
o.display_description_item[o.display_page_one,7] = "Emergency Ladder"
o.display_description_item[o.display_page_one,8] = "Unknown Tile"
o.display_description_item[o.display_page_one,9] = "Unknown Tile"
o.display_description_item[o.display_page_one,10] = "Unknown Tile"
o.display_description_item[o.display_page_one,11] = "Unknown Tile"
o.display_description_item[o.display_page_one,12] = "Unknown Tile"
o.display_description_item[o.display_page_one,13] = "Unknown Tile"
o.display_description_item[o.display_page_one,14] = "Unknown Tile"
o.display_description_item[o.display_page_one,15] = "Unknown Tile"
o.display_description_item[o.display_page_one,16] = "Unknown Tile"
o.display_description_item[o.display_page_one,17] = "Unknown Tile"
o.display_description_item[o.display_page_one,18] = "Unknown Tile"
o.display_description_item[o.display_page_one,19] = "Unknown Tile"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Mayor Zao Statue"
o.display_description_item[o.display_page_two,1] = "Pillar End Cap"
o.display_description_item[o.display_page_two,2] = "Large Wall"
o.display_description_item[o.display_page_two,3] = "Shop Template"
o.display_description_item[o.display_page_two,4] = "Promtional Sale Shop"
o.display_description_item[o.display_page_two,5] = "Clearance Sale Shop"
o.display_description_item[o.display_page_two,6] = "Bike World Shop"
o.display_description_item[o.display_page_two,7] = "Tree"
o.display_description_item[o.display_page_two,8] = "Pillar"
o.display_description_item[o.display_page_two,9] = "Wall Trimming"
o.display_description_item[o.display_page_two,10] = "Scenery Panel 1"
o.display_description_item[o.display_page_two,11] = "Scenery Panel 2"
o.display_description_item[o.display_page_two,12] = "Scenery Panel 3"
o.display_description_item[o.display_page_two,13] = "Bike World Sign"
o.display_description_item[o.display_page_two,14] = "Promotional Sign"
o.display_description_item[o.display_page_two,15] = "Clearance Sale Sign"
o.display_description_item[o.display_page_two,16] = "Unknown Tile"
o.display_description_item[o.display_page_two,17] = "Unknown Tile"
o.display_description_item[o.display_page_two,18] = "Unknown Tile"
o.display_description_item[o.display_page_two,19] = "Unknown Tile"
