switch(argument0)
    {
        case spr_ladder_0:  {return 1; break;}
        case spr_ladder_1:  {return 1; break;}
        case spr_ladder_2:  {return 1; break;}
        case spr_ladder_3:  {return 1; break;}
        case spr_ladder_4:  {return 1; break;}
        case spr_ladder_5:  {return 1; break;}
        case spr_hangbar_0: {return 1; break;}
        case spr_hangbar_1: {return 1; break;}
        case spr_hangbar_2: {return 1; break;}
        case spr_hangbar_3: {return 1; break;}
        case spr_hangbar_4: {return 1; break;}
        case wd_fof_0:      {return 1; break;}
        case wd_fof_1:      {return 1; break;}
        case wd_fof_2:      {return 1; break;}
        case wd_fof_3:      {return 1; break;}
        case wd_fof_4:      {return 1; break;}
        case mu_fof_10:     {return 1; break;}
        case mnt_fof_0:     {return 1; break;}
        case mnt_fof_1:     {return 1; break;}
        case mnt_fof_2:     {return 1; break;}
        case mnt_fof_3:     {return 1; break;}
        case mnt_fof_4:     {return 1; break;}
        case cs_slope_0:     {return 1; break;}
        case cs_slope_1:     {return 1; break;}
        case cs_slope_2:     {return 1; break;}
        case cs_slope_3:     {return 1; break;}
        case cs_slope_alt_0: {return 1; break;}
        case cs_slope_alt_1: {return 1; break;}
        case cs_slope_alt_2: {return 1; break;}
        case ll_slope_0:    {return 1; break;}
        case ll_slope_1:    {return 1; break;}
        case ll_slope_2:    {return 1; break;}
        case ll_slope_3:    {return 1; break;}
        case ll_slope_24:   {return 1; break;}
        case ll_slope_25:   {return 1; break;}
        case ll_slope_26:   {return 1; break;}
        case ll_slope_27:   {return 1; break;}
        case ll_slope_28:   {return 1; break;}
        case ll_slope_29:   {return 1; break;}
        case ll_slope_30:   {return 1; break;}
        case ll_slope_31:   {return 1; break;}
        case ll_slope_32:   {return 1; break;}
        case ll_slope_33:   {return 1; break;}
        case ll_slope_34:   {return 1; break;}
        case ll_slope_35:   {return 1; break;}
        case ll_slope_36:   {return 1; break;}
        case spr_dirt_0:    {return 1; break;}
        case rg_rail_0:     {return 1; break;}
        case rg_rail_1:     {return 1; break;}
        case rg_rail_12:    {return 1; break;}
        case rg_rail_15:    {return 1; break;}
        case tile_ramp_1:   {return 1; break;}
        case tile_ramp_2:   {return 1; break;}
        case ll_slope_43:   {return 1; break;}
        case ll_slope_44:   {return 1; break;}
        default: {return 0; break;}
    }
