//Save Data Player 1
player_gems[0]                = real(ini_read_string("save_file_1","player_gems",0))
player_shards[0]              = real(ini_read_string("save_file_1","player_shards",0))
player_bosses[0]              = real(ini_read_string("save_file_1","player_bosses_defeated",0))
player_hub[0]                 = ini_read_string("save_file_1","player_hub","WestDistrictHub01.map")
player_skin[0]                = real(ini_read_string("save_file_1","player_skin",0))
player_play_time[0]           = real(ini_read_string("save_file_1","player_time",0))
player_world_state[0]         = real(ini_read_string("save_file_1","world_state",0))
player_temple_hub_5_check[0]  = real(ini_read_string("save_file_1","player_temple_hub_5_check",0))
potion_petal_potion_save[0]   = real(ini_read_string("save_file_1","potion_petal_potion",0))
potion_petal_core_save[0]     = real(ini_read_string("save_file_1","potion_petal_core",0))
potion_stamina_drink_save[0]  = real(ini_read_string("save_file_1","potion_stamina_drink",0))
potion_stamina_core_save[0]   = real(ini_read_string("save_file_1","potion_stamina_core",0))
potion_feather_potion_save[0] = real(ini_read_string("save_file_1","potion_feather_potion",0))
potion_mystery_potion_save[0] = real(ini_read_string("save_file_1","potion_mystery_potion",0))

//Save Data Player 2
player_gems[1]                = real(ini_read_string("save_file_2","player_gems",0))
player_shards[1]              = real(ini_read_string("save_file_2","player_shards",0))
player_bosses[1]              = real(ini_read_string("save_file_2","player_bosses_defeated",0))
player_hub[1]                 = ini_read_string("save_file_2","player_hub","WestDistrictHub01.map")
player_skin[1]                = real(ini_read_string("save_file_2","player_skin",0))
player_play_time[1]           = real(ini_read_string("save_file_2","player_time",0))
player_world_state[1]         = real(ini_read_string("save_file_2","world_state",0))
player_temple_hub_5_check[1]  = real(ini_read_string("save_file_2","player_temple_hub_5_check",0))
potion_petal_potion_save[1]   = real(ini_read_string("save_file_2","potion_petal_potion",0))
potion_petal_core_save[1]     = real(ini_read_string("save_file_2","potion_petal_core",0))
potion_stamina_drink_save[1]  = real(ini_read_string("save_file_2","potion_stamina_drink",0))
potion_stamina_core_save[1]   = real(ini_read_string("save_file_2","potion_stamina_core",0))
potion_feather_potion_save[1] = real(ini_read_string("save_file_2","potion_feather_potion",0))
potion_mystery_potion_save[1] = real(ini_read_string("save_file_2","potion_mystery_potion",0))

//Save Data Player 3
player_gems[2]                = real(ini_read_string("save_file_3","player_gems",0))
player_shards[2]              = real(ini_read_string("save_file_3","player_shards",0))
player_bosses[2]              = real(ini_read_string("save_file_3","player_bosses_defeated",0))
player_hub[2]                 = ini_read_string("save_file_3","player_hub","WestDistrictHub01.map")
player_skin[2]                = real(ini_read_string("save_file_3","player_skin",0))
player_play_time[2]           = real(ini_read_string("save_file_3","player_time",0))
player_world_state[2]         = real(ini_read_string("save_file_3","world_state",0))
player_temple_hub_5_check[2]  = real(ini_read_string("save_file_3","player_temple_hub_5_check",0))
potion_petal_potion_save[2]   = real(ini_read_string("save_file_3","potion_petal_potion",0))
potion_petal_core_save[2]     = real(ini_read_string("save_file_3","potion_petal_core",0))
potion_stamina_drink_save[2]  = real(ini_read_string("save_file_3","potion_stamina_drink",0))
potion_stamina_core_save[2]   = real(ini_read_string("save_file_3","potion_stamina_core",0))
potion_feather_potion_save[2] = real(ini_read_string("save_file_3","potion_feather_potion",0))
potion_mystery_potion_save[2] = real(ini_read_string("save_file_3","potion_mystery_potion",0))

//Save Data Player 4
player_gems[3]                = real(ini_read_string("save_file_4","player_gems",0))
player_shards[3]              = real(ini_read_string("save_file_4","player_shards",0))
player_bosses[3]              = real(ini_read_string("save_file_4","player_bosses_defeated",0))
player_hub[3]                 = ini_read_string("save_file_4","player_hub","WestDistrictHub01.map")
player_skin[3]                = real(ini_read_string("save_file_4","player_skin",0))
player_play_time[3]           = real(ini_read_string("save_file_4","player_time",0))
player_world_state[3]         = real(ini_read_string("save_file_4","world_state",0))
player_temple_hub_5_check[3]  = real(ini_read_string("save_file_4","player_temple_hub_5_check",0))
potion_petal_potion_save[3]   = real(ini_read_string("save_file_4","potion_petal_potion",0))
potion_petal_core_save[3]     = real(ini_read_string("save_file_4","potion_petal_core",0))
potion_stamina_drink_save[3]  = real(ini_read_string("save_file_4","potion_stamina_drink",0))
potion_stamina_core_save[3]   = real(ini_read_string("save_file_4","potion_stamina_core",0))
potion_feather_potion_save[3] = real(ini_read_string("save_file_4","potion_feather_potion",0))
potion_mystery_potion_save[3] = real(ini_read_string("save_file_4","potion_mystery_potion",0))

//Save Data Player 5
player_gems[12]                = real(ini_read_string("save_file_5","player_gems",0))
player_shards[12]              = real(ini_read_string("save_file_5","player_shards",0))
player_bosses[12]              = real(ini_read_string("save_file_5","player_bosses_defeated",0))
player_hub[12]                 = ini_read_string("save_file_5","player_hub","WestDistrictHub01.map")
player_skin[12]                = real(ini_read_string("save_file_5","player_skin",0))
player_play_time[12]           = real(ini_read_string("save_file_5","player_time",0))
player_world_state[12]         = real(ini_read_string("save_file_5","world_state",0))
player_temple_hub_5_check[12]  = real(ini_read_string("save_file_5","player_temple_hub_5_check",0))
potion_petal_potion_save[12]   = real(ini_read_string("save_file_5","potion_petal_potion",0))
potion_petal_core_save[12]     = real(ini_read_string("save_file_5","potion_petal_core",0))
potion_stamina_drink_save[12]  = real(ini_read_string("save_file_5","potion_stamina_drink",0))
potion_stamina_core_save[12]   = real(ini_read_string("save_file_5","potion_stamina_core",0))
potion_feather_potion_save[12] = real(ini_read_string("save_file_5","potion_feather_potion",0))
potion_mystery_potion_save[12] = real(ini_read_string("save_file_5","potion_mystery_potion",0))

//Save Data Player 6
player_gems[5]                = real(ini_read_string("save_file_6","player_gems",0))
player_shards[5]              = real(ini_read_string("save_file_6","player_shards",0))
player_bosses[5]              = real(ini_read_string("save_file_6","player_bosses_defeated",0))
player_hub[5]                 = ini_read_string("save_file_6","player_hub","WestDistrictHub01.map")
player_skin[5]                = real(ini_read_string("save_file_6","player_skin",0))
player_play_time[5]           = real(ini_read_string("save_file_6","player_time",0))
player_world_state[5]         = real(ini_read_string("save_file_6","world_state",0))
player_temple_hub_5_check[5]  = real(ini_read_string("save_file_6","player_temple_hub_5_check",0))
potion_petal_potion_save[5]   = real(ini_read_string("save_file_6","potion_petal_potion",0))
potion_petal_core_save[5]     = real(ini_read_string("save_file_6","potion_petal_core",0))
potion_stamina_drink_save[5]  = real(ini_read_string("save_file_6","potion_stamina_drink",0))
potion_stamina_core_save[5]   = real(ini_read_string("save_file_6","potion_stamina_core",0))
potion_feather_potion_save[5] = real(ini_read_string("save_file_6","potion_feather_potion",0))
potion_mystery_potion_save[5] = real(ini_read_string("save_file_6","potion_mystery_potion",0))

//Classic Mode Saves

//Save Data Player 1
player_gems[6]                = real(ini_read_string("save_file_7","player_gems",0))
player_shards[6]              = real(ini_read_string("save_file_7","player_shards",0))
player_bosses[6]              = real(ini_read_string("save_file_7","player_bosses_defeated",0))
player_hub[6]                 = ini_read_string("save_file_7","player_stage","WestDistrict01.map")
player_skin[6]                = real(ini_read_string("save_file_7","player_skin",0))
player_play_time[6]           = real(ini_read_string("save_file_7","player_time",0))
potion_petal_potion_save[6]   = real(ini_read_string("save_file_7","potion_petal_potion",0))
potion_petal_core_save[6]     = real(ini_read_string("save_file_7","potion_petal_core",0))
potion_stamina_drink_save[6]  = real(ini_read_string("save_file_7","potion_stamina_drink",0))
potion_stamina_core_save[6]   = real(ini_read_string("save_file_7","potion_stamina_core",0))
potion_feather_potion_save[6] = real(ini_read_string("save_file_7","potion_feather_potion",0))
potion_mystery_potion_save[6] = real(ini_read_string("save_file_7","potion_mystery_potion",0))

//Save Data Player 2
player_gems[7]                = real(ini_read_string("save_file_8","player_gems",0))
player_shards[7]              = real(ini_read_string("save_file_8","player_shards",0))
player_bosses[7]              = real(ini_read_string("save_file_8","player_bosses_defeated",0))
player_hub[7]                 = ini_read_string("save_file_8","player_stage","WestDistrict01.map")
player_skin[7]                = real(ini_read_string("save_file_8","player_skin",0))
player_play_time[7]           = real(ini_read_string("save_file_8","player_time",0         ))
potion_petal_potion_save[7]   = real(ini_read_string("save_file_8","potion_petal_potion",0))
potion_petal_core_save[7]     = real(ini_read_string("save_file_8","potion_petal_core",0))
potion_stamina_drink_save[7]  = real(ini_read_string("save_file_8","potion_stamina_drink",0))
potion_stamina_core_save[7]   = real(ini_read_string("save_file_8","potion_stamina_core",0))
potion_feather_potion_save[7] = real(ini_read_string("save_file_8","potion_feather_potion",0))
potion_mystery_potion_save[7] = real(ini_read_string("save_file_8","potion_mystery_potion",0))

//Save Data Player 3
player_gems[8]                = real(ini_read_string("save_file_9","player_gems",0))
player_shards[8]              = real(ini_read_string("save_file_9","player_shards",0))
player_bosses[8]              = real(ini_read_string("save_file_9","player_bosses_defeated",0))
player_hub[8]                 = ini_read_string("save_file_9","player_stage","WestDistrict01.map")
player_skin[8]                = real(ini_read_string("save_file_9","player_skin",0))
player_play_time[8]           = real(ini_read_string("save_file_9","player_time",0))
potion_petal_potion_save[8]   = real(ini_read_string("save_file_9","potion_petal_potion",0))
potion_petal_core_save[8]     = real(ini_read_string("save_file_9","potion_petal_core",0))
potion_stamina_drink_save[8]  = real(ini_read_string("save_file_9","potion_stamina_drink",0))
potion_stamina_core_save[8]   = real(ini_read_string("save_file_9","potion_stamina_core",0))
potion_feather_potion_save[8] = real(ini_read_string("save_file_9","potion_feather_potion",0))
potion_mystery_potion_save[8] = real(ini_read_string("save_file_9","potion_mystery_potion",0))

//Save Data Player 4
player_gems[9]                = real(ini_read_string("save_file_10","player_gems",0))
player_shards[9]              = real(ini_read_string("save_file_10","player_shards",0))
player_bosses[9]              = real(ini_read_string("save_file_10","player_bosses_defeated",0))
player_hub[9]                 = ini_read_string("save_file_10","player_stage","WestDistrict01.map")
player_skin[9]                = real(ini_read_string("save_file_10","player_skin",0))
player_play_time[9]           = real(ini_read_string("save_file_10","player_time",0))
potion_petal_potion_save[9]   = real(ini_read_string("save_file_10","potion_petal_potion",0))
potion_petal_core_save[9]     = real(ini_read_string("save_file_10","potion_petal_core",0))
potion_stamina_drink_save[9]  = real(ini_read_string("save_file_10","potion_stamina_drink",0))
potion_stamina_core_save[9]   = real(ini_read_string("save_file_10","potion_stamina_core",0))
potion_feather_potion_save[9] = real(ini_read_string("save_file_10","potion_feather_potion",0))
potion_mystery_potion_save[9] = real(ini_read_string("save_file_10","potion_mystery_potion",0))

//Save Data Player 5
player_gems[10]                = real(ini_read_string("save_file_11","player_gems",0))
player_shards[10]              = real(ini_read_string("save_file_11","player_shards",0))
player_bosses[10]              = real(ini_read_string("save_file_11","player_bosses_defeated",0))
player_hub[10]                 = ini_read_string("save_file_11","player_stage","WestDistrict01.map")
player_skin[10]                = real(ini_read_string("save_file_11","player_skin",0))
player_play_time[10]           = real(ini_read_string("save_file_11","player_time",0))
potion_petal_potion_save[10]   = real(ini_read_string("save_file_11","potion_petal_potion",0))
potion_petal_core_save[10]     = real(ini_read_string("save_file_11","potion_petal_core",0))
potion_stamina_drink_save[10]  = real(ini_read_string("save_file_11","potion_stamina_drink",0))
potion_stamina_core_save[10]   = real(ini_read_string("save_file_11","potion_stamina_core",0))
potion_feather_potion_save[10] = real(ini_read_string("save_file_11","potion_feather_potion",0))
potion_mystery_potion_save[10] = real(ini_read_string("save_file_11","potion_mystery_potion",0))

//Save Data Player 6
player_gems[11]                = real(ini_read_string("save_file_12","player_gems",0))
player_shards[11]              = real(ini_read_string("save_file_12","player_shards",0))
player_bosses[11]              = real(ini_read_string("save_file_12","player_bosses_defeated",0))
player_hub[11]                 = ini_read_string("save_file_12","player_stage","WestDistrict01.map")
player_skin[11]                = real(ini_read_string("save_file_12","player_skin",0))
player_play_time[11]           = real(ini_read_string("save_file_12","player_time",0))
potion_petal_potion_save[11]   = real(ini_read_string("save_file_12","potion_petal_potion",0))
potion_petal_core_save[11]     = real(ini_read_string("save_file_12","potion_petal_core",0))
potion_stamina_drink_save[11]  = real(ini_read_string("save_file_12","potion_stamina_drink",0))
potion_stamina_core_save[11]   = real(ini_read_string("save_file_12","potion_stamina_core",0))
potion_feather_potion_save[11] = real(ini_read_string("save_file_12","potion_feather_potion",0))
potion_mystery_potion_save[11] = real(ini_read_string("save_file_12","potion_mystery_potion",0))

//Time Attack Mode Data
player_best_time[0]  = ini_read_string("save_time_attack","stage_0","600000")
player_best_time[1]  = ini_read_string("save_time_attack","stage_1","600000")
player_best_time[2]  = ini_read_string("save_time_attack","stage_2","600000")
player_best_time[3]  = ini_read_string("save_time_attack","stage_3","600000")
player_best_time[4]  = ini_read_string("save_time_attack","stage_4","600000")
player_best_time[5]  = ini_read_string("save_time_attack","stage_5","600000")
player_best_time[6]  = ini_read_string("save_time_attack","stage_6","600000")
player_best_time[7]  = ini_read_string("save_time_attack","stage_7","600000")
player_best_time[8]  = ini_read_string("save_time_attack","stage_8","600000")
player_best_time[9]  = ini_read_string("save_time_attack","stage_9","600000")
player_best_time[10] = ini_read_string("save_time_attack","stage_10","600000")
player_best_time[11] = ini_read_string("save_time_attack","stage_11","600000")

player_best_crystals_count = 0
player_best_crystals[0]  = ini_read_string("save_time_attack","stage_0_gems","0")
player_best_crystals[1]  = ini_read_string("save_time_attack","stage_1_gems","0")
player_best_crystals[2]  = ini_read_string("save_time_attack","stage_2_gems","0")
player_best_crystals[3]  = ini_read_string("save_time_attack","stage_3_gems","0")
player_best_crystals[4]  = ini_read_string("save_time_attack","stage_4_gems","0")
player_best_crystals[5]  = ini_read_string("save_time_attack","stage_5_gems","0")
player_best_crystals[6]  = ini_read_string("save_time_attack","stage_6_gems","0")
player_best_crystals[7]  = ini_read_string("save_time_attack","stage_7_gems","0")
player_best_crystals[8]  = ini_read_string("save_time_attack","stage_8_gems","0")
player_best_crystals[9]  = ini_read_string("save_time_attack","stage_9_gems","0")
player_best_crystals[10] = ini_read_string("save_time_attack","stage_10_gems","0")
player_best_crystals[11] = ini_read_string("save_time_attack","stage_11_gems","0")
