///Shang Mu Temple Tile Definition Table
var o = obj_level_editor;

//Page Descriptions
o.display_page_description[0] = "Plataformas"
o.display_page_description[1] = "Paredes"
o.display_page_description[2] = "Rampas"
o.display_page_description[3] = "Cenário"
o.display_page_description[4] = "Extras"
o.display_page_description[5] = "???"

//Tile Descriptions (Page 1)
o.display_description_item[o.display_page_one,0] = "Painel(Chão) 1"
o.display_description_item[o.display_page_one,1] = "Painel(Chão) 2"
o.display_description_item[o.display_page_one,2] = "Painel(Chão) 3"
o.display_description_item[o.display_page_one,3] = "Peça da Ponte 1"
o.display_description_item[o.display_page_one,4] = "Peça da Ponte 2"
o.display_description_item[o.display_page_one,5] = "Peça da Ponte 3"
o.display_description_item[o.display_page_one,6] = "Peça da Ponte 4"
o.display_description_item[o.display_page_one,7] = "Painel(Parede) 1"
o.display_description_item[o.display_page_one,8] = "Painel(Parede) 2"
o.display_description_item[o.display_page_one,9] = "Painel(Parede) 3"
o.display_description_item[o.display_page_one,10] = "Peça da Ponte 5"
o.display_description_item[o.display_page_one,11] = "Painel(Parede) 4"
o.display_description_item[o.display_page_one,12] = "Peça da Ponte 6"
o.display_description_item[o.display_page_one,13] = "Painel(Teto) 1"
o.display_description_item[o.display_page_one,14] = "Painel(Teto) 2"
o.display_description_item[o.display_page_one,15] = "Painel(Teto) 3"
o.display_description_item[o.display_page_one,16] = "Painel(Interno) 1"
o.display_description_item[o.display_page_one,17] = "Painel(Interno) 2"
o.display_description_item[o.display_page_one,18] = "Painel(Interno) 3"
o.display_description_item[o.display_page_one,19] = "Painel(Interno) 4"

//Tile Descriptions (Page 2)
o.display_description_item[o.display_page_two,0] = "Painel(Parede) 4"
o.display_description_item[o.display_page_two,1] = "Painel(Parede) 5"
o.display_description_item[o.display_page_two,2] = "Painel(Parede) 6"
o.display_description_item[o.display_page_two,3] = "Ventilador Gigante"
o.display_description_item[o.display_page_two,4] = "Painel(Parede) 7"
o.display_description_item[o.display_page_two,5] = "Painel(Parede) 8"
o.display_description_item[o.display_page_two,6] = "Painel(Parede) 7"
o.display_description_item[o.display_page_two,7] = "Viga de Suporte 1"
o.display_description_item[o.display_page_two,8] = "Viga de Suporte 2"
o.display_description_item[o.display_page_two,9] = "Viga de Suporte 3"
o.display_description_item[o.display_page_two,10] = ""
o.display_description_item[o.display_page_two,11] = ""
o.display_description_item[o.display_page_two,12] = ""
o.display_description_item[o.display_page_two,13] = ""
o.display_description_item[o.display_page_two,14] = ""
o.display_description_item[o.display_page_two,15] = ""
o.display_description_item[o.display_page_two,16] = ""
o.display_description_item[o.display_page_two,17] = ""
o.display_description_item[o.display_page_two,18] = ""
o.display_description_item[o.display_page_two,19] = ""

//Tile Descriptions (Page 3)
o.display_description_item[o.display_page_three,0] = "Painel(Inclinado) 1"
o.display_description_item[o.display_page_three,1] = "Painel(Inclinado) 2"
o.display_description_item[o.display_page_three,2] = "Ponte(Rampa) 1"
o.display_description_item[o.display_page_three,3] = "Ponte(Rampa) 2"
o.display_description_item[o.display_page_three,4] = "Plataforma Flutuante 1"
o.display_description_item[o.display_page_three,5] = "Orbe Flutuante"
o.display_description_item[o.display_page_three,6] = "Orbe Rachado Flutuante"
o.display_description_item[o.display_page_three,7] = "Painel(Loop) 1"
o.display_description_item[o.display_page_three,8] = "Painel(Loop) 2"
o.display_description_item[o.display_page_three,9] = "Loop Exposto 1"
o.display_description_item[o.display_page_three,10] = "Loop Exposto 2"
o.display_description_item[o.display_page_three,11] = ""
o.display_description_item[o.display_page_three,12] = ""
o.display_description_item[o.display_page_three,13] = "Painel(Loop) 3"
o.display_description_item[o.display_page_three,14] = "Painel(Loop) 4"
o.display_description_item[o.display_page_three,15] = "Loop Exposto 3"
o.display_description_item[o.display_page_three,16] = "Loop Exposto 4"
o.display_description_item[o.display_page_three,17] = ""
o.display_description_item[o.display_page_three,18] = ""
o.display_description_item[o.display_page_three,19] = ""

//Tile Descriptions (Page 4)
o.display_description_item[o.display_page_four,0] = "Porta do Laboratório"
o.display_description_item[o.display_page_four,1] = "Disjuntor (Fechado)"
o.display_description_item[o.display_page_four,2] = "Disjuntor (Aberto)"
o.display_description_item[o.display_page_four,3] = "Caixa com Tralhas 1"
o.display_description_item[o.display_page_four,4] = "Placa E.P.C"
o.display_description_item[o.display_page_four,5] = "Caixa com Tralhas 2"
o.display_description_item[o.display_page_four,6] = "Estação de Trabalho"
o.display_description_item[o.display_page_four,7] = "Estação Base"
o.display_description_item[o.display_page_four,8] = "Estação de Wifi"
o.display_description_item[o.display_page_four,9] = "Drone Desligado"
o.display_description_item[o.display_page_four,10] = "Corrimão"
o.display_description_item[o.display_page_four,11] = ""
o.display_description_item[o.display_page_four,12] = ""
o.display_description_item[o.display_page_four,13] = ""
o.display_description_item[o.display_page_four,14] = ""
o.display_description_item[o.display_page_four,15] = ""
o.display_description_item[o.display_page_four,16] = ""
o.display_description_item[o.display_page_four,17] = ""
o.display_description_item[o.display_page_four,18] = ""
o.display_description_item[o.display_page_four,19] = ""

//Tile Descriptions (Page 5)
o.display_description_item[o.display_page_five,0] = ""
o.display_description_item[o.display_page_five,1] = ""
o.display_description_item[o.display_page_five,2] = ""
o.display_description_item[o.display_page_five,3] = ""
o.display_description_item[o.display_page_five,4] = ""
o.display_description_item[o.display_page_five,5] = ""
o.display_description_item[o.display_page_five,6] = ""
o.display_description_item[o.display_page_five,7] = ""
o.display_description_item[o.display_page_five,8] = ""
o.display_description_item[o.display_page_five,9] = ""
o.display_description_item[o.display_page_five,10] = ""
o.display_description_item[o.display_page_five,11] = ""
o.display_description_item[o.display_page_five,12] = ""
o.display_description_item[o.display_page_five,13] = ""
o.display_description_item[o.display_page_five,14] = ""
o.display_description_item[o.display_page_five,15] = ""
o.display_description_item[o.display_page_five,16] = ""
o.display_description_item[o.display_page_five,17] = ""
o.display_description_item[o.display_page_five,18] = ""
o.display_description_item[o.display_page_five,19] = ""

//Tile Descriptions (Page 6)
o.display_description_item[o.display_page_six,0] = ""
o.display_description_item[o.display_page_six,1] = ""
o.display_description_item[o.display_page_six,2] = ""
o.display_description_item[o.display_page_six,3] = ""
o.display_description_item[o.display_page_six,4] = ""
o.display_description_item[o.display_page_six,5] = ""
o.display_description_item[o.display_page_six,6] = ""
o.display_description_item[o.display_page_six,7] = ""
o.display_description_item[o.display_page_six,8] = ""
o.display_description_item[o.display_page_six,9] = ""
o.display_description_item[o.display_page_six,10] = ""
o.display_description_item[o.display_page_six,11] = ""
o.display_description_item[o.display_page_six,12] = ""
o.display_description_item[o.display_page_six,13] = ""
o.display_description_item[o.display_page_six,14] = ""
o.display_description_item[o.display_page_six,15] = ""
o.display_description_item[o.display_page_six,16] = ""
o.display_description_item[o.display_page_six,17] = ""
o.display_description_item[o.display_page_six,18] = ""
o.display_description_item[o.display_page_six,19] = ""

