//Language Array (Pause Menu); 0 = English; 1 = Portuguese; 2 = Polish; 3 = Spanish; 4 = German; 5 = Russian
lang_gui[0,0] = "Character Select"
lang_gui[0,1] = "Tutorial Stage"
lang_gui[0,2] = "Costumes"
lang_gui[0,3] = "Confirm"
lang_gui[0,4] = "Cancel"
lang_gui[0,5] = "Return"
lang_gui[0,6] = "Palettes"
//Portuguese
lang_gui[1,0] = "Selecionar Personagem"
lang_gui[1,1] = "Fase Tutorial"
lang_gui[1,2] = "Trajes"
lang_gui[1,3] = "Confirmar"
lang_gui[1,4] = "Cancelar"
lang_gui[1,5] = "Voltar"
lang_gui[1,6] = "Paletas"
//Polish
lang_gui[2,0] = "Wybór Postaci"
lang_gui[2,1] = "Samouczek"
lang_gui[2,2] = "Kostiumy"
lang_gui[2,3] = "Potwierdź"
lang_gui[2,4] = "Anuluj"
lang_gui[2,5] = "Wróć"
lang_gui[2,6] = "Paleta"
//Spanish
lang_gui[3,0] = "Seleccionar Personaje"
lang_gui[3,1] = "Nivel Tutorial"
lang_gui[3,2] = "Disfraces"
lang_gui[3,3] = "Confirmar"
lang_gui[3,4] = "Cancelar"
lang_gui[3,5] = "Volver"
lang_gui[3,6] = "Paleta"
//German
lang_gui[4,0] = "Charakterauswahl"
lang_gui[4,1] = "Tutorial Level"
lang_gui[4,2] = "Kostüme"
lang_gui[4,3] = "Bestät."
lang_gui[4,4] = "Abbrechen"
lang_gui[4,5] = "Zurück"
lang_gui[4,6] = "Farben"
//Russian
lang_gui[5,0] = "Выбери Персонажа"
lang_gui[5,1] = "Обучение"
lang_gui[5,2] = "Костюмы"
lang_gui[5,3] = "Выбор"
lang_gui[5,4] = "Отмена"
lang_gui[5,5] = "Назад"
lang_gui[5,6] = "Палитры"
